### ISSUE TITLE
Tracking Issue for `Iterator::array_chunks`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#100450]
Feature gate: `#![feature(iter_array_chunks)]`

This is a tracking issue for `Iterator::array_chunks`, an iterator adapter that allows to group elements of an iterator.

### Public API

```rust
// trait Iterator

fn array_chunks<const N: usize>(self) -> ArrayChunks<Self, N>
where
    Self: Sized,self);
```
```rust
// core::iter

pub struct ArrayChunks<I: Iterator, const N: usize> { ... }

impl<I, const N: usize> ArrayChunks<I, N> {
    pub fn into_remainder(self) -> Option<array::IntoIter<I::Item, N>>;
}

impl<I: Iterator, const N: usize> Iterator for ArrayChunks<I, N> {
    type Item = [I::Item; N];
}

impl<I: DoubleEndedIterator + ExactSizeIterator, const N: usize> DoubleEndedIterator for ArrayChunks<I, N> {}
impl<I: FusedIterator, const N: usize> FusedIterator for ArrayChunks<I, N> {}
impl<I: ExactSizeIterator, const N: usize> ExactSizeIterator for ArrayChunks<I, N> {}
```

### Steps / History

- [x] Implementation: #100026
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- [ ] Should `DoubleEndedIterator` be implemented?
  - Is there a use-case for this?
  - In order to yield the same items either way we require `ExactSizeIterator`
  - Note that `.rev().array_chunks()` and `.array_chunks().rev()` are different
  - If we decide to keep `DoubleEndedIterator` implementation should be improved
    - For example, maybe there should be `Iterator::next_chunk_back` like there is for forward
  - [ ] Is the `unwrap_err_unchecked` in `next_back_remainder` sound, despite not using `TrustedLen`?  (I didn't block the original PR on this because it goes through `take`, which I *think* we can trust, but I'd like someone smarter than me to think about it and confirm.)
- [ ] Should this be a type error for `N != 0`?  (See also this same question in `[T]::as_chunks`.)
- [ ] What's the tradeoff between the item type being `array::IntoIter<T, N>` and the current one where the items are `[T; N]` and there's a remainder?  (`[T]::array_chunks` has this question too and is unstable.)

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by the8472** [comment]
>  What's the tradeoff between the item type being array::IntoIter<T, N> and the current one where the items are [T; N] and there's a remainder?

It is definitely valuable to have a guaranteed, fixed length in the happy path. It aids vectorization and [known-length specialization](https://github.com/rust-lang/rust/blob/e8dc8bca2118ec1ed5970790614f0b81e9167f10/library/core/src/iter/adapters/flatten.rs#L257-L263). It could even help in-place iteration in shapes like `vec.into_iter().array_chunks().map(...).flatten().collect()`.

**Comment by rossmacarthur** [comment]
Might be good to align the naming of this function with `Iterator::next_chunk`, i.e. either 

- `Iterator::chunks`
- `Iterator::next_chunk`

Or

- `Iterator::array_chunks`
- `Iterator::next_array_chunk`

**Comment by camelid** [comment]
I think I'd vote for `Iterator::chunks` since arrays are a pretty clear fit for what this function accomplishes and `array_chunks` is a bit unwieldy.

**Comment by adamse** [comment]
It seems good to follow the same naming conventions as `slice::array_chunks` #74985 where possible?

**Comment by andria-dev** [comment]
I think that `Iterator::array_chunks` is fine, but not great. The simple present tense of the verb 'to chunk' (i.e. `Iterator::chunk`) could better indicate the **action** portion of organizing separate smaller units into single larger units. This should also avoid overriding the meaning of the plural noun 'chunks' as defined by `Itertools::chunks` (https://github.com/rust-lang/rust/pull/104969#issuecomment-1330804159). As for following the naming convention of `slice::array_chunks` (https://github.com/rust-lang/rust/issues/74985), it is also a nightly-only experimental API, so now should be a perfect time to change both as the above reasoning for using `chunk` applies there as well.

**Comment by SignalWhisperer** [comment]
I agree with @andria-dev. The name should also represent the action being performed. Most of the other iterator functions are action names (`map`, `fold`, `collect`, `count`, `advance_by`, etc.), but `array_chunks` is not an action. I much prefer `Iterator::chunk` as it better represents the action I am trying to perform.

**Comment by GnomedDev** [comment]
An interesting unresolved question was brought up in #116000, should ArrayChunks::into_remainder return Option?

**Comment by ronnodas** [comment]
I do not see the point of artificially converting an empty slice into a None, which needs to be unwrapped on use. Or semantically, it's not that the remainder is undefined, it just happens to be empty.

**Comment by WaffleLapkin** [comment]
One question that comes to mind looking at the API is why `into_remainder` returns an option? Couldn't it just return `array::IntoIter<I::Item, N>`, which is empty in case there is no remainder? (see also previous comments mentioning this and https://github.com/rust-lang/rust/issues/116000)

If there is a reason for the option, the documentation should explicitly say when the method returns `Some` or `None`.

**Comment by the8472** [comment]
We discussed this during a libs-api meeting. 

A major obstacle to stabilization is that this builds on `next_chunk` (#98326) which is also unstable and in its current API shape is likely not good for performance (vectorization, small N) of iterators consisting of nested adapters. And it also blows up stack space for large N.

That one likely needs an API redesign to become a lower-level API (e.g. by taking maybeuninit buffers) or compiler optimizations to make enums holding arrays have a more efficient return ABI.
