### ISSUE TITLE
Tracking Issue for `rustdoc::missing_doc_code_examples`

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#101730]
This is a tracking issue for the lint `rustdoc::missing_doc_code_examples`.
The feature gate for the issue is `#![feature(rustdoc_missing_doc_code_examples)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the lint https://github.com/rust-lang/rust/pull/54349
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions
* https://github.com/rust-lang/rust/issues/77230
* https://github.com/rust-lang/rust/issues/87858

### Implementation history

* https://github.com/rust-lang/rust/pull/54349
* https://github.com/rust-lang/rust/pull/74855
* https://github.com/rust-lang/rust/pull/75776
* https://github.com/rust-lang/rust/pull/76212
* https://github.com/rust-lang/rust/pull/76716
* https://github.com/rust-lang/rust/pull/80527
* https://github.com/rust-lang/rust/pull/88735
* https://github.com/rust-lang/rust/pull/88745
* https://github.com/rust-lang/rust/pull/90098

**Comment by jplatte** [comment]
If this lands, could there be a new lint group like `rustdoc::all` that activates all non-"restriction" rustdoc lints? All the current lints in from https://doc.rust-lang.org/rustdoc/lints.html are very useful to deny in CI, but this one obviously isn't (for most people).

**Comment by peter-kehl** [comment]
Please add #109592 and its PR (if accepted). And if you choose to look at that issue, please comment on the related question (item number 2).

**Comment by peter-kehl** [comment]
@jplatte FYI related to `rustdoc::all`
- #87858, and
- `rustdoc::all` in `src/librustdoc/lint.rs` -> `register_lints(...)`: https://github.com/rust-lang/rust/blob/master/src/librustdoc/lint.rs#L195.
