### ISSUE TITLE
Tracking Issue for De-RFC 3307: Remove type ascription

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#101728]
This supersedes https://github.com/rust-lang/rust/issues/23416

This is a tracking issue for the RFC "3307" (rust-lang/rfcs#3307).

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC:
    - [x] Remove type ascription from the parser and diagnostics
    - [ ] @rust-lang/compiler: Do y'all have a preference as to how far the removal should go? Unparseable AST nodes could be left in the code, for example (perhaps only instantiable by internal macro)
- [ ] Adjust documentation: Remove it from the unstable book
- [x] (No stabilization PR necessary)
- [ ] Remove the feature gate.

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

 - [ ] Should this be completely removed by the compiler, or left behind in a way that cannot be directly accessed through Rust syntax (or requires using a wrapper macro)?
 - [ ]

**Comment by Nilstrieb** [comment]
@rustbot claim

I'll remove all the parsing and diagnostic logic/hacks but leave the AST nodes and everything after it behind for now.

**Comment by RalfJung** [comment]
Would it make sense to possibly replace type ascription by an unstable macro in the standard library?
```rust
macro_rules! type_ascribe {
    ($e:expr, $t:ty) => {{
        let val: $t = $e;
        val
    }};
}
```
I noticed https://github.com/rust-lang/rust/pull/104614 added a magic macro that preserves the old semantics, but maybe we can implement this entirely in userland?

**Comment by bjorn3** [comment]
That macro shortens the lifetime of temporaries created in the expression.

**Comment by RalfJung** [comment]
That can be wrapped in a macro, of course:
```rust
pub fn type_ascribe<T>(value: T) -> T { value }

#[allow(unused_macros)]
macro_rules! type_ascribe {
    ($e:expr, $t:ty) => {type_ascribe::<$t>($e)};
}

pub fn main() {
    println!("{}", type_ascribe!(String::from("hello world").split_once(' '), _).unwrap().0)
}
```

**Comment by Nilstrieb** [comment]
This has taken a lot more time than I thought since lots of diagnostics were relying on it in subtle ways and require restructuring. I don't have enough time to work on this and also the other things I'm working on so I'm dropping my assignment here, feel free to take it. There's a WIP PR #106826 which may or may not be useful.
@estebank maybe you're interested in working on it, given all the pains you've had with type ascription :D
@rustbot release-assignment

**Comment by lcnr** [comment]
@chenyukang is there still something to do here after https://github.com/rust-lang/rust/pull/109128?

**Comment by chenyukang** [comment]
I will take a check in the following days, I remember there are still some macros left.
