### ISSUE TITLE
Tracking Issue for `feature(const_slice_split_at_mut)`

### ISSUE THREAD

**Issue by onestacked** [rust-lang/rust#101804]
Feature gate: `#![feature(const_slice_split_at_mut)]`

This is a tracking issue for spliting mutable slices in const context.

### Public API

```rust
// slice
pub const fn split_at_mut(&mut self, mid: usize) -> (&mut [T], &mut [T]);
pub const fn split_at_mut_unchecked(&mut self, mid: usize) -> (&mut [T], &mut [T]);
pub const fn split_at_mut_checked(&mut self, mid: usize) -> Option<(&mut [T], &mut [T])>;
```

### Steps / History

- [x] Implementation: #101800
- [x] https://github.com/rust-lang/rust/pull/124678
- [x] Wait for https://github.com/rust-lang/rust/issues/57349 to be stabilized.
- [ ] Wait for #130403 since from_raw_parts_mut is used internally
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR #130428

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by RalfJung** [comment]
@rust-lang/libs-api this should be ready for stabilization now, once const_mut_refs is stable. :)

**Comment by dtolnay** [comment]
@rfcbot fcp merge

`const` for these 2 already-stable functions:

- https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.split_at_mut
- https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.split_at_mut_unchecked

**Comment by okaneco** [comment]
`split_at_mut_checked`'s const stability was placed under this feature in #124678
https://doc.rust-lang.org/nightly/core/primitive.slice.html#method.split_at_mut_checked

**Comment by dtolnay** [comment]
Good call. Added it to the Public API description and the stabilization proposal.
