### ISSUE TITLE
Tracking Issue for keyword generics

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#102090]
This is a tracking issue for https://github.com/rust-lang/keyword-generics-initiative
The feature gate for the issue is `#![feature(keyword_generics)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC (@oli-obk is employed by aws to work on it, with regular reviews by @lcnr)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

* https://github.com/oli-obk/rust/tree/const_trait_take_two

**Comment by doivosevic** [comment]
whats the status of this?

**Comment by oli-obk** [comment]
This feature has been replaced by https://github.com/rust-lang/rust/issues/110395

**Comment by yoshuawuyts** [comment]
I think it's worth clarifying here that: yes, we're still working on effect generics. But to implement that as a language feature in the compiler we first have to generalize the `~const` feature to be able to be used with other keywords too. And in order to do *that*, we have to first remove the existing integration of `~const` and `impl const` from the stdlib. That's what https://github.com/rust-lang/rust/issues/110395 is tracking:

> This is a tracking issue for removing `impl const` and `~const` in the standard library. This is carried out so that migrating to a new implementation under keyword generics can go more smoothly. See [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/.60const.20Trait.60.20removal.20or.20rework) for discussion around this operation.

Despite `impl const` and `~const` being removed from the stdlib, they are still (experimentally) being developed as part of the language. The general tracking issue for this is the `#[feature(effects)]` gate. We expect that once the removal from the stdlib is complete, we'll be able to begin reworking the feature and probably gate + track features more granularly ([ref](https://github.com/rust-lang/rust/issues/110395#issuecomment-1526964326)):

> The removal is supposed to make it so that it is easier to land the better implementation. Therefore, the procedure is removal -> better implementation -> restoration. Removing after the better implementation makes no sense, since we'd still want to continue to experiment const traits until stabilization of a better syntax.

@FeldrinH Does that make sense?

**Comment by FeldrinH** [comment]
I see. I'm still a little confused about the current state of this work and what exactly https://github.com/rust-lang/rust/issues/110395 is meant to track. Is there a specific tracking issue for #[feature(effects)]? The list of steps under https://github.com/rust-lang/rust/issues/110395 seems to include a lot of steps that are related to the new implementation, rather than removing the old implementation. This seems to contradict the title and description of the issue, which talk only about removing features in the standard library.
