### ISSUE TITLE
Tracking issue for dyn-star

### ISSUE THREAD

**Issue by eholk** [rust-lang/rust#102425]
This issue tracks known issues or missing functionality with support for `dyn* Trait` objects. These are an experimental feature that are meant to support async function in dyn traits.

In addition to the issues linked here, you can also find things that need to be done by greping the code for `// FIXME(dyn-star)` or looking at the [F-dyn_star](https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+dyn-star+label%3AF-dyn_star) label.

- [x] https://github.com/rust-lang/rust/issues/102173
- [x] https://github.com/rust-lang/rust/issues/102172
- [x] https://github.com/rust-lang/rust/issues/102141
- [x] https://github.com/rust-lang/rust/issues/102427
- [x] https://github.com/rust-lang/rust/issues/102429
- [x] https://github.com/rust-lang/rust/issues/102430
- [x] https://github.com/rust-lang/rustfmt/issues/5542
- [x] https://github.com/rust-lang/rust/pull/134601
- [ ] https://github.com/rust-lang/rust/issues/104800
- [ ] `dyn` and `dyn*` should (probably?) have their TyKind representation split from one another -- #107908 was an attempt at this

## Associated PRs

- https://github.com/rust-lang/rust/pull/101212
- (list is incomplete)

## About this issue

This is a **lang-team experiment** -- there hasn't been an RFC for this functionality, we're exploring it both as a potential implementation detail and (more speculatively) a possible language feature in the future. You can read more about dyn* at [this blog post](https://smallcultfollowing.com/babysteps/blog/2022/03/29/dyn-can-we-make-dyn-sized/). 

Lang-team champion: @nikomatsakis

**Comment by RalfJung** [comment]
Currently the dynamic type hidden by `dyn*` is required to match `usize` in size and alignment. In principle it seems possible to allow smaller alignment, and possibly even smaller size (though in the latter case care has to be taken that the vtable always ends up at the same offset -- this would be easier if the vtable was the first component of the pair, not the 2nd). Are there plans to allow that?

**Comment by ds84182** [comment]
Right now you can actually place smaller size & align types with `dyn*` by stuffing it inside a `usize` with a little bit of `unsafe`. Due to the existing alignment requirements for the vtable ptr, it will always end up at the same offset as long as `size_of::<T>() <= size_of::<usize>() && align_of::<T>() <= align_of::<usize>()`.

**Comment by RalfJung** [comment]
> Due to the existing alignment requirements for the vtable ptr, it will always end up at the same offset as long as size_of::<T>() <= size_of::<usize>() && align_of::<T>() <= align_of::<usize>().

This is not true for `size_of::<T>() == 0`. Also, this assumes that for a `usize` (and pointers), `size == align`.

**Comment by ds84182** [comment]
> This is not true for `size_of::<T>() == 0`. Also, this assumes that for a `usize` (and pointers), `size == align`.

Ah, right. I guess a better way to describe the requirements is something like
```rust
union DynStarCompatible<T> {
  true_value: T,
  size_align: usize,
}
```
where `DynStarCompatible<T>` matches the size and align of `usize`.

**Comment by eholk** [comment]
> Currently the dynamic type hidden by `dyn*` is required to match `usize` in size and alignment. In principle it seems possible to allow smaller alignment, and possibly even smaller size (though in the latter case care has to be taken that the vtable always ends up at the same offset -- this would be easier if the vtable was the first component of the pair, not the 2nd). Are there plans to allow that?

Yes, this is something I would like to support.

**Comment by RalfJung** [comment]
From the initial PR:

> Note that this is never intended to become stable surface syntax for Rust, but rather dyn* is planned to be used as an implementation detail for async functions in dyn traits.

Honestly that seems like a shame -- this could be useful way beyond `async fn` I think. (But then there are other proposals that are [even more general](https://dev.to/cad97/dyn-doesnt-need-to-be-special-3ldm) so indeed stabilizing this particular one might be the wrong call.)

**Comment by l-Luna** [comment]
> From the initial PR:
> 
> > Note that this is never intended to become stable surface syntax for Rust, but rather dyn* is planned to be used as an implementation detail for async functions in dyn traits.
> 
> Honestly that seems like a shame -- this could be useful way beyond `async fn` I think. (But then there are other proposals that are [even more general](https://dev.to/cad97/dyn-doesnt-need-to-be-special-3ldm) so indeed stabilizing this particular one might be the wrong call.)

might be useful to point out that the post you linked intentionally ignores any non-`Box` types, considering them not useful for supporting `Pin`

**Comment by eholk** [comment]
> From the initial PR:
> 
> > Note that this is never intended to become stable surface syntax for Rust, but rather dyn* is planned to be used as an implementation detail for async functions in dyn traits.
> 
> Honestly that seems like a shame -- this could be useful way beyond `async fn` I think. (But then there are other proposals that are [even more general](https://dev.to/cad97/dyn-doesnt-need-to-be-special-3ldm) so indeed stabilizing this particular one might be the wrong call.)

Maybe "never" was too strong in the original PR. I think `dyn*` will likely turn out to be a more ergonomic version of `dyn`, so hopefully we can find a version that makes sense to make part of the surface language at some point. I think the point was we picked `dyn*` as a placeholder syntax that we didn't want to bikeshed just yet, and if the feature becomes part of Rust proper we'd probably do it under a different syntax.

**Comment by oxalica** [comment]
I doubt that if this needs to be a language feature instead of a library impl.
We can implement `dyn*` using `ptr_metadata`:
```rust
pub struct InlinedDyn<Dyn: Pointee<Metadata = ptr::DynMetadata<Dyn>> + ?Sized> {
    data: usize, // Or anything if you like, or even with a const generic size.
    metadata: ptr::DynMetadata<Dyn>,
    _marker: PhantomData<Dyn>,
}
impl<Dyn: Pointee<Metadata = ptr::DynMetadata<Dyn>> + ?Sized> InlinedDyn<Dyn> {
    pub fn new<T: Unsize<Dyn>>(value: T) -> Self;
}
impl<Dyn: Pointee<Metadata = ptr::DynMetadata<Dyn>> + ?Sized> ops::Deref for InlinedDyn<Dyn> {}
impl<Dyn: Pointee<Metadata = ptr::DynMetadata<Dyn>> + ?Sized> ops::DerefMut for InlinedDyn<Dyn> {}
```

Is there any feature I missed that cannot be implemented like this?

**Comment by bjorn3** [comment]
That doesn't allow coercing to `dyn*` or using it as receiver. It also doesn't allow an automatic `impl Trait for dyn* Trait` for every trait.

**Comment by compiler-errors** [comment]
Noting here (and left an unchecked checkbox above) that `dyn` and `dyn*` should (probably?) have their `TyKind` representation split from one another. #107908 was an attempt at this, but the PR got stale, and rebasing it would've probably been a pain.

**Comment by bjorn3** [comment]
> `Box<T>` doesn't do this also, but we are still able do make `Box<dyn FnOnce()>` work.

Through an unstable feature to allow unsized arguments that is. Not something that can be replicated by end users for other traits.

**Comment by eholk** [comment]
> > That doesn't allow coercing to `dyn*` or using it as receiver.
> 
> That's fair, but I still think a struct-like lang-item is more pretty, just like `Box<T>`. So we can more easily extend it with more methods or parameterized it with const-generic custom size or alignment.

For what it's worth, we consider `dyn*` to be a placeholder syntax while we develop the idea. If we were to stabilize something like as part of user-facing Rust, we'd probably spell it something like `Dyn<T>` instead.

**Comment by RalfJung** [comment]
> dyn and dyn* should (probably?) have their TyKind representation split from one another 

https://github.com/rust-lang/rust/pull/115699 o the side fixes yet another bug caused by those two being the same TyKind.

**Comment by davidtwco** [comment]
I've been looking at what it would take to make `-Csymbol-mangling-version=v0` our default this morning and a bunch of dyn-star tests fail with the v0 mangling - something to look into for whomever is working on this.
