### ISSUE TITLE
Tracking Issue for negation methods on `NonZeroI*`

### ISSUE THREAD

**Issue by jmillikin** [rust-lang/rust#102443]
Feature gate: `#![feature(nonzero_negation_ops)]`

This is a tracking issue for adding negation methods such as `wrapping_neg()` to the `core::num::NonZeroI{8,16,32,64,128}` types.

ACP: https://github.com/rust-lang/libs-team/issues/105

### Public API

```rust
// core::num

for $Ty in NonZeroI{8,16,32,64,128} {
	pub const fn is_positive(self) -> bool;
	pub const fn is_negative(self) -> bool;
	pub const fn checked_neg(self) -> Option<$Ty>;
	pub const fn overflowing_neg(self) -> ($Ty, bool);
	pub const fn saturating_neg(self) -> $Ty;
	pub const fn wrapping_neg(self) -> $Ty;
}
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/102342
- [x] #111186
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/111044

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by jmillikin** [comment]
(pinging someone from the libs team, per instructions at https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html)

@joshtriplett I'd like to start the FCP for this feature. The new methods have been in nightly since v1.66, and the the stabilization PR for `impl Neg` is now merged (https://github.com/rust-lang/rust/pull/102341).

**Comment by jmillikin** [comment]
Timed out waiting for someone to start the FCP -- since there's much much to discussion regarding the API (it just copies the primitive types), I sent in PR https://github.com/rust-lang/rust/pull/111044 to stabilize.

**Comment by Robbepop** [comment]
Sorry for being a bit late to the show but I just found this via TWIR.

What is the rational for leaving out an `is_positive` method? I know it is trivial to emulate via `!n.is_negative()` where `n: NonZeroIxx` but ...

- Rust primitive signed integers such as `i32` do have both methods.
- Using the aforementioned `!n.is_negative()` instead of `n.is_positive()` when needed can be considered bad style.

**Comment by jmillikin** [comment]
Thanks for the catch! I just didn't see that `is_positive()` existed. Created PR https://github.com/rust-lang/rust/pull/111186 to add it.
