### ISSUE TITLE
Tracking Issue for CStr::is_empty

### ISSUE THREAD

**Issue by jmillikin** [rust-lang/rust#102444]
Feature gate: `#![feature(cstr_is_empty)]`

This is a tracking issue for adding an `is_empty()` method to `core::ffi::CStr`.

ACP: https://github.com/rust-lang/libs-team/issues/106

### Public API

```rust
// core::ffi

impl CStr {
	pub const fn is_empty(&self) -> bool;
}
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/102445
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/111043

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by jmillikin** [comment]
Gentle ping for @rust-lang/libs-api -- would it be possible to start the FCP now? I don't think there's much API surface to review.

**Comment by jmillikin** [comment]
(pinging someone from the libs team, per instructions at https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html)

@cuviper I'd like to start the FCP for this feature. The new method has been in nightly since v1.66, and it'd be nice to have it in stable.

**Comment by jmillikin** [comment]
Timed out waiting for someone to start the FCP -- since there's much much to discussion regarding the API, I sent in PR https://github.com/rust-lang/rust/pull/111043 to stabilize.

**Comment by BurntSushi** [comment]
@rfcbot fcp merge

**Comment by BurntSushi** [comment]
@rust-lang/libs-api This issue is for stabilizing `CStr::is_empty`, which seems sensible. It returns true in precisely the cases where `CStr::to_bytes().is_empty()` returns true. One odd thing here is that there is no `CStr::len` method, but that can always be added in the future.

**Comment by BurntSushi** [comment]
@jmillikin Yes that makes sense. I just mean that it is somewhat odd from an API perspective. Usually if there's an `is_empty` and its a collection, then there's also a `len` method. And vice versa. I raise it as something that I find a little odd, but not a blocker for moving forward.

**Comment by madsmtm** [comment]
> Having a `len()` that iterates through the entire value seems surprising enough that it's worth its own ACP

But is this not also the case for `is_empty`? In the future, `is_empty` _would_ iterate through the entire value, which I think is just as surprising.

**Comment by chloekek** [comment]
is_empty just checks the first byte. No iteration necessary.

**Comment by madsmtm** [comment]
> is_empty just checks the first byte. No iteration necessary. That's why it's worth having in addition to len, as len == 0 would be linear time.

Right, didn't actually think that through.
