### ISSUE TITLE
Tracking Issue for MIR-only generator witness

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/rust#102805]
This is a tracking issue for the unstable option `-Zdrop-tracking-mir`.
This option changes how generator interior types are computed, to get the types from MIR instead of computing them on the HIR.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- [ ] the implementation currently marks all generator as requiring `Drop` to avoid query cycles;
- [ ] the implementation currently filters out "internal" locals for no good reason.

### Implementation history

Initial implementation: #101692
