### ISSUE TITLE
Tracking Issue for `String::leak`

### ISSUE THREAD

**Issue by finnbear** [rust-lang/rust#102929]
Feature gate: `#![feature(string_leak)]`

This is a tracking issue for `String::leak`

```rust
impl String {
    pub fn leak<'a>(self) -> &'a mut str {
        let me = self.into_bytes().leak();
        // Safety: Bytes from a [`String`] are valid utf8.
        unsafe { std::str::from_utf8_unchecked_mut(me) }
    }	
}
```

### Steps / History

- [x] ACP (https://github.com/rust-lang/libs-team/issues/109)
- [ ] Implementation: (pending; will PR soon)
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html
