### ISSUE TITLE
Tracking issue for `-Z instrument-xray`

### ISSUE THREAD

**Issue by ilammy** [rust-lang/rust#102921]
This is a tracking issue for `-Z instrument-xray` flag, enabling XRay instrumentation support.

- Docs: TBD
- MCP: rust-lang/compiler-team#561

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Get the MCP accepted 
  - [ ] need a second
  - [ ] need willling reviewers  
- [ ] Implement the feature
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- Do we want to stabilize this at all? That will be know after the unstable option sees some use.

### Implementation history

TBD

**Comment by csmoe** [comment]
https://maskray.me/blog/2023-06-18-port-llvm-xray-to-apple-systems xray was ported to mac recently, should we enable it on those targets?
