### ISSUE TITLE
Tracking issue for `-Zdwarf-version`

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#103057]
This is a tracking issue for the `-Zdwarf-version` unstable flag (no RFC/MCP) added in #98350 which allows selecting the specific version of DWARF to use when creating debuginfo. 

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [x] Initial implementation (#98350)
- [x] Wider Testing (tested on RfL)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide]) (#136926)
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide]) (#136926)

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/main/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [ ] Is the pre-compiled standard library (potentially) using a different version of DWARF an issue?
- [ ] What should the behavior of the flag do when the active target does not use DWARF?

### Implementation history

- Initial implementation: #98350
- Stop emitting `.debug_pubnames` and `.debug_pubtypes` when using DWARF 5 #117962
- Refactoring & cleanups #135739
- Fix LLVM warning on LTO with different DWARF versions #136659 
- Improve argument validation #136746

**Comment by thomcc** [comment]
Ideally this design proposal would include some method of exposing it to cargo build scripts, so crates like `cc` would be able to use the righ version of DWARF (see https://github.com/rust-lang/cc-rs/pull/694, for example, where we hardcode decisions compatible with rustc)

**Comment by Wyvern** [comment]
Is there a unstable way to opt-in DWARF5 for Rust now? 
Tried `-Zdwarf-version=5` in macOS, but seems failed.

**Comment by fhanau** [comment]
As of [Xcode 16](https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes#Debugging) DWARFv5 is used by default when targeting macOS 15 or higher, LLVM also defaults to 5 on Linux for most architectures. Hopefully the defaults can be updated to what LLVM is doing soon. This is especially helpful when using linker plugin LTO to link Rust and C++ code together, which produces lots of LLD warnings when there are mismatching Rust versions.
