### ISSUE TITLE
Tracking issue for speeding up rustc via its build configuration

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/rust#103595]
There are several ways to speed up rustc by changing its build configuration, without changing its code: profile-guided optimization (PGO), link-time optimization (LTO), post-link optimization (via BOLT), and using a better allocator (e.g. jemalloc or mimalloc).

This is a tracking issue for doing these for the most popular Tier 1 platforms: Linux64 (`x86_64-unknown-linux-gnu`), Win64 (`x86_64-pc-windows-msvc`), and Mac (`x86_64-apple-darwin`).

Items marked with [2022] are on the [Compiler performance roadmap for 2022](https://hackmd.io/YJQSj_nLSZWl2sbI84R1qA).

### PGO

- [x] Linux64: done some time ago.
- [x] Win64 [2022]: #96978, merged 2022-07-12.
- [ ] Mac [2022]:
  - Slow Macs on GitHub CI is the limiting factor. Mac CI builds are slow (2.5 hours without PGO). Linux CI builds take under 2 hours with full PGO. It's not acceptable to make a CI cycle a lot slower.
  - Faster hardware isn't an option. Getting our own faster machines would be easy, but configuration and maintenance of such machines for custom CI would be painful.
  - Could we take PGO artifacts/profiles from Linux and apply them on OS X? Initial attempts failed.

### LTO

- Linux64:
  - [x] rustc front-end: #101403, merged 2022-10-24.
  - [x] LLVM: done some time ago.
- Win64:
  - [ ] rustc front-end
  - [ ] LLVM [2022]
- Mac:
  - [ ] rustc front-end
  - [ ] LLVM [2022]

This is all thin LTO, which gets most of the benefits of fat LTO with a much lower link-time cost.

### BOLT

- Linux64:
  - [ ] rustc front-end [2022]: #102487, in progress, mixed results.
  - [x] LLVM [2022]: #94381, merged 2022-10-10.
- Win64: N/A
- Mac: N/A

Bolt only works on ELF binaries, and thus is Linux-only.

### Better allocator

- [x] Linux64: jemalloc, done some time ago.
- [ ] Win64 [2022]
- [x] Mac: jemalloc, done some time ago.

#92249 tried using mimalloc 1.7.0 instead of jemalloc, which was faster but used more memory on Linux64 CI, a trade-off deemed to be unacceptable. It was suggested that mimalloc 2.0.x might use less memory.

Note: we use a better allocator by simply overriding malloc/free, rather than using `#[global_allocator]`. See [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/Using.20.60.23.5Bglobal_allocator.5D.60.20for.20jemalloc.20on.20macOS.20.28w.2F.20data.29/near/294375737) for some discussion about the sub-optimality of this.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

**Comment by the8472** [comment]
Another thing to try that was brought up on zulip is aligning the text segment to 2MB so it can be loaded in a way that transparent huge pages kick in, but I'm not 100% sure if this even works yet, last time I checked large page support in the page cache was still a WIP and I haven't seen it in release notes.

**Comment by lqd** [comment]
An update for windows: 
- I'm trying ThinLTO for `rustc_driver.dll` in https://github.com/rust-lang/rust/pull/103591 as local results looked interesting enough (but nowhere near as high as we saw on `x86_64-unknown-linux-gnu`).
- I don't think we actually can (or need to) ThinLTO LLVM separately on MSVC: that is done by [linking to LLVM as a shared library](https://github.com/rust-lang/rust/blob/36285c5de8915ecc00d91ae0baa79a87ed5858d5/src/bootstrap/config.rs#L1131-L1133), which is [not supported on `x86_64-pc-windows-msvc`](https://github.com/rust-lang/rust/blob/36285c5de8915ecc00d91ae0baa79a87ed5858d5/src/bootstrap/native.rs#L336-L338). So IIUC only the above should be necessary as LLVM seems statically linked there.

**Comment by nnethercote** [comment]
> Another thing to try that was brought up on zulip is aligning the text segment to 2MB so it can be loaded in a way that transparent huge pages kick in

Given that it's not even clear that this works, let's leave it off this issue for now.

**Comment by the8472** [comment]
It looks like file-backed huge pages are supported now. https://www.kernel.org/doc/html/latest/filesystems/proc.html#meminfo

> FileHugePages
>    Memory used for filesystem data (page cache) allocated with huge pages
> FilePmdMapped
>   Page cache mapped into userspace with huge pages

I think it was introduced with this one https://github.com/torvalds/linux/commit/793917d997df2e432f3e9ac126e4482d68256d01 so it needs at least 5.18

**Comment by tschuett** [comment]
I read and actually checked that rustc links dynamically against rustc_driver. The same article said we dlopen codegen backends. Isn't there a way for the common case, a static binary: rustc + rustc_driver + LLVM?

**Comment by tschuett** [comment]
I would enable LTO over the full binary. Startup time may also be better.

**Comment by Kobzol** [comment]
Well, the "full binary" is one function call into `rustc_driver` :) But it's true that I haven't tried benchmarking static linking on top of the current LTO optimized `librustc_driver`. I'll try it, to see if static linking + LTO could provide substantial benefits.

Shipping a statically linked `rustc` would probably only be possible on some OSes (Linux), and it would increase the size of the distributed artifacts by a nontrivial amount.

**Comment by tschuett** [comment]
My LLVM folder is full of large statically linked LTO'd binaries (OSX). 

Could you also statically link in the LLVM backend?

**Comment by Kobzol** [comment]
In theory, yes. In practice, I'm not sure if our current build system supports it (will check).

**Comment by tschuett** [comment]
No worries.

```console
-rwxr-xr-x 1 xxx staff 129M Jul 28 18:44 clang-15
```
It only links against system libraries and no LLVM libraries.

**Comment by Elabajaba** [comment]
I'm not sure if it helps, but on Windows LLVM can be built with a different allocator using the `-DLLVM_INTEGRATED_CRT_ALLOC=path/to/allocator` flag (supports rpmalloc|mimalloc|snmalloc). However I tried doing that a few months ago, and while the llvm builds seemed to work fine, `rustc_llvm` failed to build using a version of LLVM built with mimalloc or snmalloc (I didn't end up testing rpmalloc at the time). The errors at the time were: for snmalloc `error: renaming of the library 'INCLUDE' was specified, however this crate contains no '#[link(...)]' attributes referencing this library` for mimalloc the error was the same, except it was `F` instead of `INCLUDE`

The LLVM pr (https://reviews.llvm.org/D71786) also showed some pretty major performance gains when it was implemented.

**Comment by jyn514** [comment]
@michaelwoerister also suggested in #49180 that we could set `codegen-units=1` for the compiler (we already do that for std).

**Comment by Mark-Simulacrum** [comment]
Apple aarch64 should have a very modern baseline.

**Comment by Kobzol** [comment]
> Note that there's a bit of a catch-22. We could start adding specialized SIMD impls for some important core routines if std were built with a higher baseline, which would increase the performance delta

That's a very good point, I agree with that!

I think that we could start with the compiler (and its stdlib), to potentially make it faster, but still keep the actual Linux x64 target without v2/v3/v4 CPU features by default.

Do you have any ideas where we could start using x86 v2 CPU features?

**Comment by the8472** [comment]
> I think that we could start with the compiler (and its stdlib),

Doesn't the compiler link the same stdlib it uses to build programs?

> Do you have any ideas where we could start using x86 v2 CPU features?

Adopting the utf8 validation impl from simdutf8. Other than that it'll need some exploration. Maybe the stdsimd folks have some ideas on tap.
There's always a difference between "if I had all the most recent CPU features I could..." and more modest optimizations 😅

Maybe rustc hash could be replaced with a different mixing function? ... odd, I can't find the feature level of the PCLMULQDQ instruction.

**Comment by Kobzol** [comment]
> Doesn't the compiler link the same stdlib it uses to build programs?

IIRC it doesn't, it has its own copy. Conceptually, it needs to be able to use to add any (target) stdlib to the resulting program to cross-compile. But I might be wrong.

**Comment by tschuett** [comment]
The targets on the [Platform Support](https://doc.rust-lang.org/nightly/rustc/platform-support.html) page look like legit target triples. Could you encode v4 in triple and ship two Linux versions for x86?

**Comment by Kobzol** [comment]
In theory yes, but I'm not sure if it's the best solution. Maybe we could bump the defaut target to v2/v3 and keep an unoptimized v1 target for people with old CPUs. In any case, maintaining a target is not for free, so maybe there are better solutions.

**Comment by tschuett** [comment]
Shipping a highly tuned v4 compiler with -mtune=icelake should give some speedup and you can use current cpu features: AVX512, PCLMULQDQ,   ..

Haswell was launched June 4, 2013.

```
x86-64: CMOV, CMPXCHG8B, FPU, FXSR, MMX, FXSR, SCE, SSE, SSE2
x86-64-v2: (close to Nehalem) CMPXCHG16B, LAHF-SAHF, POPCNT, SSE3, SSE4.1, SSE4.2, SSSE3
x86-64-v3: (close to Haswell) AVX, AVX2, BMI1, BMI2, F16C, FMA, LZCNT, MOVBE, XSAVE
x86-64-v4: AVX512F, AVX512BW, AVX512CD, AVX512DQ, AVX512VL
```

**Comment by Kobzol** [comment]
Yes, our measurements show that v3 produces ~1-3% speedup for the compiler. But on it's own, that hasn't been worth it to use it so far, because there is non-trivial maintenance costs for doing that, plus we would drop some existing users. We'll need to tread carefully.

**Comment by the8472** [comment]
AVX-512 is not really viable for broad use because AMD only started shipping it recently and intel has only shipped it to some of their market segments (workstation/server chips) and even removed disabled it on recent ships due to inconsistencies between P and E cores.
AVX2 has a much larger user base.

See https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam?platform=linux
99% for SSE42 (~v2)
93% for AVX2 (~v3)
6.5% for AVX512 (~v4)

**Comment by klensy** [comment]
Attempted to tune ColdFuncOpt option for PGO (https://github.com/llvm/llvm-project/pull/69030) https://github.com/rust-lang/rust/pull/132779 to decrease file size, but sadly, no good results. Possible reasons: current linux dist uses bolt on top of pgo, which increases size; i forgot to apply the same optimization for libllvm (applied only for rustc_driver).

**Comment by davidhewitt** [comment]
With the recent-ish promotion of `aarch64-apple-darwin` to tier 1, and all recent apple hardware being shipped with architecture, will this issue be updated to add (or replace) that as a Mac target for optimization? It's not clear to me what the optimization status is for that toolchain, and this seemed the best place to attempt to find it.

**Comment by nnethercote** [comment]
@Kobzol, @lqd: does Mac/ARM64 get all the same treatment as Mac/Intel?

**Comment by lqd** [comment]
It has LTO and jemalloc, but not the 1CGU config. It’s not going to be earth shattering or anything, but I’ll make some local tests and a PR for try builds soon, to see the potential improvements there.

**Comment by lqd** [comment]
> I’ll make some local tests and a PR for try builds soon

done in https://github.com/rust-lang/rust/pull/133747
