### ISSUE TITLE
Tracking Issue for `impl_trait_projections`

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/rust#103532]
This is a tracking issue for the feature using `Self` and projections in `impl Trait`.
The feature gate for the issue is `#![feature(impl_trait_projections)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement https://github.com/rust-lang/rust/pull/103491
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

**Comment by cjgillot** [comment]
Closed by stabilizing PR https://github.com/rust-lang/rust/pull/115659
