### ISSUE TITLE
Tracking Issue for integrating `Error` trait with panic interfaces

### ISSUE THREAD

**Issue by DebugSteven** [rust-lang/rust#103820]
Feature gate: `#![feature(error_in_panic)]`

This is a tracking issue for integrating the `Error` trait with `panic` interfaces.
 
This PR seeks to allow panic handlers to access the richer `Error` trait interface when reporting panics that have a runtime error as their source.

### Public API

```rust
impl PanicInfo<'_> {
    pub fn source(&self) -> Option<&(dyn Error + 'static)>;
}
```

```rust
pub const fn panic_source(msg: fmt::Arguments<'_>, source: &(dyn Error + 'static)) -> !;
```

### Steps / History

- [ ] ACP: https://github.com/rust-lang/libs-team/issues/124
- [ ] Implementation: #103169
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- [ ] How should this actually be invoked? What should be the final interface?
- [ ] How do we integrate this with `expect` and `unwrap`? (More detail in the [ACP](https://github.com/rust-lang/libs-team/issues/124))

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html
