### ISSUE TITLE
Tracking Issue for `for<'a> impl Trait<'a>`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#104288]
Some context can be found in [this comment](https://github.com/rust-lang/rust/issues/96194#issuecomment-1124745154).

We would like to support using higher kinded lifetimes in opaque types. 

At present 

```rust
#![feature(type_alias_impl_trait)]

trait Tr<'a> {
	type Assoc;
}

impl<'a> Tr<'a> for () {
	type Assoc = ();
}

type Associated<'a> = impl Copy;
type Associated2<'a> = impl Copy + 'a;

fn f() -> impl for<'a> Tr<'a, Assoc = Associated2<'a>> {}
fn f1() -> impl for<'a> Tr<'a, Assoc = Associated<'a>> {}

impl<'a> Tr<'a> for i32 {
	type Assoc = &'a ();
}

fn f2() -> impl for<'a> Tr<'a, Assoc = Associated2<'a>> { 42_i32 }
fn f3() -> impl for<'a> Tr<'a, Assoc = Associated<'a>> { 42_i32 }
```

ICEs the compiler and the equivalent code for RPIT doesn't compile.

An implementation should also add tests that actually use the higher kinded lifetimes, e.g. via closures or similar datastructures.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Replace the error from https://github.com/rust-lang/rust/pull/97039 with a feature gate and then implement meaningful semantics.
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

* https://github.com/rust-lang/rust/issues/96194 issue where this was noticed
* https://github.com/rust-lang/rust/pull/97039

**Comment by SkiFire13** [comment]
The issue title seems to be swapping the `impl` and `for<'a>`
