### ISSUE TITLE
Tracking Issue for simple_fmt

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#105054]
Feature gate: `#![feature(simple_fmt)]`

This is a tracking issue for the `simple_fmt` methods on the format traits.

### Public API

```diff
  pub trait Display {
      fn fmt(&self, f: &mut Formatter) -> Result;
+     fn simple_fmt(&self, f: &mut Formatter) -> Result {
+         self.fmt(f)
+     }
  }
```

And the same for for `Debug`, `Pointer`, `Binary`, `Octal`, `UpperHex`, `LowerHex`, `UpperExp`, and `LowerExp`.

Formatting placeholders without any options, like in `format_args!("{} {:x}", x)`, will call the `simple_fmt` method rather than `fmt`. This allows for optimized implementations for e.g. `<String as Display>::simple_fmt` that do not need to pull in code for padding, etc. See https://github.com/rust-lang/rust/pull/104525#issuecomment-1318399783.

### Steps / History

- [ ] Implementation: #104525
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- [ ] Do we want to stabilize this at all, to allow crates to override `simple_fmt` for their own types?
- [ ] Should the method be `unsafe`, such that the implementation may unsafely assume that the `Formatter`'s options are all set to default?
