### ISSUE TITLE
Tracking Issue for closures in const contexts

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/rust#106003]
This is a tracking issue for declaring const closures.
The feature gate for the issue is `#![feature(const_closures)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the feature
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

* `const static async move || {}` (keyword order?)

**Comment by Jerrody** [comment]
> ### Unresolved Questions
> 
> 
> * `const static async move || {}` (keyword order?)

In my opinion, suggested keyword order is good.

**Comment by dtolnay** [comment]
> ### Unresolved Questions
> 
> * `for<'a> const static async move || {}` (keyword order?)

Data point: `const async fn f() {}` is the order accepted for function definitions, so we should ensure at minimum the relative order of `const`&ndash;`async` is consistent.

**Comment by jhpratt** [comment]
For the top-level comment: the feature is `#![feature(const_closures)]`, plural.

**Comment by jasper310899** [comment]
Now with the Fn trait constified this seems possible, right?

**Comment by oli-obk** [comment]
Yes, but it needs significant work and possibly a redesign from scratch. Unsure, but it's def more than a few days of work, considering I worked on it for a day and didn't get very far in even understanding the full situation. I'll post my status as a PR as it's an improvement to the currently broken feature, but it still may require getting ripped out and done over
