### ISSUE TITLE
Rustdoc JSON 2023 Roadmap

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#106697]
## Foreign ID Lookup

This need's it's own issue at some point, but for [the zulip chat](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Rustdoc.20JSON.3A.20Include.20All.20Foreign.20Items.3F) is the best resource.

The problem we want to solve is that if I have an `Id` from one crate's json, but the Id is for a foreign type, then it won't be present in `index`, only `paths`. If you want to see the `Item`, you need to find the json for the crate that this `Id` is from. The problem is that in this JSON you need to use a different ID. To find the ID in the crate the item is local to, you need to find the path for the item from `paths`, and then look that up the the json for the crate the item's from.

This is cumbersome, slow, and unreliable [^unreliable].

Idealy you should be able to just use the Id from one JSON in another. I'm not sure if this is possible, or if we'll need some translation scheme, potentially spiting Id's into two fields (crate id, and item id). How exactly this will work needs further design work.

[^unreliable]: Especialy when the `path` isn't present in the public docs.

## Correctness.

Rustdoc JSON should never emit wrong, or invalid data (duh). Theirs still work to do on this, in paticular:

- [ ] #106378
- [ ] #106435

Once these are fixed, we should:

- [ ] Do a crater run with `jsondoclint` on the output running automaticly.

## Performance

Rustdoc JSON has had essentially no performance work done to it [^syscall]. Theirs probably alot of low hanging fruit.
The first thing to make this feasable is

- [ ] Add suport in rustc-perf (https://github.com/rust-lang/rustc-perf/pull/1512).

Once this lands and we can use `@ bors try @ rust-timer queue`, we can actually make some changes. It's hard to know what actually matters without data, but some ideas to explore:

- [ ] Don't allocate a `String` for each `Id`
- [ ] Done use the default hasher when building `index`, but use one of the good ones without HashDos migrations (probably rustc's fxhash)
- [ ] Be cleverer about cloning items before inserting them into the index, by using the entry api
- [ ] Avoid allocating a `PathBuf` in `Span`.

[^syscall]: Except for fixing an issue where a syscall was being done for every single key, punctuation and value in JSON.

## Internal Improvements

- [ ] Think about how to avoid hitting the recursion limit for more compex types ([eg](https://github.com/obi1kenobi/cargo-semver-checks/issues/108)0
- [ ] Ensure we don't lose a FORMAT_VERSION bump to git race conditions. [#94591](https://github.com/rust-lang/rust/issues/94591)
- [ ] Switch away from jsonpath_lib for jsondocck, as it can't do complex predicated, which is annoyed ([issue](https://github.com/freestrings/jsonpath/issues/91))
- [ ] Add suport for using variable to create jsonpath query in jsondocck. Would be usefull for $.index[$$some_id$$].inner.something, although the syntax for interpolation here needs work.
- [ ] Writeup docs for the testing settup, [#100515](https://github.com/rust-lang/rust/issues/100515)
