### ISSUE TITLE
Tracking Issue for `#![feature(offset_of)]`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#106655]
Feature gates tracked by this issue:

* `#![feature(offset_of)]`
* ~~`#![feature(offset_of_enum)]`~~ -> moved to #120141

This is a tracking issue for the `offset_of!` macro which evaluates to a constant
containing the offset in bytes of a field inside some type (https://github.com/rust-lang/rfcs/pull/3308).

### Public API

```rust
// core::mem

pub macro offset_of($Container:ty, $field:tt $(,)?) {
    // ...implementation defined...
}
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/106934
- [x] Split off `offset_of_enum`:  #117537
- [x] Final comment period (FCP)[^1]: [old](https://github.com/rust-lang/rust/issues/106655#issuecomment-1546837391), [new](https://github.com/rust-lang/rust/pull/118799#issuecomment-1863113634)
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/118799

### Possible future extensions / work

- [ ] Support for static alignment DSTs (`struct Example(u32, [u8])`)
- [x] Support for `enum`s: #114208
- [ ] Improving diagnostics around the macro errors

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by tgross35** [comment]
It looks like https://github.com/rust-lang/rust/pull/106934 is the implementation PR, you may be able to link it in the readme

**Comment by est31** [comment]
Some things that could get tests:

* `offset_of!(Self, ...)` works, if and only if it's inside an impl block.
* the return type of `offset_of!()` is usize: some code that tries to use it as usize -> works. some code that tries to use it as u8/isize -> fails.

**Comment by Amanieu** [comment]
Small nit on the docs: I don't think "stable" is the right word to use for describing the output on non-`repr(C)` structs since this causes confusion with Rust's concept of stable APIs.

@rfcbot fcp merge

**Comment by m-ou-se** [comment]
Looks like it has an issue: `0.0` doesn't work right now for nested tuple fields.

**Comment by m-ou-se** [comment]
This FCP is to confirm that libs-api is happy with committing to this macro existing forever with this interface. That seems refreshingly uncontroversial in this case.

Whether the implementation is robust/bug free enough is a bit of a separate question, and it might be worth delaying stabilization for that.

If you think there is value in having more time for the interface/api itself, please share your thoughts on that!

**Comment by WaffleLapkin** [comment]
Oh I see! I don't think we are *committing* to the interface until stabilization, but yes, the interface seems uncontroversial 👍🏻

**Comment by est31** [comment]
One nice project before stabilization would be to make a PR to [memoffset](https://github.com/Gilnaa/memoffset) to use `offset_of` internally behind a cfg or feature flag, then test that together with some users of memoffset. Maybe it could be integrated into a crater run in some fashion.

**Comment by BurntSushi** [comment]
I wanted to double check that the lang team was okay with us making the call on an API like this, and indeed, they did respond on the RFC saying they were comfortable with it being in libs-api's hands: https://github.com/rust-lang/rfcs/pull/3308#issuecomment-1331189141

**Comment by BurntSushi** [comment]
@rfcbot concern docs

The documentation for this macro is woefully incomplete. I would expect it to be full of interesting bits about what guarantees are provided and which aren't. I'd love to see someone comb through the RFC discussion at https://github.com/rust-lang/rfcs/pull/3308 and extract the salient and interesting points, then convert them somehow into API docs for this macro.

I also find the existing docs somewhat confounding. The reference to C's `offsetof` is only going to help C programmers. I'm okay with references like that personally, but I think they need to be properly contextualized such that anyone who isn't familiar with C's `offsetof` will understand what is meant.

**Comment by BurntSushi** [comment]
@rfcbot concern implementation quality

I like @est31's idea above about putting this through its paces before we commit to it. I don't see anything changing about the API, but it doesn't feel right to stabilize something that hasn't seen some kind of use in anger yet.

**Comment by Amanieu** [comment]
I tried converting all uses of `memoffset::offset_of` with `core::mem::offset_of` in one of my projects and ICE'd the compiler: #111657

**Comment by est31** [comment]
I've filed #111669 for linting if someone doesn't use the result of `offset_of`. The macro is side effect free. I don't think this should be a stabilization blocker however, it's only a minor thing.

**Comment by est31** [comment]
Some updates in the past days:

* My test PR has been merged: #111665
* An ICE fix PR has also been merged: #111696
* I've filed #111839 to organize some efforts around testing `offset_of` in the ecosystem. Help is wanted!

**Comment by oxalica** [comment]
> Looks like it has an issue: `0.0` doesn't work right now for nested tuple fields.

Since #112216, `offset_of!(NestedTuple, 0.0)` is now accepted. It looks super suspicious and confusing to me. It is also not covered by this tracking issue nor the RFC. Is there more existing discussion about it?

**Comment by est31** [comment]
As pointed out in #112204, `0.0` already works for field access as well, so `(((), ()),()).0.0` is a valid Rust expression.  The RFC does mention nested field access as one of the extensions, which were implemented by the original PR https://github.com/rust-lang/rust/pull/106934. My PR #112216 only touched the parser to recognize float-like tokens as their field-like components.

**Comment by oxalica** [comment]
> As pointed out in #112204, `0.0` already works for field access as well, so `(((), ()),()).0.0` is a valid Rust expression.

That's different than `offset_of!(Ty, 0.0)`, which looks exactly a float literal, but have different unrelated meaning. I can parse field access as `expr.0.0` as `expr .0 .0`, but not `ty, 0.0` as `ty ,0 .0`. I prefer to let them have more similar surface syntax, by also putting a dot before the first field `offset_of!(Ty, .0.0)`, or the same but blessed by rustfmt `offset_of!(Ty, .0 .0)`.
I hope enforcing a `.` before field accesses could merge the parser logic between two field access syntax for consistency.

**Comment by joshlf** [comment]
IIUC from this thread, the outstanding issues blocking FCP are:
- Ecosystem testing 
  - Looks like that just entails testing with the remaining crates here? https://github.com/rust-lang/rust/issues/111839
- Improving docs

Is that correct?

**Comment by deltragon** [comment]
There was also a discussion about syntax on zulip, and making sure that the basic syntax does not lead to issues for the extended case: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/.60offset_of!.60.20Syntax (see also https://github.com/rust-lang/rust/pull/114208 for that)

**Comment by GKFX** [comment]
> Small doc nit:
> 
> > Note that the output of this macro is not stable, except for `#[repr(C)]` types.
> 
> There are other reps that guarantee type layout for structs/unions (namely, `transparent` and `packed`/`packed(1)`).

This has been updated to the below, linking out to the documentation on the subject rather than trying to summarise it all in place.
> Note that type layout is, in general, [subject to change and platform-specific](https://doc.rust-lang.org/reference/type-layout.html).

**Comment by joshlf** [comment]
I've put up a PR to address https://github.com/rust-lang/rust/issues/106655#issuecomment-1550041499: https://github.com/rust-lang/rust/pull/117512

**Comment by BurntSushi** [comment]
Given the testing work @est31 has put in (and a DM from them noting that they think this concern can be resolved), I'll resolve the implementation quality concern. :-)

@rfcbot resolve implementation quality

**Comment by BurntSushi** [comment]
There is also a fair bit of discussion around the syntax here on Zulip: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/.60offset_of!.60.20Syntax

Is there a summary of that discussion anywhere? cc @scottmcm 

I'll mark a concern for it just in case.

@rfcbot concern syntax

**Comment by the8472** [comment]
We should also comb through the standard library and maybe the compiler to find places to dog-food this.

**Comment by GKFX** [comment]
> We should also comb through the standard library and maybe the compiler to find places to dog-food this.

I think `std::intrinsics::option_payload_ptr` is now redundant to `offset_of` - it could be removed.

**Comment by BurntSushi** [comment]
@rfcbot resolve docs

**Comment by est31** [comment]
> We should also comb through the standard library and maybe the compiler to find places to dog-food this.

FTR there was already #112298, but that doesn't mean it is the end of such efforts :).

**Comment by joshlf** [comment]
> * if we want to stabilize soon (1.76 will be earliest I think), we should put the enum variant changes done by [Support enum variants in offset_of! #114208](https://github.com/rust-lang/rust/pull/114208) into a separate feature gate as it hasn't had enough time to bake (and is a non-minor extension to offset_of)

+1 to this. Does someone want to provide mentoring instructions or put up a PR? I'd be happy to put up a PR if someone can give me a rough sketch of what needs to be done.

**Comment by GKFX** [comment]
> > * if we want to stabilize soon (1.76 will be earliest I think), we should put the enum variant changes done by [Support enum variants in offset_of! #114208](https://github.com/rust-lang/rust/pull/114208) into a separate feature gate as it hasn't had enough time to bake (and is a non-minor extension to offset_of)
> 
> +1 to this. Does someone want to provide mentoring instructions or put up a PR? I'd be happy to put up a PR if someone can give me a rough sketch of what needs to be done.

I've opened the relevant PR at #117537.

**Comment by joshlf** [comment]
> * some conclusion of the syntax discussion, as pointed out above by @deltragon. see [this link](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/.60offset_of!.60.20Syntax). further up in the thread it was [said that the syntax is uncontroversial](https://github.com/rust-lang/rust/issues/106655#issuecomment-1547981791) but that was before the opening of that zulip thread. I'm fine with the current syntax but note that we are currently doing some tricks to allow stuff like `0.0` (they are seen as floats)

From a very brief skim of that thread, it seems like most of the complexity in the design space has to do with the syntax for enum variants. IIUC, considering only structs (which is what's being proposed for stabilization given https://github.com/rust-lang/rust/pull/117537), and importantly _not_ considering array indexing, the only question is about how to represent a sequence of nested field accesses. The current syntax - `offset_of!(Foo, bar.baz)` - is consistent with @llogiq's [point about consistency with existing syntax](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/.60offset_of!.60.20Syntax), and IMO is the right call. What would we need to do to reach a formal agreement to keep this syntax, keeping in mind that we're _not_ committing to a syntax for array indexing or enum variant access?

**Comment by llogiq** [comment]
Does getting the offset of triply nested indexed fields work with this syntax, e.g. `offset_of!(Foo, 1.2.3)`? Because IIRC there was some hack around double indexed fields being parsed as floats.

My proposal was type,.followed by a comma separated list of field or variant::field, but I'm totally OK with the current syntax, provided it works well for all expected cases.

**Comment by joshlf** [comment]
> Does getting the offset of triply nested indexed fields work with this syntax, e.g. `offset_of!(Foo, 1.2.3)`? Because IIRC there was some hack around double indexed fields being parsed as floats.

[It appears to](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=08b58f9660b46d7b98a27b03ba299032):

```rust
println!("{}", mem::offset_of!(D, c.b.a));
```

> My proposal was type,.followed by a comma separated list of field or variant::field, but I'm totally OK with the current syntax, provided it works well for all expected cases.

Not sure I can picture what you're describing; can you give an example of this syntax?

**Comment by llogiq** [comment]
`c.b.a` doesn't parse the same as `1.2.3` though. I was thinking of:

```
struct Foo(Outer);
struct Outer(Inner);
struct Inner(u8);

assert_eq!(0, core::mem::offset_of!(Foo, 0.0.0));
```

**Comment by est31** [comment]
> Does getting the offset of triply nested indexed fields work with this syntax, e.g. offset_of!(Foo, 1.2.3)? Because IIRC there was some hack around double indexed fields being parsed as floats.

The parser already has these workarounds, since #112216. See [this](https://github.com/rust-lang/rust/blob/2db26d3d55387930f1b1dfb84810bcde5a787a09/tests/ui/offset-of/offset-of-tuple-nested.rs) test file for working examples.

**Comment by llogiq** [comment]
That's what I thought, and this is the exact reason I proposed the comma-separated syntax. It's even parseable with standard matchers, and is completely immune to whitespace changes.

**Comment by GKFX** [comment]
The dotted syntax has the advantage of looking more like field access, and of being near-identical to C for the sake of familiarity. The parsing definitely has to work though - there is a comment on #112216 suggesting to define the macro to take `($Container:ty, $($fields:tt)+)` and add error handling into the macro which sounds reasonable.

**Comment by joshlf** [comment]
+1 to the syntax being the same as native field access to keep the mental model simple. IMO we should prioritize consistency of mental model for casual users who aren't thinking in terms of the syntax that you'd write using `macro_rules!`, and instead are just thinking in terms of it looking the same as they'd "normally" access a field. It's also consistent with `addr_of!`, which does a similar thing to `offset_of!`.

**Comment by the8472** [comment]
When I think of manually doing pointer arithmetic for field accesses I do not think of "casual users" or people who would have their mental model upset by an extra comma in the syntax or anything like that.

**Comment by joshlf** [comment]
Fair point. I'm on my phone rn and  can't check, but I wonder whether the existing syntax might cause problems for users who want to write macros which will call `offset_of!` and pass metavariables as arguments?

**Comment by llogiq** [comment]
Yes, it appears that [one cannot pass expr-matched indices into a chain of dot-separated field accessors](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=b5df44a9fb37bdf53cc5f168a9c93fc8). That's an even stronger argument against the "natural" syntax. I also find the argument of consistency with `addr_of!` spurious. With `addr_of`!`, the field accessor syntax makes sense, because we have an object to access. Much unlike `offset_of!` where we operate on the type, not any particular value.

**Comment by GKFX** [comment]
I think a correct set of macro arguments for the C-style syntax is `($a:ty, $($b:expr)+ $(,)?)` (https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e3fe4caa1b5bb7a9204919a99275cbe4). It accepts all the tuple accesses in offset-of-tuple-nested.rs, and unlike `$($fields:tt)+` it does allow for following arguments, which I think addresses @joshlf's point. That would require a re-write of the parser for `builtin # offset_of` because as noted above it doesn't currently accept expressions in the second argument.

**Comment by llogiq** [comment]
I want to add that I do like the current syntax from a user's point of view. On the other hand, I worry that the hacks needed to implement it will come back to bite us.

**Comment by deltragon** [comment]
I would argue for just stablizing the MVP of `offset_of!(MyStruct, single_field)` for now, and punting everything else (nested fields, array indexing, enums) to afterwards. The MVP would already accomplish a lot and remove the need for a lot of hacks in the ecosystem.
It might even be possible to implement nested fields support as a macro in a library on top of the MVP `offset_of!`, which would give the ecosystem the option of experimenting with the syntax, and deciding whether extending the builtin one is even necessary.

**Comment by est31** [comment]
> I would argue for just stablizing the MVP of `offset_of!(MyStruct, single_field)` for now

@deltragon such an MVP is a great idea. I think if others think similarly, we could split up the feature further, and stabilize the MVP very soon (likely going to be in 1.76, so one release after the christmas/async-in-traits one), and leave the syntax for multiple fields open for now.

IIRC array indexing is also not even supported yet by `offset_of!`.

**Comment by tgross35** [comment]
+1 for a stabilization without nested fields or enum variants. I don’t see any use of anything fancier from a rough search anyway https://grep.app/search?q=offset_of%21%5C%28.%2A%3F%2C.%2A%3F%5B%5C.%3A%5D.%2A%3F%5C%29&regexp=true, probably because many uses of offset_of are related to sharing things with C.

I’m not sure what the current support level is, but I think it makes sense to include tuples and tuple structs as part of the stabilization. That is, I would expect this to work:

```
struct Foo { a: i32, b: String }
struct Bar(i32, String);
type Baz = (i32, String);

let _ = offset_of!(Foo, b);
let _ = offset_of!(Bar, 1);
let _ = offset_of!(Baz, 1);
let _ = offset_of!((i32, String), 1);
```

But not support nesting (which can be worked around with multiple `offset_of!`s anyway) or enums (the big syntax discussion point, but probably a very small use case).

I think somebody interested could put a PR up to do this.

The remaining syntax might be best in a proposal about how type-level references in Rust should look, since that is useful beyond the scope of this macro (metaprogramming, reflection)

**Comment by Amanieu** [comment]
I make use of `offset_of!` with nested fields and find the syntax very convenient. I previously used multiple `offset_of!` but the resulting code was often hard to read.

**Comment by tgross35** [comment]
It just seems we aren't close to consensus on nested syntax due to various concerns:

- Matching in user macros, above
- User friendliness / discoverability
- Consistency with whatever happens for enums (#114208) and arrays
- Parsing of nested tuple fields look like floats `1.2`
- Wanting this sort of meta field reference to work outside of `offset_of` whenever we use it in the future (like C++ member pointers, swift field paths, reflection)
- Other things discussed on zulip https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/.60offset_of!.60.20Syntax

This is likely at least a few months of design work if not more, even if the bare minimum is somebody writing a justification proposal/examples defending the current syntax. It doesn't seem worth indefinitely blocking the core functionality of `offset_of` on this when nested field access was [just a future possibility](https://rust-lang.github.io/rfcs/3308-offset_of.html#nested-field-access) in the RFC.

cc implementer @DrMeepster for any thoughts

**Comment by DrMeepster** [comment]
I agree with @tgross35 that we shouldn't block stabilization on nested field accesses. While it's nice to have, it's not a critical feature. We can let it bikeshed a little while longer l.

**Comment by est31** [comment]
Regarding @Amanieu 's remarks, they are useful feedback but note that I think nobody is arguing against nested uses at all: I think everyone here wants it. The question is more about the timing: it would be really great if we could stabilize some form of `offset_of` soon. The demand in the ecosystem is quite high from what I can tell.

I think most people have spoken out in favour of the MVP approach: maybe it is time for someone (@GKFX? @joshlf?) to make a PR to split off nested fields into a separate feature gate (`#![feature(offset_of_nested)]`?) and stabilize the single-field `offset_of` feature. Of course it needs a libs-api FCP, too (or maybe the [current one](https://github.com/rust-lang/rust/issues/106655#issuecomment-1546837391) could be reused?).

**Comment by GKFX** [comment]
I have a branch locally for stabilizing `offset_of!` taking only a single ident - I can try to get that finished.

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting today. We're happy to limit the stabilization to single fields for now while the discussion about nested fields and enum variants is ongoing. cc @BurntSushi

**Comment by BurntSushi** [comment]
@est31 Do you have ideas on how to move forward here with a partial stabilization?

**Comment by est31** [comment]
That is wonderful news @Amanieu! I think the three things missing are:

* PR to split the feature off -- @GKFX has indicated they can work on this
* stabilization PR
* [stabilization report](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#write-a-stabilization-report)
* stabilization FCP

If we want to get this into 1.76.0, the most time intensive concern is the stabilization FCP which needs 10 days. Either we can re-use the FCP in this issue, or we can issue a new one. I would prefer latter, as it is cleaner. Maybe rfcbot cancel followed by rfcbot merge are the right commands? I will write a stabilization report shortly.

**Comment by est31** [comment]
## Feature Summary

This proposes stabilization of the [offset_of](https://doc.rust-lang.org/nightly/std/mem/macro.offset_of.html) macro *restricted to non-nested uses*:

```Rust
struct FieldStruct {
    first: u8,
    second: u16,
    third: u8
}

assert_eq!(std::mem::offset_of!(FieldStruct, first), 0);
assert_eq!(std::mem::offset_of!(FieldStruct, second), 2);
assert_eq!(std::mem::offset_of!(FieldStruct, third), 4);
```

Nested uses will for now still require a feature gate:

```rust
#![feature(offset_of_nested)] // precise feature name still TBD

#[repr(C)]
struct NestedA {
    b: NestedB
}

#[repr(C)]
struct NestedB(u8);

assert_eq!(mem::offset_of!(NestedA, b.0), 0);
offset_of!()
```

Except for `#[repr(C)]` types, the output is documented to be not stable.

## Documentation

Like most library features, it has a [rustdoc-level](https://doc.rust-lang.org/nightly/std/mem/macro.offset_of.html) documentation.

## Tests

The feature is well tested, both in the [testsuite](https://github.com/rust-lang/rust/tree/master/tests/ui/offset-of), and in the [ecosystem](https://github.com/rust-lang/rust/issues/111839).

**Comment by joshlf** [comment]
Thanks for writing this up!

> Except for #[repr(C)] types, the output is documented to be not stable.

This isn't sufficient - in some cases, other reprs such as transparent or packed are sufficient to fully guarantee a type's field offsets.

We should probably also clarify: "...not to be stable across multiple compilations of the same program." Within a given compilation, the output is stable even without a repr.

**Comment by GKFX** [comment]
> We should probably also clarify: "...not to be stable across multiple compilations of the same program." Within a given compilation, the output is stable even without a repr.

This has been re-worded a couple of times in the library documentation and I believe the documentation there is now adequate; it includes or links out to the information you mention.

Would it be OK to stabilize this in the form below?

```rust
#[stable]
pub macro offset_of {
    ($Container:ty, $field:ident $(,)?) => /* stable */,
    ($Container:ty, $($fields:tt).+ $(,)?) => /* unstable */,
}
```

I would have some concern about making the `$($fields:tt).+` form usable on stable since it looks like it will need to change and I don't want there to be unintended breakage when the macro is called from other macros etc.

**Comment by the8472** [comment]
Ident wouldn't support the tuple field accesses mentioned in https://github.com/rust-lang/rust/issues/106655#issuecomment-1793844266

**Comment by est31** [comment]
> This has been re-worded a couple of times in the library documentation and I believe the documentation there is now adequate; it includes or links out to the information you mention.

Thanks for pointing that out, I have updated the stabilization comment.

**Comment by RalfJung** [comment]
> If we want to get this into 1.76.0, 

We do time-based released, not feature-based releases, precisely to avoid any kind of "deadline rush". Please don't rush this. It's no problem at all if it takes 6 weeks longer to ship this, so I'd rather we take the time to do this properly. :)

E.g. we need to be reasonably confident that whatever syntax we ship is forward-compatible for extending this to multiple fields later.

**Comment by est31** [comment]
At least I am quite confident that the existing syntax is forward-compatible for multiple fields, whether `.` or `,` or `/`, or `->`, or `::` is used to separate fields, or just spaces. I have pointed to the place above where I think it's easiest to lock things down. I am familiar with the parsing code as I have implemented it, and I think it's extremely easy to restrict it to single fields.

It is not my intent to rush the feature, and please don't misunderstand me that it is an absolute must that it has to be released at that date: it isn't.

But I have made the experience that light nudges towards a target date are helpful in getting a feature over the finishing line, even if it misses a release in the end. It puts people into the right mindset of looking for issues and wondering if they are big enough to block stabilization or not.

Sure it gives more scrutiny if you have six weeks of a feature sitting on nightly as "to be stabilized soon" until it actually goes to beta, but that is actually quite close to a feature being stabilized shortly before a release, it's just a few days offset :).

When humans collaborate, there is the need for coordination, which also involves when to work on something. Mere waiting time is not helpful on its own, as a feature's issues and problems and their solution are only discovered from attention. Sometimes that attention only appears once a feature is on stable, which is not as optimal when attention appears to nightly features. I'd argue that for `offset_of`, we had plenty of time at this point. People have brought up stabilization weeks after the PR merged: the feature is quite wanted.

It happens often that features get stuck in a "final touches missing" hell, and can be there for months or even years. Not because the final touches are insurmountable, but because they need people's attention and nobody is confident enough to step up and say "let's stabilize this *soon*". I only push towards stabilization now because of the [questions about the remaining blockers](https://github.com/rust-lang/rust/issues/106655#issuecomment-1724158417) earlier in the thread, and because it indeed feels like that the feature is ready.

I think people already apply a fair amount of scrutiny for unstable features, and this time around I put extra emphasis on tests and I have asked for [testing inside the ecosystem for `offset_of`](https://github.com/rust-lang/rust/issues/111839), and people did report their experiences with it in addition to some of my own experiments.

In this instance, I don't believe there is any stabilization blockers left (outside of the split of the feature into two). This doesn't mean that this is an unchangeable fact, it can actually be that there is concerns. So if anyone has concrete issues, please bring them up. If any concern grave enough comes up, it is absolutely important to delay the stabilization until it is resolved or worked around (eg by limiting the stable parts of the feature).

**Comment by RalfJung** [comment]
> At least I am quite confident that the existing syntax is forward-compatible for multiple fields, whether . or , or /, or ->, or :: is used to separate fields, or just spaces. I have pointed to the place above where I think it's easiest to lock things down. I am familiar with the parsing code as I have implemented it, and I think it's extremely easy to restrict it to single fields.

Okay, so it is very unlikely that we'll end up with `offset_of!(Type.field.field)` or so, something other than a `,` between giving the type and giving the field of the type?

**Comment by CryZe** [comment]
I'm sorry if I've missed it, but at least a CTRL+F "pattern" didn't turn up anything, but I'm really surprised by this issue why we are not just using the basic pattern matching syntax? That resolves all cases including deeply nested stuff, enums and co., while also not needing to make up any new way of expressing these things. Also in my opinion, if we were to go with pattern matching syntax, then it wouldn't be super compatible with the `offset_of!(Type, field)` that is intended to be stabilized.

**Comment by est31** [comment]
The current-on-nightly syntax has precedent in c's [offsetof](https://en.cppreference.com/w/cpp/types/offsetof) ([standard link](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf#section.7.21)), including the way dots work for nesting, so it has some familiarity I would presume.

But this doesn't mean that we can't do `offset_of!(Type.field.field)` if we really wanted to.or pattern syntax

, although I wonder how arrays would be represented, so what would be the pattern analog of c's `offsetof(S, field.field[20].10)`?

I wasn't much involved in the syntax discussion, if there is actual doubts on the non-nested 

Hmm yeah alright, those are good points. Maybe it might make sense to have 

I think we should focus on the more general syntax concerns. Actually pattern syntax is a quite interesting suggestion.


Regarding pattern syntax,

**Comment by est31** [comment]
IDK maybe I made the wrong estimate and it's too early still for a stabilization of `offset_of` before the syntax discussion advances further. But my fear is that this can drag on for months and years.

**Comment by GKFX** [comment]
I am thinking that `offset_of!(Type, self.a.b.0[n])` might be a good choice - it's a single `expr` which the compiler already knows how to parse, with no edge cases around 0.0 etc.

To summarise, the main options that I'm aware of and my views on them are:

* Type.a.b - not a syntax currently used elsewhere so would need custom parsing, breaks the macro follow-set restrictions if matching the type with `ty`.
* C-style - current implementation but has issues with consecutive tuple accesses and whitespace not matching the current metavariables. Needs some quite awkward parsing because of that.
* Pattern-based - significantly more verbose, no obvious method for array indexing, but is a pre-existing syntax so no parser work
* self.a.b - slightly more verbose version of C-style. Also should need no parser work.

**Comment by the8472** [comment]
You're forgetting enums

**Comment by est31** [comment]
@CryZe btw, [patterns have come up](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/.60offset_of!.60.20Syntax/near/384561393) in the syntax discussion on zulip.

Maybe it would be best to move this discussion there? Or a dedicated thread elswhere. This is a tracking issue after all :).

**Comment by RalfJung** [comment]
> Regarding pattern syntax, I wonder how arrays would be represented, so what would be the pattern analog of c's offsetof(S, field.field[20].10)?

`offset_of!(S.field.field[20].10)`. (C does not have `.10` though, is this a Rust tuple field access?)

I don't think I understand what the pattern syntax would look like, could someone give some examples? `offset_of!(Struct { field1, field2 })` makes no sense so surely it'd have to be a very restricted subset of patterns, and rather redundant if one has to always add the `..`?

**Comment by est31** [comment]
> surely it'd have to be a very restricted subset of patterns, and rather redundant if one has to always add the `..`?

Yeah the zulip thread [proposes usage of @](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/.60offset_of!.60.20Syntax/near/384561766) for that.

> C does not have .10 though, is this a Rust tuple field access?

Yes, sorry I forgot. replace that .10 with .ten :).

**Comment by est31** [comment]
As #118799 has been merged, non-nested `offset_of!()` is now stable on the master branch and will likely be part of the [1.77.0 stable release](https://releases.rs/docs/1.77.0/) on March 21, 2024. For details of what was stabilized, see the [stabilization report](https://github.com/rust-lang/rust/issues/106655#issuecomment-1841622744).

I'm closing this tracking issue as the still unstable aspects of the `offset_of` macro now have different tracking issues:

* [`#[feature(offset_of_enum)]`](#120141)
* [`#[feature(offset_of_nested)]`](#120140)

Thanks everyone involved in getting `offset_of` specified, implemented, tested and stabilized.
