### ISSUE TITLE
Tracking Issue for `{Arc, Rc}::into_inner`

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#106894]
Feature gate: `#![feature(arc_into_inner)]`

This is a tracking issue for the `Arc::into_inner` method, and (for API-consistency) also an `Rc::into_inner` analogue.

The function `Arc::into_inner(x)` serves as an atomic race-condition-free alternative to `Arc::try_unwrap(x).ok()`. See the ACP for more details.

### Public API

```rust
// alloc::sync

impl<T> Arc<T> {
    /// Returns the inner value, if the `Arc` has exactly one strong reference.
    /// Otherwise, `None` is returned and the Arc is dropped.
    pub fn into_inner(this: Arc<T>) -> Option<T>;
}
```
and the extension to `Rc`
```rust
// alloc::rc

impl<T> Rc<T> {
    /// Returns the inner value, if the `Rc` has exactly one strong reference.
    /// Otherwise, `None` is returned and the Arc is dropped.
    pub fn into_inner(this: Rc<T>) -> Option<T>;
}
```

### Steps / History

- [ ] ACP: rust-lang/libs-team#162
- [ ] Implementation:
  - [ ] `Arc::into_inner` #106854
  - [ ] `Rc::into_inner`
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by ryoqun** [comment]
Hey, I've stumbled on this. I wonder how soon this can be stabilized? My usecase is complex. but in a nut shell, I want this to conditionally and cleanly restart bunch of interconnected threads of mixed roles, all sharing `Arc<GlobalContext>`, depending on which thread did actually dropped the GlobalContext.

if sharing helps, i can write the usecase in detail...

Of course, I can resort to sync::Weak or tls. but it incurs overhead and futher complexities. or `mem::transmute` like this to forcibly bring `::into_inner` into stable rustc: https://rust.godbolt.org/z/r5rbsYYcT, in which i have to use `unsafe`...

**Comment by joshtriplett** [comment]
Submitted the `Rc::into_inner` implementation as https://github.com/rust-lang/rust/pull/109026

**Comment by joshtriplett** [comment]
I think `Arc::into_inner` makes sense to stabilize at this point. And `Rc::into_inner` is trivial.

@rust-lang/libs-api, shall we stabilize these?

@rfcbot merge

**Comment by thynson** [comment]
Probably I'm too late here, but I think the `Arc::<T>::into_inner` should returns `Result<T, Self>`, instead of `Option<T>`. 
Unlike `Rc`, checking `Arc::strong_count(arc) == 1` does not guarantee that the subsequence call to `Arc::<T>::into_inner` will no fail. And when it happens, the caller lost an owning `Arc`, making it impossible to recover from such a situation.

```rust
fn unbox_from_arc(arc: Arc<T>) -> T {
  if Arc::strong_count(&arc) == 1 {
    // RACE CONDITION: another thread could upgrade a corresponding Weak<T> at this moment
    return Arc::into_inner(arc)
    // We have no chance to recover from the failure, since `arc` was consumed by`Arc::into_inner`
    // the only thing we could do is to panic
    .unwrap();    
  }
}
```
Since `Arc::into_inner` has been stabilized, a new interface `Arc::try_into_inner::<T>(x: Arc<T>) -> Result<T, Arc<T>>` could be proposed. It should check the reference count is `1` and unwrap it **atomically**,  or returns the `Arc` itself when the condition was not met, so the caller still have an owning `Arc`.

In theory, the above issue is not applicable for `Rc`, but `Rc::try_into_inner::<T>(x: Rc<T>) -> Result<T, Rc<T>>` could also be proposed for consistency.

**Comment by steffahn** [comment]
@thynson Feel free to open an issue if you have concrete ideas how the documentation of `Arc::into_inner` can be improved to convince users to _actually_ look at the `Arc::try_unwrap` function. Of course, it's already mentioned there multiple timest (it's _also_ mentioned on this tracking issue) but apparently not in a way that convinced you to _actually_ look at that method. 

Maybe also a [doc alias](https://doc.rust-lang.org/rustdoc/advanced-features.html#add-aliases-for-an-item-in-documentation-search) “`try_into_inner`” to further help discoverability 🤔

**Comment by steffahn** [comment]
Hmm, no `try_unwrap` is only meant to be discouraged in the case where you ignore the `Arc<T>` you get back in the `Err` case. That’s clearly documented, too… but it’s describing the details of when and how to use `try_unwrap`, and hence not documented in `into_inner`’s documentation.

On the other hand, I wasn’t aware that someone could try to combine `into_inner` with a `Arc::strong_count(…) == 1` check.

Anyways… maybe a sentence that introduces `Arc::try_unwrap` before immediately calling out an expression using it could be sufficiently useful, after all.

>  If `Arc::into_inner` is called on every clone of this `Arc`, it is guaranteed that exactly one of the calls returns the inner value. This means in particular that the inner value is not dropped.
> 
> [`Arc::try_unwrap`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.try_unwrap) offers similar functionality to this function, and might seem simply like a more general/powerful API than `Arc::into_inner`; but it has in fact _different_ use-cases. It you *did* use it to replace `Arc::into_inner`, such as with the expression `Arc::try_unwrap(this).ok()`, then you do *not* get the guarantee described in the previous paragraph. For more information, see the last example below and read the documentation of [`Arc::try_unwrap`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.try_unwrap).

^^^ Maybe like this?

**Comment by thynson** [comment]
> It you did use it to replace Arc::into_inner,  ...

If I understand it right, it looks like a typos of
 
> If you did use it to replace `Arc::into_inner`, ... 

And it shoud be clear enough for me.
