### ISSUE TITLE
Tracking Issue for Async Functions in Dyn Traits

### ISSUE THREAD

**Issue by eholk** [rust-lang/rust#107011]
This is a tracking issue for async functions in dyn traits.
The feature gate for the issue will be `#![feature(async_fn_in_dyn_trait)]`.

See #91611 for the static version.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Write the RFC
- [ ] Implementation
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- How do we convert between static async traits and dyn async traits?

**Comment by traviscross** [comment]
Closing in favor of:

- https://github.com/rust-lang/rust/issues/133119
