### ISSUE TITLE
Seperate clauses and goals from the Predicate type

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#107250]
Split up the `PredicateKind` type into `Goal` and `Clauses` similar (or exactly :D) like what chalk does. The TLDR is that ParamEnv only contains a small set of `PrecicateKind` variants and we want to encode this in the type system by only returning `Clause`s from it.

This projection has been accepted as an MCP: https://github.com/rust-lang/compiler-team/issues/531

## Implementation steps

* [x] [SP] Split out `Trait`, `TypeOutlives`, `RegionOutlives` and `Projection` into `Clause` enum: [#104846](https://github.com/rust-lang/rust/pull/104846)
* [x] [SP] [#104911](https://github.com/rust-lang/rust/pull/104911) `inferred_outlives_crate` returns predicates, but they are always only TypeOutlives or RegionOutlives
    * may kill perf, so let's see if it works to just return ty::Clause where it now returns `ty::Predicate` and build the predicates at the caller site of `inferred_outlives_of`
* [ ] doing the same thing for `explicit_predicates_of` is gonna be a bit more involved
* [ ] Improve perf of [#104846](https://github.com/rust-lang/rust/pull/104846)
* [ ] start with `gather_explicit_predicates_of` and convert at the caller sites
* [ ] `Bounds::predicates` should return an iterator over Clauses

leave a comment when you start working on one of these steps so that no one else duplicates work.

**Comment by spastorino** [comment]
@oli-obk thanks for opening this, I'd be happy to review and/or help/mentor if needed.

**Comment by BoxyUwU** [comment]
`PredicateKind::ConstEvaluatable` `PredicateKind::ConstEquate` and `PredicateKind::WellFormed` can all appear in the param_env/predicates_of so should be moved to `Clause` as well

**Comment by zirconium-n** [comment]
I think I'm a little bit unsure about the task.

> Validate that all of the `ToPredicate` impls are acutally still needed, or prune them if they're not.

What count as an unneeded impl? Some impls can be removed without error, but theres one gray area I'm not sure. That is the impl is not there to satisfy a trait bound but just a helper function. Does this count the impl needed or not? We can just inline the impl body?

**Comment by nnethercote** [comment]
#159990 does "Rename identifiers like pred and predicates to clause if they're actually clauses around the codebase".

**Comment by ada4a** [comment]
@nnethercote [said](https://github.com/rust-lang/rust/issues/107250#issuecomment-5087340329):
> [#159990](https://github.com/rust-lang/rust/pull/159990) does "Rename identifiers like pred and predicates to clause if they're actually clauses around the codebase".

There are still some remaining `ClauseKind`s which use "predicate" in the name: `Projection(ProjectionPredicate)`, `Trait(TraitPredicate)`, and `HostEffect(HostEffectPredicate)`; and those are responsible for a lot of `pred(icate)` identifiers – I'd like to rename them as well before we actually tick the box.

I tried renaming `TraitPredicate`, but that turned out to result in an impolitely large diff... so I'd try renaming the other kinds first, and then return to `TraitPredicate`, splitting its rename into multiple PRs.
