### ISSUE TITLE
Tracking Issue for ip_in_core

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#108443]
Feature gate: `#![feature(ip_in_core)]`

This is a tracking issue for RFC https://github.com/rust-lang/rfcs/pull/2832, providing networking types in `core::net`: `IpAddr`, `Ipv4Addr`, `Ipv6Addr`, `SocketAddr`, `SocketAddrV4`, `SocketAddrV6`, `Ipv6MulticastScope` and `AddrParseError`.

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/104265
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/119276

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by elpiel** [comment]
I guess there's nothing left to do.
Can this feature now move to the the FCP?

**Comment by Xiretza** [comment]
Can this be stabilized before [`error_in_core`](https://github.com/rust-lang/rust/issues/103765) (`AddrParseError` implements `core::error::Error`)?

**Comment by Nemo157** [comment]
You can't feature gate a trait implementation. The question would be if it's possible to refer to any of the `trait Error` methods on the error types without having to activate the feature. I believe not, since you would have to `use core::error::Error` in order to bring the methods into scope.

**Comment by elpiel** [comment]
Thanks for the explanation @Nemo157 and yes, I agree that it can't be stabilised before Error then.

**Comment by a1phyr** [comment]
I disagree, it can be specialized before `error_in_core`. Nothing will change for `std` users, and `no_std` users will merely not be able to use the `Error` impl.

This is just like all existing errors in `core`, eg `core::fmt::Error` (which is arguably stable): https://github.com/rust-lang/rust/blob/735bb7e5df185cc24e56533abd0bbab510931f6f/library/core/src/error.rs#L1046-L1052.

**Comment by djc** [comment]
Ping @rust-lang/libs-api, could this go into FCP?

**Comment by elpiel** [comment]
Yes, please.

**Comment by ChrisDenton** [comment]
I've added the nomination label so it'll be discussed in a libs-api meeting, though it's possible a libs-api member may decide to remove the label and just fcp it. It'd likely be helpful if someone could provide a summary of the current state of things and why this is ready for stabilization.

**Comment by Kixunil** [comment]
I'm not claiming this bears enough weight to stabilize but I just allowed `no_std` in a small library that used `std::net` address types and it went completely smooth.

**Comment by joshtriplett** [comment]
Starting FCP for stabilization.

@rfcbot merge

**Comment by faern** [comment]
I pushed a stabilization PR: https://github.com/rust-lang/rust/pull/119276
