### ISSUE TITLE
Tracking issue for syn 2.0 inside rust-lang/rust

### ISSUE THREAD

**Issue by Noratrieb** [rust-lang/rust#109302]
syn 2.0 was just released!
https://github.com/dtolnay/syn/releases/tag/2.0.0

We should try to fully eliminate syn 1.0 from our dependency tree for better compile times.

The current ways in which we depend on syn 1:

```[tasklist]
- [ ] `synstructure` (chalk and yoke) - https://github.com/mystor/synstructure/pull/57
- [x] `rustc_macros` (requires `synstructure` support, #109663)
- [x] [`chalk_derive`](https://github.com/rust-lang/chalk/blob/master/chalk-derive/Cargo.toml) (chalk) (requires `synstructure`) https://github.com/rust-lang/chalk/pull/793
- [x] `askama_derive` (used by rustdoc) #109512
- [x] `clap_derive` (used by cargo and several other tools) #110077
- [x] `declare_clippy_lint` https://github.com/rust-lang/rust-clippy/pull/10621
- [ ] `derive_new` (through rustfmt) - https://github.com/nrc/derive-new/pull/61
- [x] `tracing-attributes` (tracing, used in the compiler) https://github.com/tokio-rs/tracing/pull/2516
- [ ] `derive_more` (used in rustc_middle) - https://github.com/JelteF/derive_more/issues/249
- [x] `displaydoc` (used in icu4x) - https://github.com/yaahc/displaydoc/pull/42
- [x] `futures_macro` (dev dep of clippy) #110079
- [ ] `icu_provider_macros`: (icu4x)
- [x] `proc-macro-error`: (through clap)
- [x] `serde_derive`: (compiletest , cargo and probably more) #110078
- [x] `thiserror-impl`: (gitoxide through cargo) #110081
- [ ] `zerovec-derive`: (used in icu4x)
- [ ] `yoke-derive`: (used in icu4x)
- [ ] `zerofrom-derive`: (used in icu4x)
- [ ] `strum_macros` (spdx, licensing)
- [ ] `unic-langid-macros-impl`
- [ ] `derivative` (unmaintained)
```

- and a few more

Fixing this involes updating the dependencies once they upgrade or contributing upgrades to them directly.

**Comment by jhpratt** [comment]
Mostly an aside: Is there a tracking issue for having a better (more thorough) proc macro API so that `syn` isn't necessary? I know there's `#![feature(proc_macro_quote)]` for output, but I'm not aware of anything for parsing.

**Comment by Manishearth** [comment]
The `databake` and `zerovec` derives are probably in this group. We should update ICU4X, and I can cut patch releases for those crates once we land the syn update upstream.

**Comment by GrigorenkoPV** [comment]
As you might have seen from the mentions, I have submitted a PR replacing `derivative` with a maintained alternative (#127042) and politely pestered the `spdx-rs` maintainers about making a new release (doubleopen-project/spdx-rs#33). When (and if) those two go through, the `syn 1.*` will officially be no more.

**Comment by GrigorenkoPV** [comment]
This will be closed by #154823
