### ISSUE TITLE
Tracking Issue for `#[track_caller]` on async fn

### ISSUE THREAD

**Issue by bryangarza** [rust-lang/rust#110011]
This is a tracking issue for `#[track_caller]` on async fn.
The feature gate `#[feature(async_fn_track_caller)]` for the issue is not implemented yet (https://github.com/rust-lang/rust/issues/110009)

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement https://github.com/rust-lang/rust/issues/110009

- [ ] Update tracking behavior (see Unresolved Questions)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

(Copied over from: https://github.com/rust-lang/rust/issues/87417#issuecomment-1496735888)

It's not 100% clear that tracking the poller, rather than the original caller, is the ideal behavior. That said, we may still be able to resolve the question without an RFC.

Arguments in favor of tracking the poller (current behavior):

- The user might expect to see the call that's happening now rather than one that happened in the past.
- Prevents us from having to store the caller in the Future type.
- Usually poller and caller are the same function, anyway, so we should do the simpler and more performant thing.

Arguments in favor of tracking the original caller instead of the poller:

- User might expect to see the actual caller; especially given the name track_caller, showing the poller can confusing.
- A &'static Location is only one pointer; storing it is not so bad.
- Combinators won't need to add #[track_caller] to "thread through" the caller information.
- If we tracked the poller, #[track_caller] on a spawned task would show the executor.
  - There's no way today for the executor to save off caller location information (e.g. in spawn) and re-provide it to the polled function, even if it wanted to. We could fix this with a set_caller API.
  - Tracking won't work for &dyn Future. Executors can easily work around this if they have an API with access to the underlying type before coercing to dyn, as most do ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=815c4e7373f6d21e3f5a1bb5bdfb8872)). But if you happen to already have a dyn Future, you'll be stuck.

### Implementation history

- https://github.com/rust-lang/rust/pull/104219
- https://github.com/rust-lang/rust/pull/104741
- https://github.com/rust-lang/rust/pull/105180

**Comment by bryangarza** [comment]
FYI @tmandry -- and btw could you help me to add the right labels to this and https://github.com/rust-lang/rust/issues/110009 please? I don't have permission to edit those.

**Comment by tmandry** [comment]
> It's not 100% clear that tracking the poller, rather than the original caller, is the ideal behavior. That said, we may still be able to resolve the question without an RFC.

@rust-lang/wg-async discussed in [this zulip thread](https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AI-async-nominated). We were leaning toward tracking the original caller rather than the poller, based on the use case we knew about (assertion helpers). If there are other use cases or points of agreement/disagreement with this, please leave them in the linked zulip thread.

**Comment by Swatinem** [comment]
Another idea worth revisiting here may be:
In https://github.com/rust-lang/rust/pull/104833, I also added `#[track_caller]` support for async blocks. Pretty much because it was trivial to do so, and actually supporting it separately would have been more work.

It might still be worth doing that, specifically to split that into its own `track_async_block_caller` or similar feature.

**Comment by CryZe** [comment]
It probably makes sense to simply allow the user to choose:
```rust
#[track_caller(poll)]
```
or
```rust
#[track_caller(original)]
```
(+- bikeshedding on the names)

**Comment by theemathas** [comment]
Lang-nominating to request stabilization, as the one unresolved question seems relatively easy to decide on. See discussion at [#wg-async > async_fn_track_caller stablization status?](https://rust-lang.zulipchat.com/#narrow/channel/187312-wg-async/topic/async_fn_track_caller.20stablization.20status.3F/with/609880035)

**Comment by traviscross** [comment]
We do our stabilization decisions on PRs and on the basis of the stabilization report and accompanying Reference PR.  So the best we could do here, in the meeting, would be to invite a stabilization PR and offer any thoughts we have about things we might want to see there.

**Comment by traviscross** [comment]
We talked about this in the lang call today.  @tmandry will give a fuller write-up.  In summary, we'd invite a stabilization PR and report on this.  On the semantics, we were inclined toward `track_caller` tracking the original caller rather than the function polling the future.

**Comment by tmandry** [comment]
There are a few reasons to prefer `#[track_caller]` pointing to the original caller.

First, it's the simplest and most obvious thing to do. It's more likely to be what users expect from the attribute based on how it behaves on normal functions, and it leads to a simpler desugaring where `#[track_caller] async fn foo()` desugars to `#[track_caller] fn foo() -> impl Future`.

From a usefulness standpoint, generally with `#[track_caller]` we want to point to the user code that is "at fault" for an error or panic. This is more likely to be the original call site for a couple of reasons:

1. The function call site contains arguments which may have caused the error, whereas the poll site is doing nothing but polling. The only thing that can be varied is when and whether poll was called, and it's rare that this is the thing at fault.
2. The future may be polled by a combinator. If that combinator is missing `#[track_caller]` on its poll function, we would point inside the combinator, which is rarely what you want.

The exceptions, e.g. when you manually poll a future too many times and it panics, might be better served by `#[track_caller(poll)]` as someone suggested, or by backtraces, or even by adding an implicit `#[track_caller]` to all compiler-generated poll functions of async blocks and functions in debug mode. But it doesn't really make sense as the default behavior for `#[track_caller]`. The main drawback is that we would have to save the caller in the future, but given that the attribute is opt-in and this seems like the most correct behavior, it's a reasonable cost.

**Comment by theemathas** [comment]
In the process of trying to stabilize this feature, I found out that the currently implemented behavior is incorrect. `#[track_caller]` currently reports the location as being at the poll site, but it should report the function call site. That needs to be fixed before stabilization.
