### ISSUE TITLE
Tracking issue for dejargonification

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#110254]
There are some things in rustc that are named historically or just really oddly. This issue tracks renaming them to reflect what they are without having to understand Rust's history and/or programming language design/theory jargon.

* [ ] Region -> Lifetime in general. While Region kinda makes more sense, we use Lifetime in the language
* [ ] `EarlyBoundRegion` -> `GenericLifetime` (to reflect what they are in the language)
* [ ] `LateBoundRegion `->`HigherRankedLifetime` (")
* [ ] `*Folder` and `fold_*` -> `*Replacer` and `replace_*`
* [ ] `Substs` -> `GenericArgs`
* [ ] `subst` -> `replace_generics`

These changes have an accepted MCP at https://github.com/rust-lang/compiler-team/issues/451

**Comment by lqd** [comment]
Maybe we can also finally pick one of "free region" vs "universal region", or something else t-types would prefer. (IIRC sometimes there's even both names used in the same function :)

**Comment by Nilstrieb** [comment]
If you want to discuss the naming, use this zulip thread instead: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/naming.20bikeshedding
