### ISSUE TITLE
Tracking Issue for removing `impl const` and `~const` in the standard library

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/rust#110395]
This is a tracking issue for removing `impl const` and `~const` in the standard library. This is carried out so that migrating to a new implementation under keyword generics can go more smoothly. See [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/.60const.20Trait.60.20removal.20or.20rework) for discussion around this operation.

For temporary preview of the effects rewrite, add `feature(effects)` to your crate code. Most bugs/misbehaviors are known so consider [opening a thread](https://rust-lang.zulipchat.com/#narrow/stream/419616-t-compiler.2Fproject-const-traits) on the project-const-traits stream on Zulip before opening an issue.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Remove unstable features that currently use const traits: #110393 
- [x] Remove logic in the compiler around const traits to allow a better implementation
   * #114134
   * #114202
   * #114781
- [ ] Land a better implementation in the compiler (see previous attempt at #101900).
   * #113210
   * #114203
   * #114545
   * #115727
   * #115817 
   * #115850 
   * #115859
   * #116210
   * #116670
   * #116756 
   * #116870
   * #116872
   * #117171 
   * #117817
   * #118245
   * #118246
   * #118282
   * #118386
   * #118605  
   * #118608 
   * #120639
- [ ] Restore unstable features using const traits
   * #116856
   * #117825 
   * #120381
   * #126552
```[tasklist]
### Tasks
```

**Comment by Thomasdezeeuw** [comment]
It would have been nice to update the old tracking issue: https://github.com/rust-lang/rust/issues/92391 so that people that actually try these feature are notified when things (are going to) change, instead of just breaking their code one day...

**Comment by zraineri** [comment]
For people whose code this broke you can use the nightly feature [rustc_attrs](https://doc.rust-lang.org/beta/unstable-book/language-features/rustc-attrs.html) along with the attribute [rustc_do_not_const_check]( https://doc.rust-lang.org/beta/nightly-rustc/rustc_span/symbol/sym/constant.rustc_do_not_const_check.html) when you know it's safe. 

Example:
```rust
#![feature(rustc_attrs)]

#[rustc_do_not_const_check]
pub const fn is_equal<T: PartialEq + Copy>(v1: T, v2: T) -> bool {
    v1 == v2
}

pub const fn is_u8_equal(v1: u8, v2: u8) -> bool {
    is_equal(v1, v2)
}
```

Obviously this isn't a realistic example, but should get the point across on how to use it.

Note: I don't have anything to do with this change or the rust team. Someone else may be able to recommend a better alternative, but this has worked for me.

**Comment by AaronKutch** [comment]
Hello, I did not see this coming. I fully understood that, as an unstable feature, `const` traits would likely have their syntax updated, or feature gates changed, or some special cases like around `Destruct` changed, etc. However, I did not expect an almost fundamental looking thing like this to be removed entirely. My crate `awint` depends on a few things but especially `const` `Deref`/`DerefMut`/`AsRef`/`AsMut`/`From` in order to support ergonomic `const` bigint operations and proper storage/DST reference separation. An early version of my crate used a function for this, but literally half of the code was just getting at references. It is going to require thousands of lines of changes within the crate and outside in order to go back to something much worse. How soon is `impl const` going to be reimplemented, and could it be expedited like how they want `const_convert` back? Should I open an issue or is it expected that re`~const`-ifying most of the standard library will come quickly after the reimplementation?

**Comment by fee1-dead** [comment]
Re `~const`-ifying will eventually happen, and once we have a polished enough implementation these features will be restored.

**Comment by fee1-dead** [comment]
@hecatia-elegua: The removal is supposed to make it so that it is easier to land the better implementation. Therefore, the procedure is removal -> better implementation -> restoration. Removing after the better implementation makes no sense, since we'd still want to continue to experiment const traits until stabilization of a better syntax.

**Comment by slightlyoutofphase** [comment]
> Removing after the better implementation makes no sense, since we'd still want to continue to experiment const traits until stabilization of a better syntax.

I may be misunderstanding your wording / intent here, but the removal (which makes it impossible to do certain things that were previously possible with const traits, by any means) seems to be in direct opposition to "continued experimentation".

**Comment by fee1-dead** [comment]
Continued experimentation happens after we improve the implementation in the compiler. There is absolutely no guarantee for unstable features that they will continue to exist tomorrow, since the point of unstable is for us to make breaking changes until it is good enough to be stabilized.

As to why the removal isn't happening alongside the pr that would change the internal compilation, we wanted to make it so that the refactor would be easy to review, therefore including the const traits removal changes in the same pr would be increasing its complexity.

As for partial removal, I don't know either. All const impls should be removed. If not then there might be a mistake.

**Comment by AaronKutch** [comment]
I find it hard to believe that the current implementation is so tangled that it would require tearing out everything up to the API level rather than progressively refactoring the different underlying aspects while keeping the public functionality working continuously. Since there are people freely contributing we can let things slide for a few months, but if the functionality is not restored in, say, by the end of the year I'd call this approach completely botched. A month in, I'm not seeing any progress at all from a cursory search. I sure hope someone has been working on something locally.

**Comment by Nilstrieb** [comment]
Const traits are an unstable feature and as such no guarantees are provided. The people actively working on it know what's best for the future of the feature and have the most experience with it. Most Rust contributors are volunteers, and therefore it's hard to give concrete timelines or plans. If you want to accelerate development of a feature, consider helping instead. If you're interested, join the [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval).

**Comment by Frostie314159** [comment]
The original message should probably be updated, because the second task appears to have been completed(i.e. all PRs merged).

**Comment by Houtamelo** [comment]
What is the status on this RFC? It seems there are only 2 issues left and they are very close to completion.

https://github.com/rust-lang/rust/pull/118386 
Seems to just be waiting for a review.

https://github.com/rust-lang/rust/pull/116872
Author claims that the issue was superseeded by https://github.com/rust-lang/rust/pull/119721, which has already been merged.

**Comment by fee1-dead** [comment]
It is still being worked on, with the most recent work happening at #120639.

**Comment by AaronKutch** [comment]
What's the current status right now?

**Comment by fee1-dead** [comment]
> What's the current status right now?

You're invited to follow development updates on the project goals issue: https://github.com/rust-lang/rust-project-goals/issues/106 :) I'll lock this issue for now because tracking issues are mostly for logging procedural concerns and linking developments, and mostly not for discussion. Feel free to ask on our [Zulip channel](https://rust-lang.zulipchat.com/#narrow/stream/419616-t-compiler.2Fproject-const-traits) in the future.

**Comment by RalfJung** [comment]
I'm confused about what is being tracked here. The issue title talks about tracking the removal of these impls, which AFAIK is completed. So either the issue should be closed or the issue title updated, I think.

**Comment by jhpratt** [comment]
I'm inclined to agree. There is #67792 for the feature itself, so this issue shouldn't be used for that purpose. Everything appears to be completed, so I'll close this issue. If I'm mistaken, feel free to reopen it of course.
