### ISSUE TITLE
Tracking Issue for builtin # syntax

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#110680]
This is a tracking issue for the MCP to add `builtin #` syntax, see https://github.com/rust-lang/compiler-team/issues/580 as well as the zulip [stream](https://rust-lang.zulipchat.com/#narrow/stream/233931-xxx/topic/Add.20builtin.23.20for.20compiler-intrinsic.20syntax.20compiler-team.23580).
The feature gate for the issue is `#![feature(builtin_syntax)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement a scaffolding for the `builtin #` syntax: #110694
- [ ] Adopt `builtin #` syntax in the qualifying places:
  - [x] `offset_of!`: #110694
  - [x] `type_ascribe!`: #122806
  - [x] `deref!(PAT)` #122793
  - [ ] `asm!`/`global_asm!`
  - [ ] `format_args!`
  - [ ] (the list is incomplete)
- There will never be a general stabilization. The sub-syntaxes should be exposed stably in other ways to end users, for example through macros. Alternatively, the syntax should be changed before stabilization to something that doesn't use `builtin #`. In any way, stabilization is specific to each feature that uses `builtin #`.
  
### Unresolved Questions

The MCP lists a few potential use cases for `builtin #`, but the list is not final (and probably will keep changing).

### Implementation history

* #110694
