### ISSUE TITLE
Tracking issue for cleaning up std's thread_local implementation details

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#110897]
`std::thread_local`, `std::thread::local`, `std::thread::local_impl`, `std::sys_common::thread_local_key`, `std::sys_common::thread_local_dtor`, `std::sys::thread_local_key`, etc. etc. are all messy and form quite a confusing maze. Just look at this map I tried to draw of it all:

![tlmap](https://user-images.githubusercontent.com/783247/234870944-1af910ef-81b7-4e7a-b748-e4212f86e2ca.jpg)

AAAaaaaAaa

Time to clean it up.

And maybe also fix some bugs while we're at it. ^^

---

- [x] Initial name and module cleanup without touching implementation: https://github.com/rust-lang/rust/pull/110861
- [x] Remove unused `Key` type: https://github.com/rust-lang/rust/pull/110898
- [x] Fix panic-in-drop handling
  - [x] https://github.com/rust-lang/rust/issues/112285
    - [x] https://github.com/rust-lang/rust/pull/112292
- [x] Stop calling everything `Key`, because most of those things are actually not keys, and drop `LazyKeyInner`
   - [x] rust-lang/rust#116123
   - [x] rust-lang/rust#122494
   - [x] rust-lang/rust#123724
- [x] Reduce the amount of code in the `thread_local!{}` expansion. rust-lang/rust#125525 
- [x] Use `*const T` rather than `&'static T` when it's not really `'static`: rust-lang/rust#125525 
- [x] Clean up implementation more
   - [x] rust-lang/rust#126523
   - [x] rust-lang/rust#126953
   - [x] rust-lang/rust#128135 
- [x] Store thread ID and stack guard range in thread locals without destructors (on platforms with `#[thread_local]`)?
   - [x] Stack guard range: rust-lang/rust#123265 
   - [x] thread ID: rust-lang/rust#124881
- [x] Make `thread::current` thread local more efficient and make it available in (most) TLS destructors: rust-lang/rust#127912 
- [ ] Detect stack overflow in TLS destructors: rust-lang/rust#131282 

Related issues to solve, maybe:

- [x] https://github.com/rust-lang/rust/issues/110708
- [ ] https://github.com/rust-lang/rust/issues/111272
  - ~~https://github.com/rust-lang/rust/issues/109785~~ 
- [ ] Maybe [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=06885c38ad9982ec799d012a26d92305) shouldn't work? See conversation around [this comment](https://github.com/rust-lang/rust/issues/110897#issuecomment-1525738849).
- [ ] ...?

**Comment by joboet** [comment]
`LazyKeyInner` unfortunately can't just be `OnceCell` because of reentrant initialization: Because `OnceCell::get_or_init` returns a shared reference to the data that lives for the duration of `self`, it [cannot change the value](https://github.com/rust-lang/rust/blob/6ce22733b973355573efd1e6294e585460e90e17/library/core/src/cell/once.rs#L188) after the first inner initialization. `LazyKeyInner` can do that ([and does](https://github.com/rust-lang/rust/blob/6ce22733b973355573efd1e6294e585460e90e17/library/std/src/sys/common/thread_local/mod.rs#L69-L71)) because the references cannot outlive `LocalKey::with`.

**Comment by m-ou-se** [comment]
@joboet In what situation would [that `mem::replace` call](https://github.com/rust-lang/rust/blob/6ce22733b973355573efd1e6294e585460e90e17/library/std/src/sys/common/thread_local/mod.rs#L69-L71) replace a `Some` instead of a `None`? Is that the right behaviour? Do we have a test for that situation?

**Comment by joboet** [comment]
It's very cursed, but [this works](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=06885c38ad9982ec799d012a26d92305). I don't think it's currently tested, however.

**Comment by m-ou-se** [comment]
That just seems like a bug to me. A (thread local) `static &'static str` (not mut, not a cell) shouldn't be able to have different values at different times (on the same thread).

**Comment by joboet** [comment]
Maybe :smile:? It's sound however, as there can be no references to the data from the first initialization when the new value is written.

**Comment by m-ou-se** [comment]
> It's sound

Sure, but so would OnceCell be. ^^ And I think users should be able to safely assume that an immutable `static` never changes. (And as a bonus we get to delete code.)

**Comment by workingjubilee** [comment]
!["We've all come to rely on undocumented endpoints in your API." "And this gives you power over me?"](https://user-images.githubusercontent.com/46493976/235007732-304c79cf-2c9d-4bc3-96e0-d0317b146a56.png)

**Comment by m-ou-se** [comment]
In this case I don't think anyone actually relies on LazyKeyInner being a OnceOrMaybeTwiceIfYouTryReallyHardCell instead of just a OnceCell. ^^

**Comment by joboet** [comment]
I'd advocate for a crater run, just in case, but yes.

**Comment by workingjubilee** [comment]
It is extremely unlikely someone is going to have tests that stress this exact point sufficiently for it to be revealed.

**Comment by joboet** [comment]
Ok, yes, it's actually [part of the documentation](https://doc.rust-lang.org/nightly/std/thread/struct.LocalKey.html#initialization-and-destruction). Nevermind, then.

**Comment by thomcc** [comment]
Thanks for this, I've been very unhappy with the `thread_local!` impl for a long time (@ChrisDenton has had to listen to me gripe about it many times). It's something I was hoping to get to back last fall, but then got a dayjob that takes up much of my time. I think you hit the big issues. Here are some other ones

1. Fixing our (mis)use of `__dso_handle`/`__cxa_thread_atexit_impl` (https://github.com/rust-lang/rust/issues/88737). That issue has a lot of writing and some of it is made with incomplete understanding of the issue (I think), so I've summarized in a gist: https://gist.github.com/thomcc/8c4a8003cf1a282949a539e899cb45aa (initially it was going to be part of this comment).

2. Lots of code does unnecessary reads from `#[thread_local]`s, which, while generally fast, can be very slow in cases like dynamic libraries (where it has to call a function that sometimes takes a lock, walks linked lists, etc).

	Some of this is just a quirk of the compiler (https://doc.rust-lang.org/nightly/src/std/sys/common/thread_local/fast_local.rs.html#182-198), but our "fast" impl actually uses two `#[thread_local]` variables now, which guarantees such behavior (that said, I only realized this yesterday and intend to fix it today).

3. Related to that code, the non-`const` version ends up pessimizing things (especially the `!needs_drop` case) to avoid extra TLS reads on macOS: https://github.com/rust-lang/rust/blob/7452822843cf461b56742f0fc648af35889a3070/library/std/src/sys/common/thread_local/fast_local.rs#L182-L199.

	This might be fixed in LLVM now, and if not could be worked around by using either `compiler_fence` or (if all else fails) `black_box`.

	(Alternatively, it's possible for us to do semi-dubious things with the fact that `std` is allowed to unstabley use `needs_drop<T>()` as a `const fn`...)

There are a few others I had written down (multiple implementations of the manual tls-dtor list) but you touch on them and it might be outdated given https://github.com/rust-lang/rust/pull/109858.

**Comment by robertbastian** [comment]
This might have caused #126992
