### ISSUE TITLE
Tracking Issue for `--extern force`

### ISSUE THREAD

**Issue by mhammerly** [rust-lang/rust#111302]
This is a tracking issue for the MCP https://github.com/rust-lang/compiler-team/issues/605: `force` option for `--extern` flag.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implementation: https://github.com/rust-lang/rust/pull/109421
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- [ ] The syntax for adding options to --extern flags was added without much bikeshedding or discussion. It may need adjusting to be more flexible for more complex options.
- Refer to https://github.com/rust-lang/rust/issues/98405
### Implementation history

- https://github.com/rust-lang/rust/pull/109421
