### ISSUE TITLE
Tracking Issue for `--crate-version` in rustc

### ISSUE THREAD

**Issue by LukeMathWalker** [rust-lang/rust#111467]
This is a tracking issue for [the MCP](https://github.com/rust-lang/compiler-team/issues/622): add `--crate-version` to `rustc`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the MCP (cc @rust-lang/XXX -- can anyone write up mentoring
      instructions?)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

**Comment by jyn514** [comment]
It looks like you're planning to use --build-id instead now, so I'm going to close this: https://github.com/rust-lang/compiler-team/issues/635
