### ISSUE TITLE
Tracking issue for ConstProp MIR opt

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/rust#111509]
This issue tracks the regression in ConstProp due to https://github.com/rust-lang/rust/pull/110719

Regressed optimizations:
- [ ] array indexing;
- [ ] non-scalar constants;
- [ ] assignment of immutable statics;
- [ ] creating rvalues with non-scalar types;
- [ ] integer-to-pointer transmutes;
- [ ] transmutes of scalar enums.

Remaining to do:
- [ ] port const-prop-lint pass to this new implementation.

**Comment by RalfJung** [comment]
Once this is all done we can also hopefully remove the `ConstPropNonsense` error variant from the interpreter, and just replace those cases by assertions.

**Comment by cjgillot** [comment]
Closing as we went for another implementation.

**Comment by RalfJung** [comment]
Can you add some links to what has been done instead?

**Comment by cjgillot** [comment]
For bookkeeping, this PR replaced legacy const-prop: https://github.com/rust-lang/rust/pull/116012
