### ISSUE TITLE
Tracking Issue for ExitCodeExt on Windows

### ISSUE THREAD

**Issue by AronParker** [rust-lang/rust#111688]
Feature gate: `#![feature(windows_process_exit_code_from)]`

This is a tracking issue for implementing additional `ExitCode`s for Windows.

### Motivation

On Windows it is common for applications to return `HRESULT` (`i32`) or `DWORD` (`u32`) values. These stem from COM based components ([HRESULTS](https://docs.microsoft.com/en-us/windows/win32/api/objbase/nf-objbase-coinitialize)), Win32 errors ([GetLastError](https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-getlasterror)), GUI applications ([WM_QUIT](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-quit)) and more. The newly stabilized `ExitCode` provides an excellent fit for propagating these values, because `std::process::exit` does not run deconstructors which can result in errors. However, `ExitCode` currently only implements `From<u8> for ExitCode`, which disallows the full range of `i32`/`u32` values. This pull requests attempts to address that shortcoming by providing windows specific extensions that accept a `u32` value (which covers all possible `HRESULTS` and Win32 errors) analog to [ExitStatusExt::from_raw](https://doc.rust-lang.org/std/os/windows/process/trait.ExitStatusExt.html#tymethod.from_raw).

This was also intended by the original Stabilization https://github.com/rust-lang/rust/pull/93840#issue-1129209143=  as pointed out by @eggyal in https://github.com/rust-lang/rust/issues/97914#issuecomment-1151076755:

> Issues around platform specific representations: We resolved this issue by changing the return type of report from i32 to the opaque type ExitCode. __That way we can change the underlying representation without affecting the API, letting us offer full support for platform specific exit code APIs in the future.__

[Emphasis added]

### Public API

```rust
/// Windows-specific extensions to [`process::ExitCode`].
///
/// This trait is sealed: it cannot be implemented outside the standard library.
/// This is so that future additional methods are not breaking changes.
#[stable(feature = "windows_process_exit_code_from", since = "1.63.0")]
pub trait ExitCodeExt: Sealed {
    /// Creates a new `ExitCode` from the raw underlying `u32` return value of
    /// a process.
    #[stable(feature = "windows_process_exit_code_from", since = "1.63.0")]
    fn from_raw(raw: u32) -> Self;
}

#[stable(feature = "windows_process_exit_code_from", since = "1.63.0")]
impl ExitCodeExt for process::ExitCode {
    fn from_raw(raw: u32) -> Self {
        process::ExitCode::from_inner(From::from(raw))
    }
}
```

### Steps / History

- [x] ACP: https://github.com/rust-lang/libs-team/issues/48
- [x] Implementation: https://github.com/rust-lang/rust/pull/97917
- [x] https://github.com/rust-lang/rust/pull/118218
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

### Additional Links

- https://github.com/rust-lang/rust/pull/93445#issue-1117891580

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by eggyal** [comment]
Kind of you to credit me for quoting that comment, but really it would make more sense to attribute it to the original author @yaahc (both to provide better context and also to draw their attention to this issue).

**Comment by AronParker** [comment]
Right sorry, I updated the link. It's just what I had in mind at the time that's why I made the link, but of course crediting @yaahc makes a lot more sense.

**Comment by rust-rfcbot** [comment]
Team member @dtolnay has proposed to merge this. The next step is review by the rest of the tagged team members:

* [x] @Amanieu
* [ ] @BurntSushi
* [x] @dtolnay
* [x] @joshtriplett
* [ ] @the8472

No concerns currently listed.

Once a majority of reviewers approve (and at most 2 approvals are outstanding), this will enter its final comment period. If you spot a major issue that hasn't been raised at any point in this process, please speak up!

See [this document](https://github.com/rust-lang/rfcbot-rs/blob/master/README.md) for info about what commands tagged team members can give me.

**Comment by rust-rfcbot** [comment]
:bell: **This is now entering its final comment period**, as per the [review above](https://github.com/rust-lang/rust/issues/111688#issuecomment-3786967400). :bell:

**Comment by rust-rfcbot** [comment]
The final comment period, with a disposition to **merge**, as per the [review above](https://github.com/rust-lang/rust/issues/111688#issuecomment-3786967400), is now **complete**.

As the automated representative of the governance process, I would like to thank the author for their work and everyone else who contributed.
