### ISSUE TITLE
`offset_of!` ecosystem testing

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#111839]
I'm filing this issue to get some testing of the `offset_of` macro, whose implementation has recently been merged in #106934 .

There is already widespread use of the `offset_of` macro in the ecosystem through an implementation supporting stable via the `memoffset` crate, whose version 0.9.0 supports the `unstable_offset_of` feature due to https://github.com/Gilnaa/memoffset/pull/72. So for a lot of the users, testing out is as simple as updating `memoffset` and running the tests with the `unstable_offset_of` feature enabled. Thankfully, for testing one doesn't have to add that feature to Cargo.toml, creating a requirement on nightly, one can just add `--features memoffset/unstable_offset_of` and it will work.

The biggest [reverse dependencies](https://crates.io/crates/memoffset/reverse_dependencies) of `memoffset` are:

- [x] crossbeam-epoch: [PR](https://github.com/crossbeam-rs/crossbeam/pull/981)
- [x] nix: [PR](https://github.com/nix-rust/nix/pull/2042)
- [x] rustix: [PR](https://github.com/bytecodealliance/rustix/pull/689)
- [x] pyo3: [PR](https://github.com/PyO3/pyo3/pull/3170) [comment](https://github.com/rust-lang/rust/issues/111839#issuecomment-1776996179)
- [x] wayland-sys: [PR](https://github.com/Smithay/wayland-rs/pull/626)
- [x] wasmtime-runtime: [PR](https://github.com/bytecodealliance/wasmtime/pull/6731) [comment](https://github.com/rust-lang/rust/issues/111839#issuecomment-1636666703)
- [ ] wasmer-types/wasmer-vm
- [x] field-offset: [PR](https://github.com/Diggsey/rust-field-offset/pull/24) [comment](https://github.com/rust-lang/rust/issues/111839#issuecomment-1776996179)
- [x] rowan: [PR](https://github.com/rust-analyzer/rowan/pull/154)
- [x] glium: [PR](https://github.com/glium/glium/pull/2081) [comment](https://github.com/glium/glium/pull/2081#issuecomment-1776973641)
- [x] intrusive-collections: [PR](https://github.com/Amanieu/intrusive-rs/pull/86)
- [x] imgui: [PR](https://github.com/imgui-rs/imgui-rs/pull/726)
- [x] egui-glow: [PR](https://github.com/emilk/egui/pull/3034)
- [x] virtio-queue: [comment](https://github.com/rust-vmm/vm-virtio/issues/269#issuecomment-1777089890)
- [x] arcstr: [PR](https://github.com/thomcc/arcstr/pull/54)
- [ ] ggez

It would be good to go through this list, and:

1. update the `memoffset` crate to 0.9.0, ideally filing a PR (but not enabling `unstable_offset_of` in Cargo.toml unless the project already requires nightly!) 
2. run `cargo +nightly test --features memoffset/unstable_offset_of` or `cargo +nightly run --features memoffset/unstable_offset_of` etc, trying out the feature and seeing if something is broken, ideally also the `--all` parameter if it's a workspace
3. tell here about the experience

In addition of that, it is useful to get feedback from any project that uses the `memoffset` crate indirectly as a transitive dependency. For that, one also has to wait for the upgrade to 0.9.0 to go through the dependency chain and then one can add a direct (unused) dependency on `memoffset` to enable the feature, and test it out.

For example, field-offset has a large number of [reverse dependencies](https://crates.io/crates/field-offset/reverse_dependencies) that one could go through also. I have made a PR for rustc in https://github.com/rust-lang/rust/pull/112298.

cc #106655 tracking issue

**Comment by sunfishcode** [comment]
With https://github.com/bytecodealliance/rustix/pull/689 I've now updated rustix to memoffset 0.9, and run the tests with `unstable_offset_of`, and everything passed.

**Comment by sunfishcode** [comment]
With https://github.com/bytecodealliance/wasmtime/pull/6731, wasmtime-runtime is now updated to memoffset 0.9, and I've now run the tests with `unstable_offset_of`, and everything passed.

**Comment by sanbox-irl** [comment]
has been merged to main in `imgui-rs` and passes just fine!

**Comment by joshlf** [comment]
Looks like PRs for [pyo3](https://github.com/PyO3/pyo3/pull/3170) and [field-offset](https://github.com/Diggsey/rust-field-offset/pull/24) have merged.

**Comment by joshlf** [comment]
PR for wasmer-types/wasmer-vm: https://github.com/wasmerio/wasmer/pull/4273

**Comment by joshlf** [comment]
Looks like virtio-queue is already done: https://github.com/rust-vmm/vm-virtio/commit/f69ec8a3037b946e2d25a9bc12fdf0e1a17a8d3b

**Comment by joshlf** [comment]
PR for ggez: https://github.com/ggez/ggez/pull/1259

**Comment by ojeda** [comment]
For what it is worth, we have been successfully using it in the kernel for a while, and the first mainline user should be landing soon: https://git.kernel.org/pub/scm/linux/kernel/git/tj/wq.git/commit/?h=for-6.7-rust-bindings&id=7324b88975c525a013ae0db747df97924ce80675.

**Comment by est31** [comment]
@joshlf thanks for filing these pull requests. For checking the checkboxes, can you verify that enabling the `offset_of` mode of `memoffset` works in these repos? As in, the test suite runs successfully with the feature enabled (see point 2 on how to do it).

**Comment by joshlf** [comment]
Confirmed for field-offset.

A lot of the remaining crates are difficult to test locally for one reason or another. I've put up do-not-merge PRs that enable memoffset's `unstable_offset_of` feature so that CI can run on those PRs as a replacement for running the test suites locally.

https://github.com/PyO3/pyo3/pull/3545
https://github.com/rust-vmm/vm-virtio/pull/266
https://github.com/ggez/ggez/pull/1260

**Comment by joshlf** [comment]
Confirmed for [virtio-queue](https://github.com/rust-vmm/vm-virtio/issues/269).

**Comment by joshlf** [comment]
@est31 Are we hoping to get to 100% coverage here, or is 14/16 good enough? (For the remaining 2, we haven't found issues, we've just run into unrelated problems running the test or getting the feature merged.)

**Comment by est31** [comment]
It's not a precise science, my main goal for the list was to give a starting point. I think we can close this particular issue which was mostly to get things started, as projects often use stable only and are afraid to use nightly features (and indeed there is discussions to maybe change the syntax of `offset_of`). Of course, even if this issue is closed, further testing will always be encouraged.

Thanks :heart: @joshlf for your help, and thanks @ojeda and everyone else for confirming that it works for their use cases.

**Comment by ojeda** [comment]
My pleasure!
