### ISSUE TITLE
Tracking Issue for `#![feature(diagnostic_namespace)]`

### ISSUE THREAD

**Issue by weiznich** [rust-lang/rust#111996]
Feature gate: `#![feature(diagnostic_namespace)]`

This is a tracking issue for [RFC 3368](https://github.com/rust-lang/rfcs/pull/3368), which introduces a `#[diagnostic]` attribute namespace for attributes that affect the compiler diagnostics. Using an unknown attribute in this attribute namespace should only result in a warning.

### Public API

```rust

#[diagnostic::something] // generates a lint warning.
pub struct Magic;
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/111780
- [x] Final comment period (FCP)[^1]: https://github.com/rust-lang/rust/pull/119888#issuecomment-1944179957
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/119888

### Unresolved Questions

- None yet. (All unresolved questions in the RFC are related to the design of the `#[diagnostic::on_unimplemented]` attribute, which likely will use a different feature)

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html
