### ISSUE TITLE
Tracking Issue for `std::ffi::c_str` module

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#112134]
Feature gate: `#![feature(c_str_module)]`

This is a tracking issue for the `std::ffi::c_str` module.

### Public API

This adds `{core, alloc, std}::ffi::c_str` modules and migrates some existing types into them. Types will still be re-exported in their current places to ensure compatibility.

The following migrations are made:

* `core::ffi::CStr` => `core::ffi::c_str::CStr`
* `core::ffi::FromBytesUntilNulError` => `core::ffi::c_str::FromBytesUntilNulError`
* `core::ffi::FromBytesWithNulError` => `core::ffi::c_str::FromBytesWithNulError`
* `alloc::ffi::CString` => `alloc::ffi::c_str::CString`
* `alloc::ffi::FromVecWIthNulError` => `alloc::ffi::c_str::FromVecWIthNulError`
* `alloc::ffi::IntoStringError` => `alloc::ffi::c_str::IntoStringError`
* `alloc::ffi::NulError` => `alloc::ffi::c_str::NulError`

And these types are also migrated on the `std` crate as well.

### Steps / History

- [x] API change proposal (ACP)[^1]: rust-lang/libs-team#134
- [x] Implementation: #112136
- [x] Final comment period (FCP)[^2]
- [ ] Stabilization PR

### Unresolved Questions

- [x] Should `c_str` and `c_string` be separated? This was not discussed in the original ACP. Decision: no.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html
[^2]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

This module has been available since 1.78-nightly, and is valuable in tidying all those types you will never need to name out of std::ffi's "Structs" section.

Without modules, are you able to guess whether `std::ffi::IntoStringError` refers to the error type returned by `std::ffi::CString::into_string` or by `std::ffi::OsString::into_string`?

**Before:**
<img src="https://github.com/user-attachments/assets/801530df-8d42-4e9f-b4ea-226b4d8c32c1" width="400">

**After:**
<img src="https://github.com/user-attachments/assets/4ea17ae4-73bd-47df-aa19-c3129c1ecdfe" width="400">

**Comment by clarfonthey** [comment]
Note that the `os_str` module, while part of the initial ACP, was rejected, and isn't part of this tracking issue. If you'd like to include it as part of the FCP, I would not oppose, but that should be stated explicitly instead of being roped in implicitly.

**Comment by joshtriplett** [comment]
For people wanting to follow `std::ffi::os_str`, it's https://github.com/rust-lang/rust/issues/120048 .
