### ISSUE TITLE
Tracking Issue for rustdoc `show-type-layout`

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#113248]
This is a tracking issue for the rustdoc `show-type-layout`/`show_type_layout` feature. This displays the layout layout (size & alignment) of types in the documentation.

This feature was formerly known as `document_type_layout`

Usage is described at [rustdoc unstable features](https://rustwiki.org/en/rustdoc/unstable-features.html#--show-type-layout-add-a-section-to-each-types-docs-describing-its-memory-layout)

Zulip thread for discussion: https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Displaying.20size.20of.20types

## Steps

- [x] Implement the feature: #83501
- [ ] Resolve any issues
  - [ ]  Add support for type aliases https://github.com/rust-lang/rust/issues/91265
  - [ ] #87752
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

## Unresolved Questions

- Exact display output needs work
- How to handle layouts that differ by target
- Handling of generic types, if any

## Implementation history

- Initial implementation: #83501

@rustbot label +T-rustdoc

**Comment by jyn514** [comment]
How does this interact with https://rustwiki.org/en/rustdoc/advanced-features.html#interactions-between-platform-specific-docs? Won't it cause errors or ICEs if you use it on a crate that compiles with rustdoc but not rustc, because you need to run typeck to determine layout?

**Comment by dev-ardi** [comment]
For generics I'd say something along the lines of 
- `1024 bytes + size_of::<T>` if it contains a normal T
- `1024 bytes + size_of::<T> * 2` if it contains two T
- `1024 bytes` if T is phantom

Since this is probably not something that you want in all types what about opting in?

```rs
#[doc_layout("x86_64-unknown-linux-gnu", "i686-unknown-linux-gnu")]
struct MyStruct {...}
```
Which gets deduplicated if it happens to be the same?

**Comment by jyn514** [comment]
i don't think it's true that the layout is some fixed offset like that. if you think about e.g. `Option<fn()>`, it has a completely different layout than `Option<usize>` because it doesn't need to store the discriminant.

**Comment by dev-ardi** [comment]
Heh, that's fair.
What about keeping it simple? It can always be refined later.

```rs
#[doc_layout] // Defaults to target that is building it
struct S<T> {
  a: usize,
  b: T,
  c: Option<T>
  d: SomePrivateStruct<T>,
  e: PhantomData<T>,
  f: SomeOtherZST<T>,
  g: [T; 10],
}
```

`8 bytes + size_of::<T> + size_of::<Option<T> + size_of::<SomePrivateStruct<T>> + size_of::<[T; 10]>`

I think that if we make it opt in it's not bad to leak the private structs.
