### ISSUE TITLE
Tracking Issue for MCP607: Rename `wasm32-wasi` target to `wasm32-wasi-preview1`

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#113364]
This is a tracking issue for the [MCP 607](https://github.com/rust-lang/compiler-team/issues/607).

### Steps
- [x] Rename the target in the compiler https://github.com/rust-lang/rust/pull/110596
- [x] Author blog post https://github.com/rust-lang/blog.rust-lang.org/pull/1099
- [x] Update stdarch submodule https://github.com/rust-lang/stdarch/pull/1417
- [x] Update rustc dev guide submodule https://github.com/rust-lang/rustc-dev-guide/pull/1678
- [ ] Update cargo to provide an alias suggestion on failure
- [ ] Update rustup to add an install alias

### References
- [Ideal target upgrade diagnostics](https://github.com/rust-lang/rust/pull/110596#issuecomment-1571012470)

**Comment by alexcrichton** [comment]
In the meantime, https://github.com/rust-lang/compiler-team/issues/695 was approved and https://github.com/rust-lang/rust/pull/120468 has now merged, giving rise to a [new schedule](https://github.com/rust-lang/rust/pull/120468#issuecomment-1977878747) for this transition.
