### ISSUE TITLE
Tracking Issue for Parallel Rustc Front-end

### ISSUE THREAD

**Issue by SparrowLii** [rust-lang/rust#113349]
This is a tracking issue for **Parallel Rustc Front-end**
This feature will improve compilation speed by parallelizing the process of rustc front end (before the codegen which has been parallelized).

The feature was previously called parallel queries (and it's tracking issue [here](https://github.com/rust-lang/rust/issues/48685)), developed by the former parallel rustc working group. Thanks to their work, developers can currently use parallel rustc by setting `parallel_compiler=true` in `config.toml` when build the compiler.

The parallel rustc working group has rebooted (Hers's the [MCP](https://github.com/rust-lang/compiler-team/issues/567)), which will make parallel front-end the default option in rustc. Below is the task list.

### Steps

- [ ] Solve the problem of single-thread performance reduction
  * [x] https://github.com/rust-lang/rust/pull/107586
  * [x] https://github.com/rust-lang/rust/pull/111755
  * [ ] https://github.com/rust-lang/rust/pull/111713
  * [ ] Specaillize the query caches -- needs a PR here
- [ ] Optimize multi-threading performance
  - [ ] typeck is executed serially -- needs a PR/issue here
- [ ] Enable parallel compilation by default in nightly rustc
  - [ ] run the crator test with `parallel_compiler=true` and `-Zthreads=1`
- [ ] bugs of parallel rustc
  - [x] https://github.com/rust-lang/rust/pull/98570
  - [x] https://github.com/rust-lang/rust/pull/108845
  - [x] Deadlock when printing query stack -- fixed by https://github.com/rust-lang/rust/pull/112708
  - [ ] https://github.com/rust-lang/rust/issues/106930
  - [ ] https://github.com/rust-lang/rust/issues/111520
  - [ ] https://github.com/rust-lang/rust/issues/111521
  - [ ] https://github.com/rust-lang/rust/issues/111522
  - [ ] https://github.com/rust-lang/rust/issues/111528
- [ ] Adjust documentation ([[see instructions on rustc-dev-guide](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-tracking-issue&projects=&template=tracking_issue.md&title=Tracking+Issue+for+XXX#)][doc-guide])
- [ ] Stabilization PR ([[see instructions on rustc-dev-guide](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-tracking-issue&projects=&template=tracking_issue.md&title=Tracking+Issue+for+XXX#)][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### About tracking issues
Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

**Comment by the8472** [comment]
The `core` crate might be a good benchmark for this. You can immediately build it after rustc and it spends about 10% of its walltime in tokenization/parsing/macro-expansion and ~80% in the query parts. The fraction codegen is small in comparison.

**Comment by tigerfsh** [comment]
Have all the work been tentatively scheduled? It's been a long time since there were any updates

**Comment by tigerfsh** [comment]
It's been a long time since there was any update. Has all work been paused？

**Comment by SparrowLii** [comment]
Them main work now is to fix deadlock and ice bugs in the issue [list](https://github.com/rust-lang/rust/labels/WG-compiler-parallel)

I recently submitted a [PR](https://github.com/rust-lang/rust/pull/132051) for an enhanced compiler test to reproduce the issue and successfully located three deadlock bugs. Unfortunately, it takes timeto figure out the cause of these bugs, which is what is making the updates slow.

I expect it will take another 1 to 2 months to fix the remaining bugs, after which the stabilization will begin.

**Comment by safinaskar** [comment]
@SparrowLii
> developers can currently use parallel rustc by setting parallel_compiler=true in config.toml when building the compiler.

As well as I understand there is no such option anymore. Please, update post

**Comment by petrochenkov** [comment]
- Monthly updates for this issue are currently posted to the corresponding project goal's tracking issue https://github.com/rust-lang/rust-project-goals/issues/121
- and also to the project goal's zulip thread [#project-goals > Promoting Parallel Front End (goals#121)](https://rust-lang.zulipchat.com/#narrow/channel/435869-project-goals/topic/Promoting.20Parallel.20Front.20End.20.28goals.23121.29/with/505732451)
