### ISSUE TITLE
Tracking Issue for rustc internal debug printing of infer var universes

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#113582]
#112984 introduced a way for rustc contributors to debug output the universes of ty/const/region vars. [This comment](https://github.com/rust-lang/rust/pull/112984#pullrequestreview-1524848827) lists a variety of things that should be followed up on. Particularly:
- [ ] Introduce `derive(DebugWithInfcx)`
- [ ] Do something about the way that type/consts store universes of infer vars differently than regions which makes debug output worse
- [ ] `DebugWithInfcx` and `InferCtxtLike` should have documentation stating what they are for and why they exist in the form they do (a lot of this can likely be taken from the PR description)

cc @compiler-errors

**Comment by BoxyUwU** [comment]
We no longer are attempting to support this as it is a complete mess :3
