### ISSUE TITLE
Tracking issue for generic consts

### ISSUE THREAD

**Issue by fmease** [rust-lang/rust#113521]
This is a tracking issue for the experimental feature *generic consts* (RFC pending).
The feature gate for the issue is `#![feature(generic_consts)]`.
This experiment is seconded by a lang team member ([Zulip topic][zulip]).

It enables generic parameters and where-clauses on free and associated const items.

Background information:

* https://lcnr.de/blog/generic-const-expressions/
* [Generic Consts (Zulip)][zulip]
* #104400

[zulip]: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Generic.20Consts/near/365186353

### About experimental features

An experimental feature is one that has not yet had an RFC. The idea is to allow implementation work to proceed to better inform an upcoming RFC. Experimental features cannot be stabilized without first having an RFC. The existence of an experimental feature does not indicate lang team consensus that the feature is desirable, only that there is the problem is worthy of being solved and that the idea has enough merit to consider exploring. See [the lang team process page][experimental] for more details.

[experimental]: https://lang-team.rust-lang.org/how_to/experiment.html

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the experiment: #NNNNNN
- [ ] Write an RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Experimental results

Part of the goal of the experimental process is to identify benefits but also concerns that need to be addressed in the RFC. This section catalogues notable findings thus far.

*None so far.*

### Implementation history

* #NNNNNN

**Comment by ytmimi** [comment]
Making a note that there's an issue in rustfmt related to `#![feature(generic_const_items)]`  https://github.com/rust-lang/rustfmt/issues/5995.

Edit: The issue should be resolved by https://github.com/rust-lang/rustfmt/pull/5996
