### ISSUE TITLE
Tracking Issue for the Rust specification

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#113527]
This is a tracking issue for [the RFC "XXX" (rust-lang/rfcs#NNN).](https://github.com/rust-lang/rfcs/pull/3355)

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Decide to start a Rust specification
- [ ] Hire the editor (Rust Foundation)
    - [x] Acquire budget
    - [ ] Find the right candidate
- [ ] Start a specification (sub)team (Language team)
- [ ] Write the specification draft (Editor and specification team)
    - [ ] ...
    - [ ] ...
- [ ] Decide on the exact name/title of the document
- [ ] Remove draft status and officially publish the document
- [ ] Maintain it forever

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

I'm going to remove the nomination as, while this is an important initiative for the lang team to track, there's not a specific question or request for a next step from the lang team right now.  Whenever there is such a thing, of course, please nominate that.

**Comment by rmcnew** [comment]
From https://blog.rust-lang.org/inside-rust/2023/11/15/spec-vision.html, it seems that the "Hire the editor" and "Start a specification team" tasks are complete.

**Comment by ehuss** [comment]
Thanks @rmcnew, it should be updated now
