### ISSUE TITLE
`-Ztrait-solver=next` proof tree improvements 

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#113655]
This is a tracking issue for improvements the proof tree implementation for the new solver. Proof trees can be used for debugging by using `-Zdump-solver-proof-tree` and `-Zdump-solver-proof-use-cache=(true|false)`

https://rustc-dev-guide.rust-lang.org/solve/proof-trees.html

For most of the improvements here, please first open a topic [on zulip](https://rust-lang.zulipchat.com/#narrow/stream/364551-t-types.2Ftrait-system-refactor) before working on them. The exact way these should be done aren't still completely clear and there are some fairly strong opinions about how this should work :sparkles:

- [ ] rename "candidate" to "probe"
  - [ ] rename `inspect::CandidateKind` to `ProbeReason` or `ProbeKind`
  - [ ] rename `GoalCandidate` to `Probe`, `candidates` fields, to `(nested_)probes` 
- [ ] change `Candidate` to use an enum instead of a `String`
  - [ ] replace `name` by `kind: CandidateKind` with the probably the following variants, this needs some more involved changes to the code layout as we don't always have this information perfectly available. It's fine to stay partially stringified as the start and have some `CandidateKind::Misc` for now.
    - [ ] `CandidateKind::Trait(assembly::CandidateSource)`
    - [ ] `CandidateKind::AliasRelate(NewEnum)`
    - [ ] and maybe something else I am forgetting right now
- [ ] canonicalize in proof trees to allow their use in diagnostics and for auto traits, the exact way this should work is still unclear, https://hackmd.io/eyieasO3TSma6sqbKBqIQQ?view
- [ ] potentially add option to output proof trees into a file, something like this would be useful, I think that longterm we want an external tool which can remove unnecessary information from proof trees for viewing/debugging.

cc @compiler-errors @BoxyUwU

**Comment by lcnr** [comment]
there has been a lot of change to prove trees and this issue was not helpful at doing so, closing.
