### ISSUE TITLE
"Legacy" tier 2 targets have misplaced or absent maintainer docs

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rust#113739]
### Location

This affects our [platform support documentation](https://github.com/rust-lang/rust/blob/4c8bb79d9f565115637cc6da739f8389e79f3a29/src/doc/rustc/src/platform-support.md).

It specifically affects targets added before the [target tier policy](https://github.com/rust-lang/rust/blob/4c8bb79d9f565115637cc6da739f8389e79f3a29/src/doc/rustc/src/target-tier-policy.md) was confirmed, and especially those that are tier 2.

### Summary

It is widely expected that the existing tier 1 targets are of primary concern for the Rust Project in general and so the absence of formally documented maintainers for them is understandable. As I understand it, we believe we have a large enough surplus of "target maintainers" for them that we can expect these targets to be effectively supported by "whoever picks up the slack".

However, tier 2 targets are trickier. Many are more niche, harder to find and run code on, and require specialized developer knowledge. These realities are essentially _why_ we expect targets to have target maintainers. Yet we have several of them without any documented support. This has recently led to us being forced to respond to [exigent circumstances](https://github.com/rust-lang/rust/issues/113065) by [interrupting our usual support](https://github.com/rust-lang/rust/pull/113274) because they have implicitly violated the other side of the target support "contract": they have impeded development of all the rest of our targets to a degree we cannot accept, with little other recourse.

This is a very bad situation. It is also a bad situation we can attempt to reduce recurrence of. Easily, in fact. Some of our targets have known target maintainers but we just... haven't written them down. Actually writing down who is invested in these targets in the same way other maintainers are listed would help reduce the need for guessing when responding in future high-priority situations where failure to act could stall-out work.

So! We should formally document target maintainers for the following tier 2 targets on the now-common platform support documentation pages. Technically this concern applies somewhat even to tier 3 targets as well but those should be handled in a separate issue as they are quite literally a separate priority level, and also because if this goes unaddressed long enough and another we may have to evaluate reducing tier 2 targets to tier 3.

## Tier 2 with Host Tools

- [ ] `aarch64-apple-darwin`: Arm64 macOS (11.0+, Big Sur+)
- [ ] `aarch64-pc-windows-msvc`: Arm64 Windows MSVC
- [ ] `aarch64-unknown-linux-musl`: Arm64 Linux with musl libc
- [ ] `arm-unknown-linux-gnueabi`: Armv6 Linux (kernel 3.2, glibc 2.17)
- [ ] `arm-unknown-linux-gnueabihf`: Armv6 Linux, hardfloat (kernel 3.2, glibc 2.17)
- [ ] `armv7-unknown-linux-gnueabihf`: Armv7-A Linux, hardfloat (kernel 3.2, glibc 2.17)
- [ ] `powerpc-unknown-linux-gnu`: PowerPC Linux (kernel 3.2, glibc 2.17)
- [ ] `powerpc64-unknown-linux-gnu`: PPC64 Linux (kernel 3.2, glibc 2.17)
- [ ] `powerpc64le-unknown-linux-gnu`: PPC64LE Linux (kernel 3.10, glibc 2.17)
- [ ] `riscv64gc-unknown-linux-gnu`: RISC-V Linux (kernel 4.20, glibc 2.29)
- [ ] `s390x-unknown-linux-gnu`: S390x Linux (kernel 3.2, glibc 2.17)
- [ ] `x86_64-unknown-freebsd`: 64-bit FreeBSD
- [ ] `x86_64-unknown-illumos`: illumos
- [ ] `x86_64-unknown-linux-musl`: 64-bit Linux with musl libc
- [ ] `x86_64-unknown-netbsd`: NetBSD/AMD64a

## Tier 2

- [ ] `aarch64-apple-ios`: Arm64 iOS
- [ ] `aarch64-unknown-fuchsia`: Arm64 Fuchsia
- [ ] `aarch64-unknown-none-softfloat`: Bare Arm64, softfloat
- [ ] `aarch64-unknown-none`: Bare Arm64, hardfloat
- [ ] `arm-unknown-linux-musleabi`: Armv6 Linux with musl libc
- [ ] `arm-unknown-linux-musleabihf`: Armv6 Linux with musl libc, hardfloat
- [ ] `armebv7r-none-eabi`: Bare Armv7-R, Big Endian
- [ ] `armebv7r-none-eabihf`: Bare Armv7-R, Big Endian, hardfloat
- [ ] `armv5te-unknown-linux-gnueabi`: Armv5TE Linux (kernel 4.4, glibc 2.23)
- [ ] `armv5te-unknown-linux-musleabi`: Armv5TE Linux with musl libc
- [ ] `armv7-unknown-linux-gnueabi`: Armv7-A Linux (kernel 4.15, glibc 2.27)
- [ ] `armv7-unknown-linux-musleabi`: Armv7-A Linux with musl libc
- [ ] `armv7-unknown-linux-musleabihf`: Armv7-A Linux with musl libc, hardfloat
- [ ] `armv7a-none-eabi`: Bare Armv7-A
- [ ] `armv7r-none-eabi`: Bare Armv7-R
- [ ] `armv7r-none-eabihf`: Bare Armv7-R, hardfloat
- [ ] `asmjs-unknown-emscripten`: asm.js via Emscripten
- [ ] `i586-pc-windows-msvc`: 32-bit Windows w/o SSE
- [ ] `i586-unknown-linux-gnu`: 32-bit Linux w/o SSE (kernel 3.2, glibc 2.17)
- [ ] `i586-unknown-linux-musl`: 32-bit Linux w/o SSE, musl libc
- [ ] `i686-unknown-freebsd`: 32-bit FreeBSD
- [ ] `i686-unknown-linux-musl`: 32-bit Linux with musl libc
- [ ] `nvptx64-nvidia-cuda`: --emit=asm generates PTX code that [runs on NVIDIA GPUs]
- [ ] `riscv32i-unknown-none-elf`: Bare RISC-V (RV32I ISA)
- [ ] `riscv32imac-unknown-none-elf`: Bare RISC-V (RV32IMAC ISA)
- [ ] `riscv32imc-unknown-none-elf`: Bare RISC-V (RV32IMC ISA)
- [ ] `riscv64gc-unknown-none-elf`: Bare RISC-V (RV64IMAFDC ISA)
- [ ] `riscv64imac-unknown-none-elf`: Bare RISC-V (RV64IMAC ISA)
- [ ] `sparc64-unknown-linux-gnu`: SPARC Linux (kernel 4.4, glibc 2.23)
- [ ] `sparcv9-sun-solaris`: SPARC Solaris 10/11, illumos
- [ ] `thumbv6m-none-eabi`: Bare Armv6-M
- [ ] `thumbv7em-none-eabi`: Bare Armv7E-M
- [ ] `thumbv7em-none-eabihf`: Bare ArmV7E-M, hardfloat
- [ ] `thumbv7m-none-eabi`: Bare Armv7-M
- [ ] `thumbv7neon-unknown-linux-gnueabihf`: Thumb2-mode Armv7-A Linux with NEON (kernel 4.4, glibc 2.23)
- [ ] `thumbv8m.base-none-eabi`: Bare Armv8-M Baseline
- [ ] `thumbv8m.main-none-eabi`: Bare Armv8-M Mainline
- [ ] `thumbv8m.main-none-eabihf`: Bare Armv8-M Mainline, hardfloat
- [ ] `wasm32-unknown-emscripten`: WebAssembly via Emscripten
- [ ] `wasm32-unknown-unknown`: WebAssembly
- [ ] `wasm32-wasi`: WebAssembly with WASI
- [ ] `x86_64-apple-ios`: 64-bit x86 iOS
- [ ] `x86_64-unknown-fuchsia`: 64-bit Fuchsia
- [ ] `x86_64-pc-solaris`: 64-bit Solaris 10/11, illumos
- [ ] `x86_64-unknown-linux-gnux32`: 64-bit Linux (x32 ABI) (kernel 4.15, glibc 2.27)
- [ ] `x86_64-unknown-redox`: Redox OS

**Comment by thomcc** [comment]
I can volunteer as a maintainer for at least these three.
- `aarch64-apple-darwin`
- `aarch64-apple-ios`
- `x86_64-apple-ios` (which is the x86_64 iOS simulator target, despite the name).

It's worth noting that for many of these there's not a clean place in the documentation to mark a target maintainer.

**Comment by workingjubilee** [comment]
There is definitely a certain degree to which this issue is really about us needing to better organize our documentation and our "search for maintainers" is about finding our `!`s with our own two hands.

**Comment by jonathanpallant** [comment]
Related to this, I found a weird codegen issue on the `thumbv7em-none-eabi` and `thumbv7em-none-eabihf` targets when specifying `-C target-cpu=xxx` and I don't know who to ask about it.

**Comment by jacobbramley** [comment]
From [this earlier comment](https://github.com/rust-lang/rust/issues/113597#issuecomment-1634900279) (but continuing it here since that seems more appropriate):

> I was under the impression that Arm Ltd were maintaining the `thumbv*m-none-eabi*` targets.

We (Arm) look at a few issues in that area, for example if we're tagged or if someone points them our way. However, we are not official maintainers of the embedded targets at the moment! That said, we care about them, so will be watching this with interest. Our day-to-day focus is `aarch64-unknown-linux-gnu` (tier 1), for which I think we are the official maintainers (though I couldn't find a list just now).

**Comment by RalfJung** [comment]
Can confirm -- I'm having some trouble with the sparc64 ABI and I'm not sure whom to ping either.

**Comment by chrisnc** [comment]
I've volunteered to maintain the Armv7-R targets (all four flavors). #110377 #119102

**Comment by jonathanpallant** [comment]
The Embedded Devices WG had a PR cleaning up the docs and adding themselves to the Cortex-M targets, but it got lost. I'll try and open it again.

**Comment by RalfJung** [comment]
Would it be worth making some sort of blogpost, saying that we need people to volunteer as maintainers here and help write the docs for the target support page, or else targets will have to be downgraded to tier 3?

**Comment by jonathanpallant** [comment]
Seems reasonable. I gave all the Cortex-M targets to the EDWG so they can be ticked off.

**Comment by chrisnc** [comment]
The two "armebv7r-none-eabi(hf)? Bare Armv7-R, Big Endian" targets can be checked off as well.

**Comment by RalfJung** [comment]
> Seems reasonable. I gave all the Cortex-M targets to the EDWG so they can be ticked off.

Are those the targets linking do [this page](https://doc.rust-lang.org/rustc/platform-support/arm-none-eabi.html)? That page does not say whom to ping in case of trouble with the target, so I don't think they can be ticked off yet.

(There is no target with "cortex" in its name so I'm afraid I don't know which targets you are talking about.)

**Comment by RalfJung** [comment]
Ah, I see, thanks.

It seems we do have target maintainers listed, but it's an email address, which doesn't work well with our usual github-based workflows. Any chance of having a github handle or [notification group](https://rustc-dev-guide.rust-lang.org/notification-groups/about.html) to ping?

**Comment by jonathanpallant** [comment]
Paging @adamgreig and @therealprof for that as I'm no longer in the WG.

**Comment by workingjubilee** [comment]
Nice, was able to mark off 15 targets as having any maintainer contacts, and a few more are en route.

**Comment by rettichschnidi** [comment]
Me (my employer) is interested [in keeping `armv5te-unknown-linux-gnueabi` a Tier 2 platform](https://github.com/husqvarnagroup/smart-garden-gateway-public). We should be able to invest resources (time, money), but we do not have any compiler experts. Please ping me if anyone out there is in a similar situation.

**Comment by RalfJung** [comment]
@uweigand [mentioned](https://github.com/rust-lang/rust/pull/131258#issuecomment-2447699731)  they could be pinged for s390x related questions. @uweigand would you be willing to be listed as target maintainer?

FYI the [definition](https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/target-tier-policy.md) of that role is

> A tier 2 target must have a designated team of developers (the "target maintainers") available to consult on target-specific build-breaking issues, or if necessary to develop target-specific language or library implementation details. This team must have at least 2 developers. 

Since we currently have 0 maintainers, I think we can make an exception to the "at least 2" rule and allow 1 to be listed (but this wouldn't be enough to get a checkbox in this issue). Maybe you know some people that would also be interested to help? :)

**Comment by uweigand** [comment]
> [@uweigand](https://github.com/uweigand) [mentioned](https://github.com/rust-lang/rust/pull/131258#issuecomment-2447699731) they could be pinged for s390x related questions. [@uweigand](https://github.com/uweigand) would you be willing to be listed as target maintainer?

Yes, I'd be happy to take on that role.

> FYI the [definition](https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/target-tier-policy.md) of that role is
> 
> > A tier 2 target must have a designated team of developers (the "target maintainers") available to consult on target-specific build-breaking issues, or if necessary to develop target-specific language or library implementation details. This team must have at least 2 developers.
> 
> Since we currently have 0 maintainers, I think we can make an exception to the "at least 2" rule and allow 1 to be listed (but this wouldn't be enough to get a checkbox in this issue). Maybe you know some people that would also be interested to help? :)

I'll ask around.

**Comment by RalfJung** [comment]
> Yes, I'd be happy to take on that role.

Awesome. :)

@workingjubilee do you know how the paperwork for that works? :D

**Comment by RalfJung** [comment]
According to https://github.com/rust-lang/compiler-team/issues/812, @psumbera has been our "de facto target maintainer" for Solaris targets. @psumbera , would you be okay with documenting that officially, so that when a Solaris issue comes up, compiler team members can find you in the target list and ping you?

Nominally we need a team of 2 target maintainers for tier 2 targets, but given that currently we have 0 listed, having 1 would be a good improvement. :) But if you happen to know anyone else who might be willing to help with this, that'd be even better. :D

**Comment by RalfJung** [comment]
@Gelbpunkt  @famfo  @neuschaefer  since you are in the process of becoming tier 2 target maintainers for powerpc64le-unknown-linux-musl, I wonder if you know people who are interested in our other powerpc targets? None of them currently have a listed target maintainer, which means they are candidates for eventual demotion to tier 3 if we can't find people who step up to help maintain those targets.

**Comment by RalfJung** [comment]
Thanks for the reply!

I don't have contacts at IBM; @uweigand maybe you could help with that?

**Comment by uweigand** [comment]
> I don't have contacts at IBM; [@uweigand](https://github.com/uweigand) maybe you could help with that?

I'll see what I can find out on the Power side.

**Comment by gilamn5tr** [comment]
@daltenty and myself can serve as the powerpc64le-unknown-linux-gnu maintainers.  I believe we can just open a PR for that to update the docs.  I would rather not be the maintainers for Big Endian PPC variants for 32 bit and 64bit powerpc. It more of a machine access issue. In a pinch we might be able to dig up access but its a non-trivial exercise.

**Comment by apiraino** [comment]
Reminder: people volunteering for maintaining a target (thanks! 🙏 ) can do so by sending a patch to add themself to the maintainers list.

(see [comment](https://github.com/rust-lang/rust/issues/113739#issuecomment-2448390097))

**Comment by RalfJung** [comment]
I checked some boxes for targets that do now have 2 target maintainers listed:
- x86_64-unknown-freebsd
- x86_64-unknown-illumos

**Comment by tgross35** [comment]
I went through the list again, we have picked up more maintainers since https://github.com/rust-lang/compiler-team/issues/896 was accepted:

* aarch64-unknown-linux-musl
* armv7-unknown-linux-gnueabihf
* aarch64-unknown-none-softfloat
* aarch64-unknown-none
* armv7-unknown-linux-gnueabi
* i686-unknown-freebsd
* sparcv9-sun-solaris
* x86_64-pc-solaris

**Comment by tgross35** [comment]
Think I may have some more candidates for T2 and T3 platforms, some more of a reach than others. If you are pinged below and interested in becoming a target maintainer, submit a PR to https://github.com/rust-lang/rust/tree/31c76a10a742d10a749ab4e19cec324864314b70/src/doc/rustc/src/platform-support:

1. Duplicate and fill in `TEMPLATE.md`, listing yourself and any others as a target maintainer
2. Add it to `SUMMARY.md`
3. Link it from relevant targets in the table at `platform-support.md`

It's low commitment, typically this just means that we can ping you when questions about the platform come up. It's fine if you're not an expert: being a contact point who knows where to look or who to ask for more information is already super helpful. (Ralf said a bit more at https://github.com/rust-lang/rust/issues/113739#issuecomment-2447786677.)

---

rust-embedded RISC-V team @almindor @dkhayes117 @romancardenas @MabezDev @jessebraham @rmsyn, you are listed as the maintainers for a few RISC-V targets like [riscv64im-unknown-none-elf](https://doc.rust-lang.org/nightly/rustc/platform-support/riscv64im-unknown-none-elf.html#riscv64im-unknown-none-elf). Would you be willing to sign up for some or all of the following?

* riscv64gc-unknown-none-elf
* riscv64imac-unknown-none-elf
* riscv32gc-unknown-linux-gnu
* riscv32gc-unknown-linux-musl

---

FreeBSD maintainers @asomers @MikaelUrankar, would you be able to claim this target with the others at https://doc.rust-lang.org/nightly/rustc/platform-support/freebsd.html?

* riscv64gc-unknown-freebsd

Cc also @jrtc27 from some libc work on RISC-V FreeBSD.

---

Fuchsia maintainers @erickt @Nashenas88 would you be able to add this one?

* riscv64gc-unknown-fuchsia ✅ 

---

I'll just ping @davidtwco since you're on every relevant team. Could this one be picked up by the embedded arm team and/or Arm, like the other thumb targets?

* thumbv7neon-unknown-linux-gnueabihf

There are also a few misc T3 arm targets:

* aarch64-unknown-linux-gnu_ilp32
* aarch64_be-unknown-linux-gnu
* aarch64_be-unknown-linux-gnu_ilp32
* armv4t-unknown-linux-gnueabi
* armv5te-unknown-linux-uclibceabi
* thumbv7neon-unknown-linux-musleabihf

---

@malbarbo you added x86_64-unknown-linux-gnux32 in https://github.com/rust-lang/rust/pull/45224. Not sure if you have any specific knowledge about that target or if you were just the first one to add it, but in any case, any interest in becoming a target maintainer?

* x86_64-unknown-linux-gnux32

---

@chitao1234 @rtzoeller @mneumann you have done work for rustc or libc on DragonflyBSD in the past (very far past! https://github.com/rust-lang/rust/pull/16073). Would you be interested in adding yourself as a target maintainer, or know somebody else who might be?

* x86_64-unknown-dragonfly

---

@nielx @kallisti5 you were involved with the initial PR adding Haiku support https://github.com/rust-lang/rust/pull/36727 and some libc changes. Would you be interested in adding yourself as a target maintainer, or know somebody else who might be?

* i686-unknown-haiku
* x86_64-unknown-haiku

---

@koachan this is a stretch but you're a SPARC maintainer for LLVM. Do you know anybody who works on Rust+SPARC and wouldn't mind adding themselves as a maintainer? Or would you yourself be interested? (Not sure what your comfort level is but expertise with Rust development isn't even really much of a requirement, knowledge about the arch is more important here.)

* sparc64-unknown-linux-gnu
* sparc-unknown-linux-gnu

---

@seritools IIRC you're doing work on x86-32 Windows, and @bdbai you're a maintainer for thumbv7a-uwp-windows-msvc. Any chance you or somebody you know would be interested in being a target maintainer for these less common Windows targets?

* i686-uwp-windows-gnu
* thumbv7a-pc-windows-msvc

---

@japaric you added MSP430 support back in https://github.com/rust-lang/rust/pull/43099. Any chance you're interested in becoming a target maintainer?

* msp430-none-elf

---

@ayrtonm you just added the mipsel-sony-psx target. Do you know anybody working on PSP that might be willing to become a maintainer?

* mipsel-sony-psp

---

That's the end of a lot of pings.

If you can't be a maintainer but know somebody else who can be, please pass it on. If you're not interested, no worries either!

**Comment by ayrtonm** [comment]
> @ayrtonm you just added the mipsel-sony-psx target. Do you know anybody working on PSP that might be willing to become a maintainer?

@overdrivenpotato did a lot of the initial mipsel-sony-psp stuff, but I don't think he's super involved these days. @sajattack still maintains the rust PSP SDK though so he'd probably be willing to be the maintainer.

**Comment by kallisti5** [comment]
> @nielx @kallisti5 you were involved with the initial PR adding Haiku support https://github.com/rust-lang/rust/pull/36727 and some libc changes. Would you be interested in adding yourself as a target maintainer, or know somebody else who might be?

You can definitely add me.   I'm sure @nielx would probably like to be added as well for Haiku.  Our port is functional and stable... We're mostly fixing crates right now for the platform.

**Comment by tgross35** [comment]
That's great news! It would be best if you (or any other interested maintainer) could create the PR, since there are a handful of questions in the template that you'd be in the best position to answer (pretty simple things like supported versions, how to build+test, etc).

**Comment by sajattack** [comment]
> > [@ayrtonm](https://github.com/ayrtonm) you just added the mipsel-sony-psx target. Do you know anybody working on PSP that might be willing to become a maintainer?
> 
> [@overdrivenpotato](https://github.com/overdrivenpotato) did a lot of the initial mipsel-sony-psp stuff, but I don't think he's super involved these days. [@sajattack](https://github.com/sajattack) still maintains the rust PSP SDK though so he'd probably be willing to be the maintainer.

Yeah I can fill in the template soon-ish (in the next few days, remind me if I forget)

**Comment by koachan** [comment]
> @koachan this is a stretch but you're a SPARC maintainer for LLVM. Do you know anybody who works on Rust+SPARC and wouldn't mind adding themselves as a maintainer? Or would you yourself be interested? (Not sure what your comfort level is but expertise with Rust development isn't even really much of a requirement, knowledge about the arch is more important here.)
>
>    sparc64-unknown-linux-gnu
>    sparc-unknown-linux-gnu

I think @glaubitz / @rorth probably knows someone?

**Comment by rorth** [comment]
> > sparc64-unknown-linux-gnu
> > sparc-unknown-linux-gnu
> 
> I think [@glaubitz](https://github.com/glaubitz) / [@rorth](https://github.com/rorth) probably knows someone?

While Solaris/sparcv9 is already dealt with, I have no idea about the Linux/sparc{,64} side of things.

**Comment by glaubitz** [comment]
> > [@koachan](https://github.com/koachan) this is a stretch but you're a SPARC maintainer for LLVM. Do you know anybody who works on Rust+SPARC and wouldn't mind adding themselves as a maintainer? Or would you yourself be interested? (Not sure what your comfort level is but expertise with Rust development isn't even really much of a requirement, knowledge about the arch is more important here.)
> > sparc64-unknown-linux-gnu
> > sparc-unknown-linux-gnu
> 
> I think [@glaubitz](https://github.com/glaubitz) / [@rorth](https://github.com/rorth) probably knows someone?

Maybe @thejpster would like to pick this up. He's been quite active on `sparc*-linux`.

**Comment by thejpster** [comment]
I’m afraid my SPARC interest here is mostly bare-metal on LEON 3 and LEON 5. I’ve been happy to try and build toolchains for SPARC V9 Linux on cfarm but given how broken I’ve found things I cannot commit to being the maintainer and getting it all fixed.

**Comment by malbarbo** [comment]
@tgross35 I cannot maintain x86_64-unknown-linux-gnux32.

**Comment by romancardenas** [comment]
> rust-embedded RISC-V team [@almindor](https://github.com/almindor) [@dkhayes117](https://github.com/dkhayes117) [@romancardenas](https://github.com/romancardenas) [@MabezDev](https://github.com/MabezDev) [@jessebraham](https://github.com/jessebraham) [@rmsyn](https://github.com/rmsyn), you are listed as the maintainers for a few RISC-V targets like [riscv64im-unknown-none-elf](https://doc.rust-lang.org/nightly/rustc/platform-support/riscv64im-unknown-none-elf.html#riscv64im-unknown-none-elf). Would you be willing to sign up for some or all of the following?
> 
>     * riscv64gc-unknown-none-elf
> 
>     * riscv64imac-unknown-none-elf
> 
>     * riscv32gc-unknown-linux-gnu
> 
>     * riscv32gc-unknown-linux-musl

From my side, I have no issues being the maintainer of `riscv64gc-unknown-none-elf` and `riscv64imac-unknown-none-elf`. I have no prior experience with Linux targets for RISC-V.

**Comment by glaubitz** [comment]
> I’m afraid my SPARC interest here is mostly bare-metal on LEON 3 and LEON 5. I’ve been happy to try and build toolchains for SPARC V9 Linux on cfarm but given how broken I’ve found things I cannot commit to being the maintainer and getting it all fixed.

I wouldn't call the port broken. We haven't seen any issues with `sparc64-linux-gnu` in Debian. It initially had some issues that needed to be ironed out, but it works fine most of the time.

If no one else wants to step up being a maintainer, I'll do it.

**Comment by chitao1234** [comment]
I'm happy to take the role as a maintainer for the x86_64-unknown-dragonfly target if no one else wants to step up.

**Comment by erickt** [comment]
We will take ownership over riscv64gc-unknown-fuchsia, I’ll try to get a PR out for it later on today.

**Comment by seritools** [comment]
> @seritools IIRC you're doing work on x86-32 Windows

sorry, I have zero experience with UWP or Surface RT 😅

i586-pc-windows-msvc from the original post was retired, so there isn't much here I could reasonably adopt I believe

**Comment by jieyouxu** [comment]
Hm, it looks like `riscv64im-unknown-none-elf` was misplaced in the summary tables, it's actually a [Tier 3](https://doc.rust-lang.org/nightly/rustc/platform-support/riscv64im-unknown-none-elf.html) target. Fixing that in #162626.

**Comment by bdbai** [comment]
@tgross35 Unfortunately I am not using GNU toolchain on Windows for i686-uwp-windows-gnu, and I don't have a proper device to test out thumbv7a-pc-windows-msvc. IIUC only thumbv7a-uwp-windows-msvc would work on my Lumia phone.
