### ISSUE TITLE
Tracking Issue for `cstr_count_bytes`

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#114441]
Feature gate: `#![feature(cstr_count_bytes)]`

This is a tracking issue for adding a `.count_bytes()` method to `CStr`.

### Public API

```rust
impl CStr {
    pub fn count_bytes(&self) -> usize;
}
```

### Steps / History

- [x] ACP: https://github.com/rust-lang/libs-team/issues/256
- [x] Implementation: https://github.com/rust-lang/rust/pull/114443
- [x] Final comment period (FCP)[^1] https://github.com/rust-lang/rust/issues/114441#issuecomment-2016942573
- [ ] Stabilization PR https://github.com/rust-lang/rust/pull/123661

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

I propose stabilizing this signature, including the constness:

```rust
impl CStr {
    pub const fn count_bytes(&self) -> usize;
}
```

Here is the comment where our team made the suggestion to expose this under the name `.count_bytes()`: https://github.com/rust-lang/libs-team/issues/256#issuecomment-1697423133

New developments since then: the `CStr::bytes` iterator was added just last week in https://github.com/rust-lang/rust/pull/104353. With that, an alternative spelling to evaluate would be `.bytes().count()` using the `Iterator` trait's `count` (possibly with a non-default implementation specific to this impl for performance). But this couldn't be `const` until perhaps the distant future, and wouldn't be straightforwardly locatable in the method list of `CStr` or in autocomplete..

This method comes with a doc alias that makes it show up in rustdoc search for `strlen`.

<p align="center"><img src="https://github.com/rust-lang/rust/assets/1940490/27e28fee-2b32-426f-9004-729a802f9dc2" width="500"></p>

The constness of this signature has so far been tracked separately under https://github.com/rust-lang/rust/issues/113219, and involves a T-lang matter. I have proposed an FCP in that issue in parallel to this one that would relinquish the constness of `count_bytes` into a T-libs-api decision only. If both FCPs go through, we stabilize `const fn count_bytes`. If only the FCP here goes through and not the one in https://github.com/rust-lang/rust/issues/113219, then we stabilize `fn count_bytes` and the constness will be left unstable for now.

**Comment by tgross35** [comment]
Since FCP here is nearly done but there are quite a few checkboxes left at https://github.com/rust-lang/rust/issues/113219, I opened https://github.com/rust-lang/rust/pull/123661 to stabilize `count_bytes` without const. When https://github.com/rust-lang/rust/issues/113219 FCP completes, we can const stabilize both.

Thanks @dtolnay for moving this forward!
