### ISSUE TITLE
Tracking Issue for RISC-V Ratified Extensions Intrinsics

### ISSUE THREAD

**Issue by coastalwhite** [rust-lang/rust#114544]
This issue tracks the implementation of all the intrinsics linked to the Ratified RISC-V Extensions. The, not yet stable intrinsics are behind the `riscv_ext_intrinsics` nightly feature.

### Steps

- [ ] Implement all extensions in [`stdarch`](https://github.com/rust-lang/stdarch)
  - [x] [Cryptography Extensions Volume I: Scalar & Entropy Source Instructions](https://github.com/riscv/riscv-crypto)
  - [ ] `Zkr`. Entropy source extension
  - [x] [Bit-Manipulation](https://github.com/riscv/riscv-bitmanip)
  - [ ] Zicntr and Zihpm
  - [ ] Zicsr
  - [ ] ~[Half-Precision](https://drive.google.com/file/d/1z3tQQLm5ALsAD77PM0l0CHnapxWCeVzP/view)~
  - [ ] ~[Float in Integer](https://github.com/riscv/riscv-zfinx)~
  - [ ] [Vector Extension](https://github.com/riscv/riscv-v-spec)
- [ ] Adjust module level documentation
- [ ] Stabilization PR 

### Unresolved Questions

- ~How to deal with instructions that are already dealt with by LLVM intrinsics and library features (e.g. `cpop` and `u*::count_ones`)? Include them or not?~
- Use `usize` for riscv32 or `riscv64` specific intrinsics or use `u32` and `u64` respectively?
- ~How to deal with intrinsics involving immediate values?~
  1. ~Use the `asm_const` feature outlined in #93332.~
  2. ~Use the trick described in rust-lang/stdarch#40 and illustrated in [`_mm_cmpestri`](https://github.com/rust-lang/stdarch/blob/ff6021b72e8cc1e7db942847d99278fe0056c245/src/x86/sse42.rs#L286).~
- How to deal with CSR registers?
- Can we source titles and descriptions from the specifications? License issues?
- Dealing with the Vector extension is very difficult due to dynamically sized registers (rust-lang/rfcs#3268).

### Implementation History

- rust-lang/stdarch#1453. Implements the Zk extension, except Entropy Source and Zkt.
- rust-lang/stdarch#1461. Implements the Zb extension.
- #116485. Stabilizes several RISC-V target features.

**Comment by coastalwhite** [comment]
Two additional points:

1. Upcoming PRs should use the `rustc_legacy_const_generics` for immediate values instead.
2. Prefer LLVM intrinsics to assembly. Intrinsics can be found [here](https://github.com/llvm/llvm-project/tree/main/clang/test/CodeGen/RISCV).

**Comment by coastalwhite** [comment]
Entropy Source of the Cryptographic Scalar Extension are not implemented in LLVM. Therefore, it should be implemented with inline assembly and is not part of the implemented intrinsics.

**Comment by coastalwhite** [comment]
Extensions such as `Zfinx`, `Zdinx` and `Zhinx` are all done by LLVM without intrinsics and therefore don't have to be done.

**Comment by michaelmaitland** [comment]
> Dealing with the Vector extension is very difficult due to dynamically sized registers (https://github.com/rust-lang/rfcs/pull/3268).

Do we really need to represent scalable vectors in rust to do this? The C RVV intrinsic types look like [this](https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/main/doc/rvv-intrinsic-spec.adoc#type-system). Those C types, which are not "scalable" are lowered to scalable LLVM types according to the inverse of [this](https://github.com/llvm/llvm-project/blob/e72c949c15208ba3dd53a9cebfee02734965a678/llvm/lib/Target/RISCV/RISCVRegisterInfo.td#L284) table.

**Comment by newpavlov** [comment]
Are there any blockers for stabilizing the crypto and bitmanip intrinsics?

**Comment by tgross35** [comment]
> Are there any blockers for stabilizing the crypto and bitmanip intrinsics?

Assuming the list of features at https://docs.riscv.org/reference/isa/v20260120/unpriv/b-st-ext.html, would that mean only the following?

* https://doc.rust-lang.org/nightly/core/arch/riscv64/fn.orc_b.html (zbb)
* https://doc.rust-lang.org/nightly/core/arch/riscv64/fn.clmulr.html (zbc)
* https://doc.rust-lang.org/nightly/core/arch/riscv64/fn.clmul.html (zbkc)
* https://doc.rust-lang.org/nightly/core/arch/riscv64/fn.clmulh.html (zbkc)
* https://doc.rust-lang.org/nightly/core/arch/riscv64/fn.xperm4.html (zbkx)
* https://doc.rust-lang.org/nightly/core/arch/riscv64/fn.xperm8.html (zbkx)

Those don't seem problematic given they don't use dynamically sized vectors, but they do run into this unresolved question:

> Use `usize` for riscv32 or `riscv64` specific intrinsics or use `u32` and `u64` respectively?

IMO we should use `u32`/`u64` since that's less likely to quietly break your logic if you're testing on 64-bit but only building on 32-bit, and often anything using these will be working with concrete-sized types anyway. @rust-lang/libs any thoughts about this or stabilization?

@rustbot label +I-libs-nominated

**Comment by newpavlov** [comment]
>Assuming the list of features at https://docs.riscv.org/reference/isa/v20260120/unpriv/b-st-ext.html, would that mean only the following?

Personally, I would expect to see all (or almost all) instructions even if respective intrinsics are unlikely to be used in practice explicitly. For example, x86 has [`_bswap64`](https://doc.rust-lang.org/nightly/core/arch/x86_64/fn._bswap64.html) intrinsic which is equivalent to the missing `rev8`. But I guess the missing intrinsics could be added later. For now I am mostly interested in cryptographic intrinsics (i.e. `Zk` extensions).

>IMO we should use u32/u64

I agree.

**Comment by coastalwhite** [comment]
AFAIK there is no real concern about stabilizing the B extension. It just wasn't fully ratified when I started working on it. The main concerns are still some of the floating-point-related extensions, as they impact the ABI. But @workingjubilee did some work on that and probably knows more.

**Comment by beetrees** [comment]
I believe the floating-point concerns have been resolved as `f` and `d` were stabilised in #161385.

**Comment by nia-e** [comment]
The team discussed this in today's meeting and a variety of opinions were expressed, but the overall conclusion is that we'd like to hear from ecosystem users / risc-v people as to which is preferable. Either option is fine, but this kind of conversation is of course very prone to bikeshedding ^^

**Comment by TechnoPorg** [comment]
Although this isn't a very weighty take, I figured I'd chime in to say that my work project uses the RV32 bit manipulation and crypto extensions (currently via inline assembly since we're on stable) and it's more ergonomic for us to work with u32 than usize.
