### ISSUE TITLE
Tracking issue for `-Znext-solver=coherence` (next solver enablement in coherence)

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#114862]
This is a tracking issue for `-Znext-solver=coherence`, and enabling the new solver in coherence mode. The `-Znext-solver=coherence` flag can be used to only enable the new solver for coherence, or `-Znext-solver` can be used to enable the new solver everywhere (see #107374 instead). This work is lead by the @rust-lang/initiative-trait-system-refactor.

### About tracking issues
Tracking issues are used to record the overall progress of implementation. They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions. A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature. Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Implementation history

* https://github.com/rust-lang/rust/pull/109447
* https://github.com/rust-lang/rust/pull/114023
* https://github.com/rust-lang/rust/pull/112122
* https://github.com/rust-lang/rust/pull/121848
* https://github.com/rust-lang/rust/pull/130249

##### Crater runs
* https://github.com/rust-lang/rust/pull/113895
* https://github.com/rust-lang/rust/pull/113991
* https://github.com/rust-lang/rust/pull/116357

### Issues

- [x] incorrect occurs check in projections https://github.com/rust-lang/trait-system-refactor-initiative/issues/8 (fixed by #117088)
- [x] intercrate ambiguity causes/proof tree work
- [x] overflow handling
  - [x] test breakage https://github.com/rust-lang/trait-system-refactor-initiative/issues/70
  - [x] typenum perrrf https://github.com/rust-lang/trait-system-refactor-initiative/issues/73
- [x] normalize for diagnostics, add new folder to `TypeErrCtxt` or sth
- [x] experiment normalizing both sides in `AliasRElate` before equating (perf)
- [x] Blog post asking for testing and experimentation https://blog.rust-lang.org/inside-rust/2023/12/22/trait-system-refactor-initiative.html
* [x] Investigate all the issues of the crater runs
* [x] https://github.com/rust-lang/trait-system-refactor-initiative/issues/65
* [x] https://github.com/rust-lang/trait-system-refactor-initiative/issues/20
    * [x] https://github.com/rust-lang/rust/pull/114023
    * [x] #118649
* [x] https://github.com/rust-lang/trait-system-refactor-initiative/issues/52 accepted breakage, caused by a bug of the old solver https://github.com/rust-lang/rust/issues/114061
* [x] https://github.com/rust-lang/trait-system-refactor-initiative/issues/51
    * [x] https://github.com/rust-lang/rust/pull/114457
* [x] work towards stabilization, writing an FCP proposal and documenting the solver https://rust-lang.zulipchat.com/#narrow/stream/364551-t-types.2Ftrait-system-refactor/topic/coherence.20stabilization
* [x] stabilization PR in #121848
* [x] reverted in #130249 due to #130056
* [ ] restabilize coherence

**Comment by compiler-errors** [comment]
Split this out from https://github.com/rust-lang/rust/issues/107374 so we can track issues specifically blocking coherence. A lot of blockers in the original issue aren't necessarily blockers for coherence.
