### ISSUE TITLE
Tracking Issue for cfg_relocation_model

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/rust#114929]
The feature gate for the issue is `#![feature(cfg_relocation_model)]`.

There isn't an RFC since it is quite a tiny feature exposing what is already stable as cfg entry.

### Steps
- [x] Implement the feature
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions
None, hopefully.

### Implementation history

https://github.com/rust-lang/rust/pull/113966
