### ISSUE TITLE
Tracking Issue for XXX

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#115590]
This is a tracking issue for the RFC "Allow cfg-attributes in where clauses" (rust-lang/rfcs#3399).
The feature gate for the issue is `#![feature(cfg_attribute_in_where)]`.

The intent, as described in the Guide-level explanation, is to enable cfg-attributes on where-clauses, like so:

```rust
impl<T> SomeTrait<T> for Thing
where
    #[cfg(something_a)] T: SomeRequirementA,
    #[cfg(something_b)] T: SomeRequirementB,
{}
```

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC (cc @rust-lang/compiler -- can anyone write up mentoring
      instructions?)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

* [ ] should cfg-attributes be allowed to decorate individual bounds on the right hand side of the colon?

**Comment by recatek** [comment]
Help would certainly be welcome!

**Comment by mj10021** [comment]
Oh, great, I can start working on this very soon (sorry for the delayed reply btw).  I'm assuming I should just ask on Zulip if I get stuck on anything?

**Comment by recatek** [comment]
Wanted to link these here for ongoing work on adding opportunities to use cfg attributes in more places.

https://github.com/rust-lang/rfcs/pull/3532 -- RFC: Allow cfg-attributes on elements of tuple type  #declarations
https://hackmd.io/2k0ZRofFRoqSxdJ5zwmFqg?view -- Comma-Terminated Fragments and #[cfg]
