### ISSUE TITLE
Tracking Issue for `no-jump-tables`

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#116592]
This is a tracking issue for the `-Zno-jump-tables` compiler flag

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC https://github.com/rust-lang/rust/pull/105812
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
  - [x] Unstable docs: https://github.com/rust-lang/rust/pull/116593
- [x] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure]) (N/A)
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [ ] Should this be `-Zjump-tables=false`? C compilers accept both `-fjump-tables` and `-fno-jump-tables`. [#rust-for-linux > Stabilizing &#96;-Zno-jump-tables&#96;? @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/425075-rust-for-linux/topic/Stabilizing.20.60-Zno-jump-tables.60.3F/near/536345902)

### Implementation history

- Implementation: https://github.com/rust-lang/rust/pull/105812

**Comment by tgross35** [comment]
I didn't see a tracking issue for https://github.com/rust-lang/rust/pull/105812 so I created this one. cc @ojeda 

@rustbot label +T-compiler
