### ISSUE TITLE
Tracking Issue for "Add `f16` and `f128` float types"

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#116909]
This is a tracking issue for the RFC 3453 (rust-lang/rfcs#3453).

The feature gate for the issue is `#![feature(f16_and_f128)]`.

From the RFC:

> This RFC proposes adding new IEEE-compliant floating point types `f16` and `f128` into the core language and standard library. We will provide a soft float implementation for all targets, and use hardware support where possible.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

**Comment by tgross35** [comment]
WIP implementation: https://github.com/rust-lang/rust/pull/114607

**Comment by lqd** [comment]
This is a tracking issue and doesn't need prioritization.

**Comment by tgross35** [comment]
A blocking issue should be added: ensure C compatibility with ABI-cafe or similar

https://github.com/rust-lang/rust/pull/114607#discussion_r1421042343

**Comment by tgross35** [comment]
Likely steps for getting this in:

- [ ] Add basic support stubs to IR and backend interfaces https://github.com/rust-lang/rust/pull/121728
- [ ] Add AST support, which probably also means the feature gate
- [ ] Add intrinsics
- [ ] Add minimal library support, which will probably be pretty broken initially
- [ ] Add more complete library support with fixes for parsing and printing
- [ ] Make sure all relevant `unimplemented`s and `FIXME`s are removed from tools that need library support
- [ ] Eventually stabilization

This is based on the suggested pattern at https://github.com/rust-lang/rust/pull/120645#issuecomment-1925900572. I have a more complete reference PR with most of these done at https://github.com/rust-lang/rust/pull/114607

I am trying to consistently use `unimplemented!("f16_f128")` and `// FIXME(f16_f128)` to make needed changes easily greppable.

@rustbot claim

**Comment by wargio** [comment]
@tgross35 we (rizinorg) have merged the changes on our demangling library. i have added also some tests https://github.com/rizinorg/rz-libdemangle/blob/main/test/test_rust.c#L75-L78

**Comment by tgross35** [comment]
> @tgross35 we (rizinorg) have merged the changes on our demangling library. i have added also some tests https://github.com/rizinorg/rz-libdemangle/blob/main/test/test_rust.c#L75-L78

That was super fast :) the update is much appreciated.

Note that the mangling isn't actually finalized but does seem reasonably likely to merge as-is https://github.com/rust-lang/rust/pull/122106

**Comment by wargio** [comment]
i don't think that will be a big issue. i can always fix this once is merged if it ever changes.

**Comment by tgross35** [comment]
@wargio https://github.com/rust-lang/rust/pull/122106 wound up being closed in favor of `C3f16` and `C4f128` (https://github.com/rust-lang/rust/pull/123816), which should already demangle correctly. So I think you should be able to revert the addition. Sorry for the noise!

**Comment by wargio** [comment]
@tgross35 i will. i read about the decision yesterday, so for me is just a couple of lines that needs to be removed. thank you for your wonderful work!

**Comment by uweigand** [comment]
The test suite currently fails on s390x in the following doctests:
```
    library/core/src/num/f16.rs - f16::f16::is_sign_negative (line 377)
    library/core/src/num/f16.rs - f16::f16::is_sign_positive (line 354)
    library/core/src/num/f16.rs - f16::f16::to_be_bytes (line 695)
    library/core/src/num/f16.rs - f16::f16::to_le_bytes (line 716)
    library/core/src/num/f16.rs - f16::f16::to_ne_bytes (line 743)
```
due to
```
rustc-LLVM ERROR: Cannot select: 0x3ffcc0737a0: i32 = fp_to_fp16 0x3ffcc072fc0
```
(which is https://github.com/llvm/llvm-project/issues/50374)

After https://github.com/rust-lang/rust/pull/127235 most doctests are already restricted to x64_64 (or aarch64), but these few listed above remain active on all Linux platforms.  Could those also be restricted for now (until the s390x LLVM back-end is fixed) so that the test suite passes again?  Thanks!

**Comment by tgross35** [comment]
Thanks for reporting, yes those could be restricted too. Feel free to open a PR similar to #127235 if you're up for it, otherwise I'll try to put one up in the next couple days.

**Comment by uweigand** [comment]
> Thanks for reporting @uweigand, yes those could be restricted too. Feel free to open a PR similar to #127235 if you're up for it, otherwise I'll try to put one up in the next couple days.

I've now opened https://github.com/rust-lang/rust/pull/127588, thanks!

**Comment by 86maid** [comment]
Hurry up. I can't wait

**Comment by Neutron3529** [comment]
Warning: `div_euclid` and `rem_euclid` is buggy. I'm not sure whether they need be marked as unsafe, since calculate div/rem with floating types are strongly discouraged.
```rust
#![feature(f16, f128)]
fn main() {
    let a = 1.2f16;
    let b = 1.1f32;
    let c = 1.1f64;
    let d = 1.1f128;
    println!(
        "{} {} {} {}",
        (12f16).div_euclid(a) as f64,
        (11f32).div_euclid(b),
        (11f64).div_euclid(c),
        (11f128).div_euclid(d) as f64
    );
    println!(
        "{} {} {} {}",
        (12f16).rem_euclid(a) as f64,
        (11f32).rem_euclid(b),
        (11f64).rem_euclid(c),
        (11f128).rem_euclid(d) as f64
    );
}
```

**Comment by traviscross** [comment]
@Neutron3529: If you could, the thing to do would be to file a separate issue for that if there isn't one already.  Reference this tracking issue in that new issue.

**Comment by joseluis** [comment]
Could we have `f16` and `f128` re-exported from `::core::primitive` as well? Right now they trigger E0573 error "expected type, found module" while trying to use them as a type from a macro.

**Comment by tgross35** [comment]
Iirc we didn't do this originally because it would require further work in the compiler to feature gate properly (I don't remember why but `#[unstable(...)]` may not have been sufficient) that would not have been worth it at the time. I never looked further and that may not be accurate anymore anyway; feel free to try it and as long as `use core::f128` doesn't work on stable, it can be added.

**Comment by bjoernager** [comment]
Is it possible at this time to implement `From<{u8, i8}>` for `f16` and `From<{u8, i8, u16, i16, u32, i32, u64, i64}>` for `f128`?

**Comment by tgross35** [comment]
That should be possible, we have support in compiler-builtins for the conversions to `f128`. I don't think LLVM will emit a libcall for i8 to f16 but would need https://github.com/rust-lang/compiler-builtins/pull/729 to work if so, though that isn't a blocker for adding the traits.

I wouldn't get to it for a while but feel free to put up a PR. It's probably worth a crater sanity check considering the issues with https://github.com/rust-lang/rust/issues/123824, though I don't expect any problems here.

**Comment by ChrisDenton** [comment]
The maximum intrinsic is missing for wasm targets: https://github.com/rust-lang/rust/issues/158673
