### ISSUE TITLE
Tracking Issue for unicode and escape codes in literals

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#116907]
This is a tracking issue for the RFC 3349 (rust-lang/rfcs#3349).

The feature gate for the issue is `#![feature(mixed_utf8_literals)]`.

From the RFC:

> Relax the restrictions on which characters and escape codes are allowed in string, char, byte string, and byte literals.
>
> Most importantly, this means we accept the exact same characters and escape codes in `"…"` and `b"…"` literals. That is:
>
> - Allow unicode characters, including `\u{…}` escape codes, in byte string literals. E.g. `b"hello\xff我叫\u{1F980}"`
> - Also allow non-ASCII `\x…` escape codes in regular string literals, as long as they are valid UTF-8. E.g. `"\xf0\x9f\xa6\x80"`

### About tracking issues

Tracking issues are used to record the overall progress of implementation. They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions. A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature. Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 

### Unresolved Questions

- [ ] Should `concat!("\xf0\x9f", "\xa6\x80")` work? (The string literals are not valid UTF-8 individually, but are valid UTF-8 after being concatenated.)

**Comment by nnethercote** [comment]
I have a partial implementation of this RFC working locally. It proposes five changes to literal syntax. I think three of them are good, and two of them aren't necessary.

### `b""`: add unicode chars

Adding them fixes the first of two cases where `b""` syntax isn't a superset of `""` syntax. This is good, and facilitates "conventionally UTF-8" string literals.

### `br""`: add unicode chars

Adding them fixes the one case where `rb""` syntax isn't a superset of `r""` syntax. After this, `rb""` syntax and `r""` syntax are the same. This is good, and also facilitates "conventionally UTF-8" string literals.

### `b""`: add `\u{NN}` escapes

Adding them fixes the second of two cases where `b""` syntax isn't a superset of `""` syntax, and fits well with adding unicode chars. This is good.

Note: After adding this, the one thing `b""` syntax has that `""` syntax does not is `\x80-\xff` bytes.

### `""`: add `\x80-\xff`

Is this necessary? What useful new functionality does this provide?

It would make `""` and `b""` syntax identical, but strings and byte strings aren't identical types, so that identicalness isn't needed.

The RFC says "Allowing all characters and all known escape codes in both types of string literals reduces the complexity of the language. We'd no longer have [different escape codes](https://doc.rust-lang.org/reference/tokens.html#characters-and-strings) for different literal types. We'd only require regular string literals to be valid UTF-8." So it has just traded one exception for another. IMO that's not a simplification.

It's odd that it would be possible to write a `""` that isn't valid UTF-8... both conceptually, and in the implementation. For the latter you can no longer start with an empty `String` and append chars one at a time knowing it'll be valid UTF-8 the whole way, which is how it's currently handled. Instead you need to start with a `Vec<u8>`, append chars as byte sequences, and then UTF-8 validate at the end. It's not that difficult, but it's not needed for any other literal kind, and weird enough that, combined with the other points above, makes me question it.

Not doing would keeps `""` syntax consistent with `''`, which makes sense given that `""` and `''` are both unicode-oriented rather than byte-oriented. This is another refutation of the complexity argument above.

Not doing this also renders moot the unresolved question of what to do with `concat!("\xf0\x9f", "\xa6\x80")`.

### `b''`: add `\u{00}-\u{7f}`

Is this necessary? It doesn't provide any useful new functionality.

The `\x` syntax is strictly more powerful, covering the range `\x00-0xff`. And supporting just the ASCII subset of `\u` escapes doesn't match behaviour of any of the other literal syntaxes. Byte literals are about a single byte, why introduce Unicode-related stuff?

The quote from the RFC I mentioned above about complexity applies again, but again, it's just trading one exception for another.

cc @rust-lang/lang @m-ou-se

**Comment by nnethercote** [comment]
Here's an alternative version of the table that I've been using and found helpful. It shows all the escapes directly instead of grouping them by name, it shows the changes proposed by the RFC, and it includes C string literals. The ones I don't like are marked with `(?!)`, and the `a -> u` marking means "changing from ascii to unicode".
```
        chars    escapes                                new escapes
        -----    -------                                -----------
- ''    unicode  \' \" \n \r \t \\ \0 \x00-\x7f \u{..}  N/A

- b''   ascii    \' \" \n \r \t \\ \0 \x00-\xff         \u{0}..\u{7f} (?!)

- ""    unicode  \' \" \n \r \t \\ \0 \x00-\x7f \u{..}  \x80-\xff (?!)
- r""   unicode  N/A 

- b""   a -> u   \' \" \n \r \r \\ \0 \x00-0xff         \u{..}
- br""  a -> u   N/A 

- c""   unicode  \' \" \n \r \t \\ __ \x01-0xff \u{..}  N/A
- cr""  unicode  N/A 
```
This makes it easier to see things like adding `\x80-\xff` to `""` syntax would make it identical to `b""` syntax, but also make "" syntax different to `''` syntax.

**Comment by nnethercote** [comment]
BTW, I have implemented the first three changes. They were pretty easy, and piggy-backed naturally off the existing support for mixed utf8 in C string literals, requiring only minor changes.

I haven't implemented the last two. They would both have required new kinds of checks, slightly annoying to implement, which is what got me thinking about whether they are necessary.

**Comment by nnethercote** [comment]
> BTW, I have implemented the first three changes

A complete draft implementation is now at #120286.

**Comment by nnethercote** [comment]
Nominated for lang-team discussion for [this comment above](https://github.com/rust-lang/rust/issues/116907#issuecomment-1853160194).

**Comment by joshtriplett** [comment]
cc @m-ou-se, who may want to provide input/responses to the above.

**Comment by joshtriplett** [comment]
@nnethercote FWIW, I do feel like having `\u{00}-\u{7f}` in `b'...'` is a clear win: if we allow it in `b"..."`, we should also allow it in `b'...'` as well.

**Comment by nnethercote** [comment]
> @nnethercote FWIW, I do feel like having `\u{00}-\u{7f}` in `b'...'` is a clear win: if we allow it in `b"..."`, we should also allow it in `b'...'` as well.

Is this a consistency argument? Consider [the table](https://github.com/rust-lang/rust/issues/116907#issuecomment-1853166357). Currently some literals don't support `\u` escapes at all, while some support `\u` escapes fully. The proposal is to add a third category, `\u{00}..\u{7f}`, which would only apply to `b''`. I don't think that's a consistency improvement!

Or maybe it's a Postel's law style "we should accept anything that makes sense" argument? If so, I would immediately ask why? The `\xx` form is inherently superior for a literal that defines a single byte, because (a) it's shorter, (b) it covers the full range 0-255, (c) it's naturally byte-oriented and therefore a better conceptual fit than a unicode-oriented escape.

**Comment by nnethercote** [comment]
> Nominated for lang-team discussion for [this comment above](https://github.com/rust-lang/rust/issues/116907#issuecomment-1853160194).

Still waiting for a lang-team response here, ten months later :(

**Comment by nnethercote** [comment]
> It seems nice to me that if you have a `b"\xf0\x9f\xa6\x80"` with valid UTF-8 and you refactor your program to use `str` instead of `[u8]`, you can just strip the `b` and use `"\xf0\x9f\xa6\x80"`.
> 
> Same argument the other way around: It seems nice that if you have a `'\u{07}'` you can change it for a `b'\u{07}'` later, without having to switch to a different way to escape the same character.

These cases seem like they would be extremely rare, and in each case they would only avoid modifying a tiny number of characters.

In general I'm interested in new syntax that enables new programs to be written, far more than (a) new syntax that makes potential refactorings marginally easier, or (b) new syntax that (arguably) addresses obscure consistencies in the language that don't cause problems in practice.
