### ISSUE TITLE
Tracking Issue for `gen` blocks and functions

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#117078]
This is a tracking issue for the RFC "#3513" (rust-lang/rfcs#3513).
The feature gate for the issue is `#![feature(gen)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC (happening in https://github.com/rust-lang/rust/pull/116447)
- [ ] Lots of diagnostics work
- [ ] Make the `Iterator`s fused (so they keep returning `None` after the first `None` instead of panicking (which is what they do now))
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

* [ ] should we use a different keyword?
* [ ] what happens when a generator panics?

### Implementation history

* [ ] https://github.com/rust-lang/rust/pull/116447

**Comment by kanashimia** [comment]
> The feature gate for the issue is `#![feature(gen)]`

It was renamed to `#![feature(gen_blocks)]` in the implementation PR

**Comment by ChayimFriedman2** [comment]
If `gen` blocks are fused, shouldn't they implement [`FusedIterator`](https://doc.rust-lang.org/stable/std/iter/trait.FusedIterator.html)?

**Comment by oli-obk** [comment]
As tracking issues are not practical for discussions, I have locked this issue. Please open separate issues for bugs or discuss on zulip for any other topics

**Comment by traviscross** [comment]
We're now tracking the aspects of this related to the release of Rust 2024 separately here:

- https://github.com/rust-lang/rust/issues/123904

**Comment by safinaskar** [comment]
Please, don't stabilize `gen` in the form described in RFC 3513. I. e. don't stabilize `gen { ... }`. These `gen` blocks are incompatible with natural `return` semantics. Let me explain. I think that `return` should always mean "return from lexically innermost function". By "function" here I mean everything that looks like function. For example, normal functions adhere to this definition. Closures, too. But async blocks in stable Rust (`async { ... }`) and `gen` blocks in their proposed form (`gen { ... }`) are not. Yet `return` in both these cases return from this entities, which do not look like functions. I think this is very unfortunate. We obviously cannot fix async blocks. But we can fix gen blocks. Make them take arguments, i. e. `gen |...|{...}`. This will make them look like functions. You may say: "But how this will work?" I propose to reuse ideas from RFC 3668 "Async closures" ( https://rust-lang.github.io/rfcs/3668-async-closures.html ).

All languages based on C syntax follow my rule, i. e. `return` always return from something, which looks like function. For example, let's look at JavaScript. JavaScript doesn't have anything like our async blocks or gen blocks. It do have async closures and gen closures. They look like functions and `return` works as expected there

**Comment by traviscross** [comment]
Tracking issues aren't really meant for this kind of discussion.  I'd suggest raising this kind of thing in Zulip or filing a separate issue.

**Comment by Houtamelo** [comment]
Has it been considered that gen blocks should implement the trait `Coroutine` as well?

**Comment by oli-obk** [comment]
Please keep discussion on zulip or the internals forums.



> A tracking issue is however _not_ meant for large scale discussion, questions, or bug reports about a feature.
