### ISSUE TITLE
Tracking Issue for RFC 3501: Edition 2024

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#117258]
This is a meta-tracking issue for the RFC "3501" (rust-lang/rfcs#3501).

Documentation: https://doc.rust-lang.org/nightly/edition-guide/rust-2024/index.html
Issues: https://github.com/rust-lang/rust/labels/A-edition-2024

If you have questions, or are interested in helping with the edition, please join us in the [#edition](https://rust-lang.zulipchat.com/#narrow/stream/268952-edition) stream on Zulip.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

* [x] Accept RFC.
  - https://github.com/rust-lang/rfcs/pull/3501
* [x] Land all lang priority items in Rust 2024.
  - https://github.com/rust-lang/rust/issues/117587
    - https://github.com/rust-lang/rust/issues/123432
  - https://github.com/rust-lang/rust/issues/123904
  - https://github.com/rust-lang/rust/issues/123748
* [x] 2024-10-11 Go / no go on all items.
* [x] 2024-10-17 Rust 2024 nightly beta.
* [x] 2024-11-28 Stabilize Rust 2024 on master.
* [x] 2025-01-03 Cut Rust 2024 to beta.
* [x] 2025-01-09 Announce Rust 2024 is pending.
* [x] 2025-02-20 Release Rust 2024 with Rust 1.85.

### Timeline

| Date       | Version       | Edition stage                  |
|------------|---------------|--------------------------------|
| 2024-09-05 | Release v1.81 | Checking off items...          |
| 2024-10-11 | Branch  v1.83 | Go / no go on all items        |
| 2024-10-17 | Release v1.82 | Rust 2024 nightly beta         |
| 2024-11-22 | Branch  v1.84 | Prepare to stabilize...        |
| 2024-11-28 | Release v1.83 | Stabilize Rust 2024 on master  |
| 2025-01-03 | Branch  v1.85 | Cut Rust 2024 to beta          |
| 2025-01-09 | Release v1.84 | Announce Rust 2024 is pending! |
| 2025-02-20 | Release v1.85 | Release Rust 2024              |

### Items

- [Items that are fully ready for Rust 2024](https://github.com/rust-lang/rust/issues?q=label%3AA-edition-2024%20label%3AC-tracking-issue%20label%3AS-tracking-ready-for-edition)
- [Items not yet fully ready for Rust 2024](https://github.com/rust-lang/rust/issues?q=is%3Aopen%20label%3AA-edition-2024%20label%3AC-tracking-issue%20-label%3AS-tracking-ready-for-edition%20-label%3At-libs%20)

### Related

- https://github.com/rust-lang/rust-project-goals/issues/117

**Comment by traviscross** [comment]
Rust 2024 is now Rust.
