### ISSUE TITLE
Tracking Issue for Lifetime Capture Rules 2024 (RFC 3498)

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#117587]
This is a tracking issue for the RFC 3498, "Lifetime Capture Rules 2024" (rust-lang/rfcs#3498).  The feature gate for the issue is `#![feature(lifetime_capture_rules_2024)]`.

In Rust 2024 and later editions, return position `impl Trait` (RPIT) opaque types will automatically capture all in-scope type *and* lifetime parameters.  In preparation for this, new RPIT-like `impl Trait` features introduced into earlier editions will also automatically capture all in-scope type and lifetime parameters.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC: #116952
- [x] Stabilize some means of [precise capturing](https://github.com/rust-lang/rfcs/blob/master/text/3498-lifetime-capture-rules-2024.md#overcapturing-1)
  - https://github.com/rust-lang/rust/pull/127672
- [x] Connect the `impl_trait_overcaptures` lint to `rust_2024_compatibility`.
  - https://github.com/rust-lang/rust/pull/129600
- [x] Add documentation to the [reference][].
    - https://github.com/rust-lang/reference/pull/1577
    - https://github.com/rust-lang/reference/pull/1601
- [x] Add documentation to the [edition guide][].
  - https://github.com/rust-lang/edition-guide/pull/316
- [x] Implement the rules for RPITIT/AFIT
  - #114489
  - https://github.com/rust-lang/rust/pull/115366
- [x] Stabilize the rules for RPITIT/AFIT
  - #115822
- [x] Implement the rules for ATPIT
  - https://github.com/rust-lang/rust/pull/114616
  - #122103
- [x] Stabilization PR (in nightly Rust 2024)
  - #116952
- [ ] Stabilize Rust 2024

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[edition guide]: https://github.com/rust-lang/edition-guide
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition

We discussed this item in the edition call today and concluded that this is **ready for Rust 2024**.

Huge thanks to @compiler-errors for moving the mountains needed to make this concept a reality.
