### ISSUE TITLE
Tracking Issue for Never Patterns

### ISSUE THREAD

**Issue by Nadrieril** [rust-lang/rust#118155]
This is a tracking issue for the experimental "never patterns" feature (as per the T-lang [experimental feature](https://github.com/rust-lang/lang-team/blob/master/src/how_to/experiment.md) process).
The feature gate for the issue is `#![feature(never_patterns)]`.

This feature aims to clarify pattern matching on empty types. It does this as follows:
- If a case is unreachable with or without unsafe shenanigans, it can be omitted from a match.
```rust
enum Void {}
fn foo() -> Result<u32, Void> { ... };
fn main() {
	match foo() {
		Ok(x) => ...
	}
	// Or even shorter:
    let Ok(x) = foo();
	...
}
```
- If a pattern for an empty type could be reachable (with unsafe shenanigans), you can write a `!` pattern to indicate that you ensured the empty case couldn't happen.
```rust
enum Void {}
unsafe {
	let ptr: *const Result<u32, Void> = ...;
	match *ptr {
		Ok(x) => { ... }
		Err(_) => { ... } // potentially reachable if `ptr` points to uninitialized data
    }
	match *ptr {
		Ok(x) => { ... }
		Err(!) // indicate explicitly that we ensured the empty case couldn't happen
    }
}
```

To distinguish between these two cases, we track whether the match scrutinee can hold invalid data or not. The potentially-invalid cases are union field accesses and ptr/ref dereferences. Unfortunately for safe users, this means we must require never patterns to match on `&Void` despite the fact that there is no safe value of type `&Void`.

A more in-depth description of this feature can be found [here](https://hackmd.io/hcnbjw2PS0GGfb2Tzl2r8g) until an RFC gets written. 

This feature is intended to subsume [`exhaustive_patterns`](https://github.com/rust-lang/rust/issues/51085). It fixes its problem of allowing footguns around unsafe values.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the feature
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- Should `!` count as a pattern for macros-by-example? Does this pose other problems there?
- Could we treat `&Void` as empty if the crate has `forbid(unsafe_code)`?
- Out of scope: opsem decisions like ["is `&!` inhabited"](https://github.com/rust-lang/unsafe-code-guidelines/issues/413). We take a maximally forward-compatible stance here pending further decisions.

**Comment by RalfJung** [comment]
The "steps" should include "write an RFC and have it accepted", no?

**Comment by Nadrieril** [comment]
Indeed it should

**Comment by Alonely0** [comment]
> ```rs
>enum Void {}
>unsafe {
>    let ptr: *const Result<u32, Void> = ...;
>    match *ptr {
>        Ok(x) => { ... }
>        Err(_) => { ... } // potentially reachable if `ptr` points to uninitialized data
>    }
>    match *ptr {
>        Ok(x) => { ... }
>        Err(!) // indicate explicitly that we ensured the empty case couldn't happen
>    }
>}
>```
The first match is UB. First, in Rust, any reads on uninitialized memory are considered undefined behavior; and second, if the Err variant cannot be constructed, it can't ever exist. Thus, the check for it can (and should) be removed by the optimizer, wiping away any matching on the Err variant and the code associated with it. Basically, the match would always execute the Ok branch regardless of the existence of valid data on the inner, which is exactly what you're not trying to do there (it would always get optimized down to the second match, which is equivalent to the ones proposed that are not unsafe).

I think the fact that we do not want to touch uninitialized memory directly (w/o `MaybeUninit`) in the language with a 10ft pole is pretty well set in stone, so I'd just remove this part of the proposal and rename it "Automatic discard of unreachable patterns".

**Comment by Alonely0** [comment]
Also, this is not really the place to bike shed stuff out, you should first make a thread on the [internals forum](https://internals.rust-lang.org) or ask around on Zulip, it's the way we give feedback and ~~destroy naive ideas~~ discuss the viability of the proposals. I found this old [blog post](https://smallcultfollowing.com/babysteps/blog/2018/08/13/never-patterns-exhaustive-matching-and-uninhabited-types-oh-my/) from Niko that I believe this is based from (I just skimmed over it), so I invite you to create a thread on the internals forum where we can discuss this further. Once someone from T-lang says that it is viable, you can start writing an RFC (I can help you with that), and then, once it gets approved, you can start creating issues here for the implementation.

Recommended read: https://github.com/rust-lang/rfcs

**Comment by Nadrieril** [comment]
Hi! I thought like you not that long ago, until I digged into the subtleties of rust operational semantics. Allow me to clarify.

> in Rust, any reads on uninitialized memory are considered undefined behavior

This is correct, but that match does not read from the value in the `Err` case, since a `_` pattern does not cause a read.

> if the Err variant cannot be constructed, it can't ever exist

While this is a likely possibility for rust opsem to decide, this has not been decided yet. Therefore I am erring on the side of assuming it is possible to read `Err` with uninitialized data. This is discussed [here](https://github.com/rust-lang/unsafe-code-guidelines/issues/443).

> it is not even marked as unsafe

I'm confused, there's an unsafe block in the code you quote. Dereferencing a pointer always requires an unsafe block.

> Has this gone through a pre-RFC of some sort?

No, this is an experimental feature gate, meant to iron out the details of the feature before we write the RFC. The lang-team took a quick look at my proposal and approved the experiment. I have discussed details of rust opsem with @RalfJung for a while before I felt confident proposing this. While I believe my approach is sound, this will have to be fully settled in the (to-be-written) RFC.

> I think the fact that we do not want to touch uninitialized memory directly (w/o MaybeUninit) in the language with a 10ft pole is pretty well set in stone

This isn't quite correct. We need the possibility of uninitialized data behind a pointer. In fact to initialize a `MaybeUninit<T>` you have to go through `as_mut_ptr` which returns a `*mut T` pointing to possibly-uninitialized memory.

The `mem::uninitialized` debacle that led to the creation of `MaybeUninit` wasn't about uninitialized memory in general, it was about the fact that the function would return an uninitialized **value**, which is indeed instant UB. As long as the uninitialized data is not read (e.g. because it is behind a pointer), we're ok.

> I'd just remove this part of the proposal and rename it "Allow elision of unreachable patterns".

This is the opposite of what this proposal is about. "Allow elision of unreachable patterns" is implemented in the [`exhaustive_patterns`](https://github.com/rust-lang/rust/issues/51085) feature gate, which hasn't been stabilized because it is unsound, exactly because it allows elision of patterns that are reachable without UB in rust's current operational semantics. The whole point of this proposal is to fix that soundness whole.

**Comment by RalfJung** [comment]
> in Rust, any reads on uninitialized memory are considered undefined behavior

This is **not correct**. Please consult [the reference](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) for what is and is not UB.

---

Miri's current implementation means that reading the discriminant of a `Result<u32, Void>` can indeed never yield `Err`. The question is:
- Do we want to commit to this and start designing surface-language-level things around it?
- Even if we do, do we want the UB to come about implicitly by omitting match arms?

Never Patterns help because they let us make explicit when we want to exploit that a type is empty. We can then factor the exhaustive_patterns discussion into "how do Never Patterns work" and "when do we implicitly insert Never Patterns".

**Comment by RalfJung** [comment]
The summary of this issue doesn't entirely capture this factoring I described though, it could be improved. Currently it mixes up the concept of Never Patterns with the concept of *eliding* Never Patterns, while I think these concepts should be discussed completely separately. In that sense gathering feedback on a separate writeup might be helpful. The experimental process means we don't have to wait until the RFC is all set and done, but i can still help to have the RFC at least sketched so that key stakeholders can even understand what the experimental change is doing without reverse engineering that from the implementation. It can also serve as a guideline to the reviewer.

The first example in this issue does not use a never pattern, making it a strange example for explaining never patterns.

**Comment by Nadrieril** [comment]
> This is not correct.

Oh well, every time I think I get it I discover I'm missing something. Thx for pointing it out.

> Even if we do, do we want the UB to come about implicitly by omitting match arms?

> Currently it mixes up the concept of Never Patterns with the concept of eliding Never Patterns

I'm intentionally moving away from this "implicit/explicit" frame that was in Niko's original never patterns blog post. Maybe this will turn out to be mistaken, but my current stance is: if a branch is reachable without UB, then it can't be omitted. That would be exhaustiveness being unsound. That's it, no elided never patterns or such things. Then I add the never patterns syntax as a cleaner alternative to `Err(x) => unreachable_unchecked!()`. I find that a lot easier to understand and specify than a contextual desugaring.

> it can still help to have the RFC at least sketched

Well I linked [this sketch](https://hackmd.io/XPZfEzcGRy2P7woORHUOcQ) in the OP, but I assume you don't find it detailed enough?

> The first example in this issue does not use a never pattern, making it a strange example for explaining never patterns.

Well yeah, that's because this proposal has two parts: there's a refinement of exhaustiveness checking, and there's the never patterns syntax. I _do_ intend to split off the exhaustiveness part into its own feature that we might be able to stabilize sooner.

**Comment by Alonely0** [comment]
> > in Rust, any reads on uninitialized memory are considered undefined behavior
> 
> This is **not correct**. Please consult [the reference](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) for what is and is not UB. [Here is an example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=967e0a55cc244ed86f124a4aac7e7af5) of code that reads uninit memory (for some definition of "reads") and has no UB.
> 
> You need to be careful with blanket statements like that.
I consulted the Rustonomicon, sorry if I was misinformed.
https://doc.rust-lang.org/nomicon/uninitialized.html

**Comment by Alonely0** [comment]
> Hi! I thought like you not that long ago, until I digged into the subtleties of rust operational semantics. Allow me to clarify.
> 
> > in Rust, any reads on uninitialized memory are considered undefined behavior
> 
> This is correct, but that match does not read from the value in the `Err` case, since a `_` pattern does not cause a read.
> 

But how do you know that it is an Err? Because you **read** the discriminant, which is either valid (Ok/Err) or invalid and UB to operate with it. You can't say "it is Err because it was not Ok", you're assuming something the optimizer hasn't yet and might not do. If, for example, it decides to use jump tables, you could be [jumping to dead code](https://www.ralfj.de/blog/2020/07/15/unused-data.html) for all you know. The unsafe thus should mean that at least, you ensure that the enum has a valid representation, and if it has it, it still has to be only Ok because the Err is uninhabited (more on that on the next paragraph).

> > if the Err variant cannot be constructed, it can't ever exist
> 
> While this is a likely possibility for rust opsem to decide, this has not been decided yet. Therefore I am erring on the side of assuming it is possible to read `Err` with uninitialized data. This is discussed [here](https://github.com/rust-lang/unsafe-code-guidelines/issues/443).
> 

But that post is about the layout and how we manage it internally, and I'm talking about the semantics of uninhabited (never) types. According to the reference, casting uninhabited (never) types out of thin air is unsound, and that's the same as having the discriminant be Err on that value, you're saying that whatever is next (in this case, zero bytes), is a constructed uninhabited type, which is equivalent to a *singularity*. The Err variant is an invalid (ergo unsound) state of the program. So you have to extend the meaning of that unsafe statement to mean "I'm sure it is an Ok", but it appears to me that's exactly the opposite of what you're trying to do...

> > it is not even marked as unsafe
> 
> I'm confused, there's an unsafe block in the code you quote. Dereferencing a pointer always requires an unsafe block.
> 

Now I see it, I was looking for it, but for some reason I couldn't find it yesterday, sorry for that, *mea culpa*.

> > Has this gone through a pre-RFC of some sort?
> 
> No, this is an experimental feature gate, meant to iron out the details of the feature before we write the RFC. The lang-team took a quick look at my proposal and approved the experiment. I have discussed details of rust opsem with @RalfJung for a while before I felt confident proposing this. While I believe my approach is sound, this will have to be fully settled in the (to-be-written) RFC.
> 
> > I think the fact that we do not want to touch uninitialized memory directly (w/o MaybeUninit) in the language with a 10ft pole is pretty well set in stone
> 
> This isn't quite correct. We need the possibility of uninitialized data behind a pointer. In fact to initialize a `MaybeUninit<T>` you have to go through `as_mut_ptr` which returns a `*mut T` pointing to possibly-uninitialized memory.
> 

Indeed, raw pointers indeed can point to uninitialized data, but that was not my point. My point is that you're reading a value that you don't know if it is initialized and in a valid state (the discriminant), and you're checking that validity using semantics that assume the value is in a valid state, so the checks may get removed altogether.

> The `mem::uninitialized` debacle that led to the creation of `MaybeUninit` wasn't about uninitialized memory in general, it was about the fact that the function would return an uninitialized **value**, which is indeed instant UB. As long as the uninitialized data is not read (e.g. because it is behind a pointer), we're ok.
> 
> > I'd just remove this part of the proposal and rename it "Allow elision of unreachable patterns".
> 
> This is the opposite of what this proposal is about. "Allow elision of unreachable patterns" is implemented in the [`exhaustive_patterns`](https://github.com/rust-lang/rust/issues/51085) feature gate, which hasn't been stabilized because it is unsound, exactly because it allows elision of patterns that are reachable without UB in rust's current operational semantics. The whole point of this proposal is to fix that soundness whole.

Oh, great then.

**Comment by Nadrieril** [comment]
I feel like we're talking a bit past each other, I ask your patience as we try to find what we're disagreeing on.

> casting uninhabited (never) types out of thin air is unsound, and that's the same as having the discriminant be Err on that value

That doesn't seem correct. First I can very well make a `ptr: *const Result<T, !>`. And until opsem rules it out, I could find a way to write to `ptr` in a way that initializes the discriminant to `Err`. So far, no uninhabited type has ever been read so we're good. Then if I read the discriminant, I get `Err` which is still good. The case that would be UB is if I then read the data part of the enum.

Note the very important fact that all of this happens behind a pointer. If it was instead a plain `let x: Result<T, !> = ...;`, then `x` must be valid, which indeed forbids the `Err` case.

Also I'm not sure what we're arguing about because it is already the case on stable rust that the `Err(_)` case must be included. This proposal doesn't change that.

> You can't say "it is Err because it was not Ok", you're assuming something the optimizer hasn't yet and might not do. If, for example, it decides to use jump tables, you could be [jumping to dead code](https://www.ralfj.de/blog/2020/07/15/unused-data.html) for all you know.

That is not what I'm doing. If the match expression was compiled that way I'm pretty sure it would be a bug. What the `Err(_)` case means is: "if we read the discriminant, and it returns `Err`, take this branch". If it turns out that it's UB to construct the `Err` case, then that's fine, the discriminant read will always return `Ok` and the `Err` branch will just never be taken.

If on the other hand I allowed `match ... { Ok(_) => {} }` to be exhaustive, then if `Err` is ever read we have UB. That would mean match exhaustiveness is unsound! I insist that requiring a branch for `Err` is the *safer alternative*.

**Comment by Nadrieril** [comment]
Maybe I should be clearer about what's currently required on stable rust. In both stable rust and under the proposal, the first match below is accepted, and the second match below gives a "non-exhaustive" error.

```rust
enum Void {}
unsafe {
    let ptr: *const Result<u32, Void> = ...;
    match *ptr {
        Ok(x) => { ... }
        Err(_) => { ... }
    }
    match *ptr { // ERROR: non-exhaustive: `Err` not covered
        Ok(x) => { ... }
    }
}
```

As long as we're behind a pointer/reference/union, there's no changes compared to stable. Where it does change is in the other cases, e.g. a plain value. In stable rust, we get:

```rust
enum Void {}
let val: Result<u32, Void> = ...;
match val { // accepted
    Ok(x) => ...
    Err(_) => ...
}
match val { // ERROR: non-exhaustive: `Err` not covered
    Ok(x) => ...
}
```

With `never_patterns`, we get:

```rust
enum Void {}
let val: Result<u32, Void> = ...;
match val {
    Ok(x) => ...
    Err(_) => ... // WARN: unreachable
}
match val { // accepted
    Ok(x) => ...
}
```

**Comment by Alonely0** [comment]
> That doesn't seem correct. First I can very well make a `ptr: *const Result<T, !>`. And until opsem rules it out, I could find a way to write to `ptr` in a way that initializes the discriminant to `Err`. So far, no uninhabited type has ever been read so we're good. Then if I read the discriminant, I get `Err` which is still good. The case that would be UB is if I then read the data part of the enum.

But you are reading it! That's where our disagreement comes from, and it's not even the root of it. You're reading it when you dereference the pointer, because you're not reborrowing it (you then discard/drop it later with `_`, but that's irrelevant). The thing is, when the compiler & the optimizer see the Err variant, they see that in order for the Err to exist, a never type had to be created beforehand, because it is a dependency of Err (unlike C, where everything is wrapped in a `MaybeUninit`). The semantics of the never type are simple, nothing can exist after it is created; but, however, if we go back to the definition of the Err variant, the never type had to exist before, so the Err exists after the never type! This violates the semantics of the never type, so your code is unsound; Q.E.D. That's proof by contradiction, this is proof by miri (the playground is down at the time of writing, so I'll just paste here the code):

```rs
fn main() {
    let x = Foo::<i32, Uninhabited>::X(1);
    assert_eq!(std::mem::size_of_val(&x), std::mem::size_of::<i32>() * 2); // Uninhabited is a ZST.
    assert_eq!(std::mem::size_of::<()>(), std::mem::size_of::<Uninhabited>()); // () is also a ZST.
    let mut y = Foo::<i32, ()>::X(1);
    assert_eq!(x, unsafe { std::mem::transmute(y) }); // Ergo, reprs are the same.
    y = Foo::Y(());
    let y_ptr = &y as *const _ as *const Foo<i32, Uninhabited>; // valid raw ptr w/ an Uninhabited.
    match unsafe { &*y_ptr } { // notice it is reborrowed (you don't move out, you copy out).
        Foo::X(x) => unreachable!("{x}"),
        Foo::Y(_) => panic!("UB")
    }
    
}

#[derive(Copy, Clone, Debug, PartialEq)]
enum Uninhabited {}

#[repr(i32)]
#[derive(Debug, PartialEq)]
enum Foo<A, B> where A: Copy, B: Copy {
    X(A),
    Y(B),
}
```

**Comment by Nadrieril** [comment]
I do not understand your explanation. Anyway, what do you concretely propose we should do differently?

**Comment by Nadrieril** [comment]
I propose to split off the exhaustiveness-affecting changes into their own feature gate: https://github.com/rust-lang/rust/pull/118803. If that gets accepted, then `never_patterns` will become exclusively about `!` patterns (which makes a lot of sense).

**Comment by Alonely0** [comment]
> I do not understand your explanation. Anyway, what do you concretely propose we should do differently?

First, define what you want the match to *semantically mean* in `never_patterns`. In current semantics, the unsafe block in your example piece of code would have to uphold the invariant of the pointee being a valid construction of the type (valid discriminant, and not a discriminant of an uninhabited variant). `never_patterns` would be checking whether the type is valid, but it would be doing it after the compiler has ensured told that it is. So, it would be changing the semantics of both a dereference and a match expression when doing a very specific thing in a very specific context, and it feels very off to me... my advice is just don't do never patterns, we already have ways to check for the validity of types, this is just tangling stuff up. `min_exhaustive_patterns` is very nice, though; with it, your example of it would translate 1:1 to the unsafe counterpart (ignoring the unsafe dereference), and if the type is not valid, your job was to check that before you dereferenced, not after the fact! In this case, what would have to be done is cast the pointer to the enum's internal layout, get the discriminant, and check for its validity.

**Comment by Nadrieril** [comment]
Oh, if you think `min_exhaustive_patterns` is good, then we're on the same page! I intend `never_patterns` to only be a bit of syntactic sugar on top of that. I'll clarify that when `min_exhaustive_patterns` gets merged, in case you still have doubts.

**Comment by Alonely0** [comment]
> Oh, if you think `min_exhaustive_patterns` is good, then we're on the same page! I intend `never_patterns` to only be a bit of syntactic sugar on top of that. I'll clarify that when `min_exhaustive_patterns` gets merged, in case you still have doubts.

Sorry, I only read half of it, I thought it was the first part of your proposal (eliding semantically unreachable patterns). `min_exhaustive_patterns` suffers from the same exact semantic problem as `never_patterns`. I think I explained it well (after a few edits, tho) in my previous reply, if you still don't understand why it is all unsound we can jump on a DM, a call, or whatever, and I can explain it for you.

**Comment by Nadrieril** [comment]
Thank you for this offer. For now I'll wait to see if anyone else comes up to either explain your point in a way that I understand or to confirm that my idea is sound.

**Comment by Alonely0** [comment]
If you want more reach, post a small & conceptual (like what you wrote on the first post) pre-RFC in the internals forums, where people far above my pay grade will (might) review it. The only way somebody is going to ever find this random GitHub thread is by mistake.

**Comment by RalfJung** [comment]
@Nadrieril 
> No, my proposal is different. I'm intentionally moving away from this "implicit/explicit" frame that was in Niko's original never patterns blog post. Maybe this will turn out to be mistaken, but my current stance is: if a branch is reachable without UB, then it can't be omitted. That would be exhaustiveness being unsound. That's it, no elided never patterns or such things. Then I add the never patterns syntax as a simpler alternative to Err(x) => match x {}.

But if an arm *is* unreachable without UB, then it can be omitted.  So there's still implicit never patterns, e.g. in `match (x: Void) {}`, which I would say is sugar for `match (x : Void) { ! }`. That may not be how you plan to implement this, but conceptually it is a lot simpler IMO than having two completely separate mechanisms for matching on uninhabited types.

> I linked [this sketch](https://hackmd.io/XPZfEzcGRy2P7woORHUOcQ) in the OP, have you read it?

"You don't have permission to access this resource. "

@Alonely0 
> I consulted the Rustonomicon, sorry if I was misinformed.

Arguably that is imprecise when it says "Attempting to interpret this memory as a value of any type will cause Undefined Behavior". I filed an [issue](https://github.com/rust-lang/nomicon/issues/435). Thanks for pointing that out!

> But you are reading it! That's where our disagreement comes from, and it's not even the root of it. You're reading it when you dereference the pointer, because you're not reborrowing it (you then discard/drop it later with _, but that's irrelevant). 

No. `GetDiscriminant` on a place is *not* the same as loading a value from that place. `GetDiscriminant` just reads the discriminant, not any other part of the place. So it is perfectly conceivable that `GetDiscriminant` might return `Err` even if that variant is impossible to construct. I think eventually we will declare that this can never happen, but for now this is an open question.

**Comment by Nadrieril** [comment]
> "You don't have permission to access this resource. "

Oh shoot! Fixed it now.

> But if an arm _is_ unreachable without UB, then it can be omitted. So there's still implicit never patterns, e.g. in `match (x: Void) {}`, which I would say is sugar for `match (x : Void) { ! }`. That may not be how you plan to implement this, but conceptually it is a lot simpler IMO than having two completely separate mechanisms for matching on uninhabited types.

What "two completely separate mechanisms for matching on uninhabited types" do you mean?

**Comment by RalfJung** [comment]
> What "two completely separate mechanisms for matching on uninhabited types" do you mean?

There's two mechanisms that both analyze whether the match subject is uninhabited: checking whether a `!` pattern is accepted, and checking whether we can omit a match arm.

**Comment by RalfJung** [comment]
> Oh shoot! Fixed it now.

Ah, now I can see it. :) I left some comments.

**Comment by joshtriplett** [comment]
Review in the style team turned up an issue that I'd like to raise with a lang hat on:

Syntactically, the idea of never patterns like `Err(!)` not having any trailing delimiter seems potentially problematic for both humans and computers to parse, if never patterns appear somewhere other than the *last* match arm.

Consider:

```rust
match expr {
    Variant1(field) => { ... }
    Variant2(!)
    Variant3(field) => { ... }
}
```

Even worse, consider leading `|`:

```rust
match expr {
    | Variant1(field) => { ... }
    | Variant2(!)
    | Variant3(field) => { ... }
}
```

I think we should have a mandatory trailing `,` on this.

(In theory, syntactically, we don't *need* the trailing comma if it's the last match arm. In practice from a style perspective and for consistency with all our other uses of delimiters, we'd probably want it.)

**Comment by Nadrieril** [comment]
That's how I implemented parsing 👍 I made the comma optional when it's the last pattern of the match, like we do for trailing commas in general

**Comment by Nadrieril** [comment]
> Ah, now I can see it. :) I left some comments.

@RalfJung you did? On [this document](https://hackmd.io/XPZfEzcGRy2P7woORHUOcQ) right? I don't see any comments, where should I be looking?

**Comment by RalfJung** [comment]
> @RalfJung you did? On [this document](https://hackmd.io/XPZfEzcGRy2P7woORHUOcQ) right? I don't see any comments, where should I be looking?

That comment disappeared. So I guess you found them? :)

**Comment by Nadrieril** [comment]
I didn't but I realized hackmd was overall very buggy y'day for me so that was probably the cause

**Comment by RalfJung** [comment]
There should be a button for "comments" at the top:

![image](https://github.com/rust-lang/rust/assets/330628/42a0a824-735f-499c-86c7-bdb49d3598e1)


If you click that it shows all the comments; you can click the comment to scroll to the place in the document it refers to.

**Comment by Nadrieril** [comment]
I see it! And it definitely wasn't there yesterday x)

**Comment by Alonely0** [comment]
@Nadrieril does this semantic flowchart help you understand my point? I'm sorry I couldn't reply earlier, I've been busy.
![image](https://github.com/rust-lang/rust/assets/59423215/fb42d913-2baf-4a32-8529-3d2df2ff5529)
In the eyes of the compiler, undefined behavior is not reachable (exactly like a never type), so it uses that axiom as a way of performing optimizations. As it cannot exist, any branches that would statically trigger are considered always unreachable. Consequently, the compiler would remove both branches and always execute the Ok code path even if the discriminant is not Ok (which we're expressing we're not sure), and thus we might be operating with an invalid inner in the case of an Err. What you want to do is match the discriminant without reading the whole enum, so that the Err branch is not uninhabited (and thus, not removed), and then **only and manually** read the inner in the Ok branch. This, of course, also applies to the `!` syntactic sugar.

**Comment by Nadrieril** [comment]
You went through a lot of trouble for this x). Look, I'm tired of this misunderstanding. Only-discriminant matching is what rust does today. I can't find a reference for this claim sorry, maybe [Ralf's comment](https://github.com/rust-lang/rust/issues/118155#issuecomment-1852524233) can convince you. But my proposal does not even rely on that! It's completely orthogonal! I'm
- adding sugar syntax (in the form of `!` patterns), which obviously does not change operational semantics.
- allowing some branches to be omitted in cases you would agree are unreachable (that's the part covered by `min_exhaustive_patterns`).

Where do you disagree with that? I think what you're talking about is off-topic here, and we should continue this conversation elsewhere.

**Comment by Alonely0** [comment]
> You went through a lot of trouble for this x)

Autism is both a superpower and a curse.

> Only-discriminant matching is what rust does today

Rust, indeed, uses the discriminant to match the enum, but semantically matches the enum. If Rust used only-discriminant semantics (what you're looking for), these two pieces of code would compile down to be the same: https://godbolt.org/z/Ys75n983r

> Do you have a problem with any of that? I think what you're talking about is off-topic here, and we should continue this conversation elsewhere.

This is not off-topic, I'm discussing why having different behavior in an unsafe context "just in case it is invalid" is nonsense.

**Comment by RalfJung** [comment]
@Alonely0 you seem to assume that the semantics of the MIR operation to read the discriminant is "read entire enum value, then extract discriminant". That is not the case, and that seems to be the root of this disagreement.

There is a MIR operation that is given a place (that is, a pointer to some location in memory, where raw bytes are stored), and what it does is determine the discriminant based on that. At no point does this operation involve constructing a value of enum type. It is, currently, legal to do this even if that place does *not* contain a valid value of the enum type. See https://github.com/rust-lang/rust/issues/91095 for further discussion of this. You may say that you'd prefer a different semantics, but these are the semantics we have, and if you want to change them then please start a suitable discussion and give proper motivation -- but not in this issue.

**Comment by Alonely0** [comment]
> you seem to assume that the semantics of the MIR operation to read the discriminant is "read entire enum value, then extract discriminant". That is not the case, and that seems to be the root of this disagreement.

Not at all, I mean the unsafe dereference. When you dereference the pointer, you either reborrow to get a reference to a type that must be valid, or copy it to local memory as a type that must be valid (which may or may not be optimized away). I didn't mean the read on the discriminant that match does, I meant the operation of the dereference. There you already promise that the enum is valid, and then the compiler then uses this information to alter the codegen of match to remove the Err code path. Thus, `Err(!)` is nonsense, as such a thing was already promised in the dereference in the match line.

**Comment by RalfJung** [comment]
> When you dereference the pointer, you either reborrow to get a reference to a type that must be valid, or copy it to local memory as a type that must be valid (which may or may not be optimized away). 

No. As I have explained already two times, there is another operation you can do on the *place* `*ptr`: you can read its discriminant. This does not involve copying its value to local memory at any type. You are just fundamentally misunderstanding how the "get discriminant" operation works.

>  I meant the operation of the dereference. 

The `*ptr` operation itself turns a pointer-typed value into a place. This operation does not access memory, and is never UB. It doesn't do anything except "cast the pointer into a different light".

This is the last time I am trying to explain this, future comments will be marked as "off topic".

**Comment by Alonely0** [comment]
Fine, I'll see myself out. I apologize if, while trying to contribute, I became a hassle.

**Comment by RalfJung** [comment]
I understand you had good intentions. :) But these discussions are hard, and if you're coming in with a wrong mental model of how Rust works, we have to disentangle a mess. The deref operation `*ptr` is one of the more subtle expressions in rust due to the place/value dichotomy. On [Zulip](https://rust-lang.zulipchat.com/) and [IRLO](https://internals.rust-lang.org/) there is enough space to discuss the questions you may have without distracting from the core of a tracking issue like here.

**Comment by dead-claudia** [comment]
To be clear, the alternate branch *would* be executed in this case.

```rs
enum Enum {
    Foo(T) = 0,
    Bar(u8),
    Baz(i16),
}

// has a discriminant of 0
unsafe {
    let zeroed: Enum<u8> = 
std::mem::zeroed();
    let ptr: *const Enum<!> = std::mem::transmute(&zeroed);

    match *ptr {
        Enum::Foo(_) => println!("Foo"),
        Enum::Bar(_) => println!("Bar"),
        Enum::Baz(_) => println!("Baz"),
    }
}
```

Is my understanding correct in the following?

- In the presence of `unsafe` code, the "never" branches are only genuinely unreachable if the enum discriminant is zero-sized.
- The enum discriminant *may*, but not *must*, be zero-sized if at most one variant has no member directly containing a value of type `!`. (Same logic as the circularity detection, but applied to `!` instead of the outer type.)

**Comment by Nadrieril** [comment]
Hey sorry, I quote:

> A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.
> Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

Please open a dedicated issue or come ask your question on Zulip.

**Comment by dead-claudia** [comment]
Now that I think of the existing state of enums, I think precedent says omitting unmatchable values is fine. Consider this:

> [Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=static+DATA%3A+u64+%3D+0xFFFFFFFFFFFFFF00%3B%0A%0Afn+main%28%29+%7B%0A++++let+ptr%3A+*const+u64+%3D+%26DATA%3B%0A++++%2F%2F+Black+box+to+ensure+it%27s+treated+as+*potentially*+well-defined.%0A++++let+ptr%3A+*const+Option%3Cu32%3E+%3D+std%3A%3Ahint%3A%3Ablack_box%28ptr%29.cast%28%29%3B%0A%0A++++unsafe+%7B%0A++++++++match+*ptr+%7B%0A++++++++++++Some%28foo%29+%3D%3E+println%21%28%22Some%28%7Bfoo%7D%29%22%29%2C%0A++++++++++++None+%3D%3E+println%21%28%22None%22%29%2C%0A++++++++++++_+%3D%3E+println%21%28%22Other%22%29%2C%0A++++++++%7D%3B%0A++++%7D%0A%7D)

```rs
static DATA: u64 = 0xFFFFFFFFFFFFFF00;

fn main() {
    let ptr: *const u64 = &DATA;
    // Black box to ensure it's treated as *potentially* well-defined.
    let ptr: *const Option<u32> = std::hint::black_box(ptr).cast();

    unsafe {
        match *ptr {
            Some(foo) => println!("Some({foo})"),
            None => println!("None"),
            _ => println!("Other"),
        };
    }
}
```

The pointer creation itself is defined, but its dereferencing is UB. It doesn't match either of the enum discriminators, and could evaluate to either branch depending on the width used to test the discriminant.

- x86 might choose to do a `cmp byte ptr [reg], 0` and load the variant value in the branch if optimizing for size.
- AArch64 might choose to do a `ldrp w0, w1, [reg]` to merge both loads into a single step, then proceed with `cbz w0, .print_ok`

You *can* specify an unreachable catch-all, but you get a compiler warning as the playground link shows. I think that counts as precedent here to allow omission in unreachable cases involving zero-variant enums and never types as well, and likewise warn if you try to match them. If you do this, `!` patterns become entirely redundant.

**Comment by dead-claudia** [comment]
@Nadrieril My bad. Deleted the relevant comments.

**Comment by Nadrieril** [comment]
@dead-claudia No worries, we don't enforce this policy very consistently 🙏

**Comment by Nadrieril** [comment]
I updated the OP to reflect the fact that I split off the exhaustiveness-affecting parts of this feature to [`min_exhaustive_patterns`](https://github.com/rust-lang/rust/issues/119612). This feature is now strictly about adding the `!` pattern.

**Comment by Nadrieril** [comment]
RFC is up: https://github.com/rust-lang/rfcs/pull/3719
