### ISSUE TITLE
Tracking Issue for WebAssembly exception handling

### ISSUE THREAD

**Issue by coolreader18** [rust-lang/rust#118168]
This is a tracking issue for wasm native exception handling, which would allow `panic=unwind` to function properly for code targeting wasm.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Initial compiler support (#111322)
- [ ] Standard library support
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- `-C target-feature=+exception-handling` vs `-C panic=unwind` -- does one imply the other, or is one of them redundant?
- Should `-C llvm-args=-wasm-enable-eh` be passed by default on all wasm targets, to be stripped out if the `exception-handling` target feature is disabled?

### Implementation history

- #111322

**Comment by coolreader18** [comment]
(The unresolved questions might have obvious answers that I couldn't see, those are just the questions I came across in poking around looking to add wasm32 support to libpanic_unwind)
