### ISSUE TITLE
Tracking Issue for MaybeDangling

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#118166]
This is a tracking issue for the experimental MaybeDangling type (as per the T-lang [experimental feature](https://github.com/rust-lang/lang-team/blob/master/src/how_to/experiment.md) process). The type is described by [this RFC](https://github.com/rust-lang/rfcs/pull/3336), but we can experiment with adding the type unstably (and even using it in `ManuallyDrop`) before the RFC gets accepted.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC (cc @rust-lang/XXX -- can anyone write up mentoring
      instructions?)
- [ ] Finish the RFC, have it accepted
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

XXX --- list all the "unresolved questions" found in the RFC to ensure they are
not forgotten

**Comment by RalfJung** [comment]
@rust-lang/opsem I realized we probably should have included t-opsem in the FCP for this RFC. Let's try to remember to do a t-opsem FCP in the PR with the initial implementation, just to make sure the team is on board.

**Comment by RalfJung** [comment]
There's an interesting open question I did not realize about the exact validity of `MaybeDangling<&T>`. I expected this to be just "non-null and aligned", but we might want to include "and has an address where an object of size `T` could actually exist" -- which would rule out being too close to the end of the address space, and might rule out more. The open question is exactly how much it should rule out.

**Comment by orlp** [comment]
I think the current name and API design are incompatible. Either the name needs to be changed to something better, or the methods that access the inner state must be `unsafe`.

A `MaybeDangling<Ptr>` which is allowed to cause UB if the `Ptr` is in fact dangling and passed to safe code is a disaster. I should never have to encounter a sentence like this in the Rust docs:

> note that safe code can still assume that the inner value in a `MaybeDangling` is not dangling

Or this on a function not marked as `unsafe`:

> Note that this is UB if the inner value is currently dangling.

**Comment by RalfJung** [comment]
Do you have any proposal for what the name should be?

Note that there is precedent for this in `ManuallyDrop`: deref'ing that is safe, so actually passing a dropped value around this way can lead to UB.

**Comment by orlp** [comment]
> Note that there is precedent for this in `ManuallyDrop`

I disagree that `ManuallyDrop` is precedent. It's not called `MaybeDropped`, it just disables automatic drop. The type doesn't at all imply it's valid to pass dropped states to safe code. On the contrary, the actual precedent is `MaybeUninit`. It is perfectly valid to pass uninit data with it to safe code.

Perhaps you read the "Maybe" in `MaybeUninit` or `MaybeDangling` as purely probabilistic, or things the type *can* theoretically represent. I read it as the much stronger "it may be", which actually *explicitly allows* the thing it says. And `MaybeUninit` follows the much stronger interpretation.

> Do you have any proposal for what the name should be?

For what it's worth, I think `MaybeDangling` is a fine name for this type, **if the accessors were `unsafe`**. On `MaybeUninit` one has to call `mu.assume_init()`, on `MaybeDangling` you'd have to call `md.assume_deref()` or `md.assume_deref_mut()`.

I think that'd be an improvement regardless as it further address the concern you raise in the open questions in your RFC (emphasis mine):

> Should MaybeDangling implement Deref and DerefMut like ManuallyDrop does, or should accessing the inner data be more explicit since <ins>that is when the aliasing and dereferencability requirements do come back in full force</ins>?

I think that should be very explicit, and marked as `unsafe`. (If it could somehow implement a hypothetical `UnsafeDeref` and `UnsafeDerefMut` like pointers do I would be fine with that.)

**Comment by RalfJung** [comment]
> For what it's worth, I think MaybeDangling is a fine name for this type, if the accessors were unsafe.

Unfortunately, there's a good reason to make them safe:
One of the motivating use-cases for this type is a bug that we had in the thread spawning logic of libstd, where a closure captured some types that contain references and those were then accidentally assumed to outlive the closure invocation, which was not intended to happen. If we make `MaybeDangling` have unsafe accessors then one has to write more unsafe code just to deal with this, which seems bad -- it seems better to be able to mitigate such a problem without new unsafe blocks.

But now that I say this I wonder if we should just consider all closure captures to be a bit like `MaybeDangling` and suppress retagging and other aliasing model effects of the references that get captured.

**Comment by orlp** [comment]
@RalfJung I'm not denying that there might be legitimate use-cases for the proposed type, and that those use-cases could be written without further `unsafe` code with an appropriate wrapper type. However I can only comment on the API design in front of me, which is a wrapper type called `MaybeDangling` which may in fact not dangle safely. E.g. if it were called something like `MayDangleAfterDrop` or `MayDangleAfterLastDeref` or something similar I could live with its accessors being safe, but with the current name and documentation I think the footgun is too large and counter to the rest of the safety design in Rust.

I also can't help but notice that two of the three mentioned use cases in the RFC are due to uniqueness being asserted upon a `Unique`/`&mut T` being moved. Is that really something we're committing to? That has always felt to me as a defect to be fixed, not something to be doubled down upon. To me it's intuitive that moving a `Box` should not invalidate existing pointers to the contained value.

**Comment by RalfJung** [comment]
I am not happy with the current name either, as the RFC indicates. I am just not sure what else to call it.

>  Is that really something we're committing to? 

I am not aware of any credible alternative. No aliasing model has even been sketched that can justify `noalias`, let alone the stronger optimizations SB/TB give us, without "retagging" `&mut`/`Box` function arguments, which leads to the behavior you describe as counterintuitive.

**Comment by theemathas** [comment]
Is `SuspendDeref` a good name for the type?

**Comment by RalfJung** [comment]
FWIW I wouldn't mind making deref'ing unsafe if we make it so that closures are implicitly like `MaybeDangling`, i.e. closure captures never participate in alias requirements (until they get taken out and turned into normal values again).

**Comment by RalfJung** [comment]
> Is `SuspendDeref` a good name for the type?

I think I like this more than `MaybeDangling`.

Part of the reason I dislike `MaybeDangling` more and more is that one intended usecase for this type is for references that you know are dereferenceable, but you have derived other references from them so the original reference needs to be "suspended" for now, making sure it doesn't get used until the child reference lifetime has ended.

`SuspendRefs` might also be an option. Though it does affect `Box` as well...

**Comment by CAD97** [comment]
I would support a name of `SuspendDeref`; it's extremely clear what it does from that name — for some reason (typically `unsafe` code outside the type system) it is `unsafe` to apply anything that relies on the type being dereferencable, for some period of time.

I've previously suggested `Suspended` or `Dormant` as names, which are cute, but `SuspendDeref` communicates much more clearly what property of the type it actually matters that we're suspending assumption of.

-----

> Note that there is precedent for \[safe element access] in `ManuallyDrop`

Here's my counterargument: the vast majority of a `ManuallyDrop<T>`'s lifetime, its holding a valid `T`, and the point of the type is to make that `T` accessible. The logical lifetime of the value ends when the `T` is dropped (or moved out), and the `ManuallyDrop` is no longer in use at this point. For `SuspendDeref<T>`, the `T` is valid through the full syntactic lifetime of `SuspendDeref<T>`; the unsafety is that for some portion of that, the `T` must not be dereferenced (or retagged from opsem requirements to be dereferencable). The `ManuallyDrop` is safe to use throughout its full logical lifetime; the `SuspendDeref` is not.

The entire purpose of the `SuspendDeref`<T> is enabling the time where the `T` cannot be safely accessed. If that lexical scope is clear, the code author can use `new` and `into_inner` to wrap and unwrap the inner value.

Note that while I believe `as_ref` and `as_mut` should be `unsafe`, `into_inner` *could* remain safe, as it takes `self` by value. This logically (even if not operationally) invalidates the loan of any pointers derived from `as_ref`/`as_mut`, and the "`ManuallyDrop`" argument for being safe to use *does* apply to `into_inner`. The `unsafe`ly broken invariant is the scope of the access made available through `as_ref`/`as_mut` unsoundly not being respected by downstream `unsafe`.

Also, giving closures inherent `MaybeDangling` semantics is FCP-merge now, so the use case there is lessened. (And didn't we decide that `ManuallyDrop` needs to have `MaybeDangling` semantics as well, so it can be moved after being dropped? Independently, `ManuallyDrop` seems more semantically correct for the `impl FnOnce` case, assuming I'm remembering the correct one.)

Furthermore, postcondition-creating APIs like `ManuallyDrop::drop` are a necessary tool, but a poor API design that should only be used rarely and when the other alternatives are worse. With `SuspendDeref`, the self-contained invariant way to express its purpose is clear: deref is `unsafe` because the value might be aliased in a way not visible to the type system.

You can argue that making `into_inner` safe like I propose gives `as_ref`/`as_mut` a postcondition, and thus is poor API design by my own argument. This isn't an incorrect observation! But I hold that this isn't a new obligation; dropping the value has the exact same implication of ending the loan that `as_ref`/`as_mut` gives access to. `into_inner` is "just" the "outer drop" of the `SuspendDeref` and gives the `T` back instead of continuing the drop glue with in-place drop of the `T`. This *should* be mentioned in the `as_ref`/`as_mut` docs, but it's a type invariant of holding and destroying the `SuspendDeref`, not of those specific methods.

**Comment by RalfJung** [comment]
> Also, giving closures inherent MaybeDangling semantics is FCP-merge now, so the use case there is lessened. 

Indeed, the main usecase for safe code I meant to cover here is not dealt with.

> And didn't we decide that ManuallyDrop needs to have MaybeDangling semantics as well, so it can be moved after being dropped?

Yes, we're in fact even already promising this in stable docs in the upcoming release (https://github.com/rust-lang/rust/pull/155750).

> Independently, ManuallyDrop seems more semantically correct for the impl FnOnce case, assuming I'm remembering the correct one.

I very much disagree on that one, accidentally leaking that memory if we forget to drop it on some codepath is not desirable IMO.
