### ISSUE TITLE
Tracking issue for `--env-set` flag

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#118372]
Adds a new `--env-set` command line option on rustc. It allows to set environment variables value at compile-time to be used by `env!` and `option_env!` macros.

When retrieving and environment variable value, the one specified by `--env-set` will take precedence. For example if you want have `PATH=a` in your environment and pass `--env-set PATH=env`, then you will have:

```rust
assert_eq!(env!("PATH"), "env");
```

### Steps

- [x] Implement the [MCP](https://github.com/rust-lang/compiler-team/issues/653) -> Done in https://github.com/rust-lang/rust/pull/118368, in https://github.com/rust-lang/rust/pull/118830 and in https://github.com/rust-lang/rust/pull/119884
- [ ] Stabilization PR - https://github.com/rust-lang/rust/pull/119926

### Unresolved questions

- [ ] What is the desired behavior if the same `--env` variable is passed twice?

**Comment by tgross35** [comment]
Ongoing zulip discussion: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Stabilizing.20.60--env.60.20option.20flag.3F

**Comment by GuillaumeGomez** [comment]
We discussed about how it might impact https://github.com/rust-lang/rfcs/pull/2794 and decided to rename it into `--env-set` to prevent potential future issues.

**Comment by fenollp** [comment]
Hi! I see the stabilization PR was closed. What's the state of this then?

My 2cents on a couple points:
* I need this so my `$RUSTC_WRAPPER` knows which envs to forward to `rustc`. Can't just forward all the envs. 
* same keys in duplicate `--env-set KEY=..` should be an error. It resolves that point and allows forward compatibility 

If help is needed here I'd like to provide some!

**Comment by xclaesse** [comment]
Hi, is there anything preventing this to be stabilized? It's pretty important as ninja cannot set env when running rustc commands. It makes using rustc outside of cargo (e.g. Meson) harder.

**Comment by Urgau** [comment]
Removed in #161831
