### ISSUE TITLE
Tracking Issue for `for await` loops

### ISSUE THREAD

**Issue by eholk** [rust-lang/rust#118898]
This is a tracking issue for a `for await` loop variant that makes it easier to work with async iterators (#79024).
The feature gate for the issue is `#![feature(async_for_loop)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Get consensus on design, and if we even want this feature
- [ ] Implement the feature
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

This is an early experimental feature, so basically every question is still unresolved.

### Implementation history

- #118847

**Comment by eholk** [comment]
cc @rust-lang/wg-async
