### ISSUE TITLE
Tracking issue for refactoring the way we represent function call ABIs

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#119183]
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/issues/119183)*

This is the issue tracking implementation of https://github.com/rust-lang/compiler-team/issues/672. Note that we do not have a final design yet; the best way to represent call ABI, and to disentangle it from the "storage kind" of a type (which is what the `Abi` type currently largely represents) is yet to be determined.

Note that for the purposes of this, by "call ABI" I mean "the target-independent information that is necessary and sufficient to compute how arguments and returns values are passed between caller and callee". The perfect end state (that we may or may not ever reach) for this would be to say that two types are [ABI compatible](https://doc.rust-lang.org/stable/std/primitive.fn.html#abi-compatibility) if and only if the computed call ABI information for them is the same -- that would be very nice for the spec and for MiniRust, anyway.

I do *not* mean "the target-specific information saying which arguments are passed in which register / on the stack, which are copied and which are passed indirectly". This already exists to some extend as a concept in rustc, called `PassMode`. It may need some reforming, but that would be a separate discussion.

- [ ] The core need is that a Rust type must have its ABI computed in a manner that is not reimplemented for every target and every codegen backend. e.g. the traversal over types should skip `repr(transparent)` in essentially every case. Then every target architecture must be ported to it:
  - [ ] aarch64
  - [ ] arm
  - [ ] csky
  - [ ] loongarch
  - [ ] loongarch64
  - [ ] mips
  - [ ] mips64
  - [ ] powerpc
  - [ ] powerpc64
  - [ ] riscv32
  - [ ] riscv64
  - [ ] sparc
  - [ ] sparc64
  - [ ] x86
  - [ ] x86_64
- [ ] layout.abi is not about actual ABI, but only about IR codegen: handling the types as SSA values versus handling them as memory locations.
    - [x] Rename it https://github.com/rust-lang/rust/pull/132246
    - [ ] and decouple it from actual ABI handling

See in particular [this comment](https://github.com/rust-lang/compiler-team/issues/672#issuecomment-1751624436).

## Implementation history

- @workingjubilee: the first few PRs are just going to be moving stuff around so that we can actually co-locate as much of the ABI code as possible:
    - https://github.com/rust-lang/rust/pull/131424
    - https://github.com/rust-lang/rust/pull/131473
    - https://github.com/rust-lang/rust/pull/132246
    - https://github.com/rust-lang/rust/pull/132385

**Comment by bjorn3** [comment]
Should this be C-cleanup or C-tracking-issue? The description for the latter says that it is about RFC's and unstable features, which this is not. But on the other hand it is tracking implementation of an MCP.

**Comment by RalfJung** [comment]
I'd say both make sense. :shrug: 

Cc @eddyb

**Comment by RalfJung** [comment]
Looks like fixing https://github.com/rust-lang/rust/issues/117480 may be blocked on this.

**Comment by workingjubilee** [comment]
I've started work on cleaning up ABI code. The first few PRs are just going to be moving stuff around so that we can actually co-locate as much of the ABI code as possible:
- https://github.com/rust-lang/rust/pull/131424
- https://github.com/rust-lang/rust/pull/131473

I'll try to implement the MCP proper as I go along.

**Comment by RalfJung** [comment]
Awesome. :-)

If you want feedback on some sketches of what the ABI might look like, feel free to post them here.

**Comment by bjorn3** [comment]
> our current PassMode is very LLVM-specific, so I don't know how much other backends can even use it today.

cg_clif makes full use of it. In fact PassMode is at pretty much exactly the right level of abstraction as Cranelift needs (it doesn't support high level types and requires you to decompose everything into primitive values and for struct arguments a pointer argument with ArgumentPurpose::StructArg and for complex return types it requires you to pass a return area pointer. all of which PassMode makes pretty easy to do). The only problems I have with it are that LLVM silently accepts things that IMO shouldn't be accepted like `PassMode::Direct` for a return value that doesn't fit in registers. (`PassMode::Indirect { on_stack: false }` should be used for that instead.) We also now have at least some sanity checks for non-sensical things like `PassMode::Direct` for a complex struct.

**Comment by workingjubilee** [comment]
Yeah, IMO our main ask from LLVM should be "more hard errors instead of silently making up some weird shit, please", with probably more IR parameter attributes to enable "please make up some weird shit **on purpose**".

**Comment by RalfJung** [comment]
Unfortunately LLVM is moving in the opposite direction, see e.g. the discussion in <https://github.com/llvm/llvm-project/pull/111334>

**Comment by workingjubilee** [comment]
Some scattered thoughts:

There are higher-level and lower-level ways to represent the ABI. Devolving to register and stack passing, for instance, versus high-level abstractions like "pass this like it would be passed via the C ABI".

The problem with using the C ABI as referent is the C ABI often has arbitrary limitations: For instance, multi-register returns are functionally inconceivable in many C ABIs, but are a normal idea for Rust. And because some C ABIs do implement them, LLVM often does not have an actual problem with doing them, they're just a bit weird to express using its C-like syntax.

Going down to individual registers for _all_ arguments might still be too low-level? Yet I definitely do not believe we should be reifying aggregates *more* in our ABI handling: thinking primarily in terms of them is almost inherently problematic. And we do think about registers a lot in our current handling.

If we did think about this in the more lower-level form, we would need to account for how the translation of a set of arguments to an ABI handling would be inherently _ordered_: at some point you run out of registers and start putting things on the stack. I don't think that's completely unacceptable, but it does point to rethinking what we're doing fairly extensively.

We already have at least should have a vague idea of what belongs in these two sets:
- what _may_ go in registers
- what _must_ go on the stack

That's kind of what all the linting about target features points to, anyways.

**Comment by workingjubilee** [comment]
Some constraints we know about:
- For any `fn(A) -> R`, then `A` and `R` *must* completely determine the ABI for the call, or else function pointers stop working. This might seem obvious, but I felt I should state it explicitly because it is sometimes tempting to say the ABI should vary based on something that isn't distinguishable as part of the function pointer type, like target features.

**Comment by Lokathor** [comment]
Doesn't that already sometimes happen, like soft float vs hard float?

**Comment by workingjubilee** [comment]
Nah, that doesn't happen because people compile code for targets and targets are not allowed to vary whether they are hard float or soft float. 😌

**Comment by Mark-Simulacrum** [comment]
> must completely determine the ABI for the call, or else function pointers stop working

I think this is only somewhat true - there must be a "function pointer" ABI, but that ABI may want to differ from the ABI we choose to use for regular (non function pointer) calls, by (for example) inserting a shim when casting a function to a pointer. Effectively, we could model this as every function having a generic of whether it ever gets erased or is always called with knowledge of the specific function.

That might be useful for example to leverage PGO or other information to optimize Result into passing the more common variant *for a particular function* through registers vs. not.

That's commonly achieved through inlining, but I think it would be nice to avoid excluding it from being done *without* inlining too.

**Comment by workingjubilee** [comment]
I am aware of that but it seems functionally identical to generating a new `extern "{CC}" fn(A) -> R`, with `CC`, `A`, and `R` based on but non-identical to the original, and rewriting the call site to call this new function?

A related concern that has been pointed out to me in the past is that sometimes, even with inlining, the codegen backend can have problems erasing the prologue and epilogue. Ideally, we would find a way to make "handling the ABI of this call" semantically separable from the actual motion of "making this call", so that we can delay addressing the need for a prologue and epilogue as long as possible. Notionally the function call ABI, after all, should be a non-event, as otherwise these functions aren't very functional.

**Comment by RalfJung** [comment]
We currently *talk* a lot about registers in our ABI handling, but that's kind of a lie. All it means is "represent this to LLVM as a scalar / array of scalars" and then LLVM decides whether to put that into registers or on the stack depending on the target's conventions. (Well, there's a flag for forcing things to be in a register -- mixed up with other flags that are irrelevant for the ABI. I don't know the exact semantics of that, it's probably target-specific.)

I don't think we should go any more low-level than this on the Rust side. I'd rather not have us be in the business of counting how many argument go in registers vs on the stack. That's a *lot* of work, very hard to test, and AFAIK none of our codegen backends actually give us that level of control anyway.

The main goal of the original MCP was to make writing our target-specific foreign ABI adjustments easier and less fragile. For that code, the C ABI is exactly the right abstraction, as that's the level the ABI is specified at: we need to tell that code what the given type "looks like as a C type", and then the code needs to compute a corresponding `PassMode`. So I think that kind of machinery is definitely on the requirements list here. The MCP talks mostly about how to represent the *input* to this step; you seem to be thinking mostly about the *output*? To be honest I have not thought about this much; what we have here currently seems to work well enough for both LLVM and cranelift, so it's not entirely terrible.

> A related concern that has been pointed out to me in the past is that sometimes, even with inlining, the codegen backend can have problems erasing the prologue and epilogue. Ideally, we would find a way to make "handling the ABI of this call" semantically separable from the actual motion of "making this call", so that we can delay addressing the need for a prologue and epilogue as long as possible. Notionally the function call ABI, after all, should be a non-event, as otherwise these functions aren't very functional.

That kind of work needs to start in the backends though; LLVM / cranelift would require a higher-level way to express the ABI so that they don't require a bunch of instructions that must later be optimized away again (e.g. when inlining). This also points towards a rather higher-level than lower-level abstraction, i.e., not "register vs stack".

**Comment by workingjubilee** [comment]
LLVM does not implement the C ABI for us.

**Comment by RalfJung** [comment]
I think you are talking about a completely different layer than what I am talking about in the MCP and the issue description. We need two "ABI representations":
- One representation sits between the notion of a Rust type, and the target-specific ABI logic. This is a function of type `fn(TyAndLayout) -> AbiRepr`, and crucially it must have the property that ABI-compatible Rust types are mapped to *the same* `AbiRepr`. This function can and should be target-independent. `AbiRepr` is a new concept that does not exist in rustc yet but I think having it would greatly improve the correctness of our foreign ABI adjustments.
- Since codegen backends do not implement the entire C ABI for us (they implement part of it, like knowing how many arguments to put into registers vs the stack, but many other parts have to be handled by the frontend), we also need to have anther layer below this. This layer consists of a function `fn(AbiRepr) -> PassMode`. I am sure `PassMode` can be improved, and in fact `PassMode::Cast` will have to be extended as currently it cannot represent everything LLVM can represent and that leads to ABI bugs on some targets. But I don't see which problem would be solved by making `PassMode` so low-level that we have to know how many arguments to put in registers.

Currently we have effectively have a function `fn(TyAndLayout) -> PassMode` for each foreign ABI (except we express this more like `fn(TyAndLayout, &mut PassMode)`, which is even worse). That's bad as it means ABI adjustments can easily accidentally map two ABI-compatible types to different `PassMode`; I fixed a bunch of those bugs last year. This proposal is about factoring that into two functions with an intermediate abstraction, `AbiRepr`. I think the vocabulary of C types is not a bad template for this. In particular, using C types here does in no way preclude using multiple return registers.

I don't know where you went on a different track than my line of thoughts here but clearly we're not talking about the same thing, maybe this helps. :)

**Comment by workingjubilee** [comment]
It simply does not make any sense to me to talk about things in terms of C types if they do not have to follow the C ABI, so I think about these elements in a more decomposed way?

**Comment by workingjubilee** [comment]
I think I will simply talk less about these things because it is not very useful for me to try to record my thoughts in forms that are likely to be misunderstood. I understand what you are saying about your primary hope was to make the input forms more sensical, I just am thinking about this from the origin of the demands... "we want programs that do FFI to successfully execute... which means certain things have to go into certain registers... which means that they have to..." etc.

**Comment by RalfJung** [comment]
> It simply does not make any sense to me to talk about things in terms of C types if they do not have to follow the C ABI, so I think about these elements in a more decomposed way?

We need some sort of high-level language of types (well, higher-level than `PassMode`, but lower-level than Rust types) that can serve as input for the target-specific ABI adjustments. I don't care what you call this. I called in `AbiRepr` above. We don't have to call it "C types" if you don't like that, we can just call it "structs and unions and leaf types" if you prefer 🤷  .

> I just am thinking about this from the origin of the demands... "we want programs that do FFI to successfully execute... which means certain things have to go into certain registers... which means that they have to..." etc.

That would make sense if we were emitting the assembly ourselves, but we are not. We are targeting the language of our backends in terms of how they represent ABI. `PassMode` is designed around that. It works well enough; the ABI issues we have seen have *not* been caused by `PassMode` being inadequate. They have been caused by the fact that the ABI adjustments take as *input* a Rust type and that makes it extremely easy to map different-but-defined-to-be-ABI-compatible Rust types to different `PassMode`.

**Comment by RalfJung** [comment]
Maybe I once again fell in the trap of "call ABI" meaning like a dozen different things to different people. For the purposes of this discussion, by "call ABI" I mean "the target-independent information that is necessary and sufficient to compute how arguments and returns values are passed between caller and callee". The perfect end state (that we may or may not ever reach) for this would be to say that two types are [ABI compatible](https://doc.rust-lang.org/stable/std/primitive.fn.html#abi-compatibility) if and only if the computed call ABI information for them is the same -- that would be very nice for the spec and for MiniRust, anyway.

**Comment by bjorn3** [comment]
@RalfJung

> Regarding the point about multi-register returns, I don't see why we couldn't extend PassMode to support that.

In fact we can already represent 4 register returns on 64bit and 8 register returns on 32bit through `PassMode::Pair(i128, i128)` And I think even more using `PassMode::Cast`. LLVM will make up an ABI when you do however and in many cases this made up ABI returns the return value using a return area pointer rather than in registers.

@workingjubilee

> It simply does not make any sense to me to talk about things in terms of C types if they do not have to follow the C ABI, so I think about these elements in a more decomposed way?

For lowering the C ABI we very much have to first map Rust types into C types as the C ABI is specified as a mapping from C types to registers and stack locations. Some of the ABI issues we have are precisely because the ABI implementation for each architecture does an implicit ad-hoc mapping from Rust to C types rather than sharing this such that we only have to get it right once. The Rust ABI follows a different code path and as such doesn't necessarily have to use this lowering to C types. It could keep directly operating on Rust types if we want.

**Comment by workingjubilee** [comment]
And we also have targets with two C-like ABIs.

**Comment by RalfJung** [comment]
> The Rust ABI follows a different code path and as such doesn't necessarily have to use this lowering to C types. It could keep directly operating on Rust types if we want.

Then we still have to get the ABI compat right twice, not the best plan IMO.

**Comment by RalfJung** [comment]
> And we also have targets with two C-like ABIs.

That's just two different functions from AbiRepr to PassMode.

**Comment by RalfJung** [comment]
FWIW it's not just all the ABI adjustments that have to duplicate similar logic here. There are other parts of the compiler that also need effective ABI information and that are duplicating parts of the same logic, often incorrectly:
- CFI
- and the ongoing pointer authentication (PAC) work
