### ISSUE TITLE
Tracking Issue for `hint::assert_unchecked`

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#119131]
Feature gate: `#![feature(hint_assert_unchecked)]`

This is a tracking issue for ...

### Public API

```rust
// core::hint

pub const unsafe fn assert_unchecked(p: bool);
```

### Steps / History

- [x] ACP: https://github.com/rust-lang/libs-team/issues/315
- [x] Implementation: https://github.com/rust-lang/rust/pull/119133
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- [x] Naming, as always: https://github.com/rust-lang/libs-team/issues/315#issuecomment-1863159430

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by bend-n** [comment]
What if the name was `unsafe_invariant`?

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting and we're happy with `assert_unchecked` because it follows the existing pattern of `_unchecked` functions in the standard library.

@rfcbot fcp merge

**Comment by tgross35** [comment]
Todo list: docs could use an example

**Comment by BurntSushi** [comment]
@rfcbot concern doc-example

I agree that we should have a doc example showing when someone might want to use this method. The docs otherwise look good as written!

**Comment by bend-n** [comment]
Suggestion for doc example: show example implementation of `[T]::slice_unchecked`?

**Comment by tgross35** [comment]
Could `assert_unsafe_precondition!` emit `assert_unchecked` when debug assertions are disabled? https://github.com/rust-lang/rust/pull/123561 looks like a case where assuming the unsafe preconditions would have led to more efficient codegen, I am sure there are others.

**Comment by tgross35** [comment]
I am unsure whether the FCP at https://github.com/rust-lang/rust/issues/119131#issuecomment-1906394087 was purely for the unstable name change or an intent to stabilize; assuming the latter, I created a stabilization PR at https://github.com/rust-lang/rust/pull/123588.

That PR should also resolve the docs example concern.

**Comment by BurntSushi** [comment]
@rfcbot resolve doc-example

**Comment by FeldrinH** [comment]
What happens if the expression passed to assert_unchecked has a side effect? I could not find a clear answer in the current documentation.

**Comment by FeldrinH** [comment]
In that case I think the documentation could use a clarification on a few related points:
* The documentation for __builtin_assume explicitly states that side effects of the expression passed to it are discarded. If this is not the case for assert_unchecked then that difference should probably be highlighted, since the documentation for assert_unchecked implies that assert_unchecked and __builtin_assume are equivalent.
* Is the expression passed to assert_unchecked likely/guaranteed to be optimized out in a release compile if it has no side effects?This could matter quite a bit for microoptimizations.

**Comment by the8472** [comment]
> Is the expression passed to assert_unchecked likely/guaranteed to be optimized out in a release compile if it has no side effects?

If there are no other uses? Probably, at some point in the optimization pipeline. But up to that point the expression is preserved which can affect earlier optimizations. Which is one of the reasons why the docs say

> [... ]but it might also make the generated code slower

The usual approach is to benchmark, look at the assembly or look at the LLVM IR after optimizations to see if it's worthwhile. Blind applications of the hint are discouraged.

**Comment by jhpratt** [comment]
Closing as completed by #123588.
