### ISSUE TITLE
Tracking Issue for asm_goto

### ISSUE THREAD

**Issue by nbdd0121** [rust-lang/rust#119364]
The feature gate for the issue is `#![feature(asm_goto)]`.

### Summary

This feature adds a `label<block>` operand type to `asm!`.

Example:
```rust

unsafe {
    asm!(
        "jmp {}",
        label {
            println!("Jumped from asm!");
        }
    );
}
```

The block must have unit type, or if `noreturn` option is used, must diverge.

### Steps

- [ ] Implementation
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

* LLVM miscompilation for asm goto with outputs

@rustbot labels: +A-inline-assembly +F-asm

**Comment by Nilstrieb** [comment]
Where is this coming from? Is there a lang MCP or anything like that?

**Comment by nbdd0121** [comment]
This is outlined as a future possibility in [RFC2873](https://rust-lang.github.io/rfcs/2873-inline-asm.html#asm-goto) which I am implementing in #119365.

**Comment by tgross35** [comment]
Could we support a named label rather than being only positional? Maybe

```rust
unsafe { asm!(
    "jmp {foo}",
    label foo {
        println!("Jumped from asm!");
    }
);}
```

**Comment by bjorn3** [comment]
```rust
unsafe { asm!(
    "jmp {foo}",
    foo = label {
        println!("Jumped from asm!");
    }
);}
```

is closer to the syntax used by other operands.

**Comment by tgross35** [comment]
_oh_, that does actually work already. Awesome

**Comment by joshtriplett** [comment]
In today's Rust-for-Linux meeting, we discussed this syntax. We realized a potential issue that wasn't considered during the design:

Because `asm!` always has to be in an `unsafe` block, that makes all the code in the labels be unsafe, too. That isn't necessarily what people want. If this integrated with existing `if` conditions people might write `if unsafe { asm!(...) } { ... } else { ... }` and those branches wouldn't be unsafe, but doing that with the current construct requires returning a bool (which currently requires label-break-value) and using *that* in an `if`, and hoping the optimizer does the right thing to have the asm branches go to the if branches. When we considered the label-based design as a syntactically simpler construct, we didn't consider that that would make the label blocks unsafe code.

We talked about a few possible ways to solve this. One that seemed appealing in the RfL meeting:

We could change the label blocks to be safe code by default. (There's some precedent for switching back to safe in unsafe code: if you define an item in an unsafe block, the contents of the item are safe.)

And, to make it less painful to use `unsafe` if you *do* need it, we can syntactically allow `ident = label unsafe { /* unsafe code */ }` in addition to `ident = label { /* safe code */ }`.

**Comment by Lokathor** [comment]
Do you mean a proposed future *different* extension to `asm!`, separate from asm_goto, would make `asm!` in some cases be an expression that could evaluate to a boolean? Because currently it can't be used in `if` like that so I'm a little confused.

**Comment by programmerjake** [comment]
> We could change the label blocks to be safe code by default. (There's some precedent for switching back to safe in unsafe code: if you define an item in an unsafe block, the contents of the item are safe.)

I think we also need a more general `safe { ... }` block, since this is far from the only case where you want known-safe code inside an `unsafe` block, e.g. macros that expand to code like `unsafe { unsafe_macro_helper(safe { safe_user_code() }, ...) }`

**Comment by joshtriplett** [comment]
> Do you mean a proposed future _different_ extension to `asm!`, separate from asm_goto, would make `asm!` in some cases be an expression that could evaluate to a boolean? Because currently it can't be used in `if` like that so I'm a little confused.

When I said:
> returning a bool (which currently requires label-break-value)

I mean this:
```rust
{'bar: { asm!("...", foo = label { break 'bar true; }); false }}
```

**Comment by nikomatsakis** [comment]
@nbdd0121 wrote up this document on [advanced assembly usage in the Linux kernel](https://hackmd.io/@nbdd0121/BJlVrepa0).

**Comment by Mark-Simulacrum** [comment]
It looks like this is now the tracking issue for the with_outputs variant of the feature since #131523, so updating the title accordingly.
