### ISSUE TITLE
Tracking Issue for RFC 3535: Constants in Patterns

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#120362]
This is a tracking issue for the RFC 3535: Constants in Patterns (rust-lang/rfcs#3535).

### Summary

When a constant appears as a pattern, this is syntactic sugar for writing a pattern that corresponds to the constant's value by hand.  This operation is only allowed when (a) the type of the constant implements `PartialEq`, and (b) the *value* of the constant being matched on has "structural equality", which means that `PartialEq` behaves the same way as that desugared pattern.

This RFC does not allow any new code, compared to what already builds on stable today.  Its purpose is to explain the rules for constants in patterns in one coherent document, and to justify why we will start *rejecting* some code that currently works (see the [breaking changes](https://github.com/rust-lang/rfcs/blob/master/text/3535-constants-in-patterns.md#breaking-changes)).

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC.
  - https://github.com/rust-lang/rust/pull/116167
  - https://github.com/rust-lang/rust/pull/116284
  - https://github.com/rust-lang/rust/pull/120423
  - https://github.com/rust-lang/rust/pull/120805
  - https://github.com/rust-lang/rust/pull/124661
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide]).
  - https://github.com/rust-lang/reference/pull/1456

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Status of the relevant lints

- [x] nontrivial_structural_match: removed in https://github.com/rust-lang/rust/pull/120423
- [x] const_patterns_without_partial_eq: turned into hard error in https://github.com/rust-lang/rust/pull/120805
- [x] illegal_floating_point_literal_pattern: partially hard error, rest removed in https://github.com/rust-lang/rust/pull/116284
- [x] indirect_structural_match: shows up in dependencies starting with Rust 1.78; will be made into hard error by https://github.com/rust-lang/rust/pull/124661
- [x] pointer_structural_match: shows up in dependencies starting with Rust 1.78; will be made into hard error by https://github.com/rust-lang/rust/pull/124661

### Unresolved questions

- [ ] When a constant is used as a pattern in a `const fn`, what exactly should we require? Also see https://github.com/rust-lang/rust/issues/119398.

### Related issues

- https://github.com/rust-lang/rust/issues/41620
- https://github.com/rust-lang/rust/issues/62411
- https://github.com/rust-lang/rust/issues/116122
- https://github.com/rust-lang/rust/issues/70861
- https://github.com/rust-lang/rust/issues/31434

**Comment by RustyYato** [comment]
> (see the [breaking changes](https://github.com/rust-lang/rust/issues/120362#breaking-changes) below)

Is there supposed to be a section about breaking changes here? Or perhaps that should link to: https://github.com/rust-lang/rfcs/blob/master/text/3535-constants-in-patterns.md#breaking-changes?

**Comment by RalfJung** [comment]
All the PRs have landed, the lints turned into hard errors, the issue closed... I would say this is done. :)
https://github.com/rust-lang/rust/issues/119398 remains open, but it doesn't need to keep this tracking issue open.

:tada:
