### ISSUE TITLE
Tracking Issue for changing rustc target docs

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#120745]
This is the tracking issue for changing rustc target docs to be generated based on the existing target triple patterns, ensuring that there's a doc page for every single target.

Discussion in https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/generating.20target.20documentation with a draft implementation in https://github.com/Nilstrieb/target-tier-docs-experiment.

### Steps

- [ ] Figure out the best format to store the target docs
- [ ] Implement infrastructure for new docs (without using it yet)
- [ ] Migrate existing docs to the new format (over several PRs)
- [ ] Use the new format for the shipped docs
- [ ] Delete the old docs

**Comment by Noratrieb** [comment]
status here: as can be seen, I haven't worked on this for a while. while I do intent to get back to it eventually, I don't want to block anyone else from doing things in this space. If someone is interested in picking this up, feel free to do so.
