### ISSUE TITLE
Tracking Issue for `derive_skip`

### ISSUE THREAD

**Issue by clubby789** [rust-lang/rust#121050]
This is a tracking issue for https://github.com/rust-lang/libs-team/issues/334.
The feature gate for the issue is `#![feature(derive_skip)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions
- How to deal with unhandled/typo arguments (e.g. `#[skip(Degub)]`
- Support for 3rd party derives, or just builtins
- Should `#[skip = "Debug"]` work?

**Comment by jplatte** [comment]
I wonder, if any fields are skipped in `Debug`, should `finish_non_exhaustive` be used automatically instead of plain `finish`?

**Comment by dead-claudia** [comment]
Related ACP: https://github.com/rust-lang/libs-team/issues/334
