### ISSUE TITLE
Tracking Issue for the 2024 prelude

### ISSUE THREAD

**Issue by Noratrieb** [rust-lang/rust#121042]
Feature gate: `#![feature(prelude_2024)]`

This is a tracking issue for the 2024 prelude.

### Public API

The 2024 prelude contains the following items in addition to all items in the 2024 prelude:

- `core::future::{Future, IntoFuture}`: RFC 3509 https://github.com/rust-lang/rfcs/pull/3509

```rust
// core::prelude

pub mod rust_2024 {
    pub use super::rust_2021::*;
    pub use crate::future::{Future, IntoFuture};
}

```

And removes `RustcEncodable`, and `RustcDecodable`:

- https://github.com/rust-lang/rust/issues/62048

### Steps

- [x] Implement in nightly Rust 2024 (`Future`, `IntoFuture`).
    - https://github.com/rust-lang/rust/pull/121041
- [x] Implement in nightly Rust 2024 (`RustcEncodeable`, `RustcDecodable`).
    - https://github.com/rust-lang/rust/pull/116016
- [x] Add migration lint for Future (based on the previous migration lints)
    - #125889
- N/A Add migration lint for RustcEncodable
  - This would be nice to have but not required.
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/292
    - https://github.com/rust-lang/edition-guide/pull/298
- [x] Update edition guide docs with migration details.
    - https://github.com/rust-lang/edition-guide/pull/314
- [x] Ensure ready for Rust 2024 stabilization.

[edition guide]: https://github.com/rust-lang/edition-guide

### Related

- https://github.com/rust-lang/rust/issues/123156

### Implementation History

- https://github.com/rust-lang/rust/pull/116016
- https://github.com/rust-lang/rust/pull/121041

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

cc @jhpratt @Nilstrieb @yoshuawuyts

**Comment by Nilstrieb** [comment]
@rust-lang/project-edition-2024 not sure how and where you want to track this in addition to the issue, but I created the issue to have something to link to.

**Comment by ehuss** [comment]
Thanks @Nilstrieb. We are doing our tracking in https://hackmd.io/@klAMrLz3QN-4luTZek9cWA/H175lzyea, and I have added that to the list.

Do you know what migration concerns there are with this change? What breakage will it cause, and what is the plan to add a migration lint for that?

**Comment by Nilstrieb** [comment]
When `TryFrom`/`TryInto` were added into the prelude in 2021, no migration lint was provided from what I can tell. But I don't see a reason why adding a migration lint wouldn't be possible (though I can't imagine the impact being very large in practice, so it probably doesn't have the highest priority).

**Comment by Nilstrieb** [comment]
Basically the breaking is that the following two programs will now error with a method ambiguity error:
```rust
trait Uwu {
    fn poll(&self) {
        println!("uwu");
    }
}
impl<T> Uwu for T {}

fn main() {
    core::pin::pin!(async {}).poll();
}
```
```rust
trait Uwu {
    fn into_future(self) where Self: Sized {
        println!("uwu");
    }
}
impl<T> Uwu for T {}

fn main() {
    async {}.into_future();
}
```
```

**Comment by ehuss** [comment]
[`rust-2021-prelude-collisions`](https://doc.rust-lang.org/nightly/rustc/lints/listing/allowed-by-default.html#rust-2021-prelude-collisions) was used to handle the migration for `TryFrom`/`TryInto`.  I would expect the migration lint would be similar to that.

**Comment by Nilstrieb** [comment]
Ah, I was searching for quite a bit but didn't find it. Then it should be pretty easy to extend the lint pass to also lint for a rust_2024_prelude_collisions.

**Comment by traviscross** [comment]
We talked through the edition items in the lang call today, and one thing on the list was "Removing Rustc\*codable from the prelude" (cc @jhpratt).  Let's perhaps track that here also.

**Comment by Nilstrieb** [comment]
I have not gotten to implement the lint yet, but I expect it to be quite simple. If anyone wants to implement, feel free to `@rustbot claim` and implement it. I do expect to get to it eventually though if no one else does it.

**Comment by jhpratt** [comment]
I intend on getting to it at some point. I'll claim whenever I start concrete work on it. Until that point, anyone should feel free to do it themself.

**Comment by jhpratt** [comment]
I am beginning work on the lint for `RustcEncodable` and `RustcDocodable`. As a prelude _removal_ rather than _addition_, it'll likely be different enough that there won't be any overlap in code. As such I will not be working on the other parts of the prelude lint.

**Comment by Nilstrieb** [comment]
I finally got around to implementing the migration lint for future in #125889.

**Comment by jhpratt** [comment]
As I just said on Zulip, I don't have a ton of time in the near future. If someone else would like to take over my side of the edition lint, please do so!

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition

Upon review, with recent work having been merged, this item is now **ready for Rust 2024**.

Thanks to @Noratrieb and @jhpratt for pushing this work forward, thanks to @ehuss for documentation, and thanks to the various reviewers who helped to get this work landed.
