### ISSUE TITLE
Tracking Issue for rust_has_provenance

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#121243]
This is a tracking issue for the RFC "Rust Has Provenance" (rust-lang/rfcs#3559).

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

(This RFC does not need any implementation.)

- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None (unless we want to bikeshed the term "provenance" itself...)

**Comment by dev-ardi** [comment]
What would it mean to stabilize this?

**Comment by Nilstrieb** [comment]
This tracking issue is mostly about tracking the official normative documentation that needs to be written about the existence of provenance (for example in `core::ptr`).
