### ISSUE TITLE
Tracking Issue for `OnceCell/Lock::get_mut_or_init`

### ISSUE THREAD

**Issue by tisonkun** [rust-lang/rust#121641]
Feature gate: `#![feature(once_cell_get_mut)]`

This is a tracking issue for

* `OnceCell::get_mut_or_init()`
* `OnceCell::get_mut_or_try_init()`
* `OnceLock::get_mut_or_init()`
* `OnceLock::get_mut_or_try_init()`
 
### Public API

```rust
    pub fn get_mut_or_try_init<F, E>(&mut self, f: F) -> Result<&mut T, E>
    where
        F: FnOnce() -> Result<T, E> { ... }

    pub fn get_mut_or_init<F>(&mut self, f: F) -> &mut T
    where
        F: FnOnce() -> T { ... }
```

### Steps / History

* [x]  ACP: https://github.com/rust-lang/libs-team/issues/294
* [x]  Implementation: https://github.com/rust-lang/rust/pull/114788
* [ ]  Final comment period (FCP)
* [ ]  Stabilization PR

 
### Unresolved Questions

None yet.

## Footnotes

1. https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html [↩](#user-content-fnref-1-39877e12402a53c830c980b62b917a0e)

**Comment by ChayimFriedman2** [comment]
The documentation seems wrong?

> Many threads may call `get_mut_or_init` concurrently with different initializing functions, but it is guaranteed that only one function will be executed.

Since it takes `&mut self`, this is entirely impossible.

The implementation can likewise be simplified a lot by not using any synchronization.

**Comment by tisonkun** [comment]
@dtolnay Shall we have an FCP for this feature? I encounter this requriement in stable toolchain today again :P

**Comment by rust-rfcbot** [comment]
@dtolnay has proposed to merge this. The next step is review by the rest of the tagged team members:

* [ ] @Amanieu
* [x] @BurntSushi
* [x] @dtolnay
* [ ] @joshtriplett
* [ ] @the8472

No concerns currently listed.

Once a majority of reviewers approve (and at most 2 approvals are outstanding), this will enter its final comment period. If you spot a major issue that hasn't been raised at any point in this process, please speak up!

cc @rust-lang/libs-ping: FCP proposed for libs, please feel free to register concerns.
See [this document](https://github.com/rust-lang/rfcbot-rs/blob/master/README.md) for info about what commands tagged team members can give me.

**Comment by coastalwhite** [comment]
Bumping this as this only needs 1 more vote to enter the FCP. This would allow a few libraries to move off `once_cell`.
