### ISSUE TITLE
Tracking Issue for Packages as (optional) namespaces

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#122349]
This is a tracking issue for the RFC "3243" (rust-lang/rfcs#3243).

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC (can anyone write up mentoring
      instructions?)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [ ] How exactly should the Cargo.toml `lib.name` key work in this world, and how does that integrate with `--extern` and `-L` and sysroots?
- [ ] Should we allow renames like `"foo::bar" = { package = "foo_bar", version = "1.0" }` in Cargo.toml?
- [ ] How precisely should this be represented in the index trie?
- [ ] How we should name the `.crate` file / download URL

Third-parties, like Linux distributions, will need to decide how to encode
cargo package names in their distribution package names according to their
individual rules.
Compared to existing ecosystems with namespaces that they package, the only new
wrinkle is that there can be 0-1 namespace levels.

**Comment by epage** [comment]
Basic cargo support is in as of rust-lang/cargo#13591 (submodule update: rust-lang/rust#122575)

I created a `cargo::issue_13576` lib and then next part to resolve in the implementation appears to be in rustc:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `/home/epage/src/personal/cargo/target/debug/cargo -Zscript check -vvv`
    Checking cargo::issue_13576 v0.1.0 (/home/epage/src/personal/dump/cargo-13576)
     Running `CARGO=/home/epage/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo CARGO_CRATE_NAME='cargo::issue_13576' CARGO_MANIFEST_DIR=/home/epage/src/personal/dump/cargo-13576 CARGO_PKG_AUTHORS='' CARGO_PKG_DESCRIPTION='' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME='cargo::issue_13576' CARGO_PKG_README='' CARGO_PKG_REPOSITORY='' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 CARGO_RUSTC_CURRENT_DIR=/home/epage/src/personal/dump/cargo-13576 LD_LIBRARY_PATH='/home/epage/src/personal/dump/cargo-13576/target/debug/deps:/home/epage/src/personal/cargo/target/debug/build/curl-sys-2b2243103868cb3e/out/build:/home/epage/src/personal/cargo/target/debug/build/libgit2-sys-71ef3ff041cafba4/out/build:/home/epage/src/personal/cargo/target/debug/build/libnghttp2-sys-5d0ed877a94b784a/out/i/lib:/home/epage/src/personal/cargo/target/debug/build/libsqlite3-sys-5134432fb6771f3a/out:/home/epage/src/personal/cargo/target/debug/build/libssh2-sys-f4299e26a5b2bcb1/out/build:/home/epage/src/personal/cargo/target/debug/deps:/home/epage/src/personal/cargo/target/debug:/home/epage/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/epage/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib' /home/epage/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name 'cargo::issue_13576' --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=5d93f16ea53919c5 -C extra-filename=-5d93f16ea53919c5 --out-dir /home/epage/src/personal/dump/cargo-13576/target/debug/deps -C incremental=/home/epage/src/personal/dump/cargo-13576/target/debug/incremental -L dependency=/home/epage/src/personal/dump/cargo-13576/target/debug/deps`
error: invalid character `':'` in crate name: `cargo::issue_13576`
  |
  = help: you can either pass `--crate-name` on the command line or add `#![crate_name="…"]` to set the crate name

error: could not compile `cargo::issue_13576` (lib) due to 1 previous error

Caused by:
  process didn't exit successfully: `CARGO=/home/epage/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo CARGO_CRATE_NAME='cargo::issue_13576' CARGO_MANIFEST_DIR=/home/epage/src/personal/dump/cargo-13576 CARGO_PKG_AUTHORS='' CARGO_PKG_DESCRIPTION='' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME='cargo::issue_13576' CARGO_PKG_README='' CARGO_PKG_REPOSITORY='' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 CARGO_RUSTC_CURRENT_DIR=/home/epage/src/personal/dump/cargo-13576 LD_LIBRARY_PATH='/home/epage/src/personal/dump/cargo-13576/target/debug/deps:/home/epage/src/personal/cargo/target/debug/build/curl-sys-2b2243103868cb3e/out/build:/home/epage/src/personal/cargo/target/debug/build/libgit2-sys-71ef3ff041cafba4/out/build:/home/epage/src/personal/cargo/target/debug/build/libnghttp2-sys-5d0ed877a94b784a/out/i/lib:/home/epage/src/personal/cargo/target/debug/build/libsqlite3-sys-5134432fb6771f3a/out:/home/epage/src/personal/cargo/target/debug/build/libssh2-sys-f4299e26a5b2bcb1/out/build:/home/epage/src/personal/cargo/target/debug/deps:/home/epage/src/personal/cargo/target/debug:/home/epage/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/epage/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib' /home/epage/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name 'cargo::issue_13576' --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=5d93f16ea53919c5 -C extra-filename=-5d93f16ea53919c5 --out-dir /home/epage/src/personal/dump/cargo-13576/target/debug/deps -C incremental=/home/epage/src/personal/dump/cargo-13576/target/debug/incremental -L dependency=/home/epage/src/personal/dump/cargo-13576/target/debug/deps` (exit status: 1)
```

The implementation will need to watch for any files/directories that are created that include `::` in the name as that is unsupported on Windows.

**Comment by epage** [comment]
@Nemo157 

> My understanding from the RFC was that the library name was meant to just be `bar`, that would avoid the rustc issue you noted
> 
> > The autogenerated `lib.name` key for such a crate will just be bar, the leaf crate name, and the expectation is that to use such crates one must use `--extern foo::bar=bar.rlib` syntax. There may be some better things possible here, perhaps `foo_bar` can be used here.
> > —https://rust-lang.github.io/rfcs/3243-packages-as-optional-namespaces.html#reference-level-explanation

> (I'd assume this also applies to the autogenerated `bin.name` for `src/main.rs`)

*(centralizing the conversation)*

**Comment by epage** [comment]
That gets complicated as cargo assumes the crate-name and extern-name are the same (and both pull from `<target>.name`) and I suspect that runs deeper than that in both programs.

**Comment by Nemo157** [comment]
Deeper than `rustc`'s assumption that a crate-name is an identifier? (IIRC pre-1.0 `-` actually made it into the crate name, so there was `extern crate "foo-bar" as foo_bar;` syntax, but that was removed from rustc and normalization to an identifier was moved to cargo).

**Comment by epage** [comment]
I can't speak to that or most of the rustc side.  If someone familiar enough with both wants to put forward a working proposal for how both sides can work, I'd love to look over it and see what the trade offs are.

**Comment by epage** [comment]
Thinking about this some more, some routes we can go
- Allow `::` in crate names, breaking rustc's assumption that its an identifier
- Translate before `<target>.name` but this breaks cargo's assumption that `<target>.name` is the name callers use to access the item
- Translate from `<target>.name` (with `::`) to an identifier when doing `--extern` calls

Some things we need to keep in mind
- Rustdoc tests should be accessed with the extern name.  I've seen rustdoc do enough weird stuff that I hold no assumptions that its behaving like a normal compilation process.
- Ideally, user errors would be in terms of the name they set, not a name used internally for bookkeeping.  If the crate name doesn't show up much in errors, maybe this isn't a big deal.

**Comment by epage** [comment]
@oli-obk why is the issue locked to collaborators?

**Comment by oli-obk** [comment]
Because half our tracking issues have more than 150 comments and that's unmanageable. I think they are notoriously bad for discussions and we should just open dedicated issues for topics.

I do realize that I forgot to state this here and that I have not looked for consensus on this opinion of mine and just done it ad-hoc. I apologize for both. I am trying to figure out how to even ask for consensus on this. There's no one team to ask.

**Comment by hydroperfox** [comment]
> Thinking about this some more, some routes we can go
> 
> * Allow `::` in crate names, breaking rustc's assumption that its an identifier
> * Translate before `<target>.name` but this breaks cargo's assumption that `<target>.name` is the name callers use to access the item
> * Translate from `<target>.name` (with `::`) to an identifier when doing `--extern` calls
> 
> Some things we need to keep in mind
> 
> * Rustdoc tests should be accessed with the `::` name.  I've seen rustdoc do enough weird stuff that I hold no assumptions that its behaving like a normal compilation process.
> * Ideally, user errors would be in terms of the name they set, not a name used internally for bookkeeping.  If the crate name doesn't show up much in errors, maybe this isn't a big deal.

Can you intercept file system calls to a crate's filename (whether for the crate's download or for the crate's target artifacts) on file open?

**Comment by Manishearth** [comment]
> Can you intercept file system calls to a crate's filename (whether for the crate's download or for the crate's target artifacts) on file open? 

I'd prefer we don't use hacks like this.

**Comment by Nemo157** [comment]
Since I don't recall ever seeing it mentioned, another unresolved question seems to be multi-registry handling:

```toml
[dependencies]
"foo::bar" = "1"
"foo::baz" = { version = "1", registry = "custom" }
```

**Comment by epage** [comment]
@Nemo157 I assume that is a question more for rust-lang/cargo#13576 as this tracking issue is just for the rustc side.

This was discussed during the RFC without a definitive answer at https://github.com/rust-lang/rfcs/pull/3243#discussion_r1120586339 but I was leaning towards leaving all restrictions for what can participate in a namespace to crates.io

**Comment by Manishearth** [comment]
@petrochenkov I suggest having the compiler team discuss this and weigh tradeoffs then. We did solicit feedback from the compiler team and got some sign off when writing this rfc.


I'm not convinced of the implementation difficulty, the list of known crates is small and the crate filtering can be done early, presumably? I think there are some other potential implementation concerns but this doesn't feel like a major one.

Also note that the RFC deliberately only introduces a single level of nesting. I don't think the problem is too bad for multiple layers either.

This might not have been in the RFC itself but generally the idea was that if you have `foo` and `foo::bar` crates, any `bar` module in `foo` can be assumed to not exist by the compoler: this is something crate owners should not do (unless it's just a reexport).

**Comment by workingjubilee** [comment]
> This might not have been in the RFC itself but generally the idea was that if you have `foo` and `foo::bar` crates, any `bar` module in `foo` can be assumed to not exist by the compoler: this is something crate owners should not do (unless it's just a reexport).

Perhaps we should specify this in some way and a predetermined resolution should be picked? ...I could see "fail the build catastrophically" being the preferred solution, here. Or is this an ambiguity that continues to be a severe problem even if we make it functionally impossible that the ambiguity ever slices two ways?

**Comment by epage** [comment]
> The core motivation in the RFC 3243 is social - allowing organizations to reserve some names and users to trust those names, it's not about some missing capabilities in the language.

This is not accurate.  While it originally started as a registry namespacing feature, with the new syntax it shifted towards being an API design feature: "(partially) open (API) namespaces".  Because of this, I've shifted the language of the tracking issues to that term even though we didn't officially rename the RFC.

For instance, Python users had hacked-in support for this for years and they officially recognized it and added support for it.  This design behaves most like Python in that it only allows you to add extend a namespace with sub-namespaces.  Python requires the top-level package to exclusively be a namespace package while we allow it to be a regular package.  We also add publish-control to our own registry (other registries and other sources of code can do their own thing).  Languages like C++ put no limits on how open namespaces are.

**Comment by heaths** [comment]
.NET (NuGet), JS (NPM), Java (Maven), Go (URIs), et. al. all have scopes built into their packaging systems.

NuGet is an interesting comparison because their registered namespace separator is `.` - the same character to separate namespace elements like `::` that was proposed for Rust. But in their cases, it's nuget.org itself that handles the reservations. For example, my team owns the `Azure.` root namespace. No one else can publish a package starting with that prefix (after the prefix support was added and our root registered). But it's still part of the package name, which tends to match the namespace.

Alternatively, if resolving `::` as part of the path is problematic, why not choose one of the other separators that was suggested? When I read through the history of the RFC a while back, there were some good suggestions and it was a little surprising that the Rust path separator was chosen because it seemed problematic to differentiate with a regular path.

**Comment by oli-obk** [comment]
> Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

**Comment by joshka** [comment]
Not quite sure which of the issues is the correct place for this (Apologies if this is the wrong place for this to be added).

I have a specific example of the unresolved question in Ratatui. We intentionally do foo::bar in foo, and also have foo-bar crate where those two are not necessarily equal. This is similar to the bevy and icu cases, but without the 1:1 mapping and that overlap causes some concern about the ambiguity between a crate and a namespace root. The focus being on separators in the naming seemed to miss the point that these are effectively different identities (crate, namespace) and should be treated as two different things.

https://docs.rs/ratatui/latest/ratatui/widgets/index.html
https://docs.rs/ratatui-widgets/0.3.2/ratatui_widgets/

I'd strongly suggest making the rust syntax side of this explicitly call this out as a namespaced crate by adding a piece of syntax. 

A guiding principal of namespace imports in code is that done right it tends to make the code readable more readable than when you have to guess where types come from due to implicit imports. A long while back I started threads (across discord, reddit, rust-lang forums) on using preludes and glob imports in libraries and found there was a resounding perspective from many rustaceans that they made source code more difficult to read due to ambiguity. We should avoid doing that with namespaces and make them require something explicit over the raw crate name.

Npm is likely a good precedent to follow there with @ as the character indicating a namespace. I'm ambivalent between either of these suggestions and don't have much of an opinion at the cargo / crate level.

```rust
use @foo::bar;
use foo@::bar;
```

Strong opinion: I think the disambiguation should be always required to be specified in source.
Weaker opinion Because it ends up in source, it should likely flow back to the cargo side of things.

**Comment by Manishearth** [comment]
I don't think that is amongst the unresolved questions, and there was significant discussion about whether we should have different syntax. Some of it was on a dedicated issue (https://github.com/Manishearth/namespacing-rfc/issues/2) but a lot of it was on the RFC itself. This distinction between namespace and module was discussed a fair amount.

When this gets implemented we should revisit these choices, but I wouldn't consider this to be an unresolved question warranting discussion _now_.

**Comment by epage** [comment]
> I have a specific example of the unresolved question in Ratatui. We intentionally do foo::bar in foo, and also have foo-bar crate where those two are not necessarily equal. This is similar to the bevy and icu cases, but without the 1:1 mapping and that overlap causes some concern about the ambiguity between a crate and a namespace root. The focus being on separators in the naming seemed to miss the point that these are effectively different identities (crate, namespace) and should be treated as two different things.

> A guiding principal of namespace imports in code is that done right it tends to make the code readable more readable than when you have to guess where types come from due to implicit imports. A long while back I started threads (across discord, reddit, rust-lang forums) on using preludes and glob imports in libraries and found there was a resounding perspective from many rustaceans that they made source code more difficult to read due to ambiguity. We should avoid doing that with namespaces and make them require something explicit over the raw crate name.

I feel like there are two things to discuss here.

The first, is on the intent of this feature. If you have a `foo-bar` that should be a `foo::bar`, then it is perfectly reasonable to not rename the package to `foo::bar`. This feature is more about language namespaces than registry namespaces and should only be used if it makes sense from the perspective of your API design in Rust.  Aspects of registry namespacing were scoped out of this RFC but we have to be careful to not take syntax (like `@`) that may be useful for registry namespacing. You can read more about those at https://internals.rust-lang.org/t/survey-of-organizational-ownership-and-registry-namespace-designs-for-cargo-and-crates-io/24027/4.

The second is potential confusion as to where names come from. That makes sense. I'm unsure if that will be to the level of a blocker or not though. We'll have to see as we explore the use of this feature. Other ecosystems do have related features though I don't think it is heavily used in those ecosystems and some of them already have some discoverability issues (decoupled package and namespace names) so it is unclear how familiar / unfamiliar this will be.

**Comment by joshka** [comment]
> When this gets implemented we should revisit these choices, but I wouldn't consider this to be an unresolved question warranting discussion _now_.

<img width="2100" height="410" alt="Image" src="https://github.com/user-attachments/assets/e384bff3-365e-4120-9177-e6651291b400" />
