### ISSUE TITLE
Tracking Issue for `Vec::pop_if`

### ISSUE THREAD

**Issue by avandesa** [rust-lang/rust#122741]
Feature gate: `#![feature(vec_pop_if)]`

This feature adds the `Vec::pop_if` method, which takes a predicate, evaluates it with the last element in the `Vec` if present, and returns the item if the predicate returns `true`. This makes it possible to conditionally remove the last element without the use of `unwrap`.

### Public API

```rust
impl<T> Vec<T> {
    pub fn pop_if(&mut self, f: impl FnOnce(&mut T) -> bool) -> Option<T>;
}
```

### Steps / History

- [X] ACP: https://github.com/rust-lang/libs-team/issues/208
- [x] Implementation: #123107
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- [X] Do we want a `VecDeque::pop_front_if` and `VecDeque::pop_back_if` API under this as well?
    - Separate tracking issue: https://github.com/rust-lang/rust/issues/135889

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by MankiratSingh1315** [comment]
I will like to work on this 👍🏼 
Although I am new in contributing to rust, so will be needing some guidance 😓

**Comment by avandesa** [comment]
Hi Mankirat, I've already got this partially implemented and am planning to open a PR tonight or tomorrow.

**Comment by tgross35** [comment]
Docs should probably mention that the function does not get run if the vector is empty.

> I don't think I have right to start an FCP, so I will just open a PR instead.

You can add the I-libs-api-nominated label with rustbot

**Comment by Amanieu** [comment]
Yes, please do. It's always backwards-compatible to change an `impl Trait ` to a generic parameter, but not the other way around.

**Comment by fmease** [comment]
> It's always backwards-compatible to change an `impl Trait` to a generic parameter

This is not true: Such a change breaks call/usage sites where the generic argument list is specified (aka turbofished call/usage sites).

However, in the case of `Vec::pop_if` which doesn't have own generic parameters, such code is be incredibly unlikely to be written in practice (only macro-generated code would realistically contain usages like `v.pop_if::<>(f)`).
