### ISSUE TITLE
Tracking Issue for match ergonomics 2024

### ISSUE THREAD

**Issue by Jules-Bertholet** [rust-lang/rust#123076]
This is a tracking issue for changes to match ergonomics for the 2024 edition, as described in #105647, #64586, https://hackmd.io/YLKslGwpQOeAyGBayO9mdw.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] `mut ref`/`mut ref mut`
  - [ ] Bikeshed
  - [ ] Update all pattern diagnostics to ensure they know about this
- [ ] Changes to `&` and `&mut` patterns
  - [ ] The HackMD says the reference types should be "compatible", not sure what that means so in the current impl they must match exactly
- [ ] Don't reset binding mode on `mut` with edition >= 2024
  - [ ] Edition migration lint
    - [ ] Rustfix
- [ ] Documentation
- [ ] FCP (RFC?)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- `mut ref mut` vs `ref mut (mut` syntax
-  The HackMD says the reference types should be "compatible", what does this mean and why?

### Implementation history

https://github.com/rust-lang/rust/pull/122978

@rustbot label T-lang A-patterns A-edition-2024

**Comment by Nadrieril** [comment]
Noting here that I no longer think we need the "`&<pat>` everywhere" part of the proposal. This makes the proposed fix less local but saves us in design and possible conflicts with deref patterns.

**Comment by Jules-Bertholet** [comment]
> possible conflicts with deref patterns.

Can you elaborate?

**Comment by traviscross** [comment]
@rustbot labels +I-lang-nominated

@Jules-Bertholet has picked up this work and is looking for a liaison for the experiment.  Let's nominate to discuss.

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this is in the lang meeting today, and I'll be picking up liaisoning on this one.  Please let me know whenever anything is needed to move this forward.

Thanks to @Nadrieril for the original work here, and thanks to @Jules-Bertholet for carrying the torch forward.

**Comment by Jules-Bertholet** [comment]
# Proposal for the lang team

Here's my current plan for this feature. Assumes familarity with <https://hackmd.io/YLKslGwpQOeAyGBayO9mdw>, I'll be going into detail only where my proposal differs.

## `mut ref`/`mut ref mut`

Adding `mut` before `ref` makes the *binding* mutable, as opposed to `mut` after `ref` which makes the *reference* mutable. This would be available in all editions. I chose this syntax over `ref (mut` because it's simpler and easier to parse.

## Non-dereferencing `mut <binding>`

In edition 2024, `mut` no longer resets the binding mode.

## Eat-one-layer

I'm proposing to go with a variant of the "eat-one-layer" option: in edition 2024, a reference pattern matches against exactly one reference: either the inherited match ergonomics reference, or if this is not possible the reference in the scrutinee. Subtleties:

- For now, the implementation requires the mutability of the matching and matched references to be the same. I'm open to changing this to allow an immutable reference pattern to match against a mutable reference; this would be a backward-compatible change, so I'm leaving it as a future possibility in light of the edition time crunch.

- As implemented, an `&mut` pattern will consume an `&mut` in the scrutinee even if there is an inherited `&`:

```rust
if let Some(Some(&mut x)) = &Some(Some(&mut 0)) {
    let _: &u32 = x;
}
```

- As a further extension, an `&mut` pattern can "peel off" multiple layers of `&` in the scrutinee:

```rust
let &mut x = &&mut 0;
let _: &u32 = x;

let &mut x = &&&&&&&&&&&&&&&&&&&&&&&&&&&&mut 0;
let _: &u32 = x;

let &mut &mut &mut &mut x = &mut &&&&mut &&&mut &mut 0;
let _: &u32 = x;
```

### Alternatives

The alternative "eat-two-layers" proposal is also implemented behind its own feature gate, if the lang team feels that eat-one-layer is too ambitious we can switch to it. We could also do eat-two-layers in ≤ 2021 along with eat-one-layer in ≥ 2024, but that would require (slightly) more complexity, and "editions are meant to be adopted."

## Never inherit mutable reference behind shared

As implemented, in edition 2024 a mutable match-ergonomics reference is never generated behind a shared reference pattern. This is necessary for the code below to work without `&` patterns even though `&` patterns can't yet consume `&mut`:

```rust
if let Some(&Some(x)) = &mut Some(&Some(0)) {
    let _: &u32 = x;
}
```

It also allows the below to compile:

```rust
if let &Some(Some(x)) = &Some(&mut Some(0)) {
               // ^ ERROR cannot borrow as mutable (on today's Rust) → shared borrow (with current impl on Rust 2024)
    let a: &u8 = x;
} 
```

This behavior could be extended to all editions, as implemented it's 2024 only. A future possibility is to be even smarter, and downgrade to `&` in more situations where staying as `&mut` leads to an error.

## Migration lint + rustfix

The major missing piece that's not implemented yet. The rustfix suggestion would entirely desugar the match ergonomics of any pattern whose meaning is changed. Maybe we can be smarter than that, can't say for sure until I actually sit down and implement it.

@traviscross go ahead and nominate this if you'd like

**Comment by WaffleLapkin** [comment]
@Jules-Bertholet I'm confused about a couple points in your proposal, can you clarify why are things implemented this way?


> As implemented, an &mut pattern will consume an `&mut` in the scrutinee even if there is an inherited `&`:
> ```rust
> if let Some(Some(&mut x)) = &Some(Some(&mut 0)) {
>     let _: &u32 = x;
> }
> ```

Why? This sort-of makes sense, if you think of `&mut` as a structure-like pattern -- after matching `Some(Some(...))`, `...` is matched against `&&mut u32`, and `&mut ...` then projects `&`, making the type `&u32`...

But that seems weird? I think this is more confusing than to error, because the type is `&_` and it must be matched by `&_` pattern.

Said another way: I don't think it makes sense to think of `&`/`&mut` patterns as structure-like.

> As a further extension, an `&mut` pattern can "peel off" multiple layers of `&` in the scrutinee:

This is a concequence of the same "treat `&mut` as structure-like pattern" and this feels even more confusing.

> As implemented, in edition 2024 a mutable match-ergonomics reference is never generated behind a shared reference pattern. This is necessary for the code below to work even though & patterns can't yet consume &mut:
> ```rust
> if let Some(&Some(x)) = &mut Some(&Some(0)) {
>     let _: &u32 = x;
> }
> ```

I don't get why this example works? And it also doesn't seem to have any place where a mutable match-ergonomics reference could be created behind a shared reference, it's in front here.

| pattern | type | comment |
|---|---|---|
| `Some(_)` | `&mut Option<&Option<u32>>` | |
| `&_` | `&mut &Option<u32>` | why doesn't this error? (mutabilities don't match) |

One could assume that this means that `&` also works like a structure pattern and `&mut` here is projected (and downgraded to `&`). But that would mean that making `&` match on `&mut` would be a breaking change (`let &x = &mut &mut &1;`, weird projecting rules you describe: `x: &i32`, after making `&` deref mutable references: `x: &mut &i32`).

The change as described/the second example does make sense though:
```rust
if let &Some(Some(x)) = &Some(&mut Some(0)) {
    let a: &u8 = x;
} 
```
Although I'm not sure it's necessary, downgrading `&mut` to `&` after we went through `&` seems sensible.

With all of the above I feel quite strongly that `&mut` and `&` must _not_ behave like structures, projecting the other reference kind.


---

Also, I do not understand what "as implemented" means. With all features enabled _and_ 2024 edition, I still couldn't get any of your examples to compile: [[play]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=5e6ef3597e9774757bd577a91a4b3e51).

**Comment by Jules-Bertholet** [comment]
> Also, I do not understand what "as implemented" means. With all features enabled _and_ 2024 edition, I still couldn't get any of your examples to compile: [[play]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=5e6ef3597e9774757bd577a91a4b3e51).

You were missing `#![feature(ref_pat_eat_one_layer_2024)]` (which I forgot to add to the tracking issue, sorry).

**Comment by Jules-Bertholet** [comment]
> This sort-of makes sense, if you think of `&mut` as a structure-like pattern

My mental model: structure patterns have the highest "weight class", `&` has the lowest, and `&mut` is in between. Higher-weight patterns can strip off lower-weight ones.

The motivating example is code like this:

```rust
if let Some(Some(&mut x)) = &Some(Some(&mut 0)) {
    let _: &u32 = x;
}
```

The equivalent pattern without this feature requires `ref`:

```rust
if let Some(Some(&&mut (ref x))) = &Some(Some(&mut 0)) {
    let _: &u32 = x;
}
```

---


> > As implemented, in edition 2024 a mutable match-ergonomics reference is never generated behind a shared reference pattern. This is necessary for the code below to work even though `&` patterns can't yet consume `&mut`:

> > ```rust
> > if let Some(&Some(x)) = &mut Some(&Some(0)) {
> >     let _: &u32 = x;
> > }
> > ```
> 
> I don't get why this example works?

The `&` pattern cannot match against the inherited `&mut`, so it instead matches against the `&` in the scrutinee directly, leaving the inherited `&mut` in place. However, as we go deeper into the pattern, we are now behind an `&` dereference, so this inherited `&mut` is downgraded to `&`, so the final type of `x` is `&u32`. (If `&` patterns are later allowed to consume `&mut`, then the same result will be achieved via a different mechanism: the `&` pattern will match against the inherited `&mut`, leaving the `&` in the type to be inherited.)

---

> And it also doesn't seem to have any place where a mutable match-ergonomics reference could be created behind a shared reference, it's in front here.

You're right, here's a better example:

```rust
if let &Some(Some(x)) = &Some(&mut Some(0)) {
    let _: &u32 = x;
}
```

**Comment by WaffleLapkin** [comment]
> My mental model: structure patterns have the highest "weight class", `&` has the lowest, and `&mut` is in between. Higher-weight patterns can strip off lower-weight ones.

I'm not sure why this is necessary. When structure pattern project outer references into inner references (`&&Struct`->`&Field`) we "strip" references because the `&Field` is a new value we just created, and it doesn't really have an address[^1].

I do not see why `&` and `&mut` need the same "projection" behavior. IMO they should do the much simpler thing of doing a single dereference[^2].

> The motivating example is code like this:
> ```rust
> if let Some(Some(&mut x)) = &Some(Some(&mut 0)) {
>     let _: &u32 = x;
> }
> ```
> The equivalent pattern without this feature requires `ref`:
> ```rust
> if let Some(Some(&&mut (ref x))) = &Some(Some(&mut 0)) {
>     let _: &u32 = x;
> }
> ```

With "`&mut` gets downgraded when matched after matching through `&`" this is just
```rust
if let Some(Some(x)) = &Some(&mut Some(0)) {
    let _: &u32 = x;
}
```

| pattern | type |
|---|---|
| `Some(_)` | `&Option<&mut Option<u32>>` |
| `Some(_)` | `&&mut Option<u32>` |
| `x` | `&u32` |

The last one is (could be?) `&u32`, because 
1. you can't project multiple references
2. after we go through `&`, `&mut` can't be used mutably

----

> The `&` pattern cannot match against the inherited `&mut`, so it instead matches against the `&` in the scrutinee directly, [...]

Why doesn't it just immediately error out?

> leaving the inherited `&mut` in place. However, as we go deeper into the pattern, we are now behind an `&` dereference, so this inherited `&mut` is downgraded to `&`, so the final type of `x` is `&u32`. (If `&` patterns are later allowed to consume `&mut`, then the same result will be achieved via a different mechanism: the `& `pattern will match against the inherited `&mut`, leaving the `&` in the type to be inherited.)

Interesting. So what this uses is the fact that there can only be 1 inhereted reference, so `&` can match either the outer-inhereted or the second-outer reference, both of which lead to the same consequence. This makes me slightly uncomfortable, because the change will break the semantics, it just happens to lead to the same result, which is not very comforting... The logic does feel sound though.

What's even worse though is that it makes a distinction between inhereted and normal references. I think this is a big problem for teachability and simplicity, without necessary motivation. `&` being able to match through mutable references inhereted when projecting, but not able to match through normal `&mut` references is a weird consequence of this, which will be hard to explain.

And it seems to be the opposite of what we were trying to achieve with `&` being able to match inhereted references, i.e. inhereted and normal references behaving in the same way in pattern matching.

----

> You're right, here's a better example:
> ```rust
> if let &Some(Some(x)) = &Some(&mut Some(0)) {
>     let _: &u32 = x;
> }
> ```

👍🏻 

[^1]: err, not sure how to best phrase this, but since `&Field` is a temporary, if we'd borrow it again for `&&Field`, that wouldn't help us in any way, since the outer ref would just reference a temporary...
[^2]: + maybe checking that the mutability matches

**Comment by Nadrieril** [comment]
If I may: while this are important clarifications, tracking issues are not the place for these kinds of discussions

**Comment by tmandry** [comment]
To add to what @traviscross said, multiple people expressed concerns with stabilizing a syntax that includes `mut ref mut`. Some wondered whether the benefits of having mutable reference bindings at all was worth the confusing syntax, and others wondered if a syntax using parentheses would be better. Personally, I find it unfortunate that `mut ref` means something different than what people mean when they say "mutable reference".

Since working this out might be time consuming, one option would be to focus on writing an RFC with the edition-relevant changes first and leave the more "controversial" bits for a follow-up RFC.

**Comment by Jules-Bertholet** [comment]
RFC posted: https://github.com/rust-lang/rfcs/pull/3627

**Comment by traviscross** [comment]
@rustbot labels -A-edition-2024

We're going to move the edition tag over to...

- https://github.com/rust-lang/rust/issues/131414

...so as to track what's going in Rust 2024 separately from the broader RFC 3627 work.

**Comment by joshtriplett** [comment]
What is the current state of this feature? Is it ready for a stabilization report?
