### ISSUE TITLE
Tracking Issue for __rust_no_alloc_shim_is_unstable

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#123015]
### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement (done in https://github.com/rust-lang/rust/pull/86844)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

* Do we want to commit to allowing linking default output (rlib) format with arbitrary linkers? (see https://github.com/rust-lang/rust/pull/86844#issuecomment-1291008533)
* TODO, maybe more. Maybe we want some formal RFC etc. before stabilizing this.

### Implementation history

* https://github.com/rust-lang/rust/pull/86844
  *  default_alloc_error_handler became stable in https://github.com/rust-lang/rust/pull/102318

**Comment by Mark-Simulacrum** [comment]
cc @bjorn3 -- wanted to file something official for this internal unstable detail (don't think anything existed already).

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rust/pull/102318 is not really useful as the alloc error handler is still part of the allocator shim. https://github.com/rust-lang/rust/pull/112331 would entirely remove the allocation error handler. After that the allocator shim only contains the `__rust_alloc_error_handler_should_panic` static when `#[global_allocator]` is used. Maybe a weak static in liballoc with the default value when `-Zoom` is not passed would work for that?

**Comment by riking** [comment]
After #127173, definitions of this symbol must include the `#[rustc_std_internal_symbol]` attribute, it looks like.

**Comment by bjorn3** [comment]
It should be to avoid breakage in the future, but currently there is an exception to not mangle this symbol for now.
