### ISSUE TITLE
This is a tracking issue for reviewing and moving sanitizers into a compiler crate (i.e., `rustc_sanitizers`)

### ISSUE THREAD

**Issue by rcvalle** [rust-lang/rust#123619]
This is a tracking issue for reviewing previously-added support for sanitizers to the Rust compiler, and moving and organizing as much as possible of the sanitizers source code into a compiler crate (i.e., `rustc_sanitizers`). This is part of our work to organize and stabilize support for the sanitizers. (See our roadmap at https://hackmd.io/@rcvalle/S1Ou9K6H6.)

### Steps

- [ ] Create the `rustc_sanitizers` compiler crate.
- [ ] Move the source code for the CFI and KCFI sanitizers to the `rustc_sanitizers` crate.
- [ ] Move common sanitizers source code, review and move other sanitizers to the `rustc_sanitizers` crate.
- [ ] TBD.

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.
