### ISSUE TITLE
Tracking Issue for pattern types

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#123646]
This is a tracking issue for the feature gate `#![feature(pattern_types)`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implementation (#120131)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Implementation history

* #120131 initial implementation of range patterns

**Comment by oli-obk** [comment]
Locking this issue, as discussions on tracking issues have a tendency to become unmanageable. Open new issues or zulip discussions if you encounter issues or want to discuss aspects of this feature.

**Comment by clarfonthey** [comment]
You can label things with `@rustbot label +F-pattern-types`. This even works in the issue description, although won't work if it's edited after being posted; you need separate comments for that.

**Comment by yhx-12243** [comment]
Some question about implementation:
1. https://github.com/rust-lang/rust/blob/6eda7419e71fdbc1185ed5be7e6bff1a474ab5cd/compiler/rustc_ty_utils/src/layout.rs#L309-L315
  I don't know why we should deliberately avoid the wrapping pattern-type for unsigned integers, e.g.: `pattern_type!(u8 is 0..=15 | 240..)`, they should have the same position as signed ones.
2. https://github.com/rust-lang/rust/blob/6eda7419e71fdbc1185ed5be7e6bff1a474ab5cd/compiler/rustc_ty_utils/src/layout.rs#L342-L349
  One should also check `layout.size.signed_int_min() as u128 != first.0`, to obey the desired semantic: a wrapping single range.
  Of course, if the first was resolved, one should check whether it is equal to the minimum for corresponding signedness, not only signed.

**Comment by oli-obk** [comment]
Please join the discussion on Zulip and do not discuss things on tracking issues

https://rust-lang.zulipchat.com/#narrow/channel/481660-t-lang.2Fpattern-types
