### ISSUE TITLE
Tracking Issue for updating `expr` macro fragment specifier for Rust 2024

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123742]
This is a tracking issue for updating the `expr` fragment specifier for Rust 2024 according to the policy described in RFC 3531:

- https://github.com/rust-lang/rfcs/pull/3531

The feature gate for the issue is `#![feature(expr_fragment_specifier_2024)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024.
  - https://github.com/rust-lang/rust/pull/123865
- [x] Add test cases around nested macros spanning crates across different editions. For ideas, see [this comment](https://github.com/rust-lang/rust/pull/123865#discussion_r1577176199).
    - https://github.com/rust-lang/rust/pull/129755 
- [x] Update `expr` to match `_`.
    - https://github.com/rust-lang/rust/pull/126697
- [x] Implement migration lints.
  - https://github.com/rust-lang/rust/pull/125627
- [x] Remove edition gating on `expr_2021` fragment specifier.
  - https://github.com/rust-lang/rust/pull/126700
- [x] Stabilize new fragment specifier (`expr_2021`) in all editions.
  - https://github.com/rust-lang/rust/pull/129972
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- [x] Add documentation to the [reference][].
    - https://github.com/rust-lang/reference/pull/1580
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/312
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr

### Unresolved Questions

- [x] Is there a reasonable semantically-appropriate name for `expr_2021`, or should we just call it that per the RFC?
    - Resolved, keeping `expr_2021`, see https://github.com/rust-lang/rust/issues/123742#issuecomment-2315764431.

### Related

- https://github.com/rust-lang/rust/pull/84364
- https://github.com/rust-lang/rust/issues/86730
- #123865
- #125828
- #126700
- #126697
- https://github.com/rust-lang/rust/pull/126700

cc @rust-lang/wg-macros @eholk @vincenzopalazzo

**Comment by eholk** [comment]
Do we also need `item_2021`, `block_2021`, etc.?

**Comment by Veykril** [comment]
It depends on what changes to the grammar have occured.

**Comment by ehuss** [comment]
Can someone please write down what changes are being done for this?

**Comment by eholk** [comment]
Based on #86730, it looks like we also need to update `expr` to match let chains.

**Comment by eholk** [comment]
We might need to update `item` since we'll be requiring `unsafe extern` blocks in 2024, but it's not totally clear to me since I think you will be able to use `unsafe extern` in earlier editions, it just won't be required.

**Comment by eholk** [comment]
I guess the other potential change for `expr` is let chains. I spent some time working on them today, and it's not really clear to me what the right behavior is right now.

As I understand the RFC and #86730, we want to update `expr` in edition 2024 to match `let x = y`, even though that form is only allowed in the test position of an `if` or `while` loop.

This seems weird to me. Do we have `expr` match let chains unconditionally, and then expect the expansion will fail? Does `expr` only match a let chain if the macro is called in test position?

I think instead it'd make more sense to add a `cond` nonterminal what matches anything that can appear in the test position of an `if` or `while` loop.

**Comment by ehuss** [comment]
See also #126749 about whether or not `$item` should accept `safe fn foo();`, and if so should there be a separate `$item_2021` for that?

**Comment by ehuss** [comment]
@compiler-errors pointed out that `safe` items won't be an issue, because `$item` already fails to parse `safe fn foo();` because `$item` can already start with the `safe` token, so ignore my last comment.

**Comment by traviscross** [comment]
To confirm, the current understanding (now reflected in the issue description) is that the `item` fragment specifier does not need to be migrated.

This is because this is currently an error on stable Rust:

```rust
macro_rules! item {
    ($x:item) => {};
    ($(x:tt)*) => {};
}

fn main() {
    item!(safe fn foo() {});
}
```

...and because this is *not* an error on stable Rust:

```rust
macro_rules! item {
    ($x:item) => { 0u8 };
    ($(x:tt)*) => { 0u16 };
}

fn main() {
    let _: u8 = item!(unsafe extern {});
}
```

**Comment by eholk** [comment]
You know, all these examples to answer questions we have here should probably be added to the test suite so we have more confidence in the future.

**Comment by ehuss** [comment]
Draft of edition docs is up at https://github.com/rust-lang/edition-guide/pull/312.

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed in the call today.  We'll name this `expr_2021`, as it is now.

In the implementation, it's currently gated on Rust 2021 and later.  We'll want to change it to be available in all editions.  And we'll want to get that new specifier stabilized soon, ahead of the edition.

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition

We reviewed this item in the edition call, and we confirmed this is now **ready** for Rust 2024.

Thanks to @eholk and @vincenzopalazzo for pushing forward on this important work.

**Comment by vincenzopalazzo** [comment]
Thank @traviscross manage and coordinate the work👌🏼
