### ISSUE TITLE
Tracking Issue for "don't special case diverging blocks"

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123747]
This is a tracking issue for the change to not special case the type of diverging blocks.

- https://github.com/rust-lang/rust/pull/123590

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement in nightly Rust 2024.
  - https://github.com/rust-lang/rust/pull/123590
- [ ] Implement migration lints.
    - [ ] Add a list against control-flow keywords used with `;` at the end of a block (e.g. `{ return; }`).
    - https://github.com/rust-lang/rust/pull/125793
- [ ] Adjust `rustfmt`.
  - https://github.com/rust-lang/rustfmt/pull/6149
- [ ] Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- [ ] Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
- [ ] Add documentation to the [edition guide][].
- [ ] Add formatting for new syntax to the [style guide][].
    - See the [nightly style procedure][].
- [ ] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Related

- https://github.com/rust-lang/rustfmt/issues/993
- https://github.com/rust-lang/rustfmt/pull/6149

### Implementation history

- https://github.com/rust-lang/rust/pull/123590
- https://github.com/rust-lang/rust/pull/125793

cc @WaffleLapkin @rust-lang/style @rust-lang/rustfmt @calebcartwright

**Comment by traviscross** [comment]
@rustbot labels -A-edition-2024

As described here:

https://github.com/rust-lang/rust/issues/125936#issuecomment-2153446908

This isn't going to happen for Rust 2024, and there's no current plan otherwise to change the status quo, so let's remove this from the edition and close the tracking issue.
