### ISSUE TITLE
Tracking Issue for RFC 3593: Reserve unprefixed guarded string literals in Edition 2024

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123735]
This is a tracking issue for the RFC 3593: Reserve unprefixed guarded string literals in Edition 2024.

- https://github.com/rust-lang/rfcs/pull/3593

The feature gate for the issue is `#![feature(unprefixed_guarded_strings)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Accept the RFC.
  - https://github.com/rust-lang/rfcs/pull/3593
- [x] Implement in nightly Rust 2024.
  - https://github.com/rust-lang/rust/pull/123951
  - https://github.com/rust-lang/rust/pull/124605
- [x] Implement migration lints.
  - https://github.com/rust-lang/rust/pull/123951
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- [x] Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
    - https://github.com/rust-lang/reference/pull/1652
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/326
- [x] Add formatting for new syntax to the [style guide][].
    - See the [nightly style procedure][].
    - N/A.
- [ ] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Implementation history

- https://github.com/rust-lang/rust/pull/123951

cc @pitaj

**Comment by ehuss** [comment]
Posted documentation at https://github.com/rust-lang/edition-guide/pull/326 and https://github.com/rust-lang/reference/pull/1652.

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition

We reviewed this in our edition call today, and this is **ready** for Rust 2024.

Thanks to @pitaj for pushing forward on this, and thanks to @ehuss for the documentation here.
