### ISSUE TITLE
Tracking Issue for RFC 3325: unsafe attributes

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123757]
This is a tracking issue for RFC 3325: unsafe attributes

RFC: https://github.com/rust-lang/rfcs/pull/3325
Issues: https://github.com/rust-lang/rust/labels/F-unsafe_attributes

The feature gate for the issue is `#![feature(unsafe_attributes)]`.

For a table showing the attributes that were considered to be included in the list to require unsafe, and subsequent reasoning about why each such attribute was or was not included, see [this comment here](https://github.com/rust-lang/rust/pull/124214#issuecomment-2124753464)

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Accept the RFC.
  - https://github.com/rust-lang/rfcs/pull/3325
- [x] Implement in nightly Rust 2024.
  - https://github.com/rust-lang/rust/pull/124214
  - https://github.com/rust-lang/rust/pull/126177
  - https://github.com/rust-lang/rust/pull/127543
- [x] Implement migration lints.
  - https://github.com/rust-lang/rust/pull/126177
- [x] rustfmt support
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- [x] Add documentation to the [reference][].
    - https://github.com/rust-lang/reference/pull/1539
    - https://github.com/rust-lang/reference/pull/1579
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/308
- N/A: Add formatting for new syntax to the [style guide][].
    - See the [nightly style procedure][].
- [x] Stabilize in all editions.
    - https://github.com/rust-lang/rust/pull/128771
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- **Different lint staging.** The lint on using existing unsafe attributes like `no_mangle` outside `unsafe(...)` could be staged in various ways: it could be warn-by-default to start or we wait a while before to do that, it could be edition-dependent, it might eventually be deny-by-default or even a hard error on some editions -- there are lots of details here, which can be determined later during the process.

### Implementation history

- https://github.com/rust-lang/rust/pull/124214
- https://github.com/rust-lang/rust/pull/127543

cc @RalfJung @carbotaniuman @rust-lang/style

This issue has been assigned to @carbotaniuman via [this comment](https://github.com/rust-lang/rust/issues/123757#issuecomment-2068257309).

**Comment by traviscross** [comment]
@rustbot assign @carbotaniuman

@carbotaniuman has volunteered to own this item to get it over the line for the edition.  Huge thanks for that.

**Comment by traviscross** [comment]
@rustbot labels +I-style-nominated

There's probably not a lot for T-style to do here, but strictly speaking, this is a kind of new syntax, so it may be worth at least a short discussion for visibility.

**Comment by traviscross** [comment]
@rustbot labels -I-style-nominated

We discussed this in the style team meeting today and confirmed that this will not require any special handling or changes to the style guide.

**Comment by ehuss** [comment]
Edition docs are up at https://github.com/rust-lang/edition-guide/pull/308.

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition

We reviewed this in the edition call today.  This item is **ready for Rust 2024**.

Thanks to @carbotaniuman for pushing forward this item.  Thanks to @RalfJung for writing up the RFC.  And thanks to the many reviewers for making this happen.

**Comment by RalfJung** [comment]
Let's reopen this to track documentation: somewhere around [here](https://doc.rust-lang.org/reference/abi.html?highlight=no_mangle#the-no_mangle-attribute), it should document what the safety requirements are for these attributes.

**Comment by ehuss** [comment]
@RalfJung That documentation has already been updated by https://github.com/rust-lang/reference/pull/1539. Can you say if that covers what you are expecting?

**Comment by geofft** [comment]
I think we could add a sentence like "It may also lead to addresses being accessed with the wrong address space, for instance, on Harvard architectures" to address #76507 specifically, but I think "place data and code into sections
of memory not expecting them" sort of covers that already.

**Comment by RalfJung** [comment]
Ah, fair, yes that should suffice for now. :)

**Comment by arthuro555** [comment]
Sorry for asking a silly question, I was wondering if rust can and/or does give a best effort attempt at making these attributes safer? My understanding is that, since some libraries and symbols are found by the linker, which the rust compiler is not aware or in control of, so the rust compiler cannot know for sure there may not be a duplicate symbol.

However, could (and/or does) the rust compiler detect duplicate symbols and raise an error by:
- Checking for duplicate symbols within the known unsafe symbols defined in the rust code?
- Detecting when a common default setup is in use, and raise an error if it is detected we are duplicating a symbol already in-use by that setup, like [the `malloc` example in the edition guide](https://doc.rust-lang.org/nightly/edition-guide/rust-2024/unsafe-attributes.html)?
- Try and build an (even if naive & non-exhaustive) list of detected libraries that are linked, parse a list of their symbols and match them against the unsafe symbol names?
- Allow crates that may link libraries with global functions to declare a list of symbol names that may not be used?

Please excuse me if I am spouting nonsense or misusing terminology, my understanding of that space is very sparse!

**Comment by RalfJung** [comment]
Those are good questions, but the tracking issue of a fully-implemented RFC is the wrong place to raise them. :)  I would suggest starting a discussion on [IRLO](https://internals.rust-lang.org/).
