### ISSUE TITLE
Tracking Issue for Rust 2024: `Box<[T]>: IntoIter`

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123759]
This is a tracking issue for `Box<[T]>: IntoIter` in Rust 2024.

- https://github.com/rust-lang/rust/pull/116607
- https://github.com/rust-lang/libs-team/issues/263
- https://github.com/rust-lang/rust/issues/59878

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024 for `Box<[T]>`.
  - https://github.com/rust-lang/rust/pull/124097
- [x] Implement migration lints for `Box<[T]>`.
  - https://github.com/rust-lang/rust/pull/124097
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- N/A: Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/307
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Related items

- https://github.com/rust-lang/rust/pull/116607
- https://github.com/rust-lang/libs-team/issues/263
- https://github.com/rust-lang/rust/issues/59878
- https://github.com/rust-lang/rust/pull/124108

### Implementation history

- https://github.com/rust-lang/rust/pull/124097

cc @rust-lang/libs-api @clarfonthey @jhpratt

**Comment by traviscross** [comment]
Based on the results of the crater run in #124108, it doesn't seem that needs the migration hack, so when that lands it will be insta-stable and not coupled to the edition.  So we can pull that off the list.

Consequently, all the remainder of this item needs now to be done is documentation.

**Comment by cuviper** [comment]
Note, that crater run was only for `Box<[T; N]>`, not `Box<[T]>`.

**Comment by traviscross** [comment]
Right.  `Box<[T]>` is #124097 which does need the migration hack, and is coupled to the edition.

**Comment by clarfonthey** [comment]
(The point being made here is that the issue should only reference the `Box<[T]>: IntoIterator` implementation, and not the `Box<[T; N]>: IntoIterator` implementation, to avoid confusing people tracking it. Right now it references both.)

**Comment by ehuss** [comment]
Docs are up at https://github.com/rust-lang/edition-guide/pull/307.

**Comment by traviscross** [comment]
We've confirmed this issue is entirely ready for Rust 2024.  Thanks to @compiler-errors and @clarfonthey for the implementation work here.
