### ISSUE TITLE
Tracking Issue for Rust 2024: Cargo MSRV-dependent dependency version resolution

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123749]
This is a tracking issue for the Rust 2024-relevant parts of:

- https://github.com/rust-lang/rfcs/pull/3537
- https://github.com/rust-lang/cargo/issues/9930

Most things should go in the Cargo tracking issue  This issue is for tracking readiness for the Rust 2024 edition.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the change in Rust 2024.
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide]).
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide]).
- [ ] Ensure ready for release of Rust 2024.

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

**Comment by epage** [comment]
rust-lang/cargo#9930 is "dev complete".  The caveats are two open questions
- rust-lang/cargo#13791: code is written, we just need to decide if we want to merge it
- rust-lang/cargo#13540: 99% of the code is written and merged, we just need to decide on the final names and create a PR for it
