### ISSUE TITLE
Tracking Issue for RFC 3484: Unsafe Extern Blocks

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123743]
This is a tracking issue for the RFC 3484: Unsafe Extern Blocks

RFC: https://github.com/rust-lang/rfcs/pull/3484
Issues: https://github.com/rust-lang/rust/labels/F-unsafe_extern_blocks

The feature gate for the issue is `#![feature(unsafe_extern_blocks)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Accept the RFC.
  - https://github.com/rust-lang/rfcs/pull/3484
- [x] Implement in nightly with feature flag and with Rust 2024 behavior (with feature flag).
    - https://github.com/rust-lang/rust/pull/124482
- [x] Implement migration lints.
    - https://github.com/rust-lang/rust/pull/124482
- [x] Fire `unsafe_code` lint for `unsafe extern` blocks
   - https://github.com/rust-lang/rust/issues/126738
   - https://github.com/rust-lang/rust/pull/127535
- [x] rustfmt support
   - https://github.com/rust-lang/rustfmt/pull/6204
- [x] Stabilize in all editions.
   - https://github.com/rust-lang/rust/pull/127921
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- [x] Add documentation to the [reference][].
    - https://github.com/rust-lang/reference/pull/1536
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/309
    - https://github.com/rust-lang/edition-guide/pull/313
- [x] Add formatting for new syntax to the [style guide][].
    - https://github.com/rust-lang/rust/pull/127922
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- Extern declarations are actually always unsafe and able to cause UB regardless of edition. This RFC doesn't have a specific answer on how to improve pre-2027 code.
    - could use attributes

### Related

- https://github.com/rust-lang/rust/pull/124482
- https://github.com/rust-lang/rust/pull/124455
- https://github.com/rust-lang/rust/pull/125077
- https://github.com/rust-lang/rust/pull/125522
- https://github.com/rust-lang/rust/issues/126738
- https://github.com/rust-lang/rust/issues/126749
- https://github.com/rust-lang/rust/issues/126755
- https://github.com/rust-lang/rust/pull/126757
- https://github.com/rust-lang/rust/pull/126758
- https://github.com/rust-lang/rust/issues/126756
- https://github.com/rust-lang/rust/pull/126973
- https://github.com/rust-lang/rust/pull/127535
- https://github.com/rust-lang/rustfmt/pull/6204

cc @Lokathor @spastorino

**Comment by oli-obk** [comment]
I have been reviewing some work (and the required refactorings), and they need more nested refactorings 😓 

The only way to get it done in time is to not do refactorings before, but just leave FIXMEs, which doesn't sit right with me. So:

let's not do this for the 2024 edition, but jump straight into implementing the 2027 edition

**Comment by traviscross** [comment]
@rustbot labels -A-edition-2027 +A-edition-2024

Based on the fact that it seems #124482 is likely to land in time, let's retarget this for Rust 2024 for now.

**Comment by traviscross** [comment]
@rustbot labels +I-style-nominated

Let's nominate to discuss this for visibility on the style side.  One style-related question here would be whether we want `rustfmt` to have an opinion about whether items within an `unsafe` extern block should be explicitly prefixed with `unsafe` if not otherwise qualified.

**Comment by ehuss** [comment]
Edition docs are up at https://github.com/rust-lang/edition-guide/pull/309.

**Comment by obi1kenobi** [comment]
Would it be possible to add docs that explicitly address what the difference (if any) is between `unsafe extern fn example() { ... }` and `unsafe extern { fn example() { ... } }`?

This is motivated by a conversation with @GuillaumeGomez [on Twitter](https://twitter.com/imperioworld_/status/1804905532089663768), and by the fact that after ~20min of digging through docs, I'm still not confident I can correctly answer that question. I'm worried this might be a possible point of confusion for others, as well as a potential source of SemVer hazards that `cargo-semver-checks` may want to screen for.

**Comment by ehuss** [comment]
`unsafe extern { fn example() { ... } }` isn't valid Rust (extern block functions don't have bodies). Was that part of the confusion?

**Comment by traviscross** [comment]
See also this section of the Reference:

https://doc.rust-lang.org/nightly/reference/items/functions.html#extern-function-qualifier

The change here -- "unsafe extern *blocks*" -- applies only to extern *blocks*.  It doesn't change anything about the extern function qualifier.

**Comment by obi1kenobi** [comment]
> `unsafe extern { fn example() { ... } }` isn't valid Rust (extern block functions don't have bodies). Was that part of the confusion?

Ah sorry, that was just me being sloppy in transcribing from the Twitter post. My confusion is about the difference between _functions_ being marked `extern` and `extern` _blocks_ containing functions.

> See also this section of the Reference:
> 
> https://doc.rust-lang.org/nightly/reference/items/functions.html#extern-function-qualifier
> 
> The change here -- "unsafe extern _blocks_" -- applies only to extern _blocks_. It doesn't change anything about the extern function qualifier.

Having read that section of the Reference, I still don't think it clearly addresses my question. I still don't feel confident I'd know when I'd use which one, nor that I could get 100% of the cases where switching from one to the other might be a breaking change.

Perhaps you feel that `unsafe extern` blocks is orthogonal to my confusion about these two Rust features, and I should open a separate issue about that. I'm on the fence about it, so I'm happy to follow your advice on that either way.

**Comment by ehuss** [comment]
It's probably best to open a new issue or Zulip thread, since this is mostly unrelated to this tracking issue.

**Comment by traviscross** [comment]
@rustbot labels -S-tracking-ready-to-stabilize +S-tracking-ready-for-edition

With the merge of #127921, this item is now **ready** for Rust 2024.

Thanks to @spastorino for pushing this important work to completion.
