### ISSUE TITLE
Tracking Issue for RFC 3606: Drop temporaries in tail expressions before local variables

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123739]
This is a tracking issue for the RFC 3606: Drop temporaries in tail expressions before local variables

- https://github.com/rust-lang/rfcs/pull/3606

The feature gate for the issue is `#![feature(shorter_tail_lifetimes)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Accept RFC: https://github.com/rust-lang/rfcs/pull/3606
- [x] Implement under feature flag with Rust 2024 behavior.
  - https://github.com/rust-lang/rust/pull/125293
  - https://github.com/rust-lang/rust/pull/129627
- [x] Crater run(s) to collect data for migration lints.
  - https://github.com/rust-lang/rust/pull/129604
  - https://github.com/rust-lang/rust/pull/129607
- [x] Implement migration lints.
  - https://github.com/rust-lang/rust-clippy/pull/13175
  - https://github.com/rust-lang/rust/pull/128662
- [x] Decide to stabilize.
  - https://github.com/rust-lang/rust/issues/131445
- [x] Stabilize in nightly Rust 2024.
  - https://github.com/rust-lang/rust/pull/131983
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- [x] Add documentation to the [reference][].
    - https://github.com/rust-lang/reference/pull/1592
    - See the [instructions][reference-instructions].
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/318
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [x] How uncommon are the situations where this change could affect existing code?
- [x] How advanced should the edition lint and migration be?
- [x] Can we make sure a lint catches the cases with unsafe code that could result in undefined behaviour?
- [x] Do we want to `warn-by-default` about these cases in older editions, or only warn when upgrading to Rust 2024?
  - https://github.com/rust-lang/rust/pull/128662#discussion_r1717408324

### Related

- https://github.com/rust-lang/rust-clippy/pull/13175
- https://github.com/rust-lang/rust/pull/128662

cc @nikomatsakis @m-ou-se

**Comment by dingxiangfei2009** [comment]
@traviscross One quick question.
> Add documentation to the [dev guide](https://github.com/rust-lang/rustc-dev-guide).

Do we need this action item?

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition

On the edition side, we've reviewed this item, and it's now **ready** for Rust 2024.

Huge thanks to @dingxiangfei2009 for his great work on pushing this item forward and getting it done.
