### ISSUE TITLE
Tracking Issue for RFC 3550: New range types

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123741]
This is a tracking issue for the RFC 3550: New range types

- https://github.com/rust-lang/rfcs/pull/3550

The feature gate for the issue is `#![feature(new_range)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC.
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide]).
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide]).
- [ ] Ensure ready for release of Rust 2024.

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- The set of inherent methods copied from `Iterator` present on the new range types
- The exact module paths and type names
  + `std::ops::range::` is long and heavily nested, perhaps `std::range::` would be better?
  + `IterRange`, `IterRangeInclusive` or just `Iter`, `IterInclusive`?
- Should other range-related items (like `RangeBounds`) also be moved under the `range` module?
- Should `RangeFrom` even implement `IntoIterator`, or should it require an explicit `.iter()` call? Using it as an iterator [can be a footgun](https://github.com/rust-lang/libs-team/issues/304), usually people want `start..=MAX` instead. Also, it is inconsistent with `RangeTo`, which doesn't implement `IntoIterator` either.
- Should there be a way to get an iterator that modifies the range in place, rather than taking the range by value? That would allow things like `range.by_ref().next()`.
- Should there be an infallible conversion from legacy to new `RangeInclusive`?
- Will the migration cost make this feasible for either Rust 2024 or Rust 2027?

### Implementation history

TODO.

**Comment by orlp** [comment]
To see which iterator methods we may want to add to the new ranges, I did an informal search on
Github using the following query:

    language:rust NOT is:fork /\W\s*\(\s*\w*\s*\.\.=?\s*\w*\s*\)\s*.\s*method\s*\(/

I matched on anything that looks like `( <> .. <> )` or `( <> ..= <> )` that is not immediately
preceded by some identifier character, to avoid matching things like `vec.drain(..).map(_)`.

Example for `map`: [search](https://github.com/search?type=code&q=language%3Arust+NOT+is%3Afork+%2F%5CW%5Cs*%5C%28%5Cs*%5Cw*%5Cs*%5C.%5C.%3D%3F%5Cs*%5Cw*%5Cs*%5C%29%5Cs*.%5Cs*map%5Cs*%5C%28%2F).

This isn't perfect but captures a rough amount of usage. Just looking by the number of matches:

 - `map`: 65.8k
 - `rev`: 23.2k
 - `collect`: 9.9k
 - `for_each`: 8.5k
 - `step_by`: 8.3k
 - `filter`: 8.2k
 - `flat_map`: 4.2k
 - `fold`: 3.5k
 - `zip`: 3.4k
 - `filter_map`: 1.6k
 - `find`:  1.5k
 - `chain`: 1.4k
 - `take_while`: 1.1k
 - `all`: 1.1k
 - `cycle`: 0.7k
 - `enumerate`: 0.6k
 - `scan`: 0.4k
 - `product`: 0.4k
 - `find_map`: 0.3k
 - `any`: 0.3k
 - `sum`: 0.2k
 - `take`: 0.2k
 - `skip`: 0.1k
 - `try_*`: 0.1k
 - `min*`: 0.1k
 - `max*`: 0.1k
 - `map_while`: 0.1k
 - `position`: 0.1k
 - `skip_while`: 0.1k
 - `count`: 0.1k
 - `reduce`: 0.1k
 - `nth`: 0.1k
 - `unzip`: 0

**Comment by pitaj** [comment]
Any reason you left out `step_by` from your final list?

**Comment by orlp** [comment]
@pitaj Yes, clerical error. I fixed it.

**Comment by programmerjake** [comment]
another common method that was omitted: `len()` (idk how many instances since github gave an error when I tried the search)

**Comment by orlp** [comment]
@programmerjake There is no `len()` on `Iterator`.

**Comment by programmerjake** [comment]
> @programmerjake There is no `len()` on `Iterator`.

there is on `ExactSizeIterator`: https://doc.rust-lang.org/std/ops/struct.Range.html#impl-ExactSizeIterator-for-Range%3Ci8%3E

**Comment by orlp** [comment]
Right. I think honestly `len` probably makes sense regardless of whether an iterator implements it and/or how many people currently are calling it.

**Comment by pitaj** [comment]
I'd rather we have a better solution for `len` than `ExactSizeIterator` since, with the proposed API, even `Range<u32>` and `RangeInclusive<i16>` don't implement it.

**Comment by orlp** [comment]
Ugh I forgot, there's still the problem that `len() -> usize` doesn't work on ranges larger than usize, nor the `0..=usize::MAX` range for `usize` itself.

**Comment by traviscross** [comment]
Let's continue that discussion about which methods to add in a separate issue [here](https://github.com/rust-lang/rust/issues/125589) rather than on the tracking issue.

**Comment by traviscross** [comment]
@rustbot labels -A-edition-2024 +A-maybe-future-edition -S-tracking-at-risk

This is, unfortunately, not likely to have all the pieces in place in time to ship with the Rust 2024 edition, so we're going to drop the label.

Thanks to all those who have been working on this, and we hope to see this ship in a future edition.

**Comment by GrigorenkoPV** [comment]
> This is, unfortunately, not likely to have all the pieces in place in time to ship with the Rust 2024 edition, so we're going to drop the label.

What things are missing so far?

**Comment by traviscross** [comment]
> What things are missing so far?

See the issue description [above](https://github.com/rust-lang/rust/issues/123741#issue-2236353974).  We need to check off all of those boxes in order to land this in any edition.
