### ISSUE TITLE
Tracking Issue for Rust 2024: Cargo remove implicit features

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123750]
This is a tracking issue for the Rust 2024-relevant parts of:

- https://github.com/rust-lang/rfcs/pull/3491
- https://github.com/rust-lang/cargo/issues/12826

Most things should go in the Cargo tracking issue  This issue is for tracking readiness for the Rust 2024 edition.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024.
- [x] Implement migration lints.
    - https://github.com/rust-lang/cargo/pull/13778
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- N/A: Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
- [x] Add documentation to the [edition guide][].
  - https://github.com/rust-lang/edition-guide/pull/301
- [ ] Update documentation to the cargo guide.
  - https://github.com/rust-lang/cargo/issues/14011
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

## Related

- https://github.com/rust-lang/cargo/issues/14010
- https://github.com/rust-lang/cargo/issues/14015
- https://github.com/rust-lang/cargo/issues/14016

cc @rust-lang/cargo @epage @Muscraft

**Comment by ehuss** [comment]
Note: This is at risk for not being included in the edition due to issues with the implementation (https://github.com/rust-lang/cargo/issues/14016 particularly).

**Comment by ehuss** [comment]
The cargo team has decided to drop this from the 2024 edition. There are some implementation issues, and we feel that there is just too much risk trying to resolve it at such a late date. Further status updates will happen on https://github.com/rust-lang/cargo/issues/12826.
