### ISSUE TITLE
Tracking Issue for Rust 2024: Cargo deprecations

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123754]
This is a tracking issue for the Rust 2024-relevant parts of:

- https://github.com/rust-lang/cargo/issues/13629

This issue is for tracking readiness for the Rust 2024 edition.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Propose dispositions for different deprecations
- [x] Get team sign off
- [x] Remove `[project]` from 2024 with migration (rust-lang/cargo#13747)
- [x] Remove `_` field alternatives from 2024 with migration (rust-lang/cargo#13804)
  - [x] Update playground (rust-lang/rust-playground#1056)
- [x] Remove useless `default-features` from inherited dependencies in 2024 with migration (rust-lang/cargo#13839)
- [x] Add documentation to the [edition guide][].
  - https://github.com/rust-lang/edition-guide/pull/301
- [ ] Add documentation to the cargo guide.
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

cc @rust-lang/cargo @epage

**Comment by epage** [comment]
Started a discussion for reviewing the dispositions on the deprecations at https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Deprecated.20cargo.20functionality

**Comment by epage** [comment]
Tracking issue is updated with the final list of what we'll be doing for this.
