### ISSUE TITLE
Tracking Issue for Rust 2024: Make `!` fall back to `!`

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123748]
This is a tracking issue for the change to make fallback fall back from `!` to `!` (rather than to `()`) in Rust 2024.  This is part of a plan that leads to eventually stabilizing the never (`!`) type.

### What this change means

This change means that [`!`](https://doc.rust-lang.org/std/primitive.never.html) does not spontaneously decay to [`()`](https://doc.rust-lang.org/std/primitive.unit.html). For example, consider this code:

```rust
fn print_return_type<R>(_: fn() -> R) {
    println!("`{}`", std::any::type_name::<R>());
}

print_return_type(|| todo!()); // before this change: prints `()`
                               // after this change: prints `!`
```

`todo!()` "returns" `!`, but before this change this `!` decayed to `()` when being returned from the closure. In general, this can happen at any coercion site, if the type is not set by something else.

If your code is broken with errors like `` `!: Trait` is not satisfied``, then you need to make sure the type is specified explicitly. For example:

```rust
fn create_zst<T: From<()>>() -> T {
    ().into()
}

if condition {
    create_zst()
} else {
    return
};
```

Before this change `!` from `return` decays to `()`, meaning that `create_zst` will also return `()`, and since `()` implements `From<()>` this was fine. _With_ this change however, `!` from `return` keeps being `!` and inference makes `create_zst` also return `!`, however `!` does not implement `From<()>` causing a compilation error.

The easiest fix is to specify the type explicitly:
```rust
if condition {
    create_zst::<()>()
} else {
    return
};
```

However, this can also be a sign that you don't care what the type is, and maybe the better solution is to refactor the code.

Also note that this "create something or return" pattern can also be caused by `?` with code like this:
```rust
deserialize(input)?;
```
Because `deserialize`'s output type is not bound to be anything, it gets inferred from `?`'s desugaring that includes a `return`. (there is a separate initiative to stop `?` from affecting inference like this: https://github.com/rust-lang/rust/pull/122412)

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024.
    - https://github.com/rust-lang/rust/pull/123508
- [x] Add migration lints.
    - [x]  Add a lint against fallback affecting `unsafe` functions.
        - [Discussion](https://hackmd.io/92bYs_v4QjWwOTVedK1u5w#What-does-it-mean-to-pass-a-type-to-an-unsafe-function).
        - https://github.com/rust-lang/rust/pull/123939
        - https://github.com/rust-lang/rust/pull/125282
    - N/A: Add a lint against fallback affecting non-diverging variables in weird ways / `?` guiding inference.
        - [Discussion](https://hackmd.io/92bYs_v4QjWwOTVedK1u5w#The-deserialize-pattern-and--interactions).
        - [Reason for N/A](https://github.com/rust-lang/rust/issues/123748#issuecomment-2117623520).
    - [x] Add a lint against fallback to unit being required for code to compile.
        - [Discussion](https://hackmd.io/92bYs_v4QjWwOTVedK1u5w#Add-a-future-incompat-lint-for-somemost-of-the-code-that-will-be-broken-by-fallback-to-).
        - https://github.com/rust-lang/rust/pull/125289
- [x] Add documentation to the standard library.
    - https://github.com/rust-lang/rust/pull/124419
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- N/A: Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/310
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [x] Decide whether to make the #123939 lint (against fallback affecting a generic that is passed to an `unsafe` function) `deny-by-default` or a hard error in Rust 2024.
   - https://github.com/rust-lang/rust/pull/126881

### Related

- https://github.com/rust-lang/rust/pull/122955
- https://github.com/rust-lang/rust/pull/123482
- https://github.com/rust-lang/rust/pull/123508
- https://github.com/rust-lang/rust/pull/123571
- https://github.com/rust-lang/rust/pull/123939
- https://github.com/rust-lang/rust/pull/124419
- https://github.com/rust-lang/rust/pull/125282
- https://github.com/rust-lang/rust/pull/125289
- https://github.com/rust-lang/rust/pull/126367
- https://github.com/rust-lang/rust/issues/126693
- https://github.com/rust-lang/rust/pull/126881
- https://github.com/rust-lang/edition-guide/pull/310

**Comment by WaffleLapkin** [comment]
> Add a lint against fallback affecting non-diverging variables in weird ways / ? guiding inference. 

It turned out that this is actually tricky/impossible to implement, because we can loose the relationships between inference variables by unifying them:
```rust
// easy to lint
// coercion graph edges: [?1t -> ?3t, ?2t -> ?3t]
match true {
    false => return /* ?1t */,
    true => Default::default() /* ?2t */,
} /* ?3t */;

// impossible to lint
// coercion graph edges: [?2t -> ?1t]
match true {
    true => Default::default() /* ?1t */,
    false => return /* ?2t */,
} /* ?1t */;
```

Even though these examples are very similar, they have enough of a difference in the coercion graph, that we can't lint them both reliably. 

I talked with Niko at RustNL and we agreed that given these circumstances this lint can be omitted.

**Comment by joshlf** [comment]
zerocopy ran into a potentially sharp edge with the [`never_type_fallback_flowing_into_unsafe`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/builtin/static.NEVER_TYPE_FALLBACK_FLOWING_INTO_UNSAFE.html) lint today. Not sure yet whether this is actually problematic, but it's at least worth letting folks know about. The docs say:

> Instead of depending on the fallback, you should specify the type explicitly

We ran into this issue when [updating to the latest nightly](https://github.com/google/zerocopy/pull/1338). [Here's the error message](https://github.com/google/zerocopy/pull/1338/files#adiff-5825b1b5e3ba149bbe3e3d6a11475afc26cddfdb9a2bff655562a6e71705b871):

```text
warning: never type fallback affects this call to an `unsafe` function
  --> tests/ui-nightly/transmute-mut-src-dst-not-references.rs:17:44
   |
17 | const SRC_DST_NOT_REFERENCES: &mut usize = transmute_mut!(0usize);
   |                                            ^^^^^^^^^^^^^^^^^^^^^^
   |
   = warning: this will change its meaning in a future release!
   = note: for more information, see issue #123748 <https://github.com/rust-lang/rust/issues/123748>
   = help: specify the type explicitly
   = note: `#[warn(never_type_fallback_flowing_into_unsafe)]` on by default
   = note: this warning originates in the macro `$crate::assert_size_eq` which comes from the expansion of the macro `transmute_mut` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Here's the [offending macro](https://github.com/google/zerocopy/blob/419d89e978e1ad4097f0950eec0eaa9616ee1f74/src/macro_util.rs#L337-L360):

```rust
/// Do `t` and `u` have the same size?  If not, this macro produces a compile
/// error. It must be invoked in a dead codepath. This is used in
/// `transmute_ref!` and `transmute_mut!`.
#[doc(hidden)] // `#[macro_export]` bypasses this module's `#[doc(hidden)]`.
#[macro_export]
macro_rules! assert_size_eq {
    ($t:ident, $u:ident) => {{
        // The comments here should be read in the context of this macro's
        // invocations in `transmute_ref!` and `transmute_mut!`.
        if false {
            // SAFETY: This code is never run.
            $u = unsafe {
                // Clippy:
                // - It's okay to transmute a type to itself.
                // - We can't annotate the types; this macro is designed to
                //   infer the types from the calling context.
                #[allow(clippy::useless_transmute, clippy::missing_transmute_annotations)]
                $crate::macro_util::core_reexport::mem::transmute($t)
            };
        } else {
            loop {}
        }
    }};
}
```

Note that `$t` and `$u` are values, not types. This macro is called from [`transmute_mut!`](https://github.com/google/zerocopy/blob/419d89e978e1ad4097f0950eec0eaa9616ee1f74/src/lib.rs#L4580), which is simply invoked as `transmute_mut!(<expr>)`, and is structured so that Rust will correctly infer the source and destination types from the surrounding context. The punchline is: **there's no way for us to name the correct type as suggested by the lint documentation.**

I *believe* that this lint isn't actually an issue, and we could soundly `allow` it. In particular, this particular test case tests an intentionally-invalid invocation of the macro, which presumably causes type inference to not have as much information as it normally would, which in turn causes the fallback logic to be reached. Note that the warning is *not* generated in our various success tests.

However, I will admit to being spooked by this since it's new to me and I haven't spent the time to really wrap my head around it to convince myself that it's definitely fine. I might instead just rewrite that macro. In particular, it's always called from dead code, but has the `if false { ... } else { loop {} }` structure so that the macro itself doesn't have to be `unsafe` to call. I might just give up on that aspiration and rewrite it so that what is currently the body of `if false { ... }` becomes the entire macro, making it `unsafe` to call:

```rust
/// Do `t` and `u` have the same size?  If not, this macro produces a compile
/// error. It must be invoked in a dead codepath. This is used in
/// `transmute_ref!` and `transmute_mut!`.
///
/// # Safety
///
/// The code generated by this macro must never be executed at runtime.
#[doc(hidden)] // `#[macro_export]` bypasses this module's `#[doc(hidden)]`.
#[macro_export]
macro_rules! assert_size_eq {
    ($t:ident, $u:ident) => {{
        // Clippy:
        // - It's okay to transmute a type to itself.
        // - We can't annotate the types; this macro is designed to
        //   infer the types from the calling context.
        #[allow(clippy::useless_transmute, clippy::missing_transmute_annotations)]
        $crate::macro_util::core_reexport::mem::transmute($t)
    }};
}
```

**Comment by joshlf** [comment]
Hmmm, confusingly the "remove the `loop {}`" approach didn't actually work - note that the lint is still triggered in https://github.com/google/zerocopy/pull/1339

**Comment by WaffleLapkin** [comment]
@joshlf note that this only happens when there is an error already, so I don't think this is a problem.

The reason warning is emitted is that compiler can't infer type of `e` (it knows it's `&mut {something}`, but not what `{something}` is; this is only the case when you assign a non-reference to `e`, which causes a type error). Then `e` gets unified with a diverging variable and ultimately gets passed to `transmute`. I believe the lint is correct. See [[code I copied]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=2e35311bda9aa789393f134cd5ac5f3e) and, more importantly, [[my minimization with explanations]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cf746ccc88f827b65a0e470e9c1a8650).

**Comment by joshlf** [comment]
> @joshlf note that this only happens when there is an error already, so I don't think this is a problem.
> 
> The reason warning is emitted is that compiler can't infer type of `e` (it knows it's `&mut {something}`, but not what `{something}` is; this is only the case when you assign a non-reference to `e`, which causes a type error). Then `e` gets unified with a diverging variable and ultimately gets passed to `transmute`. I believe the lint is correct. See [[code I copied]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=2e35311bda9aa789393f134cd5ac5f3e) and, more importantly, [[my minimization with explanations]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cf746ccc88f827b65a0e470e9c1a8650).

Okay that makes sense, thanks for investigating!

**Comment by i18n-now** [comment]
I use rustc 1.81.0-nightly (f1586001a 2024-06-13)

why this function has warn 
```
warning: this function depends on never type fallback being `()`
  --> /root/i18n/srv/rust/lib/user/src/lib.rs:77:3
   |
77 | /   pub async fn uid_score<C: SortedSetsInterface + Sync>(
78 | |     &self,
79 | |     p: &C,
80 | |     uid_bin: &[u8],
81 | |     time: u64,
82 | |     sign_in: bool,
83 | |   ) -> RedisResult<()> {
   | |______________________^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #123748 <https://github.com/rust-lang/rust/issues/123748>
   = help: specify the types explicitly
warning: this function depends on never type fallback being `()`
```
<img width="1728" alt="image" src="https://github.com/rust-lang/rust/assets/145643935/0a2d9ad0-058f-4289-9a1c-258f24fde069">


```
impl ClientUser {
  pub fn bin(&self) -> Box<[u8]> {
    u64_bin(self.id)
  }

  pub async fn uid_score<C: SortedSetsInterface + Sync>(
    &self,
    p: &C,
    uid_bin: &[u8],
    time: u64,
    sign_in: bool,
  ) -> RedisResult<()> {
    let bin = &self.bin()[..];
    let score = if sign_in { time as _ } else { -(time as f64) };
    p.zadd(client_uid(bin), None, None, false, false, (score, uid_bin))
      .await?;
    Ok(())
  }
}
```

**Comment by nihohit** [comment]
I see similar errors -

```rs
pub async fn subscribe(&mut self, channel_name: impl ToRedisArgs) -> RedisResult<()> {
        if self.protocol == ProtocolVersion::RESP2 {
            return Err(RedisError::from((
                crate::ErrorKind::InvalidClientConfig,
                "RESP3 is required for this command",
            )));
        }
        let mut cmd = cmd("SUBSCRIBE");
        cmd.arg(channel_name);
        cmd.query_async(self).await?;
        Ok(())
    }
```

The current check seems to mistake some `()` with `!`, unless I'm missing a hidden `!` in the code.

**Comment by Skgland** [comment]
Might be the `return` in the `?` de-sugaring, as return would be of type `!`.

**Comment by udoprog** [comment]
Hi!

I'm getting [a ton of false positives](https://github.com/rune-rs/rune/actions/runs/9516245427/job/26232235561) on nightly, I've reduced it to this interaction between a generic and a macro invocation:

```rust
pub trait Trait {}

impl Trait for () {}

pub fn run<T>() -> Result<T, ()>
where
    T: Trait,
{
    Err(())
}

macro_rules! call {
    () => {
        match run() {
            Ok(output) => output,
            Err(..) => {
                panic!("Panik");
            }
        }
    };
}

fn main() {
    call!();
}
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=58d5a3bc1b52465a332924b8422bc5e8)

**Comment by Skgland** [comment]
A macro isn't necessary 

```rust
pub trait Trait {}

impl Trait for () {}

pub fn run<T>() -> Result<T, ()>
where
    T: Trait,
{
    Err(())
}

fn main() {
    match run() {
        Ok(output) => output,
        Err(_) => {
            return;
        }
    };
}
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5e24a8094682d9c7b3066ed0f4ad6d5c)

**Comment by Skgland** [comment]
The examples by @udoprog and me actually fail to inferred the type argument of `run` when run in the 2024 edition on nightly, so these might not actually be false positives of the lint.

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=15c5a17cc32b166252ec6f4c5d1e0dd5)

**Comment by WaffleLapkin** [comment]
I believe all of the examples mentioned here are correct warnings, @Skgland is right.

- @i18n-now hard to guess without the code, but I assume `zadd` returns a generic which is bounded by a trait not implemented for `!` (see below for why there is `!`)
- @nihohit `query_async` returns `Result<T, _>`, where `T: FromRedisValue`, `!` does not implement `FromRedisValue` (again see below)
- @udoprog similarly to the above cases, `run` returns a generic, and `!` does not implement the trait needed

In all of those cases "old" inference rules for `!` coerce it to `()`, so the generic function infers `()` and compiles; whereas with the "new" inference rules we keep `!`, which will cause a compilation error. `!` is coming either from `return`, or from `return` in `?`'s desugaring. See an explanation here: https://github.com/rust-lang/rust/issues/51125#issuecomment-1991733203.

The fix is to specify the `()` type explicitly. I would personally probably do it with `() =` (i.e. `() = cmd.query_async(self).await?;`, etc).

Also, please don't discuss these issues here, it is quite hard to track, and respond, to problems reported in a tracking issue. **Please report problems with the lints or 2024 edition problems in new issues** (if you tag them with https://github.com/rust-lang/rust/labels/F-never_type via `@rustbot label +F-never_type` I'll get notified).

**Comment by traviscross** [comment]
This item is now **ready** for Rust 2024.

Huge thanks to @WaffleLapkin for pushing forward on this important work.

**Comment by julianskartor** [comment]
Hi there! I wonder what opinion people have on [this issue in the redis crate](https://github.com/redis-rs/redis-rs/issues/1228). With this change, it seems we will unfortunately have to set explicit types for void functions like:

```diff
- connection.set("test", "test_data")?;
+ let _: () = connection.set("test", "test_data")?;
 ```

**Comment by traviscross** [comment]
Hi @julianskartor: Thanks for letting us know about that discussion.  I'll reply over there, as tracking issues are not a good place to have these discussions.
