### ISSUE TITLE
Tracking Issue for Rust 2024: Make `unsafe_op_in_unsafe_fn` warn-by-default

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123916]
This is a tracking issue for making `unsafe_op_in_unsafe_fn` warn-by-default in Rust 2024 per:

- https://github.com/rust-lang/rust/issues/120535
- https://github.com/rust-lang/rust/issues/71668#issuecomment-1189396860

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024.
  - https://github.com/rust-lang/rust/pull/112038
- [x] Implement migration lints.
  - https://github.com/rust-lang/rust/issues/119823
- [x] Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
    - (Unneeded)
- [x] Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
    - (The reference does not list lints; however, it is fully documented in the [rustc book](https://doc.rust-lang.org/nightly/rustc/lints/listing/allowed-by-default.html#unsafe-op-in-unsafe-fn).)
- [x] Add formatting for new syntax to the [style guide][].
    - See the [nightly style procedure][].
    - (Unneeded; there is no new syntax.)
- [x] Add documentation to the [edition guide][].
    - (Done: https://github.com/rust-lang/edition-guide/blob/master/src/rust-2024/unsafe-op-in-unsafe-fn.md)
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Related

- https://github.com/rust-lang/rust/issues/71668
- https://github.com/rust-lang/rust/issues/120535

### Implementation history

- https://github.com/rust-lang/rust/pull/112038
- https://github.com/rust-lang/rust/issues/119823
- https://github.com/rust-lang/cargo/pull/13728

cc @tmandry

**Comment by asquared31415** [comment]
Should this issue be mentioned here? https://github.com/rust-lang/rust/issues/123304

**Comment by traviscross** [comment]
We discussed this in our edition call today, and this item looks *entirely* ready for Rust 2024.

Huge thanks to @tmandry for making that happen.

**Comment by ehuss** [comment]
Note: A crater run for this was done in https://github.com/rust-lang/rust/pull/122960, and identified #13728 as an issue, which is fixed via a change in cargo. Otherwise it went well. 🎉

**Comment by tmandry** [comment]
Woohoo, the first edition change of 2024 is ready!

A big thanks to @Nemo157, @asquared31415, and @weihanglo for contributing the implementation and bug fixes. And thanks for @RalfJung for the RFC.
