### ISSUE TITLE
Tracking Issue for Rust 2024: Reserve `gen` keyword

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123904]
This is a tracking issue for reserving the `gen` keyword in Rust 2024 according to:

- https://github.com/rust-lang/rfcs/pull/3513

The feature gate for the issue is `#![feature(gen_blocks)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Reserve the `gen` keyword in nightly Rust 2024.
    - https://github.com/rust-lang/rust/pull/116447
- [x] Implement migration lints.
    - https://github.com/rust-lang/rust/pull/123680
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- [x] Add documentation to the [reference][].
    - https://github.com/rust-lang/reference/pull/1501
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/300
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [x] Whether we should use some keyword other than `gen`.
    - https://github.com/rust-lang/rust/issues/123731
- [x] Whether we should reserve `gen` as a full keyword or as a contextual one.

### Related

- https://github.com/rust-lang/rust/issues/117078

### Implementation history

- https://github.com/rust-lang/rust/pull/116447
- https://github.com/rust-lang/rust/issues/124862

cc @oli-obk @compiler-errors

**Comment by oli-obk** [comment]
Does the `gen_blocks` feature need to be stabilized for the 2024? or is it fine to just stabilize the syntax in the parser?

**Comment by jhpratt** [comment]
Minor bug in the lint: #124862

**Comment by zachgrayio** [comment]
what will it take to support this in rust-analyzer?

**Comment by ehuss** [comment]
Results from the crater run showed a few limitations of the migration lint, which I don't think there is much we can do about. The following is a summary:

attribute macro issues:
```rust
use thiserror::Error;
#[derive(Error, Debug)]
pub enum Error {
    #[error("it is {gen}")]
    A{gen: i32}
}
```

`sn_consensus@3.5.2`
`reductionml-core@0.1.0 (via schemars macro)`
`hermit-toolkit-hmip20@0.1.0 (via schemars macro)`
`hermit-toolkit-hmip721@0.1.1 (via schemars macro)`
`hermit-toolkit-permit@0.1.0 (via schemars macro)`
`hermit-toolkit-utils@0.1.0 (via schemars macro)`
`hermit_toolkit_hmip21@0.1.5 (via schemars macro)`
https://github.com/mahamzaidi/secret-marketplace (via schemars macro)
https://github.com/kubecfg/kubit (via schemars macro)
https://github.com/hatuank97lhp/ptrans2 (via schemars macro)
https://github.com/chinhnotional/custom-snip721 (via schemars macro)

proc-macro got confused via quote!:
```rust
let gen = 123;
quote!(let a = #gen);
```

`trait-gen-0.3.2`
`llml_derive_crate@0.1.0`

`build.rs` generated code:
`boring-sys@4.6.0`
`bssl-cmake-sys@0.1.2405130`
`switchtec-user-sys`
`wolfssl-sys@1.0.0`

Pulled via `include!` which isn't fixed:
`zcash_script@0.1.16`

**Comment by traviscross** [comment]
We reviewed this in the edition call today.  This item is **ready** for Rust 2024.  It's implemented; the automatic migration lints have landed; we've tested those with crater, and the item is documented in the reference and in the edition guide.

Thanks to @oli-obk and to @compiler-errors for pushing this forward.
