### ISSUE TITLE
Tracking Issue for Rust 2024: Rescope temporary lifetimes with respect to `else`

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#124085]
This is a tracking issue for shortening the scope of temporary lifetimes in `if-let` blocks to end before `else`.  E.g.:

```rust
if let Some(x) = ref_cell.write().some_method_that_returns_option() {
} else {
    // question is whether the `ref_cell` is still write-locked here;
    // currently, it is, but it wouldn't be under this change
}
```

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement with a feature gate.
    - https://github.com/rust-lang/rust/pull/107251
- [x] Do a crater run to analyze impact.
    - https://github.com/rust-lang/rust/pull/125151
    - https://github.com/rust-lang/rust/pull/129466
      - https://github.com/rust-lang/cargo/pull/14447
- [x] Decide to stabilize in Rust 2024.
    - https://github.com/rust-lang/rust/issues/131154
- [x] Stabilize in nightly Rust 2024.
    - https://github.com/rust-lang/rust/pull/131984
- [x] Implement migration lints.
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- [x] Add documentation to the [reference][].
    - https://github.com/rust-lang/reference/pull/1592
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/318
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

TODO.

### Related

- https://github.com/rust-lang/rust/issues/103107
- https://github.com/rust-lang/rust/issues/103108
- https://github.com/rust-lang/rust/issues/103248
- https://github.com/rust-lang/rust/pull/103293
- https://github.com/rust-lang/rust/issues/104843
- https://github.com/rust-lang/rust/pull/107251

### Implementation history

- https://github.com/rust-lang/rust/pull/107251
- https://github.com/rust-lang/rust/pull/125151

**Comment by dingxiangfei2009** [comment]
Update: #107251 has been repurposed for this edition change.

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition

On the edition side, we've reviewed this item, and it's now **ready** for Rust 2024.

Huge thanks to @dingxiangfei2009 for his great work on pushing this item forward and getting it done.
