### ISSUE TITLE
Tracking Issue for `macro_metavar_expr_concat`

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust#124225]
Provides a modern alternative to the `concat_idents!` macro.

### Public API

```rust

macro_rules! many_idents {
    ($a:ident, $c:ident) => {
        const ${concat($a, B, $c, D)}: i32 = 1;
    };
}

fn main() {
    many_idents!(A, C);
    assert_eq!(ABCD, 1);
}
```

### Steps / History

- [x] Implementation (https://github.com/rust-lang/rust/pull/118958)
- [ ] Final comment period
- [ ] Stabilization PR

### Unresolved Questions

* [ ] https://github.com/rust-lang/rust/pull/118958#discussion_r1435269076
* [ ] https://github.com/rust-lang/rust/pull/118958#discussion_r1520260272

### References

* https://github.com/rust-lang/rust/pull/117050

**Comment by fmease** [comment]
This still needs a [T-lang sheperd](https://lang-team.rust-lang.org/how_to/experiment.html), right?

**Comment by c410-f3r** [comment]
> This still needs a [T-lang shepherd](https://lang-team.rust-lang.org/how_to/experiment.html), right?

Unfortunately I am not familiar or aware of this procedure.

**Comment by fmease** [comment]
All language features have to go through the RFC process eventually. However, the implementation can be done before an RFC has been written by following T-lang's experimental feature process which requires a T-lang member to support — *shepherd* — the venture. Only “small” language (not compiler) “fixes” don't need to follow the RFC process, they just need a T-lang FCP.

**Comment by fmease** [comment]
T-lang, this feature is seeking a shepherd, therefore I'm nominating this for you.

**Comment by joshtriplett** [comment]
Happy to second this with my T-lang hat on.

@c410-f3r Good luck, and please reach out to #t-lang on Zulip if you have any questions. Feel free to @ me there if needed.

**Comment by c410-f3r** [comment]
Thank you @joshtriplett

**Comment by UserIsntAvailable** [comment]
Sorry if this is the wrong place to discuss this, but should `${concat}` provide its own case-conversion mechanism (just like `paste!` does), or should we instead provide a standalone `${case}` metavar expr to handle this?

If we where to follow `paste!` syntax, then it would look like:

```rust
macro_rules! many_idents {
    ($a:ident, $c:ident) => {
        const ${concat($a:upper, B, $c:lower, D)}: i32 = 1;
    };
}

fn main() {
    many_idents!(a, C);
    assert_eq!(ABcD, 1);
}
```

Or with a _future_ `${case}` metavar expr:

```rust
macro_rules! many_idents {
    ($a:ident, $c:ident) => {
        const ${concat(${case($a, upper)}, B, ${case($c, lower)}, D)}: i32 = 1;
    };
}

fn main() {
    many_idents!(a, C);
    assert_eq!(ABcD, 1);
}
```

Which I think is way too verbose, but maybe I'm just too used to `paste!` simplicity. The advantage of `${case}` over `${concat}` would be that, currently, `${concat}` requires 2 operands to be able to be used (this could technically be changed), so `${case}` would allow:

```rust
use std::ops::Add;

pub struct Wrapper<T>(T);

macro_rules! impl_op {
    ($Op:ident => $Ty:ty) => {
        impl $Op<$Ty> for Wrapper<$Ty> {
            type Output = Self;

            // alternative syntax; `:` instead of `,`.
            fn ${case($Op:snake)}(self, rhs: $Ty) -> Self::Output {
                Self(self.0.${case($Op:snake)}(rhs))
            }
        }
    };
}

impl_op!(Add => u8);
```

---

With that said, maybe there is a world where both approaches are accepted, but I think there is probably less motivation to do that?

cc @c410-f3r @joshtriplett for opinions about this.

**Comment by c410-f3r** [comment]
Well, I personally don't mind discussing potential designs in a tracking issue.

### ${case} 

The introduction of `${case}` as a new metavariable expression that can be used with or without `${concat}` looks worth pursuing and semantically correct but IFAICT, inputs currently only accept ad-hoc parameters. More specifically, `${concat}` only accepts literal identifiers and variables.

```rust
// Same problem with multiples `${concat}`s

macro_rules! foo {
    ($a:ident, $b:ident, $c:ident) => {
        let ${concat(a, ${concat(b, c)})}: () = (); // ERROR !
    }
}
```

Perhaps the evaluation of nested metaravariables expressions will become a thing someday? 

### $ident:modifier

Looks feasible in regards to a possible implementation but semantically awkward IMO. I am not aware of something similar in the macro system.

If acceptable, then it should probably be restricted to a subset of operations.

```rust
macro_rules! foo {
    ($a:ident) => {
        // Is it OK?
        let $a:upper = ();
    }
}
```

These are just my opinions. A theoretical stabilization of `${concat}` with or ***without*** case modifiers is fine to me.

**Comment by UserIsntAvailable** [comment]
> The introduction of `${case}` as a new metavariable expression that can be used with or without `${concat}` looks worth pursuing and semantically correct but IFAICT, inputs currently only accept ad-hoc parameters. More specifically, `${concat}` only accepts literal identifiers and variables.
> 
> ```rust
> // Same problem with multiples `${concat}`s
> 
> macro_rules! foo {
>     ($a:ident, $b:ident, $c:ident) => {
>         let ${concat(a, ${concat(b, c)})}: () = (); // ERROR !
>     }
> }
> ```
>
> Perhaps the evaluation of nested metaravariables expressions will become a thing someday?

Oh I wasn't aware of that limitation. I imagine that something like that would be needed down the line. I don't much about the internals of the macro codebase, so I wouldn't know if this would be hard to implement.

As a side note, I wonder if something like `${concat(a, concat(b, c)}` would be able to be made non ambiguous; I would imagine this kind of analysis would be hard to pull off, since you can't no longer look for `${}` to know that the next thing is a metavar expr identifier.

> ### $ident:modifier
> 
> Looks feasible in regards to a possible implementation but semantically awkward IMO. I am not aware of something similar in the macro system.
> 
> If acceptable, then it should probably be restricted to a subset of operations.
> 
> ```rust
> macro_rules! foo {
>     ($a:ident) => {
>         // Is it OK?
>         let $a:upper = ();
>     }
> }
> ```

Do note that if `$ident:modifier` is accepted as the final syntax, it would only work inside of `${concat}` or `${case}`, which would remove the ambiguity for `let $a:upper = ();`; identifiers can't use the `:` symbol, so `let ${case($a:upper)} = ();` is non ambiguous.

With that said, you made me realize that with this change some metavar exprs would have "special syntax" attached to them, which might not be the desired design, specially because most users would think about metavar exprs as functions rather than "fancier macros" (although accepting [this change](https://github.com/rust-lang/rust/pull/118958#discussion_r1435269076) would contradict this).

Another option would be to allow a standalone syntax `${$ident:modifier}` (without writing `case`), but I don't know if case-conversion is important enough to have its own syntax (I also don't know what other modifiers you could really add to these).
 
> These are just my opinions. A theoretical stabilization of `${concat}` with or _**without**_ case modifiers is fine to me.

This is something that can go under "Future possibilities" on the final RFC. I don't particularly think that stabilization should be blocked on this, since we can always add it later. :)

**Comment by c410-f3r** [comment]
Looks like a bug to me. I will try to investigate it in the following weeks

**Comment by tgross35** [comment]
It would be nice if there was some way to allow turning `${concat(c, $litstr)}` into `c"some string"` for constructing C string literals when a Rust string is provided. That is, a replacement for [`cstr!`](https://docs.rs/cstr/latest/cstr/). But I can't think of a good syntax here.

https://github.com/rust-lang/rust/pull/127542 adds support for literals, but the above would get turned into (invalid) identifier `csome string`.

**Comment by tgross35** [comment]
Regarding syntax, I would prefer a space-separated form like `${concat(get_ $item _mut)}`, rather than the current comma-separated `${concat(get_, $item, _mut)}`. That just makes it easier to read imo, and matches [`paste`](https://docs.rs/paste/latest/paste/).

**Comment by safinaskar** [comment]
🚀 I found a way to evaluate `concat_idents` (and `concat` and few other built-in macros) **before** evaluating other macro, which takes `concat_idents` as an argument! I. e. I found a way to evaluate `a!(concat_idents!(...))` such way, that `concat_idents` evaluates before `a`. Answer is crate https://crates.io/crates/with_builtin_macros !!! Thanks, @danielhenrymantilla ! In other words, `with_builtin_macros` is `paste`, but not only for `concat_idents`, but also for `concat` and some other macros.

And in other words, `with_builtin_macros` allows one to achieve eager evaluation of macros in limited way.

Also, `with_builtin_macros` allows one to use `concat_idents` when defining new identifier.

Also, https://crates.io/crates/with_builtin_macros allows one to use `concat_idents` in stable Rust.

```rust
// (This code was not tested, may contain typos)

fn concat_idents!(a, b) () {} // Doesn't work

with_builtin_macros::with_eager_expansions! {
  fn #{ concat_idents!(a, b) } () {} // Works! Even on stable!
}

macro_rules! this_macro_accepts_ident {
  ($a:ident) => {}
}

this_macro_accepts_ident!(concat_idents!(a, b)); // Doesn't work, because "this_macro_accepts_ident" evaluates before "concat_idents"

with_builtin_macros::with_eager_expansions! {
  this_macro_accepts_ident!(#{ concat_idents!(a, b) }); // Works! Even on stable!
}

macro_rules! this_macro_accepts_literal {
  ($a:literal) => {}
}

this_macro_accepts_literal!(concat!("a", "b")); // Doesn't work. Moreover, you cannot solve this problem using #[feature(macro_metavar_expr_concat)], because ${concat(...)} produces identifier, not string literal!!! Same applies to "paste"! "paste::paste!" deals with identifiers, not strings. So, with_builtin_macros is the only way!!!

with_builtin_macros::with_eager_expansions! {
  this_macro_accepts_literal!(#{ concat!("a", "b") }); // Works! Even on stable!
}
```

**Comment by l-Luna** [comment]
the error message `note: currently only string literals are supported` when using some `$t:ty` is confusing, since there's no string literals involved & other kinds of identifiers are supported.

it feels like `ty`s should be supported, but i guess https://github.com/rust-lang/rfcs/pull/3714 could handle that better with a field for "short name" rather than whole path?
