### ISSUE TITLE
Tracking Issue for autodiff

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#124509]
This is a tracking issue for the automatic differentiation experiment ("autodiff").

The feature gate for the issue will be `#![feature(autodiff)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.  Discussion comments will get marked as off-topic or deleted.  Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [x] Get compiler MCP approved.
    - https://github.com/rust-lang/compiler-team/issues/611
- [ ] Get lang experiment approved.
- [ ] Write an RFC.
- [ ] Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- [ ] Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
- [ ] Add formatting for new syntax to the [style guide][].
    - See the [nightly style procedure][].

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Related

- https://github.com/rust-lang/compiler-team/issues/611

### Unresolved Questions

TODO.

### Implementation history

TODO.

**Comment by traviscross** [comment]
@rustbot -I-lang-nominated

We discussed this on the lang triage call today and were happy to see this move forward as an experiment.  I'll be continuing as the liaison for this, so please let me know whenever anything is needed to keep this moving along.

**Comment by 0x00b1** [comment]
I just learned about this and would love to help. Who can I ask for some issues to work on?

**Comment by traviscross** [comment]
@0x00b1: Join Rust's [Zulip](https://forge.rust-lang.org/platforms/zulip.html), if you're not already there, then reach out on the `#wg-autodiff` channel.

**Comment by jasalper** [comment]
Hi! I've come across this project - seems super cool. 

https://rustc-dev-guide.rust-lang.org/autodiff/installation.html

This guide seems to suggest that autodiff still needs rustc to be built from source, but in the near future it will be bundled in with the compiler. Is that still accurate? And if so, do you have any estimates for when it'll be bundled? 

(And also, some estimate of how stable the api is. I've noticed from 1.87 to Tonight's nightly that the #autodiff macro has switched to autodiff_forward and autodiff_reverse (#140697). Do you expect significant future changes?)

Also, I seem to have been able to build it, and most tests are passing except these few are failing. Happy to discuss elsewhere if that'd be more convenient than GitHub issues:

```
failures:
    [codegen] tests/codegen/autodiffv2.rs
    [codegen] tests/codegen/autodiff/identical_fnc.rs
    [codegen] tests/codegen/autodiff/batched.rs
    [codegen] tests/codegen/autodiff/sret.rs
```

`Some tests failed in compiletest suite=codegen mode=codegen host=aarch64-apple-darwin target=aarch64-apple-darwin`

**Comment by sharifhsn** [comment]
I'm also interested in this project, as I am designing a nonlinear optimizer that depends on efficient autodiff for some research. I'm fine using nightly and all the instability that it entails, but it would be nice if I could use it like any other nightly API instead of building it from source.

**Comment by ZuseZ4** [comment]
Hi! This is a tracking issue, which isn't meant for technical discussion.
Can you two please open threads in the [#wg-autodiff](https://rust-lang.zulipchat.com/#narrow/channel/390790-wg-autodiff) zulip instead? Happy to answer questions there.
