### ISSUE TITLE
Fix googleability of docs

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#12466]
Googling for Rust documentation gives very inconsistent results, often to very old docs. Newbies often are led astray.

Old description:

This is a topic I haven't paid much attention to, but it's important, and I know our googlability has traditionally been very bad. I don't know at all what needs to be done off hand but it's something we should dedicate some effort to.

Nominating.

Tasks:

* [x] description and keyword meta for home page
* [ ] description and keyword meta for standalone docs (needs #16178)
* [x] description and keyword meta for crate docs
* [x] descriptive titles for standalone docs
* [ ] teach rustdoc to meta (https://github.com/rust-lang/rust/issues/16178)
* [ ] add `<link rel="canonical">` to docs (needs #16178)

**Comment by BigBoneDaddy** [comment]
@steveklabnik Steve is this something you work on during doc update or you just update doc contents and not googleabiliyt?

**Comment by brson** [comment]
Closing in favor of specific linked bugs.
