### ISSUE TITLE
Tracking Issue for Rust 2024: rustfmt trailing comment alignment

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rust#124760]
This is a tracking issue for correcting the alignment of trailing comments in rustfmt.  This is needed to support the Style Edition 2024 which is expected to be released with Rust 2024.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024.
  - https://github.com/rust-lang/rustfmt/pull/6247
- [x] Add documentation to the [edition guide][].
  - https://github.com/rust-lang/edition-guide/pull/351
- [ ] Add formatting for new syntax to the [style guide][].
    - See the [nightly style procedure][].
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Implementation history

- https://github.com/rust-lang/rustfmt/pull/6247

cc @rust-lang/rustfmt @rust-lang/style

Intended to cover https://github.com/rust-lang/rustfmt/issues/5577#issuecomment-1315302533

**Comment by traviscross** [comment]
@rustbot labels -S-tracking-needs-documentation +S-tracking-ready-for-edition

Given that this was documented (thanks @ehuss) in:

- https://github.com/rust-lang/edition-guide/pull/351

This item is now **ready** for Rust 2024.  Thanks to @calebcartwright, @ytmimi, and the rest of the rustfmt and style teams for pushing this forward.

Note that, separately from edition readiness, there may (or may not) still be more to do here in terms of documenting this in the style guide.
