### ISSUE TITLE
Tracking Issue for Rust 2024: rustfmt raw identifier sorting

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rust#124764]
This is a tracking issue for correcting the sort order of imports that include raw identifiers in rustfmt.  This is needed to support the Style Edition 2024 which is expected to be released with Rust 2024.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024.
  - https://github.com/rust-lang/rustfmt/pull/6247
- [x] Add documentation to the [edition guide][].
  - https://github.com/rust-lang/edition-guide/pull/321 
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Implementation history

- https://github.com/rust-lang/rustfmt/pull/6247

cc @rust-lang/rustfmt @rust-lang/style

Intended to cover https://github.com/rust-lang/rustfmt/issues/5577#issuecomment-1321035553

**Comment by calebcartwright** [comment]
Dropping the needs-doc label given that https://github.com/rust-lang/edition-guide/pull/321 was merged

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition -I-style-nominated

We reviewed this on the edition call.  This is now **ready** for Rust 2024.

Thanks to @calebcartwright and the rest of the rustfmt team and style team for pushing this forward.
