### ISSUE TITLE
Tracking Issue for Rust 2024: Rustdoc tests in one binary

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#124853]
This is a tracking issue for compiling all rustdoc tests in one binary.

- https://github.com/rust-lang/rust/pull/123974
- https://github.com/rust-lang/rust/issues/75341

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024.
    - https://github.com/rust-lang/rust/pull/123974
    - https://github.com/rust-lang/rust/pull/126245
- N/A Implement migration lints.
    - We just want to document the breakage in the migration guide.
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- N/A: Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/320
- [ ] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md

### Unresolved Questions

TODO.

### Related

- https://github.com/rust-lang/rust/pull/123974
- https://github.com/rust-lang/rust/pull/125798
- https://github.com/rust-lang/rust/pull/126245
- https://github.com/rust-lang/testing-devex-team/issues/5

cc @epage @GuillaumeGomez

**Comment by weihanglo** [comment]
How is this linked to T-cargo, and how can we help?

**Comment by traviscross** [comment]
@rustbot labels -T-cargo +T-rustdoc

Thanks @weihanglo.  Correcting labels.

**Comment by weihanglo** [comment]
At one second, I thought we were pushing <https://github.com/rust-lang/testing-devex-team/issues/5#issuecomment-1934496605>, which is indeed a Cargo-heavy design 😆.

(Off topic. I'll hide all of them)

**Comment by ehuss** [comment]
Posted draft of the documentation at https://github.com/rust-lang/edition-guide/pull/320

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition

We reviewed this in our edition call today.  This item is **ready for Rust 2024**.

Thanks to @GuillaumeGomez for pushing this important work forward, and thanks to all the reviewers for providing helpful feedback.

**Comment by GuillaumeGomez** [comment]
Thanks for writing the edition explanations! :D
