### ISSUE TITLE
Tracking Issue for Rust 2024: Make `std::env::{set_var, remove_var}` unsafe

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#124866]
This is a tracking issue for making `std::env::{set_var, remove_var}` unsafe to call in Rust 2024.

- https://github.com/rust-lang/rust/pull/116888#issuecomment-1852620311

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024 for `std::env::{set_var, remove_var}`.
  - https://github.com/rust-lang/rust/pull/124636
- [x] Implement migration lints for `rustc_deprecated_safe_2024`.
  - https://github.com/rust-lang/rust/pull/124636
  - https://github.com/rust-lang/rust/pull/125990
  - https://github.com/rust-lang/rust/pull/126019
 - [x] Implement in nightly Rust 2024 for `CommandExt::before_exec`.
   - https://github.com/rust-lang/rust/pull/125970
   - https://github.com/rust-lang/rust/pull/127857
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- N/A: Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/304
- [ ] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md

### Unresolved Questions

TODO.

### Related

- https://github.com/rust-lang/rust/pull/124636
- https://github.com/rust-lang/rust/issues/27970
- https://github.com/rust-lang/rust/issues/90308
- https://github.com/rust-lang/rust/pull/125925
- https://github.com/rust-lang/rust/pull/125937
- https://github.com/rust-lang/rust/pull/125970
- https://github.com/rust-lang/rust/pull/125990
- https://github.com/rust-lang/rust/pull/126019
- https://github.com/rust-lang/rust/pull/127857

### Implementation history

- https://github.com/rust-lang/rust/pull/124636

cc @tbu @Amanieu @rust-lang/libs-api

**Comment by joboet** [comment]
I'm really not a big fan of this, because `unsafe` is completely unnecessary on well-behaved platforms like Windows, which provide a good API with proper synchronization, and on the platforms where this is an issue, we could easily make the API sound by properly enforcing that `setenv` is only called on the main thread (our current behaviour is technically unspecified, see [`MT-safe env`](https://www.man7.org/linux/man-pages/man7/attributes.7.html)).

**Comment by BurntSushi** [comment]
@joboet The nooks and crannies of this issue have been discussed at length already. Your suggestion to "add a new API" to glibc/musl has been brought up before and it [isn't viable](https://github.com/rust-lang/rust/issues/27970#issuecomment-1003066633). I would suggest at least skimming through that thread, and pay special attention to richfelker's comments if you think the solution to this problem can come from libc. (He is the maintainer of musl.)

> I'm really not a big fan of this, because `unsafe` is completely unnecessary on well-behaved platforms like Windows, which provide a good API with proper synchronization

I don't think anyone is a big fan of this. The fact that Windows has a safe API for this isn't sufficient criteria for marking a platform independent API safe that is unsafe on some set of supported tier1 platforms. The answer here is to probably to publish a crate that exposes the safe Windows specific API.

**Comment by RalfJung** [comment]
> I think the best solution would be to contribute new API to glibc/musl... that behaves correctly (e.g. by copying the [GetEnvironmentVariable](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getenvironmentvariable) behaviour of copying into a user-provided buffer).

I agree. I hope someone will pursue this.

However, there was, as far as I can tell, zero progress on this in the almost 9 years (!) since https://github.com/rust-lang/rust/issues/27970 was filed. I see no reason to believe that a fix for this will materialize medium-term (let's say, ≤ 5 years). Even on a 10-year scale I am not optimistic that anything will happen. Saying we have to wait until Unixes get their APIs fixed is, at this point, basically equivalent to saying we're okay with this just not being fixed.

Given that the best solution is just unrealistic, we should pursue the second-best solution, and that's what we are doing right now. I'm very happy to finally see progress on this.

**Comment by ehuss** [comment]
It's a bit unclear to me why the migration lint was named `deprecated_safe`, since it is specific to the 2024 edition. @tbu- Would it be possible to rename it to something more specific for its purpose? Perhaps something like `deprecated_safe_2024` to mirror `keyword_idents_2024`[^1]?

[^1]: Unfortunately it looks like there is inconsistency in the naming conventions, with most lints using `rust-2021-xxxx` but keyword idents split into `keyword-idents-20xx`. I'm guessing `deprecated_safe` might follow in similar footsteps. :shrug:

**Comment by SteveLauC** [comment]
Hi, is this considered a breaking change? The patch for this is available in Rust nightly 1.80 2024-05-31, and [Nix encountered this](https://github.com/nix-rust/nix/pull/2421) even though we are using Rust 2021.

**Comment by ehuss** [comment]
@SteveLauC This should only fire in 2024. If you are encountering a problem, please open a new issue with a reproduction.

**Comment by SteveLauC** [comment]
> @SteveLauC This should only fire in 2024. If you are encountering a problem, please open a new issue with a reproduction.

Hi, thanks for your reply! [issue](https://github.com/rust-lang/rust/issues/125875) filed.

**Comment by tbu-** [comment]
> Would it be possible to rename it to something more specific for its purpose? Perhaps something like `deprecated_safe_2024` to mirror `keyword_idents_2024`?

Of course it's possible to rename the lint, if we want to do that.

> It's a bit unclear to me why the migration lint was named `deprecated_safe`, since it is specific to the 2024 edition.

My thinking was that the `deprecated_safe` mechanism might be properly extended to more editions or third-party crates in the future and didn't want to give it a too specific name. I guess a `deprecated_safe` lint group could be added containing only the `deprecated_safe_2024` lint, but I was thinking that this could also be done in the future, when we split it into multiple different lints.

**Comment by ehuss** [comment]
Yea, I think it would be best. The lint can't change after the edition is released, and it helps with documentation to make it clearer it is for the edition.

**Comment by tbu-** [comment]
Only addressing this particular sub-point:

> The lint can't change after the edition is released

Why can the lint not change after the edition? It seems to be that it could be renamed to `deprecated_safe_2024` if a lint group `deprecated_safe` containing it is created at the same time.

**Comment by ehuss** [comment]
The behavior of the lint can't change. It could be renamed, but that causes hassle with updating documentation, bug reports and older documentation no longer being accurate, etc.

**Comment by tbu-** [comment]
Created a PR: #125990.

The updated documentation, bug reports, older documentation make sense.

Why can the behavior of a lint not change? I didn't think this was part of our stability guarantees.

**Comment by workingjubilee** [comment]
> Why can the behavior of a lint not change? I didn't think this was part of our stability guarantees.

It is explicitly not.

**Comment by workingjubilee** [comment]
RFC 1122 [Underspecified language semantics](https://rust-lang.github.io/rfcs/1122-language-semver.html#underspecified-language-semantics):
> There are a number of areas where the precise language semantics are currently somewhat underspecified. Over time, we expect to be fully defining the semantics of all of these areas. This may cause some existing code – and in particular existing unsafe code – to break or become invalid. Changes of this nature should be treated as soundness changes, meaning that we should attempt to mitigate the impact and ease the transition wherever possible.
> 
> Known areas where change is expected include the following:
> - [...]
> - Lints will evolve over time (both the lints that are enabled and the precise cases that lints catch). We expect to introduce a [means to limit the effect of these changes on dependencies](https://github.com/rust-lang/rfcs/issues/1029).

For those who don't have time to reread the entire RFC, all soundness changes are considered permitted breaking changes, especially including
> - Cases where the user is able to produce Undefined Behavior (UB) purely from safe code.

It is a permitted breaking change to simply delete these functions. This change, in its entirety, is merely one of the recommended mitigation strategies.

**Comment by ehuss** [comment]
> Why can the behavior of a lint not change?

In this particular case, it's because the set of unsafe functions that need to be migrated for 2024 will be fixed once 2024 is stabilized. The lint machinery itself does not support a single lint spanning multiple editions (and that is the reason why keyword_idents was split up), so `deprecated_safe` would not be able to add new functions that would otherwise hard-error, even for 2027.

As for @workingjubilee's context about fixing soundness, there is some latitude to make fixes regarding soundness, but in this case it was decided to fix it in a non-breaking manner.

**Comment by ehuss** [comment]
Posted a draft of the docs at https://github.com/rust-lang/edition-guide/pull/304 if anyone wants to help review that.

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition

We reviewed this in our edition call today.  This item is **ready for Rust 2024**.

Thanks to @tbu- and @RalfJung for pushing forward this important work.  And thanks to the many reviewers for providing helpful feedback.

**Comment by quininer** [comment]
I think [set_current_dir](https://doc.rust-lang.org/nightly/std/env/fn.set_current_dir.html) should also be mark to unsafe, but seems to miss it?

**Comment by RalfJung** [comment]
If you know some way in which that operation is unsafe, please file an issue. But to my knowledge, `chdir` is thread-safe?

**Comment by quininer** [comment]
@RalfJung  You're right, that surprises me a bit.

My impression of this comes from https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setcurrentdirectory

> Multithreaded applications and shared library code should avoid calling the SetCurrentDirectory function due to the risk of affecting relative path calculations being performed by other threads. Conversely,

but this seems to be just condition race, not thread safety.
I can still imagine it interacting with some special case, but that's hard to attribute directly to memory safety issues.
