### ISSUE TITLE
Tracking Issue for PanicHookInfo::payload_as_str()

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#125175]
Feature gate: `#![feature(panic_payload_as_str)]`

This is a tracking issue for PanicHookInfo::payload_as_str()

### Public API

```rust
// std::panic

impl PanicHookInfo {
    pub fn payload_as_str(&self) -> Option<&str>;
}
```

Documentation: https://doc.rust-lang.org/nightly/std/panic/struct.PanicHookInfo.html#method.payload_as_str

### Steps / History

- [x] Implementation: part of #115974
- [x] Final comment period (FCP)
- [x] Stabilization PR: https://github.com/rust-lang/rust/pull/144861

### Unresolved Questions

- None yet.

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by madsmtm** [comment]
The documentation on `payload_as_str` is reproduced here:

> Returns the payload associated with the panic, if it is a string.
>
> This returns the payload if it is of type `&'static str` or `String`.
>
> A invocation of the `panic!()` macro in Rust 2021 or later will always result in a panic payload where `payload_as_str` returns `Some`.
>
> Only an invocation of [`panic_any`](https://doc.rust-lang.org/nightly/std/panic/fn.panic_any.html) (or, in Rust 2018 and earlier, `panic!(x)` where `x` is something other than a string) can result in a panic payload where `payload_as_str` returns `None`.

I'm unsure, would you say that it is written in such a way that we could allow changing it to also internally also cast e.g. `Box<str>` or `Cow<'static, str>`, or perhaps even `dyn AsRef<str>`? If not, then I think perhaps that should be changed?

**Comment by m-ou-se** [comment]
> I'm unsure, would you say that it is written in such a way that we could allow changing it to also internally also cast e.g. `Box<str>` or `Cow<'static, str>`, or perhaps even `dyn AsRef<str>`?

Yes. It says it is guaranteed to return `Some` if it contains a `&str` or `String`, not that it is guaranteed to return `None` if it is neither.
