### ISSUE TITLE
Tracking Issue for `#[global_registration]`

### ISSUE THREAD

**Issue by jdonszelmann** [rust-lang/rust#125119]
This is a tracking issue for the global registration experiment.
The feature gate for the issue is `#![feature(global_registration)]`.

Global registration has previously been discussed on [internals.rust-lang.org](https://internals.rust-lang.org/t/global-registration-a-kind-of-pre-rfc/20813/26) and a [proposal was made on the testing devex team](https://github.com/rust-lang/testing-devex-team/issues/3) with @epage . Specific syntax has not been discussed yet, which is part of what this experiment is going to figure out. Likely, a first implementation will use built-in attribute macros.

### About tracking issues

Tracking issues are used to record the overall progress of implementation. They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions. A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature. Instead, open a dedicated issue for the specific matter and add the relevant feature gate label. Discussion comments will get marked as off-topic or deleted. Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [ ] Get lang experiment approved. (@scottmcm is liaisoning me)
- [ ] Land the experimental implementation in nightly.
- [ ] Accept an RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

TODO

### Implementation history

TODO

**Comment by camsteffen** [comment]
Another use case: I think Clippy could use this to register more Symbol constants like `sym::*`.

**Comment by bjorn3** [comment]
You did have to be careful to ensure that the crate metadata encoder doesn't consider those extra symbol constants as preinterned, otherwise rustc won't be able to decode metadata generated by clippy. Also clippy uses rustc as dylib, so for clippy to use `#[global_registration]` dylibs would have to be supported.

**Comment by Indra-db** [comment]
A potential use case if this is or could be supported, is assigning meta data to a type. 

In my particular use case, assigning an id / index "static" to each type. 

Currently Rust doesn't support generic statics due to issues on windows with dylib, but this could potentially be used instead? Would global registration allow for such use case? 

See relevant discussion (before and after) here: https://discord.com/channels/273534239310479360/592856094527848449/1246014749288955945

**Comment by T-Dark0** [comment]
To elaborate a bit, as I was in that discussion:

The goal here is to generate a per-type identifier that, for FFI/stability reasons, cannot be `TypeId`. This identifier also needs to consider different instantiations of the same generic type to be different types.

The C++ way of doing this is approximately equivalent to a `OnceLock`ed local static variable inside a function of a template class, which causes the variable to be duplicated per instantiation of the template class. This doesn't work in Rust, as the local `static` will, just like all local items are, behave as if it had been written at the top scope in all except its own scope.

The idea here, from our discussion, is to ensure that `register!`, or whatever replaces it in the eventual syntax, can be called from inside a monomorphised function, and behaves more like an expression than an item, allowing it, and its "initializers" (assuming a syntax like `register!(registry, initializers)`"), to access generics from the enclosing scope much like `const {}` blocks, and performing one registration per instantiation.

**Comment by jdonszelmann** [comment]
in a way, I'm not actively developing it anymore. I wrote a blog post on why I don't believe the original way to implement it is right, and I did not just receive postitive feedback on that point of view. As I don't feel like defending my own point of view I've done a few other things around the compiler for now. Maybe, some day, I might look at it again.
