### ISSUE TITLE
Enable `f16` in assembly on platforms that support it

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#125398]
The below should work, but errors that f16 is not usable for registers:

```rust
#![feature(f16, f128)]

use core::arch::asm;

#[inline(never)]
pub fn f32_to_f16(a: f32) -> f16 {
    a as f16
}

#[inline(never)]
pub fn f32_to_f16(a: f32) -> f16 {
    let ret: f16;
    asm!(
        "fcvt    {ret:h}, {a:s}",
        a = in(vreg) a,
        ret = lateout(vreg) ret,
        options(nomem, nostack),
    );

    ret
}
```

On aarch64 the first function generates:

```asm
example::f32_to_f16::hc897184dfb47f3d6:
        fcvt    h0, s0
        ret
```

`f16` types should be supported as a vreg on aarch64 in order to reproduce that code.

---

The following other platforms also apparently have some level of instruction support, but are less well documented:

- `arm-*`, `armv7-*`, `aarch64-*`, https://developer.arm.com/documentation/den0024/a/Porting-to-A64/Data-types
- PowerPC PowerISA apparently has a half-precision format according to section 7.3.2.1 https://files.openpower.foundation/s/dAYSdGzTfW4j2r2, but I can't get LLVM to emit any instructions for it. Per others, the VSX feature on PowerISA 3.1+ has conversion support for `f16`, and the SVP64 feature (which I can't find documented anywhere) adds full hardware support
- MIPS with the MSA extension...? https://s3-eu-west-1.amazonaws.com/downloads-mips/documents/MD00868-1D-MSA64-AFP-01.12.pdf section 3.1 says "16-bit floating-point storage format is supported through conversion instructions to/from 32-bit floating-point data.", I am unsure whether its vector registers have any special support
- riscv64gc with the Q extension: https://github.com/riscv/riscv-isa-manual/blob/riscv-isa-release-2023-05-23/src/q-st-ext.adoc

Additionally, s390x supports f128, referred to as "BFP Extended Format" in https://publibfp.dhe.ibm.com/epubs/pdf/a227832c.pdf. I am not sure if this comes with any special instructions

**Comment by tgross35** [comment]
I'm adding E-Easy because a PR that just enables support for aarch64 should be pretty easy, start around https://github.com/rust-lang/rust/blob/b54dd08a84f3c07efbc2aaf63c3df219ae680a03/compiler/rustc_hir_analysis/src/check/intrinsicck.rs#L65-L66 and massage the new types in.

Sample for reference: https://rust.godbolt.org/z/8n7o4Exbf

@rustbot label +T-compiler +E-Easy +F-f16_and_f128 +A-inline-assembly

**Comment by lengrongfu** [comment]
@tgross35 I can try to submit a PR, can you give me some guidance?

**Comment by tgross35** [comment]
Hi @lengrongfu, thanks for the interest!

This should be pretty easy I think. Start by making a test in [`tests/ui/asm/`](https://github.com/rust-lang/rust/tree/003a9027927a51de770a1cf22fccade616a5f0e3/tests/ui/asm/) that contains the assembly function from my original post. Make sure this fails when you run `./x t --stage 1 path/to/your/new/test.rs`.

Then just find where the error is emitted (search the codebase for "cannot use value of type") and work backwards from that until the test passes. This will probably mean adding `F16` to `InlineAsmType` and then chasing down errors.

We will need to make sure that this works on platforms with support (e.g. aarch64) but still fails on those without it (e.g. x86). Just focus on getting aarch64 to build first.

There is a compiler help stream on Zulip https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp feel free to ask if you get stuck! Also not a bad idea to post a draft PR as soon as you have some basic work done, even if not yet passing.

**Comment by ismailarilik** [comment]
I think `E-easy` label should be removed from this issue.

**Comment by tgross35** [comment]
Fair enough - it is still pretty easy for a compiler change, but does require some background knowledge.

**Comment by heiseish** [comment]
Sorry I claimed this issue before realizing that @beetrees has pushed forward the PR for aarch64. 
@tgross35 - may I confirm the remaining work for this issue is the other platforms other than aarch64?

**Comment by tgross35** [comment]
@heiseish there are still platforms available; as far as I know, we haven't yet added support for PowerPC, Mips, or s390x. The PRs would look reasonably similar to the completed ones for x86, aarch64, and RISC-V, but you'll need to double check the specific interaction with target features.

**Comment by beetrees** [comment]
Status (by file in [compiler/rustc_target/src/asm](https://github.com/rust-lang/rust/tree/main/compiler/rustc_target/src/asm)):

- Stable inline ASM architectures:
  - [x] `aarch64`: Done in #129536.
  - [x] `arm`: Done in #126555.
  - [x] `loongarch`: Done in #142481.
  - [x] `powerpc`: Needs `f16` and `f128` (has hardware support). Done in #161135.
  - [x] `riscv`: Done in #126530.
  - [x] `s390x`: Done in #131664 and #150826.
  - [x] `x86`: Done in #126417.

- Experimental inline ASM architectures:
  - [x] `amdgpu`: Done in #149793.
  - [x] `avr`: N/A: No hardware support, not mentioned in the [AVR ABI](https://gcc.gnu.org/wiki/avr-gcc).
  - [x] `bpf`: N/A: No native support.
  - [x] `csky`: N/A: No hardware support, not mentioned in the [C-SKY ABI](https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource//1695027452256/T-HEAD_800_Series_ABI_Standards_Manual.pdf).
  - [x] `hexagon`: N/A: No hardware support and not mentioned in the [Hexagon ABI](https://lists.llvm.org/pipermail/llvm-dev/attachments/20190916/21516a52/attachment-0001.pdf).
  - [x] `m68k`: N/A: No hardware support, not mentioned in the [M68k ABI](https://m680x0.github.io/doc/abi.html) (`long double` is `f80` AFAICT).
  - [x] `mips`: Needs `f16` (has hardware support). No hardware `f128` support, no single-register-sized mentions in the [o32](https://refspecs.linuxfoundation.org/elf/mipsabi.pdf), [n32](https://irix7.com/techpubs/007-2816-005.pdf) or [n64](https://irix7.com/techpubs/007-2391-006.pdf) ABIs. Done in #160851.
  - [x] `msp430`: N/A: No hardware support, not mentioned in the [MSP430 ABI](https://www.ti.com/lit/an/slaa534a/slaa534a.pdf).
  - [ ] `nvptx`: Needs `f16` (has hardware support). No hardware `f128` support and no mention in [NVPTX ABI](https://docs.nvidia.com/cuda/ptx-writers-guide-to-interoperability/index.html). Done in #161667.
  - [x] `sparc`: Needs `f128` (has hardware support) (hardware-supported `f32` and `f64` are also missing). No hardware `f16` support and no mention in the [64-bit SPARC ABI](https://sparc.org/wp-content/uploads/2014/01/SCD.2.4.1.pdf.gz) or the [32-bit SPARC ABI](https://sparc.org/wp-content/uploads/2014/01/psABI3rd.pdf.gz). Done in #160949.
  - [ ] `spirv`: Needs `f16` (has native support). No native `f128` support.
  - [x] `wasm`: N/A: Currently no native support, no single-value mentions in the [WASM ABI](https://github.com/WebAssembly/tool-conventions/blob/main/BasicCABI.md).
  - [x] `xtensa`: N/A: No hardware support, not mentioned in the [Xtensa ABI](https://0x04.net/~mwk/doc/xtensa.pdf).

I've generally assumed that, if there isn't any hardware support for a type and it isn't mentioned as been passed in a particular type of register in the ABI specification, we don't need to add any inline ASM support for said type.

**Comment by folkertdev** [comment]
Given that rustc itself has no support for any spirv target (`rustc --print target-list | grep "spir"` returns nothing), and we don't have any support spirv assembly (in-tree anyway), I think we're done here?

**Comment by tgross35** [comment]
I'm fine to close it, or leave it open if there are others I missed that we may as well track here. @beetrees knows the most here so your choice.

**Comment by beetrees** [comment]
All `rustc` targets that have native support now have inline ASM support; I've asked about the status of SPIR-V on Zulip in [#t-compiler > SPIR-V inline ASM architecture status](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/SPIR-V.20inline.20ASM.20architecture.20status/with/626365803). I'll leave this issue open till we work out whether we want to add inline ASM `f16` to SPIR-V, but I think apart from that this is complete.
