### ISSUE TITLE
Tracking Issue for externally implementable items

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#125418]
This is a tracking issue for the lang **experiment** on externally implementable items.  This currently covers these proposals:

- https://github.com/rust-lang/rfcs/pull/3632
- https://github.com/rust-lang/rfcs/pull/3635
- https://github.com/rust-lang/rfcs/pull/3645
- https://github.com/rust-lang/rfcs/pull/2492

The feature gate for the issue is `#![feature(extern_item_impls)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Get alternate proposals.
  - [x] Original proposal from @m-ou-se. https://github.com/rust-lang/rfcs/pull/3632
  - [x] Alternative proposal from @m-ou-se. https://github.com/rust-lang/rfcs/pull/3635
  - [x] Alternative proposal from @Amanieu. https://github.com/rust-lang/rfcs/pull/3645
  - [x] Alternative proposal from @tmandry. https://github.com/rust-lang/rfcs/pull/3632#issuecomment-2125972702
- [x] Pick a design for the experiment.
  - Using attributes rather than new syntax: https://github.com/rust-lang/rust/issues/125418#issuecomment-2360542039
- [x] Submit project goal: https://github.com/rust-lang/rust-project-goals/pull/198
  - [x] Approval
- [ ] Implement the experiment.
   - [x] First fix attributes so we can do name resolution in them: https://github.com/rust-lang/compiler-team/issues/796
   - [x] Implement externally implementable items using attributes: https://github.com/rust-lang/rust/pull/146348
- [ ] Verify proposals are consistent with:
  - https://github.com/rust-lang/rfcs/pull/3484
- [ ] Write/update RFC based on experiment.
- [ ] Accept an RFC.
- [ ] Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- [ ] Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
- [ ] Add formatting for new syntax to the [style guide][].
    - See the [nightly style procedure][].

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- Which exact alternative or alternatives should we adopt?

### Related

- https://github.com/rust-lang/rfcs/pull/3632
- https://github.com/rust-lang/rfcs/pull/3635
- https://github.com/rust-lang/rfcs/pull/3645
- https://github.com/rust-lang/rfcs/pull/2492

### Implementation history

- https://github.com/rust-lang/rust/pull/146348

### TODO

- Check `no_mangle` on EIIs is rejected properly
- Implement for codegen_gcc
- windows support
- rewrite panic_handler in terms of EII
- rewrite alloc_handler in terms of EII
- macos support: https://github.com/rust-lang/rust/pull/146348#issuecomment-3631810110

cc @m-ou-se @Amanieu @tmandry @joshtriplett

**Comment by m-ou-se** [comment]
@jdonszelmann and I are currently impleneting this, with a different syntax. Instead of using new syntax (e.g. `extern impl fn ...`) as in the RFC draft, we're using attribute macros instead:

```rust
#[externally_implementable(thing_handler)]
fn do_thing();
```
```rust
#[thing_handler]
fn my_thing_handler() {
    ..;
}
```

This has a number of advantages. `#[thing_handler]` could be replaced by a proc_macro in semver-compatible versions of the crate, so we don't need to worry about providing conversion/upgrade mechanisms. It also makes it look identical to `#[panic_handler]` and `#[global_allocator]` attributes. It clarifies the naming and visibility issue: `do_thing` is the function to call, and `#[thing_handler]` is the attribute to override it, so they each have their own name and visibility. And it allows us to place `unsafe` in the attribute itself, to separate "unsafe to implement" and "unsafe to call".

More updates soon!

**Comment by Amanieu** [comment]
Does this introduce a new global namespace for `thing_handler`? I would prefer if this was a proper path to an item within a crate since that properly takes care of things like multiple instances of the same crate with different major versions.

**Comment by m-ou-se** [comment]
> Does this introduce a new global namespace for `thing_handler`?

Nope! It behaves the same as any other attribute (macro), as an item with a path.

**Comment by nikomatsakis** [comment]
(Adding myself in my role as lang-team champion only)

**Comment by bstrie** [comment]
It would be nice to have a more-or-less complete list of externally-definable items that the stdlib would seek to provide. RFC 3632 mentions panic_handler and global_allocator, and implies that there are others that could use this, but I'm drawing a blank.

**Comment by bjorn3** [comment]
The rng used by `DefaultHasher` (so we can move `HashMap` to `alloc`), and probably things like the `Mutex` implementation, and other well defined OS interfaces.

**Comment by LegNeato** [comment]
Why not...everything? Some use-cases I can come up with off the top of my head:

* Filesystem so you can swap out for an in-memory FS during testing and fuzzing. Or so you can scope a binary to a particular FS sandbox and your deps are blissfully unaware. Or for FS support on embedded with custom impls for your particular board + storage + OS combo.
* Channels so you can use them to communicate between workgroups when run on the GPU via rust-gpu
* Network so you can simulation test code in a made up network or proxy real services in production. You could also add observability at the network api level so every dependency using networking use doesn't need to do so.
* threads, so I can put a watchdog or heartbeat on all threads created.

Give me a rust api, and I can come up with multiple situations for why I'd want to control it from user code. Almost all of them involve testing and observability, but there are realcapability use-cases as well.

IMO `std` should be a bunch of traits with a default concrete implementation. That's too big of an ask, but this feature has the potential to get 80% of the way there and unlock use-cases and quality we can't imagine today.

**Comment by Enselic** [comment]
I intend to try to solve the `SIGPIPE` problem with an externally implementable item, as suggested [here](https://github.com/rust-lang/rust/issues/97889#issuecomment-2437138234).

libstd would somehow (tbd) define a "pre-main" hook that by default sets `SIG_IGN` on `SIGPIPE` on unix. Then a simple `[dependencies] sigpipe-default = "1.0.0"` in `Cargo.toml` would override that function in libstd and instead set `SIG_DFL` on `SIGPIPE`. Or leave it untouched (`sigpipe-inherit`).

**Comment by programmerjake** [comment]
> > [...] implies that there are others that could use this, but I'm drawing a blank.
> 
> I intend to try to solve the `SIGPIPE` problem with an externally implementable item, as suggested [here](https://github.com/rust-lang/rust/issues/97889#issuecomment-2437138234).
> 
> libstd would somehow (tbd) define a "pre-main" hook that by default sets `SIG_IGN` on `SIGPIPE` on unix. Then a simple `[dependencies] sigpipe-default = "1.0.0"` in `Cargo.toml` would override that function in libstd and instead set `SIG_DFL` on `SIGPIPE`. Or leave it untouched (`sigpipe-inherit`).

maybe a better approach would be to have an externally implemented item that handles `EPIPE` from the `print!` family of macros, by default it would panic, but it could be overridden to exit without any messages (exiting without messages might be a better default anyway...maybe a silent panic so cleanup still runs?). that way your process wouldn't abort if a network connection was dropped, but would still behave like a standard unix application and terminate if stdout wasn't fully read in a pipeline.

**Comment by bjorn3** [comment]
The intent of not changing `SIGPIPE` is that if the program inherited the default signal disposition for `SIGPIPE`, the program will kill the process on any read/write of a broken pipe, not just for those in the `print!` family. However if the program inherited `SIGIGN` for `SIGPIPE` it would behave as libstd currently does and returning `EPIPE`. The inheriting the signal disposition is the important part. If not for that part everyone could just change the signal disposition for `SIGPIPE` back to the default.

**Comment by m-ou-se** [comment]
Update:

@jdonszelmann has a working prototype in which `#[panic_handler]` is fully implemented as a library feature. `core` simply declares an 'externally implementable' `fn panic_handler`, and std and any usage of the panic handler remain unchanged. (Except you now get better errors if you get the signature wrong!). There is no more mention of `panic_handler` anywhere in the compiler, which I think is pretty amazing! 🎉

Next steps:

- Write an RFC based on the feature as we now know is implementable.
- Clean up and split the prototype in mergable PRs.

**Comment by orlp** [comment]
Could this perhaps use something namespaced rather than a completely unnamespaced attribute? E.g.
`#[override(panic_handler)]` rather than simply `#[panic_handler]`?

I'm interested in using this feature in library crates as well. For example for my `foldhash` crate it would be nice if I could specify an overridable source of global randomness.  But if this feature is implemented using naked attributes every such instance would add another name to the global attribute namespace which seems like a recipe for disaster, also for backwards-compatibility of introducing new attributes.

Even better if it accepts a path of the thing to override, e.g. `#[override(foldhash::get_global_random_entropy)]` or `#[override(std::panic::panic_handler)]`.

**Comment by jdonszelmann** [comment]
I mean, that's how it works already right? It doesn't add to the global namespace of attributes, it declares a macro, which is exported similar to how `macro_rules` would be (or actually more like macro v2, which is nicer in that it doesn't go to the root of the crate). In other words; it works like the following example

```rust
// my_crate

mod foo {
    #[eii]
    fn bar();
}

// dependent crate
#[my_crate::foo::bar]
fn implements_bar() {}
```

If I understand your question correctly, that should make it work for you right? If you're interested, you can experiment with https://github.com/rust-lang/rust/pull/146348. The implementation, though it needs some work, is reasonably solid now.

**Comment by jdonszelmann** [comment]
I've updated the main issue text with a bunch of TODO items :3

**Comment by boozook** [comment]
Usage-counter of eii-implementation should inherit number of uses (references/calls) of a eii-definition, imho. Otherwise DCE eats impls.

_tested current implementations for functions and statics ([ref](https://github.com/rust-lang/rfcs/pull/3632#issuecomment-4561443151))._

_Maybe I'm wrong, now it looks like it minimizes duplicate conflicts and gives more manual control, but requires you to explicitly import the implementation by-hands. __And now eii-implementation must be public for it__, or internally used to prevent dce._

**Comment by jdonszelmann** [comment]
For a first experiment of what EIIs in the standard library could look like, here's a draft PR for a feature RfL would really like: https://github.com/rust-lang/rust/pull/157314

**Comment by bushrat011899** [comment]
> For a first experiment of what EIIs in the standard library could look like, here's a draft PR for a feature RfL would really like: [#157314](https://github.com/rust-lang/rust/pull/157314)

I also have a use-case for EIIs in the standard library for moving `std::io::Error` into `core` (see [#155625](https://github.com/rust-lang/rust/pull/155625/changes#diff-5334466bab1c8af1f28b617d7b3579dd1052ca733effd5d0d4e4c900be8c0223R1-R61)). If EII with defaults was reliably available (at least for targets where `std` is provided), I could replace the use of a static `AtomicPtr` with something like [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=51791a8ac8a7322eb5b4c03c20eb9669).

**Comment by boozook** [comment]
I've been using the `eii` feature (for statics and funcs) already, I've been waiting for it for 10 years, thanks! ❤️‍🔥
Please don't forget about __`naked` functions as `eii`-impl.__ Currently it's broken for naked functions.

**Comment by bjorn3** [comment]
Naked functions as EII may not be possible. It is possible that we will have to introduce a wrapper function that forwards to the right EII impl. But naked functions can't have wrapper functions. If you only need ELF and Mach-O platforms, you could directly define weak functions in your inline asm. EII also has to work with PE/COFF and other object file formats that have bad weak symbol support.

**Comment by Paladynee** [comment]
a few questions about this RFC:

1) what happens when there's `crate_a`, `crate_b` and `crate_c`. Think of `crate_a` as a default user binary crate, `crate_b` and `crate_c` as libraries.

`crate_b` exports an EII (externally implementable item/externally definable function/externally definable static etc.), and `crate_c` acts as a wrapper over `crate_b`, while relying on the fact that it implemented the `crate_b`'s EII for its own soundness, logical correctness. giving the user the opportunity to then overwrite `crate_b`s implementation causes one of 3 problems, mutually exclusively:
- `crate_c` has unsound behavior due to invariant breakage because the user changed the implementation (might be avoidable with having all EIIs unconditionally also be `unsafe`: `unsafe extern static ...`)
- compiling `crate_b` twice, one for `crate_c`, one for `crate_a`, the two versions with different overrides.
- EIIs may not be relied upon for emergent qualities of code such as soundness, unwind safety, logical correctness etc. other than the type information (function return type & unwindability & other function attributes / type of the static value)
 
2 )there's also a hidden two dimensional visibility matrix involving who can override and who can use/call these EIIs. i dont believe allowing everyone who can name the EII to also override it is a good idea, since it'll lead to "empirically-sealed" modules when people will eventually want to depend on it for invariants:

```rs
pub mod __private_externs {
    extern impl fn get_crate_name() -> &'static str; 
}
```

3) the RFC mentions that "It is an error to have no impl static item (in any crate) for an extern static item without a default value."

In the case of violation of the clause, the answer to the question "who is the erroneous crate" is not immediately obvious to me. Is a library not defining the externally implemented thing erroneous? Can't the library just depend on whatever that externally defined thing is on other crates? That'd enforce the library to essentially "bubble up" the EII manually, a huge semver trap: in a setup with crates `foo`, `image` and `png`, where `foo` is the end user crate; `png` is a dependency of `image`; and `png` exports an EII, if `image` wants to let the user to define the EII for `png` (and use that EII for its own implementations), it has to do the following:
```rs
// crates/image/src/lib.rs
extern crate png; // assume extern impl fn log_handler(msg: &Log);
extern impl png_externs_log_handler(msg: &png::Log);
impl fn log_handler(msg: &png::Log) {
    png_externs_log_handler(msg)
}
```

this not only vendor locks the user to use `png` through `image` as long as they continue using `image`, but also prevents anyone else other than `image` from overriding `png`'s EIIs due to having another clause that prevents multiple overrides.

Also, focusing on the "in any crate" specifically, importing a big crate like `tokio` - depending on the specific implementation of EIIs - may either
- pull in numerous amounts of internal EIIs to the downstream end user crate which have to be manually defined
- or have to resort to the `image`-`png` workaround shown above.

The end user binary crate is a possible candidate for the ultimate erroneous crate as it is the root of all empirical compilation, but how about dependencies between libraries?


i'd be glad if someone could clarify these questions i had about the RFC

**Comment by bjorn3** [comment]
1. If there are multiple definitions of an EII you will get an error.
2. Why would you want to use EIIs if not to allow the user to select a different implementation?
3. Introducing a new EII without default implementation is indeed a semver breaking change. This matches how the standard library can't add new features like `#[panic_handler]` without adding a default implementation.

By the way please only use tracking issues for progress on implementing the feature and keep questions to other venues like the RFC or the zulip.
