### ISSUE TITLE
Tracking issue for migrating from Glacier to compiletest ICE tracking

### ISSUE THREAD

**Issue by fmease** [rust-lang/rust#125459]
Tracks the necessary steps to fully transition from [rust-lang/glacier] to `compiletest` ICE tracking inside `tests/crashes/`.
See also [this Zulip topic][zulip].

### Steps

- [x] Implement `rustc` ICE/crash tracking: #122997
- [ ] Implement `rustdoc` ICE/crash tracking
- [ ] Implement `rustfmt` ICE/crash tracking
- [ ] Implement ICE/crash tracking via `run-make`/`rmake` (to supersede Glacier's shell scripts)
- [x] Archive [rust-lang/glacier]: rust-lang/team#1459
- [ ] Sunset [triagebot] support for Glacier
- [ ] Update the [rustc-dev-guide]
  * Remove mentions of Glacier
  * Add small section about `tests/crashes/`: Overview, rough procedure (adding `//@ known-bug`, https://github.com/rust-lang/rust/labels/S-bug-has-test)
  * Mention `tests/crashes/` in places where we reference https://github.com/rust-lang/rust/labels/E-needs-test
- [ ] Update the [Rust Forge][forge]
  * Remove mentions of Glacier (namely the [triagebot section](https://forge.rust-lang.org/triagebot/glacier.html))
  * Maybe mention the new system in the [issue triaging chapter](https://forge.rust-lang.org/release/issue-triaging.html) 

### Unresolved Questions

* Should we implement `rust{doc,fmt}` support via subdirectories/tests suites (e.g., `tests/crashes/rust{doc,fmt}/`) or via a new compiletest directive (e.g., `//@ bin: rust{fmt,doc}`)
  * If we do the former, should we move `rustc` tests from `tests/crashes/` to `tests/crashes/rustc/`?
* Should we define *precise* procedures for adding new tests to `tests/crashes`?

[rust-lang/glacier]: https://github.com/rust-lang/glacier/
[rustc-dev-guide]: https://rustc-dev-guide.rust-lang.org/
[forge]: https://forge.rust-lang.org/
[triagebot]: https://github.com/rust-lang/triagebot/
[zulip]: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/where.20to.20mass-add.20known.20ices.20.2F.20merging.20glacier.20into.20rust/near/429082963

**Comment by fmease** [comment]
cc @matthiaskrgr

**Comment by matthiaskrgr** [comment]
I'm not sure if it makes a lot of sense to track crashes inside the rustc repo for tools (rustfmt, clippy, miri etc) that are actually living inside their own repos because in most cases I guess you would "accidentally" fix something during a submodule/tree sync?

**Comment by fmease** [comment]
Good point. I guess that means T-rustfmt for example needs to introduce their own mechanism if they're interested in doing that and that "we" won't try to find a Glacier replacement for them.
