### ISSUE TITLE
Tracking Issue for RFC 3624: Supertrait item shadowing v2

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#125788]
This is a tracking issue for RFC 3624: Supertrait item shadowing v2.

The feature gate for the issue is `#![feature(supertrait_item_shadowing)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Accept an RFC.
  - https://github.com/rust-lang/rfcs/pull/3624
- [ ] Implement in nightly.
  - https://github.com/rust-lang/rust/pull/125782
- [ ] Add documentation to the [dev guide][].
  - See the [instructions][doc-guide].
- [ ] Add documentation to the [reference][].
  - See the [instructions][reference-instructions].
- [ ] Add formatting for new syntax to the [style guide][].
  - See the [nightly style procedure][].
- [ ] Stabilize.
  - See the [instructions][stabilization-instructions].

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[stabilization-instructions]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

TODO.

### Related

- https://github.com/rust-lang/rust/pull/125782

**Comment by traviscross** [comment]
Actually, on second thought, let's just reuse the existing tracking issue:

- https://github.com/rust-lang/rust/issues/89151
