### ISSUE TITLE
Tracking Issue for `--print=check-cfg`

### ISSUE THREAD

**Issue by Urgau** [rust-lang/rust#125704]
This is a tracking issue for the MCP 743 "Add --print=check-cfg" (https://github.com/rust-lang/compiler-team/issues/743).
The flag is gated under `-Zunstable-options`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [X] Implement the MCP (https://github.com/rust-lang/rust/pull/124320)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
	- [unstable book - --print=check-cfg](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/print-check-cfg.html)
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

None at this time.

### Implementation history

 - https://github.com/rust-lang/rust/pull/124320
