### ISSUE TITLE
Tracking Issue for RFC 3467: UnsafePinned

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#125735]
This is a tracking issue for RFC 3467: `UnsafePinned`.

- https://github.com/rust-lang/rfcs/pull/3467

The feature gate for the issue is `#![feature(unsafe_pinned)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement.
- [ ] Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- [ ] Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
- [ ] Stabilize.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [ ] Do we want to bikeshed the name further before stabilization?

### Related

- https://github.com/rust-lang/rfcs/pull/3467

### Implementation history

TODO.

**Comment by RalfJung** [comment]
Turns out the existing hack that attempts to make self-referential async lowering sound is [incomplete](https://github.com/rust-lang/miri/issues/3780#issuecomment-2264908274), and we most likely need `UnsafePinned` to make it actually sound.

**Comment by RalfJung** [comment]
In the RFC we had the question whether `UnsafePinned` should also act like an `UnsafeCell`. I am now fairly sure that the answer is "yes, it must". The reason is [this](https://github.com/rust-lang/miri/issues/3796#issuecomment-2299177277): due to `Pin::deref` being safe, it is at any moment possible to create a shared reference to a future that is halted at a suspension point. If there is no `UnsafeCell`, this acts like a read of the entire future data, and that read conflicts with mutable references that the future may hold to its own data. This is not a necessary property of aliasing with mutable reference, but it is a necessary consequence of the decision that `Pin::deref` should be safe.

Cc @rust-lang/opsem

**Comment by Sky9x** [comment]
## Implementation status update

1. **Libs**: https://github.com/rust-lang/rust/pull/137043
   - `UnsafePinned` struct
   - `UnsafeUnpin` private auto trait
   - disable niches on `UnsafePinned`
2. **Lowering**: https://github.com/rust-lang/rust/pull/139896
   - New `CoroutinePinnedLocals` mir dataflow analysis  
   - `CoroutineLayout`: calculate pinned coroutine fields (borrowed across a yield)
   - builtin impl logic of `UnsafeUnpin` for coroutines in both trait solvers
3. **Codegen**: TODO
   - restore coroutine niche optimizations (#129313)
   - `noalias` metadata for `&mut` is now dependent on `UnsafeUnpin`, not `Unpin`
4. **Miri**:  TODO
   - make miri understand how `UnsafePinned` fields work
   - add retags and protectors inside of `![Unsafe]Unpin` types
   - `PhantomPinned` compatibility hack?

**Comment by onestacked** [comment]
> In the RFC we had the question whether `UnsafePinned` should also act like an `UnsafeCell`. I am now fairly sure that the answer is "yes, it must". The reason is [this](https://github.com/rust-lang/miri/issues/3796#issuecomment-2299177277): due to `Pin::deref` being safe, it is at any moment possible to create a shared reference to a future that is halted at a suspension point. If there is no `UnsafeCell`, this acts like a read of the entire future data, and that read conflicts with mutable references that the future may hold to its own data. This is not a necessary property of aliasing with mutable reference, but it is a necessary consequence of the decision that `Pin::deref` should be safe.

@RalfJung @Sky9x  The current implementation does not contain `UnsafeCell` and even explicitly mentions that `UnsafePinned`

> does not lift the requirement that shared references must be read-only!

I assume that this means that the plan is for this to stay this way and that some solution for the `Pin::deref` problem was found that doesn't require `UnsafeCell` in `UnsafePinned` is that correct?

This question came up on the LKML: https://lore.kernel.org/rust-for-linux/aBJTVWsrqzuasx7W@Mac.home/

**Comment by RalfJung** [comment]
@onestacked due to https://github.com/rust-lang/rust/issues/137750, we'll likely want to change this and declare `&UnsafePinned` to be basically equivalent to `&UnsafeCell`.

**Comment by RalfJung** [comment]
> `UnsafePinned::get` signature has been changed to returned `*mut T` in [#142162](https://github.com/rust-lang/rust/pull/142162), but `UnsafePinned::raw_get` was left untouched and still returns `*const T`. Shouldn't `raw_get` signature be updated too, in order to be consistent with `get`?

Good point, I opened https://github.com/rust-lang/rust/pull/145593 for that.



> By the way, now that `UnsafePinned::get` returns `*mut T`, is `UnsafePinned::get_mut_unchecked` still justified? Are there some borrow rules that would require to call `get_mut_unchecked` instead of `get` in some cases? The question can also apply to `UnsafePinned::raw_get_mut` if `UnsafePinned::raw_get` signature is updated to return `*mut T` (see my previous comment).

It doesn't really seem needed any more. OTOH, having `get` and `get_mut_pinned` where the short function is the more dangerous one does not seem great...

**Comment by wyfo** [comment]
> OTOH, having `get` and `get_mut_pinned` where the short function is the more dangerous one does not seem great...

Actually, another effect of #142162 is that `get_mut_pinned` has become "useless", as `get` can always be used instead. Indeed, thanks to `Pin::deref`, this compiles:
```rust
fn get_mut_pinned<T: ?Sized>(pinned: Pin<&mut UnsafePinned<T>>) -> *mut T {
    pinned.get() // same as `pinned.get_mut_pinned()`
}
```
So, maybe we should only keep `get` and `raw_get` after all... 

Using `UnsafePinned` for things like intrusive list is already fully unsafe and very complex, so I'm not sure that an API like `get_mut_pinned` helps a lot here; you still have to deal with pointers that can be aliased everywhere. In fact, I started to play with `UnsafePinned` in a intrusive list implementation (before #142162), and using `get_mut_pinned` was requiring me to do a pin-projection of my inner `UnsafePinned` field first. So I had basically the choice between:
- unsafe `Pin::map_unchecked_mut` + `UnsafePinned::get_mut_pinned`
- unsafe `Pin::get_unchecked_mut` + `UnsafePinned::get_mut_unchecked`

and I chose the second one. Today, thanks to #142162, I just use `UnsafePinned::get`.

**Comment by jacobsa** [comment]
Hi, question about what seems to be an omission in the documentation: should `UnsafePinned` make the same layout guarantees as `UnsafeCell`? I assume that's more or less intended, but it would be good to be explicit (and in any case I'd still be happy with an answer here).

For the record: the reason I care is that I'm pretty sure I need this guarantee in order to be able to do in-place initialization of the `T` within an `UnsafePinned<T>`, using e.g. Crubit's [`ctor`](https://github.com/google/crubit/blob/bee20b5882907b492a0a4c6670b794ff8e68cca3/support/ctor.rs) crate, at least in order for it to approach being ergonomic.

**Comment by RalfJung** [comment]
Yeah it would make sense to give it the same layout guarantees.

**Comment by nbdd0121** [comment]
The change that make `UnsafePinned` also wrap `UnsafeCell` changes the variance of `UnsafePinned`. In 1.87/1.88 `UnsafePinned` is covariant, while 1.89+ it becomes invariant. This makes it much more limiting than `PhantomPinned` as that doesn't change the variance.

For code that just needs pinning for self-reference and not for mutation, this is very limiting.

**Comment by RalfJung** [comment]
Oh yeah I didn't think about variance at all.

It would seem a bit odd if UnsafePinned becomes the way to have covariant interior mutability...

**Comment by nbdd0121** [comment]
Well, I suppose if we have [`CovariantUnsafeCell`](https://github.com/rust-lang/libs-team/issues/815) then `UnsafePinned` should move to use that instead.
