### ISSUE TITLE
Tracking Issue for `mixed_integer_ops_unsigned_sub`

### ISSUE THREAD

**Issue by davidzeng0** [rust-lang/rust#126043]
Feature gate: `#![feature(mixed_integer_ops_unsigned_sub)]`

This is a tracking issue for https://github.com/rust-lang/libs-team/issues/386

### Public API

```rust
impl uX {
    pub const fn checked_sub_signed(self, iX) -> Option<Self>;
    pub const fn overflowing_sub_signed(self, iX) -> (Self, bool);
    pub const fn saturating_sub_signed(self, iX) -> Self;
    pub const fn wrapping_sub_signed(self, iX) -> Self;
}
```

### Steps / History

- [x] ACP: https://github.com/rust-lang/libs-team/issues/386
- [x] Implementation: https://github.com/rust-lang/rust/pull/126046
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by callmeclover** [comment]
@Amanieu @rust-lang/libs Can we start FCP on this? The ACP (https://github.com/rust-lang/libs-team/issues/386) and implementation (#126046) passed last year.

**Comment by Amanieu** [comment]
I'm not a huge fan of `overflowing_*` methods but I think it's fine in this case since it is consistent with the existing ones. The other methods seem fine to me.

@rfcbot merge
