### ISSUE TITLE
Tracking Issue for offset_of_slice

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#126151]
The feature gate for the issue is `#![feature(offset_of_slice)]`.

This is a tracking issue for allowing offset_of to determine the offset of unsized fields whose tail is a slice, and hence their alignment and their offset is statically known.

### Steps

- [ ] Implement the RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Implementation history

- https://github.com/rust-lang/rust/pull/126150
