### ISSUE TITLE
Tracking Issue for async drop codegen

### ISSUE THREAD

**Issue by zetanumbers** [rust-lang/rust#126482]
This is a tracking issue for the async drop codegen from MCP "727" (rust-lang/compiler-team#727).
The feature gate for the issue is `#![feature(async_drop))]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [ ] Implement the async drop codegen
  - [x] `AsyncDrop` trait (#121801)
  - [ ] `async_drop_in_place_raw`/async drop glue generation support for
    - [x] Trivially destructible types (integers, bools, floats, string slices, pointers, references, etc.), arrays and slices (array pointer is unsized into slice pointer), ADTs (enums, structs, unions), tuple-like types (tuples, closures) (#121801)
    - [ ] Dynamic types (`dyn Trait`)
      - One proposed design: https://zetanumbers.github.io/book/async-drop-design.html#dyn_trait
    - [ ] Coroutines (#123948)
  - [ ] Type level support (possibly outside of the scope of this tracking issue)
    - [ ] Union rejects non-trivially async destructible fields
    - [ ] `AsyncDrop` implementation requires same bounds as type definition
    - [ ] Synchronously undroppable types
  - [ ] Optimizations
    - [x] Skip trivially destructible fields (optimization) (#124662)
    - [ ] New [`TyKind::AdtAsyncDestructor`](https://zetanumbers.github.io/book/async-drop-design.html#adt-async-destructor-types) and get rid of combinators
  - [ ] Automatic async drop at the end of the scope in async context (#123948)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] ~~Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])~~
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [ ] Async drop for dynamic types (`dyn Trait`)
  - One proposed design: https://zetanumbers.github.io/book/async-drop-design.html#dyn_trait
- [ ] Drop of async destructors
- [ ] `AsyncDrop` and `Drop` should somehow be combined to not duplicate implementations (possibly outside of the scope of this tracking issue)

### Implementation history

- #121801
- #124662
- #123948

**Comment by AndyGauge** [comment]
I'm not sure what is left to do on Union rejects trivially async destructible fields since AsyncDrop requires Drop and Drop throws E0740.

**Comment by P8L1** [comment]
@AndyGauge I think the main work still left is the dyn case. I'm unsure about unions at the moment. But I know for a fact dyn has not been handled. I have reached out to @nikomatsakis for advice on a PR to lay the groundwork for dyn earlier this week. (It is an edited version of Zetanumbers's approuch). I am yet to receive a reply. My Zulip is P_L1 catch me there if you want more info about what I want to do!

Have a good one!
