### ISSUE TITLE
Tracking Issue for `x86_sha512_sm`

### ISSUE THREAD

**Issue by sayantn** [rust-lang/rust#126624]
This tracks the integration of Intel's `SHA512`, `SM3` and `SM4` instruction sets in Rust

The feature gate for the issue is `#![feature(x86_sha512_sm)]`.

### Steps

- [ ] Add the feature to rustc
- [ ] Add the target-features
- [ ] Add the intrinsics to stdarch
- [ ] Stabilization PR

**Comment by sayantn** [comment]
cc @rust-lang/lang
cc @Amanieu 

I believe these are ready to be stabilized, as all the implementation jobs are done.

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We do our stabilization FCPs on stabilization PRs.  Please submit and nominate one of those for us along with the stabilization report.  See the new template for that:

https://github.com/rust-lang/rustc-dev-guide/pull/2219

**Comment by sayantn** [comment]
The lang-stabilization is being done in #140767, so let's do the libs stabilization here (intrinsics and runtime detection, in rust-lang/stdarch#1796)

@rustbot label I-libs-api-nominated

**Comment by Amanieu** [comment]
Libs-api FCP for the intrinsics.

@rfcbot merge
