### ISSUE TITLE
Tracking Issue for `x86_amx_intrinsics`

### ISSUE THREAD

**Issue by sayantn** [rust-lang/rust#126622]
This issue tracks the integration of Intel `AMX` instruction family to Rust.

The feature gate for the issue is `#![feature(x86_amx_intrinsics)]`.

### Steps

- [ ] Add the feature flag to rustc
- [ ] Add the `target-feature` attributes
- [ ] Implement the associated intrinsics in stdarch
- [ ] Stabilization PR

**Comment by sayantn** [comment]
Afaik, AMX doesn't change any ABI. Although we would need to change some things in inline asm to support `tmm` registers (it is currently clobber-only, when we introduce the `__tile1024i` type in stdarch, we can use that in inline asm, but sadly it would require compiler support to add the `__tile1024i` type)

**Comment by SupernaviX** [comment]
Looks like AMX-TF32 has also been removed upstream https://github.com/llvm/llvm-project/pull/207673

**Comment by sayantn** [comment]
> Looks like AMX-TF32 has also been removed upstream https://github.com/llvm/llvm-project/pull/207673

Yea, it is being removed from Rust too #158910 and rust-lang/stdarch#2184
