### ISSUE TITLE
Tracking Issue for annoymous_pipe API

### ISSUE THREAD

**Issue by NobodyXu** [rust-lang/rust#127154]
This is a tracking issue for the ACP rust-lang/libs-team#375 .
The feature gate for the issue is `#![feature(annoymous_pipe)]`.

### Steps

- [ ] Implement the ACP #127153
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Implementation history

 - #127153

**Comment by Fulgen301** [comment]
You might want to fix the typo in the title and feature name - it's an an**on**ymous pipe, not an annoymous pipe.

**Comment by NobodyXu** [comment]
Thanks!

I've fixed the typo in this issue and the linked PR.

**Comment by NobodyXu** [comment]
I think we can now add more specialisation to [`std::io::copy`](https://doc.rust-lang.org/src/std/sys/pal/unix/kernel_copy.rs.html#407) for `std::pipe`

**Comment by NobodyXu** [comment]
I'm thinking about a new method for checked conversion from `OwnedFd` on unix.

I think it would be quite helpful for jobserver-rs

**Comment by RalfJung** [comment]
Currently the documentation for this module is very bare-bones, quite far from the depth and quality we are used to in other parts of the standard library. There's not even a single example. This should be resolved before stabilization.

**Comment by NobodyXu** [comment]
@olishmollie has added e examples and improve documentation in #133986, does it mean it can be stabilised @RalfJung

**Comment by RalfJung** [comment]
That's up for the team to decide. I have nominated this for team discussion to get them to take a look at this.

**Comment by joshtriplett** [comment]
I'm going to go ahead and start a stabilization FCP to collect consensus asynchronously, though we'll still talk about it in a meeting as well:

@rfcbot merge

**Comment by dtolnay** [comment]
I have added an API outline to the top of this issue. It is different from the one in the ACP.

**Comment by tbu-** [comment]
I'd think this makes sense to put into `std::io` instead of creating a new module `std::pipe`. This would also reduce the stuttering in the import paths: `std::io::pipe` instead of `std::pipe::pipe` and also `std::pipe::Pipe{Reader,Writer}` → `std::io::Pipe{Reader,Writer}`.

**Comment by NobodyXu** [comment]
Hmmm I'm worried about having too many stuff in `std::io`, stdlib put all network I/O type in a separate namespace and tokio put pipe in `tokio::net`

**Comment by tbu-** [comment]
I find that creating a new module for these three symbols (`fn pipe`, `struct PipeReader`, `struct PipeWriter`) is a bit too much — fitting it into another module means that the number of modules in `std` directly does not unnecessarily increase.

**Comment by NobodyXu** [comment]
I don't have a particular strong opinion on this honestly, if t/libs-api thinks that's better I am willing to change that

**Comment by joshtriplett** [comment]
No strong preference either. I don't think there's any *problem* with small modules, but I'd also be fine with merging it into `io`.

@rustbot label +I-libs-api-nominated

**Comment by joboet** [comment]
@rust-lang/libs-api were the system-specific trait implementations (e.g. `From<OwnedFd>`, `From<OwnedHandle>`) also part of the FCP? And could you confirm that you are okay with establishing this pattern, considering that `File` does not have such implementations? For what it's worth I have nothing against those implementations, but they are unprecedented...

@rustbot label +I-libs-api-nominated

**Comment by joshtriplett** [comment]
https://doc.rust-lang.org/std/os/fd/struct.OwnedFd.html#impl-From%3COwnedFd%3E-for-File ? Or do you mean something else?

**Comment by joboet** [comment]
Oh dang, sorry, I totally overlooked that. Nevermind!

**Comment by LevitatingBusinessMan** [comment]
Did something happen to this experimental api?

The example code at https://doc.rust-lang.org/stable/std/pipe/index.html does not seem to compile anymore.

**Comment by NobodyXu** [comment]
It has been moved into std::io

https://doc.rust-lang.org/nightly/std/io/fn.pipe.html
