### ISSUE TITLE
Work tracking issue for moving `rustc_infer` error reporting into `rustc_trait_selection`

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#127492]
I'm mostly just opening this for myself since I want somewhere to track the work. Look away unless you care about completely compiler-internal stuff.

The motivation for doing this is that error reporting in `rustc_infer` is fraught with challenges, like the lack of trait selection. This became evident in #127172, which demonstrates that the new trait solver needs trait selection in order to actually even prove that things can be equal or not. We also suffer from the lack of normalization, and to a lesser extent autoderef (though the latter isn't yet uplifted into trait selection, it very well could be, or at least replicated in some way for the purposes of diagnostics, but that requires trait selection lol)

- [x] Create top level `rustc_trait_selection::error_reporting` module (#127493)
- [x] Move trait error reporting to `error_reporting::traits` (from `traits::error_reporting`) (#127493)
    - [x] Split out overflow error reporting from other error reporting (#127495)
    - [x] Split out ambiguity error reporting from other error reporting (#127495)
    - [ ] flatten module structure of `error_reporting::traits` (e.g. no need to have `type_err_ctxt_ext` module) (#128076)
- [ ] Move rustc_infer's error reporting to `rustc_trait_selection::error_reporting::infer` (#128041)
    - [x] Move all the diagnostics from infer -> trait selection ftl file (#128041)
    - [x] Split out region error reporting from type error reporting (#127500)
- [x] Pull `TypeErrCtxt` into `rustc_trait_selection`, and delete all the extension traits (since they can be inherent now) (#128041)
    - [ ] Delete `can_eq_shallow` (#128067)
    - [ ] Delete normalization helper from `TypeErrCtxt` since normalization is defined in `rustc_trait_selection`
- [ ] Audit code for anything that we can now use since error reporting lives in trait selection
