### ISSUE TITLE
Tracking Issue for `-Zdirect-access-external-data`

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rust#127488]
This is a tracking issue for the `-Zdirect-access-external-data` flag for LoongArch.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [x] MCP: https://github.com/rust-lang/compiler-team/issues/707.
- [x] Implementation: https://github.com/rust-lang/rust/pull/119162 (1.78).
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
