### ISSUE TITLE
Tracking Issue for `-Z llvm-plugins`

### ISSUE THREAD

**Issue by nikic** [rust-lang/rust#127577]
### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [x] Implement the option (https://github.com/rust-lang/rust/pull/86267).
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

This option currently only works on targets that use an llvm dylib, which is just x86_64-unknown-linux-gnu. On other targets LLVM is linked statically, and symbols needed by plugins are not visible.

### Implementation history

Originally implemented in https://github.com/rust-lang/rust/pull/86267.
