### ISSUE TITLE
Tracking Issue for `debug_more_non_exhaustive`

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#127942]
Feature gate: `#![feature(debug_more_non_exhaustive)]`

This is a tracking issue for the `non_exhaustive()` function on `fmt::Debug{List, Map, Set, Tuple}`, which provides an easy way to omit fields with `..`.

### Public API

```rust
// core::fmt

impl<'a, 'b: 'a> DebugList<'a, 'b> {
    pub fn finish_non_exhaustive(&mut self) -> Result<(), Error>;
}

impl<'a, 'b: 'a> DebugMap<'a, 'b> {
    pub fn finish_non_exhaustive(&mut self) -> Result<(), Error>;
}

impl<'a, 'b: 'a> DebugSet<'a, 'b> {
    pub fn finish_non_exhaustive(&mut self) -> Result<(), Error>;
}

impl<'a, 'b: 'a> DebugTuple<'a, 'b> {
    pub fn finish_non_exhaustive(&mut self) -> Result<(), Error>;
}
```

### Steps / History

- [x] ACP: https://github.com/rust-lang/libs-team/issues/248
- [x] Implementation: https://github.com/rust-lang/rust/pull/127945
- [ ] Final comment period (FCP)[^1] https://github.com/rust-lang/rust/issues/127942#issuecomment-2386608886
- [ ] Stabilization PR https://github.com/rust-lang/rust/pull/131109

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by clarfonthey** [comment]
Small bit of feedback as I'm looking through this, but it feels like it might be useful to actually have the `non_exhaustive` marker anywhere inside these, rather than just at the end.

Example where it'd be useful: I'm working on a tool to help more easily verify that double-ended iterators are working, and they accumulate their data into a `VecDeque` that gets rotated back to the correct position once everything has been accumulated. Therefore, when displaying this data in a `Debug` impl, it would make more sense to indicate the "non-exhaustive" marker in the middle of the list, rather than at the end, since the missing elements will end up between the ones that have already been added to the beginning and end.

While structs have no order to their fields (and thus, adding to the end is appropriate every time), lists *do* have relevant order here, and it feels reasonable to put the marker in the middle.

For now, I'll just add a `RangeFull` entry anyway since that covers it, but it feels like it would be reasonable to do it as a field rather than just a `finish_non_exhaustive` like structs do it.

**Comment by tgross35** [comment]
That is an interesting idea. Are you imagining that this would be something like `.field_elided().finish()` rather than `.finish_non_exhaustive()`?

**Comment by tgross35** [comment]
I think that is a good idea, guess libs-api feedback is needed.

@rustbot label +I-libs-api-nominated 

Requesting discussion about whether we should replace the current unstable API with @clarfonthey's suggestion above. This would mean something like `.elided_fields()`/`.elided_entries()` methods that print `..` at any position. We would probably want the same thing for `DebugStruct`, which already has `finish_non_exhaustive`.

(Name suggestions welcome, `skipped_fields`?)

**Comment by clarfonthey** [comment]
Note that like I mentioned, I don't think that `DebugStruct` needs this since the fields in a struct can be reordered but the `..` must always be at the end, whereas lists and maps do have an explicit order to their fields.

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/libs-api meeting. We'd like to stabilize these four `finish_non_exhaustive` methods as-is.

We may also be amenable to adding `elided_xyz()` methods to show elisions in the middle of an array/tuple/struct/etc, but that'd be separate.

**Comment by joshtriplett** [comment]
FCP to stabilize:

@rfcbot merge

**Comment by tgross35** [comment]
Oh, well that's easier :) candidate PR for after FCP https://github.com/rust-lang/rust/pull/131109
