### ISSUE TITLE
Tracking Issue for unsized const parameter types

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#128028]
This is a tracking issue for supporting unsized types in const generics.
The feature gate for the issue is `#![feature(unsized_const_params)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

Most of the work here will be coordinated in the `#project-const-generics` stream on [zulip](https://rust-lang.zulipchat.com/#narrow/stream/260443-project-const-generics).

- [ ] Experiment with supporting `{ *"hi" }` as a const argument to `const N: str`
- [ ] Resolve #120961 somehow (e.g. by forbidding references if the previous step works out)
- [ ] Author an RFC for the feature
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide]) merges the `ConstParamTy` and `UnsizedConstParamTy` traits

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- Can we forbid references and support `!Sized` types some other way

### Implementation history

- Feature was split out of `adt_const_params` in #127722

**Comment by abohossny** [comment]
> هذه مشكلة تتبع لدعم الأنواع غير المحددة الحجم في الأنواع العامة الثابتة. بوابة الميزة للمشكلة هي `#![feature(unsized_const_params)]`.
> 
> ### حول مشكلات التتبع
> تُستخدم مشكلات التتبع لتسجيل التقدم العام في التنفيذ. كما تُستخدم أيضًا كمحاور تتصل بمشكلات أخرى ذات صلة، مثل الأخطاء أو أسئلة التصميم المفتوحة. ومع ذلك، _لا_ يُقصد بمشكلة التتبع إجراء مناقشات واسعة النطاق أو طرح أسئلة أو الإبلاغ عن أخطاء حول ميزة ما. بدلاً من ذلك، افتح مشكلة مخصصة للمسألة المحددة وأضف علامة بوابة الميزة ذات الصلة. سيتم وضع علامة على تعليقات المناقشة على أنها خارج الموضوع أو حذفها. قد تؤدي المناقشات المتكررة حول مشكلة التتبع إلى قفل مشكلة التتبع.__
> 
> ### خطوات
> سيتم تنسيق معظم العمل هنا في `#project-const-generics`البث على [zulip](https://rust-lang.zulipchat.com/#narrow/stream/260443-project-const-generics) .
> 
> * [ ] تجربة الدعم `{ *"hi" }`كحجة ثابتة لـ`const N: str`
> * [ ] حل [كيف ينبغي أن تعمل العناصر العامة الثابتة ذات المراجع حول هوية المؤشر والحشو؟ ](https://github.com/rust-lang/rust/issues/120961)[ #120961](https://github.com/rust-lang/rust/issues/120961) بطريقة ما (على سبيل المثال عن طريق منع المراجع إذا نجحت الخطوة السابقة)[](https://github.com/rust-lang/rust/issues/120961)
> * [ ] مؤلف RFC للميزة
> * [ ] ضبط الوثائق ( [راجع التعليمات الموجودة في rustc-dev-guide](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs) )
> * [ ] دمج السمات و لتثبيت العلاقات العامة ( [راجع التعليمات الموجودة في دليل rustc-dev](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr) )`ConstParamTy``UnsizedConstParamTy`
> 
> ### أسئلة لم يتم حلها
> * هل يمكننا منع المراجع وأنواع الدعم `!Sized`بطريقة أخرى؟
> 
> ### تاريخ التنفيذ
> * تم تقسيم الميزة `adt_const_params`في [منع الاقتراض والأنواع غير المقاسة من الاستخدام كنوع من النوع الثابت العام تحت `adt_const_params` #127722](https://github.com/rust-lang/rust/pull/127722)
> 
> cc @rust-lang/project-const-generics
