### ISSUE TITLE
Tracking Issue for Rust 2024: Make `missing_fragment_specifier` an error

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#128143]
This is a tracking issue for:

- https://github.com/rust-lang/rust/pull/128006

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024.
  - https://github.com/rust-lang/rust/pull/128122
  - https://github.com/rust-lang/rust/pull/128006
- N/A: Implement migration lints.
- N/A: Add documentation to the [dev guide][].
    - See the [instructions][doc-guide].
- N/A: Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/315
- N/A: Add formatting for new syntax to the [style guide][].
    - See the [nightly style procedure][].
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Related

- https://github.com/rust-lang/rust/pull/128006

@rustbot assign @tgross35

**Comment by ehuss** [comment]
Posted edition-guide docs at https://github.com/rust-lang/edition-guide/pull/315, with the expectation that it might need to be reverted if the change is made in all editions.

**Comment by traviscross** [comment]
@rustbot labels +S-ready-for-edition

Everything is now merged here, and we can mark this item as being **ready** for Rust 2024.

Thanks to @tgross35 for pushing this forward and to @ehuss for the documentation here.

**Comment by tgross35** [comment]
Thanks for making this change happen!
