### ISSUE TITLE
Tracking Issue for `unsigned_is_multiple_of`

### ISSUE THREAD

**Issue by folkertdev** [rust-lang/rust#128101]
Feature gate: `#![feature(unsigned_is_multiple_of)]`
ACP: https://github.com/rust-lang/libs-team/issues/404

This is a tracking issue for the `.is_multiple_of` method on unsigned integers.

Returns `true` if `self` is an integer multiple of `rhs`, and false otherwise.

This function is equivalent to `self % rhs == 0`, except that it will not panic for `rhs == 0`. Instead, `0.is_multiple_of(0) == true`, and for any non-zero `n`, `n.is_multiple_of(0) == false`.

If you have a real usecase for this function on signed integer types, let us know! That was not included for simplicity, but if a usecase comes up, adding it will be considered.

### Public API

A version of this for all the unsigned types 

```rust
fn is_multiple_of(lhs: u64, rhs: u64) -> bool {
    match rhs {
        // prevent division by zero
        0 => lhs == 0,
        _ => lhs % rhs == 0,
    }
}
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/128103
- [x] Final comment period (FCP)[^1]
- [x] Stabilization PR https://github.com/rust-lang/rust/pull/137383

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by diondokter** [comment]
I'd love to have this stable at some point. It's not a must have, but it makes code much nicer to read.

In my case right now, I need to check if the hardware busses have dividers that are a multiple of the main bus. You judge what's better to read and conveys more meaning:

```rust
let apb_dividers = [config.apb1_divider, config.apb2_divider, config.apb3_divider, config.apb4_divider];
for apb_divider in apb_dividers {
    assert!(
        apb_divider.div_value() % config.core_clock_prescaler.div_value()
            == 0
    );
}
```

Or

```rust
let apb_dividers = [config.apb1_divider, config.apb2_divider, config.apb3_divider, config.apb4_divider];
for apb_divider in apb_dividers {
    assert!(
        apb_divider.div_value()
            .is_multiple_of(config.core_clock_prescaler.div_value())
    );
}
```

**Comment by joshtriplett** [comment]
This has been implemented for a while, it's simple and straightforward, it's useful, people want it, and there are no known issues with it.

Shall we stabilize it?

@rfcbot merge

**Comment by jieyouxu** [comment]
Closing this tracking issue as `unsigned_is_multiple_of` has been stabilized in https://github.com/rust-lang/rust/pull/137383 (reopen if reverted or sth).
