### ISSUE TITLE
Tracking Issue for `rwlock_downgrade`

### ISSUE THREAD

**Issue by Connortsui20** [rust-lang/rust#128203]
Feature gate: `#![feature(rwlock_downgrade)]`

This is a tracking issue for a `downgrade` method for `RwLock` as discussed in https://github.com/rust-lang/libs-team/issues/392.

The `downgrade` method on `RwLockWriteGuard` will transform a write-locked `RwLock` into a read-locked one.

### Public API

```rust
impl<'a, T: ?Sized> RwLockWriteGuard<'a, T> {
    pub fn downgrade(s: Self) -> RwLockReadGuard<'a, T> {}
}
```

### Steps / History

- [X] ACP: https://github.com/rust-lang/libs-team/issues/392
- [ ] Implementation: # soon^tm
    - [ ] `downgrade` implementation for [`futex.rs`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/sync/rwlock/futex.rs)
    - [ ] `downgrade` implementation for [`no_threads.rs`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/sync/rwlock/no_threads.rs)
    - [ ] `downgrade` implementation for [`queue.rs`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/sync/rwlock/queue.rs)
    - [ ] `downgrade` implementation for [`solid.rs`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/sync/rwlock/solid.rs)
    - [ ] `downgrade` implementation for [`teeos.rs`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/sync/rwlock/teeos.rs)
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- Does the `solid_asp3` platform already have a `downgrade` method on their `RwLock` implementation?
- Does lock poisoning play into this at all?

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by Connortsui20** [comment]
For the `futex.rs` implementation, it is likely that the protocol for waiting readers will have to change slightly. You can read it in the [code changes](https://github.com/rust-lang/rust/pull/128219/files), but I'll give a quick summary here.

When a call to `downgrade` occurs on the inner `RwLock`, it is arguably incorrect for just the single thread that initially held the write-lock to be the only one who is allowed to hold the read-lock. With no changes to the current implementation, this is what would happen, as we don't let readers (either waiting or very recently entered into the protocol) take the read lock if there are _any_ readers or writers waiting (see the [`is_read_lockable`](https://github.com/rust-lang/rust/blob/2d5a628a1de1d38318909a710ef37da6251e362e/library/std/src/sys/sync/rwlock/futex.rs#L49) function).

So a solution that is arguably less wrong would be to allow readers who have just been waken up after a call to `futex_wait(&self.state)` to take the read lock, regardless of if there are other readers or writers waiting. This means that the `futex.rs` implementation no longer _always_ prioritizes writers over readers, and I'm not sure if this is acceptable.

It is hard to say if this is a good solution, if anyone would like to give their input that would be much appreciated!

**Comment by Connortsui20** [comment]
@joboet Hi, I saw that you wrote the `queue.rs` implementation. Do you have an idea on how to go about implementing `downgrade` for the queue version? I believe it should be something along the lines of finding the tail of the queue and then changing the reader count from 0 to 1, but I am very unfamiliar with the code and I am probably missing something. I also assume that `add_backlinks_and_find_tail` is probably going to be necessary here?

**Comment by joboet** [comment]
Sure! There are two cases to consider:

1. no threads are waiting (fast path)
2. threads are waiting

The fast path is pretty easy, you just need to CAS the write-locked state (`LOCKED`) with the read-locked state for one thread (`LOCKED + SINGLE`).

For the contended case, I'd first of all change this line:
https://github.com/rust-lang/rust/blob/2d5a628a1de1d38318909a710ef37da6251e362e/library/std/src/sys/sync/rwlock/queue.rs#L340-L344

so that the count is one if the lock is write-locked (try `cmp::max`ing the address). I'll get back to this later.

If the fast path above fails, you need to try to acquire the queue lock so that you can make modifications to the queue (try a CAS that sets the `QUEUE_LOCKED` bit, fail if the bit is already set). If this is unsuccessful, then return, as there is no way to wake up new threads. Since the last node contains a lock-count of one (with the change above), the `read_unlock` call will still work correctly.

If you acquired the `QUEUE_LOCKED` bit, then you need to wake up new threads. I'd modify `unlock_queue` so that it takes a `downgrade` argument, if that is `true` then skip the [`LOCKED` check](https://github.com/rust-lang/rust/blob/2d5a628a1de1d38318909a710ef37da6251e362e/library/std/src/sys/sync/rwlock/queue.rs#L487-L502), do not remove the last node if it is a writer ([this](https://github.com/rust-lang/rust/blob/2d5a628a1de1d38318909a710ef37da6251e362e/library/std/src/sys/sync/rwlock/queue.rs#L509-L515) and [this](https://github.com/rust-lang/rust/blob/2d5a628a1de1d38318909a710ef37da6251e362e/library/std/src/sys/sync/rwlock/queue.rs#L523-L527) line need to be skipped) and use `LOCKED + SINGLE` as [unlock value](https://github.com/rust-lang/rust/blob/2d5a628a1de1d38318909a710ef37da6251e362e/library/std/src/sys/sync/rwlock/queue.rs#L535) if the last node is a reader.

**Comment by connortsui20** [comment]
~I think I understand your algorithm, though I was wondering if there might be another way to do it. This algorithm basically is an atomic unlock and place a reader node at the end of the queue, right? Do you think it is possible to implement `downgrade` _without_ adding a node to the queue at all, and instead just mutating the current state so that we go from `0b0001` to `0b1001` for the fast path and for the waiting path simply incrementing the last queue node from a reader count of 0 to 1?~

~I'm not sure this is possible, but if it is, it would allow for more opportunities to potentially wake up readers as well.~

**Comment by connortsui20** [comment]
~I see the problem now after playing around with the code and trying to implement what I said above. In the queue implementation, if there are _any_ waiters in the queue (writer _or_ readers), we do not allow readers to take the read lock. So my idea of waking up readers after a call to downgrade is not exactly compatible with the current implementation.~

~However, that doesn't imply that this is completely impossible with the current implementation. I think what might work is forcing the writer who just downgraded to wake up the next readers in the queue AND remove them from the queue. Maybe the former writer thread can set a bit somewhere (probably stored in the `Node` struct) to let the awakened readers know that they have been awaken by a call to `downgrade`, and then there can be an extra case in `lock_contended` to handle readers who just woke up and observed that bit. However, there might be something I am missing that makes this not able to work.~

~@joboet Do you have any thoughts about this? (Sorry for all of the pings!)~

(EDIT: resolved! see PR)

**Comment by connortsui20** [comment]
# Stabilization Report

### Implementation History

- This method was added in https://github.com/rust-lang/rust/pull/128219
- No substantial changes have been made since (a few type renames, plus the entire module being moved into the new `poison` module).

### API Summary

_(Copied and pasted from the top of this issue)_

```rust
impl<'a, T: ?Sized> RwLockWriteGuard<'a, T> {
    pub fn downgrade(s: Self) -> RwLockReadGuard<'a, T> {}
}
```

### Experience Report

I haven't actually seen anyone else other than me use this feature... so I'll say that I haven't run into any problems?

Nevertheless, nobody has found any issues with this feature since the PR above was merged over half a year ago, and as stated in the ACP this is an identical API to the one found in [`parking_lot`](http://docs.rs/parking_lot/latest/parking_lot/type.RwLockWriteGuard.html#method.downgrade).

@rustbot label +I-libs-api-nominated

**Comment by tgross35** [comment]
Renominated the PR https://github.com/rust-lang/rust/pull/143191 since that is where FCP will take place

@rustbot label -I-libs-api-nominated
