### ISSUE TITLE
Tracking Issue for struct_target_features (RFC 3525)

### ISSUE THREAD

**Issue by veluca93** [rust-lang/rust#129107]
This is a tracking issue for the RFC "struct target features" (rust-lang/rfcs#3525).
The feature gate for the issue is `#![feature(struct_target_features)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [ ] Implement the RFC (#127537)
- [ ] Add support for feature-carrying structs as generic parameters
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [ ] Should functions with witness types as arguments implement Fn traits?
