### ISSUE TITLE
Tracking Issue for `lazy_get`

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-lang/rust#129333]
Feature gate: `#![feature(lazy_get)]`

This is a tracking issue for `LazyCell/Lock::get[_mut]()`, allowing you to extract a reference from a `Lazy` only if it is initialized, approved in ACP https://github.com/rust-lang/libs-team/issues/429.

### Public API
```rust
impl<T, F> core::cell::LazyCell<T, F> {
    pub fn get(this: &Self) -> Option<&T>;
    pub fn get_mut(this: &mut Self) -> Option<&mut T>;
    pub fn force_mut(this: &mut Self) -> &mut T;
}
impl<T, F> std::sync::LazyLock<T, F> {
    pub fn get(this: &Self) -> Option<&T>;
    pub fn get_mut(this: &mut Self) -> Option<&mut T>;
    pub fn force_mut(this: &mut Self) -> &mut T;
}
```

### Steps / History

- [x] ACP: https://github.com/rust-lang/libs-team/issues/429
- Implementation:
  - [ ] https://github.com/rust-lang/rust/pull/129334
  - [x] https://github.com/rust-lang/rust/pull/130476
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by jalil-salame** [comment]
The docs for `LazyLock::get[_mut]` are backwards:

`LazyLock::get`:
> Returns a mutable reference to the value if initialized, or None if not.

`LazyLock::get_mut`:
> Returns a reference to the value if initialized, or None if not.

The examples are right through.

**Comment by ChayimFriedman2** [comment]
@jalil-salame Why is that backwards? That seems correct to me.

**Comment by jalil-salame** [comment]
> @jalil-salame Why is that backwards? That seems correct to me.

Get should get a **reference** not a **mutable reference**

Get mut should get a **mutable reference** not a **reference**

**Comment by kornelski** [comment]
get/get_mut have been fixed. Can this be stabilized now?

**Comment by Amanieu** [comment]
FCP to stabilize `get`. `get_mut` and `force_mut`.

@rfcbot merge

**Comment by pthariensflame** [comment]
What happened to this one?

**Comment by darconeous** [comment]
What are the next steps for this?

**Comment by rust-rfcbot** [comment]
@Amanieu proposal cancelled.

**Comment by rust-rfcbot** [comment]
Team member @Amanieu has proposed to merge this. The next step is review by the rest of the tagged team members:


No concerns currently listed.

Once a majority of reviewers approve (and at most 2 approvals are outstanding), this will enter its final comment period. If you spot a major issue that hasn't been raised at any point in this process, please speak up!

See [this document](https://github.com/rust-lang/rfcbot-rs/blob/master/README.md) for info about what commands tagged team members can give me.

**Comment by rust-rfcbot** [comment]
The final comment period, with a disposition to **merge**, as per the [review above](https://github.com/rust-lang/rust/issues/129333#issuecomment-3368366763), is now **complete**.

As the automated representative of the governance process, I would like to thank the author for their work and everyone else who contributed.

This will be merged soon.

**Comment by darconeous** [comment]
Hmm. It's a little tricky because the existing behavior hasn't been altered, we've just added a new way to access the value that explicitly doesn't initialize. But I see what you mean.

Personally, I don't find the description to be confusing or significantly misleading, but if the consensus is to change it, perhaps a viable alternative would be "A value which is initialized on the first **dereference**."?

**Comment by pthariensflame** [comment]
> Hmm. It's a little tricky because the existing behavior hasn't been altered, we've just added a new way to access the value that explicitly doesn't initialize. But I see what you mean.
> 
> Personally, I don't find the description to be confusing or significantly misleading, but if the consensus is to change it, perhaps a viable alternative would be "A value which is initialized on the first **dereference**."?

How about "A value which is initialized on the first *forced access*, which can be accomplished by the `force` method or by dereferencing"?
