### ISSUE TITLE
Implement DST

### ISSUE THREAD

**Issue by nick29581** [rust-lang/rust#12938]
Tracking bug for implementing DST (I'll file issues for the intermediate steps).

@nick29581 to implement, @nikomatsakis to write an RFC for the RFC repo.

Nominating 1.0 (I think its already been discussed and agree that this blocks 1.0, if someone could tag this, it would be great).

Sub-bugs:
========

- [x] #12969: Add the unsized keyword 
- [x] #13120: Remove the `Sized` kind
- [x] #13121: Allow the last field of a struct to be a DST 
- [x] #13367: Remove hack around requiring `Sized` bound in collect.rs
- [x] #13376: Prevent storing and passing DST values
- [x] #13554: Refactor ty_vec, avoiding vstore
- [x] #13716: Implement coercion rules from `&[T, ..n]` to `&[T]`, etc.
- [x] #13819: Refactor ty_str, avoiding vstore (follow up (#13834) - remove size field from ty_str)
- [x] #12755: Coerce return values (needed for DST `&[T]` literals)
- [x] #14869: Refactor ty_trait, avoiding tstore
- [x] #15521 Implement syntax for unsized types. Currently `Sized?` looks like the favourite
- [x] #16805 fat raw pointers
- [x] #17178 unify [T] with U in type inference (needs refactoring a lot of the libs, and/or trait reform, see #16918) - turns out we *really* need this. Doing anything non-trivial with DST requires it. I had hoped we could get away without for a while but that does not seem to be the case.
- [x] #19187 DST: trait objects should automatically implement the trait

Tasks which don't yet have issues
===========================

- [x] Add fat pointers to trans
- [x] Indexing into fat pointer types in trans
- [x] remove all the hackey support for old behaviour (where we treat `&[T]` differently from `&([T])`)
- [x] structs
- [ ] recursive coercions (pointers in structs) - needs some design work (#18598, part of #18469)
- [x] strings (but can only be instantiated using transmute)
- [x] traits
- [x] use DST coercions for receiver when doing trait/method search (leaving this till post- NIko's cleanup of everything trait related, if we want to do it at all).
- [ ] properly deal with type aliases which are traits (i.e., accept them everywhere a trait is accepted). I don't actually think there is anything legitimate to do here - type = Trait... works and can be used anywhere a trait type could be used. It would be wrong to use a type, even an alias to a trait type where a trait is expected

**Comment by nick29581** [comment]
The only outstanding issue here is coercions which have their own issue and are tracked as part of the coercions RFC. Closing.
