### ISSUE TITLE
Tracking Issue for fixing of typos in `compiler` folder

### ISSUE THREAD

**Issue by Sajjon** [rust-lang/rust#129874]
This issue replaces PR https://github.com/rust-lang/rust/pull/129867/ and is used to track progress of three separate PRs ([as suggested by](https://github.com/rust-lang/rust/pull/129867/#issuecomment-2323796226) @fee1-dead) specifically:
- [x] [Batch 1](https://github.com/rust-lang/rust/pull/129875)
- [x] [Batch 2](https://github.com/rust-lang/rust/pull/129877)
- [x] [Batch 3](https://github.com/rust-lang/rust/pull/129878)
