### ISSUE TITLE
Tracking issue for RFC 3637: Guard patterns

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#129967]
This is a tracking issue for XXX.

The feature gate for the issue is `#![feature(guard_patterns)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Accept an RFC.
  - https://github.com/rust-lang/rfcs/pull/3637
- [ ] Implement in nightly.
- [ ] Add documentation to the [dev guide][].
  - See the [instructions][doc-guide].
- [ ] Add documentation to the [reference][].
  - See the [instructions][reference-instructions].
- [ ] Add formatting for new syntax to the [style guide][].
  - See the [nightly style procedure][].
- [ ] Stabilize.
  - See the [instructions][stabilization-instructions].

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[stabilization-instructions]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [ ] Should we allow mismatched bindings when possible in pattern disjunctions?
- [ ] How should we refer to "guard patterns"?

### Related

TODO.

**Comment by safinaskar** [comment]
Current wording of this RFC (3637) contradicts policy introduced in RFC 3531 ( https://rust-lang.github.io/rfcs/3531-macro-fragment-policy.html ). RFC 3637 says that old macro fragment specifier for patterns should be named `pat_no_top_guard`, but RFC 3531 says that it should be named something like `pat_2021`

**Comment by traviscross** [comment]
No, what's here is fine.  The policy says we use the edition number only when "no better semantically meaningful name could be found".
