### ISSUE TITLE
Tracking issue for RFC 3617 precise capturing of types

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#130043]
The feature gate for the issue is `#![feature(precise_capturing_of_types)]`.

This tracking issue covers extending the `precise_capturing` feature to allow for the partial capturing of type and const generic parameters.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Accept an RFC.
  - https://github.com/rust-lang/rfcs/pull/3617
- [ ] Stabilize precise capturing syntax and precise capturing of lifetimes.
  - https://github.com/rust-lang/rust/issues/123432
- [ ] Implement in nightly.
- [ ] Add documentation to the [dev guide][].
  - See the [instructions][doc-guide].
- [ ] Add documentation to the [reference][].
  - See the [instructions][reference-instructions].
- [ ] Add formatting for new syntax to the [style guide][].
  - See the [nightly style procedure][].
- [ ] Stabilize.
  - See the [instructions][stabilization-instructions].

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[stabilization-instructions]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

TODO.

### Related

TODO.

**Comment by nikomatsakis** [comment]
I had added an example in #130031 (which I closed in favor of this issue)

**Comment by workingjubilee** [comment]
Because I thought I was seeing double for a moment, for future reference, these two issues are related for obvious reasons, but currently...
- https://github.com/rust-lang/rust/issues/130043 <- YOU ARE HERE
- https://github.com/rust-lang/rust/issues/130044

**Comment by NeuralModder** [comment]
@traviscross I believe this tracking issue can be closed (since https://github.com/rust-lang/rust/pull/138128)?

**Comment by compiler-errors** [comment]
No, this functionality is still not implemented yet, and it will probably be a challenge to get it implemented correctly.

**Comment by NeuralModder** [comment]
Ah, apologies then. Guess the PR closing the other issue was only to deduplicate them...
