### ISSUE TITLE
Tracking issue for RFC 3617 precise capturing in traits

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#130044]
The feature gate for the issue is `#![feature(precise_capturing_in_traits)]`.

This tracking issue covers extending the `precise_capturing` feature to allow for the partial capturing of generic parameters within trait definitions.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Accept an RFC.
  - https://github.com/rust-lang/rfcs/pull/3617
- [x] Stabilize precise capturing syntax and precise capturing of lifetimes.
  - https://github.com/rust-lang/rust/issues/123432
- [x] Implement in nightly.
- [ ] Add documentation to the [dev guide][].
  - See the [instructions][doc-guide].
- [ ] Add documentation to the [reference][].
  - See the [instructions][reference-instructions].
- [ ] Add formatting for new syntax to the [style guide][].
  - See the [nightly style procedure][].
- [ ] Stabilize.
  - See the [instructions][stabilization-instructions].

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[stabilization-instructions]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

TODO.

### Implementation History

- https://github.com/rust-lang/rust/pull/131033
- https://github.com/rust-lang/rust/pull/132795

### Related

TODO.

cc @compiler-errors

**Comment by workingjubilee** [comment]
Because I thought I was seeing double for a moment, for future reference, these two issues are related for obvious reasons, but currently...
- https://github.com/rust-lang/rust/issues/130043
- https://github.com/rust-lang/rust/issues/130044 **<- YOU ARE HERE**

**Comment by ActuallyHappening** [comment]
What about this feature meant it was harder to stabilize than normal functions?
