### ISSUE TITLE
rustdoc: tracking issue for improved path handling

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#130358]
looking through old rustdoc issue, there's a common theme of wanting to display or act on an item's canonical path instead of just its name.

unfortunately, this information is not easily available to the librustdoc render logic.

* [ ] https://github.com/rust-lang/rust/issues/105307
* [ ] https://github.com/rust-lang/rust/issues/45260
* [ ] https://github.com/rust-lang/rust/issues/130189
* [ ] https://github.com/rust-lang/rust/issues/84367 (has more to do with canon names than paths, but still related)
