### ISSUE TITLE
Tracking Issue for generic `Atomic`

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#130539]
Feature gate: `#![feature(generic_atomic)]`

This is a tracking issue for replacing the distinct `Atomic*` types with a generic `Atomic<T>` type. This allows using `Atomic` with FFI type aliases and helps clean up some API surface.

### Public API

```rust
// core::sync::atomic

pub struct Atomic<T: AtomicPrimitive>(/* private fields*/);

pub type AtomicI32 = Atomic<i32>; // etc
```

### Steps / History

- [x] ACP: https://github.com/rust-lang/libs-team/issues/443
- [ ] Implement `Atomic<T>` as an alias to `AtomicT`
- [ ] Flip alias so `AtomicT` is an alias to `Atomic<T>`
- [ ] Move generic functionality from `AtomicT` to `Atomic<_>`
- [ ] Pseudo-prerequisite: Stabilize 128-bit atomics: https://github.com/rust-lang/rust/issues/99069
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- `Atomic<T>` is soft-blocked on 128-bit atomics, because since trait implementations cannot be unstable, gating `Atomic<i128>` separately from `Atomic<i32>` isn't possible.
  - If necessary, `AtomicI128` could instead name `Atomic<Wrapper<i128>>` for some unstable name `Wrapper` until 128-bit atomics are stable, to prevent `Atomic<i128>` from being usable from stable earlier than intended.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by cynecx** [comment]
Would/could this allow `Atomic<(*const (), u64)>?

**Comment by CAD97** [comment]
Not in the initial implementation tracked here, which does not aim to extend the set of types usable atomically yet. In the future, yes, this moves us into the direction of being able to support additional atomic types in the API.

**Comment by RalfJung** [comment]
From the ACP

> `impl<T> Unpin for Atomic<T> {}

This is suspicious, why does this not propagate the `Unpin`ness of `T`?

**Comment by CAD97** [comment]
> Why not propagate `Unpin`

In this case, because I was overly terse laying out the API in the ACP, apparently. Both the `NonZero` code I was basing general structure off of and my local sketch do actually bound the autotrait impls on `T: AutoTrait`.

But also,

- The initial set of allowed types are all `Unpin`.
- It seems fundamentally impossible to use the atomic load/store/swap API with pinned data.

**Comment by CAD97** [comment]
> other operations need a bit more design work (https://github.com/rust-lang/rust/pull/153407)

<details><summary>The shape of what I'm ultimately imagining</summary>

```rust
// SAFETY: Only implemented by core on types that can be used in the atomic intrinsics
// SAFETY: Only implemented when cfg(target_has_atomic_load_store) as necessary
// SAFETY: Self and Self::Aligned are value-transmute-equivalent
// SAFETY: &mut Self::Aligned can be cast to &mut Self
pub unsafe trait AtomicPrimitive: AtomicSwap<Atom=Self> + Copy + Sealed {
    type Aligned;
}

// Types that can be stored in Atomic<T>
// SAFETY: Self can be transmuted to Self::Atom
// SAFETY: Self values transmuted to Self::Atom can be transmuted back to Self
pub unsafe trait AtomicSwap: Sized {
    type Atom: AtomicPrimitive;
}

// SAFETY: Only implemented when cfg(target_has_atomic_equal_align) as necessary
// SAFETY: &mut Self can be cast to &mut Self::AtomicPrimitive::Aligned (modulo valid values)
// SAFETY: (align_of::<Self::AtomicPrimitive::Aligned>() <= align_of::<Self>())
pub unsafe trait AtomicFromMut: AtomicSwap {}

// SAFETY: &mut Self::AtomicPrimitive::Aligned can be cast to &mut Self (modulo valid values)
// SAFETY: (align_of::<Self>() <= align_of::<Self::AtomicPrimitive::Aligned>())
pub unsafe trait AtomicIntoMut: AtomicSwap {}

// SAFETY: Only implemented when cfg(target_has_atomic) as necessary
pub unsafe trait AtomicCas: AtomicSwap<Atom: AtomicCas> + Copy {}

// SAFETY: Self and Self::Atom are value-transmute-equivalent
// SAFETY: (all bit values are valid Self values, modulo provenance)
pub unsafe trait AtomicBitOps: AtomicCas<Atom: AtomicBitOps> {}

// Atomic<Self> has arithmetic fetch_op methods
pub trait AtomicIntOps: AtomicBitOps<Atom: AtomicIntOps> {}

// Atomic<Self> has pointer fetch_op methods
pub trait AtomicPtrOps: AtomicBitOps<Atom: AtomicPtrOps> {}

// NOTE: as written, bounds on Self::Atom are coinductive
// WORKAROUND: separate sealed AtomicOpsPrimitive traits, e.g.
unsafe trait AtomicCasPrimitive = AtomicPrimitive {}
unsafe impl<T> AtomicCasPrimitive for T
where T: AtomicPrimitive + AtomicCas {}

#[repr(transparent)]
pub struct Atomic<T: AtomicSwap>(UnsafeCell<<T::Atom as AtomicPrimitive>::Aligned>);

impl<T: AtomicSwap> Atomic<T> {
    pub const fn new(v: T) -> Self;
    pub const fn into_inner(self) -> T;
    pub const unsafe fn from_ptr(ptr: *mut T) -> &'a Self;
    pub const fn as_ptr(&self) -> *mut T;
}

impl<T: AtomicIntoMut> Atomic<T> {
    pub const fn get_mut(&mut self) -> &mut T;
    pub const fn get_mut_slice(&this: &mut [Self]) -> &mut [T];
}

impl<T: AtomicFromMut> Atomic<T> {
    pub const fn from_mut(v: &mut T) -> &mut Self;
    pub const fn from_mut_slice(v: &mut [T]) -> &mut [Self];
}

impl<T: AtomicSwap> Atomic<T> {
    pub fn load(&self, order: Ordering) -> T where T: Copy;
    pub fn store(&self, v: T, order: Ordering) where T: Copy;
    pub fn swap(&self, v: T, order: Ordering) -> T;
}

impl<T: AtomicCas> Atomic<T> {
    pub fn compare_exchange(&self, current: T, new: T, success: Ordering, failure: Ordering) -> Result<T, T>;
    pub fn compare_exchange_weak(&self, current: T, new: T, success: Ordering, failure: Ordering) -> Result<T, T>;
    pub fn try_update(&self, set_order: Ordering, fetch_order: Ordering, f: impl FnMut(T) -> Option<T>) -> Result<T, T>;
    pub fn update(&self, set_order: Ordering, fetch_order: Ordering, f: impl FnMut(T) -> T) -> Result<T, T>;
}

impl<T: AtomicBitOps> Atomic<T> {
    pub fn fetch_and(&self, v: T, order: Ordering) -> T;
    pub fn fetch_nand(&self, v: T, order: Ordering) -> T;
    pub fn fetch_or(&self, v: T, order: Ordering) -> T;
    pub fn fetch_xor(&self, v: T, order: Ordering) -> T;
    pub fn fetch_not(&self, v: T, order: Ordering) -> T;
}

impl<T: AtomicIntOps> Atomic<T> {
    pub fn fetch_add(&self, v: T, order: Ordering) -> T;
    pub fn fetch_sub(&self, v: T, order: Ordering) -> T;
    pub fn fetch_max(&self, v: T, order: Ordering) -> T;
    pub fn fetch_min(&self, v: T, order: Ordering) -> T;
}

impl<T: AtomicPtrOps> Atomic<T> {
    pub fn fetch_ptr_add(&self, v: usize, order: Ordering) -> T;
    pub fn fetch_ptr_sub(&self, v: usize, order: Ordering) -> T;
    pub fn fetch_byte_add(&self, v: usize, order: Ordering) -> T;
    pub fn fetch_byte_sub(&self, v: usize, order: Ordering) -> T;
    // maybe specialize AtomicBitOps for provenance documentation
}
```

</details>

> Can we use this as an opportunity to require that `Ordering` be provided as a const parameter?

That requires `Ordering: ConstParamTy` at a minimum, and personally I don't think it's really worth it if it's going to make `Atomic<T>` not the same type as `AtomicT`, and the hacks I can think of to bodge name resolution don't feel good either.
