### ISSUE TITLE
Tracking Issue for mergeable rustdoc cross-crate info

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#130676]
This is a tracking issue for the RFC "3662" (rust-lang/rfcs#3662).

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [x] Implement the RFC (#129337)
- [ ] Add documentation (to Rustdoc Book) -- cc @EtomicBomb
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [ ] Consider removing `--merge=shared` and only allow it by not providing a `--merge` flag. This would allow removing the implementation of shared CCI later, once Cargo uses mergeable CCI. https://github.com/rust-lang/rfcs/pull/3662#discussion_r1735147546

### Implementation history

- #129337
- #128252
- #128161

**Comment by csmulhern** [comment]
Looks like the RFC is implemented and the documentation update is merged. Is this ready for a stabilization PR?

**Comment by weihanglo** [comment]
> `@rust-lang/cargo` is the current design good enough for your team as well? Rustdoc is planning to stabilize it so we'd like to confirm with you it's ok before doing so.

@GuillaumeGomez this is my little wish, not a blocker

* https://github.com/rust-lang/rust/issues/83784#issuecomment-3572830043

**Comment by camelid** [comment]
We should see if there is some way to automatically run our rustdoc-html testsuite on both legacy-shared CCI and mergeable CCI.
