### ISSUE TITLE
Tracking issue for removing unnecessary `ty::Const::{normalize,eval}` calls from the type system

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#130704]
We want to remove calls to `ty::Const::{normalize,eval,eval_to_*}` because they won't work correctly with future reformulations of GCE, and because they're unnecessary with non-GCE consts. This issue tracks doing that so I won't forget. Boxy can probably write more motivation here idk

- [x] Remove eval calls from codegen (#130644)
    - [ ] Replace calls to `eval_bits` with `try_to_bits`, which I forgot in codegen lol
- [x] Normalize writeback results (#130645)
    - [ ] Replace calls to `eval` from `mir_build` and `pattern_analysis` in now that writeback results are normalized
- [ ] Add `structurally_resolve_const` for use in `FnCtxt`/`hir_typeck`
    - [ ] Replace calls to `eval_*` with `structurally_resolve` + `try_to_*` in hir typeck
- [ ] Audit remaining calls to `eva;/normalize` post-borrowck, replacing them with their `try_to_*` variants + possibly normalizing depending on the source of the const.

cc @BoxyUwU

**Comment by RalfJung** [comment]
> and because they're unnecessary with non-GCE consts

Are they? The role of `ty::Const::normalize` is to bring this constant into the shape `ConstKind::Value` where possible. This is entirely orthogonal to GCE.

**Comment by RalfJung** [comment]
As a meta remark here, I think @rust-lang/wg-const-eval should generally be kept in the loop when t-types is fundamentally changing the API of `ty::Const`, as that API is clearly in the responsibility of both teams/groups. :)

In particular, we did a bunch of work to make that API somewhat consistent with `mir::Const`, for good reasons. (Type systems consts can be used as MIR values, so every operation on `mir::Const` has to be supported by `ty::Const`.)

**Comment by BoxyUwU** [comment]
Nothing is fundamentally changing about being able to normalize type system constants, this has zero impact on const evaluation.

**Comment by RalfJung** [comment]
I didn't say any functionality was being removed. Just APIs are being (re)moved, for what I assume are good reasons. But surely const-eval needs to understand why this is done. You can't say that the `ty::Const` API is not relevant for wg-**const**-eval...

**Comment by BoxyUwU** [comment]
I am absolutely saying that in this case it has nothing to do with this group. Nothing has fundamentally changed with this refactoring, it has no impact on const eval whatsoever. This is primarily a focus about how the API should be structured for normalizing type system constants *not* any of the actual const eval logic. 

If we were introducing new constraints on how ctfe must work for const generics or what circumstances ctfe must be able to run in then sure wg-const-eval should be included. But this refactoring does not affect const eval/ctfe in any real way.

**Comment by fee1-dead** [comment]
Both of you may be interested in moving extended discussion into a Zulip topic :)
