### ISSUE TITLE
Tracking issue for rename of traits from "object safe" to "dyn compatibie"

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#130852]
This is a tracking issue for the change to call traits that are compatible with `dyn` from "object safe" to "dyn compatible".

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Decide to do this.
  - https://github.com/rust-lang/lang-team/issues/286
- [ ] Update rustdoc.
  - https://github.com/rust-lang/rust/pull/126554
- [ ] Update the compiler.
  - https://github.com/rust-lang/rust/pull/130826
- [ ] Update the standard library.
  - https://github.com/rust-lang/rust/pull/130827
- [ ] Update the Reference.
  - https://github.com/rust-lang/reference/pull/1512
- [ ] Update the dev guide.

cc @rust-lang/lang @fmease

**Comment by fmease** [comment]
Changes to the compiler & the libraries will be included in 1.83.
Changes to the Reference & rustdoc will be included in 1.84.

**Comment by fmease** [comment]
I'll close this as completed. Three of the four unaddressed bullet points concern 7 tests in total (belonging to Miri / codegen_{gcc,cranelift}) and I can't be bothered to update them.  

Postmortem: I failed to add this change to the release notes which is super unfortunate. Part of the reason was the fact that a beta bump occurred in the middle of updating the world (it was quite a lot). I could've maybe nominated some renames for a backport back then which I didn't do. Later, we agreed not to add it to the relnotes of 1.83 and I missed to add it to the ones of 1.84.

---

If anyone is curious, throughout the migration I used the following regex: `obj(ect)?[ _-]?(un)?safe(ty)?`.
