### ISSUE TITLE
Tracking Issue for default-visibility

### ISSUE THREAD

**Issue by davidlattimore** [rust-lang/rust#131090]
This is a tracking issue for `default-visibility`, which allows setting the visibility of symbols when building a shared object / dylib.

MCP: https://github.com/rust-lang/compiler-team/issues/782

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [ ] Implement the flag as `-Z default-visibility`
- [ ] Stabilize as `-C default-visibility`

### Unresolved Questions

- [ ] Are we happy with the naming of the flag and its options?
- [ ] What should the default be?

### Implementation history

* https://github.com/rust-lang/rust/pull/130005

**Comment by weihanglo** [comment]
Do people know about the status of this feature, or are we waiting for [RFC 3834](https://rust-lang.github.io/rfcs/3834-export-visibility.html) to move forward?

**Comment by bjorn3** [comment]
There was a binutils bug until somewhat affecting non-default visibilities: https://github.com/rust-lang/rust/issues/105518#issuecomment-2313680228

**Comment by ZuseZ4** [comment]
I answered in the zulip discussion: [#t-compiler > &#96;-Zdefault-visibility&#96; @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/.60-Zdefault-visibility.60/near/601905515)
