### ISSUE TITLE
Tracking issue for RFC 3678: Trait method impl restrictions (`final` methods)

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#131179]
This is a tracking issue for RFC 3678: Trait method impl restrictions (`final` methods).

The feature gate for the issue is `#![feature(final)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Approve as lang experiment.
  - (Approved implicitly given the circumstances.)
- [x] Accept an RFC.
  - https://github.com/rust-lang/rfcs/pull/3678
- [ ] Implement in nightly.
  - Previous implementation PR, for reference: https://github.com/rust-lang/rust/pull/130802
  - Needs an implementation.
- [ ] Add documentation to the [dev guide][].
  - See the [instructions][doc-guide].
- [ ] Add documentation to the [reference][].
  - See the [instructions][reference-instructions].
- [ ] Add formatting for new syntax to the [style guide][].
  - See the [nightly style procedure][].
- [ ] Stabilize.
  - See the [instructions][stabilization-instructions].

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[stabilization-instructions]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

TODO.

### Related

TODO.
