### ISSUE TITLE
Tracking issue for RFC 3695: Allow boolean literals as cfg predicates

### ISSUE THREAD

**Issue by clubby789** [rust-lang/rust#131204]
This is a tracking issue for the RFC "Allow boolean literals as cfg predicates" ([rust-lang/rfcs/#3695](https://github.com/rust-lang/rfcs/pull/3695)).
The feature gate for the issue is `#![feature(cfg_boolean_literals)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [x] Accept an RFC.
  - https://github.com/rust-lang/rfcs/pull/3695
- [x] Implement in nightly.
  - https://github.com/rust-lang/rust/pull/131034
- [ ] Add documentation to the [reference][].
  - https://github.com/rust-lang/reference/pull/1762
- [ ] Stabilize.
  - https://github.com/rust-lang/rust/pull/138632

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[stabilization-instructions]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Related

- https://github.com/rust-lang/rust/pull/131034
- https://github.com/rust-lang/cargo/pull/14649

**Comment by Urgau** [comment]
## Call for testing

This is call for testing regarding [RFC3695: Allow boolean literals as cfg predicates](https://github.com/rust-lang/rfcs/pull/3695).

RFC 3695 adds support for `true` & `false` in `#[cfg]`, `#[cfg_attr]` and `cfg!` predicates.

### Testing instructions

Requires: `nightly-2024-10-06` or newer with [`feature(cfg_boolean_literals)`](https://doc.rust-lang.org/nightly/unstable-book/language-features/cfg-boolean-literals.html).

 - Use `#[cfg(true)]`, `#[cfg(false)]` with (or without) `any`/`all`/`not`. 

### Feedback

 - Did the feature work as expected?
 - Were there surprising results?

@rustbot label +call-for-testing

**Comment by U007D** [comment]
Hi.  This will appear in This Week in Rust issue #581 under "Call for Testing".  You may remove the `call-for-testing` label, or retain it (in which case it will appear again in the following issue of TWiR).

**Comment by clubby789** [comment]
With a quick review:
- `#[cfg(true)]`, `#[cfg(false)]` and variants (`all`/`any`/`not`) work as expected
- Same for `cfg_attr`s
- `cfg!(true)` and `cfg!(false)` work
- `r#true` and `r#false` are also unchanged as specified:
```rs
[poc.rs:4:5] cfg!(true) = true
[poc.rs:5:5] cfg!(false) = false
[poc.rs:6:5] cfg!(r#true) = false
[poc.rs:7:5] cfg!(r#false) = false
```

**Comment by U007D** [comment]
Hi. This will appear in This Week in Rust issue 582 under "Call for Testing". You may remove the call-for-testing label.

**Comment by joshtriplett** [comment]
Works well here, behaving exactly as expected.

**Comment by clubby789** [comment]
# Stabilization Report

## General design

### What is the RFC for this feature and what changes have occurred to the user-facing design since the RFC was finalized?

[RFC 3695](https://github.com/rust-lang/rfcs/pull/3695), none.

### What behavior are we committing to that has been controversial? Summarize the major arguments pro/con.

None

### Are there extensions to this feature that remain unstable? How do we know that we are not accidentally committing to those?

None

## Has a call-for-testing period been conducted? If so, what feedback was received?

Yes; only positive feedback was received.

## Implementation quality

### Summarize the major parts of the implementation and provide links into the code (or to PRs)

Implemented in [#131034](https://github.com/rust-lang/rust/pull/131034).

### Summarize existing test coverage of this feature

Typical use cases including various cfg predicate combinations are tested. Interaction with `#[doc(cfg(..))]` is also tested (but is not properly gated until [#138293](https://github.com/rust-lang/rust/pull/138293) lands.)

### What outstanding bugs in the issue tracker involve this feature? Are they stabilization-blocking?

The above mentioned issue; it should not block as it interacts with another unstable feature.

### What FIXMEs are still in the code for that feature and why is it ok to leave them there?

None

### Summarize contributors to the feature by name for recognition and assuredness that people involved in the feature agree with stabilization 
- @clubby789 (RFC)
- @Urgau (Implementation in rustc)

### Which tools need to be adjusted to support this feature. Has this work been done?

`rustdoc`'s  unstable`#[doc(cfg(..)]` has been updated to respect it. `cargo` has been updated with a forward compatibility lint to enable supporting it in cargo once stabilized.

## Type system and execution rules

### What updates are needed to the reference/specification? (link to PRs when they exist)

A few lines to be added to the reference for configuration predicates, specified in the RFC.

**Comment by joshtriplett** [comment]
Reference update at https://github.com/rust-lang/reference/pull/1762 .

**Comment by traviscross** [comment]
@rfcbot cancel

@clubby789: We put our stabilization reports, and do our stabilization FCPs on stabilization PRs.  If you could please put up a [stabilization PR](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html?highlight=stabil#stabilization-pr) for this and nominate it for us (`@rustbot labels +T-lang +I-lang-nominated`), we'll review and do an FCP on that PR.  Thanks for your work on this.

**Comment by clubby789** [comment]
#138632
