### ISSUE TITLE
Tracking Issue for minicore (core prelude stubs test auxiliary)

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#131485]
### Context

We have a bunch of `#![no_core]` ui/codegen/assembly tests that roll their own `core` prelude stubs because they need to build (but not run) on a cross-compiled target. But this means:

- A bunch of duplicated implementations of `core` prelude stubs scattered in different tests.
- A heavy burden on a contributor of possibly having to update *many* tests if a new *required* lang item wants to be added.
- Prelude stubs can obfuscate the intent of the test (more things that the reader has to read and mentally filter out).

Instead of continuing to add more copies of `core` prelude stubs, let's centralize such `core` prelude stubs into a shared test auxiliary called `minicore`. `minicore` is for `core` prelude stubs specifically. `std` prelude which can include `liballoc` items and such is beyond the scope of `minicore`, because `core` is usable by more tests. This does not preclude adding another `ministd` or `minialloc` for stubs of `std`/`liballoc` respectively.

See https://github.com/rust-lang/rust/issues/130375 for more discussions.

### Steps

- [x] 1. Open an MCP to add `minicore` test auxiliary.
    - MCP is accepted: https://github.com/rust-lang/compiler-team/issues/786
    - Note that the MCP title specified std/core prelude stubs, but we revised the scope to `core` stubs only.
- [x] 2. Implement initial test infra support for `minicore`.
    - https://github.com/rust-lang/rust/pull/130693 
- [x] 3. Adjust rustc-dev-guide docs.
    - https://github.com/rust-lang/rustc-dev-guide/pull/2097 
- [x] 4. ~~Figure out the logistics on how to absorb `core` stubs into `minicore`, then use `minicore` to simplify existing `#![no_core]` tests.~~
    - Currently, I think it's better to just have the infra in place to allow newer and changed tests to use `minicore.rs`, it seems like unnecessary churn to also force existing tests to use `minicore.rs` atm.

### Unresolved questions

- What do we do with existing `#![no_core]` tests that could benefit from `minicore`?

**Comment by RalfJung** [comment]
Thanks a lot for adding this! I only now finally got around to play with it, and it seems to work great. :)

I admit I am a bit confused by the naming -- it's called "core-stubs" but then the import is called "minicore". Are these two 
different things, or are we using two different names to refer to the same thing?

**Comment by jieyouxu** [comment]
> Thanks a lot for adding this! I only now finally got around to play with it, and it seems to work great. :)
> 
> I admit I am a bit confused by the naming -- it's called "core-stubs" but then the import is called "minicore". Are these two different things, or are we using two different names to refer to the same thing?

So... I am not very good with naming things, what happened was:

- Initially, the test auxiliary file was called `minicore.rs`, and the directive was called `//@ use-minicore`.
- This was discussed during a [compiler triage meeting](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-10-17/near/477455125), was suggested to rename it `//@ add-core-stubs` for ppl who don't know what a "minicore" is. I don't really have a strong opinion on the *exact* directive name, so I went with that lol.

There really isn't any strong reasoning here 😆

**Comment by jieyouxu** [comment]
Also I should close this specific tracking issue as it has served its purpose, specific bugs/enchancements should probably be in their separate issues.

**Comment by jieyouxu** [comment]
For easier search purposes, there *is* a drawback to the current implementation in that it's possible for actual `library/core` definitions to diverge from `minicore`. This is tracked in https://github.com/rust-lang/rust/issues/134652, where ideally we'd able to use *host* "real" core when available, and only the "minicore" stubs on cross. Even better, is if somehow

> maybe `minicore` could be a file or module within `library/core` that can be built as a standalone crate. Then compiletest would use this directly and the real `core` just reexports things in the right place, so we'll always be using the same API regardless of whether or not all of `core` is available.

as mentioned in https://github.com/rust-lang/rust/issues/134652#issuecomment-2558625648.

**Comment by jieyouxu** [comment]
> Is there an issue tracking "port all the existing tests to minicore" or is that not planned?

I considered this. However, I felt like

> Currently, I think it's better to just have the infra in place to allow newer and changed tests to use `minicore.rs`, it seems like unnecessary churn to also force existing tests to use `minicore.rs` atm.

**Comment by RalfJung** [comment]
Yeah fair.
