### ISSUE TITLE
Tracking issue for Rust 2024: Match ergonomics rules 1C/2C

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#131414]
This is a tracking issue for reserving space in match ergonomics in Rust 2024 for RFC 3627 and other proposals for the future of match ergonomics.

### Rules

- Rule 1C: When the DBM (default binding mode) is not `move` (whether or not behind a reference), writing `mut`, `ref`, or `ref mut` on a binding is an error.
- Rule 2C: Reference patterns can only match against references in the scrutinee when the DBM is `move`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024 w/migration lints.
  - https://github.com/rust-lang/rust/pull/123080
  - https://github.com/rust-lang/rust/pull/123512
  - https://github.com/rust-lang/rust/pull/124567
  - https://github.com/rust-lang/rust/pull/123535
  - https://github.com/rust-lang/rust/pull/124639
- [x] Stabilize in Rust 2024.
  - https://github.com/rust-lang/rust/pull/131381
- [x] Add documentation to the [reference][].
  - https://github.com/rust-lang/reference/pull/1702
- [x] Add documentation to the [edition guide][].
  - https://github.com/rust-lang/edition-guide/pull/349
- [x] Update the `reference` field of the `rust_2024_incompatible_pat` lint definition to point to the edition guide.
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

Tracking for broader RFC 3627 work:

- https://github.com/rust-lang/rust/issues/123076

**Comment by traviscross** [comment]
@rustbot labels -S-tracking-needs-documentation +S-tracking-ready-for-edition

This item is **ready** for Rust 2024.

Thanks to @Jules-Bertholet, @Nadrieril, and the various reviewers for making this happen.
