### ISSUE TITLE
Tracking Issue for GPU-offload

### ISSUE THREAD

**Issue by ZuseZ4** [rust-lang/rust#131513]
This is a tracking issue for the GPU offload experiment.

The feature gate for the issue will be `#![feature(gpu_offload)]`.

This work is part of the [project goal](https://rust-lang.github.io/rust-project-goals/2024h2/Rust-for-SciComp.html) for Scientific Computing in Rust.
This project will use LLVM's offload infrastructure, which is already used to support OpenMP Offload in other languages like C++.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [x] Get lang experiment approved.
    - We approved this in the lang triage meeting on 2024-05-01.
- [ ] Land the experimental implementation in nightly. 
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions
TODO.
