### ISSUE TITLE
Tracking issue for wasm32-emscripten ui test failures

### ISSUE THREAD

**Issue by hoodmane** [rust-lang/rust#131738]
- [ ] `abi/numbers-arithmetic/return-float.rs` (possible problem with [wasm treatment of noncanonical floats](https://webassembly.github.io/spec/core/exec/numerics.html#nan-propagation)?)

- [ ] `async-await/issue-60709.rs` -- [Emscripten bug](https://github.com/emscripten-core/emscripten/issues/22742) that occurs when `-lc` and `-Oz` are passed to the linker, can be reproduced with 
  ```sh
  echo "fn main(){}" > a.rs
  rustc -Copt-level=z a.rs -o a.js --target=wasm32-unknown-emscripten
  ```
- [ ] backtrace/dylib-dep.rs -- Says "Not supported"
- [ ] backtrace/line-tables-only.rs -- Says "Not supported"
- [ ] no_std/no-std-unwind-binary.rs -- compiler says error: lang item required, but not found: eh_catch_typeinfo
- [ ] structs-enums/enum-rec/issue-17431-6.rs -- One of the two compiler errors is missing
- [ ] test-attrs/test-passed.rs
