### ISSUE TITLE
Tracking Issue for `download-rustc` improvements

### ISSUE THREAD

**Issue by onur-ozkan** [rust-lang/rust#131744]
These changes are necessary to make `download-rustc` more stable and less risky:

- [x] Based on [this](https://github.com/rust-lang/rust/issues/131658) idea from @RalfJung, instead of checking specific directories to see if they have changed, check for any changes outside of certain allowed directories. This is more maintainable over time because the current approach requires constantly updating [hard-coded denied paths](https://github.com/rust-lang/rust/blob/f79fae3069c449993eda6b16934da3b144cb8a66/src/bootstrap/src/core/config/config.rs#L2751-L2757).
- [x] When not running in CI, if the "library" tree has changed but the "compiler" tree hasn't, avoid recompiling the "compiler" tree. This approach is similar to [how `download-rustc=true` handles library changes](https://github.com/rust-lang/rust/blob/f79fae3069c449993eda6b16934da3b144cb8a66/src/bootstrap/src/core/build_steps/compile.rs#L125-L144). The goal is to make `if-unchanged` useful for library developers as well.
- [x] Once above is done, make `download-rustc=if-unchanged` default option for the "library" profile.
- [x] https://github.com/rust-lang/rust/issues/131947

**Comment by RalfJung** [comment]
> When not running in CI, if the "library" tree has changed but the "compiler" tree hasn't, avoid recompiling the "compiler" tree. 

Isn't this premature? We can do this once the compiler uses the beta library, because then the `library` folder truly does not affect the stage 0 compiler artifacts. But today, `library` *is* an input to the stage 0 compiler artifacts. Also today, library developers can do `./x.py test --stage 0 library/..` so they can already avoid building the compiler.

**Comment by onur-ozkan** [comment]
Yeah I forgot mentioning https://github.com/rust-lang/rust/pull/119899.
