### ISSUE TITLE
Tracking Issue for `-Zregparm`

### ISSUE THREAD

**Issue by azhogin** [rust-lang/rust#131749]
This is a tracking issue for the `-Zregparm` flag for x86. It is the equivalent of Clang's/GCC's `-mregparm=3`. The kernel needs it to support the x86 32-bit architecture, together with [`-Zreg-struct-return`](https://github.com/rust-lang/rust/issues/116973).

It could potentially be a ["global target feature"](https://github.com/rust-lang/rust/issues/121970#issuecomment-1978605782), i.e. a target feature that is required to be set the same way for all compilation units.

- https://gcc.gnu.org/onlinedocs/gcc/x86-Function-Attributes.html#index-regparm-function-attribute_002c-x86
- https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-mregparm

### About tracking issues
Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [x] Implementation:
    - https://github.com/rust-lang/rust/pull/130432
- [ ] Adjust documentation ([see instructions on rustc-dev-guide](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs))
- [ ] Stabilization PR ([see instructions on rustc-dev-guide](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr))

### Unresolved Questions & Answers
- [ ] Q: Should it affect the Rust ABI? It cannot be documented as doing such, because the Rust ABI is unstable, but should it do so anyways as a quality-of-implementation matter?
     - **Currently**: No.
     - **Alternatives**:
         - Maybe yes?
         - Maybe we want to have a modification equivalent to `"fastcall"` or `-Zregparm=3` apply to the Rust ABI implicitly, without `-Zregparm` affecting it?
- [ ] Q: Should it affect *any* other ABIs than `"C"`, `"cdecl"`, and `"stdcall"`?
     - **Currently**: No.
     - **Alternatives**: It's not yet clear what ABIs this affects for gcc and clang.
- [ ] Q: Should it be accepted on any other architecture than x86_32?
     - **Currently**: No.
- [ ] Q: Does MSVC code use this? `extern "fastcall"` does something equivalent to `-Zregparm=2`, so do MSVC targets even use it, or do they just use `fastcall`?

**Comment by tgross35** [comment]
@rustbot label +I-lang-nominated

This feature is not ready for stabilization yet, but I'd like to get a vibe check on what I proposed in the above comment since it is novel.

I can add more details if needed but basically what I'm proposing is:

1. A mental model that flags like `-Zregparm=n` and `-Zreg-struct-return` create a new ABI based on `cdecl`
2. That ABI is nameable, something like `cdecl+regparm(3)+reg-struct-return` (bikeshedable)
3. We allow users to change what `extern "C"` means to a restricted set of other ABIs via compiler flag, including some `regparm` and `reg-struct-return` variants.
4. With this, we don’t need the `-Zregparm` and `-Zreg-struct-return` flags. 

The C compilers also have an attribute:

```c
// I couldn't find a reg-struct-return attribute
__attribute__((regparm(3))) void pass_regparm(int x, int *p) {
    *p = x;
}
```

https://gcc.godbolt.org/z/49fvf1dTr

If we ever wanted to support this, I think the ABI strings would work nicely here:

```rust
extern "cdecl+regparm(3)" fn pass_regparm(x: i32, p: &mut i32) {
    *p = x;
}
```

Which would also extend to things like function pointer types nicer than a `#[regparm(3)]` attribute.

**Comment by RalfJung** [comment]
> Regarding the unresolved questions, is there any prior art for regparm being used with stdcall? I'm imagining most Windows-oriented cases that may need something like regparm are just using fastcall or thiscall instead, so I would be a bit hesitant to stabilize stdcall+regparm and effectively invent a stable ABI that isn't used anywhere else.

Cc @ChrisDenton

**Comment by ChrisDenton** [comment]
I'm not aware of MSVC's `cl.exe` supporting anything equivalent to this (other than, as noted, using an entirely different function call ABI).

@rustbot ping windows

**Comment by dpaoliello** [comment]
There's no equivalent to `regparam` in MSVC. Even `__fastcall` is quite different since it is callee-pop whereas `regparam` is caller-pop.

There's also no way to express this in MSVC. You can't do custom calling conventions other than manually setting up the stack then calling a `__declspec(naked)` function.

MSVC does let you choose the default calling convention via [various `/G` flags](https://learn.microsoft.com/en-us/cpp/build/reference/gd-gr-gv-gz-calling-convention?view=msvc-170), but it's a fixed list.

My opinion: I'd rather avoid having `regparam` on Windows (or for the MSVC envs), since MSVC generated code can't interact with it. But I would love `-Cdefault-c-abi=` as there are various parts of Windows that switch the default calling convention, but that may require coordination with windows-rs as I'm not sure what it assumes (@kennykerr ?)

**Comment by kennykerr** [comment]
Yes, we are limited by what can be practically expressed with MSVC.

Daniel, `windows-rs` now produces its own metadata for Windows APIs directly from headers using libclang so I think we could handle this if needed.

**Comment by dpaoliello** [comment]
I was more worried about `-Cdefault-c-abi=` - does windows-rs ever generate `extern "C"` for x86? Or is it always `extern "system"`, `extern "cdecl"`, etc.

**Comment by kennykerr** [comment]
Oh there's around 1500 functions that assume `extern "C"` but it uses this to mean `cdecl` - I think rustc has/had some issue with `cdecl` in all cases and only "C" worked for all targets.

**Comment by RalfJung** [comment]
"cdecl" is an x86-32 ABI so doesn't really make sense on other targets.

**Comment by retep998** [comment]
I'm in the camp of simply do not allow `-Zregparm` on Windows. There's no existing known need for it, and there's no precedent with any MSVC feature to do the same. Better to simply not allow it, and not have to answer any questions about how it would work. Also the safest option because it always leaves the door open to enabling it in the future if it turns out there is in fact a good use case.
