### ISSUE TITLE
Figure out which target features are required for which SIMD size

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#131800]
The context for this is https://github.com/rust-lang/rust/issues/116558: passing vector types by-value over `extern "C"` needs certain registers to be present, so if the target feature enabling these registers is missing, then either the ABI needs to change (which can lead to soundness issues if caller and callee disagree on their target features), or LLVM just errors outright.

https://github.com/rust-lang/rust/issues/127731 moves us towards detecting this situation, but that approach needs data about which target feature is needed to pass which vector size. That will be different for each architecture. So this issue is about gathering all that data.

- [x] x86 (32bit and 64bit)
  - "sse" => vlen(128)
  - "avx" => vlen(256)
  - "avx512f", "evex512" => vlen(512)
  - "amx-tile" => ??? ( matrix type, needs investigation, see https://github.com/rust-lang/rust/issues/126622 )
- [x] arm
  - "neon" | "mve" => vlen(128)
- [x] aarch64:
  - "neon" => vlen(128)
  - "sve" => ["it's complicated"](https://github.com/rust-lang/rust/issues/131800#issuecomment-2426934201)
- [x] powerpc
  - "altivec" => vlen(128)
  - "mma" => vlen(512), NOTE: not supported by clang
- [x] riscv
  - "zve32x" | "zve32f" => vlen(32),
  - "zve64x" | "zve64f" | "zve64d" => vlen(64),
  - "zvl128b" | "v" => vlen(128)
  - "zvl{N}b" => "it's complicated"
- [x] wasm: "simd128" => vlen(128)
- [x] loongarch: should have an on-stack ABI
- [x] s390x: "vector" => vlen(128)
- [x] sparc: "vis" => vlen(64) (or more? [hard to say](https://github.com/rust-lang/rust/issues/131800#issuecomment-2473871620))
- [x] hexagon
  - "hvx-length64b" => vlen(512)
  - "hvx-length128b" => vlen(1024)
- [x] mips and mips*r6: "msa" => vlen(128)
- [x] nvptx: vlen(128)
- [x] bpf: none
- [x] csky: "vdspv1" | "vdspv2" => vlen(128),
- [ ] m68k
- [ ] more?

**Comment by workingjubilee** [comment]
cc @programmerjake to confirm what features are relevant re: PowerPC

**Comment by workingjubilee** [comment]
- arm: I think we can rip most of this out of https://github.com/rust-lang/rust/pull/130987 
- csky: cc @Dirreke re: target-features that affect vector ABIs?
- loongarch: cc @heiher re: target-features that affect vector ABIs?
- riscv: cc @kito-cheng or @topperc to confirm for LLVM features that can affect the vector ABI?
- s390x: this got a nice nice writeup recently in https://github.com/rust-lang/rust/issues/130869#issuecomment-2407689780

**Comment by programmerjake** [comment]
`+altivec` enables 128-bit vectors, I'm not sure if there are any wider types -- there's MMA with 512-bit accumulators, but idk if they are vector types, they're used for matrix ops.

**Comment by topperc** [comment]
>riscv: cc @kito-cheng or @topperc to confirm for LLVM features that can affect the vector ABI?

+zve32x, +zve32f, +zve64x, +zve64f, +zve64d, +v, +zvbb, +zvkb. There several others that start with +zv*. There is an implies relationship so they all ultimately imply +zve32x. These change the ABI for fixed length vector arguments/returns in IR in the backend.

When compiling with clang with the default C ABI, fixed length vectors are passed coerced to a scalar integer type or passed indirectly through memory. clang will not create fixed length vector return types or arguments in IR.

There is a fixed length vector ABI being implemented via an attribute https://github.com/llvm/llvm-project/pull/100346. This changes how fixed length vectors are passed.

**Comment by programmerjake** [comment]
vsx just enables an additional 32 registers that overlap with the scalar floating point registers but are otherwise the same as the 32 128-bit registers from vmx (aka. altivec), so no new simd bitwidths.

**Comment by workingjubilee** [comment]
@programmerjake and no alterations to the calling convention?

**Comment by workingjubilee** [comment]
@topperc hm, it seems LLVM doesn't have the crypto implications for these features specified here? is it somewhere else? https://github.com/llvm/llvm-project/blob/d54953ef472bfd8d4b503aae7682aa76c49f8cc0/llvm/lib/Target/RISCV/RISCVFeatures.td#L734-L746

it seems to rather be the opposite, a requirement relationship, but perhaps I'm misunderstanding: https://github.com/llvm/llvm-project/blob/d54953ef472bfd8d4b503aae7682aa76c49f8cc0/llvm/lib/TargetParser/RISCVISAInfo.cpp#L754-L758

**Comment by topperc** [comment]
> [@topperc](https://github.com/topperc) hm, it seems LLVM doesn't have the crypto implications for these features specified here? is it somewhere else? https://github.com/llvm/llvm-project/blob/d54953ef472bfd8d4b503aae7682aa76c49f8cc0/llvm/lib/Target/RISCV/RISCVFeatures.td#L734-L746
> 
> it seems to rather be the opposite, a requirement relationship, but perhaps I'm misunderstanding: https://github.com/llvm/llvm-project/blob/d54953ef472bfd8d4b503aae7682aa76c49f8cc0/llvm/lib/TargetParser/RISCVISAInfo.cpp#L754-L758

My mistake. I'm not sure why we don't have the implies. gcc does.

**Comment by programmerjake** [comment]
> [@programmerjake](https://github.com/programmerjake) and no alterations to the calling convention?

enabling vsx doesn't alter the calling convention.

**Comment by RalfJung** [comment]
> `+altivec` enables 128-bit vectors, I'm not sure if there are any wider types -- there's MMA with 512-bit accumulators, but idk if they are vector types, they're used for matrix ops.

Are there types which are passed  via these MMA registers?

**Comment by RalfJung** [comment]
> My mistake. I'm not sure why we don't have the implies. gcc does.

For us it's nice that there's no "implies" here, that makes it a lot easier to check the ABI consequences. ;) This way we juts have to block the actual feature changing something, not other features implying them.

Though maybe this is also unnecessary if https://github.com/rust-lang/rust/pull/131807 takes care of all that.

**Comment by RalfJung** [comment]
> `Cllvm-args="--riscv-v-vector-bits-min=N"`

Uh wait a second, we are exposing *another* flag that can change ABI? 😢  😭

**Comment by heiher** [comment]
For LoongArch:
- "lsx" => vlen(128)
- "lasx" => vlen(256)

**Comment by heiher** [comment]
LoongArch: According to the [LoongArch ABI Specs](https://github.com/loongson/la-abi-specs/blob/release/lapcs.adoc), vector type parameters and return values ​​are passed in GAR(general-purpose argument registers) or on the stack, and do not rely on vector registers or vector features.

**Comment by programmerjake** [comment]
> > `+altivec` enables 128-bit vectors, I'm not sure if there are any wider types -- there's MMA with 512-bit accumulators, but idk if they are vector types, they're used for matrix ops.
> 
> Are there types which are passed via these MMA registers?

after a bit more research, there are types for MMA, but you can't pass them by value in function arguments or return, so thry're not ABI-breaking: https://clang.godbolt.org/z/e4sTY37Pv
they lower to `<256 x i1>` and `<512 x i1>`

**Comment by workingjubilee** [comment]
...concerning. these blockades are in clang's semantic checks, they don't seem to be enforced by LLVM.

**Comment by workingjubilee** [comment]
cc @jacobbramley re: aarch64

**Comment by workingjubilee** [comment]
cc @androm3da re: hexagon

**Comment by RalfJung** [comment]
> after a bit more research, there are types for MMA, but you can't pass them by value in function arguments or return

How do we handle that in Rust? We'd need a special pass during collection rejecting them as arguments, likely as part of the simd arg check that this issue is about.

**Comment by RalfJung** [comment]
> after a bit more research, there are types for MMA, but you can't pass them by value in function arguments or return

How do we handle that in Rust? We'd need a special pass during collection rejecting them as arguments, likely as part of the simd arg check that this issue is about.

I assume we don't support these types yet, but this will need to be considered when someone decides to add them.

**Comment by RalfJung** [comment]
> > `-Cllvm-args="--riscv-v-vector-bits-min=N"`
> 
> Uh wait a second, we are exposing _another_ flag that can change ABI? 😢 😭

I only just realized this only affects scalable vector types. Which anyway we don't support. So we can ignore this for now.

**Comment by Dirreke** [comment]
According to the [CSKY Development Guide: 4.5 vdsp](https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource/1721094254407/%E7%8E%84%E9%93%81CPU%E8%BD%AF%E4%BB%B6%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97V3.3.pdf), the vector width is configured as follows:

For vdspv2, the width is fixed at 128 bits.
For vdspv1, the default width is 128 bits, but it can optionally be set to 64 bits using the -mvdsp-width=64 compiler flag. However, please note that the 64-bit width option is currently unsupported by LLVM.

Therefore, for both versions, you can safely set the vector width to 128 bits.

csky:
"vdsp1" | "vdsp2" => vlen(128),

**Comment by androm3da** [comment]
Hexagon HVX supports uses these target flags - +hvx-length64b, +hvx-length128b, +hvx, +hvxv60 through +hvxv73 (explicitly 60,62,65,66,67,68,69,71,73).  `hvx-length64b` maps to 64 *byte* (512 bit) value registers, `hvx-length128b` is 128 byte (1024 bit) value reg.  These registers can also be paired.

Oh - and there's also vector predicate registers -  they're 64-bit and 128-bit wide in hvx-length64b and hvx-length-128b modes, respectively.  These registers can also be quad'd.

All of these vector, vector-predicate registers are caller-saved.

[Link to hexagon ABI doc](https://docs.qualcomm.com/bundle/publicresource/80-N2040-23_REV_K_Qualcomm_Hexagon_Application_Binary_Interface_User_Guide.pdf)

**Comment by jacobbramley** [comment]
> cc [@jacobbramley](https://github.com/jacobbramley) re: aarch64

Neon vectors always have 128 bits, so I can confirm this (if I understand the notation correctly):

>    "neon" => vlen(128)

SVE vectors have a size that isn't known until runtime. In general, we say that they must be passed in "Z" registers (or "P" registers for the predicate type, `svbool_t`). Expressing this as `N` in `vlen(N)` is verbose, but it's simpler to say that Rust will need the "sve" target feature to pass these (as well as to handle them at all), and then each vector will occupy exactly one "Z" or one "P" register, or an appropriately-sized stack slot in case a function takes many arguments.

>   "sve" & -Cllvm-args="--aarch64-sve-vector-bits-min={N}" => vlen(N), NOTE: only scalable vectors?

That `N` can be any power of two such that `128 <= N <= 2048`. SVE code is usually intended to be length-agnostic. However, some compilers have options for specialising code generation in case `N` is actually known in advance. Clang has [`-msve-vector-bits`](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-msve-vector-bits), for example. I would guess that `--aarch64-sve-vector-bits-min` does a similar thing, setting a lower bound.

Passing something like `--aarch64-sve-vector-bits-min` _could_ generate incorrect code if the user gets the vector length wrong. It doesn't actually change the procedure call part of the ABI, though, so I think this is no different than any of the other `-Cllvm-args` or `-Ctarget-features`; these can all result in incorrect code generation if the runtime environment doesn't support what is enabled.

**Comment by jacobbramley** [comment]
For AArch32 ("arm"), Neon has 128-bit vectors (like AArch64), and also supports 64-bit vectors. They are used _differently_ for argument passing, but I doubt that it's important here.

>    "neon" => vlen(128)

MVE has a register layout similar to Neon, and also has 128-bit vectors, but I can't see any operations on 64-bit vectors (e.g. [in ACLE](https://github.com/ARM-software/acle/blob/main/mve_intrinsics/mve.md)). I'm not deeply familiar with MVE, but from recent experiments inspired by Zulip discussions, I think it's similar to Neon on A-class AArch32.

>    "mve" => ???

**Comment by workingjubilee** [comment]
I experimented with gcc and clang and it seems that these C compilers at least offer us the small mercy of resisting doing anything but stack-passing for fixed-size vectors on AArch64. Even if you have SVE above 128 bits, and even if you do your merit best to trick it into accepting such code: https://gcc.godbolt.org/z/GYGEso3Pe

Which, well, **good**.

It still conceivably has some ABI problems, but they at least don't try to sometimes do register passing and sometimes not, which is where we are with x86_64's featureset.

**Comment by Dirreke** [comment]
@RalfJung Sorry, there's a typo in my previous response. In csky, its vdspv1 and vdpsv1, not vdsp1 or vdsp2. Thanks

**Comment by workingjubilee** [comment]
clang says:
- VDSPV1 : [clang::targets::CSKYTargetInfo](https://clang.llvm.org/doxygen/classclang_1_1targets_1_1CSKYTargetInfo.html#ad3332d3b749f4d8fc4436f08aaa3a387)
- VDSPV2 : [clang::targets::CSKYTargetInfo](https://clang.llvm.org/doxygen/classclang_1_1targets_1_1CSKYTargetInfo.html#afb978d9389cdf1472adde4c57dfe9dba)

so going with that.

**Comment by chenx97** [comment]
> but are there any other vector extensions for MIPSr6, and can it even use MSA?

1. There is DSP but it cannot co-exist with MSA. The document also discourages the use of DSP in general.
[MIPS® Architecture For Programmers Volume I-A: Introduction to the MIPS64® Architecture p.36](https://s3-eu-west-1.amazonaws.com/downloads-mips/documents/MD00083-2B-MIPS64INT-AFP-06.01.pdf#page=36)
DSP is a good option when your processor only has legacy nan, and thus cannot implement MSA, but MIPS R6 is nan-2008-only, so it's always recommended to implement MSA instead.

2. MSA is the preferred vector extension for MIPS R6 so yes.

**Comment by RalfJung** [comment]
And these q registers are not used for any ABI / any arguments of any type?

**Comment by MabezDev** [comment]
> And these q registers are not used for any ABI / any arguments of any type?

Correct, they are strictly used for accumulation or parallelisation of 8/16/32 bit math/float operations in memory. There are no custom types nor any changes to the standard calling convention. As the DSP operates on memory, alignment could be a concern here, but the DSP is able to load/store from unaligned addresses (at a perf cost) meaning it stays ABI compatible, but it would of course be preferable to use 128 bit alignment where possible which I'm guessing `std::simd::Simd` will take care of as it mentions "Simd<T, N> can have an alignment greater than T, for better mechanical sympathy" .

**Comment by kito-cheng** [comment]
The issue for the q reg from the esp32 s3 is 1) they didn't upstream their DSP extension to LLVM upstream 2) standard RISC-V ABI won't use reg from vendor extension to pass any things

**Comment by MabezDev** [comment]
> 1) they didn't upstream their DSP extension to LLVM upstream

The plan is for the DSP extensions to be upstreamed into LLVM.

> 2) standard RISC-V ABI won't use reg from vendor extension to pass any things

Good point, the P4 isn't finalized yet so perhaps we'll end up supporting the official vector extensions, if not we'll just expose the instructions via a separate crate instead of `std::simd::*`.

**Comment by sayantn** [comment]
AMX has a special type in LLVM called `x86_amx`, LLVM also supports auto-bitcast of this from/to `i32x256`. Rustc doesn't generate IR that references this type - so we were not able to add this type and it will probably require compiler support

**Comment by kjetilkjeka** [comment]
>nvptx64: I remember this being "it's complicated". cc @RDambrosio016 @kjetilkjeka

I'm not sure I understand the topic well enough to give a complete answer but I will give it my best.

First of all. PTX only deals with virtual registers and exactly how values are passed is handled at a lower level (SASS). The errors encountered due to not treating SIMD types correctly might therefore be of a different nature when compiling to PTX.

Instead of having features there's ISA versions that may slightly change how things work. When using LLVM to produce ptx it's tied to the cpu arch, while the NVIDIA tooling strives to use new ISA versions even for old arches. 

At the current newest version (PTX ISA 8.5) the documented size of vector registers is as described [here](https://docs.nvidia.com/cuda/parallel-thread-execution/#register-state-space)

> scalar registers have a width of 8-, 16-, 32-, 64-, or 128-bits, and vector registers have a width of 16-, 32-, 64-, or 128-bits 

On the other hand there doesn't exists actual vector instructions operating on the described 16, 64, or 128-bit registers. It only exists instructions operating on 32-bit registers (4x8bit or 2x16bit).

I still believe this means the "most correct " thing to use is `vlen(128)` and if that ever changes in a newer ISA version we hopefully have a better grasp of how different ISA version should be handled than we have today.

**Comment by RalfJung** [comment]
Seems like we were missing Sparc in this list -- Cc @thejpster

**Comment by glaubitz** [comment]
> pinging maintainers on the remaining architectures or subarchitectures:
> 
>     * sparc64: I think some have vectors? cc [@glaubitz](https://github.com/glaubitz)

SPARC V9 (i.e. sparcv8plus and sparc64) has different versions of the [VIS SIMD extensions](https://en.wikipedia.org/wiki/Visual_Instruction_Set).

>     * m68k? I'm expecting a "no", but: cc [@glaubitz](https://github.com/glaubitz) [@ricky26](https://github.com/ricky26)

Not that I know of.

**Comment by RalfJung** [comment]
> SPARC V9 (i.e. sparcv8plus and sparc64) has different versions of the [VIS SIMD extensions](https://en.wikipedia.org/wiki/Visual_Instruction_Set).

The question is, which target feature is required to pass SIMD vectors of which size over a C ABI boundary?

**Comment by thejpster** [comment]
The SPARC systems I look after (V7 and V8) don't have any vector extensions.

**Comment by RalfJung** [comment]
Seems like the answer is `vis` (according to @taiki-e )

**Comment by RalfJung** [comment]
Regarding RISC-V, it seems that right now our ABI adjustment logic will never use LLVM vector types for argument passing. It will make them indirect or use an integer register (if the vector is small enough). So I guess the plan is that that logic is updated if/when we get support for the corresponding target features? That will mean we are breaking ABI for any existing code that passes repr(simd) types by-val. However, that's only possible on nightly, so I guess this is fine?

Still, it'd probably be nicer if the ABI adjustment logic just said "vector types currently not supported for this architecture" instead of computing *some* non-standard ABI.

**Comment by RalfJung** [comment]
@veluca93's PR has a comment indicating `128` now, that seems wrong then?
64bit registers seem kind of odd on a 64bit system though...

> On SPARC64: 128-bit(arg)/256-bit(ret) or smaller integer/float vectors are passed using FP reg

That doesn't mean the register is 256bit large though, is it? It probably uses more than one register? OTOH vectors larger than a register are also odd. So I don't really understand what to do with this.

**Comment by taiki-e** [comment]
SPARC FP registers (f[0-63]) are 32-bit long, and two/four of these are combined to process f64/f128. 64-bit VIS vectors also use two FP registers, as does f64.

128-bit/258-bit vectors are also passed or returned using four/eight FP registers.
https://github.com/gcc-mirror/gcc/blob/730f28b081bea4a749f9b82902446731ec8faa93/gcc/config/sparc/sparc.cc#L7388

(By the way, this complication of the nature of FP registers is one of the reasons I postponed FP register support in [the initial implementation of SPARC inline assembly](https://github.com/rust-lang/rust/pull/132472).)

**Comment by RalfJung** [comment]
The relevant question here is: for a vector of size N bits, which target feature must be present so that the vector is passed in a register (whereas if the feature is absent, vectors of that size are passed in a different way).

**Comment by taiki-e** [comment]
IIUC, in that case, we need to refer to the calling conventions'.

> - According to [calling conventions implemented by GCC](https://github.com/gcc-mirror/gcc/blob/730f28b081bea4a749f9b82902446731ec8faa93/gcc/config/sparc/sparc.cc#L6620-L6690):
>   - On SPARC32: 64-bit or smaller integer vectors are passed using FP reg
>   - On SPARC64: 128-bit(arg)/256-bit(ret) or smaller integer/float vectors are passed using FP reg

Assuming our ABI code is correct:

- "sparc": "vis" => vlen(64)
- "sparc64": "vis" => vlen(256)

However, AFAIK our ABI code does not support vector types correctly, so for now we may need to treat it as vlen(0) in lint. (Otherwise, it could incorrectly allow the SPARC64 256-bit vectors in arguments or the SPARC32 float vectors. )

**Comment by RalfJung** [comment]
You said it's 256 only for return values... not sure how that makes any sense, but something can't be right here then. It should probably be "128" for sparc64? Like, maybe in the future they define 256 bit vectors and then pass them different for arguments. Or so?

**Comment by taiki-e** [comment]
> You said it's 256 only for return values... not sure how that makes any sense, but something can't be right here then. 

The 256-bit vector in argument position is passed through memory, not FP registers.

From [calling conventions implemented by GCC](https://github.com/gcc-mirror/gcc/blob/730f28b081bea4a749f9b82902446731ec8faa93/gcc/config/sparc/sparc.cc#L6620-L6690):

>                                size      argument     return value
>      vector integer           <=16        FP reg.        FP reg.
>      vector integer       16<s<=32        memory         FP reg.
>      vector integer            >32        memory         memory

IIUC, our ABI code should handle this correctly by calling make_indirect for vectors with size>16(argument) or size>32(return value). (If it is handled correctly, the 256-bit vector in argument position should not generate a warning anyway, since the lint trigger condition is no longer satisfied.)

> maybe in the future they define 256 bit vectors

GCC's VIS builtins support 32-bit and 64-bit vectors, but larger sizes of vector types are available via `vector_size(...)`. (In Rust, the former is `core::arch` vector type (not available for SPARC yet) and the latter is `core::simd` or custom `#[repr(simd)]` vector type)

Here is a code generated by GCC (only 256-bit vector is moved from memory to FP reg): https://godbolt.org/z/5vEdejj6j

**Comment by taiki-e** [comment]
In any case, LLVM doesn't currently support Vector ABI (https://github.com/llvm/llvm-project/issues/45418), so I think using vlen(0) in the lint is correct for now.

**Comment by RalfJung** [comment]
I guess the number we need is "for vectors of which size is this calling convention guaranteed to be the final word, and future extensions won't change how those vectors are passed". Even assuming a correct ABI implementation on our side, what is that number for SPARC32 + vis / SPARC64 + vis? Or is this somehow not a well-formed question?

**Comment by taiki-e** [comment]
SPARC's Vector ABI is defined based on the existing float and aggregate calling convention, not the VIS ISA [^1], and changing it without a new ABI would also break other non-vector arguments due to the nature of using FP registers. So, I don't believe it can be changed without a new ABI. (This is very different from the x86_64, which extended the ISA in the form of increasing the size of the vector registers.)

That said, if our policy is to not trust the current behavior of psABI with respect to vectors larger than ISA supports [^2], I think the 64-bit mentioned in https://github.com/rust-lang/rust/issues/131800#issuecomment-2473871620 is safe selection.

[^1]: [sparc_pass_by_reference](https://github.com/gcc-mirror/gcc/blob/730f28b081bea4a749f9b82902446731ec8faa93/gcc/config/sparc/sparc.cc#L6745) and [sparc_return_in_memory](https://github.com/gcc-mirror/gcc/blob/730f28b081bea4a749f9b82902446731ec8faa93/gcc/config/sparc/sparc.cc#L7671) in GCC have comments about this.
[^2]: I think this is the correct policy for most architectures.

**Comment by RalfJung** [comment]
> SPARC's Vector ABI is defined based on the existing float and aggregate calling convention, not the VIS ISA

So having or not having `vis` actually makes no difference for how things are passed?
That would mean we could actually allow arbitrary-size vectors -- once we implement the existing ABI correctly, of course.

**Comment by taiki-e** [comment]
> So having or not having `vis` actually makes no difference for how things are passed?
> That would mean we could actually allow arbitrary-size vectors -- once we implement the existing ABI correctly, of course.

Good point. Looking at the assemblies generated by GCC it does not appear to be affected by -mvis (affected by -msoft-float, though): https://godbolt.org/z/3sTMqoaq4

(As for SPARC's soft-float target feature, it should be marked as Forbidden anyway because it affects the float ABI: https://github.com/rust-lang/rust/issues/131799#issuecomment-2468623519)

**Comment by RalfJung** [comment]
Yeah, most targets have a `soft-float` feature and it should be forbidden on all of them. But not all do, e.g. aarch64 does not.

**Comment by workingjubilee** [comment]
> OTOH vectors larger than a register are also odd. So I don't really understand what to do with this.

Fun facts to know and tell: RVV also supports these! it's something called a "register group", and is modified by `LMUL` ("length multiplier"), which its a bitfield that specifies a value in `{8, 4, 2, 1, 1/2, 1/4, 1/8}`. When LMUL is greater than 1, instructions that manipulate vectors in vector registers must address a register with an appropriate factor, but they otherwise operate like a vector of the currently-set vector length multiplied by LMUL.

**Comment by workingjubilee** [comment]
Thank you everyone for participating, I believe we have concluded this investigation for now. There are some only-partly-resolved questions so I opened new issues for them:
- https://github.com/rust-lang/rust/issues/133141
- https://github.com/rust-lang/rust/issues/133144
- https://github.com/rust-lang/rust/issues/133146
