### ISSUE TITLE
Tracking issue for Rust 2024: Fix doctest `include` paths

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#132230]
This is a tracking issue for fixing the path used for `include` in rustdoc doctests.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024.
  - https://github.com/rust-lang/rust/pull/132210
- N/A: Implement migration lints.
- [x] N/A: Add documentation to the [reference][].
    - See the [instructions][reference-instructions].
- [x] Add documentation to the [edition guide][].
  - https://github.com/rust-lang/edition-guide/pull/329
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [x] Should this be an edition item for Rust 2024?

### Related

- https://github.com/rust-lang/rust/issues/132203
- https://github.com/rust-lang/rust/pull/130582
- https://github.com/rust-lang/rust/issues/130470

cc @rust-lang/rustdoc @ehuss @notriddle @GuillaumeGomez

**Comment by notriddle** [comment]
I ran a grep over the Reference, and only https://doc.rust-lang.org/1.82.0/reference/input-format.html and https://doc.rust-lang.org/1.82.0/reference/attributes.html mention `include_str!`. I checked it off.

**Comment by notriddle** [comment]
@rfcbot fcp merge

Since the compiler can already auto-correct `include!` paths, I don't think this needs a migration lint. But if you disagree, and can come up with a way to make it work, please let me know!

**Comment by ehuss** [comment]
I'd like to stress that we need to move quickly if we want to make this change. The crater run should have started a few weeks ago. We have the last edition PR going in as I write this, and we were planning to start the crater run today. Delaying for this is stressing our timeline.

I would encourage considering the forward-compatible warning approach suggested in https://github.com/rust-lang/rust/pull/132210#issuecomment-2440107534 as a way to simplify the problem and the code, since you won't need to retain the arguably old broken behavior. (Or, just accept the breakage in https://github.com/rust-lang/rust/issues/132203 and help those packages fix their tests.)

Can the rustdoc team focus on getting this resolved and merged within a few days? I would prefer to not delay for something last minute like this.

**Comment by traviscross** [comment]
Given the timeline, and building on what @ehuss said, here are the questions and items probably most in need of focus:

1. Might the @rust-lang/rustdoc team just accept the breakage in Rust 1.83?
   - This is arguably a bug-fix, which is normally allowed breakage.
   - The number of crates affected is not large.
   - Unlike other forms of breakage we worry a lot about, this does not affect the dependency graph or whether the program works.
2. If the team does want this to be an edition item, then please:
   - Post the chapter to the edition guide tomorrow (cc @notriddle).
   - While the FCP can continue, in the interest of time we need a presumptive decision by the team lead about the direction here.  I.e., @GuillaumeGomez, if this is an ask for an edition item, please confirm that's the direction you want to go.
   - With the edition guide done and that presumptive decision, we'll merge #132210, which will allow us to go ahead with our edition crater runs.

**Comment by notriddle** [comment]
> I would encourage considering the forward-compatible warning approach suggested

The problem is that the only way to get rid of the warning is to bump the edition, or to stop using `include_bytes!` in your README examples, or to stop using `#![doc=include_str!("../README.md")]` to test your README examples. There's no localized fix to make the code work both before and after the compiler change at the same time.

This is also why I'd rather not just accept the breakage. There's no way for the affected crates to fix nightly without breaking stable.

> Post the chapter to the edition guide tomorrow

https://github.com/rust-lang/edition-guide/pull/329

**Comment by GuillaumeGomez** [comment]
I confirm this is the direction I want to go. I'm surprised an FCP is needed here though but I trust @notriddle's judgement. Let's try to get it approved by tomorrow.

**Comment by GuillaumeGomez** [comment]
It got approved. I think we can exceptionally ignore the FCP if needed. If no one is against it, I'll r+ this evening.

**Comment by ehuss** [comment]
Thank you, I appreciate it!

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition

This item is now **ready** for Rust 2024.  Thanks to @notriddle, @GuillaumeGomez, and the rustdoc team for putting everything in place quickly here.

**Comment by camelid** [comment]
@rfcbot cancel

Given the unusual conditions, the FCP was foreshortened but rfcbot doesn't realize that. Let's cancel it to avoid confusion later.
