### ISSUE TITLE
Tracking Issue for Rust 2024: rustfmt assignment operators rhs indentation

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rust#132380]
This is a tracking issue for changing the indentation level used in formatting assignment/op expressions where the left hand side expression has to be formatted across multiple lines, with the style/formatting changing to indent the right hand side expression relative to the last line of the left hand side expression

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement in nightly Rust 2024.
- [x] Add documentation to the [edition guide][].
  - https://github.com/rust-lang/edition-guide/pull/341
  - https://github.com/rust-lang/edition-guide/pull/343
- [x] Add formatting for new syntax to the [style guide].
    - See the [nightly style procedure].
    - https://github.com/rust-lang/rust/pull/119838 (initially applied to all binary expressions regardless of the operator type)
    - https://github.com/rust-lang/rust/pull/132369 (adjusted scope to only be applicable with assignment operators)
- [ ] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Implementation history

- https://github.com/rust-lang/rust/pull/119838
- https://github.com/rust-lang/rust/pull/132369
- https://github.com/rust-lang/rustfmt/pull/6305

cc @rust-lang/rustfmt @rust-lang/style

**Comment by calebcartwright** [comment]
the Style and Rustfmt teams are already aware of this, but given the late date I will note for transparency that we do already have this "implemented" in `rustfmt` and have been doing some testing on it (and it's that testing that surfaced some formatting diffs that led to us winding back the operators where the new rule should be applied).

I am intentionally going to keep the impl-incomplete label here though until we get the PR merged in

**Comment by traviscross** [comment]
Reminder: There are only 12 days left until the branch date for Rust 1.85.  Anything not in master at that point will not make it into Rust 2024 unless it is accepted by compiler according to the conventions for backports to beta.

I.e., this item is in jeopardy.

**Comment by traviscross** [comment]
@rustbot labels -A-edition-2024 +A-maybe-future-edition

This item unfortunately isn't going to make Rust 2024 (or, equivalently, the Style Edition 2024), given that it's not implemented in nightly and the branch date for Rust 1.85 (and Rust 2024) is 2025-01-03.

Hopefully this item can be included in a future edition.

We'll be reverting this chapter in the Edition Guide, and the relevant changes will also need to be reverted in the Style Guide.
