### ISSUE TITLE
opt-in built-in bounds traits RFC tracker

### ISSUE THREAD

**Issue by FlaPer87** [rust-lang/rust#13231]
#### Checklist 

Here is a check-list of code to write and tricky scenarios to be sure we handle:

- [ ] forbid conditional negative impls [as described here](https://gist.github.com/nikomatsakis/bbe6821b9e79dd3eb477#negative-reasoning-from-oibit-and-rfc-586)
- [ ] conditional negative impls not properly enforced https://github.com/rust-lang/rust/issues/23072
- [ ] `impl !Pod for ..` should not be legal https://github.com/rust-lang/rust/issues/28475
- [x] fix feature-gate for `impl Foo for ..` https://github.com/rust-lang/rust/issues/23225
- [x] defaulted traits ought to be have more restrictive coherence rules https://github.com/rust-lang/rust/issues/22978
- [x] defaulted traits should have no methods #23080 / https://github.com/rust-lang/rust/pull/23117
- [x] Add parser support for `impl Foo for ..`
- [x] Port `Send/Sync` to use new infrastructure internally
- [x] Add `unsafe impl Send for ..` / `unsafe impl Sync for ..` 
- [x] Object types should never match against a defaulted trait (though the object type itself may add a candidate for traits that appear in the object type)
- [x] When a defaulted trait matches, it should impose any supertrait bounds on the matched type as nested obligations
- [x] Be wary of type inference -- if we haven't resolved a type yet, we have to be ambiguous
- [ ] Systematic testing for `constituent_types`
- [x] Coherence interaction: a defaulted trait can only be implemented for structs/enums
- [x] Coherence interaction: a trait can only be defaulted in the crate where it is defined
- [x] Coherence interaction: a trait can only be defaulted once
- [x] Defaulted impls cannot be generic
- [x] Fix the interaction with PhantomData. OIBIT should treat PhantomData<T> as if there were an instance of T reachable rather than breaking it down like it would a different struct. https://github.com/rust-lang/rust/pull/23091
- [x] Allow negative implementations for traits that have a default implementation (besides Send/Sync).

#### Original text

This is a tracking issue for the approved RFC [opt-in-builtin-traits](https://github.com/rust-lang/rfcs/blob/master/text/0019-opt-in-builtin-traits.md)

Nominating

**Comment by aturon** [comment]
Nominating for removal from milestone; I believe the backcompat issues have been handled.

**Comment by pnkfelix** [comment]
removing from 1.0 milestone.

**Comment by alexcrichton** [comment]
I believe this has basically all been implemented to the fullest extent it will for now, so closing.

**Comment by steveklabnik** [comment]
For posterity's sake, what hasn't been?

One question I have about a lot of these older RFCs is how much I can actually rely on their text for documenting semantics. For really old stuff like this, I worry that the RFCs might not be useful for people. This might just be the reality, though.

**Comment by aturon** [comment]
There's definitely more work to do here (see the checklist -- there may be more), and this should ultimately become the tracker for stabilization.

cc @nikomatsakis

**Comment by nikomatsakis** [comment]
In this particular case, the RFC is definitely out of sync with the current
implementation. One of my pending worklist items has been to write an
update to the text.

@steveklabnik I also think that, as part of the stabilization process, we
should go back and update the RFCs to bring them inline with the final
results.

**Comment by dylanede** [comment]
I'm writing a library that depends on OIBIT. In particular, it depends on the following coding pattern working:
```rust
trait NotSame {}
impl NotSame for .. {}
impl<T> !NotSame for (T, T) {}

trait Foo<A> {}

struct Bar<B>(B);

impl<A, B> Foo<A> for Bar<B> where (A, B): NotSame {
    // stuff
}

impl<A> Foo<A> for Bar<A> {
    // other stuff
}
```
This works on nightly at the moment. Is this relying on any behaviour that is disallowed by the intended functionality? I.e. will this break by the time this is stabilised? Thanks.

**Comment by brson** [comment]
RFC needs to be ammended, not sure for what.

**Comment by nikomatsakis** [comment]
Roughly speaking I wanted to formalize the following things:

- [ ] that we no longer do *fallback* with priorities, but instead do "default impls" more like what is described here <https://gist.github.com/nikomatsakis/d5fe4a4b5b075b3d0ec9>
- [ ] the name `auto trait`
- [ ] perhaps a change in the syntax
- [ ] coinductive matching semantics (loosely described in the RFC today)

**Comment by nikomatsakis** [comment]
@dylanede hmm, sorry I failed to answer your question before. I'm sorry to say this, but your code snippet is not expected to work. 

In particular, the way to think about it is that, by adding a negative impl for `(T, T)`, you have suppressed the default impl that would have been provided -- so now there is no positive impl! Therefore, `(X, Y): NotSame` cannot hold *for any* tuple. (But, `(X, Y): !NotSame`, if we ever added negative impls, would only hold if `X == Y`; otherwise, `(X, Y)` neither implements `NotSame` nor `!NotSame`, a situation which @withoutboats artfully described as `(X, Y): ?NotSame`.)

Note that the behavior for your example is inconsistent already. For example, while [your code compiles](https://is.gd/STAYGi), this [similar snippet does not](https://is.gd/te4yXG).

I had to dig a bit into the code to see why your example worked at all: the answer is that the "first pass" test which tries to unify with various impls fails to unify for types like `u32` and `i32` -- it will basically succeed "modulo regions". So then later when we check to see if there were any negative impls that applied, we find out that there were not (in the case of `u32`, `i32`) but that there are (in the case of `&'static u32`, `&'a u32`). If we were properly implementing the RFC the way that I had intended to amend it, we would always find applicable negative impls (in fact, until such time as we add general negative reasoning, I had intended to make the negative impl you wrote illegal -- you would have to write negative impls that are "fully general", much like the rules we enforce for `Drop`.)

**Comment by chriskrycho** [comment]
This is… beyond me. Someday maybe. 😬

But I'm trying to [document all the things](https://github.com/rust-lang/rust/issues/38643), so: can someone take a gander at the reference and the book and give me a reasonable summary of the extent to which this is or isn't documented?

**Comment by Zoxc** [comment]
I just wanted to note that if we add [immovable types](https://github.com/rust-lang/rfcs/pull/1858) in it's current form, default traits would have to be declared with ```trait Send: ?Move {}``` to avoid having `Move` as a supertrait (which has soundness bugs).

**Comment by bstrie** [comment]
Resuming the bikeshed which I had previously missed, not quite sold on the new `auto trait` syntax as of https://github.com/rust-lang/rust/pull/45247 (though nevertheless an improvement over the old). Not only is it a new keyword (a heavyweight addition) for a feature that is intended to be incredibly obscure, but it risks confusion for people coming from C++.

In https://github.com/rust-lang/rust/pull/45247 an alternative of `#[autoderive]` was floated and seemed to have quite some support. I think it makes sense as a general policy for us to prefer attributes/macros for obscure features, and later offer keywords/operators if anyone demands (which was the trajectory for `?`, and the possible trajectory for `async`/`await`, and unlikely to ever occur for autotraits IMO).

**Comment by clarcharr** [comment]
Random thing I noticed is that OIBIT (hackily) allows checking for type equality (and hence type inequality):

```
mod private {
    pub auto trait NotSame {}
    impl<T> !NotSame for (T, T) {}
}
use NotSame;
trait ReqDifferent<T> where (T, Self): NotSame {}
trait ReqSame<T> where (T, Self): !NotSame {}
```

I assume that this is not desired.

**Comment by dylanede** [comment]
No, it's not. This behaviour is a bug, See the responses to https://github.com/rust-lang/rust/issues/13231#issuecomment-187302270

**Comment by clarcharr** [comment]
Wow, I completely missed that comment. Appears that this has already been discussed

**Comment by mitsuhiko** [comment]
I ran into this issue when trying to implement `!Sync` for a type of mine. I know you can work around this with `PhantomData` well but it makes for ugly error messages. I wish I could tell my users that *my* type is not `Sync` and not that `*mut ()` or something similar contained in my type is not sync.

**Comment by arielb1** [comment]
Added #56934

**Comment by Robbepop** [comment]
With the current implementation (that might be buggy) one can solve some simple specialization cases with this feature which is nice:
https://gist.github.com/rust-play/4ea94f766d49abdbc9b2c55e49a9d2d9

**Comment by mtak-** [comment]
> Fix the interaction with PhantomData. OIBIT should treat PhantomData as if there were an instance of T reachable rather than breaking it down like it would a different struct. #23091

This has either been regressed, or was never totally working: [example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=43fd89c965a6ff328b06ee75922784bd).

**Comment by WaffleLapkin** [comment]
@clarfon note that type equality (but sadly not inequality) can be reached with simple traits on stable:
```rust
trait Id {
    type This: ?Sized;
}

impl<T: ?Sized> Id for T {
    type This = T;
}

fn assert_same<A, B>() where A: Id<This = B> {}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e71a8456cea726393a5e1926368c534a))

**Comment by jdahlstrom** [comment]
The following code ([playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f805f333be07fc8ab5b9e6c60ddec1dc)) is rejected by the compiler because `Something` is not implemented for the type `dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static`. Providing an explicit impl makes the code compile. This is probably a bug?

```
#![feature(optin_builtin_traits)]
#![feature(negative_impls)]

pub enum Nothing {}

pub auto trait Something {}

impl !Something for Nothing {}

// Uncomment this to make the code compile
//
//impl Something for dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static {}

pub fn foo<T: Something>(_: T) {}

#[test]
fn test() {
    use std::io::*;
    foo(Error::new(ErrorKind::Other, ""));
}
```

**Comment by dtolnay** [comment]
That is the correct behavior @jdahlstrom. std::io::Error does not get a Something impl because it holds something that does not necessarily implement Something. In general you would only get the auto trait impl if all the fields are known to implement that auto trait.

For example:

```rust
struct S;
impl std::error::Error for S {}
impl std::fmt::Display for S {fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {Ok(())}}
impl !Something for S {}
foo(Error::new(ErrorKind::Other, S));  // io::Error containing an S.
```

**Comment by jdahlstrom** [comment]
@dtolnay Ah, of course. Thanks.

**Comment by camelid** [comment]
I updated the name of this issue to be consistent with the new feature name (see #79336).

**Comment by sourcefrog** [comment]
The RFC doc talks about the `Share` trait, but I think that is now renamed to `Sync`? (Or is it / was it different?) Could I suggest the RFC text be updated, at least with a note if not a search-and-replace?

**Comment by camelid** [comment]
@sourcefrog Usually RFCs aren't updated since there are so many and it would be too much work to keep them up-to-date. But you can open a PR on rust-lang/rfcs and see if indeed it was renamed and they think it's a good idea to update the RFC.

**Comment by dtolnay** [comment]
#107082 proposes an adjustment to the coherence rules involving autotraits.

**Comment by dtolnay** [comment]
I am adding a note to the checklist that the interaction between auto traits and `str` needs to be revisited as part of any eventual stabilization.

Currently with the following code:

```rust
auto trait AutoTrait {}

impl<T> !AutoTrait for [T] {}
```

we get `str` implements AutoTrait but `[u8]` does not.

Under a different libcore-based `str` library implementation something like https://github.com/rust-lang/rust/pull/70911, we'd get that neither implements AutoTrait.

If we want to ever be able to push something like https://github.com/rust-lang/rust/pull/70911 through in the future, there may need to be `str`-specific special cases in the autotrait feature for now.

**Comment by dhardy** [comment]
This RFC is a little dated.
ancient... and possibly needs a re-write. It's unclear to me exactly what "auto traits" are supposed to be. Lets summarise the RFC:

## Motivation

To paraphrase (with comments):

1. `Send` and `Share` (is this the old `Sync`?) should not be opt-in. This issue is solved.
2. Move `Send` and `Share` out of the language into the standard library.
3. Allow user-defined classification traits. Suggested uses are: "tainted", `Snapshot`, `NoManaged`, `NoDrop` (now `!Drop`).

## Detailed design

### Default and negative impls

> We add a notion of a default impl, written:
> ```
> impl Trait for .. { }
> ```
(This is now just `auto trait Trait {}` IIUC.)

> Negative impls are only permitted if `Trait` has a default impl.

This is reliant on having a specified "default impl", as above (not just `impl<T> Trait for T {}` and not the type of default impl used for specialization). *If* an auto-trait is defined as exactly "a trait which is implemented by default, with opt-out", then `auto trait Trait {}` suffices.

> Intuitively, to check whether a trait `Foo` that contains a default impl is implemented for some type `T`, we first check for explicit (positive) impls that apply to `T`. If any are found, then `T` implements `Foo`. Otherwise, we check for negative impls. If any are found, then `T` does not implement `Foo`. If neither positive nor negative impls were found, we proceed to check the component types of `T` (i.e., the types of a struct's fields) to determine whether all of them implement `Foo`. If so, then `Foo` is considered implemented by `T`.

Aha, the (informal) definition of an `auto trait`.

### Modeling Send and Share using default traits

The RFC details how to define `Send` and `Share` as `auto` traits (the current `Sync` is slightly different, but still an `auto` trait).

(The private trait `Freeze` is another `auto` trait with some explicit opt-in and opt-out impls.)

(`auto trait Unpin` is another public auto trait with some explicit opt-ins. As a work-around for not having stable negative impls, `Unpin` has a negative impl for public type `PhantomPinned`.)

### The Copy and Sized traits

`Copy` is just an ordinary (opt-in) marker trait.

`Sized` *looks* like an ordinary trait but the compiler provides all impls (no opt-in or opt-out possible).
(The same is true for `trait Unsize<T: ?Sized>`.)

---

My thoughts follow.

"auto trait" in conjunction with negative impls are a niche solution to moving a few trait definitions from the language to the standard library:

- `Send` (user-defined opt-in and opt-out not allowed)
- `Sync` (user-defined opt-in and opt-out not allowed)
- `Freeze` (not public)
- `Unpin` (user-defined opt-out allowed via an alternative mechanism)

"auto trait" does not allow all "automatically defined traits" to be offloaded from the compiler: e.g. `Sized`, `Unsize<T>`, `Drop`.

The RFC mentions a few other uses of auto traits:

- "tainted" data to be excluded from some generic routine (I do not understand the motivation)
- `Snapshot`, a marker such that a type `T: Clone + Snapshot` indicates that a clone preserves value (i.e. that the clone may not be mutated by some internal reference); this is documentation-via-type-system and possibly has some utility though I don't see how such a bound would be required (the preferred method of preserving generic data will often be to serialize, which allows writing to an external medium)
- `NoManaged`
- `NoDrop`. This is `!Drop` (also known as linear types) and explored elsewhere

The only other possible usage I can think of:

- [`bytemuck::Pod`](https://docs.rs/bytemuck/latest/bytemuck/trait.Pod.html): but this does not work since `Pod` types must not have padding

Hence it remains unclear whether there is sufficient utility "auto traits".

The *other* angle for auto-traits is as an opt-out marker trait (i.e. negative impls #68318). These do not require any rules pertaining to component types, thus, for simplicity, should not use "auto traits" as defined by [RFC 19](https://github.com/rust-lang/rfcs/blob/master/text/0019-opt-in-builtin-traits.md).

**Comment by madsmtm** [comment]
To me, it mostly has value for checking whether the types involved in a closure satisfy a specific property. A perfect example of this, outside the usual `Send/Sync`, is `UnwindSafe` (however badly named that is).

Concretely, I'm using it (behind a feature flag) to make [autorelease pools in Objective-C sound](https://docs.rs/objc2/latest/objc2/rc/fn.autoreleasepool.html), just as a data point for how it's useful.

**Comment by dhardy** [comment]
Thanks for the examples, adding motivation for this feature.

The aspects of this feature I'm least comfortable with are:

- Using a simple name like "auto trait" for what is a complex feature ("auto recursive trait"?)
- The idea of using it as a key building block of negative impls. Potentially that feature should introduce another form of opt-out trait.

**Comment by scottmcm** [comment]
My best recollection of current lang consensus is that `S-tracking-perma-unstable` is correct here.  This is essential for the standard library, but the ecosystem effects of "you need to know to opt out of dozens of random auto traits created by various crates" seems unworkable for a crate ecosystem, so without some solution to that, these likely will remain a standard library exclusive privilege.

**Comment by fogti** [comment]
how about coupling the auto traits so that they only get auto-used when the crate defining them is a direct dependency of the current crate (so no automatic spill of auto traits happens)? (making it crate-level opt-in, trait-level opt-out instead of pure opt-out)

**Comment by GoldsteinE** [comment]
I think pyo3 usecase wasn’t mentioned here, so I’ll bring it as a data point.

pyo3 needs to track which types can only be accessed when Python’s GIL is held. Currently it uses `Send` as a proxy for this property, but it’s neither neccessary nor sufficient requirement and only works as a rough heuristic. It seems like there’s no good way to do it properly without auto traits (+ negative impls). Similar usecase was mentioned above with ObjC, so it seems like this feature is neccessary for sound FFI in at least some cases.

I think that this is evidence that auto traits currently have usecases outside of standard library. Maybe these usecases could be covered by another feature, maybe they’re not enough to sway the decision, but I think it should be recognized that auto traits _have_ utility outside of standard library, and making them perma-unstable will probably make some usecases perma-unsound, unless some other solution is found. I feel like if this issue is to be closed, this tradeoff (“we’re OK with these cases having no known sound solution”) should be explicitly made in the final decision.

**Comment by GoldsteinE** [comment]
I’d also like to address this point specifically wrt `Ungil`:

> you need to know to opt out of dozens of random auto traits created by various crates

Opting out of `Ungil` would be only sensible when you’re doing something with Python and already using pyo3. In my intuition, auto traits are used to represent some properties related to a certain system (e.g. `Send` and `Sync` represent properties related to threads). You opt out of them when your type has some special properties in this system (e.g. is safe to access from multiple threads). Opting out of an auto trait is thus only sensible if you’re actually using this system, so you can promise to uphold some invariants. Opting out of auto traits related to systems you’re not actively integrating with feels like a wrong thing to do in almost any situation.

**Comment by madsmtm** [comment]
> Opting out of auto traits related to systems you’re not actively integrating with feels like a wrong thing to do in almost any situation.

In my case too, you'd only need to opt out of `AutoreleaseSafe` when you're doing stuff with Objective-C (or perhaps Swift, but they're close enough) autorelease pools.

I'll add that if a library wanted to make sure to opt out of all auto traits (e.g. if it implemented some sort of dynamic type), even for generic structs, they could do:
```rust
trait HelperTrait {}

struct MyTypeThatOptsOutOfEverything<T> {
    inner: T,
    p: PhantomData<dyn HelperTrait>,
}
```

Of course this is yet another SemVer footgun to be aware of, but fortunately we [have tools for that now](https://github.com/obi1kenobi/cargo-semver-checks).

**Comment by GoldsteinE** [comment]
Oops, I mixed up “opting out” and “opting in” in my original message. Either way, the point stands: I don’t see a reason to opt out of arbitrary auto traits unless you’re doing something that can affect this particular system. Author of the auto trait guarantees that it’s safe to impl it if all the fields impl it.

**Comment by GoldsteinE** [comment]
Oh, that’s really sad. If `scoped-tls` is valid (and I don’t see a reason for it not to be), then `auto trait Ungil` can only make pyo3 less-obviously-unsound instead of sound. IMHO that’s still a valid reason for it to be an auto trait, but it’s really unfortunate that it doesn’t just make it clean and sound.

**Comment by madsmtm** [comment]
Hmm, I don't think that's a problem for `objc2`'s `AutoreleaseSafe`, since the only type it's used on is `AutoreleasePool<'pool>`, whose only purpose is to carry a lifetime (it's a ZST that doesn't actually carry any data), which it seems like `scoped-tls-hkt` manages to properly bind to the execution of the closure.

So even though we can access the pool, we can't actually do anything bad with it, since it's only the lifetime that we care about, and that is still correctly bounded. See the following example for details.

````rust
```cargo
[dependencies]
# requires `auto_traits` feature
objc2 = { version = "0.5", features = ["unstable-autoreleasesafe"] }
scoped-tls-hkt = "0.1"
```

use objc2::rc::{autoreleasepool, AutoreleasePool, Id};
use objc2::runtime::NSObject;
use scoped_tls_hkt::scoped_thread_local;

fn main() {
    autoreleasepool(|pool1| {
        scoped_thread_local!(static POOL: for<'pool> AutoreleasePool<'pool>);

        POOL.set(pool1, || {
            let obj = autoreleasepool(|_pool2| {
                POOL.with(|pool1| {
                    Id::autorelease(NSObject::new(), pool1)
                })
            });

            // If we manage to get here, then that's unsound, since the object
            // would have been released in the second autorelease pool.

            println!("{obj:?}");
        });
    });
}
````

If you manage to produce a similar example that does compile, then I'd love to know!

**Comment by steffahn** [comment]
@madsmtm Here we go:
```rs
use std::cell::Cell;

use objc2::rc::{autoreleasepool, AutoreleasePool, Id};
use objc2::runtime::NSObject;
use scoped_tls_hkt::scoped_thread_local;

struct PoolHolder<'p> {
    pool1: AutoreleasePool<'p>,
    obj_cell: &'p Cell<Option<&'p NSObject>>,
}
trait IPoolHolder {
    fn autorelease(&self, id: Id<NSObject>);
}
impl<'pool> IPoolHolder for PoolHolder<'pool> {
    fn autorelease(&self, id: Id<NSObject>) {
        self.obj_cell.set(Some(Id::autorelease(id, self.pool1)));
    }
}

fn main() {
    autoreleasepool(|pool1| {
        scoped_thread_local!(static POOL_HOLDER: for<'p> &'p dyn IPoolHolder);

        let obj_cell = &Cell::new(None);

        POOL_HOLDER.set(&PoolHolder { pool1, obj_cell }, || {
            autoreleasepool(|_pool2| {
                POOL_HOLDER.with(|pool1_holder| pool1_holder.autorelease(NSObject::new()))
            });

            let obj: &NSObject = obj_cell.get().unwrap();

            // If we manage to get here, then that's unsound, since the object
            // would have been released in the second autorelease pool.

            println!("{obj:?}");
        });
    });
}
```

**Comment by Zenithsiz** [comment]
Is it possible to make an auto trait **not** depend on the fields of a type?

I'd like to be able to have an auto trait `auto trait Everything {}`, and a type `struct Wrapper<T>(T)` such that an auto-trait is always implemented for `Wrapper` regardless of `T: Everything` (unless there's an explicit `impl !Everything for Wrapper<...> {}`).

<details>

<summary>Further motivation</summary>

I have a normal trait with a default implementation depending on an auto trait:

```rust
pub auto trait WantsAutoSet {}

pub trait Set {
	fn set(&self);
}

// "Default" impl for all types.
impl<S: WantsAutoSet> Set for S {
	fn set(&self) {}
}
```

I then have 2 types, `Normal` which just wants the default impl and `Special` which wants to do a special implementation:

```rust
// Wants default `Set` impl
pub struct Normal<T>(T);


// Wants special `Set` impl
pub struct Special<T>(T);

impl<T> !WantsAutoSet for Special<T> {}

impl<T> Set for Special<T> {
	fn set(&self) {}
}
```

The issues happen downstream, where a consumer of `Normal` cannot call `set` on a generic `T`, only on `T: WantsAutoSet`:

```rust
// Works
fn set_normal_with_explicit_auto<T: WantsAutoSet>(normal: Normal<T>){
    normal.set();
}

// Does not work
fn set_normal<T>(normal: Normal<T>) {
    normal.set();
}
```

(See the [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=77e2a568ade0ea4044522ed53a9e2fee))

This can be fixed by just using `impl<T> WantsAutoSet for Normal<T> {}`, (or by having `Normal` not have a type parameter), but I have a lot of these `Normal`-like types and I don't want to need to make this impl for each one, since at that point I'd just make it a normal trait instead of an auto trait.

Also these `Normal`-like types do need ownership of `T` for the `Set` impl, I can't just use `PhantomData` to wave it away somehow.

(Also note that this is somewhat like specialization, but I can't just use actual specialization because the `Special` impl of `Set` has different bounds that are incompatible (i.e. not a subset), and I'd also like to "disable" the default implementation because it'd inefficient for `Special`, which wouldn't work with specialization.)

</details>

**Comment by lygstate** [comment]
When this can be stablized, https://github.com/rust-lang/rust/pull/149335 also want this and blocks https://github.com/rust-lang/rust/issues/154046

I really want io to be mved from std into core.

**Comment by madsmtm** [comment]
See https://github.com/rust-lang/rust/issues/13231#issuecomment-1730129155, it likely won't be stabilized outside of the standard library.
