### ISSUE TITLE
Tracking Issue for Rust 2024: rustfmt single line where clauses

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rust#132381]
This is a tracking issue for changing the formatting of where clauses to be formatted on a single line in some additional contexts, provided they meet certain constraints (short, single bound, and no `=` on aliases)

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement in nightly Rust 2024.
- [x] Add documentation to the [edition guide][].
  - https://github.com/rust-lang/edition-guide/pull/340
  - https://github.com/rust-lang/edition-guide/pull/344
- [ ] Add formatting for new syntax to the [style guide].
    - See the [nightly style procedure].
    - https://github.com/rust-lang/rust/pull/119515
- [ ] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Implementation history

- https://github.com/rust-lang/rust/pull/119515

cc @rust-lang/rustfmt @rust-lang/style

**Comment by calebcartwright** [comment]
Similar to my comment in https://github.com/rust-lang/rust/issues/132380#issuecomment-2448894537, I will note that we have already done the development for this and have been testing and reviewing the testing results with the style team.

Going to keep the impl-incomplete label until implementation is merged though

**Comment by joshtriplett** [comment]
https://github.com/rust-lang/edition-guide/pull/340

**Comment by ytmimi** [comment]
@calebcartwright was the plan to default `where_single_line=true` for `style_edition=2024`? Should be a one line change:

https://github.com/rust-lang/rustfmt/blob/9f8fcc2f3e7c7ff48412c30cfda67306d8e3320f/src/config/options.rs#L622

```diff
-    WhereSingleLine, bool, _ => false;
+    WhereSingleLine, bool, Edition2024 =>  true, _ => false;
```

**Comment by traviscross** [comment]
Reminder: There are only 12 days left until the branch date for Rust 1.85.  Anything not in master at that point will not make it into Rust 2024 unless it is accepted by compiler according to the conventions for backports to beta.

I.e., this item is in jeopardy.

**Comment by traviscross** [comment]
@rustbot labels -A-edition-2024 +A-maybe-future-edition

This item unfortunately isn't going to make Rust 2024 (or, equivalently, the Style Edition 2024), given that it's not implemented in nightly and the branch date for Rust 1.85 (and Rust 2024) is 2025-01-03.

Hopefully this item can be included in a future edition.
