### ISSUE TITLE
Tracking Issue for `NonZero<u*>::div_ceil`

### ISSUE THREAD

**Issue by tyilo** [rust-lang/rust#132968]
Feature gate: `#![feature(unsigned_nonzero_div_ceil)]`

This is a tracking issue for implementing `div_ceil` for `NonZero<T>` where `T` is an unsigned integer.

### Public API

```rust
// core::num

impl NonZero<u8> { // similarly for u16, u32, u64, u128 & usize
    pub const fn div_ceil(self, other: Self) -> Self;
}
```

### Steps / History

- [x] ACP: https://github.com/rust-lang/libs-team/issues/471
- [x] Implementation: #132665 
- [x] Final comment period (FCP)[^1]
- [x] Stabilization PR: https://github.com/rust-lang/rust/pull/147562

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by tyilo** [comment]
Seems like I have to ping a libs team member directly, so ping @Amanieu.

**Comment by Amanieu** [comment]
@rfcbot merge
