### ISSUE TITLE
Tracking Issue for Generic Const Args MVP

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#132980]
This is a tracking issue for the prototype described in rust-lang/rust-project-goals#100.
The feature gate for the issue is `#![feature(min_generic_const_args)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [ ] Add `ConstArgKind::Path`
- [ ] Use `ConstArgKind::Path` for all single-segment paths
- [ ] Use `ConstArgKind::Path` for all paths
- [ ] Implement support for paths to `static`s
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/main/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

TODO

### Implementation history

- #125915
- #129137
- #131081
