### ISSUE TITLE
Tracking Issue for `async_fn_in_dyn_trait`

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#133119]
This is a tracking issue for dyn-compatible traits with async functions in them, called "async functions in dyn trait".
The feature gate for the issue is `#![feature(async_fn_in_dyn_trait)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [ ] Experiment with the design
- [ ] Author an RFC
- [ ] Implement the RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/main/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

XXX --- list all the "unresolved questions" found in the RFC to ensure they are
not forgotten

**Comment by traviscross** [comment]
@rustbot -I-lang-nominated +B-experimental

We discussed this in lang triage today and were all enthusiastic to approve an experiment here with @nikomatsakis to liaison.  We look forward to seeing the results of this.

Thanks to @compiler-errors for pushing forward on this.

**Comment by jieyouxu** [comment]
#107011 is superseded by this tracking issue, right?
