### ISSUE TITLE
Tracking Issue for relnotes interest group ping group

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#133334]
Tracking issue for creating a ping group for relnotes PRs so interested contributors can get pinged for that specific purpose (instead of pinging whole teams like T-compiler which has idk 50+ members). Note that the following steps are derived from [T-compiler notification group procedure](https://forge.rust-lang.org/compiler/notification-groups.html) but adjusted because those procedures are for compiler-specific ping groups, whereas this is a general ping group.

### Implementation steps

- [x] ~~File a tracking issue in the [rust-lang/compiler-team](https://github.com/rust-lang/compiler-team) repository to collect your progress.~~ Not compiler-specific ping group.
- [x] Create a PR against the [rust-lang/team](https://github.com/rust-lang/team) repository adding the notification group. https://github.com/rust-lang/team/pull/1613
- [x] Configure the [rust-lang/rust](https://github.com/rust-lang/rust) repository to accept triagebot commands for this group. https://github.com/rust-lang/rust/pull/135032
- [x] Configure the [rust-lang/blog.rust-lang.org](https://github.com/rust-lang/blog.rust-lang.org) repository to accept triagebot commands for this group. https://github.com/rust-lang/blog.rust-lang.org/pull/1453
- [x] ~~Create a PR for the rustc-dev-guide amending [the notification group section](https://rustc-dev-guide.rust-lang.org/notification-groups/about.html) to mention your group.~~ T-release mostly, not compiler.
- [x] Create a sample PR for the [rust-lang/team](https://github.com/rust-lang/team) repository showing how one can add oneself. This will be referenced by your blog post to show people how to join. See https://github.com/rust-lang/team/pull/1613.
- [x] Create a PR for the forge release notes section to describe the relnotes interest group ping group. https://github.com/rust-lang/rust-forge/pull/799
- [x] ~~Create a Zulip stream for the notification group. If you don’t have the permission to do, you can ask on [#t-compiler/wg-meta](https://rust-lang.zulipchat.com/#narrow/stream/185694-t-compiler.2Fwg-meta).~~ Unclear if needed, probably better to discuss on the relnotes PR itself.
- [x] Write an announcement blog post for Inside Rust and open a PR against [blog.rust-lang.org](https://github.com/rust-lang/blog.rust-lang.org). https://github.com/rust-lang/blog.rust-lang.org/pull/1484, live at https://blog.rust-lang.org/inside-rust/2025/02/27/relnotes-interest-group.html.

### Relevant context

- Zulip discussion: https://rust-lang.zulipchat.com/#narrow/channel/241545-t-release/topic/Please.20CC.20lang

**Comment by jieyouxu** [comment]
The steps have been completed, so closing.
