### ISSUE TITLE
Tracking Issue for `core_slice_as_array`.

### ISSUE THREAD

**Issue by bjoernager** [rust-lang/rust#133508]
Feature gate: `#![feature(core_slice_as_array)]`

This is a tracking issue for adding conversion functions going from slices to arrays.

<sub>This tracking issue has been branched into #148082.</sub>

### Public API

```rust
// core::slice

impl<T> [T] {
    pub const fn as_array<const N: usize>(&self) -> Option<&[T; N]>;

    pub const fn as_mut_array<const N: usize>(&mut self) -> Option<&mut [T; N]>;
}

// core::ptr

impl<T> *const [T] {
    pub const fn as_array<const N: usize>(self) -> Option<*const [T; N]>;
}

impl<T> *mut [T] {
    pub const fn as_mut_array<const N: usize>(self) -> Option<*mut [T; N]>;
}
```

### Steps / History

- [x] API change proposal (ACP): [#496](https://github.com/rust-lang/libs-team/issues/496/)
- [x] Implementation:
  - [x] ... for `[_]`, `*const [_]`, and `*mut [_]`: #133512
  - [x] Fix docs for `<[_]>::as_array`: #133743
- [x] Final comment period (FCP)
- [ ] Stabilisation: #147540

### Unresolved Questions

- ~~`str::as_bytes_array` and `str::as_bytes_array_mut`?~~ : Will be moved to new tracking issue in due time.

**Comment by bjoernager** [comment]
Also, can we even implement the `into_array` converters? `[T; N]` and `[T]` do AFAIK not have the same representation due to the latter storing its length.

**Comment by bjoernager** [comment]
@RustyYato suggests the following signature for the `alloc`-typed slices:

```rust
pub fn into_array<const N: usize>(self) -> Result<Self<[T; N]>, Self<[T]>>;
```

to prevent accidental leaks if conversion fails. Would this be preferred as-is or would a new error type (e.g. `SliceIntoArrayError`) have to be defined?

**Comment by programmerjake** [comment]
well, if you use `Rc::<dyn Any>::downcast` as precedence, just returning `Result<Rc<[T; N]>, Rc<[T]>>` (and likewise for other owning types) should be good imo

**Comment by bjoernager** [comment]
It seems I messed up the docs entry for `<[T]>::as_array`. I'll make a follow-up PR addressing this when I can.

**Comment by bjoernager** [comment]
I am aware that they mostly do not specialise any methods, but could (and should) we extend this to also include `Mutex` and `RwLock`?

**Comment by bjoernager** [comment]
I guess the fact that you call them `as_array_mut` is an indication that naming is still an open topic.

That name was the initial suggestion but is not what has been implemented.

Personally, I am for the current name (similarly to `<[T; N]>::as_mut_slice`). But we also have `str::as_bytes_mut`, so I am not completely certain what the consensus here is.

But otherwise, there doesn't seem to be any other blockers for the primitive types.

**Comment by hanna-kruppe** [comment]
I guess [there is a source for the `as_mut_foo` convention](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv):

> If the `mut` qualifier in the name of a conversion method constitutes part of the return type, it should appear as it would appear in the type. For example [Vec::as_mut_slice](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.as_mut_slice) returns a mut slice; it does what it says. This name is preferred over `as_slice_mut`.

I always forget about this because the "`_mut` as suffix" style is so overwhelmingly common. But it seems this guidance is applied somewhat consistently if you interpret it very narrowly as referring to the canonical name of the return type. So it probably doesn't apply to `as_bytes_mut` since `&mut [u8]` isn't necessarily pronounced "mut bytes". If the scope of this convention is really that narrow, then it may not apply to `as_*` returning `Option<&mut [T; N]>` either (glossing both over the reference and the `Option` seems like a stretch).

But I don't care either way, rust-analyzer is decently good at papering over such small naming differences.

**Comment by ProgramCrafter** [comment]
> I am aware that they mostly do not specialise any methods, but could (and should) we extend this to also include Mutex and RwLock?

Borrowed conversions are impossible here, because `&Mutex<[T]>` could have the slice's length change at any moment. User would need to lock explicitly for that operation to mean anything, and then they have `&[T]` by Deref.

Owned conversion might be nice though, so that underlying OS mutex is not destroyed to be created anew!

**Comment by programmerjake** [comment]
> Borrowed conversions are impossible here, because `&Mutex<[T]>` could have the slice's length change at any moment.

I don't think that's correct. `Mutex<T>` is conceptually:
```rust
struct Mutex<T: ?Sized> {
    os_mutex: OsMutex,
    value: UnsafeCell<T>,
}
```
so for `Mutex<[T]>` to be resized you would have to reallocate the `Mutex<[T]>` which you can't do while other threads could be accessing the `os_mutex` field.

also, the slice's length is stored in the reference itself, not the `Mutex` struct, there's no way to simultaneously update all references with the new length.

**Comment by bjoernager** [comment]
Sure. But I understood from <https://github.com/rust-lang/rust/issues/146939#issuecomment-3353071319> that subset FCPs were allowed, thus not necessitating separate tracking issues.
