### ISSUE TITLE
Tracking Issue for `hint::select_unpredictable`

### ISSUE THREAD

**Issue by joboet** [rust-lang/rust#133962]
Feature gate: `#![feature(select_unpredictable)]`

This is a tracking issue for `hint::select_unpredictable`, which selects between two values and hints to the optimizer that it should try to generate branchless code.

### Public API

```rust
// core::hint

/// Returns either `true_val` or `false_val` depending on the value of
/// `b`, with a hint to the compiler that `condition` is unlikely
/// to be correctly predicted by a CPU’s branch predictor.
pub fn select_unpredictable<T>(b: bool, true_val: T, false_val: T) -> T;
```

### Steps / History

- [x] ACP: https://github.com/rust-lang/libs-team/issues/468
- [x] Implementation: https://github.com/rust-lang/rust/pull/133964
- [x] Moved to `core::hint`: https://github.com/rust-lang/rust/pull/139726
- [x] Fixed drop handling: #139977 
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- This should be `const`, right?

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by tgross35** [comment]
Reading through the ACP, it seems like the justification for having this on `bool`, rather than `hint`

 since it acts as a convenience API (ternary standin) but ties it to a low level optimization feature - not having an equivalent that doesn't affect codegen seems like it may confuse users. I think [@scottmcm's suggestion of a regular `select` method](https://github.com/rust-lang/libs-team/issues/468#issuecomment-2456486784) would improve this

**Comment by leb-kuchen** [comment]
I would prefer a builtin branch_hint function as the first statement in a branch like in Zig. 
[BrachHInt](https://ziglang.org/documentation/master/std/#std.builtin.BranchHint)
[branch_hint()](https://ziglang.org/documentation/master/#toc-branchHint)
This would a lot more flexible and not only work with a ternary statement.

**Comment by hanna-kruppe** [comment]
For likely/unlikely, such intrinsic(s) are under discussion at https://github.com/rust-lang/libs-team/issues/510. In contrast, the motivation for `select_unpredictable` is to reliably get branchless machine code. Expressing that by control flow at the source level can sabotage the intended effect, [as discussed in the APC](https://github.com/rust-lang/libs-team/issues/468#issuecomment-2431402691). So an equivalent of Zig's `branch_hint(.unpredictable)` wouldn't be a good replacement for `select_unpredictable`. If it's still useful for other reasons, then that should be an *additional* proposal laying out those reasons.

**Comment by Amanieu** [comment]
I'm personally inclined to move this to `std::hint` to make it clear that it is only an optimization hint and not something that is guaranteed (e.g. for cryptographic code). It would slightly depart from the precedent that all existing functions in `std::hint` are no-ops, but I don't think this is a significant concern.

**Comment by hanna-kruppe** [comment]
This is a good point. It would also be inconsistent with a "non-unpredictable" `select` method (as discussed in the ACP) which has no reason at all to live in `std::hint`. But perhaps the important thing is just that both exist and not where they live and how they're invoked (`cond.select(t, f)` vs `hint::select_unpredictable(cond, t, f)`).

**Comment by Amanieu** [comment]
In #139726 I argue for moving this to `core::hint`, after which I would like to push towards stabilizing this.

**Comment by Amanieu** [comment]
I think this is ready for stabilization now.

@rfcbot merge

**Comment by Amanieu** [comment]
Stabilized by #140550
