### ISSUE TITLE
Tracking Issue for RFC 3591: `use`ing associated items from traits

### ISSUE THREAD

**Issue by clubby789** [rust-lang/rust#134691]
This is a tracking issue for the RFC "Add support for `use Trait::func`" (rust-lang/rfcs#3591).
The feature gate for the issue is `#![feature(import_trait_associated_functions)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [x] Implement the RFC
   - https://github.com/rust-lang/rust/pull/134754
   - https://github.com/rust-lang/rust/pull/138712
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/main/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

**Comment by crumblingstatue** [comment]
Might be worth noting that there is an orthogonal implementation of using a trait function through the unstable [`fn_delegation`](https://github.com/rust-lang/rust/issues/118212) feature.

```Rust
#![feature(fn_delegation)]

reuse Default::default;

fn main() {
    let s: i32 = default();
    dbg!(s);
}
```

**Comment by joshtriplett** [comment]
We were discussing this feature in a @rust-lang/libs-api meeting. We were wondering if the infrastructure that enables this feature would make it straightforward to provide a (separate) feature allowing `use` of an *inherent* function or associated constant/type from a concrete type.

**Comment by joshtriplett** [comment]
Also, separately from that: what's the status of this feature? Are there any blockers that aren't in the (currently empty) list at the top of this tracking issue? If not, could @rust-lang/lang get a stabilization report, please?

**Comment by fmease** [comment]
> We were wondering if the infrastructure that enables this feature would make it straightforward to provide a (separate) feature allowing `use` of an *inherent* function or associated constant/type from a concrete type.

Not in the slightest. This feature is powered by name resolution and its impl just needed to lift some essentially artificial restrictions.

Referencing a specific inherent associated item always requires type checking routines (namely, type unification) because they are first identified by their self type which can be arbitrary and contain aliases that'd need to be normalized first (which requires type checking routines).

Furthermore, the current `use` syntax won't do (`fn_delegation`'s `reuse` comes closer, see below), how else would you be able to disambiguate between `impl Ty<A> { fn f() {} }` and `impl Ty<B> { fn f() {} }` if not by generic arguments which aren't allowed in `use`s. How would you refer to inherent `impl`s for `dyn Trait`?

This is T-types territory. Even then, it's incredibly hard to support for the same reason why inherent associated types haven't been implemented for more than a decade. And can likely only support them in a more limited form via HACKs: See #140247 most recently.

Note that we also have the feature `fn_delegation` (`reuse …;` in code) (https://github.com/rust-lang/rfcs/pull/3530) with which one can do a lot more things but it also doesn't support inherent associated items and likely won't do so anytime soon.

**Comment by petrochenkov** [comment]
>Note that we also have the feature `fn_delegation` (`reuse …;` in code) (https://github.com/rust-lang/rfcs/pull/3530) with which one can do a lot more things but it also doesn't support inherent associated items and likely won't do so anytime soon.

Unlike in `use` imports, in delegation it should be quite realistic (there's an old semi-working prototype [here](https://github.com/bryanskiy/rust/tree/delegImpl)), we are planning to implement it this year or in early 2026.

**Comment by fmease** [comment]
As long as you have `Body` (which you would have for `reuse`'d inherent assoc consts & fns) and lower the target via a `FnCtxt` instead of `ItemCtxt`, everything should indeed be fine.

**Comment by obsgolem** [comment]
> Also, separately from that: what's the status of this feature? Are there any blockers that aren't in the (currently empty) list at the top of this tracking issue? If not, could @rust-lang/lang get a stabilization report, please?

Does the documentation need written before a stabilization report is written? I would be willing to do both if needed.

**Comment by clarfonthey** [comment]
Adding official documentation (e.g. reference) for a future is usually done as part of stabilisation, so, that can be done later. So, just a stabilisation report is needed.

At the moment, I'm noticing a few issues that should be addressed before stabilisation:

1. rustdoc only links to to the trait on the re-exports, not the specific type, constant, or function anchor on that page.
2. Right now, trying to import an associated constant or method from an inherent type will show an error saying it's "a struct, not a module," which should be updated to say "not a module or trait". Alternatively, if it's not too much work, we could just support this for inherent types.

**Comment by anthonyaviles620-dotcom** [comment]
I want to make bank account number and routing number online checkouts using cash app feed and plaid enviroment endpoint oauth client and tenant verifications from azure.microsoft.com.
