### ISSUE TITLE
Tracking Issue for `keylocker_x86`

### ISSUE THREAD

**Issue by sayantn** [rust-lang/rust#134813]
Feature gate: `#![feature(keylocker_x86)]`

This is a tracking issue for the `kl` and `widekl` target features and the associated intrinsics in `stdarch`

### Public API
The following target features and all their associated intrinsics
 - `kl`: Intel Key Locker
 - `widekl`: Intel Key Locker Wide

### Steps / History

- [ ] Add the target features to Rust
- [ ] Add the Intrinsics and Feature Detection to `stdarch`
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

### Implementation History

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by sayantn** [comment]
cc @rust-lang/lang
cc @Amanieu 

I believe this is also ready for stabilization, as all the intrinsics have been implemented already

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We do our stabilization FCPs on stabilization PRs.  Please submit and nominate one of those for us along with the stabilization report.  See the new template for that:

https://github.com/rust-lang/rustc-dev-guide/pull/2219

**Comment by sayantn** [comment]
The lang-stabilization is being done in #140766, so let's do the libs stabilization here (intrinsics and runtime detection, in rust-lang/stdarch#1795)

@rustbot label I-libs-api-nominated

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by cuviper** [comment]
This was released in 1.89.0.
