### ISSUE TITLE
Tracking Issue for `-Z link-native-libraries`

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#134948]
This is a tracking issue for the unstable rustc flag `-Z link-native-libraries`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [x] ~~Open an MCP and have it accepted.~~ At the time of impl, there was no such requirement.
- [x] Implementation PR.
    - https://github.com/rust-lang/rust/pull/107675
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- What does this unstable rustc flag `-Z link-native-libraries` do, exactly?
- How does it relate to the stable `#[link]` attribute?
- What does this mean for the [`#[link]` attribute][link-attr] (which is a stable attribute)?
- How does this unstable flag relate to `-Z link-directives`?

### Implementation history

- Initial implementation PR: https://github.com/rust-lang/rust/pull/70095

[link-attr]: https://doc.rust-lang.org/reference/items/external-blocks.html#the-link-attribute

**Comment by ChrisDenton** [comment]
So `link-native-libraries=no` is interesting. It appears to entirely disable passing native libraries to the linker. And unlike other flags, it has a global effect. So if we have `#[link(name = "something")]` in the precompiled std then usually there's no way to stop `something` being passed to the linker. However, with this flag it is possible (at the cost of having to manually add back everything else). The effect is useful for build systems that want complete control of linking.

Personally, if we ever stabilize something like this, I'd want it to be a bit more fine grained. So you could remove or replace individual native libraries as well as removing everything. You can kinda do a rename today with `-l oldname:newname`. But that effect is local to the crate and only allows renaming and not removing.

**Comment by Ralith** [comment]
This flag is useful in combination with the buck2 build system, which specifies most libraries explicitly. However, it breaks std on Windows for the reasons outlined by above. Thanks to the example at https://github.com/rust-lang/rust/pull/134918, I worked out that you need to compensate by passing [a subset of] the libs referenced from https://github.com/rust-lang/rust/blob/master/library/std/src/sys/pal/windows/c/windows_sys.rs, where for each `foo.dll` you add `-Clink-arg=foo.lib` to the rustc command line.

This is probably all working as intended -- for a hermitic build, you might want to instead pass paths to specific versions of those libraries, too. Still, it was difficult to uncover.
