### ISSUE TITLE
Tracking issue for RFC 3722: Explicit ABIs in `extern`

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#134986]
This is a tracking issue for:

- https://github.com/rust-lang/rfcs/pull/3722

The feature gate for the issue is `#![feature(explicit_abis)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Accept an RFC.
  - https://github.com/rust-lang/rfcs/pull/3722
- [ ] Implement in nightly.
- [ ] Add documentation to the [dev guide][].
  - See the [instructions][doc-guide].
- [ ] Add documentation to the [reference][].
  - See the [instructions][reference-instructions].
- [ ] Add formatting for new syntax to the [style guide][].
  - See the [nightly style procedure][].
- [ ] Stabilize.
  - See the [instructions][stabilization-instructions].

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[stabilization-instructions]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Related

TODO.

### Implementation history

TODO.

**Comment by obeis** [comment]
I have started working on implementing the RFC, and I will probably address a PR in the next two weeks.

**Comment by compiler-errors** [comment]
Is this not already implemented as the `MISSING_ABI` lint? cc @m-ou-se

**Comment by m-ou-se** [comment]
Yes, it is already implemented as a lint.

I assume this tracking issue is for making it a hard error in the next edition?

**Comment by compiler-errors** [comment]
Yeah, I just wanted @obeis and @traviscross to be aware that this functionality is already implemented. It would be nice to have a PR to set it to deny in the new edition and implements a migration, though that is also dependent on a PR that adds the new edition.

**Comment by traviscross** [comment]
The tracking issue steps above are now updated with the relevant work.
