### ISSUE TITLE
Model lexer is still wrong

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#15883]
Tracking issue for all known problems with the lexer.

Todo:

- [ ] https://github.com/rust-lang/rust/issues/15679 antlr's lack of unicode is disturbing
- [x] https://github.com/rust-lang/rust/issues/15877 Model lexer doesn't handle range correctly
- [ ] https://github.com/rust-lang/rust/issues/15878 Weirdness with shebang between model and rustc
- [x] https://github.com/rust-lang/rust/issues/15879 Model lexer doesn't handle question marks
- [ ] https://github.com/rust-lang/rust/issues/15881 Model lexer doesn't handle ... something?
- [ ] https://github.com/rust-lang/rust/issues/15882 Model lexer doesn't handle CRLF correctly
- [ ] Remove any remaining `ignore-lexer-test`s.

**Comment by fhahn** [comment]
Does it stilll make sense to keep the antlr lexer after the flex/bison parser was added in https://github.com/rust-lang/rust/pull/21452 ?

**Comment by cmr** [comment]
I initially wrote this lexer to serve as the reference because it is far simpler than the flex one.
