### ISSUE TITLE
Windows metabug

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#16459]
These are some of the major outstanding Windows bugs, ordered roughly by priority. [Prior discussion](http://discuss.rust-lang.org/t/prioritizing-windows-issues/319)

Major tasks:

* [x] #16312 64-bit automation
* [x] #16823 Installer naming
* [x] #11782 stop requiring mingw install
* [x] #16456 cargo installation
* [x] #13259 TCB-slot usage                                                                  
* [x] https://github.com/rust-lang/cargo/issues/326 native dlls
* [x] #16457 run full test suite on bots
* [ ] #13810 make install problems
* [x] #17202 debuginfo

Compiler fixes:

* [x] #13256 debugging problems
* [x] #15644 'benign' segfaults
* [x] #15420 static libgcc
* [ ] #13794 inconsistent output naming
* [x] #13793 0-length static array
* [x] #13429 float casts
* [x] #11261 which system ABI on win64

Library fixes:

* [x] #16070 MemoryMap::new()
* [ ] #15836 fs::rename
* [ ] #15522 plugin_registrar ICE
* [x] #5286 x-crate tests
* [x] #13725 regex tests
* [x] #12795 lstat
* [x] #10102 UDP tests
* [x] #8818 dynamic lib tests
* [ ] #8755 math test failures
* [x] #16937 process::Command::env

Mysterious crashes:

* [x] #14403
* [x] #15813
* [x] #16324

Other:

* [x] #16654 - docs
* [x] #15717 - triples
* [x] #17260 - broken installer link
* [x] #17251 - incompatibility with system mingw

**Comment by frewsxcv** [comment]
Visiting for triage: Any updates for any of the items above?

**Comment by alexcrichton** [comment]
Enough of this has been checked off that I think it's safe to say this can be closed now.
