### ISSUE TITLE
Implement associated items

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#17307]
Tracking issue for https://github.com/rust-lang/rfcs/pull/195

This meta-bug contains links to the most significant tasks remaining for associated items. For a comprehensive listing of bugs, please [search using the A-associated-items label](https://github.com/rust-lang/rust/labels/A-associated-items).

Post 1.0 Tasks
 * [ ] Normalize associated types used in where clauses (#20765) and associated type bounds (#20775)
 * [ ] Implement associated lifetimes (see Issue #17842),
 * [ ] Update library code for associated constants (see Issue #17825).

Completed Tasks
 * [x] Implement associated output types (see PR #16377),
 * [x] Update library code for associated output types (see Issue #17826),
 * [x] Implement multi-dispatch (see PR #17669),
 * [x] Update library code for multi-dispatch (see Issue #17827),
 * [x] ICE: Unbound path #17388 
 * [x] Clarify outlives requirements on projected types (https://github.com/rust-lang/rust/issues/20303)
 * [x] Integrate projection types into method dispatch #20469
 * [x] Some types not normalized? #20604
 * [x] ICE with missing impl items https://github.com/rust-lang/rust/issues/20347
 * [x] Associated types should permit builtin bounds (#17921)
 * [x] Implement `Trait<Out=Type>` syntax (#18432)
 * [x] Support `T::Type` syntax (#18433)
 * [x] Associated types are used as inputs for multidispatch (#18437)
 * [x] Traits with associated types appearing on structs, enums, or other traits (#18768)
 * [x] Qualified paths don't check type arguments in the trait reference (#18865)
 * [x]  rustdoc panics when dealing with associated types (#18594)
 * [x] Associated types  should permit arbitrary bounds (#18178)
 * [x] Associated types need to do transitive bound expansion (#18434)
 * [x] Traits with where clauses that themselves reference traits with assoc types (#18436)
 * [x] Integrate object projection predicates into rustdoc (https://github.com/rust-lang/rust/issues/20299)
 * [x] Convert T::Foo resolution to use where clauses, not bounds (https://github.com/rust-lang/rust/issues/20300)
 * [x] Implement associated constants (see Issue #17841),
 * [x] Implement defaults for associated types (see issue #19476),

Declined tasks
* ~~Permit unqualified references to associated types of the trait within the trait definition (#18764)~~
* ~~Update library code for associated lifetimes (see Issue #17828),~~

**Comment by nikomatsakis** [comment]
**Meta-note: the top-level comment includes all bugs listed so far that have not yet been fixed.**

**Comment by rrichardson** [comment]
Found a possible bug wrt to traits which have types which are Deref: #20502

**Comment by carllerche** [comment]
My current associated type blockers:

Constraints on nested associated types: #20543
Default type parameters w/ associated types: #20540 (more of a severe API ergonomic issue)

**Comment by edwardw** [comment]
cc me

**Comment by bluss** [comment]
I updated the list in this issue. A lot of items are done now!

**Comment by retep998** [comment]
Has https://github.com/rust-lang/rust/issues/8995 been lost from this list somehow?

**Comment by bltavares** [comment]
Triaging: #20765 and #17825 are closed.

**Comment by alexcrichton** [comment]
This has basically all long since been implemented, so closing.

**Comment by dashed** [comment]
This isn't implemented yet: https://github.com/rust-lang/rust/issues/8995

**Comment by Centril** [comment]
What happened to associated const bounds as in the following? An omission perhaps?

```rust
trait Foo {
    const Bar: usize;
}

fn baz<T: Foo<Bar = 1>>() {}
```

cc @SergioBenitez
