### ISSUE TITLE
Automation metabug

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#17356]
Unprioritized list of automation tasks.

* [x] bundling mingw https://github.com/rust-lang/rust/issues/11782
* [x] fully test windows https://github.com/rust-lang/rust/issues/16457
* [x] rev1 mingw-w64 64-bit toolchain https://github.com/rust-lang/rust/issues/17394
* [x] rust/cargo install https://github.com/rust-lang/rust/issues/16456
* [x] release channel https://github.com/rust-lang/rust/issues/16677
* [x] out of sync nightlies https://github.com/rust-lang/rust/issues/14431
* [x] feature staging https://github.com/rust-lang/rust/issues/16678
* [x] valgrind https://github.com/rust-lang/rust/issues/13217
* [ ] testing 32 bit on distcheck https://github.com/rust-lang/rust/issues/17344
* [x] 32-bit cargo on CentOS
* [x] OSX auto builds are segfaulting (no issue)
* [x] high-5 https://github.com/rust-lang/rust/issues/16674
* [x] merging win32/64 bots https://github.com/rust-lang/rust/issues/17354
* [x] cloudfare sync is weird https://github.com/rust-lang/rust/issues/16649
* [x] msys2 win32 https://github.com/rust-lang/rust/issues/17347
* [ ] lexer tests https://github.com/rust-lang/rust/issues/15880
* [x] benchmark bot https://github.com/rust-lang/rust/issues/12458
* [x] lldb tests https://github.com/rust-lang/rust/issues/16112
* [ ] test more OS X https://github.com/rust-lang/rust/issues/17269
* [x] OSX is segfaulting with nightlies https://github.com/rust-lang/rust/issues/16489
* [ ] more android slaves https://github.com/rust-lang/rust/issues/16795
* [x] increase builds/slave https://github.com/rust-lang/rust/issues/17395
* [ ] doc/master -> doc/nightly https://github.com/rust-lang/rust/issues/17398
* [x] license packaging https://github.com/rust-lang/rust/issues/17690
* [x] doc installation https://github.com/rust-lang/rust/issues/14916
* [x] shutdown idle slaves https://github.com/rust-lang/rust/issues/18151
* [x] losing windows slaves https://github.com/rust-lang/rust/issues/18703
* [x] nightlies running at wrong time https://github.com/rust-lang/rust/issues/18912
* [x] stability upload fails incorrectly https://github.com/rust-lang/rust/issues/19079
* [x] remove metrics infra https://github.com/rust-lang/rust/issues/19145
* [x] doc tools on dist bots https://github.com/rust-lang/rust/issues/19200
* [x] mac minis -> macstadium https://github.com/rust-lang/rust/issues/19286
* [x] guidelines https://github.com/rust-lang/rust/issues/19315
* [x] rust-by-example https://github.com/rust-lang/rust/issues/19455
* [x] release signing https://github.com/rust-lang/rust/issues/13252
* [x] snap signing https://github.com/rust-lang/rust/issues/13254
* [ ] upload rustup.sh https://github.com/rust-lang/rust/issues/19505
* [ ] test 'make install' https://github.com/rust-lang/rust/issues/19698
* [x] install an uninstall script https://github.com/rust-lang/rust/issues/20283
* [ ] fix dist security https://github.com/rust-lang/rust/issues/20629
* [ ] package dbg std https://github.com/rust-lang/rust/issues/20630
* [x] directory listings https://github.com/rust-lang/rust/issues/20838
* [x] update rustup for beta https://github.com/rust-lang/rust/issues/21149
* [ ] install source https://github.com/rust-lang/rust/issues/19535
* [ ] get rid of cloudfront https://github.com/rust-lang/rust/issues/21239
* [ ] cargo dist dir https://github.com/rust-lang/rust/issues/21240
* [x] machine readable dist index https://github.com/rust-lang/rust/issues/21241
* [x] channel metadata https://github.com/rust-lang/rust/issues/21243
* [ ] windows dist locking bug https://github.com/rust-lang/rust/issues/21434
* [x] ec2 spot instances https://github.com/rust-lang/rust/issues/21904
* [ ] cargo compatibility bots https://github.com/rust-lang/cargo/issues/1276
* [ ] rust package desyncing https://github.com/rust-lang/rust-buildbot/issues/7
* [x] cross-platform type system consistency for std https://github.com/rust-lang/rust/issues/22228
* [ ] slave per build https://github.com/rust-lang/rust/issues/22448
* [x] fix build date https://github.com/rust-lang/rust/issues/22774
* [x] permission denied on windows https://github.com/rust-lang/rust/issues/22628
* [x] beta/stable integration automation https://github.com/rust-lang/rust/issues/23756
* [ ] doc translation services https://github.com/rust-lang/rust/issues/25660
* [ ] upload feature list https://github.com/rust-lang/rust/issues/25724
* [x] www.rust-lang.org SSL https://github.com/rust-lang/rust/issues/13180
* [ ] move from buildbot to taskcluster?
* [x] turn off ssh on play.rlo https://github.com/rust-lang/rust/issues/25811
* [ ] signing key revcert https://github.com/rust-lang/rust/issues/25814
* [x] keybase.io https://github.com/rust-lang/rust/issues/25815
* [x] convert playpen sandbox https://github.com/rust-lang/rust-playpen/issues/134

**Comment by edunham** [comment]
This list represents the unchecked items in brson's list, sorted into categories which roughly correlate to what action they look like they'll need next, and annotated with summaries/updates where necessary. Duplicating mainly so I can have permissions on a copy of the list, with issue numbers turned into links correctly.

### Brson's Notes-To-Self
- [ ]  upload rustup.sh #19505
- [ ]  channel metadata #21243
- [ ]  fix build date #22774
- [ ]  windows dist locking bug #21434
- [ ]  doc translation services #25660

### Things that got closed or became a different issue
- [ ]  release channel ~~#16677~~  #23757 is only surviving child of this issue
- [ ]  beta/stable integration automation #23756  -- closed for
https://github.com/rust-lang/rust/issues/23757
- [ ]  more android slaves #16795 -- will probably fork into enabling more
android configs, if that doesn't exist yet
- [ ]  rust package desyncing rust-lang/rust-buildbot#7 -- is closed now, yay
- [ ]  cross-platform type system consistency for std #22228 -- original bug got
closed; needs new bug?
- [ ]  remove metrics infra #19145 -- it got finished, then closed, then
reopened by a comment referencing https://github.com/servo/html5ever/issues/72

### Things that look "easy"
- [ ]  benchmark bot #12458 -- looks "easy" if stuff still works
- [ ]  doc/master -> doc/nightly #17398  -- pretty sure i can do this one, but
is it dev.rust-lang.org or static.rust-lang.org bucket?
- [ ]  test 'make install' #19698  -- has caused pile of bugs. maybe not done
yet because slow? should be "easy"
- [ ]  guidelines #19315  -- work done in
https://github.com/rust-lang/rust/pull/22331 needs to be linked from somewhere
- [ ]  snap signing #13254  -- directly from
https://github.com/rust-lang/rust/issues/13252
- [ ]  upload feature list #25724 -- looks clearly defined, could be a good
first "real bug"
- [ ]  www.rust-lang.org SSL #13180 -- kick nginx and the DNS

### Buildbot things, or things that'll change a lot if we switch CI
- [ ]  slave per build #22448 -- nice-to-have
- [ ]  fix dist security #20629  -- needs BUILDBOT to become https
- [ ]  ec2 spot instances #21904  -- looks like a matter of
read-the-linked-manual
- [ ]  move from buildbot to taskcluster?

### Everything Else (mostly things that need design decisions)
- [ ]  testing 32 bit on distcheck #17344 -- need to add more cases to make
check. Slowdowns incoming!
- [ ]  lexer tests #15880 -- hello, yak (hairier than its cousin the yacc)...
- [ ]  test more OS X #17269 -- tools are identified; licensing situation
unknown
- [ ]  losing windows slaves #18703 -- needs troubleshooting
- [ ]  doc tools on dist bots #19200 -- needs design decision
- [ ]  mac minis -> macstadium #19286  -- needs research, design, implementation
- [ ]  package dbg std #20630  -- needs design decision
- [ ]  install source #19535 -- needs design decision
- [ ]  get rid of cloudfront #21239 -- turned into artifact invalidation. lots
of noise here; having it broken makes many people very unhappy
- [ ]  cargo dist dir #21240 -- design decision kinda made; needs implementation
knowledge
- [ ]  cargo compatibility bots rust-lang/cargo#1276  -- cargo needs better
tests
