### ISSUE TITLE
Implement where clauses

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#17657]
Tracking https://github.com/rust-lang/rfcs/pull/135.

**Task list:**
- [x] PR #20002: Parse and process where clauses not attached to parameters.
- [x] #20019: Reject where clauses that do not mention a type parameter.
- [x] #20020: Check that the bounds of impl are implied by trait in a more general way.
- [x] #20023: Parse and accept outlives expressions in where clauses.
- [ ] #20021: Permit unsatisfiable methods to be omitted.
- [x] #20022: Permit higher-ranked qualifiers to enclose the self type
 - [ ] #20041: Accept type equality constraints in where clauses

**Comment by aturon** [comment]
Nominating for removal from P-backcompat-libs; enough has landed for us to already roll this out.

**Comment by pnkfelix** [comment]
removing from P-backcompat-libs (since the back compat stuff is done).  P-high.

**Comment by camelid** [comment]
ping from triage

**Comment by nikomatsakis** [comment]
This is close enough to done that we are going to close it -- the two remaining issues can be resolved independently.
