### ISSUE TITLE
Implement / optimize the shootout benchmarks

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/rust#18085]
This is supposed to be a meta issue for optimization efforts like http://www.reddit.com/r/rust/comments/2j2ij3/benchmark_improvement_reverse_compliment/

The benchmarks to optimize (where rustc is slower than g++, according to http://benchmarksgame.alioth.debian.org/u64q/rust.php):
- [x] binary-trees
- [x] pidigits
- [x] mandelbrot
- [x] fannkuch-redux (fixed by #16999)
- [ ] fasta
- [ ] k-nucleotide
- [ ] n-body
- [x] reverse-complement (fixed by #18143, #18357)
- [x] spectral-norm (fixed by #17989)
- [ ] regex-dna
- [ ] fasta-redux (Rust version missing)

Secondary benchmarks:
- [ ] meteor-contest
- [ ] chameleos-redux
- [ ] thread-ring
- [ ] binarytrees-redux

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#665
