### ISSUE TITLE
Unboxed closure metabug

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#18101]
This is a metabug for tracking work remaining to be done on unboxed closures. It contains only the high-level remaining issues. For a comprehensive list of closure bugs, [search using the A-closures label](https://github.com/rust-lang/rust/labels/A-closures).

1.0 Issues

- [ ] #20872 -- Make `Fn` traits be treated like everything in trait selection
- [x] #19982 -- ICE using parenthetical notation in impls
- [ ] #11740 -- Unexplained lifetime error in closure type 
- [x] #18835 -- Unable to manually implement `FnOnce`
- [x] #23015 -- Impl `FnMut` for `&mut F` where `F: FnMut` 

Completed issues

- [x] #20871 -- Make return type of the `Fn` traits an associated type
- [x] #21603 -- Allow individual upvars to be moved
- [x] #16640 -- Implement unboxed closure upvar inference
- [x] #18799 -- Infer `move` using `Send` trait
- [x] #16749 -- `|&mut:|` wants (`Copy`) upvar to be mutable when it shouldn't 
- [x] #17881 -- Bad type inference error message with unboxed closures 
- [x] #18875 -- Adjust feature gates
- [x] #17908 -- clarify lifetimes in closure return type syntax 
- [x] #12831 -- by-ref closure capture semantics are a backwards compatibility hazard 
- [x] #17661 -- Implement higher-ranked trait bounds 
- [x] #14798 -- Remove old (boxed) closures from the language 
- [x] #18387 -- Fn trait hierarchy not respected
- [x] #18992 -- Parentheses notation should support lifetime elision
- [x] #19817 -- unboxed closures should not be implicitly copyable
- [x] #19836 -- should pretty-print with parenthesized notation
- [x] #19730 -- "perfect forwarding" traits are not accepted by HRTB 
- [x] #17551 -- ICE on generic type inference failure for unboxed closures
- [x] #17545 -- ICE using explicit lifetime with unboxed closures 
- [x] #17060 -- ICE fictitious type O in sizing_type_of() 
- [x] #17021 -- ICE when using unboxed closures 
- [x] #16939 -- ICE calling an unboxed closure with the wrong number of parameters inside another closure
- [x] #16808 -- Unboxed closures ICE when debug println!()d 
- [x] #16791 -- ICE related to sizing of unboxes closures 
- [x] #16790 -- ICE in metadata::tydecode::parse_def_id related to unboxes closures 
- [x] #16774 -- Running into segmentation fault with new closures 
- [x] #16739 -- ICE: When creating Box<FnOnce<(), ()>> from unsugared unboxed closure 
- [x] #16672 -- ICE returning unboxed closure 
- [x] #18057 -- internal compiler error 
- [x] #17816 -- Unboxed closure ICE: cannot relate bound region: ReInfer(16) <= ReLateBound 
- [x] #18378 -- Unboxed closures ICE: Expected(expected EBML doc with tag EsEnumVid but found tag 27)
- [x] #18453 -- Unboxed closures and traits ICE
- [x] #20582 -- normalization failure in return type in impl
- [x] #17403 -- Aliasing rules are broken for closures 
- [x] #16560 -- Struct + Fn fulfills `Send`, but sugary version `|&: ...|` does not 
- [x] #16929 -- Cannot call a unboxed-closure trait object with () syntax
- [x] #18385 -- Overloaded call notation doesn't work with trait bounds
- [x] #16814 -- Unboxed closures: `ref`-prefixed closures still capture by value 
- [x] #16668 -- Unboxed closures: cannot borrow data mutably in aliasable location 
- [x] #17961 -- Function pointers should implement the various Fn* types 
- [x] #17907 -- Unboxed closures: Type inferencer failed to detect closure argument types 
- [x] #17703 -- unboxed closure sugar not working in trait objects 
- [x] #18772 -- `Box<Fn() + 'static>` not accepted

**Comment by steveklabnik** [comment]
Given that only two issues remain, I don't think this metabug is particularly valuable anymore, so I'm gonna close it.
