### ISSUE TITLE
Implement collections reform

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#18424]
Tracking issue for https://github.com/rust-lang/rfcs/pull/235, there are a number of sub-issues associated with this:

Backwards incompatible changes to make:

* [x] [Remove collections traits](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#removing-the-traits) - @alexcrichton https://github.com/rust-lang/rust/pull/18474
* [x] [Add a `Borrow` trait](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#the-borrow-trait) - @aturon #18910
* [x] [Add methods using the `Borrow` trait, deprecating `_equiv` methods](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#using-borrow-to-replace-_equiv-methods) - @aturon #18910
* [x] [Ensure construction methods follow conventions](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#construction) -
* [x] [Ensure `FromIterator` is implemented](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#the-fromiterator-trait) - @gamazeps 
* [x] [Ensure insertion methods follow conventions](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#insertion) -
* [x] [Rename `Extendable` to `Extend`](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#the-extend-trait-was-extendable) - @gamazeps  https://github.com/rust-lang/rust/pull/18475
* [x] [Ensure `Extend` is implemented](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#the-extend-trait-was-extendable) - @gamazeps  https://github.com/rust-lang/rust/pull/18475
* [x] [Ensure deletion methods follow conventions](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#deletion) -
* [x] [Ensure inspection/mutation methods follow conventions](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#inspectionmutation) -
* [x] [Implement `Index` and `IndexMut` where appropriate](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#the-index-trait) - @alexcrichton - https://github.com/rust-lang/rust/pull/18445
* [x] [Ensure iteration methods follow conventions](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#iteration) -
* [x] [Ensure capacity-related methods follow conventions](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#capacity-management) -
* [x] [Implement bounded iterators for `TreeMap`](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#bounded-iterators)
* [x] [Ensure set operations follow conventions](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#set-operations) -
* [x] [Ensure map operations follow conventions](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#map-operations) -
* [x] [Implement `Deref` for strings and vectors](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#relating-vec-and-string-to-slices) - @alexcrichton - https://github.com/rust-lang/rust/pull/18443
* [x] [Ensure string api related methods are follow utf8/byte conventions](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#string-api) -
* [x] [Add `repeat` to `std::iter` and the prelude](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#removing-methods-like-from_elem-from_fn-grow-and-grow_fn) - @jakub- https://github.com/rust-lang/rust/pull/18468

Backwards compatible changes that will require additional language features:

* [ ] [Add `ByNeed` and `Predicate` traits](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#minimizing-variants-byneed-and-predicate-traits) (needs negative bounds to work with unboxed closures)

Backwards compatible changes to make:

* [x] [Add `Cow` pointers](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#clone-on-write-cow-pointers) - @aturon #18910
* [x] [Add `IntoIterator`](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#intoiterator-and-iterable) - @aturon
* [x] [Move `for`-loops to use `IntoIterator`](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#benefits-of-intoiterator) - @jakub-
* [x] [Implement partitioning via `FromIterator`](https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#minimizing-method-variants-via-iterators) - @aturon

**Comment by alexcrichton** [comment]
This issue has been growing stale for some time now, and I think that we're basically all done with the implementation work, so closing.

**Comment by zommiommy** [comment]
From my understanding, this RFC was blocked due to the lack of support for HKT.

The proposed HKT version of the `Iterable` trait is currently supported in stable:
```rust
trait Iterable {
    type A;
    type I<'a>: Iterator<&'a Self::A>;

    fn iter(&self) -> Self::I<'_>;
}

trait IterableMut {
    type A;
    type I<'a>: Iterator<&'a mut Self::A>;

    fn iter_mut(&self) -> Self::I<'_>;
}
```

so it might be worth re-discussing this
