### ISSUE TITLE
std::path and path-related metabug

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#18720]
In prep for 1.0 stabilization, this metabug collects the various known API issues for `std::path`. These issues need to be triaged.

Semantic problems:

* [ ] path: Windows paths may contain non-utf8-representable sequences #12056 
* [ ] Windows verbatim paths shouldn't normalize path when .push-ed #11594 
* [ ] std::path::posix::Path should not automatically normalize #14028 
* [ ] Path::join should concat paths even if the second path is absolute #16507 

Ergonomics:

* [ ] Path::dirname should return Path instead of [u8] #14049 
* [ ] GenericPath dirname and dirname_str should be removed #10035 
* [ ] Path::new should return Option<Path> vs. failing (if there is a null byte) #14048 

Implementation:

* [ ] `pub use` and `GenericPath` versus new `sys` setup

Missing functionality:

* [ ] Make os::make_absolute logic available for arbitrary Paths #5003 
* [ ] We need fs::realpath #11857

**Comment by alexcrichton** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/20034
