### ISSUE TITLE
Library modernization blockers

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#19186]
This is a list of the blockers (ICEs/bugs) that I found while attempting to modernize the standard library with features like unboxed closures and associated types. This list serves two purposes:

- It should signal which parts of the standard library become actionable. For example, after #19126 gets fixed, the `Option`/`Result` API can be updated to use unboxed closures.
- As a list of high priority FIXMEs.

# Unboxed closures

-> Move library code away from boxed closures (part of #14798)

## In function arguments

`Option`, `Result`, etc

``` rust
// from
fn map<U>(self,  f: |T| -> U) -> Option<U>;
// to
fn map<U, F: FnOnce(T) -> U>(self,  f: F) -> Option<U>;
```

### Blockers

- [x] the trait `Fn<(&_,), &_>` is not implemented for the type `fn(&'a u8) -> &'a u8` #19126 (AFAIK, this will be a compiler change, and will need a snapshot)

## In structs fields

`core::iter::Map`

``` rust
struct Map<A, B, I, F> where I: Iterator<A>, F: FnMut(A) -> B {
    iter: I,
    f: F,
}
```

Main issue here is that closures have anonymous types, so they can't be part of the signature of functions, structs, etc. See https://github.com/rust-lang/rust/issues/19186#issuecomment-64425312
and/or https://github.com/rust-lang/rust/issues/18101#issuecomment-61416554 for more details.

### Use bare functions instead of closures that capture nothing

`core::str::Bytes`, `core::str::AnyLines`
`collections::btree::Keys`, `collections::hash_map::Values`

As pointed by @sfackler: If the closure captures nothing, we can use a bare function instead.

``` rust
type Bytes<'a> = Map<&'a u8, u8, slice::Items<'a, u8>, fn(&u8) -> u8>;

// Self = str
fn bytes(&self) -> Bytes {
    fn deref(&b: &u8) -> u8 { b }
    self.as_bytes().iter().map(deref)
}
```

#### Blockers

- the trait `Fn<(&_,), &_>` is not implemented for the type `fn(&'a u8) -> &'a u8` #19126

### Use boxed closures otherwise

*Add examples here*

#### Blockers

- [x]  `Box<Fn(int) -> int + 'static>` is not accepted: "explicit lifetime bound required" #18772 (Fixed in #19298, but needs to get snaptshot-ed)

# Associated types

-> Update library code for associated output types #17826

There are several issues in this area, so I'll list the blockers in increasing complexity order:

## Extension traits with only output types

`AdditiveIterator`, `MultiplicativeIterator`, etc

### Blockers

- [ ] ICE: When cross-crate importing trait with associated output types https://github.com/rust-lang/rust/issues/18048#issuecomment-63867112 (this one blocks any work with associated types)
- [x]  rustdoc panics when dealing with associated types #18594 (this one also blocks any work with associated types)
- [x]  Associated types Order can cause ICE #18611 (can be worked around by shuffling the code around, but fixing it should reduce the amount of code churn)

## Traits with only output types that are used for GP

`AsSlice`, `Hasher`, etc

### Blockers

- [x]  ICE: When using an associated type as the type parameter of a bound #19081
- [x]  Support the `Trait<Output=Type>` syntax #18432 

## Traits with input and output types

`Add`, `Mul`,  `Sub`, etc

### Blockers

- [x] ICE: When implementing trait with a generic parameter and an associated output type #19129 

---

It's likely that we'll find more blockers as we progress, so I'll try to keep this list up to date.

cc @alexcrichton @aturon @nick29581 @nikomatsakis

**Comment by AndyShiue** [comment]
Can this be closed?

**Comment by japaric** [comment]
> Can this be closed?

Yes. There are still blockers (mainly for assoc types) but I'm working with @nikomatsakis in a tight feedback loop (on IRC) so this issue is not relevant anymore.
