### ISSUE TITLE
Stabilization for 1.0-alpha2

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#20761]
This is a tracking issue for stabilization of both APIs and gated features.

### General passes

* [ ] Pass over all `#[deriving(Trait)]`
* [ ] integer auditing https://github.com/rust-lang/rust/issues/22240
  * [ ] `column!` #19284

### Modules that need further scrutiny

* [x] `any` - @alexcrichton #21165 
  * [ ] `BoxAny` blocked on #18737
* [x] `bitflags` @alexcrichton #21254
* [x] `borrow` - @aturon #22210, blocked by #22246
* [x] ~~`error`~~ - @aturon (leaving `Error` trait unstable until `Reflect` is ready)
* [x] `intrinsics` - @alexcrichton #21165
* [x] `io`- @alexcrichton / @aturon, rust-lang/rfcs#576, #21835
  * [x] `ffi::OsString` - @aturon #21488 
  * [x] `std::env` - @alexcrichton, rust-lang/rfcs#578, #21787
  * [x] `std::fs` - @alexcrichton, rust-lang/rfcs#739, #21936
  * [x] `std::process` - @aturon, rust-lang/rfcs#579, #22119
  * [x] `std::net` - @alexcrichton, rust-lang/rfcs#807, #22015
  * [x]  ~~deadlines - rust-lang/rfcs#577~~
* [ ] `marker` - @nikomatsakis / @aturon, rust-lang/rfcs#738
* [x] `os` - @alexcrichton / @aturon, rust-lang/rfcs#578, #21787
* [x] `path` - @aturon, rust-lang/rfcs#474, #21759
* [x] `rand` - @huonw, ~~rust-lang/rfcs#722~~, #21892
* [x] ~~`time`~~ - leaving unstable for now
* [x] ~~`thunk`~~ - leaving unstable

### Modules that should move to `#[stable]` once dust settles

* [x] `ascii` - #22024
* [ ] `ffi` - @alexcrichton, rust-lang/rfcs#556, rust-lang/rfcs#592, #21926, #22482
* [x] `fmt` - @alexcrichton ~~#21457~~, #21713, #21870
* [x] `hash` - @alexcrichton, rust-lang/rfcs#823, #22480
* [x] `thread` - @aturon #20615

### Misc stabilization

* [x] `FromStr` - #21718
* [x] `FromIterator::from_iter` - #21870
* [x] `Peekable::peek` - #21870
* [x] `Atomic{Usize,Isize}` - #21794

### Pending RFCs

* [x] [io and os reform](https://github.com/rust-lang/rfcs/pull/517/)
* [x] [variance markers](https://github.com/rust-lang/rfcs/pull/738)

## Crates to move out

* [ ] `libtest`

## Feature gates to remove

* [x] ~~`box_syntax`~~
* [x] `unsafe_destructor` #21972

## CLI Tooling

* [ ] command line flags - #19051, #19900
* [ ] lints - #21761

**Comment by aturon** [comment]
Nominating for 1.0-beta milestone.

**Comment by aturon** [comment]
Stability requests from users are [on a discuss thread](http://users.rust-lang.org/t/using-unstable-apis-tell-us-about-it/157).

**Comment by alexcrichton** [comment]
I'm going to try to keep track of all requests from the discuss thread [in a gist](https://gist.github.com/alexcrichton/0394d018660c15609212)

**Comment by aturon** [comment]
This is subsumed by the new beta stabilization tracker, which includes the last changes prior to alpha2: https://github.com/rust-lang/rust/issues/22500

Closing!
