### ISSUE TITLE
Tracking issue for RFC 517: IO reform

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#21070]
Tracking for rust-lang/rfcs#517

### Areas that still need RFC amendments:

* [ ] Timeouts
* [x] stdin/stdout/stderr - rust-lang/rfcs#899, #23292
* [x] TempDir - #23081
* [x] timers/sleeping (probably just a `sleep` function) - #23330
* [x] ~~write! macro~~ (WONTFIX)
* [x] make the new io modules all hook into each other (std::env use new paths) #22727
* [x] ErrorKind - #23292, #23430
* [ ] exit statuses 

### Areas that need more scrutiny before stabilization

* [x] Various `std::os::platform` extensions -- no clear plan for these yet #23353
* [ ] `AsRawFd` and friends -- need a `FromRawFd` etc

**Comment by aturon** [comment]
Note: this is a metabug that will link to individual tracking issues as each piece of the RFC is separately accepted.

**Comment by aturon** [comment]
cc @alexcrichton

**Comment by aturon** [comment]
I've added some tracking information for smaller details that haven't been addressed yet.

**Comment by aturon** [comment]
Nominating for 1.0-beta P-backcompat-libs -- this should be the last issue standing for IO reform.

**Comment by pnkfelix** [comment]
1.0 beta P-backcompat-libs

**Comment by alexcrichton** [comment]
I've added a new RFC for stdout/stdin/stderr: https://github.com/rust-lang/rfcs/pull/899

**Comment by l0kod** [comment]
Probably #12148 too.

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rfcs/issues/939, future extensions to `std::fs`

**Comment by blaenk** [comment]
You can check TempDir now.

**Comment by l0kod** [comment]
cc #11203

**Comment by pnkfelix** [comment]
closing as implemented; everything in RFC as written/accepted is now implemented.

**Comment by newpavlov** [comment]
What about `core::io` [part](https://github.com/rust-lang/rfcs/blob/master/text/0517-io-os-reform.md#modules) of RFC? In my opinion this issue should be reopened. Related issues: #15568, #1314
