### ISSUE TITLE
Tracking issue for Integer Overflow (RFC 560)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#22020]
RFC: https://github.com/rust-lang/rfcs/pull/560
Final text: https://github.com/rust-lang/rfcs/blob/master/text/0560-integer-overflow.md

List of tasks to accomplish:

- [x] Optional error checking on `+`, `-`, `*` #22532
- [x] Implement `wrapping_add`, `wrapping_sub`, `wrapping_mul` from the `WrappingOps` trait #22532
- [x] Optional error checking on `/`, `%` (we currently check unconditionally; see #8460)
- [x] Implement `wrapping_div`, `wrapping_rem` from the `WrappingOps` trait (see https://github.com/rust-lang/rfcs/issues/964) #24420
- [x] Optional error checking on `<<` and `>>` #23536 
- [x] Implement `wrapping_lshift`, `wrapping_rshift` from the `WrappingOps` trait
   - (renamed to `wrapping_shl`, `wrapping_shr`.) #24420
- [x] Optional error checking on unary `-` for signed values #24500 
- [x] Implement `wrapping_neg` from the `WrappingOps` trait #24420 
- [ ] Lint for use of one of the potentially fallible operations in an `unsafe` fn or fn containing `unsafe` blocks
  - Note that the use need not occur *in* an `unsafe` block, just a fn containing `unsafe` blocks
- [x] Option to forcibly enable overflow checking
- [x] Overflow checking disabled by default when optimizations are enabled - #22980
- [x] Fix const_eval to do overflow checking based on declared type rather than `u64`/`i64` (on all of the above cases) - #23863 (#22531)

----

- [ ] ~~Optional error checking on `as` (see http://internals.rust-lang.org/t/on-casts-and-checked-overflow/1710/15)~~
- [ ] ~~Implement `wrapping_as_X` methods from the `WrappingOps` trait~~
  -  (above two are no longer needed since `as` has been [re]defined to never panic).
- [ ] consider saturating cast operations https://github.com/rust-lang/rust/issues/23596

**Comment by aturon** [comment]
cc @nikomatsakis

**Comment by aturon** [comment]
cc @Aatch

**Comment by glaebhoerl** [comment]
(cc #20795)

**Comment by pnkfelix** [comment]
(cc #22532)

**Comment by pnkfelix** [comment]
@aturon does a `-Z` flag count for "Option to forcibly enable overflow checking" ?

**Comment by aturon** [comment]
@pnkfelix I'm not sure; I wasn't the one who updated this with a checklist. @nikomatsakis @alexcrichton?

**Comment by alexcrichton** [comment]
I would personally consider a `-Z` flag to fit the bill

**Comment by nikomatsakis** [comment]
Interesting. I consider a `-Z` flag adequate for *this* bug, perhaps,
but not a good overall solution. However, it seems like having a good
set of public flags around this falls under
https://github.com/rust-lang/rust/issues/22492

**Comment by jmesmon** [comment]
May also want to add:

- [ ] Implement wrapping_negate method from the WrappingOps trait

(or whatever it should be named)

To match with:

- [ ] Optional error checking on unary `-`

**Comment by pnkfelix** [comment]
for consistency with the `Shl` trait etc in `core:ops`, we probably should name the wrapping shift methods `wrapping_shl`, etc

**Comment by pnkfelix** [comment]
@aturon to be 100% clear, the lint that is described here:
> Lint for use of one of the above operations in an unsafe fn or fn containing unsafe blocks 

is a reference to the [lint section] of the RFC, and therefore is talking about linting for uses of `{+, -, *, <<, >>, as <integral-type>}` in a function with `unsafe` blocks, and *not* about linting for uses of the newly added WrappingOps methods in such functions...

[lint section]: https://github.com/rust-lang/rfcs/blob/master/text/0560-integer-overflow.md#lint

Right?

**Comment by aturon** [comment]
@pnkfelix I didn't make the detailed list here -- I would check with @nikomatsakis

**Comment by freebroccolo** [comment]
cc me

**Comment by nikomatsakis** [comment]
@pnkfelix correct

**Comment by pnkfelix** [comment]
(regarding shift behavior, I thought the (old) discussion on #1877 was interesting.  In particular there is a semi-open question of whether we should follow Java in our fallback behavior for the RHS of a shift, or if we should just pass it directly to LLVM, and live with underspecification in general.)

**Comment by glaebhoerl** [comment]
If we weren't willing to live with underspecification around the result of arithmetic overflows (with checks off), then it seems we should be consistent and be the same way with respect to shifts also.

**Comment by pnkfelix** [comment]
@glaebhoerl yes that is a reasonable conclusion to draw.

In any case, I have left a prominent spot in the code indicating what lines to uncomment to follow Java's approach; see:
  https://github.com/rust-lang/rust/pull/23536/files#diff-88ce76a36e25f7f0d19bc4cdd58ee1b8R2584

**Comment by pnkfelix** [comment]
@glaebhoerl okay, due to #10183 and #23551, my mind is now completely turned around on this issue: As far as I can tell, we must ensure that the input-rhs is in the range `[0, sizeof(lhs_t)*8]`, because otherwise LLVM can produce nonsense.

**Comment by pnkfelix** [comment]
I don't know how this managed to avoid getting nominated up until now.

triage: P-backcompat-lang (1.0)

**Comment by pnkfelix** [comment]
I think all of the backwards compatibility issues have now been resolved.

**Comment by pnkfelix** [comment]
Not sure how important that lint was.  Nominating for discussion at next triage mtg.

**Comment by pnkfelix** [comment]
triage: P-medium

**Comment by pnkfelix** [comment]
(oops I added a "triage:" comment and then deleted it, but of course rust-highfive cannot turn back time.)

**Comment by pnkfelix** [comment]
My intent was to nominate, but also suggest a P-medium assignment for the remaining work here.   I will put back the P-backcompat-lang label.

**Comment by pnkfelix** [comment]
triage: Remaining work is P-medium (at most).... lint may only qualify as a "nice to have" at this point, it is unclear how important it will be.

**Comment by alexcrichton** [comment]
I believe this has basically all been implemented, so closing.

**Comment by pnkfelix** [comment]
(Well there is the lint that was listed in the description, but its questionable whether we actually need/want that...)
