### ISSUE TITLE
`box` and `in` expressions (tracking issue for RFC 809)

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#22181]
Tracking issue for https://github.com/rust-lang/rfcs/pull/809. This should be filled out with TODO items. Note that in this case there are some [unsettled design questions](https://github.com/rust-lang/rfcs/pull/809#issuecomment-73910414) to be resolved as well.

To do:
- [x] land placement-`in` desugaring implementation
- [ ] land overloaded-`box` desugaring implementation
- [ ] port `libstd` APIs to support `in`
- [ ] port `libstd` APIs to support `box`
- [ ] resolve/finalize syntax for placement-`in`
- [ ] investigate improvement of inference, coercion, and cast interactions (subissues #22221, #22403, #22405)
- [ ] improve error messages when code is rejected (#22231)

Unresolved questions:
- [ ] best precedence for `box` (was https://github.com/rust-lang/rust/issues/21192)

**Comment by pnkfelix** [comment]
Status update: https://internals.rust-lang.org/t/lang-team-minutes-feature-status-report-placement-in-and-box/4646

**Comment by nikomatsakis** [comment]
@aidanhs has proposed to remove these features in https://github.com/rust-lang/rust/pull/48333, and the proposal is being actively discussed. =)

**Comment by aidanhs** [comment]
Placement new is imminently about to be/has been removed as an unstable feature and the RFCs unaccepted. The approved/merged PR is at #48333 and the tracking issues were at #22181 (this issue) and #27779. Note that this does not affect box syntax.

You can find the summary comment at https://github.com/rust-lang/rust/issues/27779#issuecomment-378416911.

Find the internals thread where you can discuss this more at https://internals.rust-lang.org/t/removal-of-all-unstable-placement-features/7223. Please add any thoughts there.
