### ISSUE TITLE
Audit integer types in the standard library

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#22240]
Below is a list of modules that contain text matching the regular expression `\bu?int\b` and which are intended to be stable. In some cases, these terms only appear in comments (which should still be fixed). In some cases, I have simply put `..` after a directory to indicate all files within that directory. Please sign up for modules in comments below and I will endeavor to keep this list up to date with who is working on what (if you have sufficient privileges, feel free to edit the comment directly).

### Guidelines to follow

These are the guidelines that we intend to follow in the standard library. These guidelines are not intended as universal guidelines to be used outside the standard library (though of course one might choose to do so).

0. Use unsigned values if the value should always be greater than or equal to zero, and signed values otherwise.
1. For indices, pointers, or other values which are tied to a data structure whose size is proportional to the size of memory, use `usize` or `isize`.
2. For cases where the acceptable domain of a value *perfectly fits* a fixed number of bits, use the appropriate fixed-size type. For example, a method like `write_u16` would take a `u16` argument.
3. Otherwise, use `i32/u32` if the value has a narrow range and `i64/u64` otherwise.

Examples:
* Vector indices and hashmap lengths use `usize`.
* The size of a file would be `u64`, as the maximum size of a file is not tied to addressable memory.
* Something like `write_u16` takes a `u16` (shocker, I know!)
* The radix of an integer would use `u32`.
  * You might expect `u8`, since a radix higher than 256 is not useful, but the domain of useful radices is actually much smaller than `u8`, so using `u8` isn't providing a meaningful guarantee, and will simply increase friction.

### Module listing

* [x] libcollections/.. -- [Gankro](https://github.com/rust-lang/rust/issues/22240#issuecomment-74153425)
* [x] libcore/mem.rs -- @pnkfelix #22401 
* [x] libcore/ops.rs -- @nikomatsakis #22294 
* [x] libcore/result.rs -- @nikomatsakis #22294 
* [x] libcore/finally.rs -- @nikomatsakis #22294 
* [x] libcore/marker.rs -- @nikomatsakis (no ints/uints)
* [x] libcore/borrow.rs -- @pnkfelix #22485
* [x] libcore/fmt/.. @nick29581 #22700
* [x] libcore/char.rs -- petrochenkov #22339 
* [x] libcore/option.rs -- @nikomatsakis #22294 
* [x] libcore/default.rs -- @pnkfelix #22485
* [x] libcore/ptr.rs -- @nikomatsakis #22294 
* [x] libcore/clone.rs @brson ok. no use of ints
* [x] libcore/cmp.rs -- @pnkfelix #22485
* [x] libcore/str/.. -- petrochenkov #22339 
* [x] libcore/nonzero.rs -- @pnkfelix #22401 
* [x] libcore/cell.rs -- @pnkfelix #22401 
* [x] libcore/intrinsics.rs -- @pnkfelix #22485
* [x] libcore/num/.. @brson https://github.com/rust-lang/rust/pull/22600 pow is covered by https://github.com/rust-lang/rust/pull/22087
* [x] libcore/lib.rs @GuillaumeGomez
* [x] libcore/atomic.rs @brson. ok. everything is ptr size. bool is implemented as usize, but intentionally.
* [x] libcore/hash/.. @nick29581 #22700
* [x] libcore/panicking.rs @GuillaumeGomez #22507
* [x] libcore/macros.rs fixed by #21769 (@nick29581 (not my patch though))
* [x] libcore/raw.rs @brson. ok. one usize representing slice length
* [x] libcore/slice.rs @brson. ok. all usizes for indexes or ranges
* [x] ~~libstd/sys/common/..~~ - not public
* [x] ~~libstd/sys/windows/..~~ - not public
* [x] ~~libstd/sys/unix/..~~ - not public
* [x] libstd/collections/mod.rs -- [Gankro](https://github.com/rust-lang/rust/issues/22240#issuecomment-74153425)
* [x] libstd/ascii.rs -- petrochenkov #22339 
* [x] libstd/thread.rs -- @GuillaumeGomez
* [x] ~~libstd/os.rs~~ - will be `#[deprecated]`
* [x] libstd/num/.. @Gankro 
* [x] libstd/lib.rs -- @GuillaumeGomez
* [ ] libstd/thread_local/.. -- @vojtechkral
* [x] libstd/failure.rs -- file no longer exists
* [x] ~~libstd/io/buffered.rs~~ - will be `#[deprecated]`
* [x] libstd/sync/.. @nick29581 #22700
* [x] libunicode/.. #22339

**Comment by nikomatsakis** [comment]
Nominating for the 1.0 beta milestone.

**Comment by Gankro** [comment]
I'll finish up collections. Looks like I just missed some docs stuff.

**Comment by nikomatsakis** [comment]
(Updated comment till this point.)

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-lib.

**Comment by nikomatsakis** [comment]
cc @nick29581 @pnkfelix @aturon @alexcrichton @pcwalton @steveklabnik @wycats don't forget to sign up for somethin' ;)

**Comment by petrochenkov** [comment]
I'll take libunicode, char, str and ascii

**Comment by pnkfelix** [comment]
@nikomatsakis some of the uses of `int`/`uint` are just arising from what seem to be dummy types in examples in the documentation.  For example [this in cell.rs](https://github.com/rust-lang/rust/blob/97a9507232a714b8c9a4341901002f0b761210db/src/libcore/cell.rs#L81) where the edges in a hypothetical graph structure are `(uint, uint)` (and `edge.0`/`edge.1` are not being used for array indexing).

I sympathize with not wanting to jump into fully generic code in these examples.  But for consistency in the docs overall, what do we want our go-to type to be in these cases: `u32`, `i32`, or ... ?  (I'm guessing `i32` for consistency with integer fallback.

**Comment by Gankro** [comment]
Yes, my general rule when updating the docs is to try to have integer-fallback trigger and have i32 inferred, with explicit i32 when necessary.

So e.g. I use a lot of `let vec: Vec<_> = [1, 2, 3, 4].iter().cloned().collect();`

**Comment by nikomatsakis** [comment]
@pnkfelix as @Gankro said, I've mostly used `u32`/`i32` as my go to type for docs, if it seems that "generic integer" is all that's requested.

**Comment by vojtechkral** [comment]
`libcore/macros.rs` → cc #19284 , which is tightly related to how types are used in `codemap.rs`: the `Pos` trait uses `usize`, `BytePos` uses `u32` and `CharPos` uses `usize`. Why are these types chosen the way they are? Could they perhaps be changed so that #19284 is easier to fix?

**Comment by GuillaumeGomez** [comment]
I'll take `libstd/lib.rs`.

**Comment by GuillaumeGomez** [comment]
I take `libcore/lib.rs` too.

**Comment by brson** [comment]
the `panicking` modules have int types that need to change and are tied to lang items. It's all unstable though.

**Comment by GuillaumeGomez** [comment]
@brson: Not just the panicking. The entire libstd needs to be clean also.

**Comment by Gankro** [comment]
Doing `std/num/..`

**Comment by vojtechkral** [comment]
May I take the remaining `libstd/thread_local/..` ?

**Comment by nikomatsakis** [comment]
Seems like it's time for someone to just finish all that remains in one fell swoop.

**Comment by GuillaumeGomez** [comment]
Everything has been taken already, no ?

**Comment by vojtechkral** [comment]
@GuillaumeGomez Looks like it.

**Comment by nikomatsakis** [comment]
@GuillaumeGomez yes I suppose you are correct, but there are several with no listed PR, all assigned to you or @vojtechkral, can you guys attest that those are in the pipeline now? I can't quite tell from all the various citations appearing everywhere.

**Comment by GuillaumeGomez** [comment]
All attributed to me have been merged.

**Comment by vojtechkral** [comment]
Mine too.

**Comment by nikomatsakis** [comment]
Great, thanks to you both!
