### ISSUE TITLE
Stabilization for 1.0-beta

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#22500]
This is a tracking issue for stabilization of both APIs and gated features.

# Library stabilization

## Schedule

**GUIDE**:

* "Land" refers to landing larger changes
* "Stabilize" means marking `#[stable]`, no deep changes anticipated
* Items are checked off when a PR is open for them

### Week of Feb 9

* [x] Land: all path/IO reform PRs #21488 #22119 #21759 #22208 #21787 #21835 #21936 #22015
* [x] Land: std::env changes #22188
* [x] Stabilize: IntoIterator::into_iter
* [x] Stabilize: std::ascii #22024

### Week of Feb 16 - alpha2

* [x] Land: Kimundi's revised str API rust-lang/rfcs#528 #22466
* [x] Land: integer audit (tracking: #22240)
* [x] Land: std::ffi::CString changes #22482
* [x] Land: uses of new io stuff
    * [x] Cargo - rust-lang/cargo#360
    * [x] rustc - #22873, #23292
* [x] Stabilize: std::hash #22480
* [x] Stabilize: std::borrow #22210
* [x] Stabilize: IntoIterator #22454
* [x] Stabilize: std::marker #22286
* [x] Stabilize: std::thread #22435
* [ ] Stabilize: uses of #[derive] #22511
* [x] Stabilize: range/iteration story @aturon #23347

### Week of Feb 23

* [x] Land: overflow changes @nikomatsakis  #22532
* [x] RFC: stdin/stdout/stderr - rust-lang/rfcs#899, #22797
* [x] Deprecate  `old_io::process` - #23079
* [x] Deprecate `old_io::util` - #23010
* [x] Deprecate `old_io::net` - #22813
* [x] Deprecate `old_io::fs` - #22873
* [x] Deprecate `old_io::extensions` - #22880
* [x] Land: std::ptr changes (@alexcrichton) - #22729
* [x] Stabilize: std::env (move to new path) - #22727, #22869
* [x] Stabilize: std::process - #22882
* [x] Stabilize: std::ffi::OsStr/OsString - #22975
* [x] Generic conversation traits, `AsSlice`, `Str`: get RFC going again

### Week of Mar 2

* [x] Stabilize: some of std::io - #23010
* [x] Stabilize: std::fs - #23081
* [x] Stabilize: std::net - rust-lang/rfcs#923, #23352
* [x] Stabilize: std::ffi::CString - #22975
* [x] Stabilize: Unicode stuff in StrExt + CharExt - #23126
* [x] Land: revisions to Path (probably involving normalization) - @aturon #23229
* [x] Finalize RFC: stdin/stdout/stderr - rust-lang/rfcs#899, #23292
* [x] Decide on TempDir/temp_dir - #23081

### Week of Mar  9 - Possible to run serious code on stable Rust

* [x] Stabilize: all of std::io - #23292
* [x] Stabilize: std::path - #23229 
* [x] Several of top ten crates run on Rust Stable
* [x] Stabilize: APIs by demand (TBD)
* [x] Land: polish/tweaks (TBD)

### Week of Mar 16

* [x] Stabilize: std::error @aturon (needs Reflect) #23541
* [x] Stabilize: `Entry` @aturon #23509 
* [x] Land: final changes to std::num @aturon #23549
* [x] Land: `thread_local` changes @aturon #23557
* [x] Finalize RFC: Generic conversation traits, `AsSlice`, `Str` - @aturon rust-lang/rfcs#529 23538

### Week of Mar 23

* [x] Stabilize: rt::unwind::try @alexcrichton #23651
* [x] Stabilize: APIs by demand (TBD)
* [x] Land: polish/tweaks (TBD)
* [x] Remove: deprecated features
* [x] Stabilize or remove: thunk - #23939
* [x] Migrate `std::time::Duration` to libtime if nothing else has happened

### Week of Mar 30 - beta

* [x] Top 10 crates on crates.io can compile on stable - https://etherpad.mozilla.org/rust-crate-stability-blockers

## Library grab-bag

This is a non-exhaustive list of APIs to polish/stabilize:

* [User requests](http://users.rust-lang.org/t/using-unstable-apis-tell-us-about-it/157/34)
* [P-backcompat-libs](https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AP-backcompat-libs)

### IO remnants

* [ ] Must have: https://github.com/rust-lang/rust/issues/21070
* [x] Normalization for paths - #23229
* [x] `std::os::platform` extensions - #23353
* [x] `thread::sleep` - #23330
* [x] reverse DNS lookup #22608

### Unicode manipulation

* [ ] `char::CharExt::encode_utf8`
* [x] `char::CharExt::to_uppercase` - #23126
* [x] `str::StrExt::char_at` - #23461
* [x] `str::StrExt::char_range_at_reverse` - #23461
* [x] `str::StrExt::char_range_at` - #23461
* [ ] `str::StrExt::escape_default`
* [x] `str::StrExt::is_char_boundary` - #23461
* [x] `str::StrExt::slice_shift_char` - #23461
* [ ] `unicode::str::utf16_items`

### `std::num`

* [x] `num::Float::is_nan` #23549
* [ ] `num::FromPrimitive`
* [x] `num::Int::abs` #23549
* [ ] `num::cast`
* [ ] `num::f64::to_str_digits`
* [x] `num::from_str_radix` #23549

### Collections and iteration

* [x] ~~`collections::HashMap::with_capacity_and_hash_state`~~
* [x] `iter::IteratorExt::cloned`
* [x] `iter::IteratorExt::partition`
* [ ] `slice::SliceExt::position_elem`
* [ ] `slice::SliceExt::tail`
* [x] `str::StrExt::split_terminator` - #22466
* [x] `vec::Vec::into_boxed_slice`

### `std::ptr`, raw

* [ ] `ptr::Unique`
* [x] `ptr::copy_memory`
* [x] `ptr::copy_nonoverlapping_memory`
* [x] `ptr::set_memory`
* [x] `ptr::zero_memory`

* [ ] `raw::TraitObject`

### Probably post 1.0:

* [ ] `rt::heap::*`

# Non-library tracking

## Crates to move out

* [ ] `libtest`

## CLI Tooling

* [ ] command line flags - #19051, #19900
* [ ] lints - #21761

**Comment by aturon** [comment]
Nominating for 1.0-beta P-backcompat-libs

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-libs.

**Comment by SimonSapin** [comment]
`libtest` is listed “to move out”. How would that interact with `rustc --test` and `cargo test`?

**Comment by aturon** [comment]
For reference: https://etherpad.mozilla.org/rust-crate-stability-blockers

**Comment by aturon** [comment]
Closing; this has been an amazing cycle!

We'll work on some other way of tracking stabilization requests (probably separately from the issue tracker) from here on.
