### ISSUE TITLE
Leverage atomically setting CLOEXEC where possible

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#24237]
After #24034 lands we will be setting `CLOEXEC` on all file descriptors on unix in the standard library. Currently we do so in a nonatomic fashion, however, so it's possible to continue to leak file descriptors into children if a thread is concurrently forking.

Many platforms have methods of creating `CLOEXEC` file descriptors atomically, but many of the APIs are quite new and they need to be properly detected at runtime. For example, the current instances of `fd.set_cloexec()` that need to be migrated are listed below. A reminder of our minimum platform requirements are linux 2.6.18 and OSX 10.7.

* [x] `File::open` - this should specify the `O_CLOEXEC` flag. This flag was added in linux 2.6.23 and appears to exist on OSX 10.7. #27971
* [x] `Socket::new` - this should be specify the `SOCK_CLOEXEC` flag in the `type` argument (second). This flag was only added in linux 2.6.27 and does not exist on OSX. #31417
* [x] `Socket::accept` - this should be replaced with a call to `accept4`. This system call was only added in linux 2.6.28 and does not exist on OSX. #31417
* [x] `Socket::duplicate` - this should be replaced with `dup3` (linux 2.6.27, not on OSX) or `F_DUPFD_CLOEXEC` (linux 2.6.24, appears to exist on OSX 10.7). #27980
* [x] `anon_pipe` - this could be replaced with `pipe2` on linux 2.6.27 and perhaps `socketpair` on OSX (not confirmed). #31417

The hard part about this bug is figuring out if it's possible to avoid compile-time detection of these functions (and instead rely on runtime detection).

**Comment by l0kod** [comment]
cc #24307

**Comment by ioquatix** [comment]
I know this is closed, but I just have to comment on how well thought out and organised the original description was - how clearly the problem is captured and then it's solution tracked. Well done everyone.
