### ISSUE TITLE
Tracking issue for type checking refactor

### ISSUE THREAD

**Issue by jroesch** [rust-lang/rust#26597]
This a placeholder issue to contain our conversation and set of pull requests around the type checking refactor. The goal of the work is to unify our type checking contexts into a single piece of state. We hope to eventually have a single context instead of the fractured situation we currently have.
- [x] unify ParameterEnvironment + InferCtxt (#26582)
- [x] move FulfillmentContext into InferCtxt
- [x] modify SelectionContext to only take a single context argument
- [x] remove remaining typer impls 
- [x] remove the ClosureTyper + Typer trait
- [ ] do some renaming to make these things more applicable to their new roles

**Comment by eddyb** [comment]
cc @rust-lang/compiler

**Comment by steveklabnik** [comment]
@jroesch bump! You only have one box not checked here, can this be closed?

**Comment by Mark-Simulacrum** [comment]
I'd be happy to do the work renaming things if given a list (or even an approximate list, general idea).

**Comment by eddyb** [comment]
I'm not even sure what we should do now, it's likely time for a cache-reuse-targetted redesign.

**Comment by nikomatsakis** [comment]
I think we can close this issue, since I think this path of changes is dead. I have some new plans I hope to write up in the next few days (or weeks...) though.
