### ISSUE TITLE
Tracking issue for Allow a re-export for `main` (RFC 1260)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#28937]
RFC Thread:
https://github.com/rust-lang/rfcs/pull/1260

Feature name:
`imported_main`

### Steps / History

- [x] Implementation:
  - [x] Support imported main from same crate (#84401)
  - [x] Support imported main from foreign crate (#84507)
- [x] Final commenting period (FCP)
- [x] Stabilization PR

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by bombless** [comment]
Do we need a feature gate for it?

**Comment by petrochenkov** [comment]
This RFC was implemented in https://github.com/rust-lang/rust/pull/84401.

**Comment by crlf0710** [comment]
#84401 has landed. Want to say thank you to @petrochenkov for your patient mentoring!

There's a small piece of codegen changes to support foreign crate imported `main` fn case. The PR is now up at #84507 .

**Comment by crlf0710** [comment]
#84507 has landed and this rfc is now fully implemented.

**Comment by joshtriplett** [comment]
@crlf0710 What's the current state of this? Are people using it successfully? Is it a potential candidate for stabilization?

**Comment by crlf0710** [comment]
@joshtriplett It's fully implemented, and the tests pass. There're no known technical limitations, but I'm not aware whether there're people using it today in nightly builds. I think it's a potential candidate for stablization.

**Comment by pnkfelix** [comment]
@rustbot +T-lang +I-lang-nominated

Its not clear from discussion whether its appropriate to shift this to S-tracking-ready-to-stabilize, or if it is S-tracking-needs-to-bake

**Comment by clubby789** [comment]
I think this should be stabilized.

# Stabilization Report
## Summary
The `imported_main` feature allows a function to be re-exported as `main`. This allows, for example, re-exporting a function from a library and using it as the entrypoint.

```rs
pub mod foo {
    pub fn bar() {
        println!("Hello, world!");
    }
}
use foo::bar as main;
```

## Tests/Edge Cases

The feature is tested in `tests/ui/entry-point`:
	- [Exporting from a module in the current crate](https://github.com/rust-lang/rust/blob/5ad7454f7503b6af2800bf4a7c875962cb03f913/tests/ui/entry-point/imported_main_from_inner_mod.rs)
	- [Exporting from an extern crate](https://github.com/rust-lang/rust/blob/5ad7454f7503b6af2800bf4a7c875962cb03f913/tests/ui/entry-point/imported_main_from_extern_crate.rs#L4)
	- [Incorrectly typed functions are not allowed](https://github.com/rust-lang/rust/blob/5ad7454f7503b6af2800bf4a7c875962cb03f913/tests/ui/entry-point/imported_main_from_extern_crate_wrong_type.rs#L4)
	- [Conflicting `main`s are not allowed](https://github.com/rust-lang/rust/blob/5ad7454f7503b6af2800bf4a7c875962cb03f913/tests/ui/entry-point/imported_main_conflict.rs#L5)

## Documentation PRs
- The Reference: https://github.com/rust-lang/reference/pull/1461
There are no known issues or unresolve questions.

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by slanterns** [comment]
I guess we can close it now?

**Comment by crlf0710** [comment]
Closed by #122060
