### ISSUE TITLE
Tracking Issue for Mutex and RWLock unique accessors

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#28968]
After #29031, this is now the tracking issue for the stabilization of the following features:
 * [ ] mutex_into_inner
 * [ ] mutex_get_mut
 * [ ] rwlock_into_inner
 * [ ] rwlock_get_mut

## Original report

As far as I can tell, it's sound to straight-up-unwrap a Mutex if you have it by value. This would enable one to do:

```rust
let data = Mutex::new(vec![])
crossbeam::scope(|scope| {
  for input in inputs {
    let data = &data;
    scope.spawn(move || {
      let output = expensive_computation(input);
      data.lock().unwrap().push(output);
    }
  }
});

for expensive in data.into_inner() {
  non_thread_safe(expensive);
}
```

Which today requires mutexing an `&mut`:

```rust
let mut data = vec![];
{
  let data_mutex = Mutex::new(&mut data);
  crossbeam::scope(|scope| {
    for input in inputs {
      let data = &data_mutex;
      scope.spawn(move || {
        let output = expensive_computation(input);
        data.lock().unwrap().push(output);
      }
    }
  });
}

for expensive in data.into_inner() {
  non_thread_safe(expensive);
}
```

Given Arc can be unwrapped, this would also allow the last `Arc<Mutex<T>>` in some concurrent context to be fully unwrapped to a `T`.

**Comment by Gankro** [comment]
cc @aturon

**Comment by sfackler** [comment]
Seems like just an oversight to me.

**Comment by alexcrichton** [comment]
This is a dupe of https://github.com/rust-lang/rfcs/issues/1269 (although cross-repo dupes are always interesting). 

The consensus is basically "this can be added as soon as someone puts in the effort".

**Comment by Gankro** [comment]
Seems like a good noobie task (upon reflection I agree with the rfc issue's assesment that this should return a poison guard).

**Comment by cristicbz** [comment]
On it!

**Comment by cristicbz** [comment]
After #29031, this is now the tracking issue for the stabilization of the following features:
 * [ ] mutex_into_inner
 * [ ] mutex_get_mut
 * [ ] rwlock_into_inner
 * [ ] rwlock_get_mut

**Comment by cristicbz** [comment]
This should probably be renamed into `Tracking issue for sync into_inner and get_mut` or something.

**Comment by alexcrichton** [comment]
Nominating for 1.6 discussion

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for stabilization :bell:

**Comment by aturon** [comment]
I'm in favor. Follows existing conventions, fills in a bit of missing expressiveness.

**Comment by cristicbz** [comment]
Something to consider that I didn't when I submitted the PR is whether we also want `fn get_mut(&mut self)` on `RefCell` (`into_inner` already exists there). In addition to consistency, I actually stumbled upon this in [real code](https://github.com/cristicbz/rust-doom/blob/master/src/game/world.rs#L117): I'm using a `RefCell` to reuse an allocation (cached as a member) in `&self` methods, but I also need to do the use it in some `&mut self` methods.

(crazy idea: it would be really awesome actually, if `RefCell`, `Mutex` etc. could somehow magically implement `DerefMut` without `Deref`)
