### ISSUE TITLE
The Standard Library Documentation Checklist

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29329]
I've been doing work on random parts of the standard library, but it's time to get systematic.

Here's a list of all of the top-level modules in `std`, with separate tracking issues for each part. Documentation is never done, but I'd at least like to ensure that every module is seen at least once.

PRs will be sent for consistency, more examples, better explanations, all the usual stuff. But here's how we can track progress.

One specific area where we can do much better is linking of types to their docs in text explanations.
- [x] home page https://github.com/rust-lang/rust/issues/29330
- [x] array https://github.com/rust-lang/rust/issues/29331
- [x] bool https://github.com/rust-lang/rust/issues/29332
- [x] char https://github.com/rust-lang/rust/issues/29333
- [x] floats https://github.com/rust-lang/rust/issues/29334
- [x] integers https://github.com/rust-lang/rust/issues/29335
- [x] raw pointers https://github.com/rust-lang/rust/issues/29336
- [x] slices https://github.com/rust-lang/rust/issues/29337
- [x] str https://github.com/rust-lang/rust/issues/29338
- [x] tuples https://github.com/rust-lang/rust/issues/29339
- [x] any https://github.com/rust-lang/rust/issues/29340
- [x] borrow https://github.com/rust-lang/rust/issues/29342
- [x] boxed https://github.com/rust-lang/rust/issues/29343
- [x] cell https://github.com/rust-lang/rust/issues/29344
- [x] char https://github.com/rust-lang/rust/issues/29345
- [x] clone https://github.com/rust-lang/rust/issues/29346
- [x] cmp https://github.com/rust-lang/rust/issues/29347
- [x] collections https://github.com/rust-lang/rust/issues/29348
- [x] convert https://github.com/rust-lang/rust/issues/29349
- [x] default https://github.com/rust-lang/rust/issues/29350
- [x] env https://github.com/rust-lang/rust/issues/29351
- [x] error https://github.com/rust-lang/rust/issues/29352
- [x] std::float https://github.com/rust-lang/rust/issues/29353
- [x] ffi https://github.com/rust-lang/rust/issues/29354
- [ ] fmt https://github.com/rust-lang/rust/issues/29355
- [x] fs https://github.com/rust-lang/rust/issues/29356
- [x] hash https://github.com/rust-lang/rust/issues/29357
- [x] std::integer https://github.com/rust-lang/rust/issues/29358
- [x] io https://github.com/rust-lang/rust/issues/29359
- [x] iter https://github.com/rust-lang/rust/issues/29360
- [x] marker https://github.com/rust-lang/rust/issues/29361
- [x] mem https://github.com/rust-lang/rust/issues/29362
- [x] net https://github.com/rust-lang/rust/issues/29363
- [x] num https://github.com/rust-lang/rust/issues/29364
- [x] ops https://github.com/rust-lang/rust/issues/29365
- [x] option https://github.com/rust-lang/rust/issues/29366
- [ ] os https://github.com/rust-lang/rust/issues/29367
- [x] prelude https://github.com/rust-lang/rust/issues/29369
- [ ] process https://github.com/rust-lang/rust/issues/29370
- [x] ptr https://github.com/rust-lang/rust/issues/29371
- [x] rc https://github.com/rust-lang/rust/issues/29372
- [x] result https://github.com/rust-lang/rust/issues/29373
- [x] std::slice https://github.com/rust-lang/rust/issues/29374
- [x] std::str https://github.com/rust-lang/rust/issues/29375
- [x] string https://github.com/rust-lang/rust/issues/29376
- [x] sync https://github.com/rust-lang/rust/issues/29377
- [ ] thread https://github.com/rust-lang/rust/issues/29378
- [x] time https://github.com/rust-lang/rust/issues/29379
- [x] vec https://github.com/rust-lang/rust/issues/29380
- [x] macros https://github.com/rust-lang/rust/issues/29381
- [x] std::char https://github.com/rust-lang/rust/issues/29428

**Comment by durka** [comment]
> One specific area where we can do much better is linking of types to their docs in text explanations.

Regarding this, is there any hope of extending Markdown with a way to reference Rust items, so you don't have to rely on knowing the URL structure?

**Comment by steveklabnik** [comment]
I'm not aware of CommonMark having extension capabilities, but yeah, let's just say that there's nothing close enough on the horizon to actually use.

**Comment by critiqjo** [comment]
>let's just say that there's nothing close enough on the horizon to actually use.

But why not add a thin layer in rustdoc which could translate links of the form, say, `rustdoc://std::collections::BinaryHeap` into `/std/collections/struct.BinaryHeap.html` before passing it to the markdown parser?

**Comment by tshepang** [comment]
@cristicbz such would be nice

**Comment by cristicbz** [comment]
@tshepang think you got the wrong guy

**Comment by tshepang** [comment]
yeah

**Comment by steveklabnik** [comment]
@critiqjo please see https://internals.rust-lang.org/t/rustdoc-restructuredtext-vs-markdown/356

**Comment by Gankro** [comment]
Replacing hoedown with https://github.com/google/pulldown-cmark should make these translations trivial because it exposes a token-stream-like interface that can be mapped over.

**Comment by critiqjo** [comment]
@steveklabnik @Gankro :+1:

Has anyone started working on replacing with pulldown-cmark?

I was looking at librustdoc source, didn't get the flow of parsing... I'll take a better look later -- an interaction diagram would have helped a lot.

(Interaction diagrams of building the compiler would also be a nice-to-have -- may be replacing the `nitty-gritty`.)

**Comment by steveklabnik** [comment]
I don't believe so, no. Rustdoc in general needs a ton of help.

**Comment by Gankro** [comment]
The flow of parsing is bananas and involves recording events using thread-local statics. I believe @alexcrichton wants to address the problem of Rust depending on external crates in tandem with this project.

**Comment by GuillaumeGomez** [comment]
I'm going to take a look as soon as I can.

**Comment by GuillaumeGomez** [comment]
I toggled the added docs. All up to date now.

**Comment by critiqjo** [comment]
> Has anyone started working on replacing [hoedown] with pulldown-cmark?

This is [almost done](https://github.com/critiqjo/rustdoc/pull/2) now, except for rendering of books. Once the buildsystem is moved to Cargo-based, I think we should also think about supporting custom links.

**Comment by steveklabnik** [comment]
@critiqjo oh wow! That's awesome

**Comment by matthew-piziak** [comment]
@steveklabnik Looks like `io`, `num`, `std::slice`, and `vec` are closed and can be checked off.

**Comment by critiqjo** [comment]
Suggestion: Turn this into a [Project](https://github.com/rust-lang/rust/projects)? (Might help in gaining visibility?)

**Comment by matthew-piziak** [comment]
@critiqjo I like that idea! Is anybody against it? I would put one up but it seems that project creation is restricted.

**Comment by GuillaumeGomez** [comment]
I think I went over every items. Once I have time, I'll try to check if I missed any.

**Comment by steveklabnik** [comment]
We haven't, as a matter of project policy, decided if we're using projects, and for what.

We should talk about it at the next docs meeting.

**Comment by frewsxcv** [comment]
Opened an issue for moving to pulldown-cmark: https://github.com/rust-lang/rust/issues/38400

**Comment by steveklabnik** [comment]
Update: I'm going to go through all of the ones that are still open today and elaborate on exactly what they need to have done to be considered closed.

**Comment by lukaramu** [comment]
Update:
* `env` is checked off, but probably shouldn't be, as #29351 is open
* the issues for [`hash`], [`net`], and [`std::str`] have been closed, so this can be checked off as well
* `ascii` isn't listed currently; #29341 is still open, but [can be closed][0], so this should probably be checked off as well
* `option` was already checked off somehow, but the issue is still open; as for `ascii` though, it has been addressed and [can be closed][1] as far as I can tell

[0]: https://github.com/rust-lang/rust/issues/29341#issuecomment-294308518
[1]: https://github.com/rust-lang/rust/issues/29366#issuecomment-294308387
[`hash`]: https://github.com/rust-lang/rust/issues/29357
[`net`]: https://github.com/rust-lang/rust/issues/29363
[`std::str`]: https://github.com/rust-lang/rust/issues/29375

**Comment by Mark-Simulacrum** [comment]
Unchecked `env`.
Checked `hash`, `net`, and `std::str`.

`path` and `ascii` still need to be added.

**Comment by marioidival** [comment]
@steveklabnik update checklist please:
[convert](https://github.com/rust-lang/rust/issues/29349), done
[env](https://github.com/rust-lang/rust/issues/29351), done

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by steveklabnik** [comment]
I think this issue has served its use. There's only a few things left, and we can track them in their own issue.

Thank you to everyone who pitched in and made the standard library docs better over the last three years! ❤️
