### ISSUE TITLE
API Docs: fmt

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29355]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/fmt/

Here's what needs to be done to close out this issue: 

- [the module level docs](https://doc.rust-lang.org/std/fmt/) almost belong in their own issue. These are very old docs written long ago, and while they're good, I have a hunch they could be made way better. Not needed to close this issue.
- [x] all of [the traits](https://doc.rust-lang.org/std/fmt/#traits) should say "`C` formatting", where `C` is the char, rather than their current boilerplate. Except Write. And Display. 
- [x] [`fmt::Result`](https://doc.rust-lang.org/std/fmt/type.Result.html) needs an example, showing off the `use std::fmt; fmt::Result` pattern.
- [x] [`write`](https://doc.rust-lang.org/std/fmt/fn.write.html) should have its `Arguments` section removed, we don't do this.
- [x] [`format`](https://doc.rust-lang.org/std/fmt/fn.format.html) has the same issue, and needs more explanation generally.
- [ ] All of the traits have... I dunno, the wording feels awkward. This doesn't need to be fixed to close this issue, but would be nice.
- [x] [`Write`](https://doc.rust-lang.org/std/fmt/trait.Write.html) needs a lot of links. and some examples.
- [x] [`Arguments`](https://doc.rust-lang.org/std/fmt/struct.Arguments.html) needs examples, but also a justification of why this is all done this way.
- [x] [`DebugList`](https://doc.rust-lang.org/std/fmt/struct.DebugList.html) should use the iterator boilerplate language, even though it's not an iterator. Mostly pointing to the docs of the function that creates it.
- [x] [`DebugMap`](https://doc.rust-lang.org/std/fmt/struct.DebugMap.html) same.
- [x] [`DebugSet`](https://doc.rust-lang.org/std/fmt/struct.DebugSet.html) same.
- [x] [`DebugStruct`](https://doc.rust-lang.org/std/fmt/struct.DebugStruct.html) same.
- [x] [`DebugTuple`](https://doc.rust-lang.org/std/fmt/struct.DebugTuple.html) same.
- [x] [`Error`](https://doc.rust-lang.org/std/fmt/struct.Error.html) needs examples, and specifically `use std::fmt; fmt::Error`
- [ ] [`Formatter`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html) should show where it's created, and talk about the details more.

**Comment by steveklabnik** [comment]
I am happy to mentor anyone who wants to tackle this issue.

**Comment by webbm** [comment]
@steveklabnik, I would like to work on this.

**Comment by steveklabnik** [comment]
@webbm awesome, please let me know if you need anything.

**Comment by mandeep** [comment]
Hi @webbm! Before I start working on some of the items on the checklist I wanted to check with you to see which items are still available so that we don't duplicate effort.

**Comment by webbm** [comment]
@mandeep, I have done a little of 1, 2, 4, and 5 is in progress. I'm going to create a Trello board to keep track of my own progress. Should I add all these as tasks and add you?

**Comment by mandeep** [comment]
@webbm No need for Trello just yet. I'll work on item 3 this weekend and report back.

**Comment by rthomas** [comment]
@steveklabnik If no one is looking at this I'll jump in for `write`.

**Comment by steveklabnik** [comment]
@rthomas I'm not aware of any active work right now, that'd be great!

**Comment by rthomas** [comment]
I have sent PRs for `write` `format` and the `Debug*` entries - 4, 5, 8, 9, 10, 11, 12.

**Comment by rthomas** [comment]
Looking at the last one (`Formatter`) although I am struggling to see where this is actually instantiated...

**Comment by mehdishojaei** [comment]
> * [`Formatter`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html) should show where it's created, and talk about the details more.

+1

**Comment by steveklabnik** [comment]
I'm going to send in a PR to help `Formatter`; after that, all of this is done enough. The module docs are still very huge, but I don't have concrete suggestions at this time. Thank you everyone!
