### ISSUE TITLE
API Docs: sync

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29377]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/sync/

Here's what needs to be done to close out this issue: 

- [ ] [the module-level documentation](https://doc.rust-lang.org/std/sync/) is very small. It should explain what the module is for in more detail, with some examples.
- [x] [`std::sync::atomic`](https://doc.rust-lang.org/std/sync/atomic/) could use links to the types it references.
- [x] [`std::sync::atomic::fence`](https://doc.rust-lang.org/std/sync/atomic/fn.fence.html) has very... dry docs that aren't very helpful. And there's no examples.
- [x] [`ATOMIC_*_INIT`](https://doc.rust-lang.org/std/sync/atomic/constant.ATOMIC_BOOL_INIT.html)  (link is just to BOOL but all of them) could use examples.
- [ ] [`Atomic*`](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicBool.html) (link is to Bool but all of them) are mostly fine, but could use links to other types and some beefing up generally.
- [x] [`Barrier`](https://doc.rust-lang.org/std/sync/struct.Barrier.html) needs a bunch of types linked.
- [x] [`BarrierWaitResult`](https://doc.rust-lang.org/std/sync/struct.BarrierWaitResult.html) should explain its relationship with `Barrier` and link to it.
- [x] [`Condvar`](https://doc.rust-lang.org/std/sync/struct.Condvar.html) needs examples on its methods.
- [x] [`Once`](https://doc.rust-lang.org/std/sync/struct.Once.html) needs to link to `ONCE_INIT`.
- [x] [`PoisonError`](https://doc.rust-lang.org/std/sync/struct.PoisonError.html) needs examples.
- [x] [`RwLock`](https://doc.rust-lang.org/std/sync/struct.RwLock.html) needs examples, links to types, and a comparison between it and `Mutex`.
- [x] [`WaitTimeoutResult`](https://doc.rust-lang.org/std/sync/struct.WaitTimeoutResult.html) should link to the method that creates it.
- [x] [`TryLockError`](https://doc.rust-lang.org/std/sync/enum.TryLockError.html) needs to link to the function that creates it.
- [x] [`ONCE_INIT`](https://doc.rust-lang.org/std/sync/constant.ONCE_INIT.html) needs a link to `Once` and some examples.
- [x] [`LockResult`](https://doc.rust-lang.org/std/sync/type.LockResult.html) needs links.
- [x] [`TryLockResult`](https://doc.rust-lang.org/std/sync/type.TryLockResult.html) needs links.
- [x] [`Weak`](https://doc.rust-lang.org/std/sync/struct.Weak.html) could do a much better job of explaining itself.
- [x] [`std::sync::mspc`](https://doc.rust-lang.org/std/sync/mpsc/) needs a lot of links. The docs are good but a bit jargon-heavy, expanding those would be nice.
- [x] [`IntoIter`](https://doc.rust-lang.org/std/sync/mpsc/struct.IntoIter.html) needs more links and to explain how you get one.
- [x] [`Iter`](https://doc.rust-lang.org/std/sync/mpsc/struct.Iter.html) is the same.
- [x] [`Receiver`](https://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html) needs links, examples, and more explanation of what it is.
- [x] [`RecvError`](https://doc.rust-lang.org/std/sync/mpsc/struct.RecvError.html) needs to link to `recv`.
- [x] [`SendError`](https://doc.rust-lang.org/std/sync/mpsc/struct.SendError.html) needs links.
- [x] [`Sender`](https://doc.rust-lang.org/std/sync/mpsc/struct.Sender.html) has the same issues as `Receiver`.
- [x] [`SyncSender`](https://doc.rust-lang.org/std/sync/mpsc/struct.SyncSender.html) has the same as `Sender`.
- [x] [`TryIter`](https://doc.rust-lang.org/std/sync/mpsc/struct.TryIter.html) needs to link to how to create one.
- [x] [`RecvTimeoutError`](https://doc.rust-lang.org/std/sync/mpsc/enum.RecvTimeoutError.html) needs to link to `recv_timeout`.
- [x] [`TryRecvError`](https://doc.rust-lang.org/std/sync/mpsc/enum.TryRecvError.html) needs to link to `try_recv`
- [x] [`TrySendError`](https://doc.rust-lang.org/std/sync/mpsc/enum.TrySendError.html) needs to link to `try_send`.
- [x] [`channel`](https://doc.rust-lang.org/std/sync/mpsc/fn.channel.html) has almost no docs and it's the focus of this module!
- [x] [`sync_channel`](https://doc.rust-lang.org/std/sync/mpsc/fn.sync_channel.html) should point to `channel` and then tell how it's different.

**Comment by iuliuv** [comment]
Possible inconsistency in the Rust documentation about channels:

https://doc.rust-lang.org/std/sync/mpsc/fn.sync_channel.html
Function std::sync::mpsc::sync_channel
"As with asynchronous channels, all senders will panic in send if the Receiver has been destroyed"

https://doc.rust-lang.org/std/sync/mpsc/struct.SyncSender.html
Struct std::sync::mpsc::SyncSender:
fn send(&self, t: T) -> Result<(), SendError<T>>
"This function will never panic, but it may return Err if the Receiver has disconnected and is no longer able to receive information."

**Comment by kmcallister** [comment]
I'm working on updating the `Arc` docs to more closely match the refined `Rc` docs from #36571.

**Comment by steveklabnik** [comment]
I am happy to mentor anyone who wants to tackle this issue.

**Comment by projektir** [comment]
@steveklabnik for all the ones that need links, are you talking about for example the types wrapped in `<code>` tags, such as `Sender` under the `std::sync::mpsc::Receiver` page? Is it safe to say that as general rule every type under a `<code>` tag should link to the page for that type? Is there other linking on these pages you would expect to see?

**Comment by steveklabnik** [comment]
> Is it safe to say that as general rule every type under a <code> tag should link to the page for that type? 

Yes, exactly. Note that *sometimes* there is a bug here; that is, certain kinds of docs get rendered on two pages and so the links won't work. I don't think that's an issue here, but our tools will catch those cases, so you shouldn't worry about it too much, but figured it'd be worth a mention.

> Is there other linking on these pages you would expect to see?

That's pretty much it, just the stuff that's in `<code>` already.

**Comment by projektir** [comment]
Barrier looks to already be taken care of on nightly.

**Comment by steveklabnik** [comment]
> Someone looks to have fixed up Barrier on nightly, btw.

Ah, I made these off of the stable links, I think :(

**Comment by projektir** [comment]
@steveklabnik can we check some boxes off to track progress and make it easier to see where we're at? 😄 Things that I believe can be marked off:

`std::sync::atomic` -> merged, but I could understand if you want more stuff here
`Once` -> merged
`ONCE_INIT` -> merged
`WaitTimeoutResult` -> looks good to me on nightly
`LockResult` -> has links on nightly
`TryLockResult` -> has links on nightly

Awaiting merge/approval:
`BarrierWaitResult` -> going to be merged, could as well be marked off I think
`td::sync::mspc` -> looks good, too, but waiting for approval

**Comment by steveklabnik** [comment]
@projektir done, thank you!

**Comment by durka** [comment]
Condvar has examples on its methods, but the ones for wait_* seem to contain race conditions.

WaitTimeoutResult::timed_out has an example that does not use the method (it is copied from the incorrect example for Condvar::wait_timeout).

**Comment by projektir** [comment]
I think @GuillaumeGomez worked on the Condvar examples?

**Comment by GuillaumeGomez** [comment]
It's very possible, I had issue with timeout stuff...

**Comment by gamazeps** [comment]
@steveklabnik is the list of things to do in this module up to date ?

I was thinking on tackling this module once I am done with the `thread` module (probably on Monday).

If no one else is working on this I'll try to document the whole module for the next week (and maybe a little bit of the next one).

**Comment by GuillaumeGomez** [comment]
@gamazeps: More or less. It still has a lot of places to improvement anyway so feel free to give it a try!

**Comment by projektir** [comment]
@gamazeps so everything starting with Weak and going down should be done now.

I've been working on rewriting this page, so `std::sync::atomic`: https://doc.rust-lang.org/std/sync/atomic/, but that relates more to this issue: https://github.com/rust-lang/rust/issues/40306, and I have been distracted so it's going slow. I hope to get it done this week.

So everything else should be up for grabs and of course nothing's stopping you from improving any given page further.

**Comment by csherratt** [comment]
> TryLockError needs to link to the function that creates it.

The latest docs have a [link back)(https://doc.rust-lang.org/std/sync/enum.TryLockError.html) to the try_lock method. Is this adequate?

**Comment by lucasem** [comment]
@steveklabnik I completed the `RwLock` subtask with #44778

**Comment by lucasem** [comment]
@steveklabnik ditto for `PoisonError` and `TryLockError`.

What did you have in mind for changes to `Atomic*`?

**Comment by steveklabnik** [comment]
@lucasem thank you!

> What did you have in mind for changes to Atomic*?

So I'm looking at them now, and they're pretty good. Mostly, there's a few types mentioned that don't have links, like how https://doc.rust-lang.org/std/sync/atomic/struct.AtomicBool.html doesn't have a link to https://doc.rust-lang.org/stable/std/primitive.bool.html

I wonder if we should point to the module documentation as well, like, add a sentence to each type saying

> For more about the differences between atomic types and non-atomic types, please see the [module-level documentation]().

Thoughts?

**Comment by christianpoveda** [comment]
I'd like to fix the module documentation
