### ISSUE TITLE
API Docs: ptr

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29371]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/ptr/

Here's what needs to be done to close out this issue: 

- [x] [the module docs](https://doc.rust-lang.org/std/ptr/) act like this is about `*const T`/`*mut T`, but it's really about common functions that work with them.
- [x] [`copy`](https://doc.rust-lang.org/std/ptr/fn.copy.html) could link to `memmove` somewhere.
- [x] [`copy_nonoverlapping`](https://doc.rust-lang.org/std/ptr/fn.copy.html) should link to `memcpy`. Both of these functions should talk more about what "overlapping" means here.
- [x] [`drop_in_place`](https://doc.rust-lang.org/std/ptr/fn.drop_in_place.html) needs links and examples
- [ ] [`read`](https://doc.rust-lang.org/std/ptr/fn.read.html) needs to explain why and where you should use it, as well as linking some stuff.
- [x] [`read_volitile`](https://doc.rust-lang.org/std/ptr/fn.read_volatile.html) needs links
- [x] [`replace`](https://doc.rust-lang.org/std/ptr/fn.replace.html) should link to `mem::replace`, and justify its unsafety better.
- [x] [`swap`](https://doc.rust-lang.org/std/ptr/fn.swap.html) needs to split out its summary from its description, link to `mem::swap`, and get an example.
- [x] [`write`](https://doc.rust-lang.org/std/ptr/fn.write.html) needs to explain when and where to use it, and to link some types
- [x] [`write_bytes`](https://doc.rust-lang.org/std/ptr/fn.write_bytes.html) needs to better justify itself, link `memset`, and move that out of its summary line.
- [x] [`write_volatile`](https://doc.rust-lang.org/std/ptr/fn.write_volatile.html) needs to link `read`.

**Comment by steveklabnik** [comment]
I am happy to mentor anyone who wants to tackle this issue.

**Comment by aminb** [comment]
@steveklabnik I'd like to help tackle this. Any specific suggestions before I get started?

I also have one question: any preference as to what website use for linking to C standard library functions? How does [this](http://clc-wiki.net/wiki/C_standard_library:string.h:memmove) look for `memmove`?

**Comment by steveklabnik** [comment]
> I'd like to help tackle this by taking on some of the items. Any general suggestions before I get started?

Wonderful! I left a bunch of related-ish comments on https://www.reddit.com/r/rust/comments/61avqf/want_to_join_the_rust_docs_team/?st=j0s6zfg8&sh=79419433. Of course, this whole exercise has brought up a meta issue, which is that our "how to contribute to docs" docs aren't as awesome as they could be. I'm gonna try to work on that 😄 

> I also have one question: any preference as to what website to use for linking to C standard library functions? 

This is a good question. I am not sure.

> How does this look for memmove?

I haven't heard of this website before and I'm slightly skpetical of a wiki. I asked on Twitter, and got a number of responses:

* https://msdn.microsoft.com/en-us/library/8k35d1fx.aspx
* http://man7.org/
* http://pubs.opengroup.org/onlinepubs/009695399/functions/memmove.html
* https://manpages.debian.org/jessie/manpages-dev/memmove.3.en.html
* https://www.freebsd.org/cgi/man.cgi?memmove

I think I'm leaning towards MSDN here.

**Comment by aminb** [comment]
Awesome. Thanks Steve. I'll get started on this in a few days (my semester's almost over).

**Comment by imiuka** [comment]
hey @aminb, i'd love to take on a few of those bits as well, if you don't intend on doing them all yourself.

**Comment by aminb** [comment]
Hey @imiuka, sure! I was thinking of doing at least `copy` and `copy_nonoverlapping`, and maybe `swap`. So feel free to take on any other ones you'd like to.

**Comment by lukaramu** [comment]
Hey there @hinaria and @aminb! I'm currently going over the remaining API tracking issues and saw your comments here. Are you still interested in helping out with this?

**Comment by hinaria** [comment]
i'm happy to commit to finishing the remaining docs here.

this issue fell off my list last time, sorry.

**Comment by GuillaumeGomez** [comment]
@lukaramu @hinaria: Want me to assign it to both of you "officially"?

**Comment by aminb** [comment]
Hi all, sorry for my absence.

I still like to do `copy` and `copy_nonoverlapping` at the very least, but @lukaramu and @hinaria feel free to split the rest.

**Comment by lukaramu** [comment]
@GuillaumeGomez I'll tackle other modules first since there are people working on this one, thanks for asking though!

**Comment by QuietMisdreavus** [comment]
I'm folding https://github.com/rust-lang/rust/issues/36450 into this issue; basically, make sure that each function also mentions its requirements w.r.t. alignment. (Generally speaking, unless it says `_unaligned`, it needs the pointer to have the same alignment as the type.)

**Comment by hinaria** [comment]
thank you! will do! i've almost got a pull request ready for all the docs here.

**Comment by hinaria** [comment]
hi everyone, just wanted to give an update - i've been struggling a bit in real life, but i'm okay now and i'll get this done during the weekend! sorry it's taken so long!

**Comment by QuietMisdreavus** [comment]
No worries! Glad you're feeling better!

**Comment by steveklabnik** [comment]
@ecstatic-morse that'd be great!

1. I'm not actually sure!
2. The "Undefined Behavior" convention is a newer one, and so not all of std is up to date with it. So yeah, go ahead and use it even though it's not heavily used yet. :)
3. You don't even need to do that; the bots will assign someone. You can also put "r? @steveklabnik" to force the bot to assign it to me, but I'll probably get assigned anyway

**Comment by GuillaumeGomez** [comment]
I'll reopen this issue because it doesn't feel like it's actually fixed.

**Comment by steveklabnik** [comment]
Triage: I have looked at all of the individual checkboxes, and 99% of the work here is done. I think these massive tracking issues have served their purpose; if you'd like to see more improvements to the `ptr` docs, please open one, focused issue for each improvement, and we can tackle them!
