### ISSUE TITLE
API Docs: thread

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29378]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/thread/

Here's what needs to be done to close out this issue: 

- [ ] [the module docs](https://doc.rust-lang.org/std/thread/) are written a while ago, and contain some questionableish advice. It's not actually bad, it's just not the way I'd orient all of this. A particularly enthusiastic contributor could toss this out and re-write it from scratch. If the rest of this work gets done, we can close the ticket without doing this, but it would be nice.
- [x] [`Builder`](https://doc.rust-lang.org/std/thread/struct.Builder.html)'s docs are... okay. Just very uninspired.
- [x] [`JoinHandle`](https://doc.rust-lang.org/std/thread/struct.JoinHandle.html) doesn't go into enough detail, and should show off, for example, the detach behavior.
- [x] [`LocalKey`](https://doc.rust-lang.org/std/thread/struct.LocalKey.html) could use some links and general cleanup.
- [x] [`Thread`](https://doc.rust-lang.org/std/thread/struct.Thread.html) has very little and very boring docs.
- [x] [`panicking`](https://doc.rust-lang.org/std/thread/fn.panicking.html) could use some more advice on when to use this.
- [x] [`park`](https://doc.rust-lang.org/std/thread/fn.park.html) should have its module documentation inlined here, and cleaned up.
- [x] [`park_timeout`](https://doc.rust-lang.org/std/thread/fn.park_timeout.html) could use links to `park`
- [x] [`spawn`](https://doc.rust-lang.org/std/thread/fn.spawn.html) needs a lot more docs generally. It's the main interface to this module!
- [x] [`yield_now`](https://doc.rust-lang.org/std/thread/fn.yield_now.html) doesn't explain any of the "why".
- [x] [`Result`](https://doc.rust-lang.org/std/thread/type.Result.html) should at least show off the "use std::thread; thread::Result" pattern, like all module-specific `Result` types.

**Comment by steveklabnik** [comment]
I am happy to mentor anyone who wants to tackle this issue.

**Comment by oldmanmike** [comment]
I would be interested in taking on the documentation improvement of `Builder` as a starter. I'd take on more, but no need to get ahead of myself.

**Comment by steveklabnik** [comment]
@oldmanmike awesome! Please let me know if you need anything.

**Comment by z1mvader** [comment]
I am not (by any means) an expert on this topic but I'd love to help on this one, as @steveklabnik says: writting docs is the best way to learn something

**Comment by imiuka** [comment]
I'd love to take on what's left - @oldmanmike @z1mvader do you guys plan to work on any (all?) of these?

**Comment by z1mvader** [comment]
I believe I will be taking the joinHandle and Thead docs

**Comment by rap2hpoutre** [comment]
Ok so I still need some mentoring! Here is a (working) example I quickly wrote for `std::thread::Result`. 

```rust
use std::thread;
use std::any;

fn main() {
    let child = thread::spawn(move || panic!("Oups"));

    let res: thread::Result<Box<any::Any + Send + 'static>> = child.join();

    match res {
        Ok(_) => println!("this is fine"),
        Err(_) => println!("thread panicked"),
    }
}
```

I think (but not sure) this example could help because type is explicit, so the user know what he can do with this `std::thread::Result`. 

@steveklabnik asked: 

> Result should at least show off the "use std::thread; thread::Result" pattern, like all module-specific Result types.

But I'm not sure to understand what does "use std::thread; thread::Result" means. I read an other example in std on `io::Result`: https://doc.rust-lang.org/std/io/type.Result.html but it seems different, I preferred wrote something more specific to threads. 

Anyway, I'm not sure my example follows best practices. And I'm not sure it's useful. So, once again @steveklabnik please help! :)

**Comment by steveklabnik** [comment]
> But I'm not sure to understand what does "use std::thread; thread::Result" means. I read an other example in std on io::Result: https://doc.rust-lang.org/std/io/type.Result.html but it seems different, I preferred wrote something more specific to threads.


It's what you wrote, specifically

```rust
use std::thread;

let res: thread::Result<()> ...
```

that is, you use this style instead of `use std::thread::Result;` which would be more conventional generally speaking. The reason why is so you don't shadow `std::result::Result` from the prelude.

> Anyway, I'm not sure my example follows best practices. And I'm not sure it's useful. So, once again @steveklabnik please help! :)

I think this example is _okay_, but we might be able to make it better! What about a function that does the spawn and join, and returns the result? then, you wouldn't be adding the extra type for no reason, as the function signature would use it. This is similar to how the `Write` trait has methods that return their `Result`s.

The question is what that function should _do_...

**Comment by rap2hpoutre** [comment]
>  What about a function that does the spawn and join, and returns the result?

Okay, I think you mean:

```rust
use std::thread;

fn spawn_and_join() -> thread::Result<()> {
    let child = thread::spawn(move || panic!("Oups"));
    child.join()
}

fn main() {
    match spawn_and_join() {
        Ok(_) => println!("this is fine"),
        Err(_) => println!("thread panicked"),
    }
}
```

But...

> The question is what that function should do...

From there I'm a bit lost: my example has _still_ no sense (what's that `spawn_and_join` function and why?), but I don't know how to create something with sense in a few lines. Maybe I should call something that _could_ panic? Something like:

```rust
fn open_file_in_thread() -> thread::Result<()> {
    let child = thread::spawn(move || {
        File::open("foo.txt").unwrap();
        // etc.
    });
    child.join()
}
```

But it's a "not real" example too. Should I give up?

**Comment by gamazeps** [comment]
@steveklabnik Hey ! I'm a bit rusty (haven't rusted in a year or so), so I'm looking to get back to it by helping with the docs, which item still need documentation in the list ?

Cheers

**Comment by steveklabnik** [comment]
@gamazeps wonderful! Everything except the last one is still open, and that's because there's a PR open, but not merged, hence no checkmark.

**Comment by z1mvader** [comment]
@steveklabnik I believed that the Thread docs were good enough :(

**Comment by gamazeps** [comment]
@steveklabnik Ok, sign me in for:

- Thread has very little and very boring docs.
- panicking could use some more advice on when to use this.
- park should have its module documentation inlined here, and cleaned up.
- park_timeout could use links to park
- spawn needs a lot more docs generally. It's the main interface to this module!

Should be done by wednesdy in the worst case scenario :)

**Comment by steveklabnik** [comment]
@gamazeps I think you pinged me on IRC, but i wasn't on until you were gone. Sorry!

About `thread::park`, it contains this line "See the module documentation for more detail.". That's this: https://doc.rust-lang.org/std/thread/index.html#blocking-support-park-and-unpark

These docs really belong on park, rather than in the module, so moving it there is what I meant by "inlining." does that make sense?

**Comment by gamazeps** [comment]
Yup, I copied some of them in `park`, but I will move them all if that's good with you

**Comment by gamazeps** [comment]
@steveklabnik what exactly do you have in mind for the documentation of `thread::spawn`, the only thing I could thing of is to add more examples and a link to `thread::Builder` for 'advanced' use.

**Comment by steveklabnik** [comment]
@gamazeps I think pointing out the `'static` constraint is a good idea, as well as `Send`, and talking about why those things exist. Maybe even calling out to the idea of "scoped threads", and linking to https://crates.io/search?q=scoped%20threads is okay...

**Comment by gamazeps** [comment]
@steveklabnik do you want me to add this to #41854 ? Or in another PR ?

**Comment by steveklabnik** [comment]
Either works; whatever is more convenient for you 😄

**Comment by gamazeps** [comment]
I usually prefer to get things merge as soon as possible, but I have no strong opinions about that.

Once the current PRs are merge I think we can tick off:

- Thread has very little and very boring docs.
- panicking could use some more advice on when to use this.
- park should have its module documentation inlined here, and cleaned up.
- park_timeout could use links to park

I'll add a part on `Send`, `Sync` and `'static`, so that we can also tick:

- spawn needs a lot more docs generally. It's the main interface to this module!

After that I'll go on

- Builder's docs are... okay. Just very uninspired.
- JoinHandle doesn't go into enough detail, and should show off, for example, the detach behavior.
- LocalKey could use some links and general cleanup.

And if I have time enough, I'll go on the module doc too (but probably next week), so that we can close this issue.

Sounds good ?

**Comment by steveklabnik** [comment]
Sounds wonderful! Thank you so much for all your work here.

**Comment by gamazeps** [comment]
@steveklabnik All ticks are done except for the documentation module.

I may try to get that done tomorrow, so we can either close the issue once the PRs are landed or once I add the new module documentation.

**Comment by steveklabnik** [comment]
@gamazeps thank you so much! ❤️

**Comment by SeanPrashad** [comment]
Hi @steveklabnik! I'd LOVE to help bring this across the finish line but with the last documentation issue for the [module docs](https://doc.rust-lang.org/std/thread/). I'd greatly appreciate some guidance with where to start if it's possible 🙂

**Comment by steveklabnik** [comment]
Hey @SeanPrashad that'd be amazing!

One option is

> A particularly enthusiastic contributor could toss this out and re-write it from scratch.

Which would be a bunch of work but might be the way to go.

Basically, I don't think the docs are organized well; they're kind of just a random collection of thoughts. So I think the first task is, how do we want to organize these docs? Generally, good module docs show an overview of the module conceptually, and then highlight key APIs. Maybe we can start there?

**Comment by SeanPrashad** [comment]
I don't mind putting in the work to get the docs updated - I enjoyed doing it last time!

I agree with what you've mentioned for the first task - give the user an overview and showcase key APIs that the module provides. I'll give that a go and touch base on IRC if I have any questions or when I'm looking for feedback!

**Comment by steveklabnik** [comment]
Quoting myself above:

> If the rest of this work gets done, we can close the ticket without doing this, but it would be nice.

We haven't come up with a good plan for the module docs, and so I'm going to close this ticket. If anyone has specific thoughts about improving them, please open a new ticket with details! Thanks.
