### ISSUE TITLE
API Docs: macros

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29381]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/#macros

Here's what needs to be done to close out this issue: 

- [ ] [`assert`](https://doc.rust-lang.org/std/macro.assert.html) could use links to `panic!`, and "This macro has a second version," should be about one and two argument forms, not "versions". In general, these docs could use some headers for each bit, rather than the rambly style they're in now.
- [ ] [`assert_eq`](https://doc.rust-lang.org/std/macro.assert_eq.html) could use links to `assert!`, also dropping the `()`. same deal with "versions" too. Mentioning its relationship to `PartialEq` would be nice.
- [ ] [`assert_ne`](https://doc.rust-lang.org/std/macro.assert_ne.html) has the same issues as `assert_eq!`.
- [ ] [`column`](https://doc.rust-lang.org/std/macro.column.html) needs to drop the `()`s, and doesn't explain why you might care about the column that it was invoked in. 
- [ ] [`debug_assert`](https://doc.rust-lang.org/std/macro.debug_assert.html) needs a bunch of links, and should really end up mostly pointing to the docs of `assert`.
- [ ] [`debug_assert_eq`](https://doc.rust-lang.org/std/macro.debug_assert_eq.html) same as `debug_assert`, that is, should mostly point to `assert_eq`.
- [ ] [`debug_assert_ne`](https://doc.rust-lang.org/std/macro.debug_assert_ne.html), same as the two previous. 
- [ ] [`file!`](https://doc.rust-lang.org/std/macro.file.html) same as `column!`
- [ ] [`format!`](https://doc.rust-lang.org/std/macro.format.html) this macro is very useful and has very little docs, what a shame! It should have a lot more, at least pointing out that it's a common way to concatenate a lot of strings, for example.
- [ ] [`format_args`](https://doc.rust-lang.org/std/macro.format_args.html) could use a lot of work, mostly expanding on what it is and why it's there.
- [ ] [`include`](https://doc.rust-lang.org/std/macro.include.html) this macro explains why it's bad but then doesn't show an example. It should.
- [ ] [`line!`](https://doc.rust-lang.org/std/macro.line.html) similar to `column!`
- [ ] [`option_env!`](https://doc.rust-lang.org/std/macro.option_env.html) needs links to `Option<T>`
- [ ] [`panic!`](https://doc.rust-lang.org/std/macro.panic.html) has anemic docs for something so heavily used!
- [ ] [`print!`](https://doc.rust-lang.org/std/macro.print.html) could use a bunch of links
- [ ] [`println!`](https://doc.rust-lang.org/std/macro.println.html) could use links
- [ ] [`thread_local`](https://doc.rust-lang.org/std/macro.thread_local.html) should link when it mentions `LocalKey`, not at the end.
- [ ] [`try!`](https://doc.rust-lang.org/std/macro.try.html) should be a little more strongly worded about `?` and should show examples of their equivalence.
- [ ] [`unreachable!`](https://doc.rust-lang.org/std/macro.unreachable.html) should discuss how it's different than the intrinsic.
- [ ] [`vec!`](https://doc.rust-lang.org/std/macro.vec.html) could use a lot of links and some more text.
- [x] [`write!`](https://doc.rust-lang.org/std/macro.write.html) has just... awkward docs. It's a weird macro, so that's why, but it could use re-done, IMHO.
- [x] [`writeln`](https://doc.rust-lang.org/std/macro.writeln.html) should mostly link to `write!` and point out that it's the same but with the extra newline.

**Comment by durka** [comment]
Not sure it's within the scope of this issue (since this is about the content), but see #26560.

**Comment by steveklabnik** [comment]
I am happy to mentor anyone who wants to tackle this issue.

**Comment by dpen2000** [comment]
I'll take a look at these @steveklabnik

**Comment by steveklabnik** [comment]
@dpen2000 awesome! Let me know if you need anything 😄

**Comment by citizen428** [comment]
@steveklabnik Seems like `write!` and `writeln!` docs have been merged now, please update the original checklist. 

I'll try to work through `assert`, `assert_eq` and `assert_ne` tomorrow.
