### ISSUE TITLE
Tracking issue for OpenOptions expansion

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#30014]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1252

Unstable APIs:

* [x] `OpenOptions::create_new`
* [ ] `os::unix::fs::OpenOptionsExt::custom_flags`
* [ ] `os::windows::fs::OpenOptionsExt::custom_flags`

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for tentative stabilization in 1.9 :bell:

Some concerns the libs team has, however, about this API are:

* The name may not always convey what's going on here.
* There are perhaps confusing semantics with calls like `.create_new(true).create(false)`. Specifically ignoring some flags may not work out so well.

**Comment by alexcrichton** [comment]
Ah and to clarify, we're just considering `OptionOptions::create_new` for stabilization, not the `custom_flags` methods.

**Comment by pitdicker** [comment]
The combination of `.create_new(true)` with `.create()` and `.truncate()` was discussed in the pr of rust-lang/rfcs#1252. Clippy now contains a [nonsensical_open_options](https://github.com/Manishearth/rust-clippy/wiki#nonsensical_open_options) lint that should catch this (but I don't know if checks for this case already). But a name that gives completely no confusion would of course be best :).

**Comment by durka** [comment]
What is "tentative stabilization"?

**Comment by alexcrichton** [comment]
Ah just in the sense that we're leaning towards stabilization, but not necessarily fully committed to it. If there are arguments against stabilizing then we're willing to wait/postpone.

**Comment by d3zd3z** [comment]
A real example of where `custom_flags` would be useful, and I'm using a horrendous hack to work around it not being stable: [open with O_NOATIME](https://github.com/d3zd3z/rsure/blob/master/src/hashes.rs#L136).

**Comment by aturon** [comment]
Regarding nonsensical combinations of options: we could consider panicking in such cases at the point that you attempt to open the file. (A panic because this is a contract violation, somewhat akin to passing a non-nonsensical memory ordering to an atomic operation.)

I definitely don't think it's worth trying to rule this out statically (using typestate or something like that).

**Comment by BurntSushi** [comment]
@aturon I definitely agree with not trying to rule it out statically. What if we returned an error instead of panic'ing? I think we could reasonably call it a contract violation, but what are the downsides of returning an error? One potential use case where an error might be more helpful is if the open options were constructed based on some other input (perhaps it was provided by or derived from a user). If the final call panic'd when the options were nonsense, I'd feel obligated to implement my own logic to ensure the options weren't nonsense. If however it returned an error, I might just rely on that instead, which does seem a bit more convenient.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **stabilize** with errors returned at runtime for "weird" situations.

**Comment by alexcrichton** [comment]
Ok, rereading things and thinking more closely, as @pitdicker [pointed out](https://github.com/rust-lang/rust/issues/30014#issuecomment-196302478) the behavior is already specified as ignoring create/truncate, so I've just left as is and stabilized without modifications.

**Comment by alexcrichton** [comment]
cc @rust-lang/libs

**Comment by alexcrichton** [comment]
Oops there's still a few unstable APIs here

**Comment by alexcrichton** [comment]
🔔 This issue is now entering its cycle-long **final comment period** for stabilization 🔔 

The libs team basically feels the same way about this as https://github.com/rust-lang/rust/issues/27720, we just want to make sure there's a comprehensive story here.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **stabilize**
