### ISSUE TITLE
Implement placement-in protocol for relevant data structures

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#30172]
We currently have the unstable new arrow syntax (`<-`) for placement-in in nightly with intention to see how people like the syntax/how ergonomic it is/etc. However, it is pretty hard to try the syntax out without having any useful/common data-structures implementing the placement-in protocol and thus it is pretty unlikely for us to collect much feedback on the syntax.

The `Placer`, `Place` and `InPlace` traits should be implemented for following data structures as appropriate:
- [x] [Vec](http://doc.rust-lang.org/nightly/std/vec/struct.Vec.html) (`&mut myvec <- value`; see [this RFC](https://github.com/rust-lang/rfcs/issues/1286) regarding mutable reference) https://github.com/rust-lang/rust/pull/32366
- [x] [HashMap](http://doc.rust-lang.org/nightly/std/collections/struct.HashMap.html) through [Entry](http://doc.rust-lang.org/nightly/std/collections/hash_map/enum.Entry.html) (i.e. `mymap.entry(k) <- value`) https://github.com/rust-lang/rust/pull/40390
- [ ] [BTreeMap](http://doc.rust-lang.org/nightly/std/collections/struct.BTreeMap.html) through [Entry](http://doc.rust-lang.org/nightly/std/collections/btree_map/enum.Entry.html).
- [x] LinkedList https://github.com/rust-lang/rust/pull/31696
- [x] [BinaryHeap](http://doc.rust-lang.org/nightly/std/collections/struct.BinaryHeap.html) (`&mut heap <- value`) https://github.com/rust-lang/rust/issues/39062
- [x] [VecDeque](http://doc.rust-lang.org/nightly/std/collections/struct.VecDeque.html) (`front_place` and `back_place`, like `LinkedList`) https://github.com/rust-lang/rust/pull/40389

It should also be investigated how viable implementing placement protocol is for other `std::collections` collections and possibly implementing these as well.

Since both placement protocol and placement-in syntax are unstable, there’s no stability hazard.

cc @pnkfelix.

---

I personally feel this issue has tons of potential to help people get acquainted with rust’s standard library (i.e. is in E-easy land) and would be willing to answer any questions (E-mentor) regarding implementation strategies on IRC or the issue itself.

**Comment by pnkfelix** [comment]
we might consider `myvec.back() <- value` rather than `myvec <- value`. the main reason I can think of of hand is that there may be issues related to indexing sugars, e.g. ambiguity of `mymap[k] <- value` when you have a map with vec values.

**Comment by apasel422** [comment]
@nagisa `BTreeMap` is also a candidate through its `Entry`.

**Comment by nagisa** [comment]
@apasel422 added to the list.

**Comment by nagisa** [comment]
Since the LinkedList has been implemented one could use the PR as example when implementing the protocol for other collections.

**Comment by notmatt** [comment]
@nagisa this looks like something I'd like to take a swing at; would some initial code in a week (±a weekend) be ok?

**Comment by nagisa** [comment]
Sure!

**Comment by notmatt** [comment]
@nagisa quick update: apart from an unexpected shortage of spare time, this is going well. I've mostly been reading/understanding Placer et alia & the LinkedList implmentation. I'm starting with the VecDeque given its broad similarity, but not a lot to show yet.

**Comment by pcwalton** [comment]
Wanted for WebRender.

**Comment by nagisa** [comment]
Dear T-libs members. It has been a

* bit more than a year since this issue has been created;
* 3 quarters since https://github.com/rust-lang/rust/pull/32366 where there was a note that there needs to be some conventions;
* 1 quarter since Servo expressed their immense interest in this feature;
* 1 quarter since there seemingly was a discussion by T-libs members with no aftermath posted whatsoever.

Perhaps the boring, cold and silent cooldown period after Christmas could be a good time to ponder on whatever you think is the best and report after the vacation?

I’d like to note that gaining experience with placement-in is *literally* blocking stabilisation of this feature and since nothing implements the placement-in stuff, nobody is using it, ergo not gaining experience. I feel like adding the placement-in impls, be it in an unstable form, is the easiest way to break this loop that’s pulling this awesome feature to the cold hands of Ms. Banshee.

**Comment by aturon** [comment]
@nagisa Thanks for the reminder! It looks like what happened here is that the libs team discussion was posted [to the PR](https://github.com/rust-lang/rust/pull/32366#issuecomment-240231116) rather than the tracking issue.

To recap:

> - Collections like `Vec` which have a clear "default place" can implement the protocol directly, e.g. `vec <- item`.
> - Otherwise standardizing around the convention `collection.place_location() <- item` seems reasonable. For example `vec.place_front() <- item`

But then [it turned out](https://github.com/rust-lang/rust/pull/32366#issuecomment-240272462) we can't quite get the desired sweet syntax for `Vec` yet, so we're proposing using `place_location` as the convention. PRs along these lines continue to be welcome.

(In terms of priority, placement continues to not be a high priority as far as I'm aware.)

**Comment by bluss** [comment]
API issue: reusing Vec's placer type allows violating memory safety (writing to the Vec without allocating space). See issue #44637

**Comment by bluss** [comment]
I'm a bit concerned that this lands close to arbitrary memory writes in safe code [(playground link)](https://play.rust-lang.org/?gist=fb67c9138789da84d47db92258788920&version=nightly); in particular that the Placer trait returns a raw pointer and the desugaring trusts that pointer.

I'm sorry if this has come up before, I can't find it exactly, at least not with the full context.

**Comment by F001** [comment]
I also wonder whether it is useful to implement placement-in protocol for many wrapper types beside collections, such as `Option`  `Cell`  `RefCell`  etc.

**Comment by tamird** [comment]
Looks like this is headed in the opposite direction now? https://github.com/rust-lang/rfcs/pull/2387

**Comment by estebank** [comment]
Closing as per removal of placement features in #48333.
