### ISSUE TITLE
Tracking issue for std::sync::Once poisoning

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#33577]
This tracks the `once_poison` feature, which currently covers the following things under `std::sync::once`:
- [ ] `OnceState`, a struct describing the poisonedness of a `Once`
- [ ] `OnceState::poisoned`, which reveals said poisonedness
- [ ] `Once::call_once_force`, which is like `call_once` but ignores poisoning

**Comment by brson** [comment]
This issue is primarily about the `call_once_force` method. Once implements poisoning, and this method is how you get around a poisoned `Once`.

**Comment by frewsxcv** [comment]
Anyone have insight why `poisoned` is not just a method on `Once`?

**Comment by dtolnay** [comment]
This naming seems inconsistent:

- [`Mutex::is_poisoned`](https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.is_poisoned)
- [`OnceState::poisoned`](https://doc.rust-lang.org/std/sync/struct.OnceState.html#method.poisoned)

Could they both be `is_poisoned` since that one is stable already? Or is `poisoned` better enough that we should deprecate and rename the one on Mutex?

**Comment by joshlf** [comment]
Relevant: #43448 contains discussion of whether forking a process should cause poisoning of various synchronization primitives. TLDR: An option is to make it so that if you fork while a `Once` is in use, thus invalidating it, that `Once` becomes poisoned.

**Comment by steveklabnik** [comment]
Triage: no changes here that I'm aware of.

**Comment by sanmai-NL** [comment]
#43448 was closed. @joshlf Can this issue be expedited, without discussing more than one scenario in which  the state should be poisoned?

**Comment by joshlf** [comment]
Yes, the "poison on fork" proposal should be considered dead for the time being. The discussion in this issue can safely ignore that proposal.

**Comment by Amanieu** [comment]
I think this API is well designed and worth stabilizing. Note that parking_lot uses a [difference `OnceState`](https://docs.rs/parking_lot/0.10.2/parking_lot/enum.OnceState.html), but I think the current one we have in libstd is fine as it is.

@rfcbot fcp merge

**Comment by Kixunil** [comment]
Apart from consistency I find `is_poisoned` more clear than `poisoned`. The latter sounds a bit like a constructor that creates a poisoned instance.

**Comment by Kixunil** [comment]
Should this API stabilize after successful FCP or do I misunderstand stabilization process?

**Comment by Amanieu** [comment]
Someone needs to submit a stabilization PR for this feature.

**Comment by Kixunil** [comment]
@Amanieu OK, I decided to become that someone. :) Thanks for clarifying!
