### ISSUE TITLE
Tracking Issue for Incr. Comp. Regression Testing

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#36350]
Incremental compilation needs good regression testing, which can be split into the following components:
- End-to-end tests for specific common cases, like already present to some extent in [test/incremental](https://github.com/rust-lang/rust/tree/master/src/test/incremental). These will use the `#[rustc_clean]`/`#[rustc_dirty]` and `#![rustc_partition_reused]` infrastructure.
- Tests for the Incremental Compilation Hash (ICH) that we compute for input data (i.e. HIR and imported Metadata). I'll open individual issues for each of the below soon.
  - [x] Test ICH for structs (see PR https://github.com/rust-lang/rust/pull/36370)
  - [x] Test ICH for enums (#36674)
  - [x] Test ICH for traits (#36681)
  - [x] Test ICH for function interfaces (#36812)
  - [x] Test ICH for function bodies
     - [x] Test ICH for unary and binary expressions (#37520)
     - [x] Test ICH for call expression (#37693)
     - [x] Test ICH for `let` statements (#37654)
     - [x] Test ICH for `match` expressions (#37654)
     - [x] Test ICH for `if` expressions (#37694)
     - [x] Test ICH for `while` loops and `loop` loops (#37841)
     - [x] Test ICH for `for` loops (#37841)
     - [x] Test ICH for closure expressions (#38202)
     - [x] Test ICH for struct constructor expressions
     - [x] Test ICH for enum constructor expressions (#38202)
     - [x] Test ICH for slice/indexing expressions (#38202)
     - [x] Test ICH for inline assembly (#38557)
  - [x] Test ICH for `extern` blocks (#38479)
  - [x] Test ICH for inherent impls/methods (#38502)
  - [ ] Test ICH for trait impls/methods (#38849)
  - [x] Test ICH for `type` definitions (#37799)
  - [x] Test ICH for statics (#37001)
  - [x] Test ICH for constants (#37000)
  - [x] Test ICH for command line arguments
- Dependency graph oriented tests that make sure that certain edges are present or not present under certain circumstances. These will use the `#[rustc_if_this_changed]`/`#[rustc_then_this_would_need]` infrastructure.
- Git history based tests that will walk the history of some selected crates, building each revision incrementally and from scratch and then comparing the two for equality. These tests will be based on [cargo incremental](https://github.com/nikomatsakis/cargo-incremental). See https://github.com/rust-lang/rust/issues/36809 for more information.

In order to make it easy to contribute in this area, we'll also want to
- Compile links to the appropriate documentation of the test framework and some of the concepts and inner workings of incremental compilation
- Provide well-documented examples of what test cases in various areas should look like
- Expand the above list with as concrete as possible descriptions of individual test cases we are interested in, and open individual GH issues for them.
