### ISSUE TITLE
Tracking issue for `invalid_type_param_default` compatibility lint

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#36887]
TODO: write the description

#### Current status

- [x] https://github.com/rust-lang/rust/pull/30724 introduces the `invalid_type_param_default` lint as warn-by-default
- [ ] PR ? makes the `invalid_type_param_default` lint deny-by-default
- [ ] PR ? makes the `invalid_type_param_default` lint a hard error

**Comment by petrochenkov** [comment]
@nikomatsakis, could you write a description for this?

**Comment by nikomatsakis** [comment]
@petrochenkov done.

**Comment by nrc** [comment]
Where can I find discussion of this issue? I don't see any on RFC 213, nor its tracking issue (#27336).

**Comment by nikomatsakis** [comment]
@nrc perhaps I should have phrased the summary with slightly differently. I think the main thing is that defaults were being accepted **in stable code** but ignored, unless you opt in to a feature gate, which gives them some semantics (but semantics that I now think I disagree with).

**Comment by RReverser** [comment]
Is there a reason this is being phased out on functions?

It's sometimes useful to have `fn do_smth<A, B=A>(a: A, b: B) { ... }`.

**Comment by nikomatsakis** [comment]
@RReverser Yes. Because, IIRC, they are basically ignored on stable Rust. On nightly Rust, meanwhile, we were considering various possible meanings, but have not yet found one that we are satisfied with.

**Comment by RReverser** [comment]
Ok, I'm now curious... where can I read about other possible meanings? The expectation seems pretty straightforward, just like in case with `struct` - that with `do_smth<T=SomeType>`, `do_smth` would be equivalent do `do_smth<SomeType>` but maybe I'm missing some issues?

**Comment by excaliburHisSheath** [comment]
I'm also curious as to what the issue is for default type arguments in generic functions. I'm running into a case where it would greatly help ergonomics of using a function with an optional generic parameter: https://is.gd/Gy9bXW

**Comment by est31** [comment]
I think this feature is very useful for API evolution e.g. when you add a generic type parameter and want to keep stability, and I think much better than inferring the type instead.

Apparently there are some issues with the implementation. Can they maybe be fixed instead of removing the feature? Would that require an RFC?

**Comment by ExpHP** [comment]
I *think* I see what the difficulty is. Bear with me:

> The expectation seems pretty straightforward, just like in case with struct - that with `fn do_smth<T=SomeType>() {}`, `do_smth()` would be equivalent do `do_smth::<SomeType>()`

So, yes, this is exactly how it works for types and traits, and it is exactly what we *don't* want for functions.  Let's look at @randomPoison's example.  Here's what we would love to be able to write, correct?

```rust
fn main() {
    let _ = foo(Some("I'm a string"));
    let _ = foo(None);  // type inference error!!
}

pub fn foo<S = String>(opt: Option<S>) -> String
    where S: Into<String>
{
    opt.map(Into::into).unwrap_or_default()
}
```

Okay, now, let's assume generic type parameters for functions worked just like those for types.  **Turns out this code still wouldn't compile.** Why?  Because it would be equivalent to this:

```rust
fn main() {
    // nothing was specified, so use the default
    let _ = foo::<String>(Some("I'm a string")); // type mismatch: &str vs String

    // nothing was specified, so use the default
    let _ = foo::<String>(None);
}
```

when what we **really want** is this:

```rust
fn main() {
    // infer the type *if possible*...
    let _ = foo::<_>(Some("I'm a string"));

    // ...otherwise, use a default
    let _ = foo::<String>(None);
}
```

which appears to require a far greater application of pixie dust.

**Comment by RReverser** [comment]
@exphp Personally I'd rather prefer the explicit default to be used in that example over the contextual inference, although I can see some people wanting the opposite. More common usecase would be where type can't be inferred at all, just like currently used for optional type params in structs like HashMap.

**Comment by randomPoison** [comment]
@ExpHP That's a good point. I guess what I really wanted was more of a default type *hint*, i.e. "always try to infer the correct type, and if there's not enough information to infer a type, use the specified type as the default. That's probably a different feature than the one being discussed in this issue, though.

**Comment by petrochenkov** [comment]
@randomPoison 
>I guess what I really wanted was more of a default type hint, i.e. "always try to infer the correct type, and if there's not enough information to infer a type, use the specified type as the default".

It's not clear how exactly this should be done, and this is the single most important blocker for progress on this issue and all related features (e.g. https://github.com/rust-lang/rfcs/pull/2176).
See https://github.com/rust-lang/rust/issues/27336 (including links to other threads) for some history.

**Comment by burtonageo** [comment]
Is there a plan to make this work for generic associated types e.g. in the following code ([playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=678843ed3f9278ec241f15dcc3e1335b))? At the moment, this is a hard error.

```rust
#![feature(generic_associated_types)]

use std::ops::Deref;

trait SomeTrait {
    type Assoc<T = i32>: Deref<Target = T>;
}

fn main() {
}
```

**Comment by mankinskin** [comment]
> ```rust
> fn main() {
>     let _ = foo(Some("I'm a string"));
>     let _ = foo(None);  // ERROR: type annotation needed
> }
> 
> pub fn foo<S = String>(opt: Option<S>) -> String
>     where S: Into<String>
> ```
I don't think this is the point of using default type parameters for functions. In your example it could easily be derived what the type of `foo(None)` should be, simply the same as `foo::<String>(None)`, as the type parameter was omitted and the default kicks in.

I have a use-case where I want to be able to apply a default value to a trait `impl`:
```
enum FilterOp<T=()> {
    Binary(T),
    Unary
}
trait Filter<T=()> {
    fn filter(self, field: &str, op: FilterOp<T>) -> Self;
    ...
}

impl<T=()> Filter<T> for Query {
    fn filter(self, field: &str, op: FilterOp<T>) -> Self {
        ...
    }
}
```
And then use the function `filter` with `FilterOp::Unary`:
```
query.filter("field", FilterOp::Unary) // should use default -> FilterOp<()>
```
But for some reason `filter` doesn't apply the default for `FilterOp<T>` and it is not allowed to define a default in the trait implementation of `Filter<T>`.

I have opened a thread on the rust-lang user forum: [here](https://users.rust-lang.org/t/why-cant-this-generic-function-resolve-a-type-from-a-default-type-parameter/34631)

**Comment by ExpHP** [comment]
> In your example it could easily be deduced what the type of `foo(None)` should be, simply the same as `foo::<String>::(None)`, as the type parameter was omitted and the default kicks in.

My point was that `foo(Some("I'm a string"));` would suddenly *stop* working for the same reason.

> ```rust
> impl<T=()> Filter<T> for Query {
>     fn filter(self, field: &str, op: FilterOp<T>) -> Self {
>         ...
>     }
> }
> ```

Defining a default in a impl seems like an absolutely crazy idea.  Impls could come into play for all sorts of reasons, and before long you could have two impls trying to specify conflicting defaults for the same type parameter. (this can happen with functions too, but for impls its more subtle because they are not explicitly named in the function body!)

The reason `FilterOp::Unary` doesn't use the type default is because defaults currently only apply to types, not expressions.  `FilterOp` in this case is only part of a path expression.  Surrounding it in angle brackets however would make it a type:

```rust
written            equivalent
FilterOp::Unary    FilterOp::<_>::Unary
<FilterOp>::Unary  <FilterOp<()>>::Unary
```

Like it or not, I'm pretty sure it would be a breaking change to make the former behave like the latter, as there may be code out there which currently uses an enum isomorphic to FilterOp, but where the variant similar to Unary is sometimes used for `T` not equal to the default.

**Comment by jhpratt** [comment]
For what it's worth, having a default type parameter on a function would be _incredibly_ useful for what I'm trying to accomplish. I'm currently trying to use typestate to statically guarantee a format description is valid (for the time crate). Part of this is the parsing of the format description; the parsing itself depends on what it'll be used for (this should be inferred). As a component may or may not be present (think true/false in const generics), the compiler currently can't determine what type should be used for this generic parameter. A default would resolve this issue.

**Comment by tbraun96** [comment]
Please keep/allow default type params on functions

**Comment by MagicRB** [comment]
1 up for default function parameters, especially useful for Enums where only some variants include the generic types...

**Comment by xNxExOx** [comment]
I have bit different example:
```rust
fn some_fn<T: MyTrait = DefaultMyTrait>(text: &str, another_param: usize) -> Result<(), ()>{
    T::check_text(text);
    // some more operations
    Ok(())
}
```
in this case there can not be mistakes about type interference because `T` **can NOT** be interfered.
How probable is that this case will stay working?

@petrochenkov "The goal of this page is describe why this change was made and how you can fix code that is affected by it."
am I missing the part "**how you can fix code that is affected by it**", or am I just bad reader and it is already explained here?

**Comment by nikomatsakis** [comment]
@xNxExOx there really isn't a fix apart from removing the default. I'm not sure how likely it is that this case in particular will keep working -- we may never stabilize defaults outside of type declarations. I hadn't considered the idea of spearating out "type parameters that do not appear in the parameter list", though certainly one could do so.

**Comment by xNxExOx** [comment]
Well I find a  way how to change my code to use iterator like structures instead, so I can provide the defaults in another way (not sure if it was best decision yet).
But my questions about the case I write stands, just not a priority anymore, did I understood it correctly that this default is safe to use, and does not have any unexpected behaviors?
And from your answer it seems like this way of avoiding code duplicity was not even considered, so it is good to offer a case that might be useful.

**Comment by nikomatsakis** [comment]
@xNxExOx I don't see any particular problems from your example, correct. And yes, thanks for raising it! It's a useful pattern to consider.

**Comment by ohsayan** [comment]
I think having type params in `fn`s is very useful. For example, think about a situation where:
```rs
pub trait FromBytes {
    fn from_bytes(inp: &[u8]) -> Self;
}

pub fn get_from_bytes<T: FromBytes = Vec<u8>>(inp: &[u8]) -> T {
    // ... do something ...
    T::from_bytes(inp)
}
```

So, for the `get_from_bytes` this can be extremely useful: if the user doesn't pass any type param for this fn, then we can just return `Vec<u8>`, else we can return whatever type param was passed:

```rust
let myslice = &somevar[..];
let x = get_from_bytes(myslice); // <- x gets a type of `Vec<u8>`
let y: MyFancyType = get_from_bytes(myslice); // <- y gets a custom type implementing `FromBytes`
```

I don't see why we want to remove this. The consequence of removing this would be to force the user to assign a type to `x` as in the above example.

**Comment by ExpHP** [comment]
> I don't see why we want to remove this.

This functionality isn't being removed because it *never existed* in the first place.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=88aab65540b9a215ae0c67c74312516c

```
   Compiling playground v0.0.1 (/playground)
error[E0282]: type annotations needed
  --> src/main.rs:33:9
   |
33 |     let x = get_from_bytes(myslice); // <- x gets a type of `Vec<u8>`
   |         ^ consider giving `x` a type
```

The only change is that the compiler now rejects the code, rather than (misleadingly) accepting it.

**Comment by ohsayan** [comment]
> > I don't see why we want to remove this.
> 
> This functionality isn't being removed because it _never existed_ in the first place.
> 
> https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=88aab65540b9a215ae0c67c74312516c
> 
> ```
>    Compiling playground v0.0.1 (/playground)
> error[E0282]: type annotations needed
>   --> src/main.rs:33:9
>    |
> 33 |     let x = get_from_bytes(myslice); // <- x gets a type of `Vec<u8>`
>    |         ^ consider giving `x` a type
> ```
> 
> The only change is that the compiler now rejects this syntax, rather than ignoring it.

Better put, it's something that would be a good thing to have.

**Comment by AljoschaMeyer** [comment]
Trying to use a default parameter in a generic associated type (via `#![feature(generic_associated_types)]`) points to this issue, although the discussion here seems to be focused on function parameters. Any chance that default parameters for GATs could become supported even if they are rejected for functions?

Example use case: allocator-aware smart pointers that mimic the API patterns of the standard library:

```rust
pub trait SmartPointer {
    type P<T, A: Allocator = Global>;

    fn new<T>(t: T) -> Self::P<T>;

    fn new_in<T, A>(t: T, alloc: A) -> Self::P<T, A>;
}
```

**Comment by rouanth** [comment]
I was playing around with making a wrapper that performed mutations and then returned the mutated argument, so that some elegant one-liners could be written for tests.

Without the default type parameters, I fail to imagine a definition such that both lines using `mutated` compile without extra type annotations.
```rust
fn mutated<T, F, S: ?Sized = T>(mut t: T, mut f: F) -> T where F: FnMut(&mut S), T: AsMut<S> {
    f(t.as_mut());
    t
}

fn main() {
    let my_vec1 = mutated(vec![0, 3, 2, 1], |v| { v.sort() });
    let my_vec2 = mutated(vec![0, 3, 2, 1], <[i32]>::sort);
    println!("{:?}", my_vec1); // [0, 1, 2, 3]
}
```

Now that I think of it, this function has limited use anyway, given how few few implementations of the form `T: AsMut<T>` there are, but the use case of using default parameters for suggesting a type boundary for intermediate values in a higher-order function should hold anyway.

**Comment by burrbull** [comment]
Any chance this restriction to be removed for functions?

**Comment by Starwort** [comment]
I'd also like this restriction to be lifted for functions, especially for trait functions. It would be much more ergonomic to have an API which allows default type parameters; For example, `Iterator::collect` could default to `Vec<T>`, while still allowing to be overridden by either type inference or an explicit turbofish; additionally `Iterator::sum` could be optimised for the common case where S = T (e.g. usize -> usize); other use-cases where an obvious default could be picked should be fairly common

**Comment by rambip** [comment]
It is especially usefull for optional functions:
```rust
fn foo<F: Fn() -> String>(bar:Option<F>){}

fn main(){
    foo(Some(|| String::new()));
    foo(None)
}
```

Here, I have to use turbofish syntax even if it is irrelevant

**Comment by gsteinLTU** [comment]
> For example, `Iterator::collect` could default to `Vec<T>`

I have to wonder how much time this would have saved people if it was like this from the start.

**Comment by rambip** [comment]
And in essence, this is just a hint for the compiler saying "instead of raising `type annotation needed for Foo`, just try to replace with some concrete type to see if that works"
Maybe it is a completely different feature and a new issue should be open (default type parameters can create a bunch of strange situations), but it would be very cool to have this feature.

**Comment by QuineDot** [comment]
Default type parameters on functions are not *completely* ignored.  Inference doesn't fallback to them just like default type parameters elsewhere, and there are less workarounds because you can't name the types of functions items.

[But this works, for example:](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a2615bf85394565d617c25b8f8b16552)
```rust
#[allow(invalid_type_param_default)]
fn partial_default<T, U: Default = String>() -> U {
    U::default()
}

fn main() {
    let x = partial_default::<()>();
    println!("{}", std::any::type_name_of_val(&x));
}
```
Because if you have one or more non-defaulted parameters, you can omit defaulted parameters in a turbofish, and (unlike when *all* parameters are elided / when there is no turbofish), the elided parameters will take on their default values instead of being inference variables.

This is required for things like `Vec<Element, Allocator>` to work as intended with the default allocator, but happens to work for functions and probably other things, as well.

**Comment by RalfJung** [comment]
FWIW I did a [crater run](https://crater-reports.s3.amazonaws.com/pr-127655/index.html) in https://github.com/rust-lang/rust/pull/127655 and there's still quite a few crates affected by this lint -- mostly because of `typemap`.

**Comment by tjpalmer** [comment]
> It is especially usefull for optional functions:
> 
> ```rust
> fn foo<F: Fn() -> String>(bar:Option<F>){}
> 
> fn main(){
>     foo(Some(|| String::new()));
>     foo(None)
> }
> ```
> 
> Here, I have to use turbofish syntax even if it is irrelevant
> 

Similar problem for things like `Option<impl ToString>`. Having to say something like `None::<String>` is sort of silly.

**Comment by EndilWayfare** [comment]
`euclid` is another example of a class of use-case in which this is useful for ergonomic/noise-reduction reasons.

The geometric primitives from this crate have an "optional" type parameter to specify unit of measure, but it's not _really_ optional. You don't have to make _active use of it_, but you do have to _mention it_ in your client code regardless.

```rust
use euclid::UnknownUnit;
// Equivalent to 
// `type Point2D<T> = euclid::Point<T, UnknownUnit>;`
use euclid::default::Point2D;

pub fn my_silly_point<U>() -> euclid::Point2D<i32, U> {
    Point2D::new(42, 21)
}

pub fn also_my_silly_point() -> Point2D<i32> {
    my_silly_point()
}

fn no_units_pls() {
    let leaky_implementation_details = my_silly_point::<UnknownUnit>();
    let strange_and_awkward = my_silly_point::<()>();

    let but_i_can = also_my_silly_point();
}

fn im_already_using_units() {
    struct ScreenSpace;

    let center = euclid::Point2D::<i32, ScreenSpace>::new(2560, 1440) / 2;

    let i_can = center - my_silly_point();

    let but_i_have_to = center - also_my_silly_point().cast_unit();
    let or_maybe_for_some_reason = center - euclid::Point2D::from_untyped(also_my_silly_point());
}
```

I don't know why `euclid` chooses to uses a type alias instead of a default type parameter, or even if this is even a deliberate design decision. But, if a crate author decides they don't like default type parameters and you _do_ like default type parameters, functions-with-default-type-parameters would let you have/emulate them without, e.g., a redundant wrapper struct.

**BEFORE-PUBLISH UPDATE:**
Ok, I'm glad I decided to write this, because in the course of making sure my examples compile I found out you CAN have default type parameters in type aliases. I didn't think those were allowed either. I was _probably_ mixing this up with the "trait bounds in type aliases don't actually do anything" issue.

My argument still stands, I think, but for other cases that I can't immediately produce a tortured artificial example of. So it's worth noting that you _can_ (and I will _now_) do the following:
```rust
use euclid::UnknownUnit;

type Point2D<T, U=UnknownUnit> = euclid::Point2D<T, U>;

fn i_have_the_power<U>() -> Point2D<f64, U> {
    Point2D::new(800., 600.)
}

let yuuuuus = i_have_the_power();
```

**Comment by RalfJung** [comment]
Yeah default type params in type aliases are common. AFAIK they do not cause any kind of inference fallback so they do not share the issues of what is being tracked here.

So for code that currently hits this future compat error, that seems like a good thing to migrate to.

**Comment by Houtamelo** [comment]
Based on the comments it is **very** clear that allow default type parameters in function signatures is **desirable**. Is there an RFC for this already? If not, I could open it.

**Comment by fmease** [comment]
I strongly recommend to read the following first: https://internals.rust-lang.org/t/interaction-of-user-defined-and-integral-fallbacks-with-inference/2496/2 (linked from https://github.com/rust-lang/rust/issues/2733).

Also CC https://github.com/rust-lang/rust/issues/98931#issuecomment-2385286755:

> In expression position, a lack of generic arguments leads to the compiler supplying *inference variables* for all generic parameters (I'm ignoring lifetime elision here). These inference variables don't know a lot about their origin starting out, most notably the fact that there could be "defaults" for them. They are disconnected from that notion, so naturally there's no way for the type checker to consider the defaults.

> And while we could almost trivially equip their origin (e.g. TypeVariableOrigin in the compiler) with a notion of defaults, the problem lies in the question of when *exactly* to apply said default during the inference process. This is why there has been no progress whatsoever on this feature.
