### ISSUE TITLE
Tracking issue for `lifetime_underscore` compatibility lint

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#36892]
#### What is this lint about

Lifetime name `'_` is reserved for possible future use as a lifetime placeholder, similarly to how `_` is used as a placeholder in types or patterns (see, for example, https://github.com/rust-lang/rfcs/pull/1177).
Earlier versions of the compiler accepted `'_` as a normal lifetime or label name, https://github.com/rust-lang/rust/pull/33794 fixed this oversight.
#### How to fix this warning/error

Rename the lifetime or label named `'_` into something else, like `'a` or `'z`.
#### Current status
- [x] https://github.com/rust-lang/rust/pull/33794 introduces the `lifetime_underscore` lint as warn-by-default
- [x] https://github.com/rust-lang/rust/pull/36894 makes the `lifetime_underscore` lint deny-by-default
- [ ] PR ? makes the `lifetime_underscore` lint a hard error
