### ISSUE TITLE
Tracking issue for the "ptx-kernel" ABI

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#38788]
Introduced in #38559.

Feature gate: `abi_ptx`

This ABI is used to generate ["global"] functions. All the other functions that *don't* use the "ptx-kernel" ABI are ["device"] functions.

["global"]: https://docs.nvidia.com/cuda/cuda-c-programming-guide/#global
["device"]: https://docs.nvidia.com/cuda/cuda-c-programming-guide/#device-function-qualifier

The host can only make the device, the GPU, execute global functions, not device functions. IOW, a PTX module that only contains device functions is basically unusable.

---

Note that this ABI *can't* be emulated using naked functions.

``` rust
#![feature(abi_ptx)]
#![feature(naked_functions)]
#![no_std]

#[naked]
#[no_mangle]
fn foo() {}

#[no_mangle]
fn bar() {}

#[no_mangle]
extern "ptx-kernel" fn baz() {}
```

Produces:

```
.version 3.2
.target sm_20
.address_size 64

.func foo()
{
        .local .align 8 .b8     __local_depot0[8];
        .reg .b64       %SP;
        .reg .b64       %SPL;

        mov.u64         %SPL, __local_depot0;
        bra.uni         LBB0_1;
LBB0_1:
        ret;
}

.func bar()
{
        .local .align 8 .b8     __local_depot1[8];
        .reg .b64       %SP;
        .reg .b64       %SPL;

        mov.u64         %SPL, __local_depot1;
        bra.uni         LBB1_1;
LBB1_1:
        ret;
}

.entry baz()
{
        .local .align 8 .b8     __local_depot2[8];
        .reg .b64       %SP;
        .reg .b64       %SPL;

        mov.u64         %SPL, __local_depot2;
        bra.uni         LBB2_1;
LBB2_1:
        ret;
}
```

Note that only `baz` uses the `.entry` directive.

**Comment by steveklabnik** [comment]
Triage: not aware of any movement on stabilizing this.

**Comment by lahwran** [comment]
would be very interested in this!

**Comment by kjetilkjeka** [comment]
I'm curious if I might have found a codegen bug related to this feature.

<details open>
<summary>When compiling the following with rustc</summary>

```rust
#![no_std]
#![feature(abi_ptx, stdsimd)]

#[panic_handler]
fn panic(info: &core::panic::PanicInfo) -> ! {
    unreachable!()
}

#[repr(C)]
pub struct Foo{
    array: [f32; 9],
}

#[no_mangle]
pub unsafe extern "ptx-kernel" fn add(a: *mut f32, b: Foo) {
    *a = b.array[5];
}
```
</details>
<details open>
<summary>Rustc will produce the following</summary>

When compiling with `rustc +nightly --target nvptx64-nvidia-cuda <filename> --crate-type cdylib`

```
//
// Generated by LLVM NVPTX Back-End
//

.version 3.2
.target sm_30
.address_size 64

	// .globl	add

.visible .entry add(
	.param .u64 add_param_0,
	.param .u64 add_param_1
)
{
	.reg .f32 	%f<2>;
	.reg .b64 	%rd<5>;

	ld.param.u64 	%rd1, [add_param_0];
	ld.param.u64 	%rd2, [add_param_1];
	cvta.to.global.u64 	%rd3, %rd2;
	cvta.to.global.u64 	%rd4, %rd1;
	ld.global.f32 	%f1, [%rd3+20];
	st.global.f32 	[%rd4], %f1;
	ret;

}
```
</details>


<details open>
<summary>On the other hand, when compiling the following with nvcc</summary>

```cuda
struct foo {
    float array[9];
};

extern "C" __global__ void add( float *a, struct foo b) {
    *a = b.array[5];
}
```

</details>
<details open>
<summary>I get the following output</summary>

When compiling with `nvcc -ptx <filename> `

```
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-30794723
// Cuda compilation tools, release 11.6, V11.6.55
// Based on NVVM 7.0.1
//

.version 7.6
.target sm_52
.address_size 64

	// .globl	add

.visible .entry add(
	.param .u64 add_param_0,
	.param .align 4 .b8 add_param_1[36]
)
{
	.reg .f32 	%f<2>;
	.reg .b64 	%rd<3>;


	ld.param.u64 	%rd1, [add_param_0];
	cvta.to.global.u64 	%rd2, %rd1;
	ld.param.f32 	%f1, [add_param_1+20];
	st.global.f32 	[%rd2], %f1;
	ret;

}


```
</details>

<details open>
<summary>Here's the different compiler versions I'm using</summary>

```
$ rustc +nightly --version
rustc 1.61.0-nightly (68369a041 2022-02-22)
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:16:03_PST_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0
```
</details>

I would be happy to try to figure out whats going on if anyone can confirm that this is a bug? If anyone would be able to point me in the right direction that would be a nice bonus as well.

**Comment by pnkfelix** [comment]
Visiting as part of a T-compiler backlog bonanza prepass.

This at very least is in a "needs summary" state. But based on @RDambrosio016 's [comment from 10 days ago](https://github.com/rust-lang/rust/pull/94703#issuecomment-1061177678), there may even be design concerns? (At least depending on what scope of potential parameter types we want this ABI to cover at the outset.)

@rustbot label: S-tracking-design-concerns S-tracking-needs-summary

**Comment by kjetilkjeka** [comment]
@pnkfelix I'm currently working on fixing bugs in ptx-kernel in #94703 and would like to help out providing a summary. I have also discovered some design concerns that I can contribute to the summary.

Do you have a template or example of how it should look like?

**Comment by kjetilkjeka** [comment]
Here's a suggestion for an update to the tracking issue to include concerns. Partially copied for japaric's original post and added concerns from and links to relevant issues.

If you have the possibility you should take a look @RDambrosio016 

- - - 

Feature gate `#![feature(abi_ptx)]`

This ABI is intended to be used when generating code for device (GPU) targets like `nvptx64-nvidia-cuda`. It is used to generate kernels (["global functions"](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#global)) that work as an entry point from host (cpu) code. Functions that do not use the "ptx-kernel" ABI are ["device functions"](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#device-function-qualifier) and only callable from kernels and device functions. Device functions are specifically not usable from host (cpu) code.

### Public API
The following code
```Rust
#![no_std]
#![feature(abi_ptx)]

#[no_mangle]
pub extern "ptx-kernel" fn foo() {}
```
Produces
```
.version 3.2
.target sm_30
.address_size 64

	// .globl	foo

.visible .entry foo()
{
	ret;
}
```
### Steps / History
 - [ ] Fix broken passing of kernel arguments (#94703)
 - [ ] Emit error for kernels with return value other than `()`
 - [ ] Resolve unresolved questions
 - [ ] Create an RFC that specifies the safe way to use this abi (I assume this will be required @pnkfelix?)
 - [ ] Document feature (https://doc.rust-lang.org/reference/items/external-blocks.html#abi)
 - [ ] Stabilization PR

### Unresolved Questions
 - [ ] Resolve what kind of stability guarantees can be made about the generated ptx.
     - The ABI of kernels have been previously changed for a major version bump and the [ptx-interoperability](https://docs.nvidia.com/cuda/ptx-writers-guide-to-interoperability/) doc is still outdated.
     - PTX is an ISA with many versions. The newest is major version 7. Do we need to reserve the possibility of breaking things when moving to a new major version?
     - Figure out what llvm does in relations to the `nvptx64-nvidia-cuda` target and the `__global__` modifier.
 - [ ] What kind of types should be allowed to use as arguments in kernels. Should it be a hard error to use these types or only a warning (https://github.com/rust-cuda/wg/issues/11)
     - The most important part is to find a minimal but useful subset of Rust types that can be used in kernels. raw pointers, primitive types and `#[repr(C)]` types seems like a good start (no slices, tuples, references, etc).
     - Using mutable references is almost certain UB except for a few unusable special cases (spawning a single thread only) 
     - There are many convenient types in Rust which do not have a stable ABI (`&[T]`, `(T, U)`, etc). Are there some types that do not have a stable representation but can be relied on having an identical representation for sequential compilation with a given rustc version? If so are there any way we could pass them safely between host and device code compiled with the same rustc version?
 - [ ] This unstable feature is one of the last stoppers to using `nvptx64-nvidia-cuda` on stable Rust. The target seems to still have a few bugs (#38789). Should this feature be kept unstable to avoid usage of `nvptx64-nvidia-cuda` until it has been verified to be usable.

### Notes
 - It is not possible to emulate kernels with `#[naked]` functions as the `.entry` directive needs to be emited for nvptx kernels.

**Comment by workingjubilee** [comment]
It seems likely that the way this ABI will work is going to be similar in its broad strokes between most GPU targets. Much like `extern "C"` varies on a per-target basis, it's not a crime to have an ABI string that works slightly differently on a platform-dependent basis. So, as there is some interest in Rust supporting multiple GPU targets, we should probably have just one [`extern "gpu-kernel"`](https://github.com/rust-lang/rust/pull/135047) ABI, and see how far we can get with it. That way we don't have to keep reimplementing the same features (argument and return type validation, not being callable from device functions, etc.) for every single platform.
