### ISSUE TITLE
Removal of the lang feature gate tests whitelist

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#39059]
PR #38914 has added a tidy check for gate tests in compile-fail for all unstable lang features, helping ensure that they are actually unstable. See also issue #22820.

To be recognized as gate test for a specific feature, tests either need to follow a naming scheme `feature-gate-NAME-OF-THE-FEAT.rs` or include a `// gate-test-NAME-OF-THE-FEAT` comment. For most of the currently present features, I could easily find matching tests in the test suite. Sadly, [there is still a whitelist](https://github.com/rust-lang/rust/blob/6fe23719feb20c25a8b2693d1f196e72d8da9af5/src/tools/tidy/src/features.rs#L168-L175) of currently 20 features for which it tolerates that it can't detect any gate tests.

The goal is to eliminate that whitelist, which this issue is tracking.

The features on the whitelist fall into the following categories:

**Has already tests, they just need to be marked (found this out only on a second look):**

* [x] `more_struct_aliases` → marked by PR #39243
* [x] `custom_attribute` → marked by PR #39243
* [x] `default_type_parameter_fallback` → marked by PR #39243
* [x] `use_extern_macros` → marked by PR #39243
* [x] `quote` → marked by PR #39250
* [x] `macro_reexport` → marked by PR #39250
* [x] `inclusive_range_syntax` → marked by PR #40031

**Used nowhere in the codebase. Remove?**

*got all removed by PR #39071*

* [x] `safe_suggestion`
* [x] `pushpop_unsafe`

**Needs a test (or I just haven't found a suiting test to mark, even on second look):**

* [x] `cfg_target_has_atomic` → got a test by #40150
* [x] `simd` → got a test by #40101
* [x] `abi_ptx`→ got a test by #40168
* [x] `const_indexing` → got a test by PR #39700
* [x] `stmt_expr_attributes` → got a test by PR #40252
* [ ] `unwind_attributes` → will get a test by PR #40279
* [x] `static_recursion` → got a test by PR #39834
* [ ] `cfg_target_thread_local` → will get a test by PR #40279
* [x] `unboxed_closures` → got a test by PR #40047
* [x] `staged_api` → got a test by PR #39772

**Don't know what to do with this one. Any ideas?**

* [x] `reflect` → removed by PR #39075

The "Needs a test" section is a good place for beginners to help out!

You basically need to:

0. if you haven't already, read `CONTRIBUTING.md` and `COMPILER_TESTS.md`
1. search in the `src/test/run-pass` suite for tests of that feature
2. copy one of those tests over to the compile-fail suite
3. rename it appropriately (`feature-gate-FEAT-NAME.rs`) and remove the `#![feature(...)]` line
4. remove the feature from the whitelist
5. test locally (`./x.py test src/tools/tidy` and `./x.py test src/test/compile-fail --test-args feature-gate-FEAT-NAME`)
5. submit a PR!

It would also be very good if you searched the `compile-fail` testsuite for already existing gate tests and mark those instead. A good place to look is the PR that introduced that feature, they usually also add gate tests.

You can help out in the "Has already tests" section as well. Here, contributing is even easier!

You'll need to:

0. read `CONTRIBUTING.md` and `COMPILER_TESTS.md` (second one is not strictly required, but it never harms :D)
1. add a line with `// gate-test-FEATURE_NAME` to the files that were mentioned above
2. remove the feature from the whitelist
3. test locally (`./x.py test src/tools/tidy`, since you only added comments)
4. submit a PR!

If you need help, ask in this thread. Also, its best to prevent duplicate work, so it would be nice if you could announce that you work on some of the items. Thanks in advance!

**Comment by brson** [comment]
Nice idea.

**Comment by alanhoff** [comment]
Hello folks, I'm just announcing that I'll try to do the `Need a test` section today

**Comment by cseale** [comment]
Guess I will do the already has tests section today!

**Comment by est31** [comment]
@alanhoff @cseale wonderful! Ping me if you need any help or when you open your PR.

**Comment by cseale** [comment]
@est31 for example, in `struct-path-self-feature-gate.rs` it's just as straight forward as 

```
// gate-test-more_struct_aliases
struct S;

trait Tr {
    type A;
}

fn f<T: Tr<A = S>>() {
    let _ = T::A {};
    //~^ ERROR `Self` and associated types in struct expressions and patterns are unstable
}

impl S {
    fn f() {
        let _ = Self {};
        //~^ ERROR `Self` and associated types in struct expressions and patterns are unstable
    }
}

fn main() {}
```

Where in the codebase is the build actually looking at these comments to detect if they should run or not? I'm used to annotations or functions declaring test groups in code (junit in java or jasmine in javascript). I am new to rust, is this a rust standard?

**Comment by cseale** [comment]
@est31 also I am receiving this error when I try to run `python x.py test src/test/compile-fail --test-args feature-gate-more_struct_aliases`

```Traceback (most recent call last):
  File "x.py", line 20, in <module>
    bootstrap.main()
  File "/Users/user/projects/rust/src/bootstrap/bootstrap.py", line 464, in main
    shutil.rmtree('.cargo')
  File "/Users/user/anaconda/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/Users/user/anaconda/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '.cargo/config'```

**Comment by cseale** [comment]
When I run the tidy check, everything run ok, but the following command produces an error: 

```
$ ./x.py test src/test/compile-fail --test-args feature-gate-more_struct_aliases

Finished debug [unoptimized] target(s) in 0.0 secs
Synchronizing submodule url for 'src/compiler-rt'
Synchronizing submodule url for 'src/jemalloc'
Synchronizing submodule url for 'src/liblibc'
Synchronizing submodule url for 'src/llvm'
Synchronizing submodule url for 'src/rt/hoedown'
Synchronizing submodule url for 'src/rust-installer'
HEAD is now at a8fc4c1 Merge pull request #28 from xen0n/preprocessor-firefighting
HEAD is now at e058ca6 Change how the default zone is found
HEAD is now at e49e9bb Auto merge of #478 - jackpot51:patch-1, r=alexcrichton
HEAD is now at ceb177e Merge pull request #60 from japaric/gh38406
HEAD is now at a3736a0 Merge pull request #6 from intelfx/patch-1
HEAD is now at 4f99485 Merge pull request #54 from brson/docdir
Building stage0 std artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/user/projects/rust/build/x86_64-apple-darwin/stage0-std/x86_64-apple-darwin/release/build/compiler_builtins-0511dd5445a3a209/out/libcompiler-rt.a(addtf3.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/user/projects/rust/build/x86_64-apple-darwin/stage0-std/x86_64-apple-darwin/release/build/compiler_builtins-0511dd5445a3a209/out/libcompiler-rt.a(divtf3.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/user/projects/rust/build/x86_64-apple-darwin/stage0-std/x86_64-apple-darwin/release/build/compiler_builtins-0511dd5445a3a209/out/libcompiler-rt.a(multf3.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/user/projects/rust/build/x86_64-apple-darwin/stage0-std/x86_64-apple-darwin/release/build/compiler_builtins-0511dd5445a3a209/out/libcompiler-rt.a(powitf2.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/user/projects/rust/build/x86_64-apple-darwin/stage0-std/x86_64-apple-darwin/release/build/compiler_builtins-0511dd5445a3a209/out/libcompiler-rt.a(subtf3.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/user/projects/rust/build/x86_64-apple-darwin/stage0-std/x86_64-apple-darwin/release/build/compiler_builtins-0511dd5445a3a209/out/libcompiler-rt.a(trampoline_setup.o) has no symbols
    Finished release [optimized] target(s) in 0.0 secs
Copying stage0 std from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage0 test artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
    Finished release [optimized] target(s) in 0.0 secs
Copying stage0 test from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage0 compiler artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
warning: ../rustllvm/RustWrapper.cpp:151:3: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
warning:   default:
warning:   ^
warning: ../rustllvm/RustWrapper.cpp:1235:3: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
warning:   default:
warning:   ^
warning: ../rustllvm/RustWrapper.cpp:1268:3: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
warning:   default:
warning:   ^
warning: ../rustllvm/RustWrapper.cpp:1282:3: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
warning:   default:
warning:   ^
warning: 4 warnings generated.
    Finished release [optimized] target(s) in 0.2 secs
Copying stage0 rustc from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Copying stage1 compiler (x86_64-apple-darwin)
thread 'main' panicked at 'failed to copy `/Users/user/projects/rust/build/x86_64-apple-darwin/stage0-sysroot/lib/rustlib/x86_64-apple-darwin/lib/libflate-89345601b107c0b9.dylib` to `/Users/user/projects/rust/build/x86_64-apple-darwin/stage1/lib/libflate-89345601b107c0b9.dylib`: Permission denied (os error 13)', src/bootstrap/util.rs:53
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by est31** [comment]
@cseale 

> Where in the codebase is the build actually looking at these comments to detect if they should run or not? I am new to rust, is this a rust standard?

No, this notation is actually internal to the rust compiler codebase. Its not used in normal rust codebases. The standard way of doing tests in rust is to [use an attribute](https://doc.rust-lang.org/book/testing.html#the-test-attribute). The compiler however has special needs, and part of the information usually passed via attributes (like whether it should panic or not) is encoded in the path (run-pass vs compile-fail etc.) the test is inside. Also, the checking is done in an executable separate from the compiler, which doesn't have access to the parser. Doing it via comments makes this check simpler to implement. The specific check is implemented here: https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/features.rs#L118-L164

About your errors: don't know what the problem is. Did you do a clean clone? Running `./x.py test` should not be very important for work in the "already has tests" section though, so if the tidy check is successful, you can open a PR :)

**Comment by cseale** [comment]
@est31 I think it's something to do with the `sudo make install`. I ran the build from source script when I first cloned rust, but I think it is causing issues when I try and run other build commands? How do I uninstall rust?

**Comment by est31** [comment]
@cseale I'm not sure, maybe there is a script at `/usr/local/lib/rustlib/uninstall.sh`? In theory it should not interfere though. Maybe try to remove the `build/stage*` directories?

**Comment by est31** [comment]
Okay, found two further gate tests, so I moved "quote" and "macro_reexport" to the section of features that need only marking. Note that their marking won't be effective until #39247 gets merged.

**Comment by cseale** [comment]
@alanhoff any progress on the tests? Need some help?

**Comment by est31** [comment]
@alanhoff any questions? Or do you want more time? Still interested to work on the tests?

**Comment by cseale** [comment]
@est31 I'd happily give the tests a go if we were satisfied that an extra hand might be needed. Can start bottom up to give @alanhoff a chance to respond and minimise the chance of overlapping work

**Comment by alanhoff** [comment]
Hello folks. @est31 and @cseale can you guys take over my task? I actually forgot about it and won't have time to finish it this weekend -- I'm sorry if I caused any trouble.

**Comment by msopena** [comment]
Hi,
   this is my first attempt to contribute to Rust. Never used Github before, so bear with me. Let me know if something doesn't make sense.

**Comment by danobi** [comment]
Correct me if I'm wrong, but I believe `cfg_target_thread_local` is already tested in `../compile-fail/gated-thread-local.rs` via the `// gate-test-thread_local` header command.

**Comment by est31** [comment]
@danobi no, the `cfg_target_thread_local` feature is distinct from `thread_local`. They both share tracking issue #29594, but are about distinct things. `thread_local` is about the `#[thread_local]` attribute, while `cfg_target_thread_local` is about the `target_thread_local` cfg feature. In `src/test/run-pass/auxiliary/thread-local-extern-static.rs` you can see how both of the features are tested. It should be easy to make that only checks for `target_thread_local`. If you need any help, just ask!

**Comment by topecongiro** [comment]
Hello. I am working on adding compile fail test for `cfg_target_has_atomic`(PR #40150) and `abi_ptx`(will create PR after #40150 got merged).

**Comment by topecongiro** [comment]
Is ` stmt_expr_attributes` still unstable? `src/rust/run-pass/cfg_stmt_expr.rs` compiles without an error after removing `#![feature(stmt_expr_attributes)]`.

**Comment by est31** [comment]
@topecongiro I think its partly stable, partly not. See this comment: https://github.com/rust-lang/rust/issues/15701#issuecomment-271953516

Relevant for us is the status in `src/libsyntax/feature_gate.rs` and that says its still unstable. About that test file, I think the `#![feature(...)]` should be removed from it (and all other test files that still compile with `#![feature(...)]` included). There are other files that have `stmt_expr_attributes`, maybe one of them will fail to compile?

**Comment by topecongiro** [comment]
@est31 There are three files that have `stmt_expr_attribues` under `src/test/run-pass`, but all of them compile successfully without `#![feature(...)]`.

Maybe a test file like the following is required to test `stmt_expr_attributes` on expression?
```rust
#![feature(stmt_expr_attributes)]
fn main() {
    let x = #[allow(dead_code)] 8;
}
```

**Comment by est31** [comment]
> Maybe a test file like the following is required to test stmt_expr_attributes on expression?

Does it fail when you remove the `#![feature(...)]`? Then it can be used as gate test. If it doesn't fail then its probably a bug of the code that checks the attributes.

**Comment by topecongiro** [comment]
It does fail after removing the `#![feature(...)]`. I will create a PR for this.

**Comment by gibfahn** [comment]
I'll take `unwind_attributes`, never contributed to rust before but I think this is right: https://github.com/rust-lang/rust/pull/40279
