### ISSUE TITLE
Tracking issue for RFC 1828: Rust Bookshelf

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#39588]
RFC PR: https://github.com/rust-lang/rfcs/pull/1828

Checklist:

## infra

- [x] Create a landing page for the bookshelf. https://github.com/rust-lang/rust/pull/39593

## porting

- [x] Pull mdbook into tree and port the nomicon and book to it https://github.com/rust-lang/rust/pull/39633
    - [x] enable linkchecker for the books https://github.com/rust-lang/rust/pull/39976 (prereq: https://github.com/rust-lang/rust/pull/39966)
- [x] Port the reference to mdbook https://github.com/rust-lang/rust/pull/39855
- [x] Create a new "Nightly Book" in-tree. https://github.com/rust-lang/rust/pull/39866

## extracting

I think this all looks similar to https://github.com/rust-lang/rust/pull/39917

- [x] Pull the book out of tree into rust-lang/book https://github.com/rust-lang/rust/pull/40332
- [x] Pull the nomicon out of tree https://github.com/rust-lang/rust/pull/40222
- [x] Pull the reference out of tree https://github.com/rust-lang/rust/pull/40213
- [x] Pull the cargo docs out of tree and convert them to mdBook. https://github.com/rust-lang/cargo/issues/4040
- [ ] Publish cargo book as part of Rust. https://github.com/rust-lang/rust/issues/44910

**Comment by steveklabnik** [comment]
@brson @alexcrichton can we coordinate soon on getting this implemented? We had talked very broadly about it before, now it's time to get concrete 😄

**Comment by tshepang** [comment]
@steveklabnik Will 2nd edition be moved elsewhere when 1st edition moves to rust-lang/book?

**Comment by steveklabnik** [comment]
@tshepang the idea is that they will both be in the same repository. The exact strategy isn't totally clear; we'll see as we dig into packaging implementation details.

**Comment by vossad01** [comment]
I made some comments on #36094 regarding the old and new book.  I have tried to familiarize myself with this issue since if has a little different focus but is the successor of that issue.

In doing so I have two comments unrelated to old vs new books discussion:
 * For the 3rd party documentation resources that you want to display on the bookshelf but are not core/official, there are still advantages to getting them transfered under a common GitHub organization where possible.  I am not saying that should be done in any way to minimize the control or credit of the original author and hope it would never be utilized in that way.  However, being under a common organization makes for a less disruptive process if something unfortunate and unforeseen happens (health, accident, etc.) because new maintainers would not need to fork the project to a new URL to continue work.
 * Please be mindful when presenting the "Nightly Book" on the documentation page and/or make it clear on the landing page of the Nightly Book what the book is.  As I read this documentation, the "Nightly Book" will only contain information on new features/changes; however, my first thought on seeing the name is that it would be the latest documentation built from nightly.  Not a huge deal, but a potential issue that is easily mitigated by context.  This may have happened automatically without me mentioning it.

**Comment by vossad01** [comment]
The latest definitive comment on what is to happen with the old book and the new book appears to be by @steveklabnik:

> I think my inclination is to let both of them stay visible, and while not doing any work on the first edition, accept PRs for minor things like that. I'm open to suggestions, though.
> https://github.com/rust-lang/rfcs/pull/1828#issuecomment-269129447

The main question I have regarding that approach is, "How are the two books differentiated from each other?"  Case-in-point, there is already inconsistency in how they are referenced, old/new and first/second edition.  Perhaps another way to make the distinction is, "If you could not use "Edition" or any variant of versioning, how would you title the "old" and "new" book?"

If there is some clear grounds that differentiate them (different learning approaches, style, brevity, etc.), they might both be have sustained usefulness.  If, however, the distinction is between old and new version of essentially the same thing, then there would seem to be little to be gained in maintenance or continuance of the older version.

**Comment by steveklabnik** [comment]
> Perhaps another way to make the distinction is, "If you could not use "Edition" or any variant of versioning, how would you title the "old" and "new" book?"

Officially, it's a second edition of the book. Even though it's a substantial re-write, conceptually, it's the same work. 

However, given that it's a re-write, and with @carols10cents' help, it is very different. The biggest thing is that it's still not done yet, so the current plan is to have `doc.rust-lang.org/book` show "Hey here's the two editions," explain the difference, and link to a `/v1` and `/v2` (or some similar URL structure.)

**Comment by vossad01** [comment]
@steveklabnik thanks for the reply!  Are do you envision that situation changing at all once the second edition is complete?

**Comment by SimonSapin** [comment]
Table of content granularity regression: #40087

**Comment by ollie27** [comment]
Regression in playground "Run" buttons: #40271

**Comment by carols10cents** [comment]
Playground run buttons are actually https://github.com/azerupi/mdBook/issues/29.

**Comment by steveklabnik** [comment]
Docs team triage: p-medium. https://github.com/rust-lang/rust/pull/40332 and cargo work outstanding.

**Comment by behnam** [comment]
A kind of unrelated question here: is there a way to see the <https://doc.rust-lang.org/> website for `beta` and `nightly` channel? Maybe on a different domain?

I'm asking to understand how I can actually see the changes when working on migrating Cargo docs to the Bookshelf. (<https://github.com/rust-lang/cargo/issues/4040>)

**Comment by QuietMisdreavus** [comment]
@behnam All the releases and release channels have subfolders on doc.rust-lang.org. So nightly is on https://doc.rust-lang.org/nightly/ and beta is on https://doc.rust-lang.org/beta/. Whenever you link the cargo docs in with the rest of the rust docs, the full doc bundle is made when you run an `./x.py doc` on the rust repo, and placed in `build/$TARGET/doc`.

**Comment by behnam** [comment]
Thanks, @QuietMisdreavus, for the info. So now I know how to test the full docs build locally.

**Comment by behnam** [comment]
# Update on Cargo docs

We are done with preparing the Cargo docs in book format, which was <https://github.com/rust-lang/cargo/issues/4040>

I have filed <https://github.com/rust-lang/rust/issues/44910> for the next steps. We can add this to the list in the description here.
