### ISSUE TITLE
Proposal: stop using bors/homu

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#40077]
# The ugly

Everyone knows the problem:
![image](https://cloud.githubusercontent.com/assets/12389383/23305238/1fcb17a2-fae1-11e6-8d99-66f485565a79.png)
**BOOM**.

We're having more and more jamming builds, while Travis has much more capacity to handle them.

The problem with bors:
* Builds are aggressively canceled.  
It's not a good idea, since it simply discards things it built before. There's definitely many spurious build failure like network, or OSX linker issues.  
The solution is so simple: we simply retry the one that failed.  
* Builds are only performed when the PR comes to top of the queue.  
We don't want to found our code was wrong after 3 days!  
(By the way, the workflow is frequently interrupted by merge conflicts, too)
* Too simple review flow.  
GitHub has a richer UI for this.

# Solution

Travis tests the PR with a merge. What's more, Travis has almost infinite capacity.

![image](https://cloud.githubusercontent.com/assets/12389383/23305498/715c6002-fae2-11e6-8756-57cf5c0755a3.png)

`wow so simple and beautiful`

![image](https://cloud.githubusercontent.com/assets/12389383/23305215/081632f4-fae1-11e6-8e03-b9d1c56d0436.png)

# Todo

* [ ] buildbot should be configured to pull the refs/pull/id/merge ref (merge simulation ref)
* [ ] buildbot should be configured to post GitHub status
* [ ] automatic merge on all status passing

**Comment by ishitatsuyuki** [comment]
Some additional things based on comments on IRC:
* This reduces build repetition, so we can build one target instead of everything on spurious failure.
* macOS builds have a big backlog, but this solution is likely to reduce the overall build numbers.
* Needs some way to control priorities.

**Comment by nox** [comment]
This solution will add as many macOS builds as there are open PRs times 5, so I'm dubious about your second bullet.

**Comment by frewsxcv** [comment]
So would every pull request get triggered to rebuild when anything merges to master?

If so: How is this an improvement?

If not: How would PRs get tested with the latest commits on master?

**Comment by frewsxcv** [comment]
Also, things aren't landing right now mostly because of network issues and builds timing out on Travis CI. Does your solution address these issues?

**Comment by steveklabnik** [comment]
This kind of discussion/proposal topic is better served through http://internals.rust-lang.org/, could you make a post there, please? Thanks!
