### ISSUE TITLE
Metaissue for Visual Studio debugging Rust

### ISSUE THREAD

**Issue by jntrnr** [rust-lang/rust#40460]
Recently, I started playing with the new VS 2017 Community edition.  Specifically, I wanted to see if Rust debugging works with VS.  Good news: out of the box, you can attach to running Rust applications compiled in debug mode, pause them, and begin debugging.

The experience isn't perfect, and I hope to grow this issue to include the places where the experience can be improved.

* [x] u8/i8 are not shown in debugger (https://github.com/rust-lang/rust/issues/36646)
* [ ] std lib needs visualisers for std structs like String, Vec etc.  [WIP effort](https://github.com/jonathandturner/rust_natvis) (though #39843 looks better)
* [ ] &str isn't understood by VS (can't natvis)
* [ ] watches for shadowed variables confuse VS

**Comment by Boddlnagg** [comment]
There was some previous work trying to use natvis: https://github.com/rust-lang/rust/issues/36503

**Comment by jonathandturner** [comment]
@Boddlnagg - I noticed that only works if you have patched s8 support?  I tried just copying/pasting your example with out and wasn't able to get it to work.

I also noticed that https://github.com/rust-lang/rust/pull/39843 is related to the natvis work.

**Comment by Boddlnagg** [comment]
@jonathandturner I did not patch s8 support (I don't even know what you mean by that) ... but I had to manually work around https://github.com/rust-lang/rust/issues/36646 by patching the type information in the PDB.

I'd also like to point out that https://github.com/rust-lang/rust/issues/36503#issuecomment-250405902 explains the ability to embed natvis files into PDBs (maybe `rustc` could do that automatically at some point).

**Comment by codec-abc** [comment]
If possible I think that conditional breakpoints would be a nice addition.

**Comment by mzji** [comment]
rustc/cargo don't copy the .pdb file to the directory of the executable automatically anymore, is that a decision/design of rustc/cargo? IIRC rustc 1.13 will copy the .pdb file.

**Comment by retep998** [comment]
@mzji The `.exe` or `.dll` has the absolute path to the `.pdb` hardcoded so the debugger can still find the `.pdb` even if you moved the `.exe` or `.dll`.

**Comment by mzji** [comment]
@retep998 So if the debugger failed to load the .pdb files automatically, that means there is a bug in the debugger?

**Comment by lnicola** [comment]
@mzji I think VS loads the PDB, but in VS Code I had to change the launch configuration to run the executable from the `deps` folder (with the PDB next to it). I would have expected WinDbg to behave just like VS does, though.

**Comment by mzji** [comment]
@lnicola Then I think we should at least leave a copy in the directory of binaries, since different debuggers have different behavior (VS will find and load pdb files automatically, Ollydbg/x64dbg and all debuggers only using `DBGHELP` won't).

**Comment by codec-abc** [comment]
Back to the original issues, the most 2 annoying things that happen when I try to debug Servo is that:

- Breakpoints are hit multiple times per line in some cases.
- Enums values are not understood in the "local" inspector. This is annoying since most Rust code use heavily Option and Result.

**Comment by jonathandturner** [comment]
@codec-abc - by chance, have you tried using the natvis from this PR to see if it helps with your second bullet point?  https://github.com/rust-lang/rust/pull/39843

I've been chatting with the author and would like to potentially make it part of the pdb at some point.

**Comment by codec-abc** [comment]
I used the one in the [opening message of the issue](https://github.com/jonathandturner/rust_natvis). So there are probably different.

**Comment by jonathandturner** [comment]
@codec-abc - yeah, the one in the PR is much better than mine, with support for more common Rust std lib structures.

**Comment by MaulingMonkey** [comment]
- Fixes for u8/i8 have landed in nightly.
- Some stdlib visualizers have landed in stable.
- I have a hacky changelist I'm working on to enable visualization of &str and array slices (via renaming debug info), and to auto-embed .natvis files into the resulting pdbs for maximum convenience.

**Comment by abonander** [comment]
@MaulingMonkey's PR brought visualization quite a long way but there's still a few shortcomings in the debugging experience as of the latest nightly:

* Mutable slices need a separate visualizer entry, as their type name is `mut slice<*>`; I was able to fix this just by duplicating the visualizer entry for `slice` in `intrinsic.natvis`:

```xml
 <Type Name="slice&lt;*&gt;">
    <DisplayString>{{ length={length} }}</DisplayString>
    <Expand>
      <Item Name="[size]" ExcludeView="simple">length</Item>
      <ArrayItems>
        <Size>length</Size>
        <ValuePointer>data_ptr</ValuePointer>
      </ArrayItems>
    </Expand>
    </Type>
    <!-- added -->
    <Type Name="mut slice&lt;*&gt;">
    <DisplayString>{{ length={length} }}</DisplayString>
    <Expand>
      <Item Name="[size]" ExcludeView="simple">length</Item>
      <ArrayItems>
        <Size>length</Size>
        <ValuePointer>data_ptr</ValuePointer>
      </ArrayItems>
    </Expand>
  </Type>
```

* Slice visualization works fine in the same stack frame that the slice is created but breaks down when the slice is passed to a function call:

| Source frame | Top frame |
| ---------------|-------------|
| ![image](https://user-images.githubusercontent.com/3198595/59411097-5ba5f580-8d6f-11e9-8693-4c54b84a1c51.png) | ![image](https://user-images.githubusercontent.com/3198595/59411020-32856500-8d6f-11e9-9d41-5ff4d8910f21.png) |

* Also,  you look closely in the screenshot above you can see that the `fn main()` stack frame is shown at the wrong source line.

**Comment by rylev** [comment]
There has been progress on this issue from several fronts lately:
* https://github.com/rust-lang/rust/pull/79184
* https://github.com/rust-lang/rust/pull/80311
* https://github.com/rust-lang/rust/pull/81898
* https://github.com/rust-lang/rust/pull/82557

Some additional todos/issues:
* Arrays cannot provide custom DisplayStrings
* Option<T> where the option can take advantage of the None == 0 niche not showing in WinDbg
* No debug info for `char` locals
