### ISSUE TITLE
Tracking issue for RFC 1866: More readable assert_eq

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#41615]
This is a tracking issue for the RFC "More readable assert_eq" (rust-lang/rfcs#1866).

**Steps:**

- [x] Implement the RFC (#42541)
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- Should we also cover `assert_ne`?
- Should we incorporate color support, or use LLVM-style arrows?

**Comment by colin-kiegel** [comment]
* IMO `assert_ne` should also print multi-lines, but not show a diff
* Color support in the built-in `assert_eq!` would be awesome. :-)

small side-note: In case anyone wants to use this before it is stabilized, I just implemented multiline display in [`pretty_assertions (v0.2)`](https://docs.rs/pretty_assertions/0.2.0/) and it currently looks like this:

![pretty assertion](https://github.com/colin-kiegel/rust-pretty-assertions/raw/master/examples/pretty_assertion.png)

**Comment by golddranks** [comment]
Btw. red and green aren't maybe the best choices for colour coding, as the red-green colour blindness is the most common type of vision deficiency out there. (The coloured pieces would still stand out from the normal text if I understand red-green-colour blindness correctly, but not from each others.)

**Comment by colin-kiegel** [comment]
`git diff --word-diff` does the following by default
```diff
The quick brown [-duck-]{+fox+} jumps over the lazy dog
```

Where `[-duck-]` and `{+fox+}` are colored red/green if the terminal supports it. This is also readable without color support (or color blindness). However this might be ambiguous if the underlying text already contains such character sequences.

**Comment by ordovicia** [comment]
Is this tracking issue supposed to be closed?

**Comment by kennytm** [comment]
Thanks @ordovicia. 

I've reopened the issue since there is still two unresolved questions (color and arrow). 

However AFAIK there can be no "Stabilization PR", the change is insta-stable. For "Adjust documentation", perhaps check the books if the output format needs to be updated, but otherwise no specific documentation is needed for this feature.

**Comment by jonas-schievink** [comment]
> Implement the RFC (#42541)

That does not look like the complete implementation. If it is, then this issue can probably be closed since this has been the stable output since over 2 years now.

**Comment by jonas-schievink** [comment]
I just re-read the RFC and this is indeed fully implemented. I do not think there's anything left to document/stabilize, and there's also https://github.com/rust-lang/rust/issues/44838 tracking further improvements to assertion error messages, so closing.
