### ISSUE TITLE
Tracking issue for RFC#1685: Deprecate anonymous parameters 

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#41686]
This is a tracking issue for the RFC "Deprecate anonymous parameters " (rust-lang/rfcs#1685).

**Steps:**

- [x] Implement the RFC (cc @rust-lang/compiler -- can anyone write up mentoring instructions?)
- [x] Adjust documentation ([see instructions on forge][doc-guide])

[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- [x] The precise deprecation strategy

**Comment by est31** [comment]
I could work on this. From reading the RFC discussion, I think the "soft" deprecation strategy has been chosen? So on the compiler side, we'll need an allow by default (deprecation) lint for anonymous parameters, right?

**Comment by aturon** [comment]
@est31 Awesome! And yes, that's correct. This will be most effective if we add the lint to Clippy as well.

(The open question is around the criteria for moving to a warn-by-default strategy in the future.)

**Comment by est31** [comment]
About the clippy lint, I'll leave that to someone else. Given #41692, it should be mostly copy paste, but maybe with official rust claiming the lint name one has to chose another one. No idea.

**Comment by matklad** [comment]
IJ inspection: https://github.com/intellij-rust/intellij-rust/pull/1211

I'll try to add an automatic fix to `rustfmt` as well. Not sure it's a great idea, but I want to try :)

**Comment by mark-i-m** [comment]
It doesn't appear that this is linting: https://play.rust-lang.org/?gist=b818c6024acb95add60b339e7708d132&version=nightly

Also, we might want to try to finish this for the 2018 epoch, so we should start linting _now_

**Comment by mark-i-m** [comment]
Oh, duh 🤦‍

It's an allow by default lint.

**Comment by mark-i-m** [comment]
Sorry for the multiple rapid posts.

After having read a bit more of the discussion that I can find, I propose a more aggressive deprecation strategy:
- We make the lint warn-by-default as soon as possible
- We make anon parameters a hard error at the epoch boundary

cc @matklad @est31 @aturon

**Comment by SimonSapin** [comment]
Should this also apply to `fn(Foo)` function pointer types?

**Comment by matklad** [comment]
@SimonSapin I would say no, because the situation for function pointers is just the opposite: nontrivial patterns are forbidden:

```
error[E0561]: patterns aren't allowed in function pointer types
 --> main.rs:1:13
  |
1 | type F = fn(&x: &i32);
  |             ^^
 
```

**Comment by mark-i-m** [comment]
Also, I think the original RFC doesn't mention fn pointers...

**Comment by petrochenkov** [comment]
@SimonSapin 
The problem solved by this RFC is unique to trait methods - they may have or not have body, so they may need or not need the full power of patterns in parameters (and full pattern support is incompatible with anonymous parameters).
Function pointers never have body, so they never need non-trivial patterns, so they can freely use anonymous parameters as well.

**Comment by vi** [comment]
Shall it be addressed before Rust 2018?

Maybe there should be a Github label like "rust-2018-checklist"?

**Comment by mark-i-m** [comment]
Do the current plan is to make this warn by default starting at the edition and deprecate it in a later edition. (See https://github.com/rust-lang/rust/issues/48309)

**Comment by Centril** [comment]
In RFC 2522, [I argue](https://github.com/Centril/rfcs/blob/rfc/generalized-type-ascription/text/0000-generalized-type-ascription.md#rfc-1685-and-deprecation-schedule) that to support the cases in that RFC we should expedite the schedule of RFC 1685
such that writing `trait Foo { fn bar(MyType) { ... } }` becomes a warning in Rust 2015 and a hard error in Rust 2018.

cc @nrc @nikomatsakis

**Comment by nikomatsakis** [comment]
@mark-i-m would you be up for prep'ing a PR to make that change? I think that was what you originally wanted to do. As long as there is a migration lint, it seems fine -- that is, as long as we can automatically migrate 2015 code.

**Comment by mark-i-m** [comment]
Sure, opened #53272.

It just changes the lint from being "warn in 2018" to "warn now" and adds a migration suggestion. Question: do we want to backport it to 1.29? Otherwise it will start warning just a month before the edition release.

**Comment by Centril** [comment]
@rfcbot merge

I propose that we adopt the deprecation strategy of warning in Rust 2015 and making this a hard error in Rust 2018 per my note over at https://github.com/rust-lang/rust/issues/41686#issuecomment-411966709.

**Comment by mark-i-m** [comment]
The OP mentions some adjusting of documentation. Does anyone know specifically which documentation needs to be adjusted?

**Comment by cramertj** [comment]
@mark-i-m [The forge has a section on updating documentation](https://forge.rust-lang.org/stabilization-guide.html#updating-documentation), but I don't think there's much to do here for deprecations other than to make sure that the book / reference / RBE aren't using the feature.

**Comment by Centril** [comment]
@cramertj @mark-i-m We should probably note this in the [edition guide](https://github.com/rust-lang-nursery/edition-guide) as well.

**Comment by Centril** [comment]
Triage: We still need to update the documentation.
ping @mark-i-m

**Comment by mark-i-m** [comment]
Sorry for the delay. I have been a bit swamped lately and mostly keeping up from my phone, so not much opportunity to write PRs :stuck_out_tongue:.

Reference: https://github.com/rust-lang-nursery/reference/pull/420
Edition Guide: https://github.com/rust-lang-nursery/edition-guide/pull/105

I did a brief search through the nomicon, book, RBE sections on traits and didn't see any other anon params, but please let me know if I missed one.

**Comment by steveklabnik** [comment]
Docs have all been merged. This is good to go.

**Comment by Centril** [comment]
Before we close the tracking issue; we still need to update the reference with notes about the actual edition-breaking change.

**Comment by mark-i-m** [comment]
@Centril @steveklabnik I opened https://github.com/rust-lang-nursery/reference/pull/421

Does this look like what you were thinking of?

**Comment by Centril** [comment]
@mark-i-m I was thinking of specifying somewhat more formally (BNF, etc.) but this is good in the interim :)

**Comment by mark-i-m** [comment]
@Centril I didn't realize there was a BNF spec of rust anywhere. Could you point me to it so I can update it?

**Comment by Centril** [comment]
@mark-i-m I don't think there is a BNF spec of Rust anywhere that covers all of Rust and is up to date;

However, we do specify some parts of the language in BNF; for example: https://doc.rust-lang.org/reference/expressions/literal-expr.html.

I think the most up-to-date specification is in [parser-lalr.y](https://github.com/rust-lang/rust/blob/master/src/grammar/parser-lalr.y) but it isn't fully updated either.

We don't need to spec it in BNF right now; but as a long term goal it would be good to do so.

**Comment by mark-i-m** [comment]
@Centril Perhaps we can spin that off into its own specific issue?

Currently, I think the last piece of documentation that is mandatory for this issue would be https://github.com/rust-lang-nursery/reference/pull/421. Right?

**Comment by Centril** [comment]
@mark-i-m nah; no issue needed; we should define a canonical grammar for Rust at some point, [hopefully soon](https://internals.rust-lang.org/t/proposal-grammar-working-group/8442/26).

Once the reference PR lands we can close this issue.

**Comment by Centril** [comment]
The reference PR has been merged, so I am closing this.
