### ISSUE TITLE
Tracking issue for struct_field_attributes

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#41681]
### Status

- [x] Implemented in  #38814: enable attributes and cfg on struct fields.
- [x] [Decided to stabilize](https://github.com/rust-lang/rust/issues/41681#issuecomment-303257198)
- [ ] Documentation PR(s) needed (see the "Updated documentation" section of [the stabilization guide](https://forge.rust-lang.org/stabilization-guide.html) for advice).
- [x] Stabilization PR needed (see the [stabilization guide](https://forge.rust-lang.org/stabilization-guide.html))

**Comment by SergioBenitez** [comment]
This has been around for a while (since Jan. 2017, ~4 months) and appears to be quite solid in my testing. Is there a reason to not move this into FCP for stabilization? @brson

**Comment by brson** [comment]
cc @rust-lang/lang Ready for stabilization?

**Comment by withoutboats** [comment]
@rfcbot fcp merge

**Comment by nikomatsakis** [comment]
Now that we've decided to stabilize this, we need someone to prepare a stabilization PR! There are some [general instructions for how to do this on forge](https://forge.rust-lang.org/stabilization-guide.html). Based on a quick run of `rg struct_field_attributes`, this should be a pretty straight-forward case! Just have to remove some of the feature-gate tests from `libsyntax` and a few other places. 

The other major thing we need before we can stabilize is documentation PRs.

**Comment by nikomatsakis** [comment]
Marking as E-mentor. The [instructions are here](https://github.com/rust-lang/rust/issues/41681#issuecomment-308171444).

**Comment by VBChunguk** [comment]
I want to work on removing the feature gate.

**Comment by nikomatsakis** [comment]
@VBChunguk nice job :)

**Comment by est31** [comment]
This might have removed one kind of inconsistence, and added another one. This doesn't work:

```rust
    struct S(u8,u8,u8);
    let _ = S { 0, 1, 2 };
```

**Comment by nikomatsakis** [comment]
Did we actually write stable documentation here? Skimming the threads I didn't see any PRs...?

**Comment by theduke** [comment]
This was stabilized with 1.20 as far as I can tell?

**Comment by cramertj** [comment]
Stabilized-- closing. LMK if there are any outstanding items here and I'll reopen.
