### ISSUE TITLE
Tracking issue for "Red/Green" Dependency Tracking

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#42293]
"Red/Green dependency tracking" is what we call the improved tracking algorithm for incremental compilation. The main difference to the algorithm used at the moment is improved accuracy because it can recover from "false positives", that is, it can stop cache invalidation short if a potentially changed value turns out to not have changed after all. A (work-in-progress) description of the system can be found at https://github.com/nikomatsakis/rustc-on-demand-incremental-design-doc/blob/master/0000-rustc-on-demand-and-incremental.md. Implementing this new tracking and caching system will happen in a few phases:

## Phase 1 - Red/Green without additional caching

In the first phase the core infrastructure for red/green tracking will be implemented. We do not cache any additional intermediate results but at the end of this phase, we will already have reached peak tracking accuracy. 

- [x] Implement direct metadata hashing as a proof of concept for general result hashing (#38114)
- [x] Remove `DepTrackingMap::write()` (#42192)
- [x] Refactor `DepNode` to use a stable hash that does not need "re-tracing" (#42294)
- [x] Clarify how checking for query cycles fits into the red/green algorithm (#42633)
- [x] Remove all occurrences of DepNode re-opening (#42298)
- [x] Fingerprint all query results (#44364)
- [x] Switch to new, append-only dependency graph implementation (#44772)
- [x] Make Metadata fingerprints available in DepGraph (#44772)
- [x] Implementing minimal `CachingPolicy` support for queries and use for CGUs
- [x] Implement red/green marking in `ty::queries::{}::try_get()`
- [x] Transition the testing framework to work properly again (#44716)

## Phase 2 - Caching `ty::TypeckTables`

In the second phase, support for caching `ty::TypeckTables` will be added, which allows the compiler to skip type checking.

- [x] Add infrastructure for caching and loading query results (#46004)
- [x] Move all uses of `NodeId` referenced by `ty::TypeckTables` over to `HirId` (#40303)
- [x] Refactor error messages, warnings, and lints to be cacheable (#41184)
- [x] Store and load `ty::TypeckTables` (#46004)

## Phase 3 - Caching MIR 

The third phase will support for caching MIR, which should be straight forward at that point. It remains to be verified though if it actually is a performance gain to do so.

- [x] Use new infrastructure to load and store optimized MIR (https://github.com/rust-lang/rust/pull/46556)
- [x] Verify that this even makes sense

cc @nikomatsakis, @eddyb, and @rust-lang/compiler in general

**Comment by michaelwoerister** [comment]
🎉 🎉 🎉 🎉 🎉

**Comment by matklad** [comment]
@michaelwoerister could you add a link to https://rust-lang-nursery.github.io/rustc-guide/query.html to the original description? This is what comes up in the search for rust red-green, so it's nice to have links to state-of-the-art docs.
