### ISSUE TITLE
Ship "the rustdoc book"

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#42322]
Located here: https://github.com/rust-lang/rust/tree/master/src/doc/rustdoc/src

This book documents Rustdoc and all its options. To do:

- [x] Write the [doc tests chapter](https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/documentation-tests.md)
- [x] Write the [in-source directives chapter](https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/in-source-directives.md)
- [ ] Write the [passes chapter](https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/passes.md)
- [x] Write the [plugins chapter](https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/plugins.md)
- [x] Create an "environment variables" chapter
- [ ] write rustbuild integration to generate the book 
- [ ] link the book from the doc index page

<img src="https://oldschoolrecordreview.files.wordpress.com/2015/04/turtles-all-the-way-down-sam-hollingsworth.jpg" />

It's no use, Mr. James – it's ~~turtles~~ docs all the way down.

Originally filed as  https://github.com/rust-lang/book/issues/725:

**Comment by steveklabnik** [comment]
Moving to p-high and assigning myself; i'd like to get this resolved in the next release cycle. If anyone else wants to pitch in, please let me know!

**Comment by steveklabnik** [comment]
@carols10cents the above has an environment variables bullet, but I can't find any environment variables in `librustdoc`. Were there ones you were thinking about? Maybe I'm bad at grepping...

**Comment by carols10cents** [comment]
I have exactly 0 recollection of filing this issue, but the turtles all the way down image has me written all over it, so I must have. This is awfully suspicious though:

>  carols10cents on May 30 • edited by steveklabnik (Steve Klabnik) 

(This is the only vaguely env var related code i could find on a cursory glance?](https://github.com/rust-lang/rust/blob/master/src/librustdoc/test.rs#L285-L299)

**Comment by steveklabnik** [comment]
Great, I'm just going to check it off then. If we magically discover one then we can add it, but I'm pretty sure there's nothing.
