### ISSUE TITLE
tracking issue for monitoring compiler performance

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#42611]
This is a tracking issue for the generic topic of monitoring compiler performance. We now have the `perf.rust-lang.org` infrastructure, but there are a number of extensions that would be helpful:

- [ ] Evaluate and improve the compile-time benchmark suite
    - The current suite was chosen somewhat haphazardly.
    - Some thoughts in [this internals thread.](https://internals.rust-lang.org/t/measuring-compiler-performance/4966).
- [ ] Tracking the runtime of generated code.
    - The current test suite tracks only compilation time.
    - https://github.com/rust-lang/rust/issues/31265: A rather preliminary effort to create a runtime benchmark suite.
- [ ] Improving the web interface: see the [rustc-perf](https://github.com/rust-lang-nursery/rustc-perf/issues) issue tracker.

cc @Mark-Simulacrum @rust-lang/compiler

**Comment by steveklabnik** [comment]
Triage: I'm not aware of what's going on here. @nikomatsakis is this metabug still useful?

**Comment by pnkfelix** [comment]
I think we may be picking up this task soon. I’d leave the metabug open at least until the next Rust all hands?

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this metabug, I think the general shape should be tracked in issues on rustc-perf these days (and each of these has a dedicated issue there or is too broad for effective tracking).
