### ISSUE TITLE
Tracking issue: improve error messages for IDEs

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#42823]
This is just a grab bag of things that would improve errors in IDEs via the RLS. These all apply to JSON errors rather than human-readable ones, where that's relevant

- [x] replace help with suggestions where possible
- [x] add suggestions that are not user-visible in human-readable output (e.g., to delete unused functions)
- [x] add suggestions in general (in particular, imports for name resolution errors)
- [x] implement the `rendered` field for all error types (currently only used by suggestions)
- [ ] make sure the main error message reads well by itself without any span labels
- [ ] if possible, suggestion labels should describe the action rather than the problem

cc @oli-obk @killercup @jonathandturner @est31

**Comment by oli-obk** [comment]
I already added import suggestions in https://github.com/rust-lang/rust/pull/41876 and am improving more name resolution errors in https://github.com/rust-lang/rust/pull/42033, but there's an inherent issue with the current name resolution impl and reporting path suggestions ( see PR for details)

**Comment by nrc** [comment]
I'm assuming the inherent issue is https://github.com/rust-lang/rust/pull/42033#issuecomment-309692903

My impression is that there are suggestions for some name resolution errors, but not all of them? And thus that there is still work to do here (I would like to nail this down more precisely).

cc @jseyfried too

**Comment by oli-obk** [comment]
Yes that is the issue description. The entire error reporting in resolve needs to be revamped I think.

I was trying to add them incrementally, as to not produce an immense unmanageable PR. These kind of changes produce a lot of churn in ui tests

**Comment by oli-obk** [comment]
The 4th box has been implemented in #46052

**Comment by estebank** [comment]
I believe all the actionable items in this ticket have already been addressed and the last two are ongoing concerns that belong in documentation, not an open ticket. Does anyone have an objection to closing this ticket?
