### ISSUE TITLE
Tracking issue for RFC 1789: Conversions from `&mut T` to `&Cell<T>`

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#43038]
This is a tracking issue for the RFC "Conversions from `&mut T` to `&Cell<T>`" (rust-lang/rfcs#1789).

**Steps:**

- [x] Implement the RFC
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Comment by bstrie** [comment]
This appears to have been implemented and is sitting behind the as_ref feature flag. Would anyone like to make any motions toward stabilization, or did the long discussion in the implementation PR cast doubts on the design?

**Comment by SimonSapin** [comment]
Let’s.

@rfcbot fcp merge

**Comment by dtolnay** [comment]
As I understand it, the new API here currently consists of:

```rust
impl<T: ?Sized> Cell<T> {
    pub fn from_mut(t: &mut T) -> &Cell<T>;
}

impl<T> Cell<[T]> {
    pub fn as_slice_of_cells(&self) -> &[Cell<T>];
}
```

**Comment by james-darkfox** [comment]
Can we have `&Cell<[T]>::split_at(usize) -> (&Cell<[T]>. &Cell<[T]>` or an Index that returns `Cell<[T]>` not `[Cell<T>]`?

I've quickly written an alternative to the byteorder crate using ~150 lines of safe rust with support for `Cell<[u8]>`. I'd like the above to extend it to include bit-level packing.

**Comment by czipperz** [comment]
Ping @BurntSushi @aturon @withoutboats do any of you have any concerns with merging this?

**Comment by SimonSapin** [comment]
Stabilization PR: https://github.com/rust-lang/rust/pull/61620

**Comment by SimonSapin** [comment]
Stabilized in #61620.

**Comment by czipperz** [comment]
Does someone want to edit the description to check the stabilization checkbox?

**Comment by SimonSapin** [comment]
Sure, though IMO the issue being close already reflects that everything in it is either done or obsolete.

**Comment by jethrogb** [comment]
Why doesn't this return `&mut Cell<T>`?

**Comment by SimonSapin** [comment]
Is there a case where this would be useful? I feel that having multiple references to the thing is the point of this API.

**Comment by jethrogb** [comment]
You can trivially convert a `&mut Cell<T>` to a `&Cell<T>` and then hand out multiple references. Also, it's too late now because 1.37 has been released.

**Comment by czipperz** [comment]
Is there a way to go from `&mut Cell<T>` to `&mut T`?

**Comment by jethrogb** [comment]
https://doc.rust-lang.org/std/cell/struct.Cell.html#method.get_mut

**Comment by czipperz** [comment]
So that's the reason why this should return `&mut Cell<T>` imo.

**Comment by SimonSapin** [comment]
This discussion is somewhat academic since `Cell::from_mut` is now stable on the stable channel, but:

* If you’re gonna convert to `&Cell<T>` anyway, why would it be useful (rather than merely not an obstacle) for `Cell::from_mut` to return `&mut Cell<T>`?
* If you’re gonna call `Cell::get_mut` on the result, why is it useful to go through `Cell::from_mut` in the first place? `&mut T` is what you started from.

**Comment by czipperz** [comment]
I see what you mean.  This is a tool for allowing temporary usage through a `&Cell<T>` for single thread scoped shared state.  But the long term storage solution should be `&mut T`.  I guess this api limits people to not store `&mut Cell<T>` that points to `&mut T`.  But I don't know how useful that is in reality.
