### ISSUE TITLE
LLVM 5.0 Tracking Issue

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#43370]
The time has come again, LLVM is releasing 5.0 soon and Rust wants to / needs to follow.

I have started work on the upgrade in these branches:

* `rust-lang/rust`: https://github.com/TimNN/rust/tree/llvm50
* `rust-lang/llvm`: https://github.com/rust-lang/llvm/tree/rust-llvm-2017-07-20
* `rust-lang/compiler-rt`: https://github.com/rust-lang/compiler-rt/tree/rust-2017-07-20
* `rust-lang-nursery/compiler-builtins`: https://github.com/TimNN/compiler-builtins/tree/llvm50

*Note: you may need to manually check out the `libcompiler_builtins` in `rust-lang/rust`.*

Next steps:
* [ ] Get `rustllvm` to compile ([error log](https://gist.github.com/aabb658aaf2460e94a46630b20e7db81))

Current issues:
* [ ] A lot changed around [attributes](https://github.com/llvm-mirror/llvm/blob/release_50/include/llvm/IR/Attributes.h)
* [ ] `SynchronizationScope` [changed / was renamed?](https://github.com/llvm-mirror/llvm/commit/8f85685860c0f6018a83b804f33e47f8122a9eba)
* [ ] `LLVMMetadataRef` was added, this can / should likely replace `LLVMRustMetadataRef`
* [ ] `createPointerType` [gained a new parameter](https://github.com/llvm-mirror/llvm/commit/2cee5cc825969057f8d23b507a4861e606216aed)
* [ ] `createNameSpace` [lost some parameters](https://github.com/llvm-mirror/llvm/commit/841400b968059a98f58ad258552692c7a4bd0bad)
* [ ] `DebugLoc` was replaced by `DiagnosticLocation` in [LLVM `DiagnosticInfo`](https://github.com/llvm-mirror/llvm/commit/787e150ebea15e81dbd497846388c8c5dc855fb6)

All but the first issues seem straight forward to fix, so I'll try to send PRs soon.

**Comment by TimNN** [comment]
cc @nagisa, @michaelwoerister, @arielb1, @eddyb: You have been recommend as familiar with the rust llvm wrapper, would one of you mind looking into the attributes changes?

**Comment by alexcrichton** [comment]
With #43387 looks like rustc can bootstrap on x86_64-unknown-linux-gnu, but there's a lot of test failures. A [full stage2 test run](https://gist.github.com/51863808eb6a8af11649bcb1d2aaac3f) has tons of errors, lots of compiler segfaults. A [stage1 test run](https://gist.github.com/a1a3a250dba4af400b5a1e0bb2964705) has much fewer errors:

```
test [compile-fail] compile-fail/proc-macro/derive-bad.rs ... FAILED
test [compile-fail] compile-fail/proc-macro/expand-to-unstable-2.rs ... FAILED
test [compile-fail] compile-fail/proc-macro/expand-to-unstable.rs ... FAILED
test [compile-fail] compile-fail/proc-macro/issue-38586.rs ... FAILED
test [compile-fail] compile-fail/proc-macro/item-error.rs ... FAILED
test [compile-fail] compile-fail/proc-macro/lints_in_proc_macros.rs ... FAILED
test [compile-fail] compile-fail/proc-macro/proc-macro-attributes.rs ... FAILED
test [codegen] codegen/lifetime_start_end.rs ... FAILED
test [codegen] codegen/issue-37945.rs ... FAILED
test [debuginfo-gdb] debuginfo-gdb/var-captured-in-nested-closure.rs ... FAILED
test [debuginfo-gdb] debuginfo-gdb/var-captured-in-sendable-closure.rs ... FAILED
test [debuginfo-gdb] debuginfo-gdb/var-captured-in-stack-closure.rs ... FAILED
test [run-make] run-make/llvm-pass ... FAILED
test [run-make] run-make/rustc-macro-dep-files ... FAILED
test [run-make] run-make/simd-ffi ... FAILED
test [run-pass] run-pass/debuginfo-lto.rs ... FAILED
test [run-pass] run-pass/issue-34569.rs ... FAILED
test [run-pass] run-pass/backtrace.rs ... FAILED
test [run-pass] run-pass/backtrace-debuginfo.rs ... FAILED
test [run-pass] run-pass/proc-macro/add-impl.rs ... FAILED
test [run-pass] run-pass/proc-macro/append-impl.rs ... FAILED
test [run-pass] run-pass/proc-macro/attr-args.rs ... FAILED
test [run-pass] run-pass/proc-macro/bang-macro.rs ... FAILED
test [run-pass] run-pass/proc-macro/count_compound_ops.rs ... FAILED
test [run-pass] run-pass/proc-macro/crate-var.rs ... FAILED
test [run-pass] run-pass/proc-macro/derive-same-struct.rs ... FAILED
test [run-pass] run-pass/proc-macro/issue-40001.rs ... FAILED
test [run-pass] run-pass/proc-macro/issue-39889.rs ... FAILED
test [run-pass] run-pass/proc-macro/hygiene_example.rs ... FAILED
test [run-pass] run-pass/proc-macro/use-reexport.rs ... FAILED
test [run-pass] run-pass/proc-macro/load-two.rs ... FAILED
test [run-pass] run-pass/issue-40663.rs ... FAILED
```

**Comment by alexcrichton** [comment]
@eddyb indicated on IRC that [this function call](https://github.com/rust-lang/rust/blob/6c949655de6bd2866d7d4bbac0238f35557563fc/src/librustc_trans/mir/mod.rs#L586-L595) may be responsible for the `debuginfo-gdb` failures, and he was spot on!

**Comment by alexcrichton** [comment]
I've filed https://bugs.llvm.org/show_bug.cgi?id=33883 related to the `run-make/simd-ffi` failure

**Comment by eddyb** [comment]
So LLVM got *even worse* (the current implementation sometimes creates an `alloca` to avoid pretty much this kind of misoptimization ruining complex `llvm.dbg.declare`).

The proper solution here at this point is to produce a pointer to *every single closure capture* (which means loading the respective pointer from the environment, if the capture is already by-ref), *and* then use `llvm.dbg.value` to indicate that... oh, wait, that won't work, let me step back.

Using `llvm.dbg.declare` *once* means that even if the value is modified *later*, a debugger knows *where* to get the value during the scope the name is defined for.
OTOH, `llvm.dbg.value` gives the value *at that time*, and even if you say the value is behind a pointer, that won't let the debugger see updated values from later writes to the same location.

Which means we need one `alloca` *for every single capture* (holding the pointers mentioned above). This is because of idiosyncratic LLVM limitations - even though there is a system for indicating *multiple* pointer offsets and dereferences to get from the argument to `llvm.dbg.declare` (or `llvm.dbg.value`) (a subset of "DWARF expressions"), `alloca` is required without data coming from it directly *anyway*.
With one `llvm.dbg.declare` per `alloca`, they should be simple enough not to break.

**Comment by alexcrichton** [comment]
The `codegen/issue-37945.rs` failure looks related to https://github.com/rust-lang/llvm/pull/90. @arielb1 would you be able to help out diagnosing this one? I've verified that the [llvm branch we have for 5.0](https://github.com/rust-lang/llvm/tree/rust-llvm-2017-07-20 does indeed include those commits:

* https://github.com/rust-lang/llvm/commit/7df06519765b14e1b08d7034c82c45a0a653eb25
* https://github.com/rust-lang/llvm/commit/156cc49e505986a1659adaa3a0b5a070372377c8
* https://github.com/rust-lang/llvm/commit/477bd758b48cb96477d3dd4cf3b36bf2706e8c1d
* https://github.com/rust-lang/llvm/commit/5a057dc8edbb63887f8c611dd8ddf1b76997f07c
* https://github.com/rust-lang/llvm/commit/2b66aeed20b61d42cd2782b94d5419c6faca49a1

Do you think that this may have regressed in upstream LLVM?

**Comment by alexcrichton** [comment]
I think I fixed `codegen/lifetime_start_end.rs` in https://github.com/rust-lang/rust/pull/43387/commits/38e40ce50653b8164915b8142e883c5a57b33e7b

**Comment by TimNN** [comment]
For a stage 1 test run, I get the same failures as @alexcrichton, for compile-fail proc macro derive:

```
thread '<unnamed>' panicked at 'proc_macro::__internal::with_sess() called before set_parse_sess()!', /home/logic/build-tmp/rust-src/src/libproc_macro/lib.rs:678:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
```

[full logs](https://gist.github.com/6d24eab1c903c46ea533ee8e6856dee1)

I'm not sure about the initial panic message, but the "failed to initiate panic" seems kind of bad (`error 5` is apparently `_URC_END_OF_STACK`)

For `run-pass` proc-macro-derive:

```
index out of bounds: the len is 0 but the index is 4294967206
```

That also seems bad.

**Comment by alexcrichton** [comment]
@TimNN oh no need to worry about those, that's a benign failure. Procedural macros don't work in stage1 and not all tests are flagged as `// ignore-stage1`

**Comment by alexcrichton** [comment]
Filed an [upstream bug](https://bugs.llvm.org/show_bug.cgi?id=33917) for the segfaults in rustc I've been seeing. (segfaults were happening on all platforms)

**Comment by arielb1** [comment]
> The codegen/issue-37945.rs failure looks related to rust-lang/llvm#90. @arielb1 would you be able to help out diagnosing this one? I've verified that the llvm branch we have for 5.0 does indeed include those commits:

Sure. That's probably https://bugs.llvm.org/show_bug.cgi?id=33470

**Comment by alexcrichton** [comment]
Ok thanks @arielb1! Do you think it'd be safe to ignore that test during the LLVM upgrade in favor of that upstream bug? Or do you think we should block the upgrade on fixing that?

**Comment by arielb1** [comment]
The bug looks quite bad. Let's ignore it for now to see all the other bugs. I bet I can get it fixed first.

**Comment by alexcrichton** [comment]
[This tree of commits](https://github.com/alexcrichton/rust/commits/61d1b6781fa8451cb64fd486d5637fc5e3fe1395) passes `./x.py test` on x86_64-unknown-linux-gnu with LLVM assertions enabled.

**Comment by alexcrichton** [comment]
I've [done a full travis run](https://travis-ci.org/rust-lang/rust/builds/257578179) against a tree with [a number of workarounds](https://github.com/alexcrichton/rust/commits/8c5ab5f60051d18b07a2fd469861a5bc09176e21), and I believe all open issues are listed under "Open Tasks" above.

**Comment by alexcrichton** [comment]
@eddyb commenting out [the call site](https://github.com/rust-lang/rust/blob/6c949655de6bd2866d7d4bbac0238f35557563fc/src/librustc_trans/mir/mod.rs#L586-L595) you indicated fixes the debuginfo related asserts in LLVM, but it doesn't actually cause any tests in Rust to fail. Do you know of an example of a test that would fail if we don't emit that debuginfo?

**Comment by eddyb** [comment]
@alexcrichton Erm, that means we don't have tests for closures... without that call no closure captures can be seen from a debugger as a local variable (from within the closure body).
cc @michaelwoerister

**Comment by michaelwoerister** [comment]
We actually do have a few test cases for captured variables, e.g. https://github.com/rust-lang/rust/blob/master/src/test/debuginfo/var-captured-in-stack-closure.rs.

**Comment by arielb1** [comment]
The #37945 failure should be fixed by https://github.com/llvm-mirror/llvm/commit/7d99ae532b4919d625248fe2b106eed38770c56e

**Comment by alexcrichton** [comment]
Awesome, thanks @arielb1! I've rebase our LLVM branch and cherry-picked that change onto it.

**Comment by bstrie** [comment]
LLVM 5.0 has been released as of yesterday, is there an update to this bug for those following along at home?

**Comment by alexcrichton** [comment]
No, the status at the top is still the status.

**Comment by dylanmckay** [comment]
I have kicked off the emscripten upgrade

* Emscripten tracking issue
    * kripken/emscripten-fastcomp#193
* Pull requests
    * kripken/emscripten-fastcomp#199
    * kripken/emscripten-fastcomp-clang#19

Depending on the amount of breakage, I may not have the time to put too much work into fixing the tests in the next week or two. If work goes stale, or even if anybody just feels like it, feel free to help out

**Comment by ishitatsuyuki** [comment]
Just by the way, this will block Arch from pushing any updated Rust compiler as llvm-5.0.0-1 is already in stable repository.

If possible, I would like to see a WIP PR so I can start building dev (easily) with system LLVM.

**Comment by ishitatsuyuki** [comment]
I see, #44421 is the blocking issue instead then. Maybe we can cherry pick the fix?

**Comment by sajattack** [comment]
I am also unable to build due to #44421

**Comment by ishitatsuyuki** [comment]
@cuviper I have experienced failure with current nightly, even after glibc downgrade.

```
cargo:warning=../rustllvm/PassWrapper.cpp:29:10: fatal error: llvm/Object/ModuleSummaryIndexObjectFile.h: No such file or directory
cargo:warning= #include "llvm/Object/ModuleSummaryIndexObjectFile.h"  
cargo:warning=          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=compilation terminated.
```

**Comment by ishitatsuyuki** [comment]
@alexcrichton can you backport https://github.com/alexcrichton/rust/commit/8687fa0e02061dd8d46ce805afaa75a2a93c1835? I guess it's the only blocker.

**Comment by main--** [comment]
On Arch Linux with stable Rust+LLVM right now:

```
$ cargo build
   Compiling fallible-iterator v0.1.3
   Compiling byteorder v1.1.0
   Compiling odds v0.2.25
invalid expression
!2579 = !DIExpression(6, 34, 0, 6)
invalid expression
!2582 = !DIExpression(6, 34, 8, 6)
   Compiling nodrop v0.1.9
   Compiling arrayvec v0.3.23
```

**Comment by hussamT** [comment]
Archlinux's rust doesn't actually depend on llvm-libs. it links statically against llvm.
You can downgrade to llvm4/llvm-libs4, recompile rust (edit out llvm-libs dependency from rust PKGBUILD) and then upgrade back to llvm5.

**Comment by ishitatsuyuki** [comment]
As we're running behind schedule, is it feasible to backport the compiler-rt matters first? It should fix much build/runtime issues on Arch, AFAIK:
- glibc compat
- ASan linkage

**Comment by martell** [comment]
@TIMNN the fix for debug-infogdb was merged into the 5.0 branch as https://reviews.llvm.org/rL309767
Seems like for this release we should skip 5.0.0 and go straight to 5.0.1.
It should be out very shortly.

asm.js seems to be the blocker here.
The real pain point is that asm.js has to do a full upgrade similar to what has to be done for rust.
This doubles the work load for a rust llvm upgrade.
@alexcrichton With asm.js giving birth to wasm and now that LLD has initial wasm linker support hopefully by 6.0.0 we begin a discussion around dropping asm.js if wasm support is where it needs to be? I'm not sure on the browser requirement implications but I thought I should bring this up.

**Comment by shepmaster** [comment]
> begin a discussion around dropping asm.js

I believe you are looking for #44006

**Comment by alexcrichton** [comment]
Given this problem and the amount of time it's been here, we've concluded that the best way forward here is mostly likely to just ship multiple LLVM backends. I've [opened an issue](https://github.com/rust-lang/rust/issues/46819) for this and would love some help implementing it! If you're interested in doing so, please just let me know.

**Comment by devurandom** [comment]
(@ishitatsuyuki commented on Oct 13 )
> @alexcrichton can you backport alexcrichton/rust@8687fa0? I guess it's the only blocker.

Where does alexcrichton/rust@8687fa0e02061dd8d46ce805afaa75a2a93c1835 live? It does not seem to be published by any branch.

**Comment by ishitatsuyuki** [comment]
It's probably superseded with a force push, and anyway I have backported and got it merged into master.

**Comment by cuviper** [comment]
What's the status of the "invalid expression" `DIExpression` errors?  Has anyone attempted the fix that @eddyb described in https://github.com/rust-lang/rust/issues/43370#issuecomment-317111044?

**Comment by alexcrichton** [comment]
@cuviper AFAIK no progress has been made

**Comment by cuviper** [comment]
I filed #47464 specifically for the `DIExpression` issue.

**Comment by cuviper** [comment]
#47610 should fix `DIExpression`.

I've added #47611 for a different debuginfo issue.

**Comment by alexcrichton** [comment]
Awesome, thanks so much for tracking that down @cuviper!

**Comment by devurandom** [comment]
This will first appear in Rust 1.25, correct?

**Comment by cuviper** [comment]
It will actually be LLVM 6, but yes, starting in 1.25.

**Comment by gaming-hacker** [comment]
What's the status on implementing fixes for llvm-6.0?

**Comment by gaming-hacker** [comment]
@martell, thanks my bad.
