### ISSUE TITLE
Tracking issue for RefCell::{replace, swap}

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#43570]
Tracking issue for https://github.com/rust-lang/rfcs/pull/2057

* [x] Implement the functionality
* [x] Add documentation
* [ ] Stabilize!

**Comment by notriddle** [comment]
Can I implement this? (I understand you'll want to give it the C-assigned label, to make sure nobody else works on it)

**Comment by alexcrichton** [comment]
Certainly!

**Comment by notriddle** [comment]
- [X] Implemented the functionality
- [ ] What documentation is needed beyond the API docs?
- [ ] I assume that once 1.20 is released, we'll be able to talk about marking it stable.

**Comment by Havvy** [comment]
The only docs needed for this is the API docs.

I've also written PR #45819 to add a `replace_with` variant.

**Comment by gbip** [comment]
Is there any plan to make this stable ? I can't figure the syntax to move a value inside a RefCell to replace the old one.
Thanks !

**Comment by alexcrichton** [comment]
Stabilized in https://github.com/rust-lang/rust/pull/46517

**Comment by SimonSapin** [comment]
`replace_with` was not stabilized together with `replace` and `swap` in #46517 because it wasn’t part of https://github.com/rust-lang/rfcs/pull/2057.

Let’s stabilize it now, perhaps with the “corresponds to `std::mem::replace`” bit of doc removed per https://github.com/rust-lang/rust/pull/45819#issuecomment-347847981

@rfcbot fcp merge

**Comment by alexcrichton** [comment]
@rfcbot concern footgun

I'd personally be somewhat concerned about the `replace_with` API in terms of the intended use case of `RefCell`. Used in the case where mutability doesn't cut it usage of `RefCell` often implies lots of aliasing all over the place which is often difficult to determine statically. As a result correct progress mostly minimize the amount of time a `RefCell` is borrowed or otherwise used for. I'd be worried that allowing an arbitrary closure in `replace_with` is hiding the fact that you're borrowing the `RefCell` for the duration of the entire closure. It may be clearer to force authors to explicitly take a borrow and map it to see where the borrow duration runs?

**Comment by alexcrichton** [comment]
I'm also under the impression that this isn't a massively used method in the sense that the ergonomic win here isn't necessary critical, but I could be wrong!

**Comment by Havvy** [comment]
I sent the PR for it because I wrote the function freely in my own code where I wanted to recurse through a path in a tree without passing a Vec of RefCell borrows but rather keep the borrow information in the stack.

Putting a warning that the RefCell is borrowed for the duration of the closure into the documentation would help.

**Comment by alexcrichton** [comment]
@SimonSapin do you have thoughts on the concern I listed above?

I'm not personally a huge fan of a warning in the sense that I don't think it absolves us of the footgun of the API, but if there's a strong use case for adding it then the warning is likely enough. I do not currently see, however, the strong use case for adding this

**Comment by Phlosioneer** [comment]
This has been merged. Tracking issue can be closed.

**Comment by Havvy** [comment]
`RefCell::replace_with` has not been stabilized yet.

**Comment by Phlosioneer** [comment]
Ah. I thought that would be a different issue, because it's not in the title and not in the RFC. Sorry.

**Comment by alexcrichton** [comment]
@rfcbot resolve footgun

I don't want to personally be on the hook for blocking this any more

**Comment by jonas-schievink** [comment]
Seems like this just needs a stabilization PR now?
