### ISSUE TITLE
Tracking issue for RFC 2025: Enabled nested method calls

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#44100]
This is a tracking issue for the RFC "Enable nested method calls" (rust-lang/rfcs#2025).

**Steps:**

- [x] Implement the RFC
    - Implementation specifically is tracked in https://github.com/rust-lang/rust/issues/46037
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Issues and questions to be resolved prior to stabilization:**

- [ ] as currently implemented, the two-phase borrows apply more broadly than the RFC text permitted https://github.com/rust-lang/rust/issues/46747

**Comment by nikomatsakis** [comment]
closing in favor of https://github.com/rust-lang/rust/issues/43234

**Comment by pnkfelix** [comment]
(I'm a little worried that closing this in favor of #43234 is going to increase the change that we either overlook or prepetually delay resolving #46901...)
