### ISSUE TITLE
incremental: refactor out non-query data from tcx

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#44137]
There are various fields in the tcx of data that is not tracked for incremental compilation, or is tracked in an odd way. Here is a ~~partial~~ list:

- [ ] used_mut_nodes - https://github.com/rust-lang/rust/pull/43945
- [x] rvalue_promotable_to_static - https://github.com/rust-lang/rust/pull/44501
- [x] normalized_cache - https://github.com/rust-lang/rust/pull/44501
- [x] inhabitedness_cache - https://github.com/rust-lang/rust/pull/44501
- [x] trait_map - #44162
- [x] export_map - #44162
- [x] named_region_map - #44142
- [x] specializes_cache - #44157
- [x] freevars - #44142
- [x] maybe_unused_trait_imports - #44142
- [x] maybe_unused_extern_crates - #44142
- [x] used_unsafe - #44195 
- [x] stability - #44142

In each case, the idea would be to (at least to start) encapsulate the fields so that we are using queries to access those maps. I'll try to write up some mentoring instructions for each one later on.

cc @michaelwoerister

**Comment by petrochenkov** [comment]
Regarding `named_region_map`, I wanted to move lifetime resolution to AST some time, and then store lifetime resolutions directly in HIR (like resolutions for other names/paths), including various late-bound and elided lifetimes.

**Comment by nikomatsakis** [comment]
Here are some other fields that look suspicious to me:

- [ ] freevars
- [ ] maybe_unused_trait_imports
- [ ] maybe_unused_extern_crates
- [ ] normalized_cache
- [ ] inhabitedness_cache
- [ ] used_unsafe
- [ ] used_mut_nodes (https://github.com/rust-lang/rust/pull/43945)
- [ ] stability
- [ ] rvalue_promotable_to_static

Many of these follow the pattern of "maps produced by resolve that ought to be accessed via queries and ought *not* to be indexed by `NodeId`".

**Comment by alexcrichton** [comment]
The final item here is tracked by https://github.com/rust-lang/rust/issues/42384, so closing in favor of that
