### ISSUE TITLE
incr.comp.: Do not hard-wire DepGraph into Session and CrateStore.

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#44390]
In the current setup, we create the `DepGraph` [very early](https://github.com/rust-lang/rust/blob/d7d75eff30ff03f607ff0656a50f4be768cfdbc9/src/librustc_driver/lib.rs#L296), so it can be put into the `CrateStore` and the `Session` object. This means that we construct the `DepGraph` long before we have enough information to know where to load the previous `DepGraph` from and, because the `CrateStore` is used very early too, we are registering dep-nodes and edges before the graph is fully operational. This is ugly but harmless in the current implementation. In the new tracking system it would become a problem.

So the plan is to construct the `DepGraph` only when we can already load the previous `DepGraph`. This needs some refactoring:
- [x] Remove the `dep_graph` field from `Session`, - #44502
- [x] Remove the `dep_graph` field from `CStore` and don't do any dependency tracking in the regular `CStore` implementation. - #44418
- [x] Make sure that we *do* perform dependency tracking for anything within the query system, via a tasteful blend of: - #44142 and #44420
  - [x] creating a `CrateStore` wrapper that does dependency tracking and make only that available via `tcx.cstore()`, and - #44142
  - [x] making all `CrateStore` access go through queries. - #44142
- [x] Adapt `librustc_incremental::persist::fs::prepare_session_directory()` to not need the `tcx` and invoke it [right after parsing, when we know the definitive crate name](https://github.com/rust-lang/rust/blob/d7d75eff30ff03f607ff0656a50f4be768cfdbc9/src/librustc_driver/driver.rs#L142). - #44502
- [x] Move `DepGraph` construction to right after `librustc_incremental::persist::fs::prepare_session_directory()` has been called. - #44502

Any work in this direction will want to be based on top of ~~https://github.com/rust-lang/rust/pull/44341~~ the master branch.

**Comment by michaelwoerister** [comment]
cc @nikomatsakis @alexcrichton

**Comment by alexcrichton** [comment]
@michaelwoerister should the `DepGraph` argument all throughout `Decoder` also be removed? For example in [this function](https://github.com/rust-lang/rust/blob/d93036a043dbd19f394ad320313bdbe81644f121/src/librustc_metadata/decoder.rs#L871-L903).

After #44142 lands then 100% of the existing cstore methods are now queries (yay!) or otherwise don't need to be tracked.

**Comment by michaelwoerister** [comment]
> @michaelwoerister should the DepGraph argument all throughout Decoder also be removed? For example in this function.

Ideally the "raw" CrateStore implementation would not know anything about the DepGraph anymore, just the queries (if that's possible).

**Comment by alexcrichton** [comment]
Ok! Sounds like a "yes"

**Comment by alexcrichton** [comment]
I have a commit for completely removing `DepGraph` from the `CrateStore` at https://github.com/alexcrichton/rust/commit/74f6a220d1b14f83efb23b6125786bdb6cc26c59, just waiting on #44142 to land
