### ISSUE TITLE
Tracking issue for RFC 2133: compiler-generated Clone impls for Arrays and Tuples 

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#44496]
This is a tracking issue for the RFC "compiler-generated Clone impls for Arrays and Tuples " (rust-lang/rfcs#2133).

**Steps:**

- [x] Implement the RFC (cc @rust-lang/compiler -- can anyone write up mentoring instructions?)
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [x] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Comment by arielb1** [comment]
The RFC has already been implementd and stabilized.

**Comment by arielb1** [comment]
So we just need to add documentation. I suppose our documentation is just as good as that for the [Copy Trait](https://github.com/rust-lang-nursery/reference/blob/0168b9f4c31001a2ce28bcd79865feaa77ccf567/src/the-copy-trait.md)

**Comment by Mark-Simulacrum** [comment]
It seems that the reference documents this at least implicitly, stating that tuples and arrays of Clone/Copy types get impl's for Copy/Clone by the compiler. So I'm closing.
