### ISSUE TITLE
Tracking issue for RFC 2128: Nested groups in imports

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#44494]
This is a tracking issue for the RFC "Nested groups in imports" (rust-lang/rfcs#2128).

**Steps:**

- [x] Implement the RFC ([very rough mentoring instructions here](https://github.com/rust-lang/rust/issues/44494#issuecomment-330540496) and [here](https://github.com/rust-lang/rust/issues/44494#issuecomment-330851451))
- [x] Adjust documentation ([see instructions on forge][doc-guide])
- [x] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Comment by pietroalbini** [comment]
I'd like to work on this.

**Comment by nikomatsakis** [comment]
@pietroalbini great! I think @petrochenkov or @jseyfried would be best equipped to writing up some mentoring notes here. But I think the general idea is going to be something like this:

- Extend [the AST](https://github.com/rust-lang/rust/blob/3a7b960731fd1cf86f1879b1a0d44196a0917c53/src/libsyntax/ast.rs) to support the new syntax. Generally speaking, we try to keep the structure of the AST as a "close match" to the raw rust input, so I think we would want to mirror the new structure there.
- Update [name resolution](https://github.com/rust-lang/rust/blob/3a7b960731fd1cf86f1879b1a0d44196a0917c53/src/librustc_resolve/lib.rs) to handle this. This is the part where I can't help -- at least without doing some digging! Hopefully, there are some intermediate data structures that we can "desugar" these extended-form view items into, and it doesn't operate directly off of the AST.

**Comment by petrochenkov** [comment]
>Update name resolution to handle this.

The desugaring is done here https://github.com/rust-lang/rust/blob/master/src/librustc_resolve/build_reduced_graph.rs#L113

**Comment by nikomatsakis** [comment]
@pietroalbini just checking in -- any progress? Any questions arisen?

**Comment by pietroalbini** [comment]
I'm still working on this. I [mostly updated all of rustc](https://github.com/rust-lang/rust/compare/master...pietroalbini:use-nested-groups) to support the feature, and now I started fixing a few bugs in the code.

**Comment by nikomatsakis** [comment]
@pietroalbini how's it going? I'm just checking in -- I know you've been hard at work on this, I was just wondering if you could give a quick status update.

**Comment by pietroalbini** [comment]
@nikomatsakis sure!

I fixed a few days ago a bunch of errors related to `self`, and now there is an bug with the hir nodes. I plan to try fixing that tomorrow, and then _hopefully_ all the errors will be fixed. After that I'll need to update all the tests (and write new ones) and feature gate the thing, and then the feature will be ready to be merged.

**Comment by pietroalbini** [comment]
The feature has been merged :tada: :tada:  
Can someone update the checklist?

**Comment by matklad** [comment]
Hm, I am quite surprised that neither the RFC nor the tracking issue had a single "no, we don't need this" comment... Given the amount of ❤️ on the RFC, I think that community overwhelmingly supports this feature, so my concerns are probably unfounded, but I still would want to register them.

I personally am neutral or slightly negative about the usefulness of this feature. The benefits seems marginal, but there's certainly a cost to chose between several ways of writing the same import now. 

I already spend quite some time make imports perfect: stdlib first, then external crates, then my crate, then sort them alphabetically, then decide if I should go with `use my_crate::foo::bar` or `use super::bar`, then decide if I need the leading `::` in use path. Adding one more decision point to the already confusing use statements is not a clear win. 

On the other hand, duplicating path segments does not seem **that** unergonomic, especially given that you can easily sort them.

**Comment by SimonSapin** [comment]
> I already spend quite some time make imports perfect: […]

These are all stylistic choices. You can choose not to use this new syntax.

**Comment by pietroalbini** [comment]
While someone can surely abuse this new syntax if they want, it can be really nice in a few cases. For example, I tend to group related imports together, so if I want to use an atomic across threads `use std::sync::{Arc, atomic::{AtomicBool, Ordering}};` is great.

**Comment by aturon** [comment]
I think we should consider stabilizing this feature for the 1.25 release (this cycle). As such:

@rfcbot fcp merge

**Comment by nikomatsakis** [comment]
I think I would be happy to stabilize, but I'd like to see a 'stabilization report' prepared. Essentially this would be a brief summary of the feature plus some links to test cases showing it works as expected, along with a list of edge cases that came up and and were considered. This seems like a sort of minimal "due diligence" that we ought to do before stabilizing.

Looking over @pietroalbini's PR, I found these:

- basic test showing things work [`run-pass/use-nested-groups.rs`](https://github.com/rust-lang/rust/blob/a0dcecff90c45ad5d4eb60859e22bb3f1b03842a/src/test/run-pass/use-nested-groups.rs)
- also covers globs in nested imports `use self::{foo::*}`
- [only relative paths are allowed in nested groups](https://github.com/rust-lang/rust/blob/a0dcecff90c45ad5d4eb60859e22bb3f1b03842a/src/test/compile-fail/absolute-paths-in-nested-use-groups.rs) (e.g., `use foo::bar::{super::baz}` is an error)
- we warn on `use foo::{*, *}`

One case not currently tested, from what I could tell, is a "doubly nested" group with multiple options, sort of like this:

- `use a::{b::{c1, c2}}` (we have `use a::b::{c::d}` in [the `use-nested-groups.rs` test]https://github.com/rust-lang/rust/blob/a0dcecff90c45ad5d4eb60859e22bb3f1b03842a/src/test/run-pass/use-nested-groups.rs#L27))

I think I'd like to see that test, as it seems slightly different from the other cases, but overall this looks pretty good to me!

**Comment by nikomatsakis** [comment]
To be clear, I'm giving my r+ to stabizing but I'd like to see those two tests I mentioned in the stabilization PR. =)

**Comment by pietroalbini** [comment]
Other than the tests mentioned by @nikomatsakis, there are a few problems at the moment:

* `use {{}, {}};` crashes the compiler -- issue #47673 and PR #47705 (waiting review)
* Unused imports lint behave strangely when empty groups are nested (the spans for every element except the empty group are correct, but the group is overlapping with everything else):

```
warning: unused imports: `b2`, `c1`, `c2`, `use a::{b1::{c1, c2}, b2, {}};`
  --> test.rs:11:1
   |
11 | use a::{b1::{c1, c2}, b2, {}};
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default
```

I'm planning to write a fix for the unused lint later this evening, and I'll add the new tests after.

**Comment by nikomatsakis** [comment]
@pietroalbini thanks for the info!

**Comment by nrc** [comment]
Hmm, this feature has only been implented for two months - that seems a pretty short stabilisation period. I don't have a strong objection to stabilising, but I don't feel a rush to either - this has always felt like a marginally useful bit of syntax sugar, with some added complexity in exchange.

**Comment by aturon** [comment]
@nrc it will still take another 3 months to actually reach stable.

Given the pipeline of features we're hoping to stabilize for the epoch release, and the [timeline thereof](https://github.com/rust-lang/rfcs/pull/2314), we need to be steadily stabilizing features to avoid a last-minute rush -- particularly when they are as straightforward as this one.

This feature is also quite important for considerations around the new module system path syntax.

**Comment by steveklabnik** [comment]
So, I'm all in favor of stabilizing this soon. However, I see that the documentation checkbox has been checked, but I can't see any links to those PRs in this issue? Does anyone have links handy, or does @rust-lang/docs need to get on it? :)

**Comment by pietroalbini** [comment]
@steveklabnik I think it's checked because I already prepared the snippets to be added to the various docs when I sent the original PR ([available on the unstable book](https://doc.rust-lang.org/nightly/unstable-book/language-features/use-nested-groups.html)). I can send PRs to the various repos so the docs team can review them, after the lang team accepts the stabilization.

**Comment by steveklabnik** [comment]
Ah, normally the process is, PRs should be open in order for someone to be able to call for stabilizing. This is a small enough feature that I'm happy to do it after.

**Comment by aturon** [comment]
I'd love to get this in for the current release cycle (beta branches in about two weeks) -- anyone want to take on the stabilization here?

**Comment by pietroalbini** [comment]
Sure, I'll start sending out PRs.

**Comment by petrochenkov** [comment]
The stabilization PR has actually landed (and doc PRs are sent), so this is done.
