### ISSUE TITLE
(RFC 1210) specialization: restrictions around lifetime dispatch 

### ISSUE THREAD

**Issue by giannicic** [rust-lang/rust#45982]
Note: https://github.com/rust-lang/rust/issues/31844 is the tracking issue for specialization in general

this issue tracks the tasks to do to implement "restrictions around lifetime dispatch" as described [here](https://internals.rust-lang.org/t/shipping-specialization-a-story-of-soundness/5507):

Specialization based on lifetimes shouldn't be allowed partly because "trans" erases any lifetime information and partly because lifetime inference could lead to counterintuitive result.
Unfotunately it's not easy to avoid any lifetime dependent specialization.
Additionally, using lifetime specialized associated types results in different deductions between type_check and trans 

Things to do:
- [ ] Stabilize just the core specialization, it will work without specializing associated type. Introduce a new feature gate called `assoc_specialization` necessary when using specialization on `default type`s.
- [ ] Issue a warning that a specialization might have applied in case a specialized `impl` imposes any lifetime constraints not present in the more general `impl`. 
      The warning should be issued at trans time when the more general `impl` is selected over the specialized `impl`, it could be relaxed or forbidden as described in this [reply](https://internals.rust-lang.org/t/shipping-specialization-a-story-of-soundness/5507/5)
- [ ] If the specialized `impl` use the same lifetime constraints as the more general `impl`, specialization should work as expected.

@nikomatsakis

**Comment by Mark-Simulacrum** [comment]
It seems like this isn't tracking extra state -- https://github.com/rust-lang/rust/issues/31844 is the primary tracking issue for specialization, and already has discussion of it not being unsound. There's definitely work here to resolve these concerns and move us forward, but it's not particularly useful to have a separate issue for it that's not being actively updated or paid attention to.

With that in mind, closing in favor of #31844.
