### ISSUE TITLE
Move Rust By Example to the Main Website

### ISSUE THREAD

**Issue by projektir** [rust-lang/rust#46194]
This is an issue for moving Rust By Example, which is currently at [https://rustbyexample.com/](https://rustbyexample.com/), to [https://doc.rust-lang.org/rust-by-example](https://doc.rust-lang.org/rust-by-example). I will be working on the first step shortly.

- [x] Convert RBE to a submodule under `rust-lang/rust/src/doc`
- [x] Add RBE to the bookshelf (thanks @QuietMisdreavus!)
- [x] Update book release process on forge

After it is converted and RBE reaches stable:

- [ ] Update the main English website link
- [ ] Make [https://rustbyexample.com/](https://rustbyexample.com/) a 301

**Comment by projektir** [comment]
Step one done! Now waiting for this to reach stable.

**Comment by Havvy** [comment]
The forge documentation can be updated now.

**Comment by steveklabnik** [comment]
This has all been done!
