### ISSUE TITLE
Make rustc thread safe when queries can be used

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#46596]
This is just an issue noting down the things required to make rustc thread safe when queries can be used.

- [ ] [Make GlobalCtxt implement Sync](https://github.com/rust-lang/rust/pull/45912)
- [x] Use scoped thread locals instead of globals, https://github.com/rust-lang/rust/pull/46193
- [ ] Misc fixes required to use a rayon thread pool, https://github.com/rust-lang/rust/pull/46564
- [x] Ensure metadata [loaded by LlvmMetadataLoader](https://github.com/rust-lang/rust/blob/master/src/librustc_trans/metadata.rs#L25) does not get freed on the wrong thread
- [ ] [CurrentDepGraph.task_stack](https://github.com/rust-lang/rust/blob/master/src/librustc/dep_graph/graph.rs#L764) has to be made a `QueryJob` field.
- [ ] [ParseSess.included_mod_stack](https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/mod.rs#L51) might be problematic
- [ ] Check that optimization fuel is not used with parallel queries
- [ ] Ensure that the err_count() API is not used to discover if errors happen in parallel code
- [ ] Find a way to order error messages deterministically so that if a query depends on another query, its error messages appear after the other query
- [ ] Make `mk_attr_id` use a scoped thread local or make it part of `ParseSess`
- [ ] See if we can get rid of [locks on `TransitiveRelation`](https://github.com/rust-lang/rust/pull/48587) once old borrowck is gone
- [ ] Review `libproc_macro` for issues, Find out which types should be `Send`, `Sync`. Deal with `Deref` impls for `Symbol`.
- [x] [Run CI with cfg(parallel_queries)](https://github.com/rust-lang/rust/issues/48607)
- [ ] Refactor away `CStore::next_crate_num`
- [ ] Refactor away `FileMap.external_src`, `FileMap.lines`, `FileMap.multibyte_chars`,  and `FileMap.non_narrow_chars`
- [ ] When executing queries, instead of keeping around a lock to the query map, create a job object immediately instead

**Comment by michaelwoerister** [comment]
Copied the items from this issue into #48685.
