### ISSUE TITLE
Privacy policy tracking issue

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#47347]
A couple of Rust related websites use Google Analytics. Google's TOS [require you](http://www.davemulder.com/2010/07/01/using-google-analytics-wheres-your-privacy-policy/) to provide a privacy policy. I couldn't find any privacy policy for rust related websites, so I'm creating this tracking issue to track adoption of privacy policies.

Edit: the core team has decided to remove google analytics, see @steveklabnik 's [comment below](https://github.com/rust-lang/rust/issues/47347#issuecomment-373040646). Thus, this list now tracks which domain has no google analytics:

- [x] https://crates.io => https://github.com/rust-lang/crates.io/commit/9ed7bbeb3768bf61d420526f58f600ae366e0ec5
- [x] https://www.rust-lang.org/ => https://github.com/rust-lang/rust-www/pull/1087
- [x] https://blog.rust-lang.org (https://github.com/rust-lang/blog.rust-lang.org/commit/7f30e2468e0f22a35741d2cfc399a88726a622d3) => https://github.com/rust-lang/blog.rust-lang.org/pull/253
- [x] https://buildbot2.rust-lang.org
- [x] ~https://buildbot.rust-lang.org~
- [x] ~https://crater.rust-lang.org~
- [x] https://dev-static.rust-lang.org
- [x] https://doc.rust-lang.org ... no idea about this one it hosts a multitude of generated content. There might be google analytics hiding *somewhere* but I don't think so.
- [x] https://forge.rust-lang.org
- [x] https://internals.rust-lang.org
- [x] https://perf.rust-lang.org
- [x] https://play-next.rust-lang.org
- [x] https://play.rust-lang.org
- [x] ~https://playtest.rust-lang.org~
- [x] https://static.rust-lang.org
- [x] ~https://testsite.rust-lang.org~
- [x] https://thanks.rust-lang.org
- [x] https://users.rust-lang.org
- [x] https://xn--qei.rust-lang.org

doc.rust-lang.org seems to be clean. Haven't checked any other websites, so please feel free and edit this issue post and add them here if you find that they use google analytics as well.

Also, if it isn't enabled yet, I think that the "Mozilla feature" should be enabled in the interface (IIRC it was added on pressure by Mozilla), to prevent Google from using the collected data for other purposes.

**Comment by Aaronepower** [comment]
It is also important that use of a third party advertising service means that those cookies aren't exempt from The EU Cookie Law and requires there be a popup that allows the user to give their consent.

**Comment by carols10cents** [comment]
crates.io issue

**Comment by est31** [comment]
I think we should disable Google Analytics usage across Rust websites until the problem is resolved, maybe even after that.

**Comment by Aaronepower** [comment]
Also it's worth pointing out that after the 25th of May this will be in violation of [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) which also requires that you can't just have a popup like "We're using cookies click X to hide this". The cookies have to be off by default and the user has to opt into giving their data.

**Comment by steveklabnik** [comment]
The core team discussed this, and we are fine just wholesale removing GA. We thought it was more useful than it actually is in practice.

PRs welcome, and if nobody gets to it, ill do it next week.

Sorry about the wait here.

**Comment by Havvy** [comment]
This is a reminder that the GDPR deadline has passed, and the GA stuff is still there.

**Comment by est31** [comment]
@steveklabnik has just disabled GA internals.rust-lang.org, and thus we are GA free now. Thanks to everyone who has contributed.

It might make some sense to think about privacy policies for places that actually store personal information, like crates.io but I think that is best left to a separate issue, as this one has turned out to be very Google Analytics focused.

**Comment by steveklabnik** [comment]
I have merged several PRs, and removed the GA code from internals. I believe that's everything! If not, please let me know.

Thank you everyone, for pushing on this.

**Comment by steveklabnik** [comment]
> It might make some sense to think about privacy policies for places that actually store personal information, like crates.io

This is in the works.
