### ISSUE TITLE
tracking issue for bugs fixed by the MIR borrow checker or NLL

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#47366]
Part of: https://github.com/rust-lang/rust/issues/43234

The MIR-based borrow checker used by NLL fixes a number of bugs in the existing AST-based borrow checker. Our plan for these bugs is to fix them by transitioning to the MIR-based borrow checker. In the meantime, we wish to add tests that show that the bugs are fixed with NLL, and then close the bugs (so they don't clutter up the issue tracker).  This issue tracks the set of such bugs and gives instructions for how to proceed.

## Bugs fixed by MIR

All these bugs are **confirmed as fixed**; the checkmark indicates that a PR with a test is enqueued or landed.

- [x] https://github.com/rust-lang/rust/issues/46557
- [x] https://github.com/rust-lang/rust/issues/38899
- [x] #45045 (using example from [this comment](https://github.com/rust-lang/rust/issues/45045#issuecomment-356953507))
- [x] https://github.com/rust-lang/rust/issues/46314
- [x] #47053  (PR https://github.com/rust-lang/rust/pull/47425)
- [x] https://github.com/rust-lang/rust/issues/47366 (examples from [this comment])
- [x] https://github.com/rust-lang/rust/issues/29149 (fix in https://github.com/rust-lang/rust/pull/47877)
- [x] #16223 
- [x] #48238 (and specifically [this reduction](https://github.com/rust-lang/rust/issues/48238#issuecomment-366048269))
- [x] https://github.com/rust-lang/rust/issues/45157
- [x] https://github.com/rust-lang/rust/issues/46314 (hygiene interaction)
- [x] https://github.com/rust-lang/rust/issues/27868 -- evaluation order and operators
- [x] https://github.com/rust-lang/rust/issues/16223 -- incorrect partially moved value error check

## Procedure

- First, if you wish, add yourself to the [list of participants for the WG-compiler-nll working group](https://docs.google.com/spreadsheets/d/1vymoSTIzepS6PVidHJWsMOVl12aSXixMev0LBLKLykY/edit?usp=sharing).
    - This will help us to find people who might like to help later!
- Create a regression test in `src/test/ui/nll/`
    - The name can be `issue-XXX.rs`, though giving a more descriptive name is also good
    - The file should include a comment saying `// Regression test for #XXX` however to ease searching later
- This test should include the error from the bug along with the following header material:
    - Rust license
    - `#![feature(nll)]` at the top
    - comments like `//~ ERROR` for the errors, or whatever is needed for test harness to pass
- Run `./x.py test --stage 1 src/test/ui --test-args nll`, this will test all the nll tests (including yours)
- Presuming that passes, open a PR! Otherwise, stop in at the [WG-compiler-nll gitter channel](https://gitter.im/rust-impl-period/WG-compiler-nll)
    - Put `r? @nikomatsakis` in the PR summary

**Comment by chrisvittal** [comment]
I'll take this.

**Comment by nikomatsakis** [comment]
Added #45045 to the list.

**Comment by nikomatsakis** [comment]
This isn't meant to be closed but rather kept open as a record of the issues involved. =)

**Comment by nikomatsakis** [comment]
Added #46314 to the list

**Comment by nikomatsakis** [comment]
Added #47053, though I think that it will be handled in #47425

**Comment by nikomatsakis** [comment]
Added https://github.com/rust-lang/rust/issues/29723

**Comment by bobtwinkles** [comment]
Added #16223

**Comment by pnkfelix** [comment]
Added #46557

**Comment by acrrd** [comment]
I think the test for #48238 has been added in #49295
