### ISSUE TITLE
Tracking issue for LLVM 6 upgrade

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#47683]
An LLVM release candidate for 6.0.0 has been tagged, and despite [not having upgraded to LLVM 5](https://github.com/rust-lang/rust/issues/43370) we should start weeding out bugs for LLVM 6!

* https://github.com/alexcrichton/rust/tree/llvm-6
* https://github.com/alexcrichton/llvm/tree/rust-llvm-release-6-0-0
* https://github.com/alexcrichton/compiler-builtins/tree/llvm-60
* https://github.com/rust-lang/compiler-rt/tree/rust-llvm-release-6-0-0

test results:

* [Second Travis Run](https://travis-ci.org/rust-lang/rust/builds/333128237)
* [First Travis Run](https://travis-ci.org/rust-lang/rust/builds/332843472) 

Issues with no diagnosis/resolution

* None!

I'm sure this list will expand over time! I'll try to keep it updated.

Issues with a diagnosis/resolution that hasn't landed

* [x] i686 MSVC is showing a corrupt rlib when linking, something about archive writing changed maybe?
  * appears to be an [LLVM regression](https://bugs.llvm.org/show_bug.cgi?id=36096)
  * local hack reverting the line in that linked commit seems to fix the issue
* [x] Emscripten needs an upgrade 
  * hopefully obviated by https://github.com/rust-lang/rust/issues/46819

Fixed issues:

* [x] LLVM [removed `CodeModel::Default`](https://github.com/llvm-mirror/llvm/commit/9aafb854c), it's now optional - #47710
* [x] The `MIPS64` archive variant [was renamed](https://github.com/llvm-mirror/llvm/commit/f45adc29de8aa80ac22b28ab421a92aaced80a97) - #47710
* [x] `UnsafeAlgebra` support [has been refactored](https://github.com/llvm-mirror/llvm/commit/00e900afd) - #47710
* [x] Return value of `writeArchive` [has changed](https://github.com/llvm-mirror/llvm/commit/203c90ba) - #47710
* [x] wasm32-unknown is showing `DICompileUnit` assertions, we probably need to apply the same fix that ThinLTO has already. - #47710
* [x] wasm32's dlmalloc needs updating as an intrinsic changed (there's an llvm5 branch in the dlmalloc repo)
* [x] Sanitizers need updating as x86_64-gnu is failing (compiler-builtins has an llvm6 branch)
* [x] Our FreeBSD x86_64 image fails to compile LLVM 6 - #47710
* [x] Lingering [debuginfo failure](https://github.com/rust-lang/rust/issues/47611) affects LLVM 5 as well - #47688
* [x] Our FreeBSD i686 image fails to compile LLVM - for now [hack around this](https://github.com/alexcrichton/llvm/commit/346b7d61b8a1dffc083245470ddd3120deda78a1)
* [x] arm-android has weird [floating point failures](https://travis-ci.org/rust-lang/rust/jobs/332843476) that suggests a compiler-rt mismatch
  * looks like this isn't caused by LLVM updates, but rather https://github.com/rust-lang-nursery/compiler-builtins/pull/222
  * that'll get resolved by either backing it out or fixing it to land locally
  * fixed in https://github.com/rust-lang-nursery/compiler-builtins/pull/224
* [x] x86_64/i686 linux dist builders can't compile newer compiler-rt (sanitizers presumably)
  * [random hack to fix this](https://github.com/rust-lang/compiler-rt/commit/dfd960b5f1a1751b22738fa34fd27b583f4618db)

* [x] armhf-gnu has a few SIGSEGV in the test suite of run-fail, something about unwinding may be busted
  * appears to be an [LLVM regression](https://bugs.llvm.org/show_bug.cgi?id=36073)
  * fix proposed at https://reviews.llvm.org/D42509

PRs:

* [x] ~~[Initial pass for upgrading in-tree support for LLVM 6](https://github.com/rust-lang/rust/pull/47681)~~
* [x] [First round of compat](https://github.com/rust-lang/rust/pull/47710)
* [x] [Fix DW_OP_deref support](https://github.com/rust-lang/rust/pull/47688) (affects LLVM 5 as well)

**Comment by alexcrichton** [comment]
The [most recent Travis run](https://travis-ci.org/rust-lang/rust/builds/333128237) is now all green. I've manually tested on OSX locally and we're all good there, and we're also good on MinGW Windows. The last remaining bug is the MSVC archive regression. Still hunting that down.

**Comment by lilianmoraru** [comment]
@alexcrichton It seems that all the mark boxes should now be ticked?(PRs merged)
