### ISSUE TITLE
tracking issue for "chalkification"

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#48049]
This is a place holder for various refactorings going on in the trait system aimed, ultimately, at improving efficiency and correctness. Some of the key goals include lazy normalization, better caching, and removing many of the trait-related overflow errors. I plan to flesh out details better here as we go.

- [x] Remove the "leak check" in favor of "universes"
    - @sgrif plans to do this; a lot of it has been done [in an older branch](https://github.com/nikomatsakis/rust/tree/chalkify-universe)
    - The plan is in [this gist](https://gist.github.com/nikomatsakis/87822133b2d85ccac801e08bcb9702de).
    - The primary goal here is to get the code in place so we can do a crater run, since this is not an entirely backwards compatible change (though it fixes some soundness bugs).
- [x] Canonicalization + normalization query
    - @nikomatsakis is working on this presently, see #48411 
- [x] Integrate universes into canonicalization (https://github.com/rust-lang/rust/issues/48696)
- [ ] re-remove the leak-check, which has been re-added (#59490)
- [ ] implement lazy normalization (#60471)

**Comment by mark-i-m** [comment]
#48411 is done

**Comment by shepmaster** [comment]
For my own searchability, I'm adding the plain word chalk.

**Comment by tmandry** [comment]
See also the [WG-traits meeting doc](https://paper.dropbox.com/doc/WG-Traits-Planning-Meeting-oDfr6ct8xx63HSAOOmIZX#:uid=630015284221598814453156&h2=Current-status) which has been updated more recently.

**Comment by ebkalderon** [comment]
For reference, some substantial work on universes has recently been merged: rust-lang/rust#55517.

**Comment by mark-i-m** [comment]
What's left here? It looks like all the checkboxes are ticked.

**Comment by vi** [comment]
Until the question is answered, this tracking issue no longer tracks the issue.

**Comment by pnkfelix** [comment]
Until @nikomatsakis corrects me otherwise, I'm going to assume that #59490 blocks this and thus this tracking issue once again tracks the issue.

**Comment by syntacticsugarglider** [comment]
Now that #65232 is merged, what is the status of this issue? What's the effective status of #59490?

**Comment by nikomatsakis** [comment]
Hard to summarize. We're working on making an approachable roadmap and summary on the https://github.com/rust-lang/wg-traits repository, but it's not quite there yet.

**Comment by joshlf** [comment]
Ping for status 🙂  Very excited for this (especially for implied bounds)!

**Comment by tmandry** [comment]
I recently looked and as I recall, roughly ~60% of (ui) tests were passing with `-Zchalk`.

**Comment by pnkfelix** [comment]
Visiting for backlog bonanza.

@rustbot label: S-tracking-needs-summary

**Comment by jackh726** [comment]
Visiting for types triage. We feel like this issue doesn't buy us much. It feels like a general "things to make rustc behave like chalk", which is probably better tracked through individual issues + a project. We're currently pursuing a-mir-formality, which will have implications here anyways.
