### ISSUE TITLE
Tracking issue for RFC #2145: Type privacy and private-in-public lints 

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#48054]
This is a tracking issue for the RFC "Type privacy and private-in-public lints " (rust-lang/rfcs#2145).

**Steps:**

- [ ] Implement the RFC (cc @petrochenkov )
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- [] It's not fully clear if the restriction for associated type definitions required for
type privacy soundness, or it's just a workaround for a technical difficulty.

- [] Interactions between macros 2.0 and the notions of reachability / effective
visibility used for the lints are unclear.

**Comment by Aaron1011** [comment]
@petrochenkov: Oops - I didn't mean for that to un-assign you.

Is there a way to prevent these lints from becoming insta-stable? Would it make sense to put them behind a feature gate?

**Comment by Aaron1011** [comment]
Perhaps we could only fire the lints if an unstable compiler flag (maybe `-Z type-privacy-lints`) is passed? This would still make the lint names insta-stable, though.

**Comment by lygstate** [comment]
in core ffi
```
// The VaArgSafe trait needs to be used in public interfaces, however, the trait
// itself must not be allowed to be used outside this module. Allowing users to
// implement the trait for a new type (thereby allowing the va_arg intrinsic to
// be used on a new type) is likely to cause undefined behavior.
//
// FIXME(dlrobertson): In order to use the VaArgSafe trait in a public interface
// but also ensure it cannot be used elsewhere, the trait needs to be public
// within a private module. Once RFC 2145 has been implemented look into
// improving this.
mod sealed_trait {
    /// Trait which permits the allowed types to be used with [super::VaListImpl::arg].
    #[unstable(
        feature = "c_variadic",
        reason = "the `c_variadic` feature has not been properly tested on \
                  all supported platforms",
        issue = "44930"
    )]
    pub trait VaArgSafe {}
}

```
There is a fixme about `RFC 2145`, how to fixes that?

**Comment by petrochenkov** [comment]
@lygstate 
By implementing this RFC, I guess.
Until that workarounds like this sealed trait will need to be used.

**Comment by lygstate** [comment]
Where is the impl, the RFC is already accepted...

**Comment by yodaldevoid** [comment]
> Where is the impl, the RFC is already accepted...

An RFC being accepted just means the feature *can* be implemented, not that it *has* been implemented. It doesn't even mean that implementing it is a priority.

I believe there has been more discussion of this RFC over at #34537 as well as other issues that I can't seem to track down right now.

**Comment by nipunn1313** [comment]
Hello! I know y'all are busy, but I'm curious if there's an update, particularly on `unnameable_types` for Voldemort Types - which I'd love to see. I was actually a bit surprised to find that it wasn't included in the existing `private_in_public` lint.

Appreciate the work that y'all are doing, especially @petrochenkov who seems to have put in a lot of legwork.

**Comment by petrochenkov** [comment]
@nipunn1313 
The *tentative* plan is that @Bryanskiy will work on this in March-May.

**Comment by nipunn1313** [comment]
> @nipunn1313 The _tentative_ plan is that @Bryanskiy will work on this in March-May.

Cool! Good luck! I'm happy to be a guinea pig to try it out or do code review if that would be helpful.

**Comment by petrochenkov** [comment]
This issue should be closed by https://github.com/rust-lang/rust/pull/120144.

Two follow up issues about improving the effective visibility tables
- https://github.com/rust-lang/rust/issues/120146
- https://github.com/rust-lang/rust/issues/120149
