### ISSUE TITLE
Tracking issue for moving to rustc-guide

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rust#48478]
The [rustc guide] has made a lot of progress and has almost reached parity with the READMEs. Indeed, there is a lot of content that is _only_ in the guide!

This is a tracking issue for completely getting rid of the READMEs, which are hard to find and often not coordinated with each other, and moving towards the guide.

- [x] Finish moving all READMEs to the guide. These are the ones that are left (I think):
    - EDIT: to reduce redundancy: https://github.com/rust-lang-nursery/rustc-guide/issues/
- [x] Remove old READMEs that are not waiting for a system to be deleted:
    - [x] Dependency tracking/Incr. Compl.: https://github.com/rust-lang/rust/blob/master/src/librustc/dep_graph/README.md (#49092)
    - [x] ./src/librustc/infer/higher_ranked/README.md (#57652)
    - [x]  ./src/librustc_data_structures/obligation_forest/README.md (#57652)
         - Put this info into the rustdocs
- [ ] In https://github.com/rust-lang/rust/pull/57652#issuecomment-455668837, it was decided that these READMEs are still accurate and are waiting for their corresponding systems to be removed...
    - [ ] ./src/librustc_borrowck/borrowck/README.md (#65772)
    - [x] ./src/librustc/infer/region_constraints/README.md
    - [ ]  ./src/librustc/infer/lexical_region_resolve/README.md (#65772)
- [x] Decide where we want the rustc guide to live (in this repo or not?), then move it there.
    - It is a submodule to this repo, with the main rusct-guide repo living in rust-lang/rustc-guide

[rustc guide]: https://github.com/rust-lang-nursery/rustc-guide

cc @nikomatsakis

**Comment by nikomatsakis** [comment]
Nice!

**Comment by mark-i-m** [comment]
Found a few more READMEs to migrate...

**Comment by mark-i-m** [comment]
Updated with next steps...

**Comment by mark-i-m** [comment]
Updated after #57652
