### ISSUE TITLE
Tracking issue for RFC 2203, "Constants in array repeat expressions"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#49147]
This is a tracking issue for the RFC "Constants in array repeat expressions" (rust-lang/rfcs#2203) (feature gate: `const_in_array_repeat_expressions`).

**Steps:**

- [x] Implement the RFC (cc @rust-lang/compiler -- can anyone write up mentoring instructions?)
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Implementation history:**

* Initial implementation: https://github.com/rust-lang/rust/pull/61749
* (this is incomplete)

**Unresolved questions:**

* Should we treat this as an [explicit promotion context](https://github.com/rust-lang/const-eval/blob/master/promotion.md#implicit-and-explicit-contexts)? That would allow calling arbitrary `const fn`, but poses the risk of breaking code that would otherwise work fine if we decide to promote when it would not have been necessary. The alternative is to rely on inline const expressions instead (https://github.com/rust-lang/rust/issues/76001).
* Should we maybe not perform any promotion at all, and instead require a named const, literal, or explicit `const {}` block for the repeat expression?

**Comment by eddyb** [comment]
See https://github.com/rust-lang/rfcs/pull/2203#issuecomment-360828613 - I don't think we should implement this before the MIR borrowck becomes the default - while it may be possible, it's getting increasingly risky to do such things.
cc @nikomatsakis

**Comment by eddyb** [comment]
So I just realized that "constant" has been a red herring all along for this problem:
What const-checking has is "value-based reasoning", that is, a value like `None::<T>` contains no values of `T`, so `T`'s properties (like `Drop` or the presence of interior mutability) do *not* apply to it.

For `[expr; n]` where we don't know that `n <= 1`, we've always required `typeof(expr): Copy`.
The accepted RFC would allow *another option* which is `SomeFormOfConstant(expr)`.
*However*, this isn't as general as it could be and it doesn't tie into the `Copy` condition very well.

One example of a *runtime* repeated expression we could allow is `[Ok::<i32, String>(rand()); n]`.
Or to expand it a bit, `{ let x = rand(); [Ok::<i32, String>(x); n] }` - this is "obviously fine" because the user could write `n` of `Ok(x)`, so *inline* ADT construction is always "inherently copyable".

I propose (a bit late) that we consider a *value (dataflow) analysis*, `Copyable(expr)`, which works similar to the current value analyses used in const-checking, effectively "recursing" on ADT constructors, and using the following two rules when reaching leaves `x` of unknown values:
* `typeof(x): Copy` (the set of types currently allowed in `[x; n`])
* `x` is *already* a constant (by naming a constant or through the *pre-existing* promotion)

Another advantage of this is that *it's not limited to `[expr; n]`*: *any* copy could be satisfied through it!

cc @nikomatsakis @RalfJung

**Comment by RalfJung** [comment]
> So I just realized that "constant" has been a red herring all along for this problem:
What const-checking has is "value-based reasoning", that is, a value like None::<T> contains no values of T, so T's properties (like Drop or the presence of interior mutability) do not apply to it.

Trying to recast what you are saying in my terms, we have `Copy` and "needs drop" as properties of *types*, but in fact these are properties of *values*. `T: Copy` merely says that all values of type `T` are copy. And a value is `Copy` if it can be duplicated because it doesn't have any ownership in it. Most of the time we only care about the type-level `Copy` because that's all the compiler knows, but e.g. the `None` value of type `Option<T>` is `Copy` for any `T`. Is that what you are saying?

I think that's a remark I already made somewhere else earlier this year but I have no idea where.^^

**Comment by nikomatsakis** [comment]
@eddyb hmm, interesting thought. So this is basically "doubling down" on the value-based reasoning we use for consts, and applying it here as well? I don't entirely hate that, particularly if we can kind of "reuse" the *form* of the rule from consts exactly.

**Comment by runelabs** [comment]
I ran into the following constraints with trying to use _primitive array repeat_ in `struct` initialization. It seems there is no way to make a RHS expression expressing the default value `None` of an `Option` for `[x; n]`.
I read the previous open issues on type ascription, but with `default()` for `Option` it would be nice to just be able to easily use the default `None` value for repetition. I am using this for a `no_std` crate.
```
enum Wrap { ... }
struct MyStruct<'a> {
  arr: &'a mut [Option<Wrap>]
}
let mut mystruct0 = MyStruct{ arr: &mut [] }; // works fine

// all fine, Copy-trait not needed (*1)
let mut empty1: [Option<Wrap>;11] = Default::default();
let mut mystruct1 = MyStruct{ arr: &mut empty1 };

// need type ascription, Copy-trait for Wrap
let mut empty2 = [Default::default();11]:[Option<Wrap>;11]; // (*2)
let mut empty3 = [Option::default();11]:[Option<Wrap>;11]; // (*3)
let mut mystruct2 = MyStruct{ arr: &mut ([Default::default();11]:[Option<Wrap>;11]) }; // (*4) , also parens expr

// need Copy-trait for Wrap
let mut mystruct3 = MyStruct{ arr: &mut [Default::default();11] }; // (*5)
```

All the cases from (*1) to (*5) try to accomplish similar initialization. Ideally, shouldn't they all work similarly?
I really want to use (*5) and not (*1).

**Comment by eddyb** [comment]
`<T>::foo` is "type-qualified path" syntax, which `T::foo` is a shorthand for (if `T` is *not* a trait).
Usually only `foo::<T>` is referred to as turbofish, the former would be more "reverse turbofish".

**Comment by eddyb** [comment]
Is the `S-blocked` label the right way to do this? I kind of want a "needs NLL" but not "fixed by NLL" label (cc @nikomatsakis).

**Comment by pnkfelix** [comment]
@eddyb hmm maybe we could/should just rename "fixed by NLL" to "needs NLL", which is ... strictly more general?

(Or is that label not a true generalization? I'm still musing over the english semantics here. I guess "fixed by NLL" implies that NLL is sufficient but not (necessarily) necessary, while "needs NLL" implies NLL is necessary but not (necessarily) sufficient...)
  * I can't believe just wrote "necessarily necessary"

**Comment by Centril** [comment]
Discussed briefly on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/subject/.2349147-const-array-repeat) -- would we want to *experiment* with this on 2018 only to begin with?

**Comment by eddyb** [comment]
I left a comment elsewhere, I think it would be fine if this were restricted to Rust 2018: https://github.com/rust-lang/rust/issues/54542#issuecomment-478261027

**Comment by Centril** [comment]
cc @pnkfelix, @eddyb, @oli-obk, and possibly more people: Should we call this unblocked now and start on an implementation? I think it would be good to avoid too much pressure to stabilize `uninitialized_array!` and do the principled fix (this feature). :)

**Comment by eddyb** [comment]
Ignoring the more powerful idea in https://github.com/rust-lang/rust/issues/49147#issuecomment-392256983, these are some mentoring notes:

1. wrap this in `if tcx.borrowck_mode() == BorrowckMode::Mir`:
https://github.com/rust-lang/rust/blob/1cc822c261f5c94a41eb725755fdda7ca6efbda2/src/librustc_typeck/check/mod.rs#L4433-L4439
Note that this should *not* break anything, as NLL borrowck has its own check (see 2.)
2. wrap this in `if let Operand::Move(_) = operand`:
https://github.com/rust-lang/rust/blob/1cc822c261f5c94a41eb725755fdda7ca6efbda2/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L1947-L1958
Note that `Operand::Copy` has its own check elsewhere and `Operand::Constant` is effectively copyable anyway, if it can even appear in this position - just to be sure, you can add this test (which currently errors):
```rust
// Doesn't implement `Copy`.
struct Foo;
const FOO: Foo = Foo;
fn main() {
    let _five_foos = [FOO; 5];
}
```
3. promote `Rvalue::Repeat` operands, just like `#[rustc_args_required_const]` arguments:
https://github.com/rust-lang/rust/blob/1cc822c261f5c94a41eb725755fdda7ca6efbda2/src/librustc_mir/transform/promote_consts.rs#L63-L68
What you'd need to add here is a `Repeat(Location)` variant (or generalize `Ref` to `Rvalue`).
https://github.com/rust-lang/rust/blob/1cc822c261f5c94a41eb725755fdda7ca6efbda2/src/librustc_mir/transform/qualify_consts.rs#L1104
This needs to become:
```rust
Rvalue::Repeat(operand, _) => {
    let candidate = Candidate::Repeat(location);
    if !IsNotImplicitlyPromotable::in_operand(self, operand) {
        debug!("visit_rvalue: candidate={:?}", candidate);
        self.promotion_candidates.push(candidate);
    }
}
```
And finally, where the actual promotion happens:
https://github.com/rust-lang/rust/blob/1cc822c261f5c94a41eb725755fdda7ca6efbda2/src/librustc_mir/transform/promote_consts.rs#L305
This needs to handle `Candidate::Repeat` by getting the statement like `Candidate::Ref` does, but replacing the `Operand` like `Candidate::Argument` does.

**Comment by eddyb** [comment]
I want to treat `Rvalue::Repeat(operand, n)` where `n > 1` as consuming `operand` more than once, which would remove the need for the explicit check, *but* that would degrade error messages, unless we do something similar to loops where we say "moved out on the previous loop iteration".

**Comment by davidtwco** [comment]
I'll give implementing this a go.

**Comment by bstrie** [comment]
> Another advantage of this is that it's not limited to [expr; n]: any copy could be satisfied through it!

Could this be used to at last return the `@` pattern to glory by making things like `x @ (y @ (1, 2), 3)` possible again? IIRC, advanced uses of `@` like this were disabled for 1.0 due to uncertainty regarding copyability.

**Comment by eddyb** [comment]
@bstrie Irrelevant, IMO. `@` was intentionally crippled because of the old borrowck.
With the MIR/NLL borrowck we should be able to just allow it, and any kind of move/borrow conflict between the two sides of `@` should be correctly detected.

**Comment by RalfJung** [comment]
@oli-obk @eddyb I just realized that this feature has one "interesting" consequence... the code in an array repeat expression might now be executed at compile-time, using CTFE rules and restrictions, without an explicit marker. We are having lots of pain with promotion because it imposes CTFE rules on code where the user did not ask for CTFE rules, won't we have all the same pain here?

**Comment by RalfJung** [comment]
Ah, turns out this actually uses the promotion infrastructure, so we the concern that we "silently" execute code under CTFE is taken care of.

Of course, the problem with this is that this is using the promotion infrastructure, which we are trying hard to contain because it's a hazard...

**Comment by leonardo-m** [comment]
Interesting differences:

    #![allow(dead_code)]
    fn main() {
        //const ARR1: [Option<Box<u32>>; 100] = [None; 100]; // Error
        const ARR2: [Option<u32>; 100]      = [None; 100];   // OK
        const X: Option<Box<u32>>           = None;
        const ARR3: [Option<Box<u32>>; 100] = [X; 100];      // OK
    }

**Comment by abonander** [comment]
@RalfJung do we _need_ the same promotion logic? It seems to me that we can have two mutually exclusive situations:

* The element type is `Copy`, thus the expression does not need to be const but is only executed once
* The element type is not `Copy` thus the expression _must_ be `const` and thus cannot be observed executing more than once anyway

**Comment by eddyb** [comment]
@abonander Ah, yeah, I forgot that part. So if the expression is `Copy` *do not attempt* promotion, meaning only code which *needs* promotion to compile will evaluate the expression at compile-time, which even if it errors in miri, it couldn't have compiled *any other way*.

This is in contrast with `&expr` promotion, which *should never* be attempted *unless* we're certain it can't fail, because the code will likely compile without promotion.

**Comment by RalfJung** [comment]
I am not convinced by that argument. It is still very non-obvious to the user of the code *needs* promotion. In particular, in generic code it could be that if the involved types were fully known, no promotion would be needed, but due to the generic nature of this code promotion happened anyway.

I think we need a clear syntactic marker for promotion, including in array length. Something like `const { expr }`, or something else specialized for array lengths, but *something*.

**Comment by oli-obk** [comment]
Even in generics everything is obvious. Either you have a `Copy` bound, or you get promotion. I think not being a full const context will confuse more than it will not. We'll just get requests to add more things or at least issues opened asking why things that are obv OK don't work

**Comment by abonander** [comment]
I think as long as we somehow clearly communicate that the idea is to not have side-effect that are dependent on the length of the array, I think the intuition that the initializer either needs `Copy` or needs to be a constexpr falls out of that. We can do this easily in error messages:

```
error[E###]: array initializers may not have length-dependent side-effects
 --> src/main.rs:2:23
  |
2 |     let mut strings = [String::with_capacity(32); 16];
  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `String` is not `Copy` nor is `String::with_capacity(32)` a const-expression
  |
  = note: the element type must either be copyable or the initializer expression must be const so as to not have length-dependent side-effects
```

**Comment by abonander** [comment]
And I'm pushing this point because I'm _assuming_ that's the reason array initializers cannot have variable side-effects because that's what it looks like to me. The reference doesn't specify the motivation. 

Does it also/instead have to do with not being able to report panics that occurred in the middle of initialization? That is, if any arbitrary expression was allowed and was run for every element at the array, e.g. if `[may_panic(); 8]` panics at element 6, we have no way to clearly report that.

**Comment by RalfJung** [comment]
@abonander the problem is not code that syntactically wouldn't be allowed in CTFE. The problem is code that *goes wrong* when doing CTFE -- either because it caused UB, or (more interestingly) because it is "unconst", meaning it would be safe at run-time but is not safe at compile-time.

We will, of course, have a proper diagnostic telling the user what went wrong when const-evaluating their code. And I think given that the alternative is to not even try and compile this, that seems like a reasonable choice. We should just make sure that the error specifically for array initializers specifically mentions that this all only happened because the type is not `Copy`.

**Comment by RalfJung** [comment]
Do we have a good name for the code that we run at const-time without the user asking for it? I used to talk about that as "promotion", but I think @eddyb calls other things promoted. I am talking specifically about the code that obeys `#[rustc_promotable]`, the code where *if* CTFE fails we screwed up because we should have just let that code run at run-time.

"implicitly promoted", maybe? Crucially, the following is a similar mechanism but it *not* that same kind of code:
```
const BAR: &'static i32 = &5;
const FOO: Option<&'static i32> = Some(&5);
```

**Comment by eddyb** [comment]
@RalfJung `&expr` is affected by "implicit promotion (to `'static`)" but `const X: &T = &expr;` (and some amount of nesting) follows the same "temporary scope" rules `let x: &T = &expr;` does (but for `const`, the "surrounding scope" is `'static`).

What works for `const X: &T = &expr;` and doesn't when `&expr` is sufficiently nested in the RHS of the `const` (e.g. `const X: &T = { let tmp = &expr; tmp };`) is "needs drop" types.

That is, `const EMPTY_BYTES: &Vec<u8> = &Vec::new();` works even if `&Vec::new()` in general won't be promoted: the difference in "temporary scope" means *there was never* any intention to drop the `Vec`, so there's nothing to promote or error on.

But `const FOO: &Vec<u8> = id(&Vec::new());` doesn't work because `id` *could* be the identity function, but could just as well only read from its argument and then return something unrelated - just like a runtime function could do.

This distinction lets us allow some leaking-to-`'static` in the language itself (some of that was needed for backcompat, and the rest will be useful as CTFE gets more powerful) while keeping the runtime semantics for the general case (but this is kinda offtopic already).

**Comment by RalfJung** [comment]
@eddyb points out that the current implementation does not work in static/const bodies. This fails:
```rust
#![feature(const_in_array_repeat_expressions)]
static FOO: i32 = {
    let x: [Option<Vec<i32>>; 5] = [None; 5];
    5
};
```

**Comment by scottmcm** [comment]
I'm concerned about semver implications here.  It seems like it would be bad if adding `Copy` to the type returned from `foo` could change what happens in things like `[foo(); 4]`.

**Comment by cramertj** [comment]
@scottmcm FWIW adding `Copy` to a type can already change significant behaviors and can actually break compilation because of how move inference for closures works.

**Comment by josephlr** [comment]
As @RalfJung mentioned in https://github.com/rust-lang/rust/issues/77138#issuecomment-698159728, the following code currently doesn't work with this feature flag:
```rust
#![feature(const_in_array_repeat_expressions)]
struct T;
impl T {
    const fn new() -> Self {
        Self
    }
}

const fn bar() -> [T; 2] {
    [T::new(); 2]
}
```

This is due to changes make around promotion rules in `const fn` (to make them more like `fn`). To fix this, there will need to be explicit constant promotion rules for array initializers.

**Comment by oli-obk** [comment]
> To fix this, there will need to be explicit constant promotion rules for array initializers.

Note that there's mostly aggreement (I think?) on the decision to *not* use explicit const promotion, but to just require `const { T::new() }` blocks

**Comment by josephlr** [comment]
> > To fix this, there will need to be explicit constant promotion rules for array initializers.
> 
> Note that there's mostly aggreement (I think?) on the decision to _not_ use explicit const promotion, but to just require `const { T::new() }` blocks

So this means the implementation becomes:

```rust
const fn bar() -> [T; 2] {
    const C: T = T::new();
    [C; 2]
}
```

Is that the desired way to write this?

**Comment by RalfJung** [comment]
The plan is that eventually, you can write `[const { T::new() }; 2]`. This is tracked at https://github.com/rust-lang/rust/issues/76001.

Until that is implemented, what you wrote is basically the manual desugaring of the above.

**Comment by RalfJung** [comment]
Unfortunately that desugaring does not work in a generic function... here's an alternative that works:
```rust
trait MakeVec: Sized { const EMPTY: Vec<Self>; }

impl<T> MakeVec for T {
    const EMPTY: Vec<T> = Vec::new();
}

const fn bar<T>() -> [Vec<T>; 2] {
    [<T as MakeVec>::EMPTY; 2]
}
```
This also shows why we need `const` blocks to support depending on generic parameters.

**Comment by RalfJung** [comment]
Turns out that [accidentally, part of this feature is already stable](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fbfad6fa9979c1696a25b82c62b20091).^^ From what I have seen so far, this only affects literal constants in array repeat expressions, which is fairly uncontroversial... but still entirely unintended.

We should at least figure out the code that enabled this to determine what exactly has been stabilized.

**Comment by RalfJung** [comment]
I think this is the problem:

https://github.com/rust-lang/rust/blob/2c4df6bb343e89c382ae2301505013132af77319/compiler/rustc_mir/src/borrow_check/type_check/mod.rs#L1987

In case of `Operand::Copy`, no check whatsoever is performed.

**Comment by oli-obk** [comment]
`Operand::Copy` is totally fine, because that is only valid for `Copy` types https://github.com/rust-lang/rust/blob/a1f7ca788d28f8df9ccd161137c3429be1ed9d0e/compiler/rustc_mir/src/transform/validate.rs#L205 the situation here is that we forgot that there's also `Operand::Constant`. The check should have never looked at the `Operand` but simply invoked [`Operand::ty`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/enum.Operand.html#method.ty).

I agree that this is a benign accidental stabilization, we should still officially stabilize it. I don't think spending effort on reverting the accidental stabilization is worth it in this case.

**Comment by RalfJung** [comment]
> I agree that this is a benign accidental stabilization, we should still officially stabilize it. I don't think spending effort on reverting the accidental stabilization is worth it in this case.

You mean, make a PR that switches to `Operand::ty` but allows constants, add tests, and FCP that?

**Comment by oli-obk** [comment]
There's no need to change the source, it does exactly what we would stabilize. So just a PR that adds tests and then FCP that.

Though I guess the implementation is a bit roundabout, so we could switch to checking the operand ty first and then checking for `Operand::Constant` if that check fails. But other than readability, that won't change anything.

**Comment by RalfJung** [comment]
I think the `if let` should be changed to a `match` to require explicit handling of all cases.

**Comment by nikomatsakis** [comment]
+1 to match

**Comment by oli-obk** [comment]
Marking as E-easy for just the match + tests "stabilization" PR

**Comment by RalfJung** [comment]
> the match + tests "stabilization" PR

Here you go: https://github.com/rust-lang/rust/pull/79270

**Comment by RalfJung** [comment]
As part of https://github.com/rust-lang/rust/pull/79270, I noticed there is an interesting open question around destructors. If we assume `N != 0`, we currently have that `[CONST; N]` calls the destructor exactly `N` times (if there is one). But at the same time we have that `[non_const_expr; N]` calls the destructor exactly once (if there is one).

With `N == 0`, we cannot match both of these patterns. I feel it makes more sense to remain consistent within `[CONST; N]`, but this show that using the same syntax for two very different operations ("create an array from a runtime value" vs "create an array from a constant") causes some friction. However, AFAIK promotion will refuse to act for values that need dropping, so right now this should be fine (except for the case being stabilized in https://github.com/rust-lang/rust/pull/79270 which does not even go through promotion).

**Comment by bstrie** [comment]
> But at the same time we have that [non_const_expr; N] calls the destructor exactly once (if there is one).
>
> With N == 0, we cannot match both of these patterns.

@RalfJung , frankly it's news to me that we even allow `[expr; 1]` for `Drop` types, let alone `[expr; 0]`, but it doesn't appear to be the case that a zero-length array will call a destructor:

```rust
fn main() {
    let _ = [foo(); 1]; // prints 42 when dropped
    let _ = [foo(); 0]; // prints nothing
}

struct Foo { f: u32 }

impl Drop for Foo {
    fn drop(&mut self) {
        println!("{}", self.f);
    }
}

fn foo() -> Foo {
    Foo { f: 42 }
}
```

Am I interpreting your statement wrong?

**Comment by Nemo157** [comment]
@bstrie that's an existing bug in the array-from-local syntax: https://github.com/rust-lang/rust/issues/74836

**Comment by RalfJung** [comment]
> frankly it's news to me that we even allow [expr; 1] for Drop types, let alone [expr; 0]

Yeah I also only learned this earlier this year and was as surprised as you are.^^

And indeed I forgot to mention that what I described for `[runtime_expr; N]` is the *intended* behavior, not the behavior currently implemented.

**Comment by bstrie** [comment]
Has anyone considered an RFC that would cause warn-by-default on `[runtime_expr; 0]` for `Drop` types? I doubt this is something that 99.99% of Rust devs even realize is possible. Not even macro authors would miss it, since this doesn't generalize to sizes other than 0 and 1. The preferred way of creating zero-size arrays is unambiguously via `[]`; the only possible use for `[foo; 0]` appears to be an unidiomatic hack around the lack of type ascription.

**Comment by RalfJung** [comment]
@bstrie This sounds like a discussion for https://github.com/rust-lang/rust/issues/74836. Let's keep this issue about consts in array repeat expressions.

**Comment by bstrie** [comment]
> However, AFAIK promotion will refuse to act for values that need dropping, so right now this should be fine

@RalfJung , perhaps this is simply another instance of describing behavior as it should be rather than as it currently is, but the following program does compile and run the destructor twice when used with `#![feature(const_in_array_repeat_expressions)]`.

```rust
struct Foo;

impl Drop for Foo {
    fn drop(&mut self) {
        println!("dropped")
    }
}

fn main() {
    let _ = [Foo; 2];
}
```

Since this would ordinarily be a compile-time error, this is an example of implicit const promotion, yes?

**Comment by Nemo157** [comment]
`struct Foo;` can in a lot of ways be considered to be equivalent to:

```rust
struct Foo {}
const Foo: Foo = Foo {};
```

what's more surprising to me is that constructor syntax is also treated as a const by `const_in_array_repeat_expressions`:

```rust
struct Foo {};

impl Drop for Foo {
    fn drop(&mut self) {
        println!("dropped")
    }
}

fn main() {
    let _ = [Foo {}; 2];
}
```

**Comment by RalfJung** [comment]
Hm, good question, but I think @Nemo157 is right -- 0-ary constructors are represented as `Operand::Const` in MIR, so they are treated the same as `const`. @oli-obk is that right?

**Comment by oli-obk** [comment]
Since neither of these compile without the feature gate, it must be promotion and not a 0-ary special representation. That's just what you see after const prop runs, which does not affect promotion.

**Comment by RalfJung** [comment]
Oh, so the rule that we do not promote things that need dropping does not apply to array repeat expressions, but only to lifetime extension?

**Comment by oli-obk** [comment]
Oh... I didn't think about that. That's weird, but I found out where it happens: https://github.com/rust-lang/rust/blob/c4926d01ada661d4fbffb0e5b1708ae5463d47b3/compiler/rustc_mir/src/transform/promote_consts.rs#L361 only runs for the lifetime extension. The same with interior mutability and derefs... and mutable references!?!

**Comment by RalfJung** [comment]
Mutable references and interior mutability are also checked here:

https://github.com/rust-lang/rust/blob/c4926d01ada661d4fbffb0e5b1708ae5463d47b3/compiler/rustc_mir/src/transform/promote_consts.rs#L667

And deref here:

https://github.com/rust-lang/rust/blob/c4926d01ada661d4fbffb0e5b1708ae5463d47b3/compiler/rustc_mir/src/transform/promote_consts.rs#L502

Lifetime extension is special in that, if I understood correctly, given `&EXPR.proj1.proj2`, it actually promotes `EXPR` and then performs runtime projections. That's why it has its own look at the involved projections.

---

But `NeedsDrop` is not checked anywhere else. I am wondering, does it need to? Array repeat expressions use the const by-value, so *except possibly for `[expr; 0]`*, the same drops happen at the same time whether or not promotion is involved. Still, this is in direct contradiction to our docs which say that things that need dropping are never promoted (implicitly or otherwise).

**Comment by oli-obk** [comment]
> But `NeedsDrop` is not checked anywhere else. I am wondering, does it need to? Array repeat expressions use the const by-value, so _except possibly for `[expr; 0]`_, the same drops happen at the same time whether or not promotion is involved. Still, this is in direct contradiction to our docs which say that things that need dropping are never promoted (implicitly or otherwise).

Right, we'd have to adjust the docs to reflect the reality of this feature gate, if we still want this feature at all. We would have fewer special cases if we never implemented it and just suggested `const` blocks instead (which will automatically work, since the promotion code will just see a single constant, just like with explicit constants)

**Comment by RalfJung** [comment]
Still, it seems strange that `validate_operand` or `validate_local` does not check `NeedsDrop`.

**Comment by oli-obk** [comment]
It must be checking drops somewhere, otherwise https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7438680b64dbd44dd0988fbba1888d2d would not error. The drop check I linked is just for the final expression

**Comment by RalfJung** [comment]
That errors because `drop` is a function call that does not get promoted.

**Comment by RalfJung** [comment]
@oli-obk so, what do we do about the dropping thing? `[expr; 0]` behaves differently depending on whether `expr` got promoted or not when the final value of `expr` needs dropping. So I think something in promotion analysis needs to reject things that need dropping. But I have no idea where the best place is to put that check -- in `Candidate::Repeat`, or should we rather have it in `validate_local` or so?

**Comment by oli-obk** [comment]
I'm still unsure we should do this at all (as mentioned [earlier](https://github.com/rust-lang/rust/issues/49147#issuecomment-736441091)). I would rather make a decision on that first before putting in more effort

**Comment by RalfJung** [comment]
You mean, supporting only `Operand::Const`, i.e., const literals and const blocks, and no promotion at all? Yeah that would of course also work.

**Comment by oli-obk** [comment]
Yes, that is what I mean. It would simplify a lot, and iirc that was always on the table.

**Comment by tmiasko** [comment]
Not checking for drop has an additional effect that enabling this feature gate changes the semantics of programs that already compile successfully:

```rust
//#![feature(const_in_array_repeat_expressions)]

struct S(&'static str);

impl Drop for S {
    fn drop(&mut self) {
        println!("{}", self.0);
    }
}

fn main() {
    // S is dropped or not depending on the feature gate.
    [&S("a"); 4];
}
```

**Comment by RalfJung** [comment]
@tmiasko ouch...

I am more and more convinced we should do what @oli-obk suggested: remove `const_in_array_repeat_expressions` and the corresponding code in promotion, and rely on `const` blocks instead.

**Comment by tesuji** [comment]
The feature `const_in_array_repeat_expressions` was removed in #80404.
Should this issue be closed or be replaced with something else ?

**Comment by oli-obk** [comment]
Ah good catch :D yea, this issue should be closed.

We removed this feature without replacement as the feature was extremely buggy and problematic and in the future we'll be able to use the `inline_const` feature to get the same behaviour albeit at a slight increase in verbosity.

**Comment by SimonSapin** [comment]
Should the accepted RFC be marked as "retracted" or something?

**Comment by scottmcm** [comment]
@SimonSapin Good call.  I'll make a quick RFCs-PR and bring it up in the lang meeting tomorrow.

**Comment by bluss** [comment]
MaybeUninit::uninit_array's docs still link to this as a "future feature", seems like that mention should be removed
