### ISSUE TITLE
🛠 Extend the "chalk lowering" pass with remaining rules

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#49177]
Now that @scalexm has created the [basic framework for lowering][], we need to flesh it out. This issue is intentionally structured as a "quest isuse" -- that is, a way for a lot of people to contribute, each doing one small thing. The goal is for everyone to get familiar with the overall "chalk" setup.

[basic framework for lowering]: https://github.com/rust-lang/rust/pull/48985

### The tasks

Each task corresponds to one of the rules [documented in the rustc-guide][rg]. You can search the guide for the rule name in order to find some text explaining the rule. **If you want to do a rule, just check the box and edit this post to add your name** (if you are a member of the [GitHub team], you should have privileges for that).  If you are not yet a member of the WG-traits group, leave a comment below or [ping me on gitter][gitter] and I will add you.

[rg]: https://rust-lang-nursery.github.io/rustc-guide/traits/lowering-rules.html
[GitHub team]: https://github.com/orgs/rust-lang/teams/wg-traits/
[gitter]: https://gitter.im/rust-lang/WG-traits

- [x] Rule Implemented-From-Impl: this is the template rule that [@scalexm started with][ife].
- [x] Rule Implemented-From-Env -- @varkor (PR #49211)
- [x] Rule Implied-Bound-From-Trait -- @tmandry (PR #49435)
- [x] Rule WellFormed-TraitRef -- @csmoe (PR #50250)
- [x] Rule ProjectionEq-Normalize  -- @csmoe (PR #52153)
- [x] Rule ProjectionEq-Skolemize -- @scalexm (PR #54909)
- [x] Rule Normalize-From-Impl -- @fanzier (PR #49626)
- [ ] Rule Implied-Bound-From-AssocTy -- not needed until GATs
- [x] Rule WellFormed-AssocTy -- @scalexm (PR #54909)
- [ ] Rule Implied-WC-From-AssocTy -- not needed until GATs / where clauses on assoc types
- [x] Rule Implied-Trait-From-AssocTy -- @scalexm (PR ##54909)

[ife]: https://github.com/rust-lang/rust/blob/a04b88d1941644df01fa5e31dd43e0f57c13d938/src/librustc_traits/lowering.rs#L121-L130

### Mentoring instructions

As described above, the goal is to add the code to generate appropriate program clauses from various Rust constructs. You should use the `Implemented-From-Impl` rule as a kind of template:

https://github.com/rust-lang/rust/blob/a04b88d1941644df01fa5e31dd43e0f57c13d938/src/librustc_traits/lowering.rs#L121-L130

Each rule should also have a unit-test. This [rustc-guide chapter](https://github.com/rust-lang-nursery/rustc-guide/blob/master/src/traits-lowering-module.md) describes how to create such unit tests.

cc @rust-lang/wg-traits

**Comment by varkor** [comment]
I'll take `Rule Implemented-From-Env` to get my feet wet!

**Comment by tmandry** [comment]
Working on `Rule Implied-Bound-From-Trait`

**Comment by fanzier** [comment]
I'd like to try `Normalize-From-Impl` :) (Also, I think the rule `Implemented-From-Impl` occurs twice in the list.)

**Comment by nikomatsakis** [comment]
@fanzier great! Let me know how it goes. Feel free to pop in on [the gitter channel](https://gitter.im/rust-lang/WG-traits) with questions.

**Comment by bjorn3** [comment]
@nikomatsakis I believe some check boxes should be checked.

**Comment by bjorn3** [comment]
PR #52153 has been merged.

**Comment by camelid** [comment]
Closed by request of @jackh726.
