### ISSUE TITLE
Tracking issue for missing Iterator::size_hint implementations

### ISSUE THREAD

**Issue by Phlosioneer** [rust-lang/rust#49205]
`size_hint()` can sometimes allow for more efficient memory allocations, and other good performance things.

I intend to make a PR to implement the trivial / easy ones, at least. I've already made a PR for the first batch, #49201. The ones in that PR are omitted from this list.

Liballoc:
- [ ] [`Range<'a, K, V>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/liballoc/btree/map.rs#L1446)
- [ ] [`RangeMut<'a, K, V>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/liballoc/btree/map.rs#L1578)
- [ ] [`MergeIter<K, V, I>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/liballoc/btree/map.rs#L2503)
- [ ] [`Range<'a, T>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/liballoc/btree/set.rs#L2503)

Libcore:
- [ ] [`Pattern: $forward_iterator<'a, P>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libcore/str/mod.rs#L926)
- [ ] [`Pattern: $reverse_iterator<'a, P>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libcore/str/mod.rs#L960)

Libfmt_macros:
- [ ] [`Parser<'a>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libfmt_macros/lib.rs#L146)

Libproc_macro:
- [ ] [`TokenTreeIter`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libproc_macro/lib.rs#L561)

Librustc:
- [ ] [`NodesMatchingSuffix<'o, 'tcx>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc/hir/map/mod.rs#L1102)
- [ ] [`EnumerateAndAdjust<I>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc/hir/pat_util.rs#L26)
- [ ] [`TraitObligationStackList<'o, 'tcx>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc/traits/select.rs#3352)
- [ ] [`Ancestors`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc/traits/specialize/specialization_graph.rs#L334)
- [ ] [`Elaborator<'cx, 'gcx, 'tcx>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc/traits/util.rs#L239)
- [ ] [`SupertraitDefIds<'cx, 'gcx, 'tcx>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc/traits/util.rs#L296)
- [ ] [`TypeWalker<'tcx>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc/ty/walk.rs#L51)
- [ ] [`Iter<'dom, Node>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc_data_structures/control_flow_graph/dominators/mod.rs#L148)
- [ ] [`Iter<'a, T>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc_data_structures/indexed_set.rs#L235)
- [ ] [`Iter<'a>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc_llvm/archive_ro.rs#L90)
- [ ] [`Prefixes<'cx, 'gcx, 'tcx>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc_mir/borrow_check/prefixes.rs#L86)
- [ ] [`ValueIter`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc_trans/base.rs#L674)
- [ ] [`Autoderef<'a, 'gcx, 'tcx>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc_typecheck/check/autoderef.rs#L44)

Librustdoc:
- [ ] [`CodeBlocks<'a, I>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustdoc/html/markdown.rs#L139)
- [ ] [`LinkReplacer<'a, 'b, I>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustdoc/html/markdown.rs#L247)
- [ ] [`HeadingLinks<'a, 'b, I>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustdoc/html/markdown.rs#L282)
- [ ] [`SummaryLine<'a, I>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustdoc/html/markdown.rs#L339)
- [ ] [`Footnotes<'a, I>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustdoc/html/markdown.rs#L702)
- [ ] [`Parser<T>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libserialize/json.rs#L1424)

Libstd:
- fs
   - [ ] [`ReadDir`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/fs.rs#L1232)
- io
   - [ ] [`Bytes<R>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/io/mod.rs#L1989)
   - [ ] [`Chars<R>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/io/mod.rs#L2026)
   - [ ] [`Split<B>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/io/mod.rs#L2101)
- net
    - [ ] [`Lines<B>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/net/mod.rs#L146)
 - [ ] [`Incoming<'a>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/net/tcp.rs#L891)
- path
    - [ ] [`Iter<'a>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/path.rs#L894)
    - [ ] [`Components<'a>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/path.rs#L913)
    - [ ] [`Ancestors<'a>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/path.rs#L1067)
- sync
    - [ ] [`Iter<'a, T>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sync/mpsc/mod.rs#L1565)
    - [ ] [`TryIter<'a, T>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sync/mpsc/mod.rs#L1572)
    - [ ] [`IntoIter<T>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sync/mpsc/mod.rs#L1587)
    - [ ] [`Packets`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sync/mpsc/select.rs#L341)
- sys
    - cloudabi
        - [ ] [`ReadDir`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/cloudabi/shims/fs.rs#L147)
        - [ ] [`LookupHost`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/cloudabi/shims/net/mod.rs#L287)
        - [ ] [`SplitPaths<'a>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/cloudabi/shims/os.rs#L51)
    - redox
        - [ ] [`ReadDir`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/redox/fs.rs#L143)
        - [ ] [`LookupHost`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/redox/net/mod.rs#L34)
    - unix
        - [ ] [`ReadDir`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/unix/fs.rs#L214)
        - [ ] [`LookupHost`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/unix/l4re.rs#L427)
    - wasm
        - [ ] [`ReadDir`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/wasm/fs.rs#L149)
        - [ ] [`LookupHost`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/wasm/net.rs#L289)
        - [ ] [`SplitPaths<'a>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/wasm/os.rs#L41)
        - [ ] [`Env`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/wasm/os.rs#L75)
    - windows
        - [ ] [`ReadDir`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/windows/fs.rs#L94)
        - [ ] [`Env`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/windows/os.rs#L94)
        - [ ] [`SplitPaths<'a>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys/windows/os.rs#L156)
   - sys_common
       - [ ] [`LookupHost`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd/sys_common/net.rs#L134)
   - unicode
       - [ ] [`ToLowercase`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd_unicode/char.rs#L66)
       - [ ] [`ToUppercase`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd_unicode/char.rs#L88)
       - [ ] [`CaseMappingIter`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd_unicode/char.rs#L120)
       - [ ] [`Utf8LossyChunksIter<'a>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd_unicode/lossy.rs#L57)
       - [ ] [`SplitWhitespace<'a>`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libstd_unicode/u_str.rs#L173)

Libsyntax:
- [ ] [`Frame`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libsyntax/ext/tt/transcribe.rs#L49)
- [ ] [`Cursor`](https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/libsyntax/tokenstream.rs#L420)

Cargo:
Cross-posting soon.

Clippy:
Cross-posting soon.

Rustfmt:
Cross-posting soon.

I found them by running `grep -r -n "impl.*\bIterator for \|fn size_hint" src > size_hint_todo.txt`. Then, delete any pairs of an `Iterator` line followed by a `size_hint` line, and manually check the remaining `Iterator` lines for false positives.

It may be a good idea to make a lint for implementing size_hint. It would be opt-in, of course. It's really easy to forget, even if you're trying to optimize performance.
