### ISSUE TITLE
Tracking issue for RFC 2300, "`Self` in type definitions"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#49303]
This is a tracking issue for the RFC "`Self` in type definitions" (rust-lang/rfcs#2300).

**Steps:**

- [ ] Implement the RFC (cc @rust-lang/compiler -- can anyone write up mentoring instructions?)
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- [ ]  This syntax creates ambiguity if we ever permit types to be declared directly within impls (for example, as the value for an associated type). Do we ever want to support that, and if so, how should we resolve the ambiguity? **A** possible, interpretation and way to solve the ambiguity consistently is discussed in the rationale.

**Comment by csmoe** [comment]
I'll work on this.

**Comment by csmoe** [comment]
I'll work on this.

**Comment by Centril** [comment]
re-cc @rust-lang/compiler - could we get some mentoring instructions perhaps per @csmoe's request?

**Comment by alexreg** [comment]
Currently working on this...

**Comment by alexreg** [comment]
You can tick off "implemented" now. :-)

**Comment by Centril** [comment]
@rfcbot merge

# Stabilization report & proposal

Feature name: `#![feature(self_in_typedefs)]`
Version target: 1.32 (2019-01-18)

Originally accepted in https://github.com/rust-lang/rfcs/pull/2300, I propose that we stabilize `self_in_typedefs`.
This has been in nightly since 2018-08-19 which is ~12 weeks ago.

The proposed change is not a blocker for anyone but it is a nice quality of life feature in some cases.
See the [motivation](https://github.com/rust-lang/rfcs/blob/master/text/2300-self-in-typedefs.md#motivation) of the RFC for reasons why we would want to do this.

## What is being stabilized

Relevant artefacts:

- [Implementation](https://github.com/rust-lang/rust/pull/53324)
- [Unstable book](https://github.com/rust-lang/rust/blob/4e7d3f5a5eb9db95194cbb672f081c2ad9647674/src/doc/unstable-book/src/language-features/self-in-typedefs.md)
- [Feature gate](https://github.com/rust-lang/rust/blob/218189536d95c12d7abbe01af3725c84a628bc51/src/test/ui/feature-gates/feature-gate-self_in_typedefs.rs)
- [Main tests](https://github.com/rust-lang/rust/blob/6408162ea13446852cb45d9e781e64ba85ec7bb1/src/test/run-pass/self/self-in-typedefs.rs)

The changes are:

1. `Self` becomes a legal type in `struct`, `enum`, and `union` type definitions and refers to the typing being defined. `Self` is permitted both in fields and in `where` clauses; For example:

```rust
enum List<T>
where
    // In where clauses, both on the side of types being constrained and on the bounds side.
    Self: PartialOrd<Self>
{
    Nil,
    Cons(T, Box<Self>) // In fields. The usual rules re. infinite types apply.
}
```

## What is not being stabilized

Mentions of `Self` in `trait`, `type, and `existential type`s are not being stabilized here.

## Divergences from RFC

None

## Unresolved questions

There is currently one unresolved question, it reads as:

> This syntax creates ambiguity if we ever permit types to be declared directly within impls (for example, as the value for an associated type). Do we ever want to support that, and if so, how should we resolve the ambiguity? A possible, interpretation and way to solve the ambiguity consistently is discussed in the rationale.

At this point I believe that the discussion [in the RFC](https://github.com/rust-lang/rfcs/blob/master/text/2300-self-in-typedefs.md#the-consistency-of-what-self-refers-to) is sufficient and that there is no problem should we ever want to pursue the extension aforementioned.

Thus, I suggest that we resolve the question as a footnote that may have some value in the future but does not impact us now.

**Comment by petrochenkov** [comment]
I still feel that this brings some harm in terms of code readability/searchability and should be *generally* discouraged.

Additionally, interactions with https://github.com/rust-lang/rust/issues/51994 are not yet implemented and value `Self` inside of a struct does not refer to the struct's constructor.

**Comment by alexreg** [comment]
We allow it pretty much everywhere else. I don’t see a difference here.

**Comment by Centril** [comment]
@petrochenkov 

> I still feel that this brings some harm in terms of code readability/searchability and should be _generally_ discouraged.

I think searchability and readability are not the same thing; `Self` is less good generally for searchability if used in `impl`s or in type definitions; I don't think this is special to type definitions such that `impl`s don't have that problem.

However; when it comes to readability, given that we chose to have an implicit head parameter to traits in the form of `Self`, we might as well make the most of it and apply it uniformly. For me, `Self`, whether in type definitions, or when used as `-> Option<Self::Item>`, or elsewhere, removes a mental burden of checking whether the type being mentioned is the same as in the head. If I can read a type definition and see `Self` then a cognitive load has been lifted.

-------------

> 
> Additionally, interactions with #51994 are not yet implemented and value `Self` inside of a struct does not refer to the struct's constructor.

What interactions? Can you elaborate (because I don't recall there being any interactions)? Also please elaborate on "value `Self` inside of a struct...".

Before stabilizing, we might want to extend [the set of tests](https://github.com/rust-lang/rust/blob/6408162ea13446852cb45d9e781e64ba85ec7bb1/src/test/run-pass/self/self-in-typedefs.rs) to include:

```rust
struct Foo;

impl Foo {
    fn bar() {
        struct Baz(u8, Option<Box<Self>>);
        let cons: Option<Box<Baz>> = None;
        let _ = Baz(1, cons); // Make sure that `Self` refers to the right thing
    }
}
```

**Comment by petrochenkov** [comment]
>What interactions?

Well, you need something contrived to get it, but something like
```rust
struct S([u8; Self]);
```
should not result in the "cannot find value `Self` in this scope" error.

**Comment by Centril** [comment]
@petrochenkov Oh I see; so to make actual use of it you would need to write:

```rust
#![feature(self_struct_ctor)]
struct S([u8; weird(Self([]))]);
const fn weird(_: S) -> usize { 0 }
// This has a cycle I think
```

(enum discriminants or https://github.com/rust-lang/rfcs/pull/1806 might be more realistic use cases...)

--------------------

 I re-checked the RFC now and apparently [I wrote](https://github.com/rust-lang/rfcs/blob/master/text/2300-self-in-typedefs.md#reference-level-explanation):

> The identifier `Self` is (now) allowed in __*type contexts*__ in fields of `struct`s, `union`s, and the variants of `enum`s.

It explicitly says type contexts (and not value contexts), so going by the letter of the RFC, the implementation is correct and the error message should occur (tho it should be differently phrased, but I think we can improve diagnostics later for this pathological case...) I think we can probably revisit this later. :)

**Comment by alexreg** [comment]
[Stabilization PR](https://github.com/rust-lang/rust/pull/56366
) (for when FCP finishes, hopefully)

**Comment by alexreg** [comment]
@Centril I believe the reference is already up-to-date.
