### ISSUE TITLE
Tracking issue for implementing stack probe correctly

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#49355]
Stack guards are hard because it's different on every platform. [OpenJDK](https://github.com/dmlloyd/openjdk/search?utf8=%E2%9C%93&q=current_stack_base&type=) has a few kLOCs dedicated to correctly probing stack. Our detection is far from perfect, and we probably can use JVM's code as a reference documentation for all the Unixes.

Issues on widely used platforms:

- [ ] [Linux musl](https://github.com/rust-lang/rust/issues/31506)
- [ ] [macOS](https://github.com/rust-lang/rust/issues/43347)

Possibly related:

- [ ] [AArch64](https://github.com/rust-lang/rust/issues/48967) - #77071

Others:

- [ ] [Expanding support to non tier-1 platforms](https://github.com/rust-lang/rust/issues/43241)

**Comment by yaahc** [comment]
we reviewed this issue during todays libs-api meeting and determined that this tracking issue is effectively serving the same role as a label, and that we'd prefer to use a label for this, so I've gone ahead and introduced the `A-stack-probe` label and applied it to all the referenced issues
