### ISSUE TITLE
Expand the Rust Bookshelf 📚

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#49453]
In the Rust Documentation team meeting today, there was a discussion about bringing more books/docs into [the Rust Bookshelf](https://doc.rust-lang.org/nightly/#the-rust-bookshelf). We want to improve the discoverability for these other books and also provide Rust users with more non-introductory resources.

Here are some ideas:

- [ ] [Learning Rust With Entirely Too Many Linked Lists](https://github.com/rust-unofficial/too-many-lists)
- [ ] [The Rust FFI Omnibus](https://github.com/shepmaster/rust-ffi-omnibus)
- [ ] [The Little Book of Rust Macros](https://github.com/DanielKeep/tlborm/)
- [x] [The Embedded Rust Book](https://github.com/rust-lang-nursery/embedded-wg/issues/56)
  - status: not yet written
- [ ] [Rust API Guidelines](https://github.com/rust-lang/api-guidelines)
- [ ] [Asynchronous Programming in Rust](https://github.com/rust-lang/async-book)
  - status: work in progresss
- [ ] [Rust Cookbook](https://github.com/rust-lang-nursery/rust-cookbook)
- [x] [Rustc Guide](https://github.com/rust-lang-nursery/rustc-guide)
- [ ] [Rust WebAssembly](https://github.com/rust-lang-nursery/rust-wasm)
  - status: work in progress

*Note: this list is not exhaustive nor have any of these books been finalized as being added*

cc @rust-lang/docs

**Comment by tinaun** [comment]
any chance of moving the rendered rfc repo http://rust-lang.github.io/rfcs/ to the bookshelf? or at least linking it in more places. i think it would be useful alongside the unstable book

**Comment by steveklabnik** [comment]
Triage: rustc guide has been added; embedded book has a PR open.

**Comment by jonas-schievink** [comment]
Triage: Embedded book is now added. Since the docs team has been disbanded, what do we do with this issue?

**Comment by GuillaumeGomez** [comment]
We keep it? The work hasn't been done yet after all.

**Comment by steveklabnik** [comment]
I'm of two minds. Like yes, we want to add these books to the bookshelf. But is this issue actually going to help that goal? I'm not sure.

Anyway, TL;DR is that yes, we'd still like to do this and it's not done yet.

**Comment by 89z** [comment]
https://github.com/rust-lang/book/issues/858

https://github.com/rust-lang/rust/issues/49453
https://github.com/rust-lang/www.rust-lang.org/issues/1433
https://github.com/rust-lang/www.rust-lang.org/issues/418

**Comment by 89z** [comment]
Regarding the Cookbook, I have noticed that it is already being linked to in
certain places, for example:

- https://doc.rust-lang.org/rust-by-example/std_misc/arg.html
- https://docs.rs (hover over Rust)

**Comment by pnkfelix** [comment]
Visiting for T-compiler backlog bonanza.

This doesn't have a clear owner, either as a person nor as a team. The compiler team does not believe it to be a tracking issue in the usual sense. 

I am for now assigning it to T-lang, under the philosophy that they are closest to making decisions about how people using Rust interface with it. But I would be fine with it being bounced to T-core, or to any other team that is currently active.

@rustbot label: T-lang I-lang-nominated

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/lang meeting.

An omnibus issue with a variety of items in it is hard to make progress on. We're going to close this issue, *however*, we'd like to add links to the items in this list that are official (under the rust-lang organization): the API guidelines, and (if the team maintaining it thinks it's ready for this) the async programming guide.

**Comment by Mark-Simulacrum** [comment]
For helpful reference: https://github.com/rust-lang/rust/blob/master/src/doc/index.md is the file which generates this page; offline availability currently means a submodule imported into this repo.
