### ISSUE TITLE
Tracking issue for RFC 2338, "Type alias enum variants"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#49683]
This is a tracking issue for the RFC "Type alias enum variants" (rust-lang/rfcs#2338).

**Steps:**

- [x] Implement the RFC (https://github.com/rust-lang/rust/pull/56225)
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR (https://github.com/rust-lang/rust/pull/61682)

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- [x] Decide how to resolve in case of ambiguities between associate types and variants. (Currently low-priority resolution for variants.) See https://github.com/rust-lang/rust/pull/56225#issuecomment-449961979. **Resolved in favour of high-priority resolution with https://github.com/rust-lang/rust/pull/57501.**

**Comment by djc** [comment]
I'd like to try implementing this. Since there was a previous implementation attempt in #31179, I can probably start off of that, but mentoring instructions would be quite welcome.

**Comment by petrochenkov** [comment]
Short instructions:
- Find a place where associated types are resolved to their definitions (probably `fn associated_path_def_to_ty`) and add high-priority resolution to variant definitions.
- Find a place where associated values are resolved to their definitions (probably `fn resolve_ufcs`) and add high-priority resolution to variant definitions.
- Try to apply the "argument transfer" scheme (`Type::Variant<Args>` -> `Type<Args>::Variant`) to generic arguments of associated items if they resolve to variants. This can meet complications because this is not something that can (or should) be done naturally, as I previously described.

**Comment by earthengine** [comment]
I have a specific concern on this. Right now, every concrete type name contains information of its component type names, making it very easy to have the name length being explode. Introducing something that making this issue worse may not be a good idea if we haven't get the type names shorted.

Here is an [example](https://internals.rust-lang.org/t/exponentially-growing-impl-trait-type-names/7447/5) on how bad this problem can be.

Internally, a type should contain all information to identify itself. But it is not necessary appear in the name, especially when the name is too long, because type names was intended to be read by human, and no one will read a name with a million chars. 

To making things worse, I just figured out that the length of a single type is not the issue I experienced. The problem is that there are too many (and too long) type names being generated, and so exceeded the compiler limit. This is why it is getting worse when I extract methods as it forces the compiler to generate more types.

This RFC, once implemented, will add much more types to the system, so please measure a typical closure-heavy-and-impl-trait-heavy program, to see how bad this problem is. It would also be good to allow the compiler to generate statistics of the types it generates, so we can keep tracking this.

**Comment by alexreg** [comment]
@djc Did you manage to make any headway on the implementation of this?

**Comment by djc** [comment]
@alexreg no, not yet. Feel free to move forward if you want to take a crack at it!

**Comment by alexreg** [comment]
Too busy right now, I'm afraid. I'd need more detailed mentoring instructions too, as too many of these concepts are foreign to me... best someone else tackles it.

**Comment by pravic** [comment]
It was already implemented. Why not to reopen the previous PR?

**Comment by alexreg** [comment]
@pravic Where’s that PR?

**Comment by alexreg** [comment]
Thanks.

**Comment by tlively** [comment]
Is there anyone currently working on this? I would love to see this RFC implemented. If there were mentoring instructions available I would take a stab at it.

**Comment by alexreg** [comment]
@tlively Do you feel you need something more detailed than 
https://github.com/rust-lang/rust/issues/49683#issuecomment-378896203? That's fine if so; maybe ping @petrochenkov or get on Discord. :-)

**Comment by djc** [comment]
@tlively I'm currently not working on this. Between the stuff that @petrochenkov already wrote here and the earlier implementation attempt I linked from the second comment, I think you should probably have a good starting point to dig in?

**Comment by alexreg** [comment]
@tlively Glad to hear! Let us know how you get on.

**Comment by tlively** [comment]
@alexreg So far it's slow-going, but I'm still chipping away at it!

**Comment by alexreg** [comment]
@tlively Okay. If you need any help, pop into Discord. Even I may be able to assist you a bit with it.

**Comment by alexreg** [comment]
Any updates on this lately, @tlively? :-)

**Comment by eddyb** [comment]
Should this *really* mention type aliases at all?
I expect `<Option<_>>::None` to require the exact same implementation, unless it's been hackily implemented today in some other fashion.
Similarly, `Self::None` should really desugar to `<Self>::None` and then get resolved by the exact same machinery that type aliases would need.

**Comment by petrochenkov** [comment]
I still think we should reconsider and not implement the "argument transfer" scheme `Type::AssocItem<Args> -> Type<Args>::AssocItem`.

**Comment by eddyb** [comment]
@petrochenkov We have to keep things like `None::<T>` working, but I'd be fine with only allowing `Option::None::<T>` as sugar for `<Option<T>>::None`, and *not* anything that wasn't resolved to a variant by `rustc_resolve` (i.e. not `<Option<_>>::None::<T>`).
Is your position pretty much that, or something else? (I'm not sure what the limitations of the "argument transfer" scheme are, if any)

**Comment by petrochenkov** [comment]
Yes, my position is to keep what's working now for compatibility, but don't expand this hack further.

**Comment by alexreg** [comment]
[**Implementation PR**](#56225)

**Comment by emilio** [comment]
It's awesome that this is finally implemented, thanks @alexreg! Does anybody know what's left to be able to stabilize this? Just docs?

**Comment by alexreg** [comment]
@emilio Sure. This feature had definitely been in the to-do queue for too long! As for stabilisation, we're at the point where we can at least start thinking about it now. My implementation PR merged almost a month ago, although the high-priority resolution only 8 days ago. It needs a PR to remove the feature gate, etc., and also one for documentation -- there are instructions linked in the original PR comment. If you want to have a go at this in a week or two, I'd be happy to review your main stabilisation PR then (documentation PR I'll leave to others). We can look to get this accepted from the 10th Feb.

**Comment by jesskfullwood** [comment]
I would have expected the following code to work:
```rust
#![feature(type_alias_enum_variants)]

enum E {
    A,
    B
}

type E2 = E;

fn main() {
    use E2::*;
    // ...
}

```
But it throws 
```
error[E0432]: unresolved import `E2`
  --> src/main.rs:15:9
   |
15 |     use E2::*;
   |         ^^ not a module `E2`
```
Is this intended behavior? It is inconsistent with the principle that the alias should be everywhere substitutable with the original type.

(Apologies if this has been answered, I couldn't see it mentioned in the RFC.)

**Comment by eddyb** [comment]
@jesskfullwood The type alias is substitutable in type positions, but there is still the *separate* module system, and `E` behaves like a module, with `A` and `B` children, while `E2` is a mere type.

That is, `E2::A` is sugar for `<E2>::A`, an associated item of `E2` (i.e. of `E`, so it's equivalent to `<E>::A`), while `E::A` exists on its own, with `<E>::A` being *a separate way* to refer to it.

For `use E2::*;` to work, it would have to be sugar for `use <E2>::*;`, and involve the typesystem in name resolution (if any generic arguments are involved, you would have to transport them faithfully), which isn't really doable atm.

This is a more general problem, in that `use Foo::...;` won't import associated consts/types/methods from types/traits.

It's why we can't e.g. remove the `MAX` const in `std::u8` (or any other integer) in favor of a `MAX` const on the `u8` type, as `use std::u8::MAX;` would stop working *even if* we made `std::u8` an alias of `u8`.

**Comment by jesskfullwood** [comment]
@eddyb Thanks for the explanation, I did not realize imports worked like that. It's a little unfortunate as it somewhat limits how much you can hide the underlying (non-aliased) type from the user - e.g.
```
enum GenericEnum<T> {
    A(T),
    B
}

type SpecificEnum = GenericEnum<()>;
```
In such a case the user still needs to 'know about' `GenericEnum` (admittedly, this might be the case anyway as the docs for `SpecificEnum` do not list the variants but simply link to `GenericEnum`, at least at the moment.)

**Comment by alexreg** [comment]
@jesskfullwood What @eddyb writes is correct... and yes, it's unfortunate. I don't know the details of how the import (`use`) system works right now, and it may require some overhauling to support things like this, but an RFC on such enhancements would of course be welcome!

**Comment by nvzqz** [comment]
So for some reason this nightly feature is required when implementing the following macro (found in https://github.com/nvzqz/static-assertions-rs/issues/11):

```rust
macro_rules! assert_variant {
    ($e:ty, $v:ident) => {
        const _: fn($e) -> () = |e| match e {
            <$e>::$v => {},
            _ => {},
        };
    }
}
```

Does anyone have an idea as to why?

**Comment by petrochenkov** [comment]
@nvzqz 
The reason is that the feature is not actually "type alias enum variants", but "type relative enum variants" or "variants as associated items".
When writing `<TYPE>::NAME` you are asking to search for an associated item named `NAME` on type `TYPE`, for variants this kind of requests is feature gated.

The stable solution will look something like:
```rust
macro_rules! assert_variant {
    ($e:ident, $v:ident) => {
        const _: fn($e) -> () = |e| match e {
            $e::$v => {},
            _ => {},
        };
    }
}
```
or
```rust
macro_rules! assert_variant {
    ($e:path, $v:ident) => {
        const _: fn($e) -> () = {
            use $e as my_ident; // On 2018 edition, or if `$e` is guaranteed to be a crate-relative path
            |e| match e {
                my_ident::$v => {},
                _ => {},
            }
        };
    }
}
```
(See also https://github.com/rust-lang/rust/issues/48067 that would provide a better solution for the second case.)

**Comment by nvzqz** [comment]
So the issue with using `path` or `ident` in this case is that neither supports generic arguments. I would like it such that `$e` could be any `enum`, generic or otherwise.

**Comment by petrochenkov** [comment]
>I thinks we can start the stabilization process once the current implementation (#57501) lands on stable.

https://github.com/rust-lang/rust/pull/57501 is now in the released stable Rust 1.34

**Comment by estebank** [comment]
Once this is stabilized, we can close https://github.com/rust-lang/rust/issues/52118 if it hasn't been closed earlier by adding a suggestion to use the enum's path instead of `Self`.

**Comment by Centril** [comment]
We discussed this on the language team meeting today and gave the green light for a stabilization report which I (@Centril) will write.

**Comment by alexreg** [comment]
I should be able to stabilise this if I'm not too busy with other things. (Or @Centril is welcome to after writing the report.)

**Comment by Centril** [comment]
I will do both things at the same time... :)

**Comment by Centril** [comment]
I have proposed stabilization in https://github.com/rust-lang/rust/pull/61682.

**Comment by Centril** [comment]
Stabilization has been done.

Documentation issue is https://github.com/rust-lang-nursery/reference/issues/631.

Everything that needs to be done on rust-lang/rust is done so I'm closing this issue as a result.
