### ISSUE TITLE
Tracking issue for  RFC 2295, "Extend Pattern API to OsStr"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#49802]
This is a tracking issue for the RFC "Extend Pattern API to OsStr" (rust-lang/rfcs#2295).

**Steps:**

- [ ] Implement the RFC (cc @kennytm)
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

None

**Comment by 1011X** [comment]
Now that [rust-lang/rfcs#2500](https://github.com/rust-lang/rfcs/pull/2500) has merged, can this RFC be implemented?

**Comment by jhwgh1968** [comment]
Hey @rust-lang/libs-api team, since [it was decided to revert the Needle/Pattern API stabilization](https://github.com/rust-lang/rust/pull/76901#issuecomment-880169952), what is the status of this?

It would still really help me with cross-platform compatibility to have this implemented.

**Comment by joshtriplett** [comment]
@jhwgh1968 We're not planning on reverting impls of this trait; we're keeping the trait. We're just planning to seal it and not support implementations outside the standard library.

**Comment by pitaj** [comment]
Is like to try my hand at implementing this. I've read the RFC and the OMG-WTF-8 spec, but I want to make sure I understand the reason for OMG-WTF-8.

My understanding is that Windows does not require that various strings are actually valid UTF-16. Any `[u16]` will do. This is the reason for the existence of WTF-8: WTF-8 allows encoding any `[u16]` as an extension of UTF-8. However, WTF-8 is not flexible enough to allow slicing into the individual units from the `[u16]`, it does not allow spitting surrogate pairs. That is what OMG-WTF-8 adds, and it makes various pattern APIs more economic.

@kennytm you mention having an implementation ready. Is that just the omgwtf8 package, or did you have a rust branch set up? If the latter, please share.

Thanks!

**Comment by mina86** [comment]
@pitaj, FYI I’ve actually started looking into this myself.  You can see stuff I’ve done so far at https://github.com/rust-lang/rust/compare/master...mina86:rust:wtf

For now this is just Pattern API stuff and not even exactly conforming to this RFC (see [my comment under the RFC PR](https://github.com/rust-lang/rfcs/pull/2295#issuecomment-1431501395)) (plus some `Haystack<&[T]>` shenanigans I've been toying around with to get a feel of the Pattern API.

I’ve just started looking at OsStr.  To answer your question, yes, pretty much.

**Comment by pitaj** [comment]
@mina86 cool! Are you on zulip? Are you open to collaborating on the implementation?

It's my understanding that `Haystack` no longer exists. Am I mistaken or are you working from an older version?

**Comment by mina86** [comment]
You may be right about Haystack now that I read the RFC again.  I’ll ping you on Zulip then.

**Comment by epage** [comment]
https://github.com/rust-lang/libs-team/issues/311 is the most recent revision to the proposed API.
