### ISSUE TITLE
support higher-ranked types for chalk

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#49810]
As discussed in [the WG-traits planning meeting today](https://paper.dropbox.com/doc/WG-Traits-Planning-Meeting-oDfr6ct8xx63HSAOOmIZX#:uid=463067912981955114240329&h2=2018.04.09), we need to decide how we will represent higher-ranked types in rustc. We decided to try for using debruijn indexing more universally, much as it is done in chalk. The plan is to generalize the existing `CanonicalVar` so that it represents a "bound" thing -- probably it just gets unified with `DebruijnIndex`. This will take a few steps, each of which I plan to describe in its own sub-issue:

- [x] Cleanup `Binder` fields (https://github.com/rust-lang/rust/issues/49814)
- [x] Make `DebruijnIndex` 0-based (https://github.com/rust-lang/rust/issues/49813)
- [x] Unify `CanonicalVar` and `DebruijnIndex` (https://github.com/rust-lang/rust/issues/49887)
- [ ] Maybe cleanup how regions are handled to use distinct indices for each region, rather than names (somewhat separate)

**Comment by nikomatsakis** [comment]
cc @rust-lang/wg-traits

**Comment by scalexm** [comment]
I believe this can be closed, in light of #55330, #55649 and #55921.
