### ISSUE TITLE
Metabug for 2018 edition lints

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#50068]
## Edition lints

*These lints will warn by default on Rust 2015.*

- [ ] Edition keywords #49716 (blocked on #49611)
   - Hygiene plan: Do this at the lexer level
- [x] fully qualified paths that use module names #48722 (PR at #50100)
   - Hygiene plan: None
- [ ] Flipping these on
   - [x] Need support for EpochAllow - `edition_lint_opts`

## Idiom lints

*These lints will warn only when you opt in to the 2018 edition, and are useful for driving `rustfix` to update idioms*.

- [x] `extern crate` #48719 (PR at https://github.com/rust-lang/rust/pull/50260)

## Bugs

- Suggestions within macros (#48704)

**Comment by Manishearth** [comment]
cc @aturon @cramertj please fill in details on lints and add more

**Comment by nrc** [comment]
I'm going to close this since there is not much info here, tracking has got too complex for a GH issue, and we can use the [A-edition-2018-lints](https://github.com/rust-lang/rust/labels/A-edition-2018-lints) label.
