### ISSUE TITLE
LLVM 7.0 tracking issue

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#50543]
I'm opening this to track upgrading to LLVM 7.0. This version of LLVM has not been release and is currently in development on the master branch of LLVM itself, but I'd like to track possible regressions over time and otherwise try to routinely build rustc with LLVM 7 and make sure it keeps working

* [Current rustc branch](https://github.com/alexcrichton/rust/tree/llvm7) - based on 56e541ddf1ee9a4e9d65a3cf6f952c31c3edf5ef
* [Current LLVM fork](https://github.com/alexcrichton/llvm/tree/rust-llvm-release-7-0-0) - based on https://github.com/alexcrichton/llvm/commit/d9367a91972e6631f831c329a47856785031d58e
* [Latest test results](https://travis-ci.org/rust-lang/rust/builds/376432459)

### Reasons to upgrade to LLVM 7

* [LLD has implemented `--gc-sections` for wasm](https://github.com/llvm-mirror/lld/commit/c69119a92799a8dd09b7e47c3be52e13b81a2cdc)
* [LLD has implemented DWARF debugging information sections for wasm](https://github.com/llvm-mirror/lld/commit/b5c6a5aca8d591cf1ead4e7f2947b4c21affb713)
* [LLD has natively implemented concatenation of custom sections for wasm](https://github.com/llvm-mirror/lld/commit/e1964ff6e9e3c9dc464b09a83b8640229b9e4f2f)
* [LLD has gained the ability to place the stack first in a wasm module's memory layout, reducing the corruption that happens on a stack overflow](https://github.com/llvm-mirror/lld/commit/0db522bf2237c7265f962c38404334e2bc78b9df)
* [LLD option to not merge data segments](https://github.com/llvm-mirror/lld/commit/4a118b5f8d03cc5090f148b71cd8db4b707dba63)
* [Some SIMD generic float intrinsics have been fixed](https://github.com/llvm-mirror/llvm/commit/e271f8c46c6bee271f75848b6110588da5df7d2f)
* [LLD optimizing further the size of release binaries](https://reviews.llvm.org/D46416)
* [LLD supports `@`-file syntax](https://reviews.llvm.org/D47500)

... and likely more coming soon!

### Changes required

* [ ] Track down and fix rustdoc panic on x86_64 (and maybe i686?)
  * https://travis-ci.org/rust-lang/rust/jobs/376432495
  * https://travis-ci.org/rust-lang/rust/jobs/376432502
  * currently [hacked around](https://github.com/alexcrichton/rust/commit/ef4f3c09330c965a62c628eaa4707f03a8cb5853#diff-4b7132e898719f35d3030ab5ec0d94b3)
* [x] [Track](https://travis-ci.org/rust-lang/rust/jobs/376432470) down, [report](https://bugs.llvm.org/show_bug.cgi?id=37382), and pull in [fix](https://reviews.llvm.org/D48846) for codegen failure on Thumb platform
* [x] `fs::tests::realpath_works_tricky` is failing on x86_64 MSVC
* [x] PGO run-make-fulldeps tests failing on x86_64 MSVC
* [x] Update LLD's `@`-syntax to always use GNU quoting
* [x] Serialize custom sections to LLVM IR for wasm instead of manually handling them
* [x] IR syntax for memcpy/memmove has changed with argument alignments
* [x] getelementptr syntax has changed with argument alignment
* [x] Pass `--gc-sections` to `wasm-ld`
* [x] Leverage LLVM for wasm custom sections instead of implementing custom support
* [x] Pass the `--stack-first` option to `wasm-ld` by default
* [x] The wasm target is now named `wasm32-unknown-unkonwn` (no trailing `-wasm`)
* [x] Pass `-O2` to LLD on wasm

### Changes hoped for

* [LLD preserving wasm import modules](https://bugs.llvm.org/show_bug.cgi?id=37168)

**Comment by fitzgen** [comment]
I will try and land https://reviews.llvm.org/D46417 before we update LLVM too :)

**Comment by alexcrichton** [comment]
Upgraded in https://github.com/rust-lang/rust/pull/51966
