### ISSUE TITLE
NLL fails to suggest "try removing `&mut` here"

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#51191]
For the following tests, AST-borrowck suggests removing `&mut`, while NLL fails to make such a suggestion:

 * [ ] [did_you_mean/issue-31424.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-31424.rs) / [NLL output](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-31424.nll.stderr) (partially fixed in #51275)
 * [x] [did_you_mean/issue-34337.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-34337.rs) / [NLL output](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-34337.nll.stderr) (fixed in #51275)
 * [x] [did_you_mean/issue-37139.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-37139.rs) / [NLL output](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-37139.nll.stderr) (fixed in #51275)

**Comment by pnkfelix** [comment]
We *might* be able to incorporate a fix for this into https://github.com/rust-lang/rust/pull/51275 ; I haven't quite dug into how we detect this case yet. But its worth at least looking into as part of that PR.

**Comment by pnkfelix** [comment]
(at this point I have indeed incorporated a fix for this into #51275 )

**Comment by pnkfelix** [comment]
(except that my fix, in the case of [did_you_mean/issue-31424.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-31424.rs), is suggest to the user that they write `mut self` rather than suggesting to the user that they remove the `&mut` borrow in the method call receiver. Not sure whether that is worth addressing. Probably shouldn't close this issue without at least looking into that.

**Comment by nikomatsakis** [comment]
To clarify the current situation. For [issue-31424.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-31424.rs), the AST-based checker gives this error:

```
error[E0596]: cannot borrow immutable argument `self` as mutable
  --> src/main.rs:19:15
   |
19 |         (&mut self).bar(); //~ ERROR cannot borrow
   |               ^^^^
   |               |
   |               cannot reborrow mutably
   |               try removing `&mut` here
```

and the NLL one gives this one:

```
error[E0596]: cannot borrow immutable item `self` as mutable
  --> src/main.rs:19:9
   |
19 |         (&mut self).bar(); //~ ERROR cannot borrow
   |         ^^^^^^^^^^^ cannot borrow as mutable

```

Note that the hint is missing from the NLL one.

**Comment by nikomatsakis** [comment]
This doesn't seem to me to rise to the cut of a Edition Preview blocker, or even a RC blocker.

**Comment by nikomatsakis** [comment]
I'll tag with the Release milestone for now, though I think it could plausibly be cut.
