### ISSUE TITLE
2018 edition lints

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#52047]
Edition lints in the `rust_2018_idioms` group power Rustfix, the tool for transitioning crates from the 2015 to the 2018 edition. Having a good automatic tool for migrating crates is essential to a successful 2018 edition, and having well-implemented lints is essential to Rustfix actually working.

[All issues](https://github.com/rust-lang/rust/labels/A-edition-2018-lints)

### `rust_2018_compatibility`

- [x] keywords (#49716, some mentoring instructions)
- [x] migrating $()?* macros (#51587; PR in progress)
  - [PR implementing the lint](https://github.com/rust-lang/rust/pull/51587)
  - Blocked on [FCP being accepted and finishing](https://github.com/rust-lang/rust/issues/51934)
- [ ] migrating extern crate with #[macro_use] (#52043)
- [x] shadowing of `extern crate`s with modules (#52040)
- [x] `dyn` should not be allowed as a trait name (#50405)
  - decision was to allow this and force `impl self::dyn for ...` for disambiguation

### `rust_2018_idioms`

- [x] `'_ `in preference to lifetime elision in types (#52041)
- [ ] `...` to `..=` (#51043; partial solution)
- [ ] unnecessary T: 'a annotations (#52042)
- [ ] declarations obviated by in-band lifetimes (#52045)
- [ ] prefer `crate` to `pub(crate)` (#52048)
- [x] suggestion for pub(crate) (#51866)
- [x] bare trait objects (i.e., missing `dyn`)
- [x] unreachable `pub`
- [x] unused `extern crate`        
- [x] inclusive range patterns (`...` to `..=`)

**Comment by alexcrichton** [comment]
I believe that this issue is largely done now so I'm going to close this in favor of the tracking issues we have for specific lints now.
