### ISSUE TITLE
Tracking issue for RFC 2289, "Associated type bounds"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#52662]
This is a tracking issue for the RFC "Associated type bounds of form `MyTrait<AssociatedType: Bounds>`" (rust-lang/rfcs#2289). The feature gate is `#![feature(associated_type_bounds)]`.

**Steps:**

- [x] Implement the RFC - #57428
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- [x] Does allowing this for `dyn` trait objects introduce any unforeseen issues? This can be resolved during stabilization.
   - [x] Use for trait objects has been forbidden in #120719

- [x] Resolve exact desugaring in the context of putting bounds on an associated type of a trait. See [discussion in the RFC](https://github.com/rust-lang/rfcs/blob/master/text/2289-associated-type-bounds.md#an-alternative-desugaring-of-bounds-on-associated-types).

- [x] Consider nested lifetimes, https://gist.github.com/Centril/b0e62d31d4ae1849535c3e506e1fad64.

**TODO:**

- [x] Extend with tests in https://github.com/rust-lang/rust/pull/57428#issuecomment-489336637.

- [x] https://github.com/rust-lang/rust/issues/61752

**Comment by kennytm** [comment]
> Does allowing this for `dyn` trait objects introduce any unforeseen issues?

😕 How does it work? For instance while `dyn Iterator<Item = T>` is object-safe, `dyn Iterator<Item: Debug>` should not since its `.next()` returns... `impl Debug` (but dynamic)?

```rust
trait Tr {
    type Assoc;
    fn input(&self, assoc: &Self::Assoc);
    fn output(&self) -> Self::Assoc;
}

let a: &Tr<Assoc: Debug> = ...;
let o = a.output();  // ???
a.input(&o);         // ???

let b: &Tr<Assoc: Debug> = ...;
b.input(&o);         // ??????????
```

**Comment by Centril** [comment]
@kennytm  I think that while `dyn Iterator<Item: Debug>` make syntactic sense to parse (to keep the parser simpler), it doesn't make much sense semantically for the reasons you've noted. Nicely spotted. :)

**Comment by kennytm** [comment]
So I suppose we could parse `dyn Trait<Assoc: Bound>` into AST, but will reject it during HIR lowering or typeck.

**Comment by Centril** [comment]
@kennytm sounds reasonable. 👍

**Comment by LukasKalbertodt** [comment]
I haven't found any discussion about this: what about super trait bounds? In particular: whether other code can "rely" on it. Example (current Rust, [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=66a6c16ebf9cd353619503a7791d82fb)):

```rust
trait Color {
    type Channel;
}

trait CloneColor: Color
where
    Self::Channel: Clone,
{}

fn foo<T: CloneColor>() {
    let f = T::Channel::clone;
}
```

This errors. While `foo` can assume that `T` also implements `Color` (the direct super trait bound) and thus `T::Channel` works, `foo` cannot assume the `where` bound of the trait to be true, and thus `::clone` doesn't work. The compiler says "the trait bound `<T as Color>::Channel: std::clone::Clone` is not satisfied". I can't quite remember what this is called, but I once heard a term that describes what things other code can rely on and what not (maybe something fancy like "projection"?).

My question is: how would the following code behave?

```rust
trait CloneColor: Color<Channel: Clone> {}
```

Would it behave as the first code example or would other code now be able to deduce `T::Channel: Clone` from `T: CloneColor`?

<sup>(I hope I'm not missing something obvious here)</sup>

**Comment by Centril** [comment]
> This errors.

https://github.com/rust-lang/rust/issues/44491 will likely change this :) (cc @scalexm)

> My question is: how would the following code behave?

Same as:

```rust
trait CloneColor where Self: Color, <Self as Color>::Channel: Clone {}
```

> Would it behave as the first code example or would other code now be able to deduce `T::Channel: Clone` from `T: CloneColor`?

Depends on whether you have implied bounds or not :)

**Comment by LukasKalbertodt** [comment]
@Centril Thanks for the quick explanation! I didn't know implied bounds would change this too -- that's great!

**Comment by Nemo157** [comment]
How does this interact with HRLB? I just discovered that trait aliases allow you to write the constraints required for working with async functions/closures, but could this be another way to do so?

You can currently write:

```rust
trait Foo<'a> = FnOnce<(&'a u8,)> where <Self as FnOnce<(&'a u8,)>>::Output: Future<Output = u8> + 'a;

fn foo<F: for<'a> Foo<'a>>(f: F)
```

and presumably once this is implemented it could be:

```rust
trait Foo<'a> = FnOnce<(&'a u8,), Output: Future<Output = u8> + 'a>;

fn foo<F: for<'a> Foo<'a>>(f: F)
```

but can you go all the way to:

```rust
fn foo<F: for<'a> FnOnce<(&'a u8,), Output: Future<Output = u8> + 'a>>(f: F)
```

**Comment by Centril** [comment]
@Nemo157 When you write:
```rust
where
    Foo: for<'a> Bar<'a, Assoc: Bound>
```
it should desugar into:
```rust
where
    Foo: for<'a> Bar<'a>,
    for<'a> <Foo as Bar<'a>>::Assoc: Bound,
```

However, rustc is generally unhappy with `for<'a> <Foo as Bar<'a>>::Assoc: Bound` today as I found out when writing tests for https://github.com/rust-lang/rust/pull/57428. Chalk will hopefully makes things better in the future and throw out some of the bugs.

**Comment by Centril** [comment]
A fix to https://github.com/rust-lang/rust/issues/61752 landed in https://github.com/rust-lang/rust/pull/61919.

**Comment by Centril** [comment]
https://github.com/rust-lang/rust/pull/63350 by @iluuu1994 & reviewed by @Centril fixed https://github.com/rust-lang/rust/issues/61738. The standard library now uses ATBs in some places.

**Comment by Centril** [comment]
In https://github.com/rust-lang/rust/pull/63620, a bug was fixed where some incorrect spans were used in diagnostics. The PR also added a test [src/test/ui/associated-type-bounds/assoc-type-eq-with-dyn-atb-fail.rs](https://github.com/rust-lang/rust/blob/1808e4da68bd94393c03229550b166cafebf38e8/src/test/ui/associated-type-bounds/assoc-type-eq-with-dyn-atb-fail.rs) which checks that `type Out = Box<dyn Bar<Assoc: Copy>>;` rejects unifying `Assoc = T` where `T: Copy` is not satisfied. The PR was written by @estebank and reviewed by @Centril.

**Comment by 0xpr03** [comment]
This would be really helpful.
Currently one can't write a function that takes `fn<T: FromStr<Err: Debug>>(a: T)`
As such it's not possible to print the error.

**Comment by KrishnaSannasi** [comment]
@0xpr03 
```rust
fn foo<T: FromStr>(a: T)
where T::Err: Debug {}
```

**Comment by 0xpr03** [comment]
Oh thanks! Sorry for the noise but that will hopefully also help other people.

**Comment by estebank** [comment]
In the meantime, while this is unstable, the compiler [when encountering](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4b9da810b4ffefe2f065467cf127a885)

```rust
fn foo<T: FromStr<Err: Debug>>(a: T) {}
```
[should suggest](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=bf23c8f7dde0075759841c2efb1314d5)
```rust
fn foo<T: FromStr>(a: T) where <T as FromStr>::Err: Debug {}
```
instead of the current
```
error[E0658]: associated type bounds are unstable
 --> src/lib.rs:5:19
  |
5 | fn foo<T: FromStr<Err: Debug>>(a: T) {}
  |                   ^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/52662
  = help: add `#![feature(associated_type_bounds)]` to the crate attributes to enable
```

**Comment by LukasKalbertodt** [comment]
I don't know if this "experience"-information is useful at this point, but I just used this feature in all places where it made sense in a fairly large project of mine: https://github.com/LukasKalbertodt/lox/commit/e2cc0c340b13428e26f01fa0923a969ecc6b6e1e. "48 additions and 92 deletions" sounds good to me. Everything worked just out of the box, I just needed to mechanically replace all occurences.

**Comment by alexreg** [comment]
@lukas-code Nope, we appreciate hearing of such use cases! Will make me feel more comfortable about stabilising in the (hopefully) near future. :-)

**Comment by tage64** [comment]
I don't know if this is a bug or of topic for this issue. But I'm encountering the following error when compiling the following code.

```rust
#![feature(associated_type_bounds)]

trait A {
    type T;
}

trait B: A<T: B> {}
```

```
error[E0391]: cycle detected when computing the supertraits of `B`
 --> src/main.rs:6:15
  |
6 | trait B: A<T: B> {}
  |               ^
  |
  = note: ...which again requires computing the supertraits of `B`, completing the cycle
note: cycle used when collecting item types in top-level module
 --> src/main.rs:6:1
  |
6 | trait B: A<T: B> {}
  | ^^^^^^^^^^^^^^^^
```

But if I merge the traits `A` and `B` into the trait `C` it works.

```rust
trait C {
    type T: C;
}
```

I think the first example should work as good as the second since the trait `C` is only split into two traits `A` and `B` with same functionality.

**Comment by Centril** [comment]
@tage64 Please re-file this as an issue.

**Comment by jplatte** [comment]
Another use case for this is constraints for associated types of associated types. Since apparently you can't put where clauses on associated types without enabling GAT (??), the only other way I could think of was using this feature.

```rust
trait MyTrait {
    type Assoc: Iterator<Item: Debug>;
}
```

**Comment by eddyb** [comment]
That's sugar for:
```rust
trait MyTrait
    where Self::Assoc: Iterator<Item: Debug>,
{
    type Assoc;
}
```
And by further desugaring this feature:
```rust
trait MyTrait
    where Self::Assoc: Iterator,
        <Self::Assoc as Iterator>::Item: Debug,
{
    type Assoc;
}
```

**Comment by jplatte** [comment]
@eddyb: Thanks! It didn't occur to me that I could put constraints on the associated type in the trait's where clauses. I'd say it's more intuitive with associated type bounds, but having a way of doing the same thing on stable today is really helpful!

**Comment by Nemo157** [comment]
After trying to use this I noticed that the desugaring inside `impl Trait<Assoc: Bound>` doesn't feel right. As an example ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2f8681af0c708ff28c66bfa98a27dc9b)) I would expect code like this to just _add_ an additional bound, while retaining the existing bounds from the trait:

```rust
pub fn foo() -> impl IntoIterator<IntoIter: Debug> {
    vec![5]
}
```

Instead it completely overwrites the bounds, so while you can return an `impl IntoIterator<Item = impl Debug>` easily without mentioning `IntoIter`, to add a `Debug` bound you need to both split off an extra type alias and write a lot of duplicate information to return a

```rust
type Item = impl Debug;
fn foo() -> impl IntoIterator<Item = Item, IntoIter: Iterator<Item = Item> + Debug> {...}
```

**Comment by nikomatsakis** [comment]
Interesting. There are similar limitations in cases like this:

```rust
fn foo<T>(x: impl IntoIterator<IntoIter=T>)
```

where you must repeat that `T: Iterator` and so forth, though I guess we don't desugar to a fresh type parameter so it doesn't come up here. In any case, I had some thoughts to fix this as part of the work we're doing on chalk and implied bounds, but (a) I'm not sure if the latest formulations actually change anything here and (b) I'm not sure if they would address the `impl Trait` case.

**Comment by Pratyush** [comment]
Has there been any progress on this? Or are there any blockers?

**Comment by SoniEx2** [comment]
We feel like this syntax potentially conflicts with implied generics, e.g.:

```rust
impl Foo<T: Clone> {
  ...
}
```

(assuming we want implied generics to look like this.)

We'd like to suggest a small tweak to the syntax, that would work with both associated types and associated consts and whatever else associated things might be added in the future, while also being compatible with hypothetical implied generics:

```rust
MyTrait<_::AssociatedType: Bounds>
```

We know it's been years and it's kinda awkward to change this now, but... thoughts?

**Comment by kennytm** [comment]
> (Uh we can't find anything about implied generics now, but we thought we had seen something about it before. But we might just be thinking of lifetimes, as there are proposals to make `fn foo(̈́&'a self)` etc "just work"...)

rust-lang/rfcs#2115? it is entirely lifetime only.

**Comment by SoniEx2** [comment]
Ah, close enough. Would be nice to be able to support in-band/implied generics without an edition boundary tho.

**Comment by TheRawMeatball** [comment]
I'm running into an issue while using this alongside HRTB s: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ee890a38e4fde158ceb86414a938c392

Is this a known issue? If so, is there an issue about it I could follow?

**Comment by clarfonthey** [comment]
Getting a lot of issues similar to #76593 when `#[feature(associated_type_bounds)]` is enabled, whether I use associated type bounds or not.

Essentially, if you have:

```rust
pub trait Base {
    type Assoc;
}
pub trait Super : Base {}
```

Then it considers `Super<Assoc = T>` ambiguous and explicitly requires that you say `Base<Assoc = T> + Super` instead.

IMHO, this feature should be tagged as incomplete and trigger a warning since it modifies stable behaviour like this. I assume it's a bug, but it should be considered an incomplete feature until this is fixed.

**Comment by mimoo** [comment]
my way of circumventing this limitation:

```rust
trait Thing : Other<F = Self::F> {
  type F: SomeBound; // <-- add the bound on an associated type
  // ...
}
```

**Comment by clarfonthey** [comment]
I assume that fully implementing this feature isn't very high priority, but what do people think in terms of marking this flag as incomplete, given [the comment I posted earlier this year](https://github.com/rust-lang/rust/issues/52662#issuecomment-1043912799)?

I would offer to help with this but I'm not sure I'm aware of what's involved to do this. I'm also not sure where this is on the road map, but my assumption is it's lower than other planned features and no one's going to be working ensure this doesn't ambiguify (?) the existing trait behaviour for a while.

**Comment by joshtriplett** [comment]
Found myself wanting this again today, and had to work around it. I would love to see this debugged and stabilized.

**Comment by maia-s** [comment]
I have another use case for this. I have a trait with associated types:
```rust
trait Trait {
    type Type: SomeBounds;
}
```
Now I want to make an extension trait that puts additional bounds on the associated types in the original. I don't want to redefine the types in the extension trait, because that would introduce ambiguity. I tried adding a where clause to the extension trait to place the additional bounds, but that requires the where clause to be repeated wherever the trait is used. Instead, I'd like this to work:
```rust
trait TraitExt: Trait<Type: MoreBounds> {}
```
As far as I can tell there's no workaround for this that doesn't require a lot of boilerplate.

**Comment by thiolliere** [comment]
> update: I found a workaround:
> 
> ```rust
> trait TraitExt: Trait<Type = Self::TypeExt> {
>     type TypeExt: MoreBounds;
> }
> ```

This work around doesn't propagate the original bounds: `SomeBounds`:

E.g.:

```rust
trait Foo: Bar<B = Self::F> {
	type F;
}

trait Bar {
	type B: Default;
}

fn f<T: Foo>() {
	<<T as Bar>::B as Default>::default(); // Fails
	<T::F as Default>::default(); // Fails
}
```

This feature is still needed for your this usecase IMO

**Comment by oli-obk** [comment]
Tracking issues are impractical for discussions. I'm locking this issue. Please open new issues for problems and discuss the feature on zulip instead
