### ISSUE TITLE
Tracking issue for RFC 2229, "Closures Capture Disjoint Fields"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#53488]
This is a tracking issue for the RFC "Closures Capture Disjoint Fields" (rust-lang/rfcs#2229).

### Status

This is under **active development** by the wg-rfc-2229 compiler-team working group. You can track their progress on the [project-rfc-2229](https://github.com/rust-lang/project-rfc-2229/) repository. 

### Implementation plan and status

See the [RFC 2229 project board](https://github.com/rust-lang/project-rfc-2229/projects/1) and [milestones](https://github.com/rust-lang/project-rfc-2229/milestones). 

### Links, see also

* rust-lang/compiler-team#292, a Major Change Proposal outlining an initial plan

**Unresolved questions:**

- [ ] How to optimize pointers. Can borrows that all reference parts of the same object be stored as a single pointer? How should this optimization be implemented (e.g. a special `repr`, refinement typing)?
- [ ] How to signal that a function is pure. Is this even needed/wanted? Any other places where the language could benefit?
- [ ] Should `Box` be special?
- [ ] Drop order can change as a result of this RFC, is this a real stability problem? How should this be resolved?

This issue has been assigned to @arora-aman via [this comment](https://github.com/rust-lang/rust/issues/53488#issuecomment-647227743).

**Comment by eddyb** [comment]
IIRC, this needs to wait for the new MIR (NLL) borrow-checker to replace the old one.
cc @rust-lang/wg-compiler-nll

**Comment by samsartor** [comment]
I would love to follow this through and give the code a shot, but it's probably too big of a first contribution to the compiler. Maybe I'll take a swing at [some starter issues](https://www.rustaceans.org/findwork/starters/compiler) and then come back if no one else has gotten it done.

@eddyb Yes, this definitely should be built on NLL.

**Comment by ghedo** [comment]
@blitzerr could you please provide a status update on this? it looks like the related issues (#57482 and #60205) had some work done, but they look stuck now. Anything that needs help with? Not sure if I can do anything, but I can try :)

**Comment by lzutao** [comment]
Concern: How does this feature interact with self-referential struct?

**Comment by RustyYato** [comment]
@lzutao Rust has no native support for self referential types, so you will just have to be careful with the unsafe code you write.

**Comment by lzutao** [comment]
I know. But with [polonius](https://github.com/rust-lang/polonius), there might be support for self-referential types. So for future design space we need to care about how to interact this feature with self-referential types.

**Comment by Ixrec** [comment]
This is the first I've heard of Polonius having anything to do with self-referential types, despite having read all the blog posts and docs behind your link. Is this interaction spelled out somewhere?

**Comment by KiChjang** [comment]
@Ixrec I do recall that there was a presentation from Niko that says it could maybe help with self-referential structs somehow, but he did preface it by saying that it's purely speculative: https://youtu.be/_agDeiWek8w?t=1900.

**Comment by nikomatsakis** [comment]
I'm not really aware of any particular interaction between this feature and self-referential types. Am I missing something?

**Comment by iamwwc** [comment]
any update on this? Does the RFC has been implemented in rust?

**Comment by arora-aman** [comment]
> any update on this? Does the RFC has been implemented in rust?

Yes it's available on the Rust nightly builds under `#![feature(capture_disjoint_fields)]`. 

On a somewhat side note we should probably update the tracking issue with the project board.

**Comment by iamwwc** [comment]
> > any update on this? Does the RFC has been implemented in rust?
> 
> Yes it's available on the Rust nightly builds under `#![feature(capture_disjoint_fields)]`.
> 
> On a somewhat side note we should probably update the tracking issue with the project board.

Yes, please, RFC tracking issue should reveal whether it has been implemented, and how to use it 😃. I believe that someone have same concerns with me

**Comment by nikomatsakis** [comment]
Stabilization proposed in https://github.com/rust-lang/rust/issues/88126

**Comment by ehuss** [comment]
Since this is now stabilized, should this issue be closed?

**Comment by nikomatsakis** [comment]
Yes.
