### ISSUE TITLE
Tracking issue for RFC 2521, "Unify std::os::raw::c_void and libc::c_void via libcore"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#53856]
This is a tracking issue for the RFC "Unify std::os::raw::c_void and libc::c_void via libcore" (rust-lang/rfcs#2521).

**Steps:**

- [x] Implement the RFC: https://github.com/rust-lang/rust/pull/53910, https://github.com/rust-lang/libc/pull/1082
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

There are none.

**Comment by Ericson2314** [comment]
OK per what @retep998 was saying, if we can get Cargo to ensure that `use_std` is always used when `std` is used, we can and should avoid putting anything in `libcore`.

**Comment by IsaacWoods** [comment]
I'd like to work on this :)

**Comment by IsaacWoods** [comment]
Afaik the implementation for this is now complete and will be insta-stable from 1.31.0

**Comment by SimonSapin** [comment]
Thanks for your PRs @IsaacWoods!

I believe `core::ffi::c_void` is also available in 1.30.0. What do you think of having `libc`’s build script do feature detection (run `rustc` on a dummy file that imports `core::ffi::c_void`) instead of version detection like https://github.com/rust-lang/libc/pull/1082 does?

**Comment by IsaacWoods** [comment]
I went with 1.31.0 to make sure not to break nightly users using a 1.30.0 libstd without the change but upgrading libc, but feature detection would probably be better. I’ll send another PR when I have the chance

**Comment by kHigasa** [comment]
I could confirm that this issue was fixed. I was able to build correctly with `rustc 1.32.0-nightly (6acbb5b65 2018-11-25)` :)

**Comment by elichai** [comment]
why not move all `std::os::raw` to libcore too?

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rfcs/blob/master/text/2521-c_void-reunification.md

> This has been extensively discussed already:
>
> * [Issue #31536: std `c_void` and libc `c_void` are different types](https://github.com/rust-lang/rust/issues/31536)
> * [Internals #3268: Solve `std::os::raw::c_void`](https://internals.rust-lang.org/t/solve-std-os-raw-c-void/3268)
> * [Issue #36193: Move std::os::raw to libcore?](https://github.com/rust-lang/rust/issues/36193)
> * [RFC #1783: Create a separate libc_types crate for basic C types](https://github.com/rust-lang/rfcs/pull/1783)
> * [Issue #47027: Types in std::os::raw should be same as libc crate](https://github.com/rust-lang/rust/issues/47027)
> * [Internals #8086: Duplicate std::os::raw in core?](https://internals.rust-lang.org/t/duplicate-std-raw-in-core/8086)
> * [PR #52839: Move std::os::raw into core](https://github.com/rust-lang/rust/pull/52839)

In some of those discussions, there was no consensus for having integer type aliases in libcore because some of them are platform-specific but libcore “should be pure”.

**Comment by SimonSapin** [comment]
This was insta-stable (with FCP) in https://github.com/rust-lang/rust/pull/53910, so closing as it seems there is nothing else to track here. Feel free to reopen if there is.
