### ISSUE TITLE
Tracking issue for copy_within

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/rust#54236]
Rust PR: https://github.com/rust-lang/rust/pull/53652
Standalone implementation: https://github.com/oconnor663/copy_in_place

Summary: This is a safe wrapper around `ptr::copy`, for regions within a single slice. Previously, safe in-place copying was only available as a side effect of `Vec::drain`.

Open questions: @SimonSapin had a proposal for an alternative API using ranges. Here's an example PR along those lines: https://github.com/oconnor663/copy_in_place/pull/1

- [x] implement as a PR (https://github.com/rust-lang/rust/pull/53652)
- [x] land as unstable
- [ ] decide on a final API
- [ ] stabilize

**Comment by oconnor663** [comment]
@alexcrichton what do the next steps look like for something like this? How do we "decide" on an API? :)

**Comment by alexcrichton** [comment]
@oconnor663 the process here is somewhat informal, but after the API has been in nightly for some time it's renominated for stabilization with any open questions, and at that point the libs team all signs off on the stabilization.

To that end it's basically "let this sit for awhile and gain feedback", and then after awhile has passed it can be proposed to be stabilized

**Comment by briansmith** [comment]
FWIW, I tried this out in *ring* and here's my feedback:

* I wish there was a non-panicking version that failed with an error result when the bounds are out of range. I ended up having to duplicate the range checking in my own code.

* It is very important that the implementation be inlined but the implementation doesn't have `#[inline]`. In practice the compiler was always inlining it for me but it would be good to do something more to ensure this.

**Comment by oconnor663** [comment]
Thanks for trying it out.

1. What's the situation where you need to check against making an out of bounds copy? Would it be possible to see the code where this came up? What fallback would you be using if copy_within returned an error?

2. https://github.com/rust-lang/rust/pull/56886

**Comment by oconnor663** [comment]
I don't imagine it would make sense to hoist the bounds checking requirement up to the caller, and just have _ring_ propagate the panic if the bounds are wrong? I guess the question is whether any of the callers are expected to have a fallback, or whether bad bounds are more likely to be programmer error.

**Comment by briansmith** [comment]
> I don't imagine it would make sense to hoist the bounds checking requirement up to the caller, and just have _ring_ propagate the panic if the bounds are wrong? I guess the question is whether any of the callers are expected to have a fallback, or whether bad bounds are more likely to be programmer error.

There are lots of possibilities. This isn't the only API in libstd that has only a panicking version so if that's what libstd people like, I would just carry on as-is.

**Comment by oconnor663** [comment]
Yeah I was definitely working by analogy with `copy_from_slice` and friends.

**Comment by Shnatsel** [comment]
FWIW this is [desired](https://www.reddit.com/r/rust/comments/accvq7/ropey_10_an_editable_text_buffer_for_rust/ed938tv/?context=3) by [Ropey](https://crates.io/crates/ropey) crate. Currently [unsafe code](https://github.com/cessen/ropey/blob/698a25c6788625816afd4a9eeb945022d9b78510/src/rope.rs#L169) is used to achieve this.

**Comment by SimonSapin** [comment]
@briansmith Adding `#[inline]` sounds good, do you want to send a PR?

The arguments for a non-panicking version also sound good to me. Perhaps even instead of, not in addition to what’s implemented today. And users that want panic can call `unwrap`.

What API should this have? Perhaps a `Result` return type rather than `Option` to take advantage of `#[must_use]`, but there is no precedent in `std` for `Result<…, ()>`, so with a new dedicated error type?

The other API that does non-panicky bounds checking of a range argument is `[T]::get` which returns an `Option`, but that one doesn’t have side effects and is only useful for its return value.

**Comment by oconnor663** [comment]
@Shnatsel this function is available in the tiny [`copy_in_place`](https://crates.io/crates/copy_in_place) crate, if you want to keep the unsafe code out of the caller.

**Comment by joshlf** [comment]
> To that end it's basically "let this sit for awhile and gain feedback", and then after awhile has passed it can be proposed to be stabilized

Has it been a while yet? :) I'd like to use this if stabilized.

**Comment by kennytm** [comment]
Filed a stabilization PR at #61398.
