### ISSUE TITLE
Tracking issue for RFC 2539, "#[cfg_attr] expanding to multiple attributes"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#54881]
This is a tracking issue for the RFC "`#[cfg_attr]` expanding to multiple attributes" (rust-lang/rfcs#2539).

**Steps:**

- [x] Implement the RFC (@Havvy is doing this)
- [x] Adjust documentation (issue filed against https://github.com/rust-lang-nursery/reference/issues/500)
- [x] Stabilization PR (merged, https://github.com/rust-lang/rust/pull/57332)
- [ ] Fix the lint: https://github.com/rust-lang/rust/issues/54881#issuecomment-441442173

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

None

**Comment by Centril** [comment]
Implementation in #54862

**Comment by Centril** [comment]
Setting earliest date for stabilization proposal: 2018-11-22 (11 days from now).

**Comment by Centril** [comment]
## Stabilization proposal

@rfcbot merge

Originally proposed in RFC https://github.com/rust-lang/rfcs/pull/2539, implemented in https://github.com/rust-lang/rust/pull/54862/, and in nightly since ~ the 12th October, `cfg_attr_multi` allows users to specify multiple attributes in `cfg_attr(condition, foo, bar)` where `foo` and `bar` are the attributes to expand should `condition` hold. The benefit of `cfg_attr_multi` is ergonomics but also readability and maintainability; you avoid having to specify `condition` several times. This can be particularly beneficial if `condition` is long and non-trivial.

### Version target

The next version is 1.32 which goes into beta the 7th of December; It is quite possible that this will slip into 1.33 however depending on how long the review process takes.

### What is stabilized

- [Unstable book](https://github.com/Havvy/rust/blob/bbe832d570e826b2012c09869aa77d6201932730/src/doc/unstable-book/src/language-features/cfg-attr-multi.md)
- [Feature gate](https://github.com/Havvy/rust/blob/bbe832d570e826b2012c09869aa77d6201932730/src/libsyntax/feature_gate.rs#L520)
   - [/src/test/ui/feature-gates/feature-gate-cfg-attr-multi-1.{rs,stderr}](https://github.com/Havvy/rust/blob/bbe832d570e826b2012c09869aa77d6201932730/src/test/ui/feature-gates/feature-gate-cfg-attr-multi-1.rs)
   - [/src/test/ui/feature-gates/feature-gate-cfg-attr-multi-2.{rs,stderr}](https://github.com/Havvy/rust/blob/bbe832d570e826b2012c09869aa77d6201932730/src/test/ui/feature-gates/feature-gate-cfg-attr-multi-2.rs)
   - [/src/test/ui/feature-gates/feature-gate-cfg-attr-multi-bootstrap-1.rs](https://github.com/Havvy/rust/blob/bbe832d570e826b2012c09869aa77d6201932730/src/test/ui/feature-gates/feature-gate-cfg-attr-multi-bootstrap-1.rs)
   - [/src/test/ui/feature-gates/feature-gate-cfg-attr-multi-bootstrap-2.rs](https://github.com/Havvy/rust/blob/bbe832d570e826b2012c09869aa77d6201932730/src/test/ui/feature-gates/feature-gate-cfg-attr-multi-bootstrap-2.rs)
- Tests
   - [/src/test/ui/conditional-compilation/cfg-attr-parse.{rs,stderr}](https://github.com/Havvy/rust/blob/bbe832d570e826b2012c09869aa77d6201932730/src/test/ui/conditional-compilation/cfg-attr-parse.rs)
   - [/src/test/ui/conditional-compilation/cfg-attr-multi-true.{rs,stderr}](https://github.com/Havvy/rust/blob/bbe832d570e826b2012c09869aa77d6201932730/src/test/ui/conditional-compilation/cfg-attr-multi-true.rs)
   - [/src/test/ui/conditional-compilation/cfg-attr-multi-false.{rs,stderr}](https://github.com/Havvy/rust/blob/bbe832d570e826b2012c09869aa77d6201932730/src/test/ui/conditional-compilation/cfg-attr-multi-false.rs)
   - [/src/test/ui/conditional-compilation/cfg-attr-multi-invalid-2.{rs,stderr}](https://github.com/Havvy/rust/blob/bbe832d570e826b2012c09869aa77d6201932730/src/test/ui/conditional-compilation/cfg-attr-multi-invalid-2.rs)
   - [/src/test/ui/conditional-compilation/cfg-attr-multi-invalid-1.{rs,stderr}](https://github.com/Havvy/rust/blob/bbe832d570e826b2012c09869aa77d6201932730/src/test/ui/conditional-compilation/cfg-attr-multi-invalid-1.rs)

Users are now permitted to write for example:

```rust
#[cfg_attr(all(),)] struct A; // trailing comma permitted as well as zero items.
#[cfg_attr(all(), must_use)] struct A;
#[cfg_attr(all(), must_use,)] struct A; // trailing permitted.
#[cfg_attr(foo, must_use, deprecated)] struct A;
#[cfg_attr(all(), must_use, deprecated,)] struct A; // trailing permitted.
```

The semantics of these are to expand to for example `#[must_use] #[deprecated]` on `struct A` if `foo` should hold (4th example).

If zero attributes are given, e.g. `#[cfg_attr(all(),)]` then `unused_attributes` the lint will be emitted. This behaviour is not witnessed in the current nightly compiler; that is OK since it's a minor issue but it will need to be fixed in the stabilization PR. See https://github.com/rust-lang/rust/blob/master/src/libsyntax/config.rs#L145.

### What is not

Users are not permitted to write:

- More than one trailing comma, e.g. `#[cfg_attr(all(), must_use, deprecated,,)]`
- Zero attributes and no comma, e.g. `#[cfg_attr(all())]`
- An empty `cfg_attr`, e.g. `#[cfg_attr()]`
- `#[foo, bar]`; this is proposed in https://github.com/rust-lang/rfcs/pull/2600.
  This stabilization is forward compatible with that RFC.

### Divergences from RFC

None

------------------------

cc @Havvy can you make the stabilization PR + resolve the minor FIXME in it?
Also cc @petrochenkov who reviewed the implementation.

**Comment by Havvy** [comment]
I wouldn't call the implementation of the lint a minor fix. The first time I tried, I bailed when I hit a set of cases I couldn't get something the lint infrastructure wanted.

The lint is also the least value add of the RFC and I propose stabilizing it separately if doing so doesn't break backwards compatibility.

**Comment by Centril** [comment]
@Havvy Warn by default lints can always be added later so if you think it is non-trivial to implement in the stabilization PR, I wouldn't mind deferring that to the future; as you say, it is indeed the least value-add.

**Comment by Centril** [comment]
@Havvy Up for writing the stabilization PR?

**Comment by Havvy** [comment]
I don't and haven't had motivation pertaining to Rustlang at the moment, sorry. Eventually it'll return.

**Comment by Centril** [comment]
Stabilization has gone through and documentation issue has been filed against the reference; what remains is to fix the lint which @Dylan-DPC will do in a separate PR. After that this issue can be closed.
