### ISSUE TITLE
Tracking issue for RFC 2514, "Union initialization and Drop"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#55149]
This is a tracking issue for the RFC "Union initialization and Drop" (rust-lang/rfcs#2514).

Successor of https://github.com/rust-lang/rust/issues/32836.

**Steps:**

- [x] Implement the RFC (Mentoring instructions: https://github.com/rust-lang/rust/issues/55149#issuecomment-435577496): https://github.com/rust-lang/rust/pull/62330
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

 - [x] There should be more tests in particular for all move-related behaviors ([1](https://github.com/rust-lang/rust/issues/32836#issuecomment-242511491), [2](https://github.com/rust-lang/rust/issues/32836#issuecomment-242800896), [3](https://github.com/rust-lang/rust/issues/32836#issuecomment-242814894), [4](https://github.com/rust-lang/rust/issues/32836#issuecomment-243841060)). Done in https://github.com/rust-lang/rust/pull/75559.

- [x] Should we try to avoid the [`DerefMut`-related pitfall](https://github.com/rust-lang/rfcs/blob/master/text/2514-union-initialization-and-drop.md#potential-pitfalls-around-derefmut)?  And if yes, should we maybe try harder, e.g. lint against using `*` below a union type when describing a place?  That would make people write `let v = &mut u.f; *v = Vec::new();`.  It is not clear that this helps in terms of pointing out that an automatic drop may be happening. (Implementation at https://github.com/rust-lang/rust/pull/75584.)

- [ ] We could allow moving out of a union field even if the union implements `Drop`.  That would have the effect of making the union considered uninitialized, i.e., it would not be dropped implicitly when it goes out of scope.  However, it might be useful to not let people do this accidentally.  The same effect can always be achieved by having a dropless union wrapped in a newtype `struct` with the desired `Drop`.

- [ ] Should we allow `impl Copy for Union` even when the union has non-`Copy` fields? (Proposed [here](https://github.com/rust-lang/rust/issues/32836#issuecomment-242800896).)

**Implementation history**
* https://github.com/rust-lang/rust/pull/62330: union fields must be no-drop
* https://github.com/rust-lang/rust/pull/75559: more tests for moving out of non-Copy union fields
* https://github.com/rust-lang/rust/pull/75584: don't implicitly `DerefMut` in unions
* https://github.com/rust-lang/rust/pull/77547: stabilize `ManuallyDrop<_>` union fields

**Comment by RalfJung** [comment]
> can anyone write up mentoring instructions

I have no idea, unfortunately.

**Comment by Centril** [comment]
@SimonSapin I just make the issues, so I'll leave the question up to @RalfJung :)

**Comment by RalfJung** [comment]
Stabilization is separate, right? It has its own checkmark above. :) Implementing the RFC means restricting unions with non-`Copy` types to the point where I think they can be stabilized, yes.

I am not fully aware of everything that exists behind the `untagged_union` feature gate though... if e.g. there is such a thing as union patterns, they are not affected by this directly.

Quoting from that RFC:

> When moving out of one field of a union, are the others considered invalidated? 

This is answered by this RFC.

> Under what conditions can you implement Copy for a union? For example, what if some variants are of non-Copy type? All variants?

The RFC doesn't say anything about that, but I think indeed the answer should be "all variants".

> What interaction is there between unions and enum layout optimizations?

This is topic of a future unsafe code guidelines discussion, and unrelated to this RFC.

**Comment by Aaron1011** [comment]
I'm interested in working on implementing this.

**Comment by Gankro** [comment]
cc'ing myself on this since this is a pre-req for unforking serde_derive in firefox

**Comment by Centril** [comment]
@Gankro GitHub has a "subscribe" button so you don't have to write "cc me" and such in issues.

**Comment by eddyb** [comment]
This is the part that needs to be changed: https://github.com/rust-lang/rust/blob/757d6cc91a691c8a749a7b0eee09df494ecdcc3b/src/librustc/middle/stability.rs#L768-L773
<sup>(argh, when did GitHub break code links?!)</sup>

It should be possible to change it to `ty.needs_drop(self.tcx, param_env)`.

(note that this will remain valid only as long as nobody changes the implementation of `needs_drop` to return `false` for `union`s without checking! but if we add tests we should be fine)

**Comment by RalfJung** [comment]
Behavior if the check failed should then also change from "require feature flag" to "hard error".

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/62330 is looking for someone to take over, to push disallowing dropping fields in a union to completion. Any takers?

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/62330 has landed. Are there remaining changes specified in the RFC that are not implemented yet?

**Comment by RalfJung** [comment]
There are certainly some open questions / TODOs in the tracking issue here and in [the other one](https://github.com/rust-lang/rust/issues/32836). In particular I'd like to make sure we have test coverage for the [examples in the RFC](https://github.com/rust-lang/rfcs/blob/master/text/2514-union-initialization-and-drop.md#union-initialization-and-drop) and these concerns/questions copied from the other tracking issue: ([1](https://github.com/rust-lang/rust/issues/32836#issuecomment-242511491), [2](https://github.com/rust-lang/rust/issues/32836#issuecomment-242800896), [3](https://github.com/rust-lang/rust/issues/32836#issuecomment-242814894), [4](https://github.com/rust-lang/rust/issues/32836#issuecomment-243841060)).

I'd also like to make sure we have a test for
> DerefMut auto-deref is not applied when working on a union or its fields

**Comment by withoutboats** [comment]
I would like to see progress on allowing users to use `ManuallyDrop` non-`Copy` types in unions on stable. It's valuable for correctly implementing "atomic state machine" patterns, common in low level async code, in which you have a tagged union with an atomically updated tag (with a locked state as well, etc.)

However, I didn't participate in the RFC thread and reading it now I notice a concern with the fully general concept of this RFC that we didn't discuss at the time: "having no drop glue" presents forward compatibility hazards for libraries, because adding a drop impl to a type would be a breaking change. Investigating, I found we have a few other cases which cause this:

* const fn can cause this #58379
* There's another example in that issue involving moving copy type fields, which petro chenkov says has been discussed and is fixable, but there's no link to further discussion

I'd like to *not* entrench this problem. We do a lot to avoid forward compatibility hazards, and I'd like it if we could move to eliminate all of these problems with `Drop` over time.

I'd propose narrowing the scope of this RFC to allowing either `ManuallyDrop` or `ManuallyDrop` and `&mut` in unions. These are types we know will never have a drop impl, and wrapping all non-copy structs in ManuallyDrop in a union is just better for tracking the fact that drop glue is not called on unions.

**Comment by RalfJung** [comment]
> I'd propose narrowing the scope of this RFC to allowing either ManuallyDrop or ManuallyDrop and &mut in unions. These are types we know will never have a drop impl, and wrapping all non-copy structs in ManuallyDrop in a union is just better for tracking the fact that drop glue is not called on unions.

Seems reasonable to me.

So specifically, the allowed types for union fields would be
* anything that implements `Copy`
* `ManuallyDrop<T>` for any `T`
* `&mut T` for any `T` (maybe)

Would everything else be disallowed? What about `(ManuallyDrop<T>, ManuallyDrop<U>)` (tuples never add their own destructors)? What about `MaybeUninit<T>` (or other drop-less libstd types such as `Option<T>`)?

**Comment by nikomatsakis** [comment]
>  adding a drop impl to a type would be a breaking change

Adding a `Drop` impl is a breaking change ever since NLL, though it's true that we could try to narrow the range of cases where that is true. It's pretty fundamental to the idea of NLL, though, since we want to have types that contain references (e.g., iterators) but have them release those references when they stop being used (vs extending until the end of scope). If they have a `Drop` impl, we have to extend until the end of scope, because the `Drop` impl may use the referenecs.

**Comment by nikomatsakis** [comment]
That said, I agree with the specific proposal of extending to include `ManuallyDrop` as well as `&mut`. I would probably extend to tuples that compose those primitives.

**Comment by withoutboats** [comment]
>  Would everything else be disallowed? What about (ManuallyDrop<T>, ManuallyDrop<U>) (tuples never add their own destructors)? What about MaybeUninit<T> (or other drop-less libstd types such as Option<T>)?

Tuples and arrays seem fine. Other std types seem like we'd need to consider them on a case-by-case basis, but the idea is to make the advice to people that they put a `ManuallyDrop` around their fields that are not Copy types or references.

I guess maybe the use case with option is `Option<&mut T>`, rather than `Option<ManuallyDrop<T>>`.

> Adding a Drop impl is a breaking change ever since NLL

Agh yea. Well the idea is to reduce the scope of breakage, not make it an iron-clad guarantee, to avoid ecosystem problems in the future.

**Comment by SimonSapin** [comment]
Having a criteria stricter than "no drop glue" so that adding `Drop` is not (more of) a breaking change sounds reasonable. Extending union fields to allow `ManuallyDrop<T>` with `T: !Copy` is what fundamentally unlocks new capabilities in the language, anything more is convenience.

We could make the language-level rule be specifically "union fields must be `Copy` or `ManuallyDrop`". But if it’s starting to look like `Copy` or `ManuallyDrop` or `&mut` or `MaybeUninit` or `Option` or tuple or array, or… Maybe we could instead have a marker trait for this purpose?

There would be a "magical" language rule that implementing the trait requires the type not to have drop glue. (The same as for `Copy`, if I remember correctly?) This trait would effectively be an opt-in for "this type will never have drop glue" (without that change being more visibly breaking).

Plus, a trait would allow generic types that contain unions to be maximally permissive in their bounds. (I don’t know if that’s particularly useful, v.s. wrapping the union fields in `ManuallyDrop`.)

I think we should either have a marker trait, or stick to only `Copy` and `ManuallyDrop`. The latter would not be so bad, anyone that needs a union field with `&mut` or `Option` or something can always wrap it in `ManuallyDrop`, like for types with drop glue.

**Comment by withoutboats** [comment]
Yea this is where we start talking about a "POD" trait. I agree that just moving ManuallyDrop to stable as quickly as possible could be the best short term action. Then we can find out how annoying it is wrapping `&mut` etc in ManuallyDrops and decide if we should do more.

**Comment by SimonSapin** [comment]
Good point, stabilizing `ManuallyDrop` fields only (in addition to `Copy`) doesn’t prevent extending to a new trait later.

**Comment by RalfJung** [comment]
There's an aspect of the RFC that has not been implemented yet. This still compiles:
```rust
#![feature(untagged_unions)]

use std::mem::ManuallyDrop;

union U<T> { x:(), f: ManuallyDrop<T> }

fn main() {
    let mut u : U<(Vec<i32>,)> = U { x: () };
    unsafe { u.f.0 = Vec::new() }; // uninitialized `Vec` being droped
}
```
The RFC suggested to not apply `DerefMut` implicitly on union fields, this making the above code a compile-time error.

**Comment by RalfJung** [comment]
>  I agree that just moving ManuallyDrop to stable as quickly as possible could be the best short term action.

I opened https://github.com/rust-lang/rust/pull/77547 to this end.

**Comment by haaami01** [comment]
> Igen, itt kezdünk el beszélni egy "POD" tulajdonságról. Egyetértek azzal, hogy az, hogy a ManuallyDrop-ot a lehető leggyorsabban stabil állapotba hozza, a legjobb rövid távú intézkedés lehet. Ezután megtudhatjuk, hogy mennyire idegesítő a csomagolás `&mut`stb. A ManuallyDrops-ban, és eldönthetjük, tennünk-e többet.

I hope this will help, I'm already spending days fixing it. 😔

**Comment by haaami01** [comment]
> > Igen, itt kezdünk el beszélni egy "POD" tulajdonságról. Egyetértek ezzel, hogy az, hogy a ManuallyDrop-ot a lehető legorsabban stabil állapotba hozza, a legjobb rövid távú intézkedés lehet. Ezután megtudhatjuk, hogy mennyire idegesítő a csomagolás `&mut`stb. A ManuallyDrops-ban, és eldönthetjük, tennünk-e többet.
> 
> Remélem, ez segít, már napokat töltök a javítással. 😔

**Comment by RalfJung** [comment]
I'm sorry, discussion language in this issue tracker is English... what are you trying to say?

**Comment by RalfJung** [comment]
FWIW, when the `untagged_unions` feature is removed, the `AssignToDroppingUnionField` unsafety kind can also be removed -- it is impossible to trigger without that feature.

**Comment by RalfJung** [comment]
In https://github.com/rust-lang/rust/pull/97995 I am suggesting to allow a few more types for union fields on stable (specifically: mutable references), before we entirely remove the `untagged_unions` feature.

**Comment by raphaelcohn** [comment]
@joshtriplett @RalfJung I think removing this has exposed an overlooked use case that should work, but now doesn't.

```
struct StackWithoutLength<T, const N: usize>(ManuallyDrop<MaybeUninit<[T; N]>>);

union StackWithoutLengthOrHeap<T, const N: usize>
{
	stack_without_length: StackWithoutLength<T, N>,

         copyable: u32
}
```

This now fails to compile with `error[E0740]: unions cannot contain fields that may need dropping` (details below)`, when it seems like it should; trivial analysis suggests that `StackWithoutLength` is a new type that can only be manually dropped...



```
error[E0740]: unions cannot contain fields that may need dropping
 --> swiss-army-knife/src/const_small_vec/StackWithoutLengthOrHeap.rs:7:2
  |
7 |     stack_without_length: StackWithoutLength<T, N>,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: a type is guaranteed not to need dropping when it implements `Copy`, or when it is the special `ManuallyDrop<_>` type
help: when the type does not implement `Copy`, wrap it inside a `ManuallyDrop<_>` and ensure it is manually dropped
  |
7 |     stack_without_length: std::mem::ManuallyDrop<StackWithoutLength<T, N>>,
  |                           +++++++++++++++++++++++                        +

```

**Comment by RalfJung** [comment]
Never inspecting the fields of a `struct` for this check was a deliberate design decision, since if that struct was in a different crate, it might start needing drop in future versions of the crate.

In this case, it seems like the struct and union are in the same crate? Possibly an exception could be made for that case, though it would be an extension of the RFC.  Please open a feature request issue.

**Comment by raphaelcohn** [comment]
@RalfJung thanks for the quick reply. The struct and union are in the same crate and both are private too it, as well.

If versions are correctly used, then a future version of the struct should then cause failure.

I won't be opening a feature request.
