### ISSUE TITLE
Tracking issue for RFC 2451, "Re-Rebalancing Coherence"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#55437]
This is a tracking issue for the RFC "Re-Rebalancing Coherence" (rust-lang/rfcs#2451).

**Steps:**

- [x] Implement the RFC – https://github.com/rust-lang/rust/pull/56145
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [x] [Stabilization proposal](https://github.com/rust-lang/rust/issues/63599)
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- [ ] Are there additional implementations which are clearly acceptable under the current restrictions, which are disallowed with this extension? Should we allow them if so?

**Comment by dwijnand** [comment]
Implemented in https://github.com/rust-lang/rust/pull/56145.

**Comment by weiznich** [comment]
To just add a implementation example:
We've used this feature to [improve the implementation of diesel-oci](https://github.com/GiGainfosystems/diesel-oci/pull/25). For this use case it seems to work fine.


@Centril  Somebody needs to update the boxes in the opening comment and change the label to `B-RFC-implemented`.

**Comment by nikomatsakis** [comment]
We discussed this some time back and the plan was for me to write a stabilization report. But I've not done so. I do expect to do so, but perhaps not for a week or two.

**Comment by pmarks** [comment]
@nikomatsakis in case it's useful: https://github.com/vbarrielle/sprs/pull/160

`ndarray::Dot` is a trait similar to `Mul` but for matrix multiplication.  `ndarray` provides dense matrices and `Dot` impls for dense matrices.  The `sprs` crate for sparse matrices wants to interoperate with `ndarray` and provide generic `sparse.dot(dense)` and `dense.dot(sparse)` impls.  Both are needed since matrix multiplication isn't commutative.  We're able to provide `impl Dot<sprs::CsMat<_,_>> for ndarray::ArrayBase<_,_>` from the `sprs` crate with this feature.  We're looking forward to having it stabilized!!

**Comment by djc** [comment]
What's the holdup for moving this towards stabilization? Still waiting for a lang team member to write the stabilization report? Is there a template that a non-team member could follow to assist with this work?

**Comment by Centril** [comment]
@djc Niko is on vacation and generally busy so he hasn't had time to write up the report yet. If you want to help out with that, there's inspiration to find in https://github.com/rust-lang/rust/pull/61682#issuecomment-502472847 (which is my most recent and elaborate report hitherto), https://github.com/rust-lang/rust/pull/61347#issuecomment-497533585, and https://github.com/rust-lang/rust/pull/57175/#issuecomment-450593735.

**Comment by nikomatsakis** [comment]
@djc see https://github.com/rust-lang/rust/issues/63599

**Comment by nikomatsakis** [comment]
Er, I could have worded that a bit more broadly for everyone. =) https://github.com/rust-lang/rust/issues/63599 contains a stabilization proposal. Thoughts etc welcome in that issue.

**Comment by djc** [comment]
@nikomatsakis awesome, thanks! Sorry I couldn't contribute anything in the end.

**Comment by lzutao** [comment]
Stabilized in #65879

**Comment by QuineDot** [comment]
This RFC stated that
> RFC #1105 is amended to remove the statement that implementing a non-fundamental trait is a minor breaking change, and states that adding any blanket impl for an existing trait is a major breaking change, using the definition of blanket impl given above.

However, [the RFC](https://rust-lang.github.io/rfcs/1105-api-evolution.html) has not been updated.  (The reference was updated in [PR 703](https://github.com/rust-lang/reference/pull/703).)
