### ISSUE TITLE
Tracking issue for RFC 2500, "Needle API (née Pattern API)"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#56345]
This is a tracking issue for the RFC "Needle API (née Pattern API)" (rust-lang/rfcs#2500).

Feature gates: 

- [ ] **`#![feature(needle)]`** (the traits and method in `core::needle` itself, and impl of these traits)
- [ ] **`#![feature(str_find_range)]`** (`find_range`, `rfind_range`, `match_ranges` and `rmatch_ranges` methods for `str`)
- [ ] **`#![feature(mut_str_needle_methods)]`** (`split_mut`, `matches_mut`, `trim_mut` etc for `str`)
- [ ] **`#![feature(slice_needle_methods)]`** (`find`, `matches`, `trim_matches`, `replace`, `split` etc for `[T]`)
- [ ] **`#![feature(os_str_needle_methods)]`** (`find`, `matches` etc for `OsStr`)

**Steps:**

- [ ] Implement the RFC (cc @rust-lang/libs @kennytm @bluss -- can anyone write up mentoring instructions?)
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

[**Unresolved questions:**](https://github.com/kennytm/rfcs/blob/pattern-3/text/0000-pattern-3.md#unresolved-questions)

- [ ] Currently, due to https://github.com/rust-lang/rfcs/pull/2089 and/or https://github.com/rust-lang/rfcs/pull/2289 not being implemented, using a `Haystack` in any algorithm would need to a redundant `where` clause.

- [ ] Naive vs. fast algorithm for `T: !Ord`

- [ ] Should we represent `SharedHaystack` using a more general concept of "cheaply cloneable"?

- [ ] With a benefit of simplified API, do we want to merge `Consumer` and `Searcher` into a single trait?

- [ ] Stabilization should [require](https://github.com/rust-lang/rfcs/pull/2500#issuecomment-438750377)  RFC 1672 (disjointness based on associated types).

**Comment by kennytm** [comment]
(Added a mention to RFC 1672 [as promised](https://github.com/rust-lang/rfcs/pull/2500#issuecomment-439950508))

**Comment by Avi-D-coder** [comment]
Will [`std::str::lines`](https://doc.rust-lang.org/std/primitive.str.html#method.lines) be implemented with using this API? 
[2500-needle.md#standard-library-changes](https://github.com/rust-lang/rfcs/blob/master/text/2500-needle.md#standard-library-changes) does not explicitly state this.
 I believe it would be a mostly backwards compatible change.

**Comment by SimonSapin** [comment]
Does it matter? This method only takes `&self`, and returns a dedicated type. Implementation detail changes that are black-box-invisible do not require RFCs. Or, by “mostly” do you mean you expect this change would be observable?

**Comment by Avi-D-coder** [comment]
Changing the internal implementation does appear to be API compatible. 
What I was intending to ask, but didn't, is if it would make sense to treat [`std::str::lines`](https://doc.rust-lang.org/std/primitive.str.html#method.lines) like the other `str` methods being deprecated and replaced by Needle API alternatives?

**Comment by SimonSapin** [comment]
`str::lines` is already implemented as `self.split_terminator('\n').map(LinesAnyMap)`, with `LinesAnyMap` stripping one trailing `\r` if any. (So equivalent to `split_terminator` with a "`\r\n` or `\n`" pattern.)

I think this is subtle enough to be worth a dedicated API. Even if it was as simple as `split('\n')`, I think this is a common enough use case.

**Comment by pickfire** [comment]
Any news on `slice::find`?

**Comment by crlf0710** [comment]
According to https://github.com/rust-lang/rust/pull/76901#issuecomment-880169952 and corresponding t-libs fcp, this rfc is withdrawn. Closing.

cc https://github.com/rust-lang/rfcs/pull/3154
