### ISSUE TITLE
Tracking issue: --persist-doctests flag for rustdoc

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#56925]
First implemented in https://github.com/rust-lang/rust/pull/56189, this flag allows users to save the compiled binaries created when rustdoc runs documentation tests.

Pending work:

- [ ] Related option to also save the processed code, for debugging purposes?
- [ ] Ability to cross-compile doctests and either save the binaries or run them through some test runner
- [ ] Combining the binaries into a singular test runner, like how libtest saves a single binary that runs unit tests

**Comment by jonhoo** [comment]
This would be really handy to have for getting code coverage for doctests. @QuietMisdreavus do you know what is left of the process to land this? Even in its current form it is very useful.

**Comment by lopopolo** [comment]
Hi folks, I've integrated this unstable flag into some code coverage infra for Artichoke Ruby. Results are published here: https://codecov.artichokeruby.org/.

I've filed a bug where it seems that doc comments with multiple examples only seem to persist one of the examples. `grcov` then reports some doc tests as uncovered.

I'm not sure if this is a rustdoc bug, a grcov bug, or a bug in how I have the coverage job configured.

Thanks for this feature! I hope it can be stabilized eventually.
