### ISSUE TITLE
Tracking issue for RFC 2235, "Implement Debug, Eq, PartialEq, and Hash for libc structs"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#57715]
This is a tracking issue for the RFC "Implement Debug, Eq, PartialEq, and Hash for libc structs" (rust-lang/rfcs#2235).

**Steps:**

- [ ] Implement the RFC (cc @rust-lang/libs @Susurrus)
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- [ ] Is it possible to just add `#[derive(Debug, Eq, Hash, PartialEq)]` since the `Copy` and `Clone` traits are directly implemented and not derived?

**Comment by Susurrus** [comment]
A problem that came up when implementing this is for implementing `Hash` for types that have floats or doubles in them. For the `fpreg_t` struct I did the following:
```rust
impl std::hash::Hash for fpreg_t {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.d.to_bits().hash(state);
    }
}
```

We should decide if we want to handle this: avoid it entirely for types that have floats or doubles, implement them like I did above, or sort out a "better" way to deal with hashing them.

**Comment by gnzlbg** [comment]
Many types still don't implement all of the traits, e.g., grep on `libc` for `missing_debug_implementations`, for example. 

* Some types can't easily `derive(Debug)` because they are `repr(packed)`. 
* Some types can't easily derive most of the traits because they contain arrays with more than 32 elements.

**Comment by jonas-schievink** [comment]
@Susurrus is this fully implemented now? https://github.com/rust-lang/libc/pull/1271 seems to indicate so.

**Comment by gnzlbg** [comment]
It’s mostly implemented, but there is still the unresolved questions about
enforcing requiring this and also about whether to enable this by default.

**Comment by joshtriplett** [comment]
This is mostly implemented, and to the extent it isn't, it's a libc issue rather than a rust-lang/rust issue. Closing; please feel free to open an issue on libc for any remaining aspects of it.
