### ISSUE TITLE
issue triage: closures, lifetimes, and nll

### ISSUE THREAD

**Issue by memoryruins** [rust-lang/rust#57964]
Most of the issues listed below appear ready to be closed or tagged. The check boxes are there to mark after a decision has been made on their respective threads (including if an issue is decided to be left open).

@pnkfelix @matthewjasper mind checking these out? what started as a general triage, ended up accumulating a bit of fixed-by-nll issues. although not all nll-related, the other issues are generally in areas you could help make a final decision on.

## now compiles on both editions

 `rustc: 1.32.0`

The following issues previously did not compile.
These appear ready to close, unless if any need a test.

- [x] [failure to infer move mode for a variable when the move is from `*x`](https://github.com/rust-lang/rust/issues/23675) #23675
- [x] [Incorrect closure type deduced despite move keyword](https://github.com/rust-lang/rust/issues/44336) #44336
- [x]  [Rustc confuses lifetimes of different unrelated variables of type &'static str when implementing a trait for &'a str](https://github.com/rust-lang/rust/issues/26448) #26448
- [x] [Unexpected lifetime issue when comparing Option<&i32](https://github.com/rust-lang/rust/issues/42966) #42966
- [x] [Incorrect lifetime error with a generic FnMut after annotating the type in a closure.](https://github.com/rust-lang/rust/issues/22557) #22557

## now compiles on 2018
`rustc: 1.32.0`

cc @rust-lang/wg-compiler-nll 

The following issues previously did not compile, but now do on 2018.
They also compile on 2015 with`#![feature(nll)]`.

- [x] [Weird lifetime error with closure and early-bound lifetime](https://github.com/rust-lang/rust/issues/28092) #28092
   * (example in description compiles in both editions, but a variant was identified that still exhibits the original problem.)
- [x] [Closures cause unnecessary borrows](https://github.com/rust-lang/rust/issues/23591) #23591
- [x] [Lifetime elision is too greedy without explicit type declaration](https://github.com/rust-lang/rust/issues/39943) #39943 
- [x] [Ref<T> and &T have different lifetime requirements](https://github.com/rust-lang/rust/issues/37785) #37785
- [x] [`if let` keeps borrows too long](https://github.com/rust-lang/rust/issues/43407) #43407
- [x] [Compiler gets lifetime scope wrong](https://github.com/rust-lang/rust/issues/28970) #28970
- [x] [Borrow checker gets confused with a mutable pointer which should be moved](https://github.com/rust-lang/rust/issues/27487) #27487 
- [x] [Slice pattern incorrectly report double borrow](https://github.com/rust-lang/rust/issues/37302) #37302
- [x] [Borrow checker false dropped while still borrowed](https://github.com/rust-lang/rust/issues/38915) #38915
- [x] [Spurious "borrowed value does not live long enough" when calling a function through a function pointer](https://github.com/rust-lang/rust/issues/49073) #49073

## now compiles on beta / nightly on both editions
`rust version 1.34.0-nightly (da6ab956e 2019-01-27)`

needs test?

- [x] [Adding Deref impl affects lifetime bounds of other methods](https://github.com/rust-lang/rust/issues/27697) #27697

## now (correctly) rejected on beta / nightly on both editions

These appear ready to close, unless if any need a test.

- [x] [HRTB bug in streaming iterator](https://github.com/rust-lang/rust/issues/30786) #30786

**Comment by memoryruins** [comment]
I've begun to comment on the individual issues with the updates and errors, as well as tagging fixed-by-nll where it seems fit. Removed #30127 from the list because it still errors on 2018 only after trying to print something out.

**Comment by pnkfelix** [comment]
tagging as metabug.

In general most of these issues are tagged NLL-fixed-by-NLL and so they'll tend to stay open until #57804 is addressed. Which means I don't see much point in trying to assign high priority to this issue (since most of the work items cannot be addressed until #57804 is addressed.)

**Comment by pnkfelix** [comment]
Hey lets start closing some of these that are fixed now that NLL is on for all editions in stable!

**Comment by pnkfelix** [comment]
oh wait:  we cannot close the ones that correspond to errors-downgraded-to-warnings I think, because most of those are soundness issues, and we probably need to wait until we stop the downgrading-to-warnings before we close all those issues. :cry:

**Comment by crlf0710** [comment]
@pnkfelix  #30786 has test added in #62519  Maybe we can tick the last box... and maybe close this issue?
