### ISSUE TITLE
Tracking issue for musl host toolchain

### ISSUE THREAD

**Issue by mati865** [rust-lang/rust#59302]
TODO:
- [x] Installable host toolchain
  - [ ] Rustup support
- [ ] Tests passing as the host
- [ ] Convenient way to link dynamically (e.g. `$arch-unknown-linux-dynmusl` triple)

For people looking how to use as it dynamic target:
```bash
RUSTFLAGS="-C target-feature=-crt-static" cargo build
```

**Comment by wangbj** [comment]
It seems `x86_64-unknown-linux-musl` target doesn't honor `--enable-default-pie`, a different behavior compare to `x86_64-unknown-linux-gnu`. Is this a known issue?

**Comment by mati865** [comment]
@wangbj I don't think Rust supports `--enable-default-pie` for any target. Could you provide more details?

**Comment by wangbj** [comment]
hmm, the problem seems caused by `musl-gcc` wrapper instead of `rustc`:

$ musl-gcc -v 2>&1 | grep --color=auto pie
Reading specs from /usr/share/dpkg/no-**pie**-compile.specs
Reading specs from /usr/share/dpkg/no-**pie**-link.specs
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-`pie` --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu

$ gcc -v 2>&1 | grep --color=auto pie
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-**pie** --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu

`--enable-default-pie` is a gcc configure flag. sorry for the noise.

**Comment by Cogitri** [comment]
FWIW, Void has been hacking around this for some time: https://github.com/void-linux/void-packages/blob/742a7d53eb0b373bf8dad3b51db3380c5cdf8dc1/srcpkgs/rust/patches/musl-dont-use-crt-static.patch and https://github.com/void-linux/void-packages/blob/742a7d53eb0b373bf8dad3b51db3380c5cdf8dc1/srcpkgs/rust/patches/link-musl-dynamically.patch

I'm currently working on this for Alpine too (BTW, maybe I can ping you on the PR for this @mati865 so you can take a look at it?).

**Comment by mati865** [comment]
I knew about Alpine and Void. IMO Alpine approach is better because `<arch>-unknown-linux-musl` remain static by default (it behaves like upstream) and new target `<arch>-alpine-linux-musl` links dynamically by default.

I had looked at that PR and `libc` changes will be incompatible with upstream rust behaviour. Official Rust packages when statically linking to musl create executables that all fully static (run basically everywhere), that patch will create static executables that depend on musl runtime (use have to install musl to be able to run them).

**Comment by Cogitri** [comment]
Yup, but at least on Void we've come to terms that the Rust in the repos is only really meant for packages in the repos, while users interested in rust development should use upstream Rust via rustip.

**Comment by smaeul** [comment]
> I had looked at that PR and `libc` changes will be incompatible with upstream rust behaviour. Official Rust packages when statically linking to musl create executables that all fully static (run basically everywhere), that patch will create static executables that depend on musl runtime (use have to install musl to be able to run them).

That doesn't make sense. Static executables by definition don't depend on having musl installed. Are you referring to rust-lang/libc#1327? That change would require having a musl-targeting toolchain installed for  *rustc* to *link* musl-targeting binaries. But any static binaries compiled by rustc would still be totally independent and require no musl installation.

**Comment by mati865** [comment]
@smaeul I'm referring to https://github.com/alpinelinux/aports/blob/21c1983ce828ead1afc9e80aa77ede330c662182/community/rust/link-musl-dynamically.patch

**Comment by smaeul** [comment]
@mati865 Okay, so that patch is misnamed. It doesn't have anything to do with static versus dynamic linking. It makes the same change as rust-lang/libc#1327 -- using the C toolchain's copy of `libc.a` instead of bundling it inside `liblibc.rlib`.

Alpine also ships [custom targets](https://github.com/alpinelinux/aports/blob/21c1983ce828ead1afc9e80aa77ede330c662182/community/rust/alpine-target.patch) that use the C toolchain's `crt*.o` instead of `rustc` shipping a second copy. Since on Alpine targets `rustc`'s copy of `crt*.o` are not used, this patch stops `rustc` from making the copy. (This change is unrelated to the `liblibc` change.)

**Comment by mati865** [comment]
Thanks for the explanation.

**Comment by thedrow** [comment]
#53968 also seems to be related but it's not included in the OP's checklist.
Am I correct?

**Comment by mati865** [comment]
Updated

**Comment by thedrow** [comment]
#61328 also seems important.

**Comment by mati865** [comment]
I don't see how #61328 relates to this, there is no issue when using `target-feature=-crt-static`.
It applies to musl toolchain in general but it has nothing to do with using musl toolchain natively.

**Comment by gnzlbg** [comment]
In https://github.com/rust-lang/libc/pull/1327, a `#[cfg(target_env = "dyn_musl")]` or similar was proposed to support both statically and dynamically linked musl environments. I don't know if that would be a good way to make progress here though. 

How do other run-times deal with this ? Is it possible to statically link glibc and others into Rust binaries ? Maybe we need a `#[cfg(target_env_linkage = "static/dynamic/...")]` system instead of duplicating `target_env`s per target.

**Comment by mati865** [comment]
AFAIK musl is the only target which you can link statically and dynamically at same time.

Duplicating target_env is easy but for me it sounds like a bad workaround because user would have to install 2 toolchains that have exactly the same libs and the only difference comes to `target-feature=-crt-static`.
With static nobundle it would be third 99% identical toolchain.

Ideally they should use single shared sysroot because all that is required can be handled at runtime.
I think Rust is not capable of it yet so this would have to go through RFC first.

**Comment by smaeul** [comment]
> How do other run-times deal with this ? Is it possible to statically link glibc and others into Rust binaries ? 

The two [relevant target attributes](https://github.com/rust-lang/rust/blob/9210359b18185f46af9c0f30cc3d2678394930ef/src/librustc_target/spec/mod.rs#L694) are `crt_static_respected` and `crt_static_allows_dylibs`.

For glibc (and all other non-musl unix-like platforms), `crt_static_respected` is false, so the `-C target-feature=+crt-static` option is ignored by the backend and still dynamically links libc, and therefore dynamic native libraries can still be linked. So the only effect of the option is that it matches
`#[cfg(target_feature = "crt-static")]`.

For MSVC, `crt_static_respected` and `crt_static_allows_dylibs` are both true, so `-C target-feature=+crt-static` only affects the C runtime, and other (rust or native) libraries can still be loaded as DLLs. This is because on Windows, there's not really such a thing as a "static binary".

musl is in the unique situation of `crt_static_respected` being true and `crt_static_allows_dylibs` being false. Since musl uses ELF (and this would apply to glibc too if it supported static linking), linking libc statically requires all other libraries to also be linked statically. For native libraries, this means `#[link(kind = "static")]` or `#[link(kind = "static-nobundle)]"`.

`rustc` currently handles this limitation correctly for rust libraries and direct native dependencies, but not for native libraries that are transitive dependencies of a dependent crate.

I had a patch (#55566) that "fixed" this by changing the semantics of `#[link]` with no `kind` in the `+crt-static` and not `crt_static_allows_dylibs` case. But the default kind is documented to be `dylib`, so that change was unacceptable. Instead, we need a patch to produce an error, similar to [the non-transitive case here](https://github.com/rust-lang/rust/blob/b43eb4235ac43c822d903ad26ed806f34cc1a14a/src/librustc/middle/dependency_format.rs#L141).

> Maybe we need a #[cfg(target_env_linkage = "static/dynamic/...")] system instead of duplicating target_envs per target.

We already have that: `#[cfg(target_feature = "crt-static")]`.

-----

The problem in rust-lang/libc#1327 is that we try to support cross-compilation to musl without having the proper sysroot installed. The whole `musl_root` system is a giant hack to support that, and it breaks in the native case, where we want to use the `libc.a` that is actually present on the system (and updated by the package manager, etc.). Distributions that ship a native musl rust have to add a patch similar to the one in that PR (specifically e.g. [this one for Adélie and Gentoo](https://github.com/smaeul/portage-overlay/blob/master/dev-lang/rust/files/0030-libc-linkage.patch)).

**Comment by Cogitri** [comment]
> I had a patch (#55566) that "fixed" this

Fwiw Alpine Linux ships a similar patch (although we don't use crt-static for pur distro packages). Good to know what's the status on that, thanks.

https://github.com/alpinelinux/aports/blob/master/community/rust/musl-fix-static-linking.patch

**Comment by gnzlbg** [comment]
> The problem in rust-lang/libc#1327 is that we try to support cross-compilation to musl without having the proper sysroot installed.

Many production users rely on this feature, so we are kind of constrained on not breaking this. If the only way to achieve that is have a second set of targets, then that's the way it is.

**Comment by smaeul** [comment]
> Many production users rely on this feature, so we are kind of constrained on not breaking this. If the only way to achieve that is have a second set of targets, then that's the way it is.

What about shipping `libc.a` alongside rust, like we already do for `crt*.o`? Then we could link it `static-nobundle` from `liblibc.rlib` instead of bundling it inside. And then if we only add a `-L` for that directory to the linker args when cross-compiling, it would work properly for the native case as well. (And distro packagers could simply `rm` rust's copy of `libc.a` instead of patching).

**Comment by gnzlbg** [comment]
I think I would prefer something that also works great for distro packages. While they could tune things when packaging, a distro that uses musl as its stdlib, will have users that might install rust via rustup, and they will want their "default" rust target to dynamically link the system musl, instead of doing something else, right?

**Comment by smaeul** [comment]
Yes. That's why most (all except Void) musl distributions ship distro-specific targets (usually matching their `$CHOST`) that default to dynamic linking. On the other hand, the "static by default" semantics of the current official musl targets are well documented, and `x86_64-unknown-linux-musl` is already available in rustup.

The two feasible solutions I can think of are:
1. Introduce new targets that are dynamic by default – by changing the vendor (e.g. `x86_64-dynamic-linux-musl`), **not** by changing the environment (e.g. `x86_64-unknown-linux-musldyn`), which would break all existing uses of `#[cfg(target_env = "musl")]`.
2. (At the risk of making the mess worse) override the `crt_static_default = true` in musl targets when the host environment is also musl, or alternatively change it to `crt_static_default = false` and override it when cross compiling.

**Comment by smaeul** [comment]
Linking these here for future reference, more cases where bundling `libc.a` into `liblibc.rlib` breaks things:
https://github.com/rust-lang/rust/issues/71564
https://github.com/rust-lang/libc/pull/1704

**Comment by msrd0** [comment]
Another problem I noticed trying to compile/run the rust compiler on a musl host like Alpine Linux is that using the jemallocator for the compiler itself does not seem to work. Given that rust is known to run slower with musl's default allocator than with jemalloc, I tried enabling `jemalloc = true` in rustc's config file (rustc version 1.48). However, probably due to the [rust compiler only referencing jemalloc](https://github.com/rust-lang/rust/blob/master/compiler/rustc/src/main.rs#L2), and the [jemalloc-sys crate forcing a prefix on musl targets](https://github.com/gnzlbg/jemallocator/blob/master/jemalloc-sys/build.rs#L45), this seems to have no effect.

**Comment by Cogitri** [comment]
FWIW Rust recently got a new allocator with musl 1.2 (mallocng), so it might be worth to benchmark that again :)
We've been avoiding jemalloc whereever possible on Alpine Linux and even patched it out of some packages, IIRC it doesn't work too well on musl, but maybe that has changed since we last tried using it.

**Comment by msrd0** [comment]
I don't know much about jemalloc, I was just playing around to see if it improved stuff and had to realize that the compiler didn't seem to use it. So I don't know if the performance issues I'm seeing are caused by the allocator, but other rust projects like [ripgrep](https://github.com/BurntSushi/ripgrep/commit/03bf37ff4a29361c47843369f7d3dc5689b8fdac) have seen the allocator change to cause performance regressions on musl targets (and that one is also not patched on alpine).

Unfortunately, `alpine:edge` with `musl 1.2.2_pre6-r0` and rust 1.47 from the alpine repos is consistently 5 to 10 seconds slower than `alpine` with `musl 1.1.24-r10` and rust 1.47 compiled with a barely modified `APKBUILD` from aports (that is, enabling clippy and rustfmt tools). So it does not seem like the new allocator changed a great deal. Also, alpine is up to 30% slower compared to the official rust docker image when running `cargo build` for [gotham](https://github.com/gotham-rs/gotham). My docker host system is ArchLinux in case it matters (which performs the best but that's an unfair comparison).

**Comment by haraldh** [comment]
Opened a new issue against the musl version used in building https://github.com/rust-lang/rust/issues/91178

**Comment by yshui** [comment]
is it possible to have dylib/cdylib with `+crt-static`?

**Comment by bjorn3** [comment]
Musl doesn't support that as the dynamic linker is part of libc and it doesn't support multiple copies of libc in a single process like on basically every Unix. The only mainstream system where that is possible is Windows as there the dynamic linker is part of the kernel and libc is not the system abi and multiple libc copies can co-exist in a single process.

**Comment by yshui** [comment]
i believe it would be possible to create "statically linked" shared library. i.e. all libc symbols are resolved at link time and the shared library is completely self-contained that it neither exposes nor references any libc symbols. we would also need the equivalent of `-fno-semantic-interposition` etc., and other things i might have missed, but i think it is doable at least in theory.

it might cause some confusion since two symbols ostensibly have the same name can actually be completely unrelated to each other, (which, btw, already happens in rust today if my project happens to use different versions of the same crate), but the shared library should otherwise work.

**Comment by bjorn3** [comment]
There are various pieces of global state in libc as well as some process state like the tls register for which each libc instance assumes exclusive access.

**Comment by yshui** [comment]
Ah right, yeah I forgot about that. That definitely makes this unsupportable from Rust's perspective. There goes my dreams :'(

OTOH it's probably not _that_ bad? I'd imagine process state and tls register setup generally happen before `main` and probably isn't going to be touched again when a shared library is loaded. I can probably still make it work as a hack.

**Comment by bjorn3** [comment]
TLS registering also happens on every dlopen and pthread_create, so don't use either from within your statically linked dylib. And you better make sure that the host program uses musl as libc as errno is stored at a fixed offset from the TLS register, which other libc's may use for other purposes.

**Comment by WhyNotHugo** [comment]
Would a patch implementing [the suggestion above](https://github.com/rust-lang/rust/issues/59302#issuecomment-509029247) be acceptable?

> override the crt_static_default = true in musl targets when the host environment is also musl, or alternatively change it to crt_static_default = false and override it when cross compiling.

I believe this yields a sane/expected behaviour when compiling x86_64-unknown-linux-musl on x86_64-unknown-linux-musl distributions, but also won't break the workflow of users who cross-compile without a musl sysroot.
