### ISSUE TITLE
Tracking issue for RFC 2565, "Attributes in formal function parameter position"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#60406]
This is a tracking issue for the RFC "Attributes in formal function parameter position" (rust-lang/rfcs#2565).

**Steps:**

- [x] Implement the RFC – https://github.com/rust-lang/rust/pull/60669
- [x] Adjust documentation (https://github.com/rust-lang-nursery/reference/pull/657)
- [x] Stabilization PR (https://github.com/rust-lang/rust/pull/64010)
- [x] Fixing https://github.com/rust-lang/rust/issues/61238

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

None.

This issue has been assigned to @c410-f3r via [this comment](https://github.com/rust-lang/rust/issues/60406#issuecomment-526314655).

**Comment by c410-f3r** [comment]
Wow! I've always wanted to contribute to Rustc itself and this is a nice opportunity. I will try to implement this feature with some mentoring.

**Comment by Centril** [comment]
@petrochenkov You are familiar with most of this, right? Could you perhaps write up some instructions?

**Comment by Centril** [comment]
Partial implementation completed as of 2019-06-12.
Implementation was done in https://github.com/rust-lang/rust/pull/60669 by @c410-f3r which was reviewed by @petrochenkov and @Centril.

https://github.com/rust-lang/rust/issues/61238 still needs to be done for a full implementation.

**Comment by Centril** [comment]
#61238 was fixed on the 2019-07-29 in https://github.com/rust-lang/rust/pull/61856. The PR was written by @c410-f3r and reviewed by @matthewjasper, @petrochenkov, and @oli-obk.

The RFC is now fully implemented.

Setting the earliest date for a stabilization report to 6 weeks from now which is on 2019-09-09.

**Comment by c410-f3r** [comment]
@Centril Which type of additional documentation is necessary to tick `Adjust documentation`? #62683 has been merged.

**Comment by Centril** [comment]
> ~@Centril Which type of additional documentation is necessary to tick `Adjust documentation`? #62683 has been merged.~

This primarily refers to the https://github.com/rust-lang-nursery/reference/ which can be shortly fixed after stabilization. In this case it should be straightforward to fix I think.

**Comment by Centril** [comment]
A bug https://github.com/rust-lang/rust/issues/63210 was filed on 2019-08-02 wherein the attributes on formal parameters would not be passed to macros. The issue was forgetting to call the relevant method in `fn print_arg` in the pretty printer. In https://github.com/rust-lang/rust/pull/63212, written by @Centril on 2019-08-02 and reviewed by @davidtwco, the issue aforementioned was fixed.

**Comment by theduke** [comment]
Would love for this feature to hit stable in `1.39`. 

Is that a doable timeframe, @Centril ?

**Comment by Centril** [comment]
Seems plausible; 1.39 branches on the 26th; - 10 days for FCP - some time to write a report.

**Comment by c410-f3r** [comment]
If possible, I would like to write the report, as well as the stabilization PR and remaining documentation

**Comment by Centril** [comment]
@c410-f3r Sure. Here's a report you can use as a template: https://github.com/rust-lang/rust/pull/61682#issuecomment-502472847. I'd like to review and vet the report first however before it is published on a stabilization PR.

**Comment by Centril** [comment]
We discussed this on the language team meeting and found that we should indeed move ahead wit stabilizing it.

**Comment by Centril** [comment]
The stabilization proposal is up: https://github.com/rust-lang/rust/pull/64010.

**Comment by Centril** [comment]
Stabilization is done; documentation will be done in the reference. Closing as nothing remains to do.

**Comment by c410-f3r** [comment]
It was a long journey and I would like to thank @Robbepop for the RFC and all the PR reviewers, specially @petrochenkov and @Centril.

**Comment by theduke** [comment]
Also thanks from me, this is much needed for improving proc macro ergonomics in juniper
