### ISSUE TITLE
Tracking issue for `#![feature(slice_patterns)]`

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#62254]
This is a tracking issue for the feature gate `#![feature(slice_patterns)]` covering the following RFCs:
- "Finalize syntax for slice patterns with subslices" (rust-lang/rfcs#2359),
- "Make `..` a pattern syntactically" (rust-lang/rfcs#2707),
- "Array pattern adjustments" (rust-lang/rfcs#495).

For the old tracking issue see https://github.com/rust-lang/rust/issues/23121.

**Steps:**

- [x] Implement the changes in rust-lang/rfcs#2359 and rust-lang/rfcs#2707
      (cc @rust-lang/compiler -- can anyone write up mentoring instructions?)
- [ ] Adjust documentation ([see instructions on rustc-guide][doc-guide])
- [x] Stabilization PR (https://github.com/rust-lang/rust/pull/67712)

[stabilization-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs

**Unresolved questions:**

None thus far.

**Comment by Centril** [comment]
For now, I'm working on the syntactic aspect of supporting `..` as a valid pattern syntactic pattern.

**Comment by Centril** [comment]
The syntax change in https://github.com/rust-lang/rfcs/pull/2707 was implemented on the 2019-07-28 in https://github.com/rust-lang/rust/pull/62550 (author: @Centril, reviewer: @petrochenkov).

What remains now is:

- [ ] Adding more tests for the syntax.

- [ ] Verifying the semantics in terms of type checking and making changes as needed.

Before / during stabilization, we must also:

- [ ] Organize the tests.

**Comment by Centril** [comment]
One remaining issue is also https://github.com/rust-lang/rust/issues/53820.
cc @RalfJung and @varkor re. ^-- Not sure whether that's blocking or not.

**Comment by RalfJung** [comment]
Not sure either. Someone will have to make the call if it is okay for matching on big arrays to stack-overflow.

Last time I checked, on Windows, matching on `[0u8; 1024]` is actually enough to trigger the error.

**Comment by Centril** [comment]
https://github.com/rust-lang/rust/pull/63111 and https://github.com/rust-lang/rust/pull/63129 have both landed. In combination previously existing tests I believe we can be confident in the implementation now. The only remaining issue is https://github.com/rust-lang/rust/issues/53820 now.

**Comment by estebank** [comment]
@Centril would having an arbitrary size limit in arrays used in patterns help with masking #53820 to stabilize earlier?

**Comment by Centril** [comment]
@estebank Seems like bad policy to encode such arbitrary limits in the language itself? At minimum I want to know why it is the case that https://github.com/rust-lang/rust/issues/53820 happens and whether it is fundamental or a bug that we can fix soon-ish.

**Comment by varkor** [comment]
When this is stable, we should suggest using `tail @ ..` rather than `..tail`, e.g. in:
```rust
fn foo(x: &[u32]) {
    match x {
        [..tail] => {} // error
    }
}
```

**Comment by matthewjasper** [comment]
#66502 is blocking this now.

**Comment by Nadrieril** [comment]
>     * [ ]  One remaining issue is also #53820.
>       cc RalfJung and varkor re. ^-- Not sure whether that's blocking or not.

This is now fixed :)

**Comment by varkor** [comment]
#66502 is now fixed, so I think there's nothing remaining blocking stabilisation.

**Comment by matthewjasper** [comment]
There's #66934. I probably want to look at the tests that we have for slice patterns in const contexts once that's fixed.

**Comment by Centril** [comment]
We're definitely close to having something shippable, but before a report is written, I think that we should:

- Fix https://github.com/rust-lang/rust/issues/66934.
- Then wait 6 weeks without incident.
- Wait for @matthewjasper to feel comfortable and give the green light on the test suite & implementation.

**Comment by Centril** [comment]
We discussed this briefly in Thursday's language team meeting. I basically informed those present (only 3, including me) of ^--- and our almost-readiness for stabilization.

**Comment by Centril** [comment]
The stabilization PR and proposal is up in https://github.com/rust-lang/rust/pull/67712.

**Comment by Centril** [comment]
Subslice patterns were stabilized in https://github.com/rust-lang/rust/pull/67712.
Reference documentation is tracked in https://github.com/rust-lang/reference/issues/739.
Book documentation in the book is tracked in https://github.com/rust-lang/book/issues/2225.

**Comment by KSBilodeau** [comment]
As a clarification, concerns regarding https://github.com/rust-lang/rust/issues/37854 were removed from this new issue list; Is there still a conflict of patterns?
