### ISSUE TITLE
Tracking issue for debug_map_key_value

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/rust#62482]
This is a tracking issue for `debug_map_key_value` (https://github.com/rust-lang/rfcs/pull/2696)

**Steps:**

- [x] Implement the RFC (#60458)
- [x] Adjust documentation ([see instructions on rustc-guide][doc-guide])
- [x] Stabilization PR ([see instructions on rustc-guide][stabilization-guide]) (https://github.com/rust-lang/rust/pull/68200)

[stabilization-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs

**Unresolved questions:**

**Comment by KodrAus** [comment]
So I’m using this feature to [provide an adapter between `serde::Serialize` and `fmt::Debug`](https://github.com/KodrAus/serde_fmt) that naturally preserves formatting flags and stays aligned with any changes to `std::fmt`.

**Comment by crlf0710** [comment]
Already implemented and stablized. Closing.
