### ISSUE TITLE
Tracking issue for `#!feature(async_unsafe)]` (RFC 2394)

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#62501]
This is a tracking issue for `#![feature(async_unsafe)]` (rust-lang/rfcs#2394).
The feature gate provides the `async unsafe fn` syntax.

**Steps:**

- [ ] Split the feature gate (https://github.com/rust-lang/rust/issues/62500)
- [ ] Adjust documentation ([see instructions on rustc-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-guide][stabilization-guide])

[stabilization-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs

**Unresolved questions:**

- [ ] Is this the right design wrt. calling `async unsafe fn`?

**Comment by Centril** [comment]
I was convinced not to feature gate this after all (see #62149 (comment)). Sorry about the noise!
