### ISSUE TITLE
Tracking issue for map_first_last: first/last methods on BTreeSet and BTreeMap

### ISSUE THREAD

**Issue by nexplor** [rust-lang/rust#62924]
Feature gate: `#![feature(map_first_last)]`

### Public API

```rust
impl<T> BTreeSet<T> {
    pub fn first(&self) -> Option<&T> where T: Ord;
    pub fn last(&self) -> Option<&T> where T: Ord;
    pub fn pop_first(&mut self) -> Option<T> where T: Ord;
    pub fn pop_last(&mut self) -> Option<T> where T: Ord;
}

impl<K, V> BTreeMap<K, V> {
    pub fn first_key_value(&self) -> Option<(&K, &V)> where K: Ord;
    pub fn last_key_value(&self) -> Option<(&K, &V)> where K: Ord;
    pub fn first_entry(&mut self) -> Option<OccupiedEntry<'_, K, V>> where K: Ord;
    pub fn last_entry(&mut self) -> Option<OccupiedEntry<'_, K, V>> where K: Ord;
    pub fn pop_first(&mut self) -> Option<(K, V)> where K: Ord;
    pub fn pop_last(&mut self) -> Option<(K, V)> where K: Ord;
}
```

### Steps / History

- [x] Implementation: #65637
- [x] Changes: #70850
- [x] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- [x] Naming (min/max, first/last, front/back, .. ?)
- [ ] For BTreeMap: Separate entry and pair (and just-value) functions?

----

Original issue title: Finding minimum/maximum element in BTreeMap does twice the required amount of computation

Original issue text:

The standard way of finding the minimum element in BTreeMap is `tree_map.iter().next()`

The `iter()` function creates a `btree_map::Iter`, which finds both the minimum and maximum element to create its internal instance of `btree_map::Range`.

This is unnecessary, and a `BTreeMap::get_min` or similar function could be provided, which would just internally call the `first_leaf_edge` private function, without needing to call `last_leaf_edge`.

Ditto for finding the maximum element.

**Comment by cuviper** [comment]
Here are what the other collections call similar methods:

- `[T]` slices (and `Vec` via deref) have `first`/`first_mut` and `last`/`last_mut`.
- `VecDeque` and `LinkedList` have `front`/`front_mut` and `back`/`back_mut`.
- `BinaryHeap` has `peek` and `peek_mut`, i.e. only from the front.
- `HashMap` and `HashSet` are unordered, and have no such methods.
- `str` and `String` have no such methods.

**Comment by cuviper** [comment]
#59947 is related -- `Iterator::min`/`max` are even worse since they naively walk everything.

**Comment by ssomers** [comment]
#64820 is also related - BTreeSet is_subset, intersection and difference now always do this double work (they actually want both min and max at the same time, but requesting both `next` and `next_back` from the same iterator that may only see one element is not the most straightforward code).

I naively thought the redundant data (the other end and iterator length) and code would all get optimized away from an expression like `tree_map.iter().next()`, but after writing out code to avoid the double work in BTreeSet::is_subset, benchmarks report a 20 to 40% speed boost, for the cases where it can quickly bail out after getting min and max either side and comparing them. I'm going to measure the effect by adding the desired functions to map, and if successful I can put them in a pull request, but I have no idea what the procedure is for adding APIs. I vote for `first` and `last` as names.

**Comment by ssomers** [comment]
According to a raw benchmark, the specialized functions are about 3 times faster than `.iter().next()`. By the way, `.range(..).next()` is a little slower, despite not bothering with iterator length, because `iter()` has access to internals to construct its unbounded range.

Details: code in liballoc/benches/btree/map.rs:
```
fn bench_first_and_last(b: &mut Bencher, size: i32) {
    let map: BTreeMap<_, _> = (0..size).map(|i| (i, i)).collect();
    b.iter(|| {
        for _ in 0..10 {
            black_box(map.first_key_value());
            black_box(map.last_key_value());
        }
    });
}

#[bench]
pub fn first_and_last_0(b: &mut Bencher) {
    bench_first_and_last(b, 0);
}

#[bench]
pub fn first_and_last_100(b: &mut Bencher) {
    bench_first_and_last(b, 100);
}

#[bench]
pub fn first_and_last_10k(b: &mut Bencher) {
    bench_first_and_last(b, 10_000);
}
```
Results using the new functions:
```
test btree::map::first_and_last_0                        ... bench:          14 ns/iter (+/- 0)
test btree::map::first_and_last_100                      ... bench:          37 ns/iter (+/- 2)
test btree::map::first_and_last_10k                      ... bench:          54 ns/iter (+/- 3)

test btree::map::first_and_last_0                        ... bench:          14 ns/iter (+/- 0)
test btree::map::first_and_last_100                      ... bench:          42 ns/iter (+/- 1)
test btree::map::first_and_last_10k                      ... bench:          56 ns/iter (+/- 2)

test btree::map::first_and_last_0                        ... bench:          14 ns/iter (+/- 0)
test btree::map::first_and_last_100                      ... bench:          37 ns/iter (+/- 1)
test btree::map::first_and_last_10k                      ... bench:          54 ns/iter (+/- 2)

test btree::map::first_and_last_0                        ... bench:          14 ns/iter (+/- 0)
test btree::map::first_and_last_100                      ... bench:          37 ns/iter (+/- 0)
test btree::map::first_and_last_10k                      ... bench:          55 ns/iter (+/- 1)
```
Results using .iter().next() / .iter().next_back():
```
test btree::map::first_and_last_0                        ... bench:          65 ns/iter (+/- 1)
test btree::map::first_and_last_100                      ... bench:          97 ns/iter (+/- 3)
test btree::map::first_and_last_10k                      ... bench:         141 ns/iter (+/- 0)

test btree::map::first_and_last_0                        ... bench:          64 ns/iter (+/- 1)
test btree::map::first_and_last_100                      ... bench:          97 ns/iter (+/- 3)
test btree::map::first_and_last_10k                      ... bench:         131 ns/iter (+/- 4)

test btree::map::first_and_last_0                        ... bench:          65 ns/iter (+/- 2)
test btree::map::first_and_last_100                      ... bench:          96 ns/iter (+/- 3)
test btree::map::first_and_last_10k                      ... bench:         131 ns/iter (+/- 7)

test btree::map::first_and_last_0                        ... bench:          65 ns/iter (+/- 2)
test btree::map::first_and_last_100                      ... bench:          99 ns/iter (+/- 2)
test btree::map::first_and_last_10k                      ... bench:         131 ns/iter (+/- 15)
```

Results using .range().next() / .range().next_back():
```
test btree::map::first_and_last_0                        ... bench:          66 ns/iter (+/- 3)
test btree::map::first_and_last_100                      ... bench:         100 ns/iter (+/- 1)
test btree::map::first_and_last_10k                      ... bench:         123 ns/iter (+/- 2)

test btree::map::first_and_last_0                        ... bench:          67 ns/iter (+/- 5)
test btree::map::first_and_last_100                      ... bench:         100 ns/iter (+/- 4)
test btree::map::first_and_last_10k                      ... bench:         127 ns/iter (+/- 4)

test btree::map::first_and_last_0                        ... bench:          66 ns/iter (+/- 1)
test btree::map::first_and_last_100                      ... bench:         101 ns/iter (+/- 6)
test btree::map::first_and_last_10k                      ... bench:         123 ns/iter (+/- 5)
```

**Comment by matklad** [comment]
I vote for min/max rather than first/last terminology. Rationale: I’ve recently had a bad bug when I used Rust’s BinaryHeap and assumed that pop yields a minimal item. If the API had used max in the method name, I wouldn’t have made the bug.

This case is similar: first is ambiguous, min is precise (and shorter ^^).

**Comment by ssomers** [comment]
I'm slightly in favour of min/max at the moment, having faced reverse iteration in (other) code with first/last names. It's a close call; min/max is ambiguous about performance, because many min/max functions out there are in fact linear searches.

**Comment by matklad** [comment]
Correctness is more important than performance, and the performance ambiguity is an a safe direction (operation is faster than it might seem)

**Comment by jmlMetaswitch** [comment]
Can we also get `take` forms that remove the entry at the same time? They are particularly useful in algorithms that repeatedly process the max/min and may add entries during that processing. I think that suggests (from the above) `max_key_value`, `max_entry`, `take_max_key_value` and the equivalent for `min`.

**Comment by ssomers** [comment]
I didn't add those back then because I thought they were intended to be, used through the entry API. But [using that in practice](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8efc36c4d0a2440d17b68faa7c2a988b) seems more complicated than I would want. There's no entry concept in BTreeSet, so `pop_X` seemed the only option there.

I wouldn't start mixing the naming scheme though. First/last or min/max (or something else) all the way.

I don't remember any discussion on whether it should be `pop` or `take` (or [`poll`] (https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html#pollFirstEntry--), anyony?) but there are lots of similar `pop`s in Rust's standard library, the existing `take`s on sets work with a particular key, and the other `take`s seem to take grab the entire contents.

**Comment by ssomers** [comment]
In the rust code base, there's only one use of this new API: [`last_entry`](https://github.com/rust-lang/miri/blob/master/src/shims/fs.rs#L59). But anyone could have a `feature(map_first_last)`, so not something I'd want to change without blessing.

By the way, that use would be slightly simpler if we had a `last_key` too. Should we? Is `last_key` trivial while `pop_last` would be worth while?

**Comment by ssomers** [comment]
And then there's the "_key_value" suffix. `get_key_value` was added recently next to `get` (which returns only the value), and it obviously needed some different name. Plain `last` or `max` returning key and value, next to the mutable `last_entry` or `max_entry`, seemed overly terse and somewhat inconsistent, so it got the same "_key_value" suffix.

But `pop_last` or `pop_max` doesn't have that terseness nor inconsistency in my mind. On the contrary, `pop_max_key_value` makes me wonder if I could pop only a key or only a value. `pop_max_key` does sound better, because it makes it clear what maximum we're talking about.

That means `max_key_value` sounds ambiguous to me now. What is the maximum of key,value pairs? Or maybe is it the value of the max key? `last_key_value` doesn't raise that first question so you don't stray into the second. `max_key_with_value`?

**Comment by pipehappy1** [comment]
randomly come across this. pop_first and pop_last are more appropriate than min/max since this is an iteration and an iteration comes with the first and ends with the last.

**Comment by ssomers** [comment]
@pipehappy1, I don't understand what you mean. Which "this" is an iteration?

Of course first and last correspond to the various forms of forward iteration on maps, but that doesn't imply first/last is any clearer than min/max.

I think both naming schemes are reasonable. Min/max when the caller can have a good notion of how keys are ordered, and really wants the minimum or maximum. As it stands, almost all members have an `Ord` bound, meaning the caller must indeed know that there is an intrinsic order on the key type, and since it's the only order around, min/max is rather clear. But many of methods don't need this bound, like BTreeMap::new and the methods discussed here. And funnily enough, the iterators that expose the order don't have this `Ord` bound, it's just documented in the methods ("sorted by key" or "in ascending order"). I don't think it was a conscious design decision.

Therefore, the first/last case is also reasonable, when the caller has no notion of key order and just wants to follow whatever order the container chooses, regardless of whether the container is a map or a vector (of pairs). But then it should not have the `Ord` bound.

**Comment by pipehappy1** [comment]
@ssomers That's quite clear and an insight. Both naming schemes get their reason. Thx

**Comment by ssomers** [comment]
I now think that the mutable methods first_entry/last_entry are pointless. The point of the `entry` interface is that you can read or write multiple things from an element, without looking up the same key more than once. In theory, first_entry/last_entry are constant time, and you need to have a mutable reference locking out other threads, so you can just invoke first_entry/last_entry twice for exotic use cases. In reality, first/last_entry are not constant time but need to descend the tree to a leaf, but most likely that could be optimized away.

Another point of `entry` is that it returns an `Entry` that has elegant methods to deal with vacant entries. But first_entry/last_entry now returns `Option<OccupiedEntry>`. Though `entry` does come with the price that, when invoked on a freshly created map, it allocates a root node, even if none will be needed.

Instead, it might be more clear to have mutable methods to access the first or last value.

**Comment by ssomers** [comment]
[Point made in internals](https://internals.rust-lang.org/t/btreemap-constant-time-first-last-iterators/12101): the fact that first/last_entry are not constant time is the real problem. The "twice" in the title of this issue is just peanuts, the "required amount of computation" matters more.

**Comment by frostyplanet** [comment]
Is there any plan to stablize thie feature ?

**Comment by BruceBrown** [comment]
minor example error for BTreeSet::last(). Shouldn't assert_eq!(map.first(), None); be assert_eq!(map.last(), None); ?

**Comment by ssomers** [comment]
Indeed, well spotted.

**Comment by BruceBrown** [comment]
makes you wonder if there are additional (cut and paste) errors in there...

**Comment by BruceBrown** [comment]
I'd also recommend initializing via: let mut a: BTreeSet<_> = (1..=3).collect(); rather than using multi-line initialization, in a few of the examples.

**Comment by ssomers** [comment]
I'm not sure the "professional" initialization style helps people understand the examples. I'd rather see some consensus throughout the documentation. Cousin `HashSet` has examples with `let set: HashSet<_> = [1, 2, 3].iter().cloned().collect();`

**Comment by bohdantrotsenko** [comment]
I came here to mention that I'd like `BTreeSet::pop_first()` to be merged into stable; as I ofter walk around it with `my_set.iter().next()` and removing the element.

**Comment by kootenpv** [comment]
> I came here to mention that I'd like `BTreeSet::pop_first()` to be merged into stable; as I ofter walk around it with `my_set.iter().next()` and removing the element.

Could you provide a working code example for this?

**Comment by frostyplanet** [comment]
> > I came here to mention that I'd like `BTreeSet::pop_first()` to be merged into stable; as I ofter walk around it with `my_set.iter().next()` and removing the element.
> 
> Could you provide a working code example for this? I get `immutable borrow later used by call` when using `my_set.iter().next()` before wanting to use `my_set.remove(value)`

It's not possible remove while iterating, because remove one item in the middle might change BTree structure and trigger rebalance.  It's only possible to add the keys that you want to delete to a list and remove them after iteration complete.

**Comment by BruceBrown** [comment]
Isn’t that the purpose of drain() and drain_filter()?
—Bruce

**Comment by BruceBrown** [comment]
actually, retain() is perhaps a better fit.

**Comment by ssomers** [comment]
The use case we're talking about is [popping an element from a set, while using the shrinking set each iteration](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=af331a6a1793e87660125e40b35212ec) (probably using it for something more obvious than asserting the obvious).

`drain_filter` and `retain` are not practical for this use case, because they always iterate the entire collection. They're designed for a very (too) particular use case. `drain` could be used, but it has no advantage over `remove` or `take`, and still requires looking up an element when you already know it is the first or last one (AKA min or max). In addition to the fact to find that element, in stable Rust, we need `iter()` which descends to leaves on both sides of the tree and we discard the element we don't need.

Though you could argue the latter point is merely `iter()`'s fault, because we often use it to iterate only forward or only backward and there is no reason to descend both sides of the tree at the start - that just simplifies the implementation if you do intermingle forward and backward iteration.

**Comment by kootenpv** [comment]
So my current approach for anyone interested is:

```rust
let drop_oldest = seen_ids.iter().cloned().next();
seen_ids.remove(&drop_oldest.unwrap());
```

Maybe someone knows a more optimized way.

**Comment by ssomers** [comment]
#86031 fixes the original issue title "Finding minimum/maximum element in BTreeMap does twice the required amount of computation", without introducing new functions. But there are more functions here, there's easy of use (either way, more functions is not necessarily easier), and benchmarks suggest that `first()` is still twice as fast as `iter().next()`.

**Comment by avl** [comment]
I think finding the first and last elements of a BTreeMap is a sufficiently common requirement to motivate these methods. Definitely something I'd like to see in stable.

**Comment by mark-i-m** [comment]
Is there anything blocking this from being stabilized? If I understand correctly, the performance issues mentioned early in the thread were fixed, right?

If that's the case, I would like to open a PR to stabilize this feature.

**Comment by ssomers** [comment]
Yes, the performance mentioned early in the thread is still significantly improved by changing calls like `iter().next()` to the new functions (factor 1.5 to 4, depending on the mood of microbenchmarks, for integer keys). I don't know why.

I haven't seen the second "unresolved question" come up anywhere, only the first, and it's still on my mind. In hindsight, I would have chosen these names instead:

```rust
impl<T> BTreeSet<T> {
    pub fn min(&self) -> Option<&T> where T: Ord;
    pub fn max(&self) -> Option<&T> where T: Ord;
    pub fn pop_min(&mut self) -> Option<T> where T: Ord;
    pub fn pop_max(&mut self) -> Option<T> where T: Ord;
}

impl<K, V> BTreeMap<K, V> {
    pub fn min_key_value(&self) -> Option<(&K, &V)> where K: Ord;
    pub fn max_key_value(&self) -> Option<(&K, &V)> where K: Ord;
    pub fn min_entry(&mut self) -> Option<OccupiedEntry<'_, K, V>> where K: Ord;
    pub fn max_entry(&mut self) -> Option<OccupiedEntry<'_, K, V>> where K: Ord;
    pub fn pop_min(&mut self) -> Option<(K, V)> where K: Ord;
    pub fn pop_max(&mut self) -> Option<(K, V)> where K: Ord;
}
```

**Comment by jmlMetaswitch** [comment]
@ssomers - I think that Ord has to not just put your keys in a sequence, but also define a direction to that sequence, so "first" and "last" do always make sense. Does `Ord` imply a type has a "minimum" and "maximum" though? I think not, especially as you might feasibly want to define a type and it's complementary "reverse order" type. Or to have a sequence that doesn't really map to a numeric value for each entry.

**Comment by ssomers** [comment]
Interesting point, if I get it correctly. I'm not at all sure minimum and maximum are the mathematically correct words for the smallest and largest key present in a map or set, but iterators already say so: `iter().min()` and `iter().max()` exist (and yes, the btree iterators define them efficiently).

**Comment by avl** [comment]
Since the contents of the set are ordered according to the implementation of the Ord-trait, isn't it actually true that the first element in the BTreeSet is the minimum, and the last is the maximum? 

If you have a non-empty set of instances of a type which implements Ord, surely there must exist both a minimum and a maximum value? By definition (of Ord) all instances are comparable, and there exists a total order. This means that at least one element must compare equal or smaller to every other element, which means it's the minimum.

That said, there could exist a wrong implementation of Ord. In that case I think it's okay if min() and max() return bogus results.

**Comment by jmlMetaswitch** [comment]
I was suggesting that an ordered sequence doesn't necessarily have to map onto numeric values, so "first" and "last" are better terms than "minimum" and "maximum". However, digging further, I see that both "std::cmp::Ord" and "std::cmp::Ordering" use the terms "less", "greater", "min" and "max", rather than "earlier" or "left of", "first" or "leftmost", etc, so it would be completely consistent to use "min" and "max" for these types too (as @ssomers suggests). Ignore me!

**Comment by ssomers** [comment]
> isn't it actually true that the first element in the BTreeSet is the minimum, and the last is the maximum?

Yes, and the [description of `first`](https://doc.rust-lang.org/std/collections/struct.BTreeSet.html#method.first) says so.

> at least one element must compare equal or smaller to every other element

Yes, but more precisely, exactly one element must compare smaller to every other element.

**Comment by avl** [comment]
Good point, since there are no duplicates, there really has to be exactly one minimum and maximum.

**Comment by ssomers** [comment]
I didn't even think about that uniqueness. If Rust had something like C++'s `multimap` (and I'm not saying it hasn't, just not in btree), which of the element(s) with minimum key would `set.pop_min()` remove? `set.pop_first()` doesn't raise that issue. Even `set.min()` raises that question: the minimum keys are all equal of course, but `min()` returns a reference to a particular key - which one?

**Comment by mark-i-m** [comment]
I actually do like `min` and `max` better, but to play devil's advocate, some other options used in the std library:
- `Vec` (via `Deref` to `[T]`): `first`, `last`
- `LinkedList`, `VecDeque`: `front`, `back`

**Comment by ssomers** [comment]
Those other options are listed in the "Unresolved Questions" and elaborated in #65637, but we're missing substantial arguments for or against them.

I don't understand @matklad's argument against first/last: in my culture, ascending order is the default, so I don't see anything unexpected or ambiguous about first/last. Looking at [a much older comment against min/max](https://github.com/rust-lang/rfcs/pull/1195#issuecomment-120068060-permalink), let's [write a set with reverse ordering on playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=db6ec10c9d618630552232762f23200b). Reversing order isn't useless since not all iterators are double-ended, and performance differs too. Then if `first()` were to renamed, `min()` return the largest element in the set. But that statement is as much a stretch as the other arguments.

**Comment by matklad** [comment]
To clarify, a counter example to “ascending is default” is `BinaryHeap::pop` which counter-intuitively yields the largest item. That is, I agree that in principle “first=min” is a good intuition, but we’ve already messed that up elsewhere, so it is not a reliable intuition sadly.

But I don’t feel super strongly here: it might be argued that that’s just a mistake in BinaryHeap design, and that it should not affect API design elsewhere. If we ignore existing confusion, my argument boils down to “yes, it is trivial one step inference that `first` gives the `min`, but, if we just call it `min`, than there’s no inference at all”.

At the same time, I don’t find “`Reverse` is confusing with `min`“ argument convincing: it is also confusingly  with `first`, as you need to mentally flip the order somewhere anyway. For BTrees thought, unlike heap, you are unlikely to run into this case: the API is symmetric, so there’s no need to flip comparison logic at the type level.

**Comment by avl** [comment]
BinearyHeap is specified to be a "max-heap", which means it yields the largest/max item first. 

BTreeMap is sorted in ascending order, so when iterated it yields the smallest/min item first.

I think this makes sense. Not every collection has to be in ascending order, but for those which are (like BTreeMap), the first item will always be 'min'. 

Couldn't there exist both a 'min' function and a 'first' function? In various situations one or the other will place less cognitive load on the programmer. The documentation could just state they are identical.

Sometimes I want to be able to easily tell that the item accessed is the first in the collection. Then I use 'first'.

Othertimes it's more important that I access the smallest element. Then I use 'min'. 

Would that make sense?

**Comment by Ralith** [comment]
There would inevitably arise code that uses both, which would then be unnecessarily confusing.

**Comment by AlessioZanga** [comment]
If we observe the problem in the broader context of the `std::collections`, methods like `first` and `last` are intuitively associated with collections that have a notion of `Index` like `Vec`, while `min` and `max` depends on the mathematical property of `Ord` like `BTreeSet`.

This naively imply that the problem itself depends on the properties of the underlying collection, but having an index and being ordered are disjoint properties: the former does not imply the latter and vice-versa. Also what @ssomers raised about the `Reverse` holds true in this context, since `Ord` does not imply an ascending order in general, at this point `min/max` would be ill-defined.

Even if there is no unique solution, we cannot afford to duplicate such an essential interface, like @Ralith observed. In the end, choosing `min/max` over `first/last` would only make the collections more heterogeneous, and we can already rely on `iter` for the `min/max` definition by @ssomers:

> Interesting point, if I get it correctly. I'm not at all sure minimum and maximum are the mathematically correct words for the smallest and largest key present in a map or set, but iterators already say so: `iter().min()` and `iter().max()` exist (and yes, the btree iterators define them efficiently).

**Comment by Ralith** [comment]
> Also what @ssomers raised about the Reverse holds true in this context, since Ord does not imply an ascending order in general,

This doesn't make sense to me. The minimum of a set of `Reverse<T>`s is perfectly well defined and straightforward: it's the maximum of the `T`s.

**Comment by AlessioZanga** [comment]
Sorry, typo, I meant **`Index`** does not imply an ascending order in general. As @matklad said:

> I agree that in principle “first=min” is a good intuition, but we’ve already messed that up elsewhere, so it is not a reliable intuition sadly.

The point is since `first` *does* imply `min` in the context of `BTreeSet`, but not in general for `std::collections`, choosing `min/max` over `first/last` would only make the collections more heterogeneous.

**Comment by ssomers** [comment]
> Couldn't there exist both a 'min' function and a 'first' function?

Like there exist identical `iter().min()` and `iter().next()` functions. But that is imposed by the `Iterator` trait.

> Sometimes I want to be able to easily tell that the item accessed is the first in the collection. Then I use 'first'.
> 
> Othertimes it's more important that I access the smallest element. Then I use 'min'.
> 
> Would that make sense?

It makes sense to me, but if it is important, shouldn't there be some sort of "bidirectionally iterable" trait, complete with `first` and `last` shortcuts (without `Ord` bound though), implemented by pretty much every collection, or at least those with a predictable order?

**Comment by jmlMetaswitch** [comment]
I don't want to delay this over a semantic argument, given the inconsistency in all of the other collection types, and especially the Ordering trait.

However, to illustrate the point being made by some of us here, imagine a BTree of elements of type "colours of the rainbow".
* We can set a direction here, red before blue, and define Ordering for the type. I don't know if every culture uses that ordering automatically, but we need to agree it for the type.
* Not all cultures will have the same set of colours in here, and some people may want to include invisible elements of the EM spectrum. That means there is a strict order of elements, whatever elements your culture chooses to include, but indices aren't intrinsic to the elements.
* You can convert the colours to a numeric value, e.g. frequency or wavelength, but the meaning of "minimum" is the opposite depending on the approach you take, so it's not really intrinsic to the type either.
* A tree can still be formed just using an "Ordering" which returns "before", "same" or "after".

Does that help explain the differences in opinion here?

**Comment by avl** [comment]
Are you saying that Ord doesn't imply that there is a 'minimum' element, just that there is always one which comes before all others? 

In your example with the colors, I think it's reasonable that a type-conversion from "color" to "frequency" does not preserve ordering. For example, converting the i32-values 19i32 and 2i32 to String would change their ordering, but that doesn't mean that a set of integers does not have a minimum value.

**Comment by avl** [comment]
> It makes sense to me, but if it is important, shouldn't there be some sort of "bidirectionally iterable" trait, complete with `first` and `last` shortcuts (without `Ord` bound though), implemented by pretty much every collection, or at least those with a predictable order?

Doesn't regular std::iter::DoubleEndedIterator fill that need? And if there is no Ord-bound, there's no reason to expect there to be min/max methods directly on the collection, since the implementation would have to iterate over it anyway to determine the smallest/largest values, right?

**Comment by ssomers** [comment]
> Doesn't regular std::iter::DoubleEndedIterator fill that need?

No, it only allows iterating once, as far as I know.

> And if there is no Ord-bound, there's no reason to expect there to be min/max methods directly on the collection, since the implementation would have to iterate over it anyway to determine the smallest/largest values, right?

I think so, but nevertheless [`Iterator`](https://doc.rust-lang.org/std/iter/trait.Iterator.html) provides min/max methods and it's up to you to hope or figure out that on a btree collection, `iter().min()` is constant time.

**Comment by ssomers** [comment]
I noticed there already is a `BTreeSet::min` function around, the one supplied by trait `Ord` if you `use std::cmp::Ordering`. I'm not quite sure how all that works, but I fear that if someone is actually using `setA.min(&setB)` to get the smallest of two sets, introducing a member `BTreeSet::min` would break their code.

**Comment by cuviper** [comment]
> If we observe the problem in the broader context of the `std::collections`, methods like `first` and `last` are intuitively associated with collections that have a notion of `Index` like `Vec`, while `min` and `max` depends on the mathematical property of `Ord` like `BTreeSet`.

I think tying `first`/`last` to indexing is too narrow -- you can more broadly say that those terms apply to the collection's iteration order. That just happens to correspond to the comparison order for B-trees. However, slices (and `Vec` by deref) are the only precedent for that, while `LinkedList` and `VecDeque` use `front`/`back`.

**Comment by kroggen** [comment]
Can we stop discussion and move forward? It has been more than 2 years! C'mon

`first` and `last` make more sense and will not cause problems

**Comment by ssomers** [comment]
`BTreeSet::min`/`max` (and more) have existed since the birth of `BTreeSet` in 2014. Not for the faint hearted, consuming both sets, but they're there. There's nothing comparable (pun intended) in `BTreeMap`. Nevertheless, to me that means the min/max naming scheme is off the table.

I preferred first/last over front/back initially, basically because a toddler could point out the front and back of a linked list on a drawing, but not the front and back of a B-tree. I would have picked front/back right now. But there is no `Vec::pop_back` matching `LinkedList::pop_back` and `VecDeque::pop_back` either. And `set.last()` does resemble `set.iter().last()`.

**Comment by rHermes** [comment]
I'm a total beginner here, but could someone comment the current way you are supposed to `pop` the first element of a `BTreeSet`, without doing a clone?

**Comment by ssomers** [comment]
@rHermes, I think there are two options:
- Write your own, less efficient function using the stable API, as in this [playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fb29075dc27f7bb806798d1b5a66f675) (somewhat copied from [my own stackoverflow question about the same thing for HashSet](https://stackoverflow.com/questions/54712618/can-i-pop-from-a-hashset-efficiently))
- Use the feature tracked here by switching to a nightly build of Rust as in this [playground example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=dff9b98401b7a230aaac6f8865a51d44), and know that at some point it will require maintenance (at best, just removing the feature flag).

**Comment by trickster** [comment]
@rHermes The first element would be minimum. `.iter().min().unwrap()` would give you the minimum element, and `.iter().max().unwrap()` would give maximum. `.iter().next().unwrap()` also gives you the first element. Once you get the first element, you can remove it from the set with `remove(elem)`.

**Comment by ssomers** [comment]
> without doing a clone?

I wondered how you'd pop by cloning a set, but now I realize it's about not cloning elements. It's technically possible by rebuilding the entire set [as in this playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3e1f67cb1dde97e91b99b2c81be68d12): no element gets cloned and the set isn't cloned either. I don't think there's a reasonable solution.

**Comment by MathieuDuponchelle** [comment]
So what's happening here? I personally don't have any preference for the naming, I'd be fine with any of the proposed choices but I reckon after 3 years someone could make an informed decision :)

**Comment by MathieuDuponchelle** [comment]
Also `first` / `last` is obviously the right choice

**Comment by m-ou-se** [comment]
See https://github.com/rust-lang/rust/pull/93709#issuecomment-1098126012 for the decision to keep the `first` and `last` names.

**Comment by MathieuDuponchelle** [comment]
> See https://github.com/rust-lang/rust/pull/93709#issuecomment-1098126012 for the decision to keep the first and last names.

Right, I was commenting prior to the checkbox for that issue being marked as resolved :)

**Comment by kyegupov** [comment]
Sorry for barging in, but I think this is a tremendously useful and obvious feature that should have been there from the day one. What can we do to accelerate its stabilization?

**Comment by searleser97** [comment]
when is this feature going to be in a stable release?

**Comment by joshtriplett** [comment]
Shall we stabilize these methods?

@rfcbot merge

**Comment by BurntSushi** [comment]
The naming here looks a tad unfortunate. For example, I'd expect `BTreeMap::first_key_value` to just be `first`, which matches `pop_first`. I suppose `first_key_value` is consistent with `get_key_value`, since `get` just returns the value. Presuming we don't want to add a `first` that only returns the value _and_ a `first_key_value`, I suppose going with `first_key_value` here is the better choice?

**Comment by pierzchalski** [comment]
This seems to have stalled, anything I can do to help push it along?

**Comment by etairi** [comment]
When will this stabilize?

**Comment by Fuuzetsu** [comment]
Presumably when remaining one of the 3 people in https://github.com/rust-lang/rust/issues/62924#issuecomment-1179489929 lets it go into final comment period... Not sure what the procedure is for when this simply doesn't happen forever.

**Comment by pierzchalski** [comment]
@Amanieu @m-ou-se @yaahc I'm assuming this just flew under your radars?

**Comment by pierzchalski** [comment]
@BurntSushi @dtolnay @joshtriplett is there any potential next step here? This _seems_ like an unusually long wait for FCP.

**Comment by est31** [comment]
As the FCP is close to starting (only one more approval needed), I've opened a PR to stabilize the `map_first_last` feature: #101727 .

**Comment by avl** [comment]
Random bystander here. 

Wouldn't it make sense for either @Amanieu , @yaahc or @m-ou-se  to either approve this, or provide some guidance on what further work is needed before this can be approved?

**Comment by Amanieu** [comment]
I've been away for the past few weeks and haven't had much time to check up on Rust-related things. I've checked my box, this API looks fine to me.
