### ISSUE TITLE
Tracking issue for `impl Trait` in `const` and `static` items and `let` bindings

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#63065]
As provided for by rust-lang/rfcs#2071, this is a tracking issue for `impl Trait` in:
- `const` items
- `static` items
- `let` bindings

**Steps:**

- [x] Implement the RFC
   - There are bugs...
- [ ] Adjust documentation ([see instructions on rustc-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-guide][stabilization-guide])

[stabilization-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs

**Unresolved questions:**

- [ ] Should the part about `let` bindings be recast more generally to be about *coercions*? This would allow `foo as impl Debug` and `foo: impl Debug` as well.

**Comment by Rua** [comment]
What's the status on this now? Is it ready to be stabilised?

**Comment by QuineDot** [comment]
The implementation was removed as part of #86729 and the corresponding checkbox should be unchecked.

**Comment by NobodyXu** [comment]
Pinging, is there any progress on this feature?

**Comment by ctrlcctrlv** [comment]
Hopefully there will be soon, as it was the cleanest way for me to solve an issue just now.

**Comment by JohnScience** [comment]
The question I opened on Stack Overflow on this topic: <https://stackoverflow.com/questions/79643282/why-errore0121-the-placeholder-is-not-allowed-within-types-on-item-signat>.

A workaround can be found there too.
