### ISSUE TITLE
Tracking issue for RFC 2574, "SIMD vectors in FFI"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#63068]
This is a tracking issue for the RFC "SIMD vectors in FFI" (rust-lang/rfcs#2574).
The feature gate is `#![feature(simd_ffi)]`.

**Steps:**

- [ ] Implement the RFC (cc @rkruppe @gnzlbg); WIP in https://github.com/rust-lang/rust/pull/59238.
- [ ] Adjust documentation ([see instructions on rustc-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-guide][stabilization-guide])

[stabilization-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs

**Unresolved questions:**

- [ ] Should it be possible to use, e.g., `__m128` on C FFI when the `avx` feature is enabled? Does that change the calling convention and make doing so unsafe ? We could extend this RFC to also require that to use certain types certain features must be disabled.

**Comment by RalfJung** [comment]
I think this is mostly implemented by the lint tracked at https://github.com/rust-lang/rust/issues/116558. However, the `simd_ffi` feature still exists, and if you don't use it you get some warnings or so? I've seen the improper C types warning, but there's a dedicated warning emitted [here](https://github.com/rust-lang/rust/blob/5eeaf2ec3310b6b10d0567890a52eb0293585e7a/compiler/rustc_hir_analysis/src/collect.rs#L1710-L1720) that I don't think I have ever seen...

Cc @workingjubilee @veluca93

**Comment by RalfJung** [comment]
Ah, you only get that error when *importing* a foreign function in an `extern "C"` block.

I think that can be removed? Calling that function without having the feature gate required for this vector type will lead to an error (well, a future-compat warning for now, an error eventually).

We can probably also remove [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=10c712ef153066a8c1829f6c7f41a3f4) warning saying that __m256 is not FFI safe when defining an `extern "C"` function.
