### ISSUE TITLE
Meta tracking issue for RFC 1892, "Deprecate uninitialized in favor of a new MaybeUninit type"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#63566]
This issue tracks the progress of `MaybeUninit<T>` in general. The type was introduced in https://github.com/rust-lang/rfcs/pull/1892. The old tracking issue is https://github.com/rust-lang/rust/issues/53491.

This issue is not for discussion about specific extensions to `MaybeUninit<T>` and only exists to provide links to other places that track the progress of specific issues. If you wish to discuss some subject related to `MaybeUninit<T>`, please find an existing appropriate issue below or create an new issue and comment here with a link to the newly created issue.

--------------------------

The `MaybeUninit<T>` related issues currently on deck are as follows:

- [ ] https://github.com/rust-lang/rust/issues/63291; "Uninitialized constructors for Box, Rc, Arc"
- [x] https://github.com/rust-lang/rust/issues/49147; "Constants in array repeat expressions"
- [ ] https://github.com/rust-lang/rust/issues/63567; `#![feature(maybe_uninit_extra)]`
- [ ] https://github.com/rust-lang/rust/issues/63568; `#![feature(maybe_uninit_ref)]`
- [ ] https://github.com/rust-lang/rust/issues/63569; `#![feature(maybe_uninit_slice)]`
- [ ] https://github.com/rust-lang/rust/issues/64490; `&raw [mut | const] $place`

Concerns:
- [ ] https://github.com/rust-lang/rust/issues/76092

**Comment by scottmcm** [comment]
With `MaybeUninit` available on stable, we talked about this in lang backlog bonanza today and decided that we're good just closing this.  There's lots more potential work, like new library APIs and more UB detection, but this meta-issue doesn't need to be open to track those things -- their own issues are sufficient.
