### ISSUE TITLE
 Tracking issue for `#![feature(maybe_uninit_slice)]`

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#63569]
This is a tracking issue for the RFC "Deprecate `uninitialized` in favor of a new `MaybeUninit` type" (rust-lang/rfcs#1892).

Most of this has been stabilized, this issue now only tracks the below unstable methods.

### Public API

```rust
impl<T> [MaybeUninit<T>] {
    pub unsafe fn assume_init_drop(&mut self);
    pub const unsafe fn assume_init_ref(&self) -> &[T];
    pub const unsafe fn assume_init_mut(&mut self) -> &mut [T];

    pub const fn slice_as_ptr(this: &[MaybeUninit<T>]) -> *const T;
    pub const fn slice_as_mut_ptr(this: &mut [MaybeUninit<T>]) -> *mut T;
}
```

### Steps / History

- [x] Implementation
- [x] Make slice methods inherent: https://github.com/rust-lang/rust/pull/129259
- [ ] Ensure documentation has examples
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- Should `slice_as_ptr`/`slice_as_mut_ptr` be methods (with some `Self` parameter) instead of functions?
- `slice_as_ptr`/`slice_as_mut_ptr` get rid of the slice length, so `.add(n)` needs to be used on the result instead of a safer `[n]`. See accepted ACP https://github.com/rust-lang/libs-team/issues/245 and its incomplete implementation https://github.com/rust-lang/rust/pull/103133

**Comment by RalfJung** [comment]
Note: https://github.com/rust-lang/rust/issues/63291 contains some APIs for *creating* uninitialized slices, but still does not have a good story for working with them, AFAIK.

Cc @SimonSapin

**Comment by asomers** [comment]
I think another missing function is a way to create a slice of uninitialized data from a Vec.  Like this:
```rust
impl<'a, T> Vec<T> {
    pub fn as_uninit(&'a mut self) -> &'a mut [MaybeUninit<T>] {...}
}
```
Which would be used like this:
```rust
let v = Vec::<u8>::with_capacity(100);
let mut sl = v.as_uninit();
if 0 != some_ffi_func(sl.first_ptr_mut(), sl.len()) {
    return Err<()>;
} else {
    v.set_len(sl.len());
    return Ok(v);
}
```
There's no need for `Vec::uninit()` or `Vec::assume_init()`, because `Vec::with_capacity` and `Vec::set_len` already do pretty much the same thing.  And for simple cases like this one `Vec::as_mut_ptr()` would suffice without the formality of creating a slice of `MaybeUninit`s.  However, the slice has the advantage that it knows its own length and it knows the lifetime of its data.  The latter is especially useful when working with FFI functions that initialize the data asynchronously, such as `aio_read`.

**Comment by RalfJung** [comment]
Cc @Shnatsel see above -- seems related to https://github.com/rust-lang/rust-clippy/issues/4483

**Comment by SimonSapin** [comment]
@asomers I agree that something like this would be good to have. However your proposal seems ambiguous: does the returned slice include the entire allocation (indices `0..capacity`) or only the range that is not known to be initialized (indices `len..capacity`)?

Would an API that returns two disjoint `(&mut [T], &mut [MaybeUninit<T>])` slices for indices `0..len` and `len..capacity` also be useful?

**Comment by SimonSapin** [comment]
Back to the APIs tracked in this issue, could they be methods of `[MaybeUninit<T>]` that take `&self` instead of associated functions of `MaybeUninit<T>`? (Though it’s not obvious what they should be called in that case.)

We have precedent for a lang item for `impl [u8] {…}`

**Comment by asomers** [comment]
Good questions @SimonSapin.  I think that the returned slice should include the entire allocation (after all, elements that are already initialized can still be represented as `MaybeUninit`.  Also, I realized that the method I proposed isn't even good enough for my particular use case.  I need a way to create an owned, maybe-uninitialized slice in a known memory location, and then transform that into an initialized vec.  This is important for Tokio, whose asynchronous nature can thwart the borrow-checker.
```rust
impl<T> Vec<MaybeUninit<T>> {
    /// Transmute this `Vec` of possibly uninitialized data into a normal `Vec`, assuming that the
    /// first `len` elements are properly initialized.
    pub unsafe fn assume_init(self, len: usize) -> Vec<T> {...}
}
/// I'm not 100% sure it's necessary, but define this for symmetry's sake:
impl<T> Vec<T> {
    /// Transmute this `Vec` into a `Vec` of possibly uninitialized data whose length is equal to
    /// the original `Vec`'s capacity.
    pub fn into_uninit(self) -> Vec<MaybeUninit<T>> {...}
}
```
And it would be used like this:
```rust
let v_uninit = Vec::<MaybeUninit<u8>>::with_capacity(1024);
let result = some_ffi_func(v_uninit.as_mut_ptr(), v_uninit.capacity());
match result {
    Ok(len) => Ok(v_uninit.assume_init(len)),
    Err(e) => Err(e)
}
```
Also, regarding the original methods, should the return type be `Option<NonNull<T>>`?  That way they could return `None` for 0-length slices.

**Comment by SimonSapin** [comment]
> I need a way to create an owned, maybe-uninitialized slice in a known memory location

That’s `Box::new_uninit` https://github.com/rust-lang/rust/issues/63291

**Comment by Shnatsel** [comment]
Why would you use `Vec<MaybeUninit<T>>`? `Vec` already encapsulates work with uninitialized memory - you can write to its capacity and then `.set_len()` to update the length. Or just use one of the myriad of methods that append to it safely.

**Comment by asomers** [comment]
@Shnatsel because I need something that _owns_ uninitialized memory, unlike a `*mut u8`. I'm using `aio_read`, which asynchronously initializes the memory.  There's no way for me to supply a `&mut Vec` reference to `aio_read` and persuade the borrow checker that the `Vec` will still be around by the time that the operation is complete (with notification delivered via kqueue).  Making matters more complicated is the fact that my stack is 5 crates deep.

Another option might be if `[T]` implemented `BorrowMut<[MaybeUninit<T>]>`.  Then I think I could make things work.

**Comment by Shnatsel** [comment]
Ah, looks like you want `aio_read` to actually own the Vec instead of getting a mutable reference to it. This has already been brought up in relation to [design of readers in `async_std`](https://www.reddit.com/r/rust/comments/cr85pp/announcing_asyncstd_beta_an_async_port_of_the/ex3n3kl/).

**Comment by krsnik02** [comment]
Is there any reason these are not directly implemented on the slice?
```
impl<T> [MaybeUninit<T>] {
    pub fn first_ptr(&self) -> *const T { ... }
    pub fn first_ptr_mut(&mut self) -> *mut T { ... }
}
```

This would allow `slice.first_ptr()` instead of `std::mem::MaybeUninit::first_ptr(&mut slice)`.

**Comment by RalfJung** [comment]
As far as I know, such inherent impls for primitive types don't actually work -- and making them work requires some magic to be added inside the compiler. I am not sure though.

**Comment by SimonSapin** [comment]
Yes, trait coherence rules would normally require this impl to be in the crate that defines the `[_]` slice type, but that is no crate. It is possible to basically change the rules of the language and make an exception, we do that here for `[u8]` for methods that were originally on the `std::ascii::AsciiExt` trait but that we later chose to make inherent:

https://github.com/rust-lang/rust/blob/21ed50522ddb998f5367229984a4510af578899f/src/libcore/slice/mod.rs#L2592-L2594

So it’s technically possible and there is precedent, but I don’t know if the Lang team is keen on expanding that pattern.

**Comment by SimonSapin** [comment]
The language change https://blog.rust-lang.org/2020/01/30/Rust-1.41.0.html#relaxed-restrictions-when-implementing-traits doesn’t apply to inherent methods, does it?

**Comment by tspiteri** [comment]
I've just submitted PR #69319 to implement `From<&[T]>` for `NonNull<T>`, but what would also be useful to me is `<From<&[MaybeUninit<T>]>>` for `NonNull<T>`. That could even be a substitute for `MaybeUninit::first_ptr_mut`: something like `NonNull::<T>::from(slice_of_uninit).as_ptr()`. It wouldn't be a substitute for `MaybeUninit::first_ptr`, but I think that method seems less useful: when I want a pointer to uninitialized, it is to pass it to some function that initializes it.

**Comment by ttencate** [comment]
The `MaybeUninit::as_mut_ptr` documentation currently warns:

> Reading from this pointer or turning it into a reference is undefined behavior unless the `MaybeUninit<T>` is initialized.

I suppose this applies to `slice_as_mut_ptr` as well, but there is no such warning in its documentation currently, so please consider adding it.

**Comment by SUPERCILEX** [comment]
Why do the `slice_as[_mut]_ptr` methods exist? I'm poking through MaybeUninit's API to see if anything else can be simplified, and those two methods seem to just be hiding a simple `as *{const,mut} T` cast.

**Comment by SUPERCILEX** [comment]
Yeah those methods are objectively bad. Nuke: #103133

**Comment by ForrestOfBarnes** [comment]
Any update on this feature?

**Comment by SUPERCILEX** [comment]
It's stalled because we wish the language could generalize over containers: https://github.com/rust-lang/libs-team/issues/122. Depending on how long that takes, it might make sense to stabilize the slice methods anyway, but these features haven't been discussed under the assumption that container generalization exists. That's probably the next step: see what makes sense to stabilize even if we get language features that makes some of the methods unnecessary. Then we can evaluate the tradeoffs of adding methods that will probably be pointless in the future but are useful now.

**Comment by ForrestOfBarnes** [comment]
Ahhh, I was just thinking it would be nice to implement this for Vec too. Anyone who really needs this functionality (might be me, idk) could just copy that one line of source code, so it probably makes sense to wait for the cleaner, container-based implementation. 👍

**Comment by clarfonthey** [comment]
Worth updating the description for these new APIs that were changed:

```
impl<T> [MaybeUninit<T>] {
    pub fn as_bytes(&self) -> &[MaybeUninit<u8>];
    pub fn as_bytes_mut(&mut self) -> &mut [MaybeUninit<u8>];
    pub unsafe fn assume_init_drop(&mut self);
    pub unsafe fn assume_init_ref(&self) -> &[T];
    pub unsafe fn assume_init_mut(&mut self) -> &mut [T];
}
```

Note that `slice_as_ptr` and `slice_as_mut_ptr` haven't been made inherent yet since it's unclear how best to do this. Maybe `as_ptr().cast()` is sufficient, but I'm not sure. #

**Comment by RalfJung** [comment]
`as_bytes` is on a different feature gate and the rest seems to already match the issue description?

**Comment by clarfonthey** [comment]
Whoops, I misread, and you're entirely right here. The confusion came from the associated methods being in the same block which is technically wrong but fine since it's not valid Rust syntax anyway.

**Comment by clarfonthey** [comment]
How would people feel about stabilising at least the `assume_init_*` methods for slices, since the main concerns seem to be addressed now that they're inherent methods instead of requiring function call syntax?

I leave the pointer methods off for now since they don't follow this pattern and probably should in the future, but maybe we could eventually have an easy method that casts `*const MaybeUninit<T>` to `*const T`.

----

EDIT: To fully elaborate, the proposal would be to replace:

```rust
impl<T> MaybeUninit<T> {
    pub const fn slice_as_ptr(this: &[MaybeUninit<T>]) -> *const T;
    pub const fn slice_as_mut_ptr(this: &mut [MaybeUninit<T>]) -> *mut T;
}
```

With the below:

```rust
impl<T> *const MaybeUninit<T> {
    pub const fn cast_init(self) -> *const T;
}
impl<T> *mut MaybeUninit<T> {
    pub const fn cast_init(self) -> *mut T;
}
```

And then calls of the form `MaybeUninit::slice_as_ptr(val)` could be replaced with calls of the form `val.as_ptr().cast_init()`.

**Comment by thaliaarchi** [comment]
I agree that the `assume_init_*` methods look ready. As inherent methods matching the pattern of the identically named stable methods on `MaybeInit`, they're quite intuitive.

I like `cast_init`. It fits with stable `cast_mut`, `cast_const`, `cast_signed`, and `cast_unsigned`.

**Comment by clarfonthey** [comment]
The code looks incredibly straightforward for it too, although I'll hold off on submitting a PR depending on whether libs-api think it's okay to make this change as an improvement on this already-accepted issue, or if it should go through the ACP process. It's technically more powerful/applicable than `slice_as_ptr`, but it is a reasonable extension to make it happen.

**Comment by Amanieu** [comment]
We discussed this in the @rust-lang/libs-api meeting. We would like to stabilize the following methods since they match the corresponding methods on `MaybeUninit`.

```rust
impl<T> [MaybeUninit<T>] {
    pub unsafe fn assume_init_drop(&mut self);
    pub const unsafe fn assume_init_ref(&self) -> &[T];
    pub const unsafe fn assume_init_mut(&mut self) -> &mut [T];
}
``` 

Separately, we would also like to *remove* the following pointer methods. We don't think the current API is useful, and alternatives such as `cast_init` should be explored separately (not in this tracking issue).

```rust
impl<T> [MaybeUninit<T>] {
    pub const fn slice_as_ptr(this: &[MaybeUninit<T>]) -> *const T;
    pub const fn slice_as_mut_ptr(this: &mut [MaybeUninit<T>]) -> *mut T;
}
``` 

@rfcbot merge

**Comment by clarfonthey** [comment]
FWIW: I filed an ACP for my alternative `cast_init` proposal so we can carry over the discussion of alternatives to `slice_as_ptr`. So, when this tracking issue is closed, we don't need to worry about keeping the other discussion going.

**Comment by rust-rfcbot** [comment]
@Amanieu proposal cancelled.

**Comment by rust-rfcbot** [comment]
Team member @Amanieu has proposed to merge this. The next step is review by the rest of the tagged team members:


No concerns currently listed.

Once a majority of reviewers approve (and at most 2 approvals are outstanding), this will enter its final comment period. If you spot a major issue that hasn't been raised at any point in this process, please speak up!

See [this document](https://github.com/rust-lang/rfcbot-rs/blob/master/README.md) for info about what commands tagged team members can give me.

**Comment by rust-rfcbot** [comment]
The final comment period, with a disposition to **merge**, as per the [review above](https://github.com/rust-lang/rust/issues/63569#issuecomment-3368371048), is now **complete**.

As the automated representative of the governance process, I would like to thank the author for their work and everyone else who contributed.

This will be merged soon.
