### ISSUE TITLE
Tracking issue for RFC 2495, "Minimum Supported Rust Version"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#65262]
This is a tracking issue for the RFC "Minimum Supported Rust Version" (rust-lang/rfcs#2495).

**Steps:**

- [x] Implement the RFC (cc @rust-lang/cargo -- can anyone write up mentoring
      instructions?)
- [ ] Adjust documentation ([see instructions on rustc-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-guide][stabilization-guide])

[stabilization-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs

**Unresolved questions:**

- Name bike-shedding: `rust` vs `rustc` vs `min-rust-version`
- Additional checks?
- Better description of versions resolution algorithm.
- How nightly versions will work with "cfg based MSRV"?

**Comment by jhpratt** [comment]
My personal opinions:

**Name** → `min-rust-version` or `msrv`. The latter may have already been declined, but if accompanied by documentation it's certainly already relatively widespread.

**Nightly** — _Both_ the dated version (`2019-10-10`) and the semver version (`1.40.0` for when `1.38.0` is stable). The latter could be somewhat confusing, as I've never seen nightly referred to like that in practice.

**Comment by Majkl578** [comment]
> Name bike-shedding: `rust` vs `rustc` vs `min-rust-version`

My personal preference would be `rust-version`. `min-rust-version` is a bit too long and `msrv` is a bit cryptic abbreviation for newcomers (when I first saw it I was like _what Microsoft stuff is this referring to_).

Regarding nightly versions: I do not like the suggestion by @jhpratt to use semver version for nightly (e.g. `1.40.0`) because the constraint is too wide. I think using `nightly-2019-10-10` (meaning nightly from 2019-10-10 or newer) would be better and specific enough.

**Comment by mathstuf** [comment]
Agreed with @Majkl578 about the `nightly` via semver thing. Just because `nightly` has your feature today doesn't mean it will appear in the stable release with that version number.

**Comment by distransient** [comment]
I went through the discussions and I couldn't see anyone discussing representing the version as a semver version requirement like package dependencies, only instead defaulting to a `>= xxx` comparison operator when none is present instead of a caret operator. This would be useful personally and seems like it'd reuse existing functionality

**Comment by Lokathor** [comment]
Minimum rust version should absolutely be a semver comparison, yes.

**Comment by distransient** [comment]
I read the RFC a second time and saw a part suggesting semver comparison but I'm leaving my comment to keep the use-case clearly vocalized

**Comment by newpavlov** [comment]
>the use-case clearly vocalized

What is this use-case though? In your previous post you only said it would be useful for you personally, without specifying why exactly. In the RFC I've wrote:
>value should be a version in semver format **without** range operators.

exactly because I didn't see why it would be useful outside of the nightly extension, and even with the extension I am not 100% sure this feature would pull its weight. Also IIRC during discussion no one have brought any substantial arguments for supporting range operators with "1.X" versions.

**Comment by distransient** [comment]
Targeting a specific Rust ABI would require pinning the Rustc version to an exact number. This can easily be accomplished with semver without developing an entirely new syntax

**Comment by mathstuf** [comment]
How can a minimum be a range though? How is a minimum of `>= 1.34.0` meaningfully different than just saying `1.34.0` is my minimum? What use case is enabled by that?

**Comment by distransient** [comment]
I suggested semver defaulting to a `>=` operator. This means that `">= 1.34.0"` and `"1.34.0"` would be identical values, just like how in dependencies, which default to the caret operator, `"^1.34.0"` and `"1.34.0"` are identical values. The original functionality of the proposal would be identical with the caveat of some extra flexibility and code reuse. Personally I'm against the "minimum" name and think just the key "rust" or "rustc" is fine.

**Comment by Majkl578** [comment]
@distransient By definition semver-compliant constraint can't default to `>=` because it would allow next major version(s), breaking the semver guarantee.
But given that Rust itself isn't following semver I'm not sure it matters.

**Comment by Lokathor** [comment]
Rust attempts to, but there are clearly spelled out parts where it is not followed perfectly.

**Comment by steveklabnik** [comment]
(this is not correct; ranges are not defined in the spec at all. rust
follows the entire semver spec accurately, but there are some extensions to
the spec (like ranges) that different implementations disagree on. (I
maintain both semver the spec as well as semver the rust package.))

**Comment by Lokathor** [comment]
That is correct, but I wasn't talking about ranges, I was referring to Rust's policy of accepted breakage.

**Comment by joshtriplett** [comment]
Given that we're extremely unlikely to ever have a rust 2.x.y semver, I would propose that we use `~` by default to match the default for dependencies.

**Comment by Lokathor** [comment]
Cargo uses `^` by default according to the cargo book. That's a lot more appropriate to what we want. If you specify you need rust 1.36, then 1.37 will do just fine as well.

**Comment by steveklabnik** [comment]
@Lokathor the semver spec also says that projects define what “breakage” is.

That said, yes, ^ is a good default.

**Comment by djc** [comment]
This has been implemented in cargo, merged as of https://github.com/rust-lang/cargo/commit/8e075c9cab41eb1ed6222f819924999476477f2e, currently with the "rust-version" name.

We should probably discuss the unresolved questions:

* Name bike-shedding: rust vs rustc vs min-rust-version

I implemented `rust-version` since it seems a decent compromise of terseness and being obvious about what it does. On the other hand, what with the value being a clear semver version and the precedence of dependencies, maybe the terseness of just `rust` could be just fine.

* Additional checks?

I can't think of any additional checks that should be done. The checks from the reference level explanation in the RFC seem like a great minimal start to me.

* Better description of versions resolution algorithm.

We currently parse the value as a `semver::VersionReq`, with the additional restrictions that only ASCII digits and `.` are allowed (so no semver operators allowed). We then check (unless `--ignore-rust-version` is passed in) that the parsed version requirement matches the major/minor/micro version for the current rustc (so ignoring prerelease identifiers).

* How nightly versions will work with "cfg based MSRV"?

Since this part of future work, I think we can punt on it for now.

We also still need an implementation in crates.io to forbid new crates that have a `rust-version` newer than current stable.

**Comment by cuviper** [comment]
Is dependency resolution still future work? And if so, is there a separate tracking issue for that?

**Comment by djc** [comment]
If you mean that the resolver would select dependencies based on their Rust version compatibility, that was explicitly scoped out of this RFC, so it would need follow-up work, presumably after we gain some experience with this more minimal take.

**Comment by Lokathor** [comment]
So this has essentially zero practical effect?

**Comment by 8573** [comment]
> So this has essentially zero practical effect?

Would the immediate practical effect be making crates that would fail to build because of MSRV [fail faster](https://en.wikipedia.org/wiki/Fail-fast) and fail with a clearer error message?

**Comment by djc** [comment]
> Would the immediate practical effect be making crates that would fail to build because of MSRV fail faster and fail with a clearer error message?

Yes, that is the practical effect of the current implementation. Also, this makes the metadata available in a standard way, so there's lots of tooling that can be built on top of that.

**Comment by dekellum** [comment]
Thanks!  Any progress is to be commended on this, @djc!  The prior failed attempt (rust-lang/cargo#7801) suggests making progress is difficult. 

I guess I can wait to test this when it lands in stable, but if I understand rust-lang/cargo#8037 well enough, then I fear that no production-targetting crates are going to be published with it, because it would make the crate a nightly-only crate, given that the feature is behind a nightly-only unstable flag?

I'm really hoping I'm wrong about this, will anyone correct me? I would have thought the intent of the first pass on this, would be to establish the MSRV metadata in crates.io published crate manifests, thus enabling subsequent passes (e.g. resolver awareness) to gain testing confidence?

**Comment by djc** [comment]
Yeah, the implementation so far is mainly for early testing, and crates using it probably cannot be published to crates.io at all. For all of that, you'll have to wait until this hits stable. I hope to be pushing it forward, but progress will depend on consensus in the cargo and crates.io teams (my prior attempts to get stuff done on the crates.io side were quite frustrating).

**Comment by newpavlov** [comment]
@djc
Since Rust 1.27 cargo accepts unknown fields and only emits a warning, so it's possible to publish such crate, but it seems that currently crates.io removes all unknown fields. I wonder if post-1.27 versions will be able to properly process dependency crates with unknown fields in their Cargo.toml.  In other words, I wonder if specifying MSRV would cause crate MSRV to be bumped to a version in which this feature will be stabilized. For obvious reasons, I think we should aim for it to not being the case.

**Comment by ehuss** [comment]
> crates using it probably cannot be published to crates.io at all

You should be able to publish, it will just be supported on nightly-only, so most non-nightly packages probably shouldn't.

> progress will depend on consensus in the cargo and crates.io teams

This feature does not touch crates.io, so they will not be involved.

> crates.io removes all unknown fields (or is it cargo?)

Starting with the nightly that contains the PR, it shouldn't be removed, and you should be able to publish with it (with the caveat that it is nightly-only).

> if post-1.27 versions will be able to properly process dependency crates with unknown fields in their Cargo.toml

Versions older than 1.51 will ignore it.

**Comment by dekellum** [comment]
@ehuss could you elaborate on how (if at all) the situation will change once 1.51 becomes a stable release?

**Comment by ehuss** [comment]
We did things a little differently than usual with this feature. On stable it will only issue a warning that the rustc-version field is ignored. (Typically unstable features are an error.) Since the field doesn't actually affect compilation, that seemed like a safer route to take, so that whenever it is stabilized, you can still reference versions prior to the stabilized release.

However, @djc, it looks like [this clause](https://github.com/rust-lang/cargo/blob/b52fc0a8270d671e33dafe8dec355624727e8534/src/cargo/util/toml/mod.rs#L1062-L1080) is missing an `else`.  Can you send a PR to fix it?

**Comment by leo60228** [comment]
> We also still need an implementation in crates.io to forbid new crates that have a rust-version newer than current stable.

I disagree with this. People should be able to set an MSRV of a currently-beta version. I don't see any way this could be worse than the status quo, since it's not like the version could go backwards.

**Comment by nagisa** [comment]
I want to add that if we expose this as a `cfg`, it cannot be a `#[cfg(foo="bar")]` style cfg – it would be either incompatible or confusing with crates that already set and use the `foo` cfg in other ways.

**Comment by djc** [comment]
> I disagree with this. People should be able to set an MSRV of a currently-beta version. I don't see any way this could be worse than the status quo, since it's not like the version could go backwards.

The crates.io part is off the table for now anyway.

**Comment by djc** [comment]
Cargo team: how do we move this forward? Do you want to change the name from `rust-version`?

**Comment by crlf0710** [comment]
Ticking the checkbox and updating the label according to https://github.com/rust-lang/rust/issues/65262#issuecomment-763765009

**Comment by ehuss** [comment]
> Cargo team: how do we move this forward? 

Sorry for the slow reply.  We don't have any process for evaluating if and when something should be stabilized.  Has anyone tested this feature?  I realize that is difficult since it is nightly only, but even if people do some local testing against their own packages or with `path` dependencies, I think that would be helpful. Kick the tires and see if it works as expected, and if other people can think of edge cases where it might have issues.

Besides that, I don't think there are any blockers.

> Do you want to change the name from `rust-version`?

I think we're fine with sticking with `rust-version`.

**Comment by djc** [comment]
I was waiting for a pronouncement on the name, since in Zulip some people expressed preferences for another name. If there is consensus about the current name, I'll start to make some noise to invite testing.

**Comment by ehuss** [comment]
Yep, sorry again about the delay. The team did talk about it in our last meeting and we felt like `rust-version` hit the right balance between the alternatives.  Our meetings have been pretty full so it takes a while to get through things.

**Comment by djc** [comment]
Cool, thanks, I'll see if I can shake loose some testing efforts.

**Comment by djc** [comment]
Wrote up a call for testing here:

https://users.rust-lang.org/t/call-for-testing-unstable-cargo-support-for-rust-version/59386

If anyone here has other suggestions for what kinds of things to test, please suggest them there.

**Comment by kornelski** [comment]
When is this going to be stabilized?

**Comment by joshtriplett** [comment]
This is on track to be stabilized in 1.56.

**Comment by newpavlov** [comment]
@joshtriplett 
Great! What about the proposed MSRV-dependent dependency version resolution? Should we open a separate Rust or Cargo issue?

**Comment by joshtriplett** [comment]
@newpavlov That was moved to future work because, among other things, it would need some confirmation that the proposed approach to resolution is something we'd want to do. Given such confirmation, someone would then need to submit a PR implementing it.

**Comment by ehuss** [comment]
Sorry, forgot that there was a second tracking issue.  Closing as this has been stabilized in https://github.com/rust-lang/cargo/pull/9732.

**Comment by newpavlov** [comment]
I went ahead and created a separate issue for MSRV-dependent dependency version resolution: #89136

**Comment by peter-kehl** [comment]
To save people's time: As per https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-rust-version-field, the field is called `rust-version`.
