### ISSUE TITLE
Tracking issue for atomic_mut_ptr

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/rust#66893]
This is a tracking issue for`atomic_mut_ptr`.

### Public API

```rust
impl AtomicBool {
    pub const fn as_ptr(&self) -> *mut bool;
}

impl AtomicI32 {
    pub const fn as_ptr(&self) -> *mut i32;
}

// … etc.

impl<T> AtomicPtr<T> {
    pub const fn as_ptr(&self) -> *mut *mut T;
}
```

### Steps / History

- [x] Implementation: #66705
- [x] Add to AtomicPtr too: #106762
- [x] Make const: https://github.com/rust-lang/rust/pull/107706
- [x] Rename to `as_ptr`: https://github.com/rust-lang/rust/pull/107736
- [x] Final comment period (FCP)
- [ ] Stabilization PR

**Comment by nox** [comment]
> Any use of the returned raw pointer requires an `unsafe` block and still has to uphold the same restriction: operations on it must be atomic.

I'm not sure this is phrased as best as it could in the documentation, in the sense that callers are definitely allowed to do non-atomic accesses to the underlying value, but they must do so only if they can guarantee that absolutely no other thread will observe a non-atomic access. Does that make sense?

**Comment by m-ou-se** [comment]
This should probably also be added to AtomicPtr, for consistency between the Atomic* types.

**Comment by tgross35** [comment]
@KodrAus are there any concerns about stabilizing this feature? If not, could we go ahead with the stabilization PR?

**Comment by tgross35** [comment]
Actually I have one addition - this could be `const` with no problem, which would make it easier to use with FFI statics.

**Comment by m-ou-se** [comment]
I'm wondering if it should just be `as_ptr` instead of `as_mut_ptr`. `Cell<T>` also has a `as_ptr()` that returns a `*mut T`.

**Comment by tgross35** [comment]
Yeah, that's a good point. I don't think there are many cases where a separate `as_ptr` and `as_mut_ptr` make sense, since you'd always prefer to just `.load(...)` the data if you don't need to change it.

Would this naming change require a FCP?

**Comment by tgross35** [comment]
I don't think there's too much debate about anything here, so I opened  #108419 to stabilize it

**Comment by m-ou-se** [comment]
@rfcbot merge
