### ISSUE TITLE
Tracking issue for RFC 2837: "Demote Apple 32bit targets to Tier 3"

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#67724]
This is a tracking issue for the RFC "Demote Apple 32bit targets to Tier 3" (rust-lang/rfcs#2837).

* Rust 1.41.0 (2020-01-30) will be the last release with the current support tier
* Rust 1.42.0 (2020-03-12) will have Tier 3 support for all Apple 32bit targets

**Steps:**

- [x] Create a post on the main blog explaining the change to our users
  - PR: https://github.com/rust-lang/blog.rust-lang.org/pull/487
- [x] Update docs.rs to stop building documentation for that target
  - PR: https://github.com/rust-lang/docs.rs/pull/541
- [x] Remove the targets from the CI builders
  - PR: https://github.com/rust-lang/rust/pull/67732

**Steps after Rust 1.42 is released:**

- [x] Update [platform support](https://forge.rust-lang.org/release/platform-support.html) and [the component history](https://rust-lang.github.io/rustup-components-history/) to reflect the demotion

**Comment by pietroalbini** [comment]
I will write the implementation PRs shortly.

**Comment by fpotter** [comment]
From https://github.com/rust-lang/rfcs/pull/2837#issuecomment-570716695 (not sure where discussion belongs)

----

I'm late, but... Apple does continue to support 32-bit for iOS devices and the simulator.

Using Catalina and Xcode 11.3 with a deployment target set to iOS 10.0 or earlier, I can build an app for i386 and armv7.

If I download the iOS 10 simulator and set the simulated device to "iPhone 5", I can run that i386 binary in the simulator on Catalina.

iOS 11 was the first release to go 64-bit only, but plenty of apps continue to support iOS 10.0 or below which may run on both 32-bit and 64-bit devices.

**Comment by pietroalbini** [comment]
@fpotter hmm, that wouldn't help with the `i686-apple-darwin` target right?

Anyway, I don't feel Apple will keep 32-bit iOS support forever, and reducing support for everything related to 32-bit Apple in one sweep is probably better.

**Comment by fpotter** [comment]
@pietroalbini Right, removing `i686-apple-darwin` seems legit to me.  Snow Leopard (10.6) was the last release to support 32-bit CPUs and that came out in 2009.  It looks like Apple hasn't sold a 32-bit Mac since 2006.

I just think dropping 32-bit iOS is a little premature.  iOS supported 32-bit as recently as iOS 10 (released in 2016).  They sold new 32-bit devices into 2015 (i.e. original iPad Mini, iPhone 5c).

I work on an iOS framework that uses Rust and currently supports down to iOS 9.0.  For us, removal of 32-bit support means we'll need to bump our minimum supported iOS version to iOS 11.0.  Or, we can keep supporting iOS 10 and below, but ask our customers to restrict their supported devices to 64-bit only.  

By comparison, many other popular iOS libraries are slow to remove old iOS versions.  e.g. Firebase (>= iOS 9.0), Facebook (>= iOS 8.0), Mixpanel (>= iOS 8.0), Crashlytics (>= iOS 7.0).

**Comment by shepmaster** [comment]
As I understand it, nothing is being **dropped** here, just that our level of support is decreasing. This means that you'd have to use a tool to compile the standard library for those platforms locally instead of getting it from rustup.

**Comment by ehuss** [comment]
The error message from rustup (1.21.1) is a bit unfortunate:

```
info: skipping nightly which is missing installed component 'rust-std'
```

It doesn't say which `rust-std` component is missing, so it took me a few minutes to realize what was wrong.  It might be nice to look at improving that message.  Perhaps include which component is missing, and instructions on how to remove it?

I'm not sure what the behavior will be on stable/beta.  Is it a hard error?  Or does it print the same `info` message and do nothing?  For people who don't follow nightly, or RFCs, or read the release notes, I suspect it is a recipe for confusion.

**Comment by pietroalbini** [comment]
@kinnison can we improve the error message by including the target name?

**Comment by kinnison** [comment]
Yes, we probably could...  I've filed https://github.com/rust-lang/rustup/issues/2191

**Comment by mexus** [comment]
Component history fixed by@LeSeulArtichaut in https://github.com/rust-lang/rustup-components-history/pull/13

**Comment by pietroalbini** [comment]
This shipped in 1.42.0! Thanks everybody who helped with this effort!
