### ISSUE TITLE
Tracking issue for RFC 2700: numeric constants as associated consts

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/rust#68490]
This is a tracking issue for [the RFC 2700](https://github.com/bstrie/rfcs/blob/intconst/text/0000-associated-constants-on-ints.md) (rust-lang/rfcs#2700): "Deprecate stdlib modules dedicated to numeric constants and move those constants to associated consts".

**Steps:**

- [ ] Add new constants (see #68123) 
- [ ] Stabilize new constants in case they won't be merged as insta-stable ([see instructions on rustc-guide][stabilization-guide])
- [ ] Potentially deprecate old items (see unresolved questions below)
- [ ] Adjust documentation ([see instructions on rustc-guide][doc-guide])

[stabilization-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs

**Unresolved questions:**

- [ ] Should the old items be deprecated? See the RFC thread as well as ["unresolved questions"](https://github.com/bstrie/rfcs/blob/intconst/text/0000-associated-constants-on-ints.md#unresolved-questions): 
  > How long should we go before issuing a deprecation warning? At the extreme end of the scale we could wait until the next edition of Rust is released, and have the legacy items only issue deprecation warnings when opting in to the new edition; this would limit disruption only to people opting in to a new edition (and, being merely an trivially-addressed deprecation, would constitute far less of a disruption than any ordinary edition-related change; any impact of the deprecation would be mere noise in light of the broader edition-related impacts). However long it takes, it is the opinion of the author that deprecation should happen eventually, as we should not give the impression that it is the ideal state of things that there should exist three ways of finding the maximum value of an integer type; we expect experienced users to intuitively reach for the new way proposed in this RFC as the "natural" way these constants ought to be implemented, but for the sake of new users it would be a pedagogical wart to allow all three to exist without explicitly calling out the preferred one.

**Comment by AGausmann** [comment]
> Add new constants (see #68123)

#68325 is the relevant PR

**Comment by faern** [comment]
I have implemented the stabilization and documentation changes needed to show people which constant is the preferred one now. I will submit this as a PR in a few days when the unstable version has been out for a bit over a week.

You can find the code here: https://github.com/rust-lang/rust/compare/master...faern:stabilize-assoc-int-consts?expand=1

What parts of it I don't think will be controversial at all:
* Stabilizing the unstable constants
* Updating the documentation on the old constants to indicate there are now better alternatives
* Update the integer/float documentation examples to actually use the new constants (the docs should reflect the preferred way)

Other changes that possibly might create some discussion:
* Exactly how to formulate the documentation telling people to not use the old constants any longer.
* Moved the `min_value`, `max_value` methods to the very bottom of the integer impl block, so they are not taking up the best spots in the documentation, but is rather moved away a bit. The `MIN`/`MAX` constants took their place. They can still of course easily be found, but they are not at the very top.

I opted for doing what `Error::description()` did with the documentation. Saying something like this:
```rust
//! **this module is soft-deprecated.**
//!
//! Although using these constants won’t cause compilation warnings,
//! new code should use the associated constants directly on
//! the [`i128` primitive type](../../std/primitive.i128.html) instead. 
```

I added soft deprecation notices to:
* Module level documentation of `core` and `std` modules for all integer and float types
* The old free standing `MIN`/`MAX` constants in the *integer* modules.
* The `min_value`/`max_value` methods on the integer types.

**Comment by faern** [comment]
The code/docs were changed a bit after I wrote that last comment just above. But the stabilization PR is live now.

**Comment by faern** [comment]
One thing that remains is to improve the compiler error that mentions the `MIN` and `MAX` constants. Try this code on nightly:
```rust
fn main() {
    match 5i32 {
        5 => (),
    }
}
```
It gives the following error:
```
error[E0004]: non-exhaustive patterns: `std::i32::MIN..=4i32` and `6i32..=std::i32::MAX` not covered
```
Now when the associated constants are the preferred ones the error should be
```
error[E0004]: non-exhaustive patterns: `i32::MIN..=4i32` and `6i32..=i32::MAX` not covered
```

**Comment by bstrie** [comment]
As the original author of RFC 2700, I propose the following resolution to the two currently-listed unresolved questions:

1. "Should the old items be deprecated?" I propose **yes**. I have a PR here for further discussion: https://github.com/rust-lang/rust/pull/78335

2. "Should constants from std::{f32, f64}::consts also be made associated consts?" I propose **no**. As mentioned in the RFC, the majority of the benefit of this change concerns the integer types, which have no analogue to the `consts` module on the float types. While it remains my opinion that having a stdlib type shadowing a primitive type is undesirable, I think it's reasonable to leave this topic to a future RFC.

**Comment by Lokathor** [comment]
if I can't just write `f32::NAN` then what the heck is the point of any of this.

**Comment by bstrie** [comment]
Unsure if that was meant to be sarcasm, but if you take the time to read the original RFC you will see that the point of all this is that `std::u8::MAX` and `u8::max_value()` are both substandard alternatives to `u8::MAX` that only exist because of extremely temporary technical limitations. When fixing this for the integral types it was natural to preserve symmetry with the floating point types as well. Some people objected to *all* the constants defined for the floating point types being given this treatment. Since the point of the RFC was to fix the integral types, we conceded so as to avoid gridlock over tangential concerns. The libs team could, of course, decide to change this policy (it would not be out of the realm of possibility to simply amend the existing RFC), but I am not on the libs team. My PR fully deprecates the constants that were superseded in https://github.com/rust-lang/rust/pull/68952 . I'm content to take this one step at a time.

**Comment by Lokathor** [comment]
I was not being sarcastic at all.

If floating types don't get the same design fixes applied them, then that's dumb for all the reasons that `std::u8::MAX` is dumb.

**Comment by bstrie** [comment]
You're preaching to the choir; as mentioned in the accepted RFC, the original RFC text had proposed this treatment for all the float constants. I'd be happy if the libs team decided to deprecate the float shadow modules as well, but in the absence of that decision there's no need to put off deprecating the integral shadow modules any longer. This RFC has gone on for quite long already.

**Comment by bstrie** [comment]
(It's also worth noting that your specific example of `f32::NAN` does indeed exist, and the alternative `std::f32::NAN` would be deprecated by this proposal. It's things like `std::f32::consts::PI` that wouldn't be.)

**Comment by bstrie** [comment]
In my deprecation PR I ran into some obstacles and have updated the issue here with references to new issues and PRs. I'll hold off on proposing deprecation until those are addressed.

**Comment by m-ou-se** [comment]
We discussed the open questions in the library meeting last week. Our conclusions were:

> Should the old items be deprecated?

Yes.

> Should constants from `std::{f32, f64}::consts` also be made associated consts? 

No. At least not as part of this tracking issue/RFC. That could be a separate proposal, with a separate discussion.

**Comment by bstrie** [comment]
Checking off "adjust the documentation" (found no uses of the old consts in the reference, the book, or Rust By Example, which I presume faern fixed when originally adjusting the stdlib docs). In addition #79877 has landed, which finishes checking off all the new issues that were filed after the closing of the prior deprecation effort (#78335). Once #79877 rides the train into beta later this month I'll file a new deprecation PR. And once that's all done I'll write up a new RFC to discuss the fate of the floating-point `const` modules.

**Comment by bstrie** [comment]
With the merge of https://github.com/rust-lang/rust/pull/80958 , I'm happy with where this is at. I will leave this issue open until such time as the old items are marked as fully deprecated rather than just deprecated-in-future, but making that change is not a priority of mine at this moment.

**Comment by pitaj** [comment]
RE from #107587 

> The float modules are a bit weird since all the constants mentioned above are redundant, but they also contain the `core::{f32, f64}::consts` modules, and these do contain information that isn't available elsewhere (constants like E, PI, SQRT_2, etc)

Can we move them into a module like `core::math` or something?

- `core::f32::consts` would become `core::math::f32`
- `core::f64::consts` would become `core::math::f64`

**Comment by pitaj** [comment]
Putting it here because I haven't see much discussion elsewhere. [small previous discussion](https://github.com/rust-lang/rust/pull/98198/files#r906359288)

It appears that the `std::char` constants haven't been marked as "deprecated" or "deprecation planned", despite all being on the `char` primitive type as well. It seems weird to keep duplicate constants around. Is this something needing a separate RFC (or maybe just ACP) or can we loop it in here?

**Comment by faern** [comment]
> Can we move them into a module like `core::math` or something?
> 
>     * `core::f32::consts` would become `core::math::f32`
>     * `core::f64::consts` would become `core::math::f64`

I don't think creating yet another copy of the constants is the right direction. Since the old ones can't be removed, only deprecated, the API surface will inevitably grow. I'm all for moving constants to better places when the new place is actually better. Here it feels like they are equally bad/good but just duplicated for the sake of deprecation.

Personally I always wanted to move the float constants onto the actual float types as well. But I know this was controversial back in RFC 2700. I know there was some talk about being able to put modules in types, so one could have `f32::math::PI` but that the language did not at the time support it. I can't find that comment now so I'm not sure what the status of this is.

> It appears that the std::char constants haven't been marked as "deprecated" or "deprecation planned", despite all being on the char primitive type as well. It seems weird to keep duplicate constants around. Is this something needing a separate RFC (or maybe just ACP) or can we loop it in here?

I'm all for deprecating that as well, but not in this RFC/issue. This issue seems to be controversial as is and moves way too slowly. Anything that can just have this be merged asap would be great. Then further similar work can happen in other RFCs. If we let RFCs scope creep it will greatly slow down their progress.
