### ISSUE TITLE
Tracking Issue for the `avr-interrupt`/`avr-non-blocking-interrupt` calling convention/ABI

### ISSUE THREAD

**Issue by dylanmckay** [rust-lang/rust#69664]
This is a tracking issue for the RFC "XXX" (rust-lang/rfcs#NNN).
The feature gate for the issue is `#![feature(FFF)]`.

### Steps

- [ ] Implement the RFC
- [ ] Adjust documentation ([see instructions on rustc-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-guide][stabilization-guide])

[stabilization-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs

### Unresolved Questions

None yet.

### Implementation history

* #69478 introduces AVR as a tier-3 target upstream

**Comment by dylanmckay** [comment]
Raised to appease `tidy` in #69478.

**Comment by joshtriplett** [comment]
In https://github.com/rust-lang/rust/issues/40180 we mentioned wanting a (single) RFC for target-specific interrupt calling conventions; you may want to coordinate with that work in progress.
