### ISSUE TITLE
Tracking Issue for Generator Memory Usage

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#69826]
(old issue: https://github.com/rust-lang/rust/issues/52924)

This issue tracks ideas for reducing the memory footprint of generators.

* [ ] https://github.com/rust-lang/rust/issues/62321 – `size_of_val` in a generator can make the generator bigger
* [ ] https://github.com/rust-lang/rust/issues/62575 – Better greedy layout computation for generators
* [ ] https://github.com/rust-lang/rust/issues/62952 – Copy trait defeats generator optimization
* [ ] https://github.com/rust-lang/rust/issues/62958 – Async fn doubles argument size
* [ ] https://github.com/rust-lang/rust/issues/66100 – [codegen] Unnecessary panicking branches in resumption of infinite generator (stored in static variable)
* [ ] https://github.com/rust-lang/rust/issues/69815 – Generators should use smaller discriminants

Note that this issue is different from https://github.com/rust-lang/rust/issues/69663, which tracks typesystem-level improvements regarding generators. This issue is purely about the code generation aspect.

**Comment by pnkfelix** [comment]
Visiting during T-compiler backlog bonanza. This isn't the same kind of "tracking issue" that we associated with the C-tracking-issue label (in terms of a specific feature being designed) 

@rustbot label: +metabug -C-tracking-issue

**Comment by oli-obk** [comment]
This is now being tracked as a github project: https://github.com/orgs/rust-lang/projects/21/views/1?layout=board

**Comment by Thomasdezeeuw** [comment]
> This is now being tracked as a github project: https://github.com/orgs/rust-lang/projects/21/views/1?layout=board

@oli-obk that link is either incorrect or the project is private, in either case it doesn't work

**Comment by oli-obk** [comment]
hmm

> Only organization owners can change project visibility.

Looking how to fix that, sorry

**Comment by anderspapitto** [comment]
this issue should also be tracked here https://github.com/rust-lang/rust/issues/62958 - see https://github.com/rust-lang/rust/issues/114064 for a Generator-specific version

**Comment by ofek** [comment]
Has there been any progress on this?
