### ISSUE TITLE
Tracking Issue for the Wake trait

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/rust#69912]
This is a tracking issue for the `Wake` trait.
The feature gate for the issue is `#![feature(wake_trait)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Write an RFC for the `Wake` trait
- [ ] Adjust documentation ([see instructions on rustc-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-guide][stabilization-guide])

[stabilization-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs

### Implementation history

- Initial implementation: #68700.

**Comment by yoshuawuyts** [comment]
Filed a stabilization PR: https://github.com/rust-lang/rust/pull/74304

**Comment by yoshuawuyts** [comment]
These are the uses the `Wake` trait will replace:

- [`RawWaker` with raw pointers can be confusing for people learning about futures](https://twitter.com/mountain_ghosts/status/1284156484583120899). `Wake` makes this safe and easier to follow.
- Replacement for the [`waker-fn` crate](https://docs.rs/waker-fn/1.0.0/waker_fn/) and [`wakeful`](https://docs.rs/wakeful/0.1.1/wakeful/fn.waker_fn.html) crates that provide a `waker_fn` function to easily create a waker from a closure. [Example use in the `blocking` crate](https://github.com/stjepang/blocking/blob/8c04ac08bf201cca868787eb5a42601535b25a6c/src/lib.rs#L317).
- Tokio uses an internally-defined `Wake` trait that has the same shape and use as `core::task::Wake` ([src](https://github.com/tokio-rs/tokio/blob/a78b1c65ccfb9692ca5d3ed8ddde934f40091d83/tokio/src/util/wake.rs#L7-L50))
- It makes it easy to author waker-based tests with. [Example from `rustc`](https://github.com/rust-lang/rust/blob/92206ab8a273d6431b07488684965a2e9b9e00ac/src/test/ui/async-await/issue-73137.rs), [example from `event-listener`](https://github.com/stjepang/event-listener/blob/2f7b3269a59333496d8e7e328c9983f66ddf4e87/tests/notify.rs#L10-L15).

This is mostly a useful helper to enable people to safely author `Waker` impls through, which is useful during testing, teaching, and when you only have a single callback that needs to be called when woken.

**Comment by taiki-e** [comment]
@yoshuawuyts 
> These are the uses the `Wake` trait will replace:
 
I believe [`futures::task::ArcWake`](https://docs.rs/futures/0.3.5/futures/task/trait.ArcWake.html) should be added to that list.

**Comment by memoryruins** [comment]
The `Wake` trait was stabilized in https://github.com/rust-lang/rust/pull/74304 and is now on stable rustc `1.51.0`.
Thanks everyone who helped see this through!
