### ISSUE TITLE
Tracking Issue for `Option::zip` and `Option::zip_with` (feature `option_zip`)

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/rust#70086]
This is a tracking issue for `#![feature(option_zip)]` which was introduced in #69997.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Resolve unresolved questions
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- [ ] Should we also include `zip_with` in the public API? Seems like a niche API and is easily replaced with `a.zip(b).map(f)`.

**Comment by cwfitzgerald** [comment]
My personal two cents are that both should be included, as even if `zip_with`'s use may be a bit more rare, I think the pattern of `(Option, Option) -> Option<Something>` is common enough, and the terseness win is great enough that it should be kept.

**Comment by WaffleLapkin** [comment]
> Edit: One note is that zip_with and zip().map() take different functions as argument, the former takes FnOnce(T, U) -> R the other takes FnOnce((T, U)) -> R, the former of which is generally more directly useful to calling off to other methods.

Yeah, I've just found the same thing. E.g.:
```rust
let a: Option<i32> = ...;
let b: Option<i32> = ...;
let res = a.zip_with(b, Add::add);
// or
let res = a.zip(b).map(|(a, b)| a + b); // destruction needed 
```
I think in this example `zip_with` is nicer/clearer than `zip`+`map`

**Comment by lzutao** [comment]
I opened a PR to stabilize `Option::zip` only: https://github.com/rust-lang/rust/pull/72938

**Comment by WaffleLapkin** [comment]
One interesting note is that `try { (a?, b?) }` is lazy, where is `a.zip(b)` is not. However, I personally think that the later is easier to read (I think that early returns are weird in cases like that or `Ok(res?)`).

Maybe we should also implement smt like this:
```rust
fn zip_lazy(self, f: impl FnOnce() -> Option<U>) -> Option<T, U> { ... }
```
? :thinking:

**Comment by lebensterben** [comment]
There's one use case, suppose foo and bar are Option<Vec<T>>.
With this new feature, we can have foo.zip_with(bar, Vec::extend) for example.
If we use zip() and map(), that'd be foo.zip(bar).map(|first, second| first.extend(second))
That's just unnecessarily long.

**Comment by qm3ster** [comment]
@lebensterben do you mean `foo: Option<&mut Vec<T>>`? Or `foo.as_mut()` (in either)?
Because otherwise it would also be immediately dropped.
```rust
foo.as_mut().map(|first| Some(first.extend_from_slice(&bar?)));
// or
let _: Option<_> = try{ foo.as_mut()?.extend_from_slice(&bar?) };
```

**Comment by sherubthakur** [comment]
I really like the interface haskell's lift functions have
```Haskell
liftA :: Applicative f => (a -> b) -> f a -> f b
liftA3 :: Applicative f => (a -> b -> c -> d) -> f a -> f b -> f c -> f d
liftA2 :: (a -> b -> c) -> f a -> f b -> f c
```
Maybe we can have something similar in Rust
```Rust
Option::lift(f, optional1)
Option::lift2(f, optional1, optiona2)
// etc
```
Probably the same interface for all applicatives (Iterators, Result, etc).

**Comment by sollyucko** [comment]
Would `lift` be equivalent to `map` and `lift2` equivalent to `zip_with`?

**Comment by sherubthakur** [comment]
@sollyucko yeah!

**Comment by sdroege** [comment]
>  Should we also include zip_with in the public API? Seems like a niche API and is easily replaced with a.zip(b).map(f).

We have quite many calls to `zip()` followed by `map()` now in the GStreamer Rust bindings for working with `Option<u64>`, e.g. to add them together. `x.zip(y).map(|(x, y)| x + y)` is more annoying to type than `x.zip_with(y, |x, y| x + y)` but I can see the point of not including it because if you include it, why not also have a shorter form (`zip_and_then`?) of the equally often used `x.zip(y).and_then(|(x, y)| x.checked_add(y))`.

**Comment by qm3ster** [comment]
@sdroege 
```rust
let a = try { x? + y? };
let b = try {x?.checked_add(y?)? };
```
![feels_good](https://user-images.githubusercontent.com/10551234/127151060-dd17a80b-1965-4788-b967-f69032b7c822.png)

**Comment by LoganDark** [comment]
Hell yeah another useful utility function locked behind `unstable`, unchanged for almost 3 years

**Comment by WaffleLapkin** [comment]
@LoganDark fyi `Option::zip` _is_ stabilized. `zip_with` is not, but it can be emulated with `a.zip(b).map(|(x, y)| f(x, y))`.

I got under the impression that T-libs did not want to stabilize `zip_with` at all, maybe it should be removed (or maybe the opinions have changed since last time I checked).

**Comment by LoganDark** [comment]
> fyi `Option::zip` _is_ stabilized.

oh, it is? I accidentally autocompleted `zip_with` and then thought `zip` was still included in the `option_zip` feature, oops. can confirm `zip` itself is stabilized, thank you :)
