### ISSUE TITLE
Tracking Issue for ASCII methods on OsStr

### ISSUE THREAD

**Issue by TyPR124** [rust-lang/rust#70516]
Feature gate: `#![feature(osstring_ascii)]`

### Public API

```rust
impl OsStr {
    pub fn make_ascii_lowercase(&mut self);
    pub fn make_ascii_uppercase(&mut self);
    pub fn to_ascii_lowercase(&self) -> OsString;
    pub fn to_ascii_uppercase(&self) -> OsString;
    pub fn is_ascii(&self) -> bool;
    pub fn eq_ignore_ascii_case<S: AsRef<OsStr>>(&self, other: S) -> bool;
}
```

### Steps / History

- [x] #70048 - Stabilized traits necessary to obtain `&mut OsStr`
- [x] #69937 - Added ASCII methods on `OsStr`
- [x] Final commenting period (FCP)
- [x] #80193 - Stabilization PR

### Unresolved Questions

- None yet.

**Comment by matklad** [comment]
Just needed `OsStr::to_ascii_lowercase` to manipulate paths on windows -- I need to lower case driver letter, `C:\Program Files` -> `c:\Program Files`.

**Comment by jplatte** [comment]
Currently, SQLx contains

```rust
env::var("SQLX_OFFLINE")
    .map(|s| s.eq_ignore_ascii_case("true") || s == "1")
    .unwrap_or(false)
```

The UTF-8 check that is included in there, while not a problem in practice, seems pointless but changing to `var_os` lands me here because of the `eq_ignore_ascii_case`. Also, if somebody did a similar thing with `.ok()` instead of `.unwrap_or(...)`, the `var_os` version could drop that and would then be a bit less noisy.

**Comment by tesuji** [comment]
#80193 is an stabilization PR.
Since lib team wants to do fcp in the tracking issue. @m-ou-se could you start one ?

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by dtolnay** [comment]
Slight question about `eq_ignore_ascii_case` -- normally when dealing with AsRef args, they come in without an explicit reference in the signature (https://doc.rust-lang.org/std/process/struct.Command.html#method.new), except when necessary to support a lifetime in the return value (https://doc.rust-lang.org/std/path/struct.Path.html#method.new). Currently https://doc.rust-lang.org/1.49.0/std/ffi/struct.OsStr.html#method.eq_ignore_ascii_case is declared as:

```rust
pub fn eq_ignore_ascii_case<S: ?Sized + AsRef<OsStr>>(&self, other: &S) -> bool
```

Is this supposed to be `fn eq_ignore_ascii_case<S: AsRef<OsStr>>(&self, other: S) -> bool` instead?

@rfcbot concern eq_ignore_ascii_case &amp;S

**Comment by TyPR124** [comment]
> Is this supposed to be `fn eq_ignore_ascii_case<S: AsRef<OsStr>>(&self, other: S) -> bool` instead?

I think it should be. I'm not sure why I wrote it like I did originally, but this makes more sense to me.

I can make that PR if needed. Or can it be done in the stabilization PR? Not sure what the process is from here.

**Comment by dtolnay** [comment]
@rfcbot resolve eq_ignore_ascii_case &amp;S
@rfcbot reviewed
Fixed in #81710.

**Comment by zseri** [comment]
@TyPR124 you can tick the FCP box, as the FCP is complete.
