### ISSUE TITLE
Tracking Issue for {BTreeMap,BTreeSet}::drain_filter

### ISSUE THREAD

**Issue by ssomers** [rust-lang/rust#70530]
This is a tracking issue for the Implementation of a `drain_filter` method on `BTreeMap` and `BTreeSet`, similar to the one in LinkedList and in Vec (#43244).
The feature gate for the issue is `#![feature(btree_drain_filter)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement suboptimally, relying on an `Ord` bound: efficient for simple and common cases, but falling back on a coarse restart after complicated removals.
- [ ] Possibly adjust the underlying tree representation (using `Cell`s) to cater .
- [ ] Implement all cases without relying on an `Ord` bound, tracking
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions
- Do we need to implement some post-panic guarantees beyond memory leaks, like the ones `Vec` and `LinkedList` provide but do not document, as I tried to discuss in #67290?

### Implementation history
- Initial suboptimal implementation #68770
- Related attempt to implement `drain` and `retain` #66747

**Comment by droundy** [comment]
Is there another issue for adding these to HashSet and HashMap?

**Comment by mbrubeck** [comment]
> Is there another issue for adding these to HashSet and HashMap?

That is #59618.

**Comment by simias** [comment]
I stumbled upon this issue from the docs and I must say that I'm a bit confused: I wanted to replace a HashMap with a BTreeMap in my code, but then I noticed that it didn't have a `retain` method unlike the hash counterpart. Then I noticed this experimental `drain_filter` method.

As far as I can tell isn't this method the same thing as HashMap's `retain`, just with the boolean result of the predicate complemented?

Looking at the APIs of BTreeMap, Vec and HashMap I find the following methods that all deal with filtering the contents of the collection:

`Vec::retain`: predicate that gets passed an `&T`
`HashMap::retain`: predicate that gets passed an `&K, &mut V`

`Vec::drain_filter`: predicate that gets passed an `&mut T`
`BTreeMap::drain_filter` (this issue): predicate that gets passed a `&K, &mut V`

LinkedList has `drain_filter` (taking a `&mut T`) but no `retain`. And then there's this old RFC from 2015 that proposes `BTreeMap::retain`: https://github.com/rust-lang/rfcs/issues/1338

I genuinely don't get the logic behind these choices of mutability and naming.

In particular I really think that the APIs of `HashMap` and `BTreeMap` should match as much as practically possible since they are so conceptually similar and it's not uncommon to want to replace one by the other in hindsight (in particular if your ordering requirements change).

**Comment by simias** [comment]
Oh, I noticed an obvious difference between retain and drain_filter: the later returns an iterator. So now I understand the need for both, but I'm still surprised by the lack of consistency between collections when it comes to mutability and the lack of `drain_filter` for HashMaps.

**Comment by ssomers** [comment]
When I first looked into it, I remember a `drain_filter` where the predicate had the opposite meaning. I liked the current one better: true means "yes, drain".

> now I understand the need for both

If you really do, please explain, but I think you mean you understand why someone made `retain` and later someone made a more general `drain_filter`, probably for another container. At least that's how I hope it went.

**Comment by zserik** [comment]
I think if we could replace `retain` with an implementation solely based upon `drain_filter`, this would prove that `retain` is therefore redundant.

**Comment by mbrubeck** [comment]
`HashMap::drain_filter` is already available in the nightly toolchain.  It's behind a feature flag, like the other `drain_filter` methods.  On stable Rust, you can use `HashMap::drain_filter` via [hashbrown](https://crates.io/crates/hashbrown).

For the status of `drain_filter` in all the standard collection types, see https://github.com/rust-lang/rfcs/issues/2140.  For discussion of the naming and API design for `drain_filter`, see https://github.com/rust-lang/rust/issues/43244, especially [this comment](https://github.com/rust-lang/rust/issues/43244#issuecomment-641638196).

**Comment by simias** [comment]
Thank you @mbrubeck, this was the context I lacked.

**Comment by mbrubeck** [comment]
I submitted #79026 to add `BTreeMap::retain` and `BTreeSet::retain`, implemented in terms of `drain_filter` as suggested above.

**Comment by ssomers** [comment]
> if we could replace `retain` with an implementation solely based upon `drain_filter`

I think `retain` is the same as `drain_filter` with the predicate inverted and the result dropped, [as in this playground demo](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=04931b36ae56a1089f76c3c96130aa3f). But in [the hashbrown code](https://github.com/rust-lang/hashbrown/blob/master/src/map.rs) they are unrelated. Maybe that's to improve performance, because `drain_filter` does add some overhead for setting up and using an iterator. Either way, it's pretty easy to implement `retain` in `BTreeMap/Set`.

**Comment by ssomers** [comment]
Note that this (nightly only) `drain_filter` in BTreeMap/Set is as optimal as I can imagine when you drain only a few elements, but definitely not when you drain a lot of elements. Of course, if you typically drain all but a few elements, you shouldn't be using `drain_filter` at all - better `into_iter`, `into_keys` or `into_values` the whole lot and divert the few ones you want to retain to a new map/set. But if you drain say half the elements, it's nowhere near as efficient as something like `split_off`. So I'm not sure this is good enough to become stable at all.

**Comment by maboesanman** [comment]
As it is now the documentation makes no claims about the order of the events returned from the iterator. Is this intended? having this iterator return in sorted order, or even returning a double ended iterator similar to range could be pretty useful.

**Comment by ssomers** [comment]
It's not intended not to be made, this claim…  I mean, I forgot to mention that, because it's guaranteed to come in ascending order.

**Comment by maboesanman** [comment]
it's certainly worth documenting that, but I also think it's worth making this into a double ended iterator.

**Comment by ssomers** [comment]
Making it double ended is something I never thought about, but it's guaranteed to work. Not sure about the same for `drain_filter`, but that doesn't matter here.

**Comment by ssomers** [comment]
Oh wait, sorry, I though this was the `drain` tracking issue…

**Comment by ssomers** [comment]
It's definitely not easy to make `drain_filter` double-ended, and almost definitely possible. I wonder why though.  Unlike iterators and `range`, `drain_filter` does not allow shortcutting, stopping when you've reached the elements you were interested in. You have to see the whole collection through, front to back. So by querying the length up front, it seems to me you can easily do the same thing you could do with a double-ended iterator.

**Comment by allada** [comment]
I just came across a use case for this method but found it could not handle the case where I need to run my predicate function on the map in reversed order. There are work arounds to this problem, but thought I'd notate potential pain pointers of users.

**Comment by kornelski** [comment]
I've just had a use-case for something like this, but I needed to drain and filter a specific **range** of key (remove certain values that are after a given key in the btreemap). `drain` on `Vec` takes a range. Maybe this one could too?

**Comment by vkrasnov** [comment]
+1 for @kornelski I most definitely have a use-case for a drain with range in btreemap

**Comment by kaimast** [comment]
I also use this to remove all entries within a specific range. I probably would would not need `drain_filter` if there was a `drain` function that took a range...

**Comment by the8472** [comment]
> If the iterator is only partially consumed or not consumed at all, each of the remaining elements is still subjected to the closure, which may change its value and, by returning true, have the element removed and dropped.

For the same reasons this is problematic in Vec and LinkedLists this is also problematic on the BTree collections.

https://github.com/rust-lang/rust/issues/43244#issuecomment-641638196
https://github.com/rust-lang/rfcs/pull/3288

**Comment by KonradHoeffner** [comment]
This feature stopped working for me with the newest nightly version as of 2023-06-16.

**Comment by Nemo157** [comment]
The feature was renamed in https://github.com/rust-lang/rust/pull/104455.

**Comment by KonradHoeffner** [comment]
Thanks! After replacing "btree_drain_filter" with "btree_extract_if" and "drain_filter" with "extract_if" the code compiles as before.

**Comment by QuineDot** [comment]
The `ExtractIf` definitions have lifetime bounds on the `F` parameter which, as far as I can tell, are unnecessary.
```rust
// BTreeMap version
pub struct ExtractIf<'a, K, V, F, A: Allocator + Clone = Global> where
    F: 'a + FnMut(&K, &mut V) -> bool,
```
Which causes [this to fail without extra bounds,](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=3f40fa712ebbc90e83fa3502f37b5d33) for example.
```rust
struct Hmm<K, V>(BTreeMap<K, V>);
impl<K: Ord, V> Hmm<K, V> {
    fn ex<F>(&mut self, f: F) -> Box<dyn Iterator<Item = (K, V)> + '_>
    where
        F: FnMut(&K, &mut V) -> bool,
    {
        Box::new(self.0.extract_if(f))
    }
}
```
The `T: 'a` on `BTreeSet` can also probably be removed (it's implied on the `extract_if` method anyway).

The same is probably also true for [`linked_list::ExtractIf`.](https://doc.rust-lang.org/std/collections/linked_list/struct.ExtractIf.html#impl-Iterator-for-ExtractIf%3C'_,+T,+F,+A%3E)

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting today. As with `Vec::extract_if` in #43244, this should take a range argument to limit the extraction to a subset of the tree. It is often desirable to only scan or extract only a subset of elements in a tree.

**Comment by rs-sac** [comment]
@Amanieu, the range argument to these functions that was requested several months ago was recently added.

Given that `Vec::extract_if` and `LinkedList::extract_if` were stabilized in 1.87 and `HashMap::extract_if` in 1.88, is this similar feature now an appropriate candidate for stabilization?

**Comment by Amanieu** [comment]
In our previous meeting the range argument was the only concern. Now that this is resolved this should be good to stabilize.

@rfcbot merge

**Comment by dtolnay** [comment]
The signature of `BTreeSet::extract_if` is weird. I put up a fix in https://github.com/rust-lang/rust/pull/142484.

@rfcbot reviewed

**Comment by the8472** [comment]
Uh, a bit late in the process, but the tracking issue doesn't have an API signature overview.

Soo...

```rust
pub fn extract_if<F, R>(
    &mut self,
    range: R,
    pred: F,
) -> ExtractIf<'_, K, V, R, F, A> ⓘ
where
    K: Ord,
    R: RangeBounds<K>,
    F: FnMut(&K, &mut V) -> bool,
```

but

```rust
pub fn range<T, R>(&self, range: R) -> Range<'_, K, V> ⓘ
where
    T: Ord + ?Sized,
    K: Borrow<T> + Ord,
    R: RangeBounds<T>,
```

Can/should we add support for the K: Borrow indirection to the range argument?
