### ISSUE TITLE
Tracking Issue for core::task::ready! macro

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#70922]
This is a tracking issue for the `ready!` macro.
The feature gate for the issue is `#![feature(ready_macro)]`.

### Steps / History

- [x] Initial implementation in https://github.com/rust-lang/rust/pull/70817
- [x] FCP
- [x] Stabilization PR in https://github.com/rust-lang/rust/pull/81050
- [x] Reverting stabilization: https://github.com/rust-lang/rust/pull/89651
- [ ] FCP, second attempt
- [ ] Stabilization, second attempt

### Unresolved Questions

- [x] bug: `pub macro` defined in submodule is shown at the wrong path #74355
- [ ] Use `.ready()` method instead? See https://github.com/rust-lang/rust/issues/89780

**Comment by yoshuawuyts** [comment]
https://github.com/rust-lang/rust/pull/77862 seems like it may resolve the rustdoc issue

**Comment by RalfJung** [comment]
@yoshuawuyts why is "Stabilization PR" checked above? There doesn't seem to actually be a stabilization PR yet?

**Comment by yoshuawuyts** [comment]
@RalfJung ah, my bad. I checked it yesterday as I was about to file a stabilization PR — right before realizing it was in fact not ready. I forgot to uncheck it.

Fixed now tho!

**Comment by yoshuawuyts** [comment]
Closed via https://github.com/rust-lang/rust/pull/81050
