### ISSUE TITLE
Tracking Issue for `or_insert_with_key` feature

### ISSUE THREAD

**Issue by ChaiTRex** [rust-lang/rust#71024]
### Steps

- [x] Implementation in `std` (https://github.com/rust-lang/rust/pull/70996)
- [x] Merge into `std`
- [x] Implementation in `hashbrown` crate (https://github.com/rust-lang/hashbrown/pull/152)
- [x] Merge into `hashbrown`
- [x] Stabilization (https://github.com/rust-lang/rust/pull/78083)
- [x] Make pull request with documentation changes from [`ChaiTRex/hashbrown`](https://github.com/ChaiTRex/hashbrown) to `rust-lang/hashbrown` (https://github.com/rust-lang/hashbrown/pull/217)
- [x] Close old issue requesting feature (https://github.com/rust-lang/rfcs/issues/1202)

**Comment by jonas-schievink** [comment]
>     * Implementation in `std` (#70966)

That seems like the wrong PR

**Comment by ChaiTRex** [comment]
@jonas-schievink Thank you. Corrected.

Also, added a 2015 issue that requested this feature so that it can be closed if this is accepted.

**Comment by ChaiTRex** [comment]
Merged into `hashbrown` (https://github.com/rust-lang/hashbrown/pull/152) and into `std` as unstable (https://github.com/rust-lang/rust/pull/70996).

**Comment by a1phyr** [comment]
What does this feature need to be stabilized ?

**Comment by ChaiTRex** [comment]
This is my first stabilization report, so please let me know if it's insufficient.

# Stabilization report

## Summary

This allows inserting key-derived values when a `HashMap`/`BTreeMap` entry is vacant.

The difference between this and  `.or_insert_with(|| ... )` is that this provides a reference to the key to the closure after it is moved with `.entry(key_being_moved)`, avoiding the need to copy or clone the key.

## Examples

* [Doc test](https://play.rust-lang.org/?version=nightly&edition=2018&gist=5bc0e9994d6946976261a6c465b14add)
* [Rust book chapter 13 memoization exercise](https://play.rust-lang.org/?version=nightly&edition=2018&gist=3d5c176a646db1ea76d6513756cb053b)

## Edge cases

I cannot think of any edge cases.

# Stabilization pull request

The stabilization pull request is https://github.com/rust-lang/rust/pull/78083

**Comment by jplatte** [comment]
Stabilized, this tracking issue can be closed AFAICT 🙂

**Comment by ChaiTRex** [comment]
**Note:** Fully stabilized today in Rust 1.50 in [`HashMap`](https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#method.or_insert_with_key) and in [`BTreeMap`](https://doc.rust-lang.org/std/collections/btree_map/enum.Entry.html#method.or_insert_with_key).
