### ISSUE TITLE
Tracking Issue for `destructuring_assignment`

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#71126]
This is a tracking issue for the RFC "Destructuring assignment" (https://github.com/rust-lang/rfcs/pull/2909).
The feature gate for the issue is `#![feature(destructuring_assignment)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Open a pull request: https://github.com/rust-lang/rust/pull/71156
	- [x] Tuples (https://github.com/rust-lang/rust/pull/78748)
    - [x] Structs and slices (https://github.com/rust-lang/rust/pull/78836)
    - [x] `_` expressions (https://github.com/rust-lang/rust/pull/79016)
- [x] Open an RFC: https://github.com/rust-lang/rfcs/pull/2909.
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [x] Stabilization PR (https://github.com/rust-lang/rust/pull/90521)

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

The initial implementation was carried out in three steps by @fanzier (split out from an initial implementation, https://github.com/rust-lang/rust/pull/71156):
- Implementing destructuring support for tuples: https://github.com/rust-lang/rust/pull/78748
- Implementing destructuring support for structs and slices: https://github.com/rust-lang/rust/pull/78836
- Implementing destructuring support for `_` expressions: https://github.com/rust-lang/rust/pull/79016

**Comment by varkor** [comment]
We've opened an RFC for destructuring assignment: https://github.com/rust-lang/rfcs/pull/2909.

**Comment by varkor** [comment]
Now that #78748, #78836, and #79016 have been merged, destructuring assignment is now implemented. Thanks to @fanzier for their hard work implementing this feature!

**Comment by bstrie** [comment]
I got kind of a weird error message recently that probably isn't too concerning, but maybe someone more familiar with the implementation of the `_` desugaring might have more insight.

The following extremely weird program:
```rust
fn main() {
    let y = Some(42);
    if y < Some(_) {}
}
```
Errors with:
```
error[E0658]: destructuring assignments are unstable
 --> src/main.rs:3:17
  |
3 |     if y < Some(_) {}
  |                 ^
  |
  = note: see issue #71126 <https://github.com/rust-lang/rust/issues/71126> for more information
  = help: add `#![feature(destructuring_assignment)]` to the crate attributes to enable

error: in expressions, `_` can only be used on the left-hand side of an assignment
 --> src/main.rs:3:17
  |
3 |     if y < Some(_) {}
  |                 ^ `_` not allowed here

error: aborting due to 2 previous errors
```
I'm wondering whether it's considered a problem that the compiler appears to consider `Some(_)` to be part of a destructuring assignment. Obviously even if this feature were stabilized this program would still error out, but I found it surprising.

**Comment by fanzier** [comment]
@bstrie Thanks for reporting this. The error message is indeed a bit misleading.

> I'm wondering whether it's considered a problem that the compiler appears to consider Some(_) to be part of a destructuring assignment.

In fact, the compiler does not consider this `_` to be part of a destructuring assignment. However, the *feature* `destructuring assignments` allows `_` to occur in more places than before (namely the left-hand side of an assignment). This necessitated a parser change: we allow `_` syntactically anywhere in an expression and only check later on that it only occurs on the left-hand side of an assignment. That parser change is feature-gated on `destructuring assignments`. If the `_` indeed occurs on the LHS of an assignment, the error message is correct because there it is only allowed if the destructuring assignments feature is enabled. Otherwise, the error message is misleading because `_` is illegal in all other expressions and that has nothing to do with destructuring assignments.

I didn't think this was a big problem because as soon as destructuring assignments are stabilized, you'll just get the second error message (`_` can only be used on the left-hand side of an assignment), which is correct. I'm not sure what the best fix for this would be. Do you think it is important to fix while the feature is unstable?

**Comment by scottmcm** [comment]
I think this is ok -- the error it's giving about `_` is arguably better than the [older one](https://rust.godbolt.org/z/GK5vdb):
```
error: expected expression, found reserved identifier `_`
 --> <source>:3:17
  |
3 |     if y < Some(_) {}
  |                 ^ expected expression
```

That said, it might be nice to tune the error based on whether there's a `=` nearby -- it could be nice to talk about patterns *and* destructuring assignments as places for `_`s.

**Comment by bstrie** [comment]
> Do you think it is important to fix while the feature is unstable?

No, I was just surprised and wanted to make sure this wasn't indicative of some deeper bug. :) Ship it!

**Comment by doivosevic** [comment]
Hey everyone. I'm relatively new so I might be missing something, but I can't see what is the roadmap for this feature. Is this expected to release in the next version of Rust?

**Comment by bstrie** [comment]
The next step is for someone on the lang team to propose a final comment period, after which the feature can be stabilized. I'll bring it up with the lang team on Zulip.

**Comment by joshtriplett** [comment]
@bstrie This needs a stabilization report.

**Comment by curldivergence** [comment]
Hello @bstrie, are there any news on the stabilization, by any chance? :)

**Comment by bstrie** [comment]
@curldivergence joshtriplett's prior comment is still accurate. All this needs is for someone to write up a stabilization report, after which this issue can be nominated for lang team discussion, at which point they may then decide to proceed with stabilization.

**Comment by starwing** [comment]
@bstrie So is there any further plan that someone may write up a stabilization report?

**Comment by jhpratt** [comment]
@starwing Anyone is able to write a stabilization report.

**Comment by varkor** [comment]
To clarify to anyone who's not familiar with Rust's stabilisation process, if you have some time and would like to see this feature stabilised, you can write a stabilisation report for this feature (there's a [guide here](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html)). Unfortunately, I don't have time to do so right now, though I don't think it should take too long: the feature is relatively simple and hasn't encountered any issues since implementation. After that, we can put the feature on to a FCP, after which the feature will be stabilised.

(If no-one does so, I will get around to it at some point, but it may be a little while.)

**Comment by rami3l** [comment]
# Request for Stabilization

## Summary

The following 3 features will be stabilized:

[Destructuring assignment for tuples](https://github.com/rust-lang/rust/pull/78748):
This change allows destructuring the left hand side (LHS) of an assignment if it's a (possibly nested) tuple.

```rust
(a,b) = (1,2);
```
[Destructuring assignment for structs and slices](https://github.com/rust-lang/rust/pull/78836): This change enables similar destructuring assignment for (tuple) structs and slices.

```rust
[a, .., b, c] = [1, 2, 3, 4, 5];
Struct { x, .. } = Struct { x: 1, y: 3 };
```
[Make `_` an expression](https://github.com/rust-lang/rust/pull/79016): This change makes `_` parsed as an expression allowed only on the left-hand side of a destructuring assignment, where it simply discards the value.

```rust
(a, _) = (1, 2);
```

## Tests

You may find test cases in:

[`bad-expr-lhs.rs`](https://github.com/rust-lang/rust/blob/d7539a6af09e5889ed9bcb8b49571b7a59c32e65/src/test/ui/destructuring-assignment/bad-expr-lhs.rs): tests against [invalid LHS of assignment](https://github.com/rust-lang/rfcs/blob/master/text/2909-destructuring-assignment.md#reference-level-explanation).

[`default-match-bindings-forbidden.rs`](https://github.com/rust-lang/rust/blob/d7539a6af09e5889ed9bcb8b49571b7a59c32e65/src/test/ui/destructuring-assignment/default-match-bindings-forbidden.rs): checks that [default match bindings](https://github.com/rust-lang/rfcs/blob/master/text/2005-match-ergonomics.md) are [forbidden in destructuring assignments](https://github.com/rust-lang/rfcs/blob/master/text/2909-destructuring-assignment.md#reference-level-explanation), "as this leads to counterintuitive behaviour since the desugaring is an implementation detail."

[`drop-order.rs`](https://github.com/rust-lang/rust/blob/d7539a6af09e5889ed9bcb8b49571b7a59c32e65/src/test/ui/destructuring-assignment/drop-order.rs): checks that the drop order for destructuring assignment is the same as normal `let` bindings.

[`nested_destructure.rs`](https://github.com/rust-lang/rust/blob/d7539a6af09e5889ed9bcb8b49571b7a59c32e65/src/test/ui/destructuring-assignment/nested_destructure.rs): shows that things work with complex destructuring like `Struct { a: TupleStruct((a, b), c), b: [d] } = Struct { a: TupleStruct((0, 1), 2), b: [3] };`.

[`note-unsupported.rs`](https://github.com/rust-lang/rust/blob/d7539a6af09e5889ed9bcb8b49571b7a59c32e65/src/test/ui/destructuring-assignment/note-unsupported.rs): makes sure that [assignments with `+=` are forbidden](https://github.com/rust-lang/rfcs/blob/master/text/2909-destructuring-assignment.md#compound-destructuring-assignment), as well as [functional record updates](https://github.com/rust-lang/rfcs/blob/master/text/2909-destructuring-assignment.md#underscores-and-ellipses).

[`slice_destructure.rs`](https://github.com/rust-lang/rust/blob/d7539a6af09e5889ed9bcb8b49571b7a59c32e65/src/test/ui/destructuring-assignment/slice_destructure.rs),
[`slice_destructure_fail.rs`](https://github.com/rust-lang/rust/blob/d7539a6af09e5889ed9bcb8b49571b7a59c32e65/src/test/ui/destructuring-assignment/slice_destructure_fail.rs),
[`struct_destructure.rs`](https://github.com/rust-lang/rust/blob/d7539a6af09e5889ed9bcb8b49571b7a59c32e65/src/test/ui/destructuring-assignment/struct_destructure.rs),
[`struct_destructure_fail.rs`](https://github.com/rust-lang/rust/blob/d7539a6af09e5889ed9bcb8b49571b7a59c32e65/src/test/ui/destructuring-assignment/struct_destructure_fail.rs),
[`tuple_destructure.rs`](https://github.com/rust-lang/rust/blob/d7539a6af09e5889ed9bcb8b49571b7a59c32e65/src/test/ui/destructuring-assignment/tuple_destructure.rs) and
[`tuple_destructure_fail.rs`](https://github.com/rust-lang/rust/blob/d7539a6af09e5889ed9bcb8b49571b7a59c32e65/src/test/ui/destructuring-assignment/tuple_destructure_fail.rs): shows that destructuring assignment works with slices, structs and tuples.

[`warn-unused-duplication.rs`](https://github.com/rust-lang/rust/blob/d7539a6af09e5889ed9bcb8b49571b7a59c32e65/src/test/ui/destructuring-assignment/warn-unused-duplication.rs): shows that a warning is emitted during assignments like `(a, a) = (0, 1);`, where a variable is being assigned to twice.

## Unresolved questions

None for the moment.

**Comment by joshtriplett** [comment]
Thank you for the stabilization report, @rami3l!

Shall we stabilize destructuring assignment?

@rfcbot merge

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

I'm excited about this :)

**Comment by varkor** [comment]
Now that the final comment period has ended, anyone can open up a [stabilisation PR](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr). The process is very straightforward, and essentially involves removing the `destructuring_assignment` feature gate wherever it currently appears in the compiler. I'm also not quite sure what the state of documentation is: it may be that pull requests (or at the very least issues) need to be opened on the repositories for the [Rust book](https://github.com/rust-lang/book) and the [reference](https://github.com/rust-lang/reference).

**Comment by jhpratt** [comment]
I'll take a shot at a stabilization PR.

**Comment by jhpratt** [comment]
PR is up: #90521

**Comment by leonardo-m** [comment]
Something related in C# 10:
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/deconstruct
