### ISSUE TITLE
Tracking Issue for raw slice len() method (slice_ptr_len, const_slice_ptr_len)

### ISSUE THREAD

**Issue by neocturne** [rust-lang/rust#71146]
This is a tracking issue for the len() method on raw slice pointers, which allows to get the length of a raw slice pointer when conversion to a slice reference would be UB (because the pointer is null or unaligned).

It covers the feature gates `#![feature(slice_ptr_len)]` and `#![feature(const_slice_ptr_len)]` (for const fn).

## Public API

```rust
impl<T> *mut [T] {
    pub const fn len(self) -> usize;
    pub const fn is_empty(self) -> bool;
}

impl<T> *const [T] {
    pub const fn len(self) -> usize;
    pub const fn is_empty(self) -> bool;
}

impl<T> NonNull<[T]> {
    pub const fn len(self) -> usize; // Already stable
    pub const fn is_empty(self) -> bool;
}
```

## History / Steps

- [x] #71082
- [x] #71940
- [x] #95594
- [x] https://github.com/rust-lang/rust/pull/118231
- [x] https://github.com/rust-lang/rust/pull/122800
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Open questions

* Potential blocker: https://github.com/rust-lang/rust/issues/73987

**Comment by SimonSapin** [comment]
PR https://github.com/rust-lang/rust/pull/71940 adds `NonNull<[T]>::len`, reusing this as its tracking issue.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/issues/73987 is a potential blocker for stabilization of these methods.

**Comment by SimonSapin** [comment]
Is it really? I feel that a DST struct with a slice field is not a common case, and certainly not the only one.

**Comment by RalfJung** [comment]
That issue shows a general problem with methods where `self` is a raw pointer: if a method with the same name as `self` being a reference exists, it is very easy to accidentally call the reference method. Isn't that a problem for stabilizing any of those raw pointer methods?

**Comment by SimonSapin** [comment]
This does look like a footgun, but I think the core of that issue is not at all the `len` methods. Instead it’s that you can’t get a raw pointer to a struct field from a raw pointer to that struct without something like https://github.com/rust-lang/rfcs/pull/2582. The example code in https://github.com/rust-lang/rust/issues/73987 never involved a `*const [u8]` value at all. I’ve commented some more there.

Once you do have a `*const [u8]` value, calling `len` on it is perfectly fine.

**Comment by RalfJung** [comment]
(Responded there. What you describe is buggy behavior, IMO -- the source code didn't involve a `&[u8]` either, the compiler added that, and that is exactly the problem.)

**Comment by wonderconstant** [comment]
Hello everyone. Thank you for working on this feature! I understand that currently #73987 is a blocker for `slice_ptr_len`. As an end-user of this API, is there any feedback I could provide that would help decide on the method signature? FWIW, I've not seen any risky situations in my usage due to its current method signature (I tend to check to which method it resolves to using my IDE in case there are multiple potential matches, so this might be more thorough than the average end-user). In an attempt to spark new ideas, an alternative I see is to turn the method signature `pub const fn len(self) -> usize` into an associated function like `pub const fn len(ptr: Self) -> usize` if this is really blocking, then it would be impossible to get confused (but at the cost of ergonomics). But as an end-user, I would also be satisfied for how the signature is currently available already, I do not find it confusing as it is. I'd like to help out more if I can, please let me know if I can contribute somehow :-) Thank you!

**Comment by wonderconstant** [comment]
A second idea for a suggestion that came to me today. Currently this tracking issues is for all of `<*const T>::len`, `<*mut T>::len` and `NonNull::<T>::len`. If I understand correctly, #73987 is only related to `<*const T>::len` and `<*mut T>::len`, but does not affect `NonNull::<T>::len()`, because creating a reference `&NonNull<T>` through `len()` would merely be a reference to the pointer to `T`, not to the actual `T`. If I'm not mistaken, the internals of `NonNull::<T>::len()` are still allowed to call the non-stabilized pointer methods, even when `NonNull::<T>::len()` would already be stable (I think remember seeing this approach before when browsing through the core library source code). Is there a possibility that `NonNull::<T>::len()` could get stabilized already before the other methods?

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/issues/73987 indeed does not affect `NonNull::len`.

**Comment by mexus** [comment]
So.. is there anything else needs to be done to begin the FCP? :)

**Comment by Pointerbender** [comment]
Hi everyone. Earlier in this discussion it came up that there is no blocker for the stabilization of `NonNull::len` (the same goes for its `const` version). I'm interested in leading an effort to split the stabilization for `NonNull::len` into a separate Github issue to help move this part along. But maybe before I start with that, may I ask for the blessing of @NeoRaider or @SimonSapin since they already worked on `(const_)slice_ptr_len`? :) Also, may I ask for some pointers on how to smoothly go through this process (documentation, etc.)? This would be the first time for me going through a stabilization process :) I found [this documentation](https://std-dev-guide.rust-lang.org/) already, it's still a work-in-progress judging by the number of "stubs" in there, but it has some handy tips already. Would I need anything else besides this guide? Thank you!

**Comment by josephlr** [comment]
I would also like to see these methods on `NonNull`, mostly so https://github.com/rust-osdev/volatile could use them in its [new implementation](https://github.com/rust-osdev/volatile/pull/22).

As https://github.com/rust-lang/rust/issues/73987 is still pending, could we open a separate stabilization PR just for the `NonNull` methods?

**Comment by RalfJung** [comment]
Technically that function is wrong in case `ptr` points to previously allocated but now deallocated memory, or an out-of-bounds pointer created e.g. with `wrapping_offset`. (See the notes about size zero in the [ptr validity docs](https://doc.rust-lang.org/nightly/std/ptr/index.html).)

**Comment by Pointerbender** [comment]
> Technically that function is wrong in case `ptr` points to previously allocated but now deallocated memory, or an out-of-bounds pointer created e.g. with `wrapping_offset`. (See the notes about size zero in the [ptr validity docs](https://doc.rust-lang.org/nightly/std/ptr/index.html).)

Thanks for catching that @RalfJung! :smiley: I updated the code snippet to `unsafe` in case anyone stumbles upon it in the future.

Thinking about safe alternatives, these 2 safety requirements can be satisfied for all situations if the caller has an `&UnsafeCell<[T]>` instead of a `NonNull<[T]>`. This won't work in all situations though, `UnsafeCell` and `Nonull` most notably differ in the following properties:

* `NonNull<[T]>` is covariant in `T`, it may point to uninitialized memory and it does not give any semantic guarantees about whether the pointee has `SharedReadOnly` or `SharedReadWrite` access under Stacked Borrows.
* `&UnsafeCell<[T]>` is invariant in `T`, it will never point to uninitialized memory (because this would be undefined behavior) and the pointee has a `SharedReadWrite` access tag on the stack under Stacked Borrows.
* It's not safe to "blindly" convert a `NonNull<[T]>` to an `&UnsafeCell<[T]>` due the above differences, and that would also require the pointee to be well-aligned and the slice length can be at most `isize::MAX` bytes.

Keeping these gotchas in mind, this can be a safe wrapper when there is access to an `&UnsafeCell<[T]>`:

```rust
pub fn ptr_len<T>(ptr: &UnsafeCell<[T]>) -> usize {
   unsafe { (&*(ptr.get() as *const [()])).len() }
}
```

That said, while writing this down I realize there are a lot of footguns when trying to get the length of a slice, so stabilizing `NonNull::len` would definitely still have merit. My [earlier offer](https://github.com/rust-lang/rust/issues/71146#issuecomment-974818985) to help push it across the finish line still stands if the original contributors are still reading along :)

**Comment by RalfJung** [comment]
Yeah, purely from a perspective of #73987, stabilizing NonNull::len seems fine. It would encourage some odd coding patterns (turning a raw slice ptr into a NonNull to get its length, unnecessarily asserting non-nullness) -- but arguably the coding patterns that were just suggested in this thread are worse.^^

@Pointerbender you don't need the blessing of the original authors to push a feature over the finish line, you only need the bless of @rust-lang/libs-api. :)

**Comment by Pointerbender** [comment]
> @Pointerbender you don't need the blessing of the original authors to push a feature over the finish line, you only need the blessing of https://github.com/orgs/rust-lang/teams/libs-api. :) And that will be obtained in the PR via the usual FCP process.

Oh! That is very good to know, thank you @RalfJung :) I'm gonna find out how to get an FCP started for a partial stabilization (just for `NonNull<[T]>::len`) and then report back here ([zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/First.20time.20going.20through.20FCP/near/273875556)).

**Comment by afetisov** [comment]
My understanding is that this issue is blocked purely on the autodereference issues in #73987. But deref coercions only apply to methods, not functions. What if `len` is initially turned into an associated function or a free function?

```rust
impl<T> *const [T] {
    fn len(ptr: *const [T]) -> usize { /* ... */ }
}
```

If a solution to the autoref issue is ever invented, I believe this can be turned into a method in a backwards-compatible way.

I'll just note that the absence of a way to get the length of `*const [T]` make raw slices essentially unusable. This is doubly confusing since the corresponding `from_raw_parts` method was stabilized a long time ago, and the corresponding methods on safe slices are stable even longer.

While an associated function isn't as pretty, natural and ergonomic as a method, at least it doesn't block actually working with raw slices.

**Comment by yaahc** [comment]
I'm sorry if this has already been addressed because I haven't taken the time to go back and review the full history, but as anyone already discussed updating the impl to internally use the [`ptr::metadata`](https://doc.rust-lang.org/stable/std/ptr/fn.metadata.html) API? I know @SimonSapin was involved in the earlier review stages for this API and noted how they're related, but I didn't find any further references to the metadata apis in the subsequent discussion (that I skimmed).

**Comment by afetisov** [comment]
@yaahc The `<*(const/mut) [T]>::len` function already internally delegates to `ptr::metadata`.

**Comment by RalfJung** [comment]
> I believe this can be turned into a method in a backwards-compatible way.

Can someone from the libs-api team confirm that this is the case?

**Comment by RalfJung** [comment]
I realized the implicit-raw-ptr-to-ref-coercion [already happens on stable](https://github.com/rust-lang/rust/issues/99437). So doing this for `ptr.len` doesn't really add a fundamentally new problem, it just makes it possible for an existing problem to show up in more situations. At the same time, having these methods is needed to work around the need for a reference in the first place.

So, I think we need some way to avoid creating a reference to a place constructed from a raw pointer (and to lint against the existing cases where that happens). But I am no longer as certain that this needs to block these raw ptr methods, in particular since acting on that lint will require some of these raw ptr methods (such as https://github.com/rust-lang/rust/issues/74265).

**Comment by mattfbacon** [comment]
Is it possible to extend this for `*const/mut str`?

**Comment by Amanieu** [comment]
> Is it possible to extend this for `*const/mut str`?

Sure, I don't see any reason why not.

**Comment by RalfJung** [comment]
I think this has been sitting around long enough, clearly a fix for https://github.com/rust-lang/rust/issues/73987 will not magically materialize. And even with https://github.com/rust-lang/rust/issues/73987 unresolved, as long as we don't let users write arbitrary-self methods on raw pointers, we can still change the autoref behavior later to use raw pointers when that is enough. So while these methods might have a footgun, they are still better than the status quo.

So I propose we move towards stabilizing of this, and of https://github.com/rust-lang/rust/issues/71146. (Except for `is_empty`; having that only on mutable raw slices makes little sense.)

@rust-lang/types are you aware of anything that would block stabilizing a function that uses a raw pointer self type? (There might already be stable functions that do that, I am not sure.)

**Comment by lcnr** [comment]
talked about this in the t-types planning meeting: https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-12-04.20planning.20meeting/near/405846203

summary:
- we believe that as long as the rest of the signature matches the existing slice methods, it will be backwards compatible to change method selection to use the raw-ptr methods instead
- we/I believe that changing method selection is valuable, but not likely to be tackled by an existing t-types members in the near future due to lack of capacity.

stabilizing this seems therefore acceptable from a t-types perspective. Whether the implicit ref in `(*raw_pointer).field.len()` is acceptable is left to t-libs-api

**Comment by RalfJung** [comment]
@lcnr are there any concerns about raw pointer `self` receivers themselves? These would be the first stable functions to use them, I think.

**Comment by lcnr** [comment]
I think apart from us not having an "auto-ref" step for raw pointers, there are no concerns from me as long as adding such a step remains backwards compatible. I believe this to be the case as long as the rest of the signatures match. 
> - we believe that as long as the rest of the signature matches the existing slice methods, it will be backwards compatible to change method selection to use the raw-ptr methods instead

**Comment by zachs18** [comment]
Note that since 1.75.0, with the stabilization of `wrapping_byte_add`, the functionality of `<*const/mut [T]>::len` can be achieved on stable (even for null slice pointers) using `wrapping_byte_add` and `NonNull::len`, e.g.

```rs
use std::ptr::NonNull;
fn slice_ptr_len<T>(ptr: *const [T]) -> usize {
  let ptr = ptr.cast_mut();
  if let Some(ptr) = NonNull::new(ptr) {
    ptr.len()
  } else {
    // We know ptr is null, so we know ptr.wrapping_byte_add(1) is not null.
    NonNull::new(ptr.wrapping_byte_add(1)).unwrap().len()
  }
}
```

**Comment by RalfJung** [comment]
@rust-lang/libs-api What is your take on stabilizing these functions? I did a little test balloon stabilizing a function with raw ptr receiver in https://github.com/rust-lang/rust/pull/118806 and that did not go through. However the situation here is a bit different (maybe) since these work on a primitive type. Also #118806 just made a function more convenient to call, this one here is about functionality that's fundamentally not available on stable today. I do think it is high time we provide a way to get the length of a raw slice. So, I wonder which option you'd prefer:

- stabilizing these as-is
- adding `ptr::slice_len(ptr: *const [T])`, i.e., exposing this as a function rather than a method (name to be bikeshed of course)

**Comment by WaffleLapkin** [comment]
@RalfJung the second pr in your message is the same as the first, did you mean to mention something else?

**Comment by RalfJung** [comment]
No I meant the same PR in both cases. There's two differences between that rejected PR and stabilizing raw slice len:
- raw slice len works on a primitive type
- raw slice len extends what can be done on stable (without awkward hacks like the one above)

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting and we are happy to stabilize these as-is.

@rfcbot fcp merge

**Comment by WaffleLapkin** [comment]
Is there a particular reason why there is no `NonNull::<[T]>::is_empty`?

**Comment by Amanieu** [comment]
> Is there a particular reason why there is no `NonNull::<[T]>::is_empty`?

That's a good point. It should be added as well for consistency with raw pointers.

**Comment by zachs18** [comment]
As per https://github.com/rust-lang/rust/pull/122800#issuecomment-2013210212, #122800 currently uses this issue as the tracking issue for `NonNull::<[T]>::is_empty`

**Comment by RalfJung** [comment]
Adding something to FCP after the boxes were already checked is rather unconventional (I expected a new tracking issue for a new function) -- @rust-lang/libs-api I hope you're okay with it (a team member proposed to do this after all).

**Comment by Amanieu** [comment]
I've added `NonNull::is_empty` to the tracking issue.

I'll restart the FCP to make sure everyone is aware of the change.

@rfcbot fcp cancel

**Comment by Amanieu** [comment]
@rfcbot fcp merge
