### ISSUE TITLE
Tracking Issue for making ptr offset methods "const fn"

### ISSUE THREAD

**Issue by josephlr** [rust-lang/rust#71499]
The feature gate for this is `#![feature(const_ptr_offset)]`. Miri has been able to handle this for some time. This feature allows code like:
```rust
static FOO: u8 = 42;
static PTR1: *const u8 = &FOO as *const u8;
static PTR2: *const u8 = PTR1.wrapping_offset(1);
```

- The following intrinsic functions will be made `const fn`:
  - [`intrinsics::offset`](https://doc.rust-lang.org/stable/core/intrinsics/fn.offset.html)
  - [`intrinsics::arith_offset`](https://doc.rust-lang.org/stable/core/intrinsics/fn.arith_offset.html)
- The allows the following `*const`/`*mut` methods to be `const fn`:
  - [`offset`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.offset)
  - [`wrapping_offset`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.wrapping_offset)
  - [`add`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.add)/[`sub`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.sub)
  - [`wrapping_add`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.wrapping_add)/[`wrapping_sub`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.wrapping_sub)

- The following methods are **not** part of this issue:
  - `align_offset`: See #62420
  - `offset_from`: Tracked as part of #41079 and https://github.com/rust-lang/rust/issues/92980
  - `wrapping_offset_from`: Not possible across different allocations
  - Any read/write methods: Tracked in #51911

### Steps (based on #69821)
- [x] Implemented in #71500
- [ ] Check if any other `core`/`alloc`/`std` functions should be made const along with this.
- [x] Remove[ miri's implementations for `offset` and `arith_offset`](https://github.com/rust-lang/miri/blob/52f5d202bdcfe8986f0615845f8d1647ab8a2c6a/src/shims/intrinsics.rs#L96-L112)
- [ ] Final commenting period (FCP): https://github.com/rust-lang/rust/issues/71499#issuecomment-1062913168
- [ ] Stabilization PR

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr

### Unresolved Questions

-  How should `offset == 0` be handled?
   - As implemented, we allow offsets of 0 for all pointers (including dangling pointers) except for null pointers.
   - Should we allow offsets of 0 for null pointers?
   - The documentation is a bit unclear on this, see: #65108 and [@RalfJung's comment](https://github.com/rust-lang/rust/issues/65108#issuecomment-540076878)

CC: @RalfJung @oli-obk @rust-lang/wg-const-eval

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval (unfortunately GH lets org members ping teams :/ )

Note that Miri already has [implementations of the relevant intrinsics](https://github.com/rust-lang/miri/blob/master/src/shims/intrinsics.rs#L96-L112) but they need to be moved to rustc.

**Comment by aodhneine** [comment]
Hi, what's the progress on this issue?

**Comment by oli-obk** [comment]
> for `offset`/`add`/`sub`, we cannot actually check during const-eval if the operation overflows, because that depends on the actual integer address the allocation starts at.

As decided in the unsafe const RFC, we only need to do a best effort UB check.

I reviewed the methods in question and believe we can stabilize all of them. The only user visible const/runtime differences occur in the presence of UB.

**Comment by RalfJung** [comment]
Indeed I think there is no reason to wait longer, we can stabilize this. Does someone want to prepare a stabilization PR?

**Comment by m-ou-se** [comment]
@rfcbot merge
