### ISSUE TITLE
Tracking Issue for Box::into_boxed_slice

### ISSUE THREAD

**Issue by elichai** [rust-lang/rust#71582]
This is a tracking issue for `Box::into_boxed_slice`.
The feature gate for the issue is `#![feature(FFF)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the feature -- https://github.com/rust-lang/rust/pull/71421
- [x] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

XXX --- list all the "unresolved questions" found in the RFC to ensure they are
not forgotten

**Comment by programmerjake** [comment]
seems to me that it would be better to instead have the function convert from `Box<T>` to `Box<[T; 1]>` since that's the minimal unsafe part, allowing the function to be more general, and since safe code can easily coerce the result to `Box<[T]>` if needed.

**Comment by zachs18** [comment]
Making this a `From` impl would conflict[^1] with existing [`From<Box<Local>> for Box<[Local]>`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b03b12a141f8d284fce04b7218f748ad) impls, since `Box` is `#[fundamental]` and thus treated like its pointee for coherence purposes in most cases. (Similarly, [`std::{array,slice}::from_{ref,mut}` becoming `From` impls](https://github.com/rust-lang/rust/issues/77101#issuecomment-2241468475) would be breaking.)
I don't think adding `From<Rc<T>> for Rc<[T]>` or `for Rc<[T; 1]>` (or `Arc`) would have the same issue, since `Rc`/`Arc` are not `#[fundamental]`.

Also, we could add `alloc::array::from_boxed(_: Box<T>) -> Box<[T; 1]>` and `alloc::slice::from_boxed(_: Box<T>) -> Box<[T]>` analogous to `from_ref`/`from_mut` instead of or in addition to having associated fn(s) on `Box`.

[^1]: I suppose a crater run could be done to see if such implementations are common, but I think this would count under the "adding a fundamental trait impl is a major change" section of the [API Evolution RFC](https://rust-lang.github.io/rfcs/1105-api-evolution.html#trait-implementations) and might not be allowed regardless.
