### ISSUE TITLE
Tracking Issue for feature arc_mutate_strong_count

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#71983]
The feature gate for the issue is `#![feature(arc_mutate_strong_count)]`.

### Steps

- [x] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [x] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- [ ] Can we improve the docs phrasing on `Arc::decr_strong_count`?

### Implementation history

- Initial PR in https://github.com/rust-lang/rust/pull/70733
- Stabilization PR in https://github.com/rust-lang/rust/pull/79285

**Comment by vorner** [comment]
Hello

Would it make sense to also include similar methods for Rc? And possibly similar ones to both Weaks? It would be in part for the sake of completeness, but I do some manipulation like this in the arc-swap crate and if this would become the „official“ way, it would be nice to be supported on all the related types.

**Comment by yoshuawuyts** [comment]
I think that's a great idea, and we should file follow-up issues to implement those.
