### ISSUE TITLE
Tracking Issue for constify-ing non-trait `Duration` methods

### ISSUE THREAD

**Issue by marmeladema** [rust-lang/rust#72440]
This is a tracking issue for constify-ing non-trait `Duration` methods

The feature gates for the issueis `#![feature(duration_consts_float)]`. The methods covered by that are:

* `Duration::as_secs_f64`
* `Duration::as_secs_f32`
* `Duration::as_millis_f64`
* `Duration::as_millis_f32`
* `Duration::div_duration_f64`
* `Duration::div_duration_f32`

### Steps

- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

XXX --- list all the "unresolved questions" found in the RFC to ensure they are
not forgotten

### Implementation history

- [x] Constify most non-trait `Duration` methods as described: https://github.com/rust-lang/rust/pull/72481
- [x] Make all methods of Duration unstably const: https://github.com/rust-lang/rust/pull/76335
- [x] Partially stabilize duration_consts_2: https://github.com/rust-lang/rust/pull/89542

**Comment by marmeladema** [comment]
I also would like to add a `Duration::MAX` associated const. Should it be part of the same tracking issue?

**Comment by Mark-Simulacrum** [comment]
I don't think so -- adding a new constant seems pretty orthogonal to me.

**Comment by marmeladema** [comment]
> I don't think so -- adding a new constant seems pretty orthogonal to me.

It's orthogonal but depends on `Duration::new` being const so I thought having a tracking issue just for one associated const might be overkill.

**Comment by RalfJung** [comment]
> Because they end up calling f32|64::is_finite which ultimately call mem::transmute which is not const.

FWIW, https://github.com/rust-lang/rust/pull/72449 makes many other safe `transmute` wrappers const, but not `is_finite` it seems. But that should be possible, too.

**Comment by RalfJung** [comment]
All right, https://github.com/rust-lang/rust/pull/72449 will make `is_finite` const as well, so you should be able to use that.

**Comment by marmeladema** [comment]
Great! I'll wait for #72449 to land and update my PR accordingly.

**Comment by RalfJung** [comment]
The tracking issue should also notice that stabilizing *any* of the `f32`/`f64` methods is blocked on stabilizing floating point in const at all (https://github.com/rust-lang/rust/issues/57241).

**Comment by jhpratt** [comment]
PR stabilizing non-float methods is up: #89542

**Comment by MoSal** [comment]
Didn't see this mentioned anywhere with a quick search, but `Duration::from_secs_f64` is not `const` anymore?

Is `#![feature(duration_consts_float)]` no-op now?

**Comment by MoSal** [comment]
> Didn't see this mentioned anywhere with a quick search, but `Duration::from_secs_f64` is not `const` anymore?
> 
> Is `#![feature(duration_consts_float)]` no-op now?

Looking at this closer today, the `from_*` and `try_from_*` float functions were no longer
`const` after #110393. That's because the [`try_from_secs` macro](https://github.com/rust-lang/rust/blob/339786e01203f0ea00601b605899429c2b4bdf3e/library/core/src/time.rs#L1262-L1340) makes use of `$int_ty::from($expr)`, the trait impls of which are no longer `const`.

The `from` calls can be replaced with `($expr as $int_ty)` if it is desired to restore the `const` impls.

**Comment by RalfJung** [comment]
@rust-lang/libs-api  With https://github.com/rust-lang/rust/issues/57241 being stable now, I think we can proceed with stabilizing these as well? :)

**Comment by dtolnay** [comment]
@rfcbot fcp merge

`const` for these 6 already-stable Duration methods, unblocked by https://github.com/rust-lang/rust/pull/128596 in Rust 1.82 (current beta).

- https://doc.rust-lang.org/nightly/core/time/struct.Duration.html#method.as_secs_f64
- https://doc.rust-lang.org/nightly/core/time/struct.Duration.html#method.as_secs_f32
- https://doc.rust-lang.org/nightly/core/time/struct.Duration.html#method.as_millis_f64
- https://doc.rust-lang.org/nightly/core/time/struct.Duration.html#method.as_millis_f32
- https://doc.rust-lang.org/nightly/core/time/struct.Duration.html#method.div_duration_f64
- https://doc.rust-lang.org/nightly/core/time/struct.Duration.html#method.div_duration_f32
