### ISSUE TITLE
Tracking Issue for `poll_ready`

### ISSUE THREAD

**Issue by djc** [rust-lang/rust#72992]
This is a tracking issue for `Poll::ready()` (PR #72994).
The feature gate for the issue is `#![feature(poll_ready)]`.

### Steps

- [x] Implement the API
- [x] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide]) [not applicable?]
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

Rationale: I have this code in Quinn:

```rust
.filter_map(|(i, x)| match Pin::new(x.as_mut().unwrap()).poll(cx) {
    Poll::Ready(y) => {
        *x = None;
        Some((i, y))
    }
    Poll::Pending => None,
})
```

And this would seem quite a bit nicer:

```rust
.filter_map(|(i, x)| {
    Pin::new(x.as_mut().unwrap()).poll(cx).ready().map(|y| {
        *x = None;
        (i, y)
    })
})
```

One potential downside is that this adds one more `ready()` after `futures::ready!()` and `futures::future::ready()`. As it is a method (compared to a free function or a macro), it seems it's still clearly distinct, but could be confusing. It otherwise seems to be the idiomatic naming choice though.

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

**Comment by KodrAus** [comment]
The PR that implemented this feature has been closed (just from inactivity). Since there isn't a feature to track here I'll go ahead and close this issue, but if there's a follow-up to #72994 that comes back then let's re-open this!
