### ISSUE TITLE
Tracking Issue for stabilizing panic=abort support in libtest

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#73228]
This is a tracking issue for stable panic=abort support in libtest. This is currently enabled by passing `-Z panic-abort-tests` while compiling a test. It also includes a currently unstable option in test binaries, `--force-run-in-process`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation. They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.

A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature. Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the feature
- [ ] Resolve #68936: Tests in panic=abort can hang if test spawns a subprocess
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

Does this need an RFC? MCP?

### Implementation history

- panic=abort support in libtest #64158
- Don't propagate __RUST_TEST_INVOKE to subprocess #68301
- Respect --nocapture in panic=abort test mode #68909
- Add --force-run-in-process unstable option to libtest #66415

**Comment by tmandry** [comment]
whoops.. this duplicates #67650
