### ISSUE TITLE
Tracking Issue for `slice_strip` feature

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#73413]
The feature gate for the issue is `#![feature(slice_strip)]`.

This feature adds two new methods to `[T]`:

```rust
impl<T> [T] {
    /// Returns a subslice with the prefix removed.
    pub fn strip_prefix(&self, prefix: &[T]) -> Option<&[T]> where T: PartialEq;
    /// Returns a subslice with the suffix removed.
    pub fn strip_suffix(&self, suffix: &[T]) -> Option<&[T]> where T: PartialEq;
}
```

This is an analogy feature like [`str::strip_{prefix,suffix}`](https://doc.rust-lang.org/nightly/std/primitive.str.html#method.strip_prefix) but has the same signature of slice's `{starts,ends}_with`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the feature (cc @rust-lang/libs)
- [x] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [x] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

None

### Implementation history

* Implemented in #73414
* Assembly for `[u8]`: https://rust.godbolt.org/z/iMcqf-

**Comment by ijackson** [comment]
Hi.  I accidentally used one of these functions, I think because I was reading the docs for `str` :-).  So, I conclude that they're useful.

I'd like to see them stabilised.  Since the docs tickbox was unticked I looked at the docs, and I have I made an MR for some slight docs wording improvements: https://github.com/rust-lang/rust/pull/75078

I think this is probably ready for stabilisation.

@lzutao Thanks for your contribution here.  Do you intend to do the stabilisation report etc.?

**Comment by lzutao** [comment]
I think it is a bit soon to stabilize this feature. It is about one month after the feature is merged and appeared on nightly.
But yeah, you could send a PR to propose stabilize this feature, but it should include real usecases?

**Comment by Rua** [comment]
I'm also interested!

**Comment by lzutao** [comment]
Could you give some example code show how do you do that with `slice::strip_` methods?
Because if you are running `strip_*` in a loop, I think it is kinda not cool, it is might be better to
introduce a new method for that functionality.

**Comment by Rua** [comment]
You're right, what I'm looking for is a slice equivalent to `str::trim_end_matches`. Which would also be welcome, but out of scope here!

**Comment by lzutao** [comment]
I just don't know if we want the API as it is, because we could bound the prefix/suffix arguments by Pattern APIs
like `str`. @withoutboats and some folks was talking about fixing Pattern API for slices.

Anyway, If you want to stabilize this API, you could just send a PR and ping T-libs for their decisions.

**Comment by ijackson** [comment]
lzutao writes ("Re: [rust-lang/rust] Tracking Issue for `slice_strip` feature (#73413)"):
> I just don't know if we want the API as it is, because we could bound the
> prefix/suffix arguments by Pattern APIs
> like str. @withoutboats and some folks was talking about fixing Pattern API for
> slices.

AIUI providing these functions now, as taking slices for the patterns,
does not preclude generalising things later with a slice Pattern API.
The current unstable strip_* functions match the signatures of the
starts_with and ends_with, as discussed in #73414.

Ie, AIUI subsequently introducing such a alice Pattern API would not
be a breaking change.  If I'm wrong about that then stabilising
starts_with and ends_with in their current form seems like it was a
mistake ?

> Anyway, If you want to stabilize this API, you could just send a PR and ping
> T-libs for their decisions.

The stabilisation checklist says to look at the docs.  I have an
outstanding MR #75078 to improve the docs.  Unfortunately that seems
to have become stuck waiting for review.

Would you be able to look into that ?

Thanks,
Ian.

-- 
Ian Jackson <ijackson@chiark.greenend.org.uk>   These opinions are my own.  

Pronouns: they/he.  If I emailed you from @fyvzl.net or @evade.org.uk,
that is a private address which bypasses my fierce spamfilter.

**Comment by lzutao** [comment]
> The current unstable strip_* functions match the signatures of the starts_with and ends_with, as discussed in #73414.

Ah yeah, I forgot about this, thanks for pointing it out.

> Ie, AIUI subsequently introducing such a alice Pattern API would not be a breaking change. If I'm wrong about that then stabilising starts_with and ends_with in their current form seems like it was a mistake ?

I'm not really sure, T-libs member should have more experiments to answer this question.

> Would you be able to look into that ?

My English is not great, so I pinged Joshua for review your PR.

> The stabilisation checklist says to look at the docs

You could always send a PR for stabilization, documentation improvements is not a blocker for stabilizing it.

**Comment by ijackson** [comment]
> My English is not great, so I pinged Joshua for review your [docs] PR.

Thanks.

> You could always send a PR for stabilization, documentation
> improvements is not a blocker for stabilizing it.

Oh, I didn't realise that.  I will do a stabilisation PR then.

Thanks,
Ian.

-- 
Ian Jackson <ijackson@chiark.greenend.org.uk>   These opinions are my own.  

Pronouns: they/he.  If I emailed you from @fyvzl.net or @evade.org.uk,
that is a private address which bypasses my fierce spamfilter.

**Comment by ijackson** [comment]
I think this issue wants to be set to merged or something now?  The docs were dealt with in #75078 and the stabilisation was in #77853, both merged now.  I'm not sure I can do that myself...

**Comment by lzutao** [comment]
Closed by #77853 .
