### ISSUE TITLE
Support for arm64e (ARMv8.3+) targets

### ISSUE THREAD

**Issue by luxxxxy** [rust-lang/rust#73628]
Currently, a blocker in a project of mine - [Crabapple](https://github.com/Crabapple-iOS/Crabapple) - is the lack of native arm64e support in Rust.

The `aarch64-apple-ios` target only emits arm64 (ARMv8) code, which will not work within an arm64e (ARMv8.3+) environment due to it's lack of awareness of Pointer Authentication, leading to segfaults when trying to access a signed pointer.

It is currently possible to work around this, by using a backtrace=false rustc, compiling with `--emit=llvm-ir -Clto`, and running the resulting IR through an arm64e-aware LLVM (such as [apple/llvm-project](https://github.com/apple/llvm-project)). Pointer authentication may be worked around by [linking to an FFI function that runs ptrauth_strip](https://github.com/Crabapple-iOS/librustsupport/blob/master/library.m#L19-L22).

This would require LLVM changes if done, and quite possibly a new target (`arm64e-apple-ios`, `aarch64-apple-ios-armv83`, etc)

**Comment by luxxxxy** [comment]
In addition, arm64e support important due to the [upcoming Mac desktops running Bionic processors (such as an A12Z)](https://youtu.be/GEZhD3J89ZE?t=5837).

**Comment by luxxxxy** [comment]
[Upstream LLVM supports armv8.3](https://lists.llvm.org/pipermail/llvm-dev/2019-October/136091.html), and most likely the Rust LLVM as well.

**Comment by jonas-schievink** [comment]
> [Upstream LLVM supports armv8.3](https://lists.llvm.org/pipermail/llvm-dev/2019-October/136091.html), and most likely the Rust LLVM as well.

Weren't you working on building a custom LLVM since upstream *doesn't* support this yet? The link just goes to an RFC thread on the mailing list with no replies.

**Comment by luxxxxy** [comment]
@jonas-schievink I was poorly attempting to jury-rig apple/llvm-project onto rustc. In short, I got arm64e and armv8.3 mixed up.

A quick grep and dig through rust-project/llvm reveals that it has the code for ARMv8.3 and Pointer Authentication support.

**Comment by luxxxxy** [comment]
ARMv8.5 support would also be good, considering that there's a high likelihood than ARM Macs will run on ARMv8.5.

**Comment by luxxxxy** [comment]
[It is worth noting that the Rust LLVM branch has support for PAC (ARMv8.3) and BTI (ARMv8.5)](https://github.com/rust-lang/llvm-project/blob/rustc/10.0-2020-05-05/lld/ELF/Arch/AArch64.cpp#L537-L570)

**Comment by glandium** [comment]
Note that the macOS 11 SDK has both arm64-macos and arm64e-macos targets, although the arm64 variants don't have an uuid in the system library TBD files.

**Comment by glandium** [comment]
> [Upstream LLVM supports armv8.3](https://lists.llvm.org/pipermail/llvm-dev/2019-October/136091.html), and most likely the Rust LLVM as well.

That's not merged in LLVM upstream.

**Comment by luxxxxy** [comment]
@glandium my bad.

**Comment by emoon** [comment]
I'm interested in this as well because of Apple Silicon (i.e arm64 on macOS)

Going forward it will be mandated by Apple that executable released (at least for the App Store) supports both `x86_64` and `amd64` target. On macOS there are "fat binary" support which makes it possible to have both targets in the same exe/obj/dylib etc file. Clang for example supports that you can have `-arch x86_64` and `-arch amd64` on the command line to generate the correct binary for this to work. Then the OS will load the correct version depending on the OS version running.

There is a command line tool called `lipo` that can be used to combine two different compiles, but this (according to Apple) should only be used as a work-around and I think for Rust it would be better to support building for both targets at the same time.

**Comment by repi** [comment]
We (Embark) are interested in it as well, should we track having a Darwin Mac on ARM target in this issue or file an additional one specifically for it (with some overlap with this)?

**Comment by luxxxxy** [comment]
We'd need someone with a Developer Transition Kit to truly test any sort of support for this.

**Comment by 19h** [comment]
The `aarch64-apple-ios` triple seems slightly ambiguous once there are arm64e targets as pointer-authentication would break unauthenticated environments. Given that arm64e-darwin is on its way, two new triples, `aarch64e-apple-darwin` and `aarch64e-apple-ios`, would probably make more sense?

**Comment by luxxxxy** [comment]
@19h `aarch64e` would be ENTIRELY inaccurate of a name.

**Comment by 19h** [comment]
@luxxxxy It's unfortunate that both arm64 and aarch64 refer to the same ISA, whereas the former was the result of proprietary work by Apple that only was open-sourced after other vendors published their work on the latter.

Aarch64 is an alias for the ARMv8-A ISA, and it would be confusing to have arm64e coexist with aarch64. But given that arm64e actually references a _proprietary_ extension of the ARMv8-A ISA, it might be reasonable to have it named in a way that clearly separates it from the other.

**Comment by ttimpe** [comment]
@luxxxxy If one had such a device, would you be interested in testing something on it?

**Comment by luxxxxy** [comment]
I have an arm64e phone (iPhone 11, iOS 13.5)

I'd be glad to test something on it, I've been using it to get rustc/cargo working on iOS.

**Comment by luxxxxy** [comment]
I am currently adding PAC/arm64e to a [fork using Apple's LLVM](https://github.com/Crabapple-iOS/rust/tree/arm64e-apple-ios). Hopefully some of my work can be reused whenever PAC/arm64e support is upstreamed into LLVM.

**Comment by asgmeonerandom** [comment]
that's work on jailbreak only?

**Comment by luxxxxy** [comment]
> 
> 
> that's work on jailbreak only?

That's how I'm testing it. However, most likely, this will also work on Apple Silicon (ARM) macs. Not sure if iOS lets you submit arm64e slice apps to the app store, though.

**Comment by hjmallon** [comment]
`arm64e` is currently required when building kernel modules for macOS on Apple Silicon machines, but `arm64e` binaries will not run in userspace (currently `arm64`, or running `x86_64` under Rosetta emulation is required).

**Comment by woachk** [comment]
@hjmallon Hello,

The arm64e ABI is currently not considered as final. To run arm64e binaries on macOS on Apple Silicon, add the -arm64e_preview_abi argument to boot-args.

**Comment by pwn0rz** [comment]
In some cases, the `arm64e` arch might be "different". For example:

1.  `thread_set_state` might fail with  `(os/kern) protection failure` if we try to call it from `arm64` process to `arm64e` process.
2. The returning value of `dlsym` is PAC signed on `arm64e`,  while left untouched on `arm64`
3. Some function like `pthread_create_from_mach_thread` requires a PAC signed function pointer on `arm64e`, which is not required on arm64e.

It seems that Apple just simply disables PAC on arm64 process to accomplish 2 and 3. However, case 1 can still not be covered if there is no arm64e target. I am not sure whether there is another case of ”cross arch“ interaction like case 1.

**Comment by kit-981** [comment]
I think the target should be `aarch64-apple-ios-arm64e` given that `arm64e` is a specific ABI that leverages instructions from the Armv8.3-A ISA. `aarch64-apple-ios` binaries can run on these devices providing they don't exercise parts of the ABI that rely on pointer authentication.

I've managed to build a Rust toolchain on Linux that generates iOS Armv8.3-A binaries where the return addresses are signed. LLVM has a `sign-return-address` module flag along with a `sign-return-address-with-bkey` module flag that can be used. From what I can tell, LLVM doesn't yet have the features required for the Rust compiler to implement complete `arm64e` support that would handle things like `dlsym` returning signed addresses.

I'm not a compiler engineer and it's very possible I've made a mistake in the above.

**Comment by aviramha** [comment]
Any news on this?

**Comment by sierkb** [comment]
Any progress on this issue?

**Comment by glandium** [comment]
What's missing after https://github.com/rust-lang/rust/pull/115526 to have `rustup target add arm64e-apple-ios` work out of the box? (IOW, what is missing for artifacts for these tier 3 targets to be available?)

**Comment by aviramha** [comment]
@glandium  It needs to be promoted to tier 2 AFAIK

**Comment by aviramha** [comment]
I sent a MCP to do the promotion for arm64-darwin.
https://github.com/rust-lang/compiler-team/issues/717

**Comment by glandium** [comment]
For what it's worth, LLVM [doesn't support CPU_SUBTYPE_PTRAUTH_ABI yet](https://github.com/llvm/llvm-project/issues/80200), which is required by Xcode's linker to link arm64e code.

**Comment by arttet** [comment]
**Summary**:

- [ ] Support for `CPU_SUBTYPE_PTRAUTH_ABI` in [LLVM](https://github.com/llvm/llvm-project/issues/80200) is required. Blocks the following issues: 
  - [ ] https://github.com/rust-lang/rust/issues/130085
  - [ ] https://github.com/rust-lang/rust/issues/130834
 - [ ] Support for `arm64e` in [LLD](https://github.com/llvm/llvm-project/issues/79543) is required.
 - [ ] Support for `arm64e` in [jemallocator](https://github.com/rust-lang/rust/issues/131884) is required.

**Comment by madsmtm** [comment]
I'll add that given that Apple haven't [completed](https://github.com/swiftlang/llvm-project/pull/8946) upstreamed their LLVM patches for this yet, it is a bit unclear what kind of ABI stability one can expect _between_ compilers (e.g. linking Rust and C code), so I'd be quite weary of making this tier 2 until we are certain in that.

Also linking to the latest MCP for attempting to promote to tier 2: https://github.com/rust-lang/compiler-team/issues/793

**Comment by glandium** [comment]
> Support for CPU_SUBTYPE_PTRAUTH_ABI in https://github.com/llvm/llvm-project/issues/80200 is required.

Note this was fixed in LLVM 20, which means rustc 1.87 has it.

Current nightly can build a hello world without LLD (lld hasn't been fixed yet to support arm64e properly):
```
% cargo +nightly build --target arm64e-apple-darwin -Zbuild-std=std
   Compiling compiler_builtins v0.1.159
   Compiling core v0.0.0 (/Users/glandium/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core)
   Compiling libc v0.2.172
   Compiling object v0.36.7
   Compiling std v0.0.0 (/Users/glandium/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std)
   Compiling rustc-std-workspace-core v1.99.0 (/Users/glandium/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling alloc v0.0.0 (/Users/glandium/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc)
   Compiling cfg-if v1.0.0
   Compiling memchr v2.7.4
   Compiling adler2 v2.0.0
   Compiling panic_abort v0.0.0 (/Users/glandium/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/panic_abort)
   Compiling rustc-demangle v0.1.24
   Compiling unwind v0.0.0 (/Users/glandium/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/unwind)
   Compiling rustc-std-workspace-alloc v1.99.0 (/Users/glandium/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/rustc-std-workspace-alloc)
   Compiling panic_unwind v0.0.0 (/Users/glandium/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/panic_unwind)
   Compiling gimli v0.31.1
   Compiling miniz_oxide v0.8.8
   Compiling hashbrown v0.15.3
   Compiling std_detect v0.1.5 (/Users/glandium/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/stdarch/crates/std_detect)
   Compiling addr2line v0.24.2
   Compiling rustc-std-workspace-std v1.99.0 (/Users/glandium/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/rustc-std-workspace-std)
   Compiling rustc-literal-escaper v0.0.2
   Compiling proc_macro v0.0.0 (/Users/glandium/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/proc_macro)
   Compiling foo v0.1.0 (/Users/glandium/foo)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 7.08s
```
The resulting binary, however, doesn't work:
```
% lldb target/arm64e-apple-darwin/debug/foo
(lldb) target create "target/arm64e-apple-darwin/debug/foo"
Current executable set to '/Users/glandium/foo/target/arm64e-apple-darwin/debug/foo' (arm64e).
(lldb) r
Process 2300 launched: '/Users/glandium/foo/target/arm64e-apple-darwin/debug/foo' (arm64e)
Process 2300 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x605a00018fa440f8)
    frame #0: 0x000000018fa440f8 libdyld.dylib`_tlv_get_addr
libdyld.dylib`_tlv_get_addr:
->  0x18fa440f8 <+0>:  ldr    w16, [x0, #0x8]
    0x18fa440fc <+4>:  mrs    x17, TPIDRRO_EL0
    0x18fa44100 <+8>:  and    x17, x17, #0xfffffffffffffff8
    0x18fa44104 <+12>: ldr    x17, [x17, x16, lsl #3]
Target 0: (foo) stopped.
(lldb) register read $x0
      x0 = 0x00000001001b89f0  foo`std::thread::current::CURRENT::h46ed779abe02c7ae
```

**Comment by aviramha** [comment]
Thanks for explaining the current situation @asl !
I wonder if anyone here knows when/if Apple will let 3rd party binaries run arm64e any time soon (on Macbooks)?

**Comment by woachk** [comment]
@aviramha This is now possible on macOS/iOS/... 26. See https://developer.apple.com/documentation/xcode/enabling-enhanced-security-for-your-app

**Comment by aviramha** [comment]
> [@aviramha](https://github.com/aviramha) This is now possible on macOS/iOS/... 26. See [developer.apple.com/documentation/xcode/enabling-enhanced-security-for-your-app](https://developer.apple.com/documentation/xcode/enabling-enhanced-security-for-your-app)

I searched for that just 2 weeks ago and didn't find - I guess my search was around aarch64/arm64e and the doc doesn't have any of those keywords. 

Reading more into that, I see this note:
> This setting is available on iOS 26 and later on iPhone 17, iPhone 17 Pro, iPhone 17 Pro Max, or iPhone Air.

Are you sure it'll also for macOS? I knew arm64e executables were supported on iPhones

**Comment by woachk** [comment]
@aviramha that's about MTE specifically, which isn't in any announced Mac right now.

**Comment by woachk** [comment]
See the Xcode changelog: https://developer.apple.com/documentation/xcode-release-notes/xcode-26-release-notes

**Comment by aviramha** [comment]
> See the Xcode changelog: [developer.apple.com/documentation/xcode-release-notes/xcode-26-release-notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-26-release-notes)

It says it supports it but it supported building even before, but you need to enable the preview abi in boot to run the process.
I'm upgrading to the beta to see if I can run a 3rd party arm64e binary
I wish they were less ambiguous about it :(

**Comment by woachk** [comment]
It's not a preview ABI anymore in the *OS 26 releases.

However, make sure to build with the newer toolchain. Older toolchains will produce preview ABI binaries that will still be blocked from launch on the new macOS release.

**Comment by aviramha** [comment]
Thanks for the heads up! It indeed works. Do you know if arm64e binary built with Xcode 26 will be able to run on pre-Tahoe (26) macOS? Wondering what kind of compatibility is needed to be considered.

**Comment by aviramha** [comment]
I provided an arm64e binary built on Xcode 26 to macOS 16 user and it ran :) very cool
