### ISSUE TITLE
Tracking Issue for `core::mem::num_variants`

### ISSUE THREAD

**Issue by doctorn** [rust-lang/rust#73662]
The feature gate for the issue is `#![feature(num_variants)]`.

### Steps

- [x] Implement the intrinsic
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

None

### Implementation history

- #73418

**Comment by avl** [comment]
@RalfJung  Responding to your response here instead, as per kennytm:s request.

The reason I asked about if it returned "largest discriminant + 1" is because such a behavior would be kind of reasonable with your motivation, about using the enum as an index into a Vec. There could be other situations where knowing the maximum discriminant value could actually be more important than knowing the number of elements. That said, maybe there should be two functions, one to get the maximum discriminant and one to get the number of elements. Or maybe the number of variants really is the only thing anyone ever cares about. Just wanted to bring up the question :-) .

The other point I was making was that perhaps an obligatory u64 is not necessary for the count. Other counts in rust use usize, and though I understand that you could in theory have 2^40 enum variants on a 32 bit machine, I don't think the compiler can really compile this even on a 64 bit machine right now. Also, I think having 2^40 enum variants on a 32-bit machine is sufficiently 'weird' that it seems reasonable for some friction to occur. I personally cannot imagine a scenario where an application would need more enum variants than the number of addressable bytes on the platform, though of course the fact I can't imagine it doesn't mean it doesn't exist :-) .

Really, there are some problems which are too big for some machines. As an example, a problem requiring a 100MB lookup-table is simply too big to process on a 16 bit machine. My argument is that a problem requiring a 2^40 variant enum is simply too big to process on a 32-bit machine. That said, a reasonable person could certainly disagree here!

Knowing the largest discriminant of an enum could be useful in these cases:

* Choosing a representation during serialization. Knowing the largest discriminant means being able to tell how many bits will be needed to serialize it.
* If an array is used as a sort of lookup-table with discriminants as keys, knowing the largest discriminant could be useful to be able to statically size the array correctly. Of course, such an approach only works well if the manually assigned discriminants are assigned in a mostly dense way.

**Comment by RalfJung** [comment]
I see, thanks.

I personally have no skin in this game, I doubt I will ever use that API.^^ I was just involved in reviewing. @doctorn  would be the one to ask about motivation. :)

**Comment by Flying-Toast** [comment]
We should probably add a deny lint to rustc that prevents calling `variant_count::<T>()` where `T` is not an enum.

Regarding the API itself though, IMO it feels a bit janky:
- Calling `variant_count` where T isn't an enum is unspecified behavior (a lint would help with this)
- Getting the variant count of an enum with > `usize::MAX` variants is unspecified (although practically impossible, it seems strange to forbid something that's technically allowed by the language)
- Returns a `usize`, even if the repr is something else

What would be the drawbacks to doing this with a trait?
```Rust
trait Enum {
    type Repr;
    /// Returns the maximum possible index into an array containing every variant of this enum.
    /// Returns `None` if the enum has no variants.
    const fn max_variant() -> Option<Repr>;
}
```
The compiler could automatically implement this trait for all enums, and it would be used like:
```Rust
enum Foo { /* ... */ }

<Foo as core::intrinsics::Enum>::max_variant()
```

**Comment by Flying-Toast** [comment]
RE: @doctorn's comment in [73418](https://github.com/rust-lang/rust/pull/73418#discussion_r445374601):
> you can’t use `<T as DiscriminantKind>::Discriminant` because if I have an enum with `256` variants the discriminant type will be `u8` which can’t represent `256`.

We could also use a similar API like my previous comment, but without a trait:
```rust
/// Returns the maximum possible index into an array containing every variant of this enum.
/// Returns `None` if the enum has no variants.
fn max_variant<T>() -> Option<<T as DiscriminantKind>::Discriminant>
```
Combined with a rustc lint for non-enum `T`s,  I think that would get rid of all unspecified behavior. Thoughts?

**Comment by doctorn** [comment]
Honestly the `Enum` trait sounded better to me. I much prefer having the number of variants returned rather than the maximum repr.

**Comment by Flying-Toast** [comment]
> Honestly the `Enum` trait sounded better to me. I much prefer having the number of variants returned rather than the maximum repr.

Ok.

One more thing - the [`discriminant_value`](https://doc.rust-lang.org/std/intrinsics/fn.discriminant_value.html) intrinsic uses `u64`s for discriminants, so maybe `variant_count` should return a `u64` to be consistent with that?

**Comment by lcnr** [comment]
> the [`discriminant_value`](https://doc.rust-lang.org/std/intrinsics/fn.discriminant_value.html) intrinsic seems to use `u64`s for discriminants;

https://doc.rust-lang.org/nightly/std/intrinsics/fn.discriminant_value.html

it does not, the docs are outdated on stable though '^^

**Comment by BusyJay** [comment]
Should this function be a const function?

**Comment by johnkjellberg** [comment]
> Should this function be a const function?

The way I want to use this require it to be const. And I don't really see why it shouldn't?

**Comment by doctorn** [comment]
@BusyJay I believe this function is `const`, but the docs incorrectly omit this

**Comment by RalfJung** [comment]
The [docs](https://doc.rust-lang.org/nightly/core/mem/fn.variant_count.html) mention constness in the top-right corner: `const: [unstable](https://github.com/rust-lang/rust/issues/73662)`.

`const fn` is only printed for functions whose constness is stable.

**Comment by EriKWDev** [comment]
I use this all the time. I love having enums represent all the variants I want and then storing data for them in arrays which requires me to know the number of them in compile time.

```rust
#[repr(usize)]
enum MyKind {
   Kind1,
   Kind2,
}

// This constant gets outdated if the number of variants change...
pub const NUM_MY_KIND: usize = 2; 

struct KindData1 { /* ... */ }
struct KindData2 { /* ... */ }
struct KindData3 { /* ... */ }

struct Data {
    //...
    data1: [KindData1; NUM_MY_KIND],
data1: [KindData1; NUM_MY_KIND],
    kinds: Vec<MyKind>,
}

fn func(data: &Data) {
    for kind in 
}
```

**Comment by joshtriplett** [comment]
Nominating this for lang, because empirically we've stalled out on a potentially useful library addition on the basis of proposed lang features, which themselves seem to have stalled out.

I'd love to see `AsRepr` if someone wants to pick that back up and get it over the finish line. But also, this might be a reasonable interim step, and it doesn't seem like it does any *harm* to have it even if we add better solutions in the future.

**Comment by MarinPostma** [comment]
@joshtriplett I like to pick this up, if someone can point me in the right direction

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this in the meeting today, and as above, **scottmcm** volunteered to make a proposal here and we decided to wait for that.  So let's unnominate this for now, but please nominate the proposal, wherever it is made, for us.

**Comment by Supreeeme** [comment]
Any updates on this?

**Comment by traviscross** [comment]
The thread to track is:

- https://github.com/rust-lang/rfcs/pull/3607

**Comment by jdm** [comment]
For those reading along at home, https://github.com/rust-lang/rfcs/pull/3607 explicitly calls out that the enum variant count functionality would require a separate RFC: https://github.com/scottmcm/rfcs/blob/enum-discriminant/text/3607-enum-discriminant.md#future-possibilities .

**Comment by RoDmitry** [comment]
I don't understand at all the purpose of "special discriminants" for `variant_count`, even if you would have `max_discriminant` and `min_discriminant`. I will explain:
```rust
#![feature(variant_count)]
fn main() {
    #[allow(unused)]
    #[non_exhaustive]
    #[repr(usize)]
    enum Data {
      A = 1,
      B = 10,
    }

    assert_eq!(std::mem::variant_count::<Data>(), 2);
    println!("{:?}", std::mem::discriminant(&Data::B)); // 10
    assert_eq!(Data::B as usize, 10);
}
```
`max_discriminant` == 10
`min_discriminant` == 1
I don't understand, how is it helping anything?

Here is my working code, and it does not require any "special discriminants":
```rust
#![feature(variant_count)]
fn main() {
    #[allow(unused)]
    #[non_exhaustive]
    #[repr(usize)]
    enum Data {
      A,
      B,
    }

    const DATA_COUNT: usize = ::core::mem::variant_count::<Data>();
    type DataArr<T> = [T; DATA_COUNT];
    fn data_arr_default<T: Default + Copy>() -> DataArr<T> {
        [Default::default(); DATA_COUNT]
    }

    // usage
    let mut data_arr = data_arr_default::<bool>();
    data_arr[Data::B as usize] = true;
}
```
That's why I need stabilization of `variant_count`.

**Comment by hanna-kruppe** [comment]
> As long as nobody assigns any values to the enum variants, code is valid. But this can be covered by the test:

How would you write a test like that without deriving `strum::EnumIter`? If you're okay with a custom derive on the enum definition, you can also get the variant count via `strum::EnumCount` as you mentioned. I don't see the benefit of replacing `strum::EnumCount` if you're still gonna need `strum` anyway.

To me the appeal of `std::mem::variant_count` is the potential to do various things reliably without needing `syn`-based custom derives or non-trivial `macro_rules!` that must wrap the entire enum definition. It seems to me that *something* more than `variant_count` is needed to achieve that. `{min,max}_discriminant` would help but only if you can do arithmetic with its return value (`Discriminant<T>` doesn't allow that last I checked).

**Comment by RoDmitry** [comment]
> How would you write a test like that without deriving `strum::EnumIter`? ... you're still gonna need `strum` anyway

I see the point. Just wanna say than `strum::EnumIter` can be restricted to be there only for tests, but not the `strum::EnumCount`.

**Comment by hanna-kruppe** [comment]
An iterator over variants-as-values only really works for field-less enums, while the notion of discriminants applies equally to all enums. Iterators also aren’t available in `const` contexts yet and I don’t know when they will be. Until then, for many use cases you’d still have to write out e.g., variant counts by hand and add a separate unit test to check if the value you’ve written down is correct.
