### ISSUE TITLE
Tracking issue for new LLVM pass manager (-Znew-llvm-pass-manager)

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#74705]
This is a tracking issue for rustc's use of the new LLVM pass manager, which is currently behind an unstable rustc flag `-Znew-llvm-pass-manager` but which we will presumably want to make default at the right time, just like Clang intends to do.

When building with `-Znew-llvm-pass-manager`, both the pre-link optimization and LTO pipelines use the new pass manager.

There are some bits that are not supported yet:

- [x] ~~NewPM does not support PGO at O0 in LLVM 9. This is supported in LLVM 10.~~ Fixed by https://github.com/rust-lang/rust/pull/67759.
- [x] NewPM does not support MergeFunctions in LLVM 9. While it's supported in LLVM 10, it's not exposed as a PassBuilder option. We'll have to manually schedule the pass, or add that option upstream.
- [x] `-C passes`. NewPM requires an entirely different way of specifying custom pass pipelines. We should probably expose that functionality, but it doesn't directly map to what `-C passes` does.
- [ ] NewPM has no support for custom inline parameters right now. We'd have to add upstream support for that first.

### About tracking issues

Tracking issues are used to record the overall progress of implementation. They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions. A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature. Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Implementation history

- Implemented in https://github.com/rust-lang/rust/pull/67954

**Comment by nikic** [comment]
> NewPM does not support MergeFunctions in LLVM 9. We'll be able to re-enable that with LLVM 10.

While it's supported in LLVM 10, it's not exposed as a PassBuilder option. So we'd have to manually schedule the pass, or add that option upstream.

**Comment by hudson-ayers** [comment]
Should this be closed by https://github.com/rust-lang/rust/pull/88243 ?

**Comment by cuviper** [comment]
Well, the `-Z` option still exists, just defaulting to "yes" now for LLVM >= 13.

**Comment by pnkfelix** [comment]
At this point I don't think this tracking issue is serving much purpose. My understanding is that LLVM 15 has removed support for the old pass manager.

I do see that the `-Z` flag is still around. I don't know if that's to accommodate users who are linking to an older version of LLVM. (I also don't know if such a scenario is tested in our CI or supported at any level.)

I'm going to close this issue; future work on what do to with the aforementioned `-Z` flag can follow the MCP process (or we can probably go straight to removing it in a Pull Request if I'm right that it doesn't make sense to continue offering it).

**Comment by cuviper** [comment]
LLVM 13 is now our minimum, and we default to newPM everywhere -- *except* on s390x due to #89609, where that was only resolved in LLVM 14 since #94764. If it weren't for that, I'd say go ahead and remove the option, along with all of the code supporting oldPM.

I have a local branch for updating the minimum to LLVM 14, and while I don't think we're ready for that quite yet, I can add this removal to my branch so I won't forget later. :)

**Comment by cuviper** [comment]
Here's a preview `git diff --stat`, not bad! :slightly_smiling_face: 

```
 Cargo.lock                                                      |   1 -
 compiler/rustc_codegen_llvm/Cargo.toml                          |   1 -
 compiler/rustc_codegen_llvm/src/back/lto.rs                     |  63 ++-----------
 compiler/rustc_codegen_llvm/src/back/write.rs                   | 258 +++--------------------------------------------------
 compiler/rustc_codegen_llvm/src/lib.rs                          |   2 +-
 compiler/rustc_codegen_llvm/src/llvm/ffi.rs                     |  74 +--------------
 compiler/rustc_codegen_llvm/src/llvm_util.rs                    |  29 +-----
 compiler/rustc_codegen_ssa/src/back/write.rs                    |   2 -
 compiler/rustc_interface/src/tests.rs                           |   1 -
 compiler/rustc_llvm/llvm-wrapper/PassWrapper.cpp                | 235 +-----------------------------------------------
 compiler/rustc_session/src/options.rs                           |   2 -
 src/doc/unstable-book/src/compiler-flags/self-profile-events.md |   2 +-
 src/test/rustdoc-ui/z-help.stdout                               |   1 -
 src/test/ui/invalid/invalid-llvm-passes.rs                      |   2 +-
 src/test/ui/sanitize/new-llvm-pass-manager-thin-lto.rs          |   2 +-
 15 files changed, 24 insertions(+), 651 deletions(-)
```

**Comment by nikic** [comment]
I think it would be fine to drop legacy PM support without dropping LLVM 13 support. That just means that the particular combination of s390x + LLVM 13 may have some issues -- but I don't think we're obligated to care given that this is both a tier 2 architecture *and* an old LLVM version. I'd even expect that that particular intersection (s390x + llvm13 + nightly rustc) has exactly zero users.

**Comment by mati865** [comment]
Also this is an unstable flag that is unusable on stable (at least without hacks) and vendors typically only provide stable toolchains.

**Comment by cuviper** [comment]
> I'd even expect that that particular intersection (s390x + llvm13 + nightly rustc) has exactly zero users.

It still matters for stable since the implicit fallback behavior happens without the unstable option, and for example Fedora 35 is a downstream that builds on LLVM 13. I don't know how active Fedora s390x really is, nor if any other distros care. For that matter, Fedora 35 EOL will be around the end of November, before the current 1.66 nightly releases on December 15.

I'll go ahead and open a PR for it, and we can see if there's any objection.
