### ISSUE TITLE
Tracking Issue for slice::array_windows

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#75027]
The feature gate for the issue is `#![feature(array_windows)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Restrict `N` to values greater than 0 at compile time instead of using a runtime panic.
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

- implemented in #75026

**Comment by yoshuawuyts** [comment]
In [the docs it says](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.array_windows):

> If N is smaller than the size of the array, it will return no windows.

I'm a bit confused what that refers to; it's the first use of "array" in that section of the docs. Perhaps there's a way to phrase that more clearly?

**Comment by lcnr** [comment]
@yoshuawuyts  see https://github.com/rust-lang/rust/pull/76827 :laughing:

**Comment by leonardo-m** [comment]
Is not possible to forbid N==0 like this?
```rust
#![feature(
    const_evaluatable_checked,
    const_generics,
    const_panic,
)]
#![allow(incomplete_features)]

const fn nonzero(n: usize) -> usize {
    assert!(n > 0);
    n
}

fn foo<const N: usize>() -> [u8; nonzero(N)] {
    [0; nonzero(N)]
}

fn main() {
    foo::<5>();
}
```

**Comment by lcnr** [comment]
yes, this is possible, it does require us to use `const_evaluatable_checked' in the standard library though.

That's not yet something I feel comfortable with

**Comment by the8472** [comment]
Bikeshed:

Would `windowed_iter()` be a better name? It follows the convention that `iter()` usually returns borrowed iterators.

**Comment by TrolledWoods** [comment]
@the8472 While it's true that ``iter`` usually returns borrowed iterators, there are a lot of borrowed iterators that do not have ``iter`` in their name. ``values``, ``keys``, ``chunks``, ``windows``, e.t.c. Considering that ``windows`` is already a stabilized name too, it would make sense for this name to also contain ``windows``.

Additionally, if there are any better name suggestions for these const generic equivalents, we need change ``array_chunks`` too to follow that convention.

**Comment by Stargateur** [comment]
Is compile time check of N == 0 a real problem ? I expect LLVM to remove this check for free. The only thing I could think of is we consider it's breaking change to add the compile time check in the future but I hardly can imagine break someone workflow with that, cause it's a hard panic anyway, user code would be considered totally bogus ?

**Comment by leonardo-m** [comment]
>Is compile time check of N == 0 a real problem ? I expect LLVM to remove this check for free.

That's beside the point. The point is spotting at compile-time some wrong code.

**Comment by yoshuawuyts** [comment]
I used `Slice::array_windows` for a project yesterday, and it worked really well. I'm excited for this to be stabilized! The only downside is that when we're dealing with streaming data it requires collecting into a vec first. 

It'd be neat if once we merge `Slice::array_windows`, we can look towards adding a variant of `Iterator::array_windows` as well ([example impl](https://github.com/yoshuawuyts/aoc/blob/d7ff2e4b6df78d71fffe2d9a3eea8e2ff323daff/aoc-2021/src/stdx.rs)). In order for it to have the same yield type as `Slice::array_windows` we'll first need GATs and lending iterators to land first though; so it'll still be a while longer out. But I hope that once those land we can start experimenting with those.

### Examples
**Usage example of `Slice::array_windows`**
```rust
fn parse1(input: &str) -> usize {
    let lines: Vec<u16> = input.lines().map(|line| line.parse().unwrap()).collect();
    lines.array_windows().filter(|[n1, n2]| n2 > n1).count()
}
```
**Usage example of `Iterator::array_windows`**
_This is slightly nicer to use when dealing with streaming data, but requires lending iterators to land in order to have the right return signature._
```rust
fn parse1(input: &str) -> usize {
    input
        .lines()
        .map(|line| line.parse::<u16>().unwrap())
        .array_windows()
        .filter(|[n1, n2]| n2 > n1)
        .count()
}
```

**Comment by Stargateur** [comment]
Could this be used ?

```rust
#[allow(unconditional_panic)]
if N == 0 {
    panic!("Size N can't be zero");
}
```

That should be more simple for the current state of the compiler and would allow to have better code in the future without introduce any potential breaking change.

**Comment by steffahn** [comment]
I'm noticing some missing `Send`/`Sync` implementations on the iterator. (Due to the usage of `*const T`, they are not auto-implemented.)

**Comment by pervognsen** [comment]
I've been finding a lot of good uses for `array_windows`, but one thing that seems missing is an implementation of the Index trait. One use case is random access bit slicing. If you have a bit stream represented as `bytes: &[u8]` and want to read the slice of bits `i..i+n`, where `i` is the bit index and `n < 64` is the bit width, then if `Index` were implemented you could do something like `let bits = (u64::from_le_bytes(array_windows::<8>()[i / 64]) >> (i % 64)) & ((1 << n) - 1)`.

**Comment by clarkmcc** [comment]
I'm getting the following error. I'm wondering if it's related to @steffahn's comment, since I can drop-in my own windowing iterator and everything compiles fine.

    has type `ArrayWindows<'_, Foobar, 3>` which is not `Send`

**Comment by Stargateur** [comment]
can't we have a mut version ?

**Comment by alexander-novo** [comment]
> can't we have a mut version ?

Not with the `Iterator` trait that we currently have in `std`. With the `Iterator` trait we currently have, the  references we get from calling `iter.next()` are allowed to outlive the next call to `iter.next()` - and if we had a `mut` version, then we could potentially have multiple references to the same item in the slice while one of the was `mut` - which isn't allowed.

To do this properly, we'd need an iterator which enforces that the references returned by `iter.next()` can't outlive the next call to `iter.next()` - which is possible to do, but until recently it wasn't possible to write a trait for that. With GATs stabilized, it's now possible to write such a trait (many people refer to such a trait as a `LendingIterator`), but no such trait has been written yet for `std`. Unfortunately, even though GATs are stabilized, there are still many bugs which would prevent people from easily *implementing* such a trait, and there are also many logistics that need to go into making such a trait useful (i.e. being able to use a `LendingIterator` everywhere you can use an `Iterator`). [Here's a blog post](https://blog.rust-lang.org/2022/10/28/gats-stabilization.html) which goes over some of the details.

**Comment by harudagondi** [comment]
Given that `const` blocks (#104087) has been stablized, is it possible to just use `const { assert!(N > 0) }` or am I missing something here?

**Comment by the8472** [comment]
We wouldn't be able to turn that into a `where N != 0` trait bound later since the const asserts result in post-mono errors while the bound would have to be proven during type-checking.

**Comment by urben1680** [comment]
Would it be bad really if this was used with `0`? It would yield infinite empty arrays. If that is documented then it would be okay.

**Comment by illicitonion** [comment]
[`slice::as_chunks` stabilised](https://github.com/rust-lang/rust/pull/139656) with the runtime check rather than bound here (from https://github.com/rust-lang/rust/issues/74985 which had originally required the same compile-time rather than panic requirement which [got dropped](https://github.com/rust-lang/rust/pull/99471)) and ended up in 1.88.0 - it feels like the same reasoning there applies here - the APIs are very similar. Should we stabilise this with just the runtime check?

**Comment by Amanieu** [comment]
We discussed this in the @rust-lang/libs-api meeting. We decided to keep this as a runtime check which is consistent with `as_chunk`. Similarly, we decided against making `N = 0` work without a panic for consistency with `windows`: it doesn't make sense for `array_windows` to have well-defined behavior for zero-sized windows when `windows` panics in this case.

@rfcbot merge

**Comment by rust-rfcbot** [comment]
:bell: **This is now entering its final comment period**, as per the [review above](https://github.com/rust-lang/rust/issues/75027#issuecomment-3352814663). :bell:

**Comment by Morgane55440** [comment]
hey sorry for the very late message after the FCP but you forgot to add Send and Sync. 

already mentioneed here too [https://github.com/rust-lang/rust/issues/75027#issuecomment-1013948571](https://github.com/rust-lang/rust/issues/75027#issuecomment-1013948571)
