### ISSUE TITLE
Tracking Issue for pointer methods returning `MaybeUninit<T>`

### ISSUE THREAD

**Issue by TimDiekmann** [rust-lang/rust#75402]
This is a tracking issue for methods on pointer types returning `MaybeUninit`: `as_uninit_ref/mut` and `as_uninit_slice(_mut)` on mutable and const raw pointers and `NonNull`.
The feature gate for the issue is `#![feature(ptr_as_uninit)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Merge Implementation (cc @rust-lang/T-libs, cc @RalfJung)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- None

### Implementation history

- Initial implementation: #75392

**Comment by RalfJung** [comment]
A possible concern for stabilization is that these methods will be somewhat redundant if we end up deciding that references do not have to point to valid data -- though maybe reflecting the initialization state is a good idea even in that case? Also it seems likely that some `T` will *not* allow uninitialized references, i.e., there is demand for making `&!` uninhabited.

**Comment by Kixunil** [comment]
Having such cast on pointers rather than references could be useful in situations like in #93653  (although having cast on `Box` is even better in that case).

@RalfJung any good resource explaining why it'd be useful to allow uninitialized references? Anyway, I do like tracking (un)initializedness in type even for documentation value.

**Comment by RalfJung** [comment]
For documentation, it is the [*safety* invariant](https://www.ralfj.de/blog/2018/08/22/two-kinds-of-invariants.html) of a type that are most relevant, and those certainly still apply recursively below references.

For the *validity* invariant, see https://github.com/rust-lang/unsafe-code-guidelines/issues/77 for the discussion. Basically, specifying the language becomes a hell of a lot simpler if the validity invariant depends solely on the bit pattern of the value itself, and not on other state of the system such as the current contents of memory.

**Comment by RalfJung** [comment]
`NonNull::as_ref` takes `&Self`.  It would seem odd for `NonNull::as_uninit_ref` to diverge from that?

**Comment by pnkfelix** [comment]
Visiting for T-compiler backlog bonanza

@RalfJung 's comments above were somewhat echo'ed by @m-ou-se in the meeting

@rustbot label: S-tracking-design-concerns
