### ISSUE TITLE
Tracking issue for `ControlFlow` enum, for use with `try_fold` and in `Try`

### ISSUE THREAD

**Issue by NoraCodes** [rust-lang/rust#75744]
(edited to turn this into a tracking issue, as it's referenced by the `unstable` attributes)

This is a tracking issue for the `std::ops::ControlFlow` type.
The feature gate for the issue is `#![feature(control_flow_enum)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement
- [x] Block interconversion with `Result`s
   - Done with https://github.com/rust-lang/rust/pull/84767
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])
   - As part of stabilizing, mention in the docs for `Iterator::try_fold` and `Iterator::try_for_each`

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- [x] ~~Should we change the generic parameter order? https://github.com/rust-lang/rust/pull/76204/files#r481357223~~ done in https://github.com/rust-lang/rust/pull/76614
- [ ] What methods make sense
  - [x] ~~(probably not the `into_try` ones, https://github.com/rust-lang/rust/pull/76204/files#r481515347)~~ Removed those ones in #85645
- [x] ~~Are the `CONTINUE`/`BREAK` constants valuable? See #102697~~
  - Removed in https://github.com/rust-lang/rust/pull/107398
- [ ] Should it have `B = ()` too?  (Might be nice for `try_for_each` uses.)

### Implementation history

Initial PR that added `LoopState` as an implementation detail: https://github.com/rust-lang/rust/pull/45595
PR that exposed as unstable and renamed to `ControlFlow`: https://github.com/rust-lang/rust/pull/76204
Added `BREAK`/`CONTINUE` associated constants: https://github.com/rust-lang/rust/pull/76318
Changed type parameter order and defaulted `C = ()`: https://github.com/rust-lang/rust/pull/76614
Add `is_break` and `is_continue` methods: #78200

---

I work with an organization that has a large amount of Rust graph traversal code as part of its core business. We used to use `itertools`'s `fold_while` for short-circuiting functional-style loops over slices of our graphs, which is now deprecated in favor of `try_fold`.

`try_fold` is great, but the lack of a standard library provided `Try` implementation that makes the loop semantics clear is confusing. We created our own, which is fine, but I think it would make a lot of sense to expose [`LoopState`](https://github.com/rust-lang/rust/blob/515c9fa505e18a65d7f61bc3e9eb833b79a68618/library/core/src/iter/mod.rs#L373) and provide an example in the docs.

Originally related to: rust-itertools/itertools#469

**Comment by scottmcm** [comment]
As [the one who added `LoopState` initially](https://github.com/rust-lang/rust/pull/45595/files), I'm not at all tied to that name, so morse's rename sounds good to me -- in fact [I've also been calling it `ControlFlow` in the `Try` discussions](https://github.com/rust-lang/rust/issues/42327#issuecomment-379955253).

@NoraCodes Want to take on making a PR here?  There's probably a few parts:
- Renaming from `LoopState` to `ControlFlow`
- Making it `pub` and having appropriate `#[unstable]` markers on it
- Probably moving it out of `core::iter`; maybe to `core::ops` instead?
- Reexporting from `std`

Feel free to ping me (here, in a draft PR, or on Zulip) if you have questions.

Its methods are probably imperfect right now, but if it's unstable that's ok.  People can start using it on nightly as we'll find out what needs fixing before stabilization that way.

**Comment by scottmcm** [comment]
Congrats on your first core libraries PR, @NoraCodes!

Want to take on the generic parameter reordering (that morse brought up in https://github.com/rust-lang/rust/pull/76204#discussion_r481357223) next?

**Comment by NoraCodes** [comment]
Thanks @scottmcm! I definitely do want to do that. I'll put in a PR either this weekend or Tuesday.

**Comment by scottmcm** [comment]
Another example of a type that's pretty close to this: the `Transition` type in https://deislabs.io/posts/a-fistful-of-states/, which is essentially `ControlFlow<Result<()>, Box<dyn State>>` -- either execution is done (possibly with an error), or it continues (in the specified state).

**Comment by scottmcm** [comment]
An MCP to use this more often in the compiler: https://github.com/rust-lang/compiler-team/issues/374

Conveniently that also suggests that `ControlFlow<BreakType>` would be better than the current `ControlFlow<(), BreakType>`.

**Comment by NoraCodes** [comment]
Apologies for taking forever on this. I set up a Rust dev env on my new PC and fixed the nits in that PR so we should be good to go.

**Comment by NoraCodes** [comment]
Personally, I don't have much of an opinion on the CONTINUE and BREAK constants. It seems mildly unidiomatic, but I can also see how those constants are useful in writing concise code.

I do think we should default `B = ()`; this makes the simplest cases the simplest to write, and doesn't really increase complexity for more complex cases.

**Comment by scottmcm** [comment]
I've posted a stabilization PR of just the type (not the methods) for consideration at https://github.com/rust-lang/rust/pull/85608

(It's not proposed here because it doesn't stabilize everything, and there can only be one FCP per issue, so having a separate PR will allow the remaining pieces to be FCPed separately later.)

**Comment by mendess** [comment]
I have re implemented a subset of this in a small project of mine since this enum just has really good names for many usecases and I want to use it when it becomes stable, I have to say that the constants `CONTINUE`/`BREAK` are really useful as my usecases haven't needed to use something other than `ControlFlow<(), ()>`. So I would be glad if these constants made it to the final release so I don't have to change much code :smile:

**Comment by dbofmmbt** [comment]
Will it be stabilized in 1.55? It's in the [stabilized APIs section](https://github.com/rust-lang/rust/blob/master/RELEASES.md#stabilised-apis).

**Comment by scottmcm** [comment]
@dbofmmbt Just the type itself was stabilized -- see https://github.com/rust-lang/rust/pull/85608.

This issue remains open to track the methods and associated constants on it which are *not* currently stabilized.

**Comment by Robbepop** [comment]
I wonder if `ControlFlow` could be used as a hint to the Rust compiler in order to optimize certain `switch` based interpreters to use the more efficient `computed-goto` codegen instead of branching at the top of a `switch`.

An example how this could be utilized can be found here: https://gist.github.com/Robbepop/756eedb75466e09e0262ef917818c553
If you paste the linked code into the [Rust compiler explorer](https://rust.godbolt.org/z/hhr4rqKvs) you will see that it currently does not generate the efficient computed goto syntax and it is [kinda hard](https://internals.rust-lang.org/t/computed-gotos-tco-threaded-interpreters-experiments-and-findings/4668) to make it happen deterministically in Rust.

**Comment by MomoLangenstein** [comment]
Would it be possible to also add boolean constructors for `ControlFlow<(), ()>`, e.g.
```rust
impl ControlFlow<(), ()> {
    #[must_use]
    pub fn continue_if(should_continue: bool) -> Self {
        if should_continue {
            ControlFlow::CONTINUE
        } else {
            ControlFlow::BREAK
        }
    }

    #[must_use]
    pub fn break_if(should_break: bool) -> Self {
        if should_break {
            ControlFlow::BREAK
        } else {
            ControlFlow::CONTINUE
        }
    }
}
```

As I am refactoring some prior `bool`-based code, I'm having to repeat these if-cases many times.

**Comment by scottmcm** [comment]
@MomoLangenstein For a simple method addition, you can absolutely send a PR.  With <https://doc.rust-lang.org/std/primitive.bool.html#method.then> stable, there's probably space for something in this area.

What it should be, I don't know.  I'm a bit skeptical of *both* the `break_if` and `continue_if` methods, though -- maybe you can find a nice name that would be ok with just having *one* method?

**Comment by dbofmmbt** [comment]
@MomoLangenstein AFAIK this could be done as an external lib. Actually, I think it may be implemented on stable, as the enum is stabilized. :thinking:

**Comment by MomoLangenstein** [comment]
> @MomoLangenstein AFAIK this could be done as an external lib. Actually, I think it can be implemented on stable, as the enum is stabilized. 🤔

Yes, that's true. Though I think this would really be a convenience function that serves to better document the code functionality more concisely, which would be valuable to have in `core` itself.

**Comment by MomoLangenstein** [comment]
> What it should be, I don't know. I'm a bit skeptical of _both_ the `break_if` and `continue_if` methods, though -- maybe you can find a nice name that would be ok with just having _one_ method?

@scottmcm  I think the most common pattern would be along the lines of
```rust
if some_condition {
    break;
}
```
meaning that `break_if` (or a better name) would probably be more valuable.

**Comment by dbofmmbt** [comment]
```
trait BoolControlFlowExt {
  fn break(self) -> ControlFlow;
  fn continue(self) -> ControFlow;
}

impl BoolControlFlowExt for bool {
  fn break(self) -> ControlFlow {
    match self {
          true => ControlFlow::Break,
          false => ControlFlow::Continue,
}

  fn continue(self) -> ControlFlow {
    match self {
          true => ControlFlow::Continue,
          false => ControlFlow::Break,
}
  }
}
```

@MomoLangenstein what do you think? Sorry about the (probably bad) trait name.

I would define another trait extension for ControlFlow too, as AFAIK it is not easily convertible between other Try types today, and would be nice to convert between them and use`?`.

**Comment by scottmcm** [comment]
Note that if, as above, the common case here is `if ... some cond ... { break }` is the common case, then methods from bool wouldn't really help with that, since it doesn't necessarily want to return the *continue* immediately too.

You might consider experimenting with `try` blocks as an alternative to the method here.  Because `ControlFlow::break_if(... some cond ...)` can also be spelled `try { if ... some cond ... { ControlFlow::BREAK? } }`, and that's more flexible to adding more code in the various different places.

**Comment by MomoLangenstein** [comment]
I guess I meant the `if cond { break }` as more of an example that breaking if a condition is met is probably more common than continuing of a condition is met. In my use case, a simulation with a user-provided early-stop condition, I need to construct `ControlFlow` based on a boolean condition inside a closure, the return value of which is used inside the simulation to determine whether to go on or stop early.

**Comment by quark-zju** [comment]
Not sure if this is the right place for this discussion but I wonder if `?` with control flow can work if the function returns the `B` type.

```rust
fn g() -> std::ops::ControlFlow<u8> {
    std::ops::ControlFlow::Break(1)
} 

fn f() -> u8 {
    g()?;
    0
}

// f() returns 1.
```

This seems useful in cases where the caller of `f` does not care about whether its result comes from a break or a continue, which might be most of the cases.

**Comment by benluelo** [comment]
Adding my 2c here - a `map_continue(..)` combinator (to go with the current `map_break(..)` one), would be very useful. Should I open a new issue and link it here, or is this suggestion OK in this issue?

**Comment by scottmcm** [comment]
@benluelo Since `map_break` exists, I think you could just open a PR to add `map_continue` under the same tracking issue.  Feel free to `r? @scottmcm` on it.

**Comment by ModProg** [comment]
I found a usecase where maybe ControlFlow could be used as well, having an early exit from a `try_fold` for speed up using the same value as the aggregator.

In case this should be in a new issue, let me know.

Something like
```rs
impl<T> ControlFlow<T, T> {
    pub fn value(self) -> T {
        match self {
            ControlFlow::Continue(value) | ControlFlow::Break(value) => value,
        }
    }
}
```

allowing to do 
```rs
let value = smth.try_fold(Vec::new(), |aggr, curr| {
  // Do something 
  if todo!("Some condition that checks weather aggr is ready for early exit e.g. full") {
    ControlFlow::Break(aggr)
  } else {
    ControlFlow::Continue(aggr)
  }
}).value();
```

**Comment by schuelermine** [comment]
@ModProg I have also run into a case where such a method would be desirable

**Comment by LeoniePhiline** [comment]
The naming of `ControlFlow::break_value` and `ControlFlow::continue_value` is inconsistent with `Result::err` and `Result::break`.

Should the two methods be renamed before stabilization?

## Proposed Method Naming

| Current name  | New name | Consistent with |
| ------------- | ------------- | ------------- |
| [`ControlFlow::break_value`](https://doc.rust-lang.org/std/ops/enum.ControlFlow.html#method.break_value)  | `ControlFlow::break`  | [`Result::err`](https://doc.rust-lang.org/std/result/enum.Result.html#method.err)  |
| [`ControlFlow::continue_value`](https://doc.rust-lang.org/std/ops/enum.ControlFlow.html#method.continue_value)  | `ControlFlow::continue`  | [`Result::ok`](https://doc.rust-lang.org/std/result/enum.Result.html#method.ok)  |

**Comment by schuelermine** [comment]
They cannot have that name because those are strict keywords.

**Comment by SmnTin** [comment]
Can we stabilize `map_break` and `map_continue`?

**Comment by SmnTin** [comment]
@scottmcm If we add these methods, `unwrap_break` and `unwrap_continue` might also be good additions. Or their utility is not as obvious as `Result::unwrap` and `Result::unwrap_err`?

**Comment by m-ou-se** [comment]
@scottmcm We discussed your comment in the libs-api meeting. We're happy with the current names (with `_value`). We agree with what you said about `map_break` and `map_continue`, to not prioritize one over the other.

**Comment by dhedey** [comment]
I'm sorry if this is the wrong place to mention this; but I've just been using ControlFlow for a visitor pattern (well a validator + visitor), and had a couple of notes that I think would be very beneficial to other users, and hopefully easy tweaks:

* I got bitten by the fact `ControlFlow` is not `#[must_use]`, and I missed a `?` to propagate the control flow in one location, and failed to abort / return an error. Could we consider adding this? Must like with result, I can't think of a scenario where it wouldn't make sense to do this. As a workaround / sanity-check for now, I'm manually adding `#[must_use]` manually to every method returning a `ControlFlow`.
* On the interface of the interpreter (which calls the visitor), I wanted to turn the `ControlFlow<E, ()>` into a `Result<(), E>` but found it weird that there was no implementation of `impl<C, B> From<ControlFlow<B, C>> for Result<C, B>`, could this be added?

**Comment by NoraCodes** [comment]
I would be in favor of a `#[must_use]` annotation on `ControlFlow`. 

I'm concerned that implementing `Into<Result< >>` would be confusing, since it wouldn't be obvious whether it was `impl<C, B> From<ControlFlow<B, C>> for Result<C, B>` or `impl<C, B> From<ControlFlow<B, C>> for Result<B, C>`. I think the proposed `continue_result` and `break_result` is a better idea, perhaps made even clearer if called `continue_ok` and `break_ok`.

**Comment by dhedey** [comment]
Thanks @NoraCodes - and just to add I much prefer the `continue_ok` and `break_ok` names you propose!

**Comment by dhedey** [comment]
Will do, thanks @scottmcm 👍
