### ISSUE TITLE
Tracking Issue for `array_methods`

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/rust#76118]
This is a tracking issue for a couple of basic methods on arrays. The feature gate for the issue is `#![feature(array_methods)]`. Currently, this includes the following methods:

- `as_slice`, `as_mut_slice` #76120
- `each_ref`, `each_mut` #75490

Note: these methods were all collected under the same `array_methods` feature name as I suspect many (often small) methods to be added to array in the near future. Creating a new feature and tracking issue for each seems overkill. We can still split off some methods into dedicated features later, if required.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Decide what set of methods to stabilize in the first round
- [ ] Change feature names of all methods that are not yet stabilized to something specific
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- [ ] Use the names `each_ref` and `each_mut` or change it to something else? Alternatives: `each_as_ref`/`each_as_mut`, `as_refs`/`as_mut_refs`. See PR #75490 for the name discussion.

**Comment by LukasKalbertodt** [comment]
Just for the protocol, I plan to add the following methods in the near future:

- `cloned`, `copied` and `unzip`: blocked by figuring out how we best add additional impl blocks for arrays (e.g. `[&T; N] where T: Clone`)
- `zip`: waiting for #75717 or #75644 to get merged; otherwise this method would add duplicate code

(discussions about the usefulness of those method should be had in the dedicated PR threads and not here)

**Comment by usbalbin** [comment]
@LukasKalbertodt I have opened PR #79451 for `zip`, saw your comment just now.

**Comment by rossmacarthur** [comment]
> - `as_slice`, `as_mut_slice`

It would be nice to stabilize these methods, I think they are much more useful than the others in this tracking issue and could be stabilized separately. These are already common methods for existing data types so it's not a new API.

I sometimes find myself running into cases where `Deref` coercion doesn't work and I need this. Currently I'm using `&arr[..]` which doesn't really communicate well why it is needed.

For example

```rust
// io::Read does something like this
trait Trait {}
impl Trait for &[u8] {}
impl<T: Trait + ?Sized> Trait for &mut T {}

fn takes_trait(rdr: impl Trait) {}

fn main() {
    let mut arr = [0, 1, 2, 3];
    
    // currently
    takes_trait(&mut &arr[..]);
    
    // with `.as_slice()` its nice and clear
    takes_trait(&mut arr.as_slice());
    
    // can't use deref coercion in this case
    takes_trait(&mut &arr);
    //          ^^^^^^^^^ the trait `Trait` is not implemented for `&[u8; 4]`
}
```

**Comment by rossmacarthur** [comment]
With regards to stabilization I think `as_slice`, `as_mut_slice` could be stabilized first.

I think they are much more useful than the others in this tracking issue. These are already common methods for existing data types so it's not a new API.

I sometimes find myself running into cases where `Deref` coercion doesn't work and I need this. Currently I'm using `&arr[..]` which doesn't really communicate well why it is needed.

For example

```rust
// io::Read does something like this
trait Trait {}
impl Trait for &[u8] {}
impl<T: Trait + ?Sized> Trait for &mut T {}

fn takes_trait(t: impl Trait) {}

fn main() {
    let mut arr = [0, 1, 2, 3];
    
    // currently
    takes_trait(&mut &arr[..]);
    
    // with `.as_slice()` its nice and clear
    takes_trait(&mut arr.as_slice());
    
    // can't use deref coercion in this case
    takes_trait(&mut &arr);
    //          ^^^^^^^^^ the trait `Trait` is not implemented for `&[u8; 4]`
}
```

**Comment by LukasKalbertodt** [comment]
I agree with @rossmacarthur and would like to propose stabilizing `as_slice` and `as_mut_slice`. These methods exist on many other types throughout `std` (e.g. `Vec`) and I can't think of a reason to wait with stabilization. I can't see how the name or semantics would still change. And I'm pretty sure we want those methods.

**Comment by yoshuawuyts** [comment]
I used `array::each_mut` to pin project an array today:

```rust
pub(crate) fn pin_project_array<T, const N: usize>(slice: Pin<&mut [T; N]>) -> [Pin<&mut T>; N] {
    // Safety: `std` _could_ make this unsound if it were to decide Pin's
    // invariants aren't required to transmit through arrays. Otherwise this has
    // the same safety as a normal field pin projection.
    unsafe { slice.get_unchecked_mut() }
        .each_mut()
        .map(|t| unsafe { Pin::new_unchecked(t) })
}
```
This allowed keeping the `const N: usize` parameter intact through the projection, which is useful when mixing const generics and manually authored futures.

**Comment by e2-71828** [comment]
I recently found myself wanting `each_mut` and `each_ref` in a project targetting the stable compiler, so I wrote these functions as a workaround while waiting for them to stabilize:

```
/// Polyfill for array::each_ref
fn array_of_refs<T, const N:usize>(arr: &[T;N])->[&T;N] {
    use core::mem::MaybeUninit;
    let mut out:MaybeUninit<[&T;N]> = MaybeUninit::uninit();
    
    let buf = out.as_mut_ptr() as *mut &T;
    let mut refs = arr.into_iter();
    
    for i in 0..N {
        unsafe { buf.offset(i as isize).write(refs.next().unwrap()) }
    }
    
    unsafe { out.assume_init() }
}

/// Polyfill for array::each_mut
fn array_of_mut<T, const N:usize>(arr: &mut [T;N])->[&mut T;N] {
    use core::mem::MaybeUninit;
    let mut out:MaybeUninit<[&mut T;N]> = MaybeUninit::uninit();
    
    let buf = out.as_mut_ptr() as *mut &mut T;
    let mut refs = arr.into_iter();
    
    for i in 0..N {
        unsafe { buf.offset(i as isize).write(refs.next().unwrap()) }
    }
    
    unsafe { out.assume_init() }
}
```

**Comment by LukasKalbertodt** [comment]
Maybe it's time to stabilize `each_ref` and `each_mut`? They were added 1.5 years ago. And the only open question is regarding the name, as far as I know. See [the PR](https://github.com/rust-lang/rust/pull/75490) for more information about the name, but in short, the alternatives that were mentioned:

- `as_[ref/mut]_array` ([from arraytools](https://docs.rs/arraytools/0.1.5/arraytools/trait.ArrayTools.html#method.as_mut_array))
- `as_[ref/mut]_elements`
- `as_refs`/`as_mut_refs`
- `each_as_[ref/mut]`

I don't really have any opinion about naming. I think all of them would be totally fine, including the current one. So I wouldn't want to block stabilizing these clearly useful methods on the name.

Any opinions?

**Comment by e2-71828** [comment]
From my perspective, stabilizing these with any name is better than leaving them on stable.  All of the proposed names have some flaws:
* `as_ref_array` implies a return type of `&[T;N]` instead of the actual `[&T;N]`
* `as_ref_elements` doesn't match anything else in `std`
* `as_refs` can be visually confused with `as_ref`
* `each_as_ref` implies that the method will take a closure as an argument

Looking elsewhere in `std`, we have:
* `Cell::as_slice_of_cells`, which suggests `as_array_of_ref` and `as_array_of_mut`
* `Iterator::by_[ref/mut]`, which could be adopted as `array::by_ref` and `array::by_mut`

**Comment by jplatte** [comment]
> Looking elsewhere in `std`, we have:
> 
> * `Cell::as_slice_of_cells`, which suggests `as_array_of_ref` and `as_array_of_mut`
> * `Iterator::by_[ref/mut]`, which could be adopted as `array::by_ref` and `array::by_mut`

FWIW, I prefer either of these new ones over the previous suggestions.

**Comment by LukasKalbertodt** [comment]
FWIW, I do *not* prefer them (`as_array_of_[ref/mut]` and `by_[ref/mut]`) over the current name :D 
The first one is long and doesn't really add clarity IMO. `as_array_of_refs` (with plural S) would be better regarding clarity, but brings problems for `mut`. And `by_ref` (from `iterator`) is short, but `Iterator::by_ref` has distinctly different semantics compared to these array methods.

What are the problems with the current names anyway? What are we looking to improve? If someone could spell that out, that would probably help this discussion.

**Comment by jplatte** [comment]
Hm, I didn't think too much about it when posting the last reply. I guess you're right about `Iterator::as_ref` and the longer names are.. Longer. The current solution definitely isn't bad!

**Comment by Aaron1011** [comment]
Are there any further objects over the current names, or are these ready to stabilize?

**Comment by Zenithsiz** [comment]
Can these be made `const fn`s? Or are we still missing features to allow these to become `const fn`s?

**Comment by xfix** [comment]
> Can these be made `const fn`s? Or are we still missing features to allow these to become `const fn`s?

Technically `each_ref` can be made a `const fn` (it can be implemented on stable), however it would require complicating the method noticeably, and that probably wouldn't be worth it at this point.

For instance, with [`array_macro` crate](https://docs.rs/array-macro/latest/array_macro/), it's possible to implement it like this:

```rust
const fn each_ref<T, const N: usize>(arr: &[T; N]) -> [&T; N] {
    array![i => &arr[i]; N]
}
```

**Comment by dead-claudia** [comment]
Curious why provide `each_ref` and `each_mut` methods, and not just providing by-ref equivalents to all 4 of the `self`-consuming array methods.

- `.map(self, f)` -> `.map_ref(&self, f)`, `.map_mut(&mut self, f)`
- `.try_map(self, f)` -> `.try_map_ref(&self, f)`, `.try_map_mut(&mut self, f)`
- `.zip(self, other)` -> `.zip_ref(&self, &other)`/`.zip_mut(&mut self, &mut other)`
- `.transpose(self)` -> `.transpose_ref(&self)`/`.transpose_mut(&mut self)`

This would avoid intermediate arrays of almost-always-pointless references, would save a method call in almost all cases, and likely be easier to optimize for. Also, `.transpose_{ref,mut}` has direct precedent elsewhere - all the `assume_init` methods for `MaybeUninit` also carry `*_ref` and `*_mut` variants.

**Comment by workingjubilee** [comment]
Noteworthy: `zip_array` was also recalled for generating intermediate references.

**Comment by pierzchalski** [comment]
@LukasKalbertodt Is there anything specific blocking stabilization of `each_ref` and `each_mut`? I notice we haven't gotten consensus on the names, but also no one seems to have a _very_ strong opinion afaics?

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

```rust
impl [T; N] {
    pub fn each_ref(&self) -> [&T; N];
    pub fn each_mut(&mut self) -> [&mut T; N];
}
```

I suggested this naming in https://github.com/rust-lang/rust/pull/75490#pullrequestreview-509675856 and provided further rationale for it in https://github.com/rust-lang/rust/pull/75490#pullrequestreview-564927613. I continue to think these are good names. The naming discussion above has reached a stopping point without any traction behind any better set of names, in my opinion.

Aside from naming, a point to consider was whether these functions are amenable enough to optimization. See https://github.com/rust-lang/rust/issues/76118#issuecomment-1521041215 with a response in https://github.com/rust-lang/rust/issues/76118#issuecomment-1684047417.

In https://github.com/rust-lang/rust/issues/80094#issuecomment-1466881799 we removed `pub fn zip<U>(self, [U; N]) -> [(T, U); N]` because `[(T, U); N]` is not the end product anyone wanted; it would always have been followed up with a `map` in practice, suggesting some kind of iterator-based zip and chunk/collect would be more suitable.

Is `[&T; N]` / `[&mut T; N]` a different situation? Currently the documentation identifies only `map` as the motivation.

```rust
let strings = ["Ferris".to_string(), "♥".to_string(), "Rust".to_string()];
let is_ascii = strings.each_ref().map(|s| s.is_ascii());
assert_eq!(is_ascii, [true, false, true]);

// We can still access the original array: it has not been moved.
```

But notice that `&[&T]` is a construct that is relatively more common in APIs than `[(T, U); N]`, so at least `each_ref` might find a use there. Stuff like:

https://github.com/rust-lang/rust/blob/d7229c479c5f330aac55f009892f82916057cf0a/compiler/rustc_lint/src/context.rs#L209

https://github.com/rust-lang/rust/blob/d7229c479c5f330aac55f009892f82916057cf0a/compiler/rustc_codegen_llvm/src/builder.rs#L224

https://github.com/rust-lang/rust/blob/d7229c479c5f330aac55f009892f82916057cf0a/compiler/rustc_codegen_llvm/src/common.rs#L97

Alternatives: something like `strings.iter().map(|s| s.is_ascii()).array_chunks::<3>().next().unwrap()`.

**Comment by pravic** [comment]
Any news about this?
