### ISSUE TITLE
Stabilize enum `is_variant` methods as const

### ISSUE THREAD

**Issue by CDirkx** [rust-lang/rust#76225]
Recently const control flow was stabilized, which enables a lot of methods within the standard library to be made stable const; specifically all of the enum `is_variant` methods:

- `Option`: `is_some` and `is_none`
- `Result`: `is_ok` and `is_err`
- `Poll`: `is_ready` and `is_pending`
- `Cow`: `is_borrowed` and `is_owned` (methods themselves are unstable)
- `IpAddr`: `is_ipv4` and `is_ipv6`
- `std::path::Prefix`: `is_verbatim`

This issue aims to collect discussion about the stabilization of these methods, due to their similarities and trivial implementations.

## Stabilization
- [x] `Option`: stabilized in [PR#76135 ](https://github.com/rust-lang/rust/pull/76135 ) (note: also contains `as_ref`)
- [x] `Result`: stabilized in [PR#76136](https://github.com/rust-lang/rust/pull/76136) (note: also contains `as_ref`)
- [x] `Poll` stabilized in [PR#76227](https://github.com/rust-lang/rust/pull/76227)
- [x] `Cow`: methods made const in [PR#76139](https://github.com/rust-lang/rust/pull/76139), the methods themselves are still unstable under `cow_is_borrowed`
- [x] `IpAddr`: stabilized in [PR#76226](https://github.com/rust-lang/rust/pull/76226)
- [ ] `Prefix`: stabilization proposed in [PR#76232](https://github.com/rust-lang/rust/pull/76232), but there is not enough motivation to stabilize this method on its own

**Comment by CDirkx** [comment]
These were all the instances of enums with `is_variant` methods I could find in the standard library. 

PRs opened for all of them, @ecstatic-morse

**Comment by CDirkx** [comment]
Closing as all `is_variant` methods have been stabilized as const, with the exception of `Prefix` which on its own doesn't seem worth it.
