### ISSUE TITLE
Tracking Issue for slice_check_range

### ISSUE THREAD

**Issue by dylni** [rust-lang/rust#76393]
The feature gate for the issue is `#![feature(slice_check_range)]`.

This issue currently tracks the following API:

```rust
impl<T> [T] {
    pub fn check_range<R: RangeBounds<usize>>(&self, range: R) -> Range<usize>;
}
```

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the feature (#75207)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

None so far

### Implementation history

- Implemented in #75207

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/rust/pull/76662 the type of this function changed, so the issue description should likely be adjusted -- unless you want to provide the old one as a convenience wrapper? I think that would be a bad idea though. The function's docs clearly position it as something used in unsafe code, and in unsafe code I'd rather not make people create slices when all they need is to compute their length. As #75207 showed, often creating those slices is not correct.

**Comment by RalfJung** [comment]
Alternatively, maybe it would make more sense to make this a method on `RangeBounds`?

**Comment by dylni** [comment]
Well, the reason for me choosing to define it on a slice is that (I think) it's not possible to create a slice of length `usize::MAX` without a custom allocator. Thus, panicking for an inclusive `usize::MAX` index is reasonable. I didn't want this method to cause developers to always ignore `..=usize::MAX`, even though I don't know why you'd need a range that large.

Outside the standard library, wouldn't `&[MaybeUninit]` be necessary to create an uninitialized slice anyway?

**Comment by RalfJung** [comment]
> Well, the reason I chose to define it on a slice is that (I think) it's not possible to create a slice of length usize::MAX without a custom allocator.

It is possible though: `&[(); usize::MAX]`.

> Outside the standard library, wouldn't &[MaybeUninit] be necessary to create an uninitialized slice anyway?

This applies inside and outside the standard library. The alternative is a raw slice, `*const [T]`

**Comment by dylni** [comment]
> It is possible though: `&[(); usize::MAX]`.

Right, that's what I was missing.

> This applies inside and outside the standard library. The alternative is a raw slice, `*const [T]`.

I agree the API change makes sense now. Thanks for the explanations!

I also fixed the code sample in this issue.

**Comment by dylni** [comment]
> Alternatively, maybe it would make more sense to make this a method on `RangeBounds`?

Now that it doesn't need a slice, I think this might be better. I'll think about it and likely create a PR to move it.

**Comment by dylni** [comment]
@RalfJung

> Alternatively, maybe it would make more sense to make this a method on `RangeBounds`?

Is this possible? I don't think provided methods can restrict the trait's type parameter at all, but `Add` and `PartialOrd` would be required at least.

**Comment by RalfJung** [comment]
> Is this possible? I don't think provided methods can restrict the trait's type parameter at all, but Add and PartialOrd would be required at least. It could be defined for (Bound<usize>, Bound<usize>), but that seems worse.

Hm, you could play with something like `fn provded(self) where Self: Bound`.

**Comment by dylni** [comment]
> Hm, you could play with something like `fn provided(self) where Self: Bound`.

Thanks. I'm not sure how I missed bounds on the method itself.

**Comment by scottmcm** [comment]
I think having the https://github.com/rust-lang/rust/pull/76885 version of this for precondition checking is great.

I'm dropping by from https://github.com/rust-lang/rust/pull/77480#issuecomment-703152193 to ponder whether there's other, more user-focused versions of this that could make sense too.  Spitballing: something on `SliceIndex` like `.check_index(x)` that could return `Result<Range<usize>, _>`, targeted more at users who want to check things before calling other methods than at people implementing APIs that take `RangeBounds`.

**Comment by dylni** [comment]
@scottmcm 

> Spitballing: something on `SliceIndex` like `.check_index(x)` that could return `Result<Range<usize>, _>`, targeted more at users who want to check things before calling other methods than at people implementing APIs that take `RangeBounds`.

The problem with adding it to `SliceIndex` is that there's no way to represent `usize` as `Range<usize>`, so users would end up going back to `RangeBounds` anyway. However, a non-panicking version of `assert_len` might be a good idea. I added it to the unresolved questions, but it can even be added after this method is stabilized.

**Comment by clarfonthey** [comment]
Note: I didn't even realise this method existed despite searching for it, and ended up adding an implementation of `SliceIndex` for `(Bound<usize>, Bound<usize>)`, which could potentially be a better way of doing this? Both could coexist but I haven't thought enough about how that would happen.

**Comment by dylni** [comment]
I thought about that. Also, this is the PR for anyone reading this issue: #81108

I think it depends on how you expect your impl to be used. Would it be used in a way this method would already cover? The advantage of this method is that it can be used when you don't have a slice: https://github.com/rust-lang/rust/blob/95cbcad920d602cb7319e819e7ebc3cf56c20cd7/library/alloc/src/collections/vec_deque/mod.rs#L1068

However, the design has changed a few times, so it's worth discussing what would be best.

**Comment by RalfJung** [comment]
IMO `assert_len` is not a great name, since it sounds like this is asserting the length *of the range*. It is impossible to tell what this function does without reading the docs. In this regardg, IMO it is worse than the previous `slice::check_bounds(len, range)`.

The `assert` in the name makes sense because it panics on OOB, but on the other hand usually `assert` functions don't return anything. This function does *both* an `assert` and actually converts the indices to `Range`, so that will be tricky to express.

**Comment by scottmcm** [comment]
Idea: it could take `RangeTo<usize>` to help clarify the meaning of the argument, without introducing overhead.

That would allow a call like `range.assert_subset_of(..self.len())`, pending bikeshedding.

**Comment by dylni** [comment]
> IMO `assert_len` is not a great name, since it sounds like this is asserting the length *of the range*.

Naming this method has [always been a problem](https://github.com/rust-lang/rust/pull/76885#pullrequestreview-491644624). That was simply the best name I found at the time, and I'd be in favor of changing it.

> That would allow a call like `range.assert_subset_of(..self.len())`, pending bikeshedding.

This is a great idea. To avoid confusion with other `assert_*` items, maybe `ensure_subset_of` would be better. I'll open a PR later with this new design to continue the discussion.

**Comment by dylni** [comment]
I created the PR: #81154

**Comment by bluss** [comment]
As @xfix detected in #81157, this method is mildly dangerous. The method cannot be trusted for asserting unsafe-critical invariants, because the trait is neither sealed nor an `unsafe trait`.

**Comment by dylni** [comment]
Thanks @bluss.

**Comment by jendrikw** [comment]
Could `slice::split_point_of` benefit from this?

**Comment by dylni** [comment]
@jendrikw Unfortunately, I doubt it. This function is used primarily to apply a length to a range. It returns the same range for `(Unbounded, Excluded(length))` and `(Included(0), Unbounded)`, for example.

**Comment by reitermarkus** [comment]
@dylni, given the implementation of `slice:range` hasn't changed in almost 4 years, is this ready to be stabilised?

**Comment by dylni** [comment]
@reitermarkus Personally, I no longer have a use for this method, so I cannot comment on if the current implementation is useful and makes sense. Do you have examples of this method providing benefit outside of libstd?

**Comment by reitermarkus** [comment]
I used it in `heapless` to implement `Vec::drain`, which basically mirrors the `std::Vec::drain` implementation: https://github.com/rust-embedded/heapless/pull/444

Stabilising would reduce the amount of code that needs to be duplicated, as is currently the case.

**Comment by jonhoo** [comment]
I've also had a use for it recently in an API that I would like to be able to take an argument of type `impl RangeBounds<usize>` (just like `Vec::drain`). Seems like this method is the (only?) way to turn `impl RangeBounds<usize>` into `Range<usize>` in `std`.

**Comment by clarfonthey** [comment]
Since so many people mentioned it, I opened #121148 to add `try_range`, which returns an `Option` instead of panicking. It just feels weird not having the pair together, and hopefully having both will make this more comfortable to stabilise.

**Comment by dylni** [comment]
@reitermarkus Would you be able to create the stabilization report? Unfortunately, as I no longer make use of the feature and am not familiar with the stabilization process, I may not have the time to devote for a while. If not, I will look to create one once as soon as I have the opportunity.

**Comment by Dylan-DPC** [comment]
> `@reitermarkus` Would you be able to create the stabilization report? Unfortunately, as I no longer make use of the feature and am not familiar with the stabilization process, I may not have the time to devote for a while. If not, I will look to create one once as soon as I have the opportunity.

we just added a new function which isn't merged yet and is tied to the same tracking issue, so we need to spend some time for it to »bake« if we plan on stabilising this all together. We could move it to a different feature gate, but for a small feature like this, I'm not sure that's a good idea. 

it's fine if you can't write the stabilisation report. The person who opens the tracking issue isn't obliged to write the stabilisation report, so once we give enough time for this, I will try and look towards writing the stabilisation report for it

**Comment by dtolnay** [comment]
#95274 added `#[must_use]` to this function, which seems potentially overbearing to me. Is `#[must_use]` a net benefit for `slice::range`? Or would it be common to call only for the bounds checking/panic side effect?

Of course for `slice::try_range` a `#[must_use]` is appropriate because that one has no side effect.

**Comment by dtolnay** [comment]
Good call. Now `must_use` makes sense to me. Thank you!

I searched GitHub for "start <= end &&" and there are a few hits that might be able to correctly use `slice::range` without using the return value, in code that does not involve `impl RangeBounds`:

- https://github.com/SpectralSequences/sseq/blob/946d52eda4cc8728da2173eceec74124a1398244/ext/crates/fp/src/vector/impl_slicep.rs#L72
- https://github.com/loro-dev/loro/blob/a47cf06712f6992f7f3de43be00c19fe522acd64/crates/loro-internal/src/container/richtext/tinyvec.rs#L155

but arguably those are APIs that would be better redesigned to use `impl RangeBounds` instead of `start: usize, end: usize`, and if not, writing `slice::range(start..end, ..self.len);` is not a definite improvement over the assert they currently have.

If someone wants to extend the documentation of `slice::range` to point out why the return value can be necessary for soundness in the situation of an untrusted RangeBounds impl, https://github.com/rust-lang/rust/issues/81138 has an example of a real-world bug like that.

**Comment by thaliaarchi** [comment]
Recently, I wrote a function with a very similar purpose as `slice::range`, without realizing this feature existed. The difference is that mine saturates instead of panicking, because it's intended to be used for slicing `&[T]` slices which cannot exceed `isize::MAX` anyways. That would bring minor performance benefits with less branching.

```rust
pub fn get(&self, range: impl RangeBounds<usize>) -> Self {
    let slice = self.as_slice();
    self.with_slice(&slice[normalize_range(range, slice.len())])
}

/// Normalizes any `RangeBounds<usize>` to a `Range<usize>` with upper bound
/// `len`. An inclusive start bound or exclusive end bound of `usize::MAX` is
/// saturated to `usize::MAX` to avoid overflow; when used to slice a collection
/// which has an upper bound of `isize::MXA` elements, it is guaranteed to be
/// out of bounds in either case.
#[inline]
fn normalize_range(range: impl RangeBounds<usize>, len: usize) -> Range<usize> {
    let start = match range.start_bound() {
        Bound::Included(&start) => start,
        Bound::Excluded(&start) => start.saturating_add(1),
        Bound::Unbounded => 0,
    };
    let end = match range.end_bound() {
        Bound::Included(&end) => end.saturating_add(1),
        Bound::Excluded(&end) => end,
        Bound::Unbounded => len,
    };
    start..end
}
```

**Comment by thaliaarchi** [comment]
I started drafting an example of how `slice::range` could be used unsoundly when the `RangeBounds<usize>` impl has interior mutability, but found it's actually more difficult than I thought, because `slice::range` takes the bounds by value and `SliceIndex<[T]>` is not implemented for `RangeBounds`. @scottmcm do you have a better example?

[[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=b81e86873239385d309e358eb7df6865)]

```rust
#![feature(slice_range)]
use std::cell::Cell;
use std::ops::{Bound, RangeBounds};
use std::slice;

struct BadBounds {
    end_bounds: [usize; 2],
    which: Cell<usize>,
}

impl RangeBounds<usize> for &BadBounds {
    fn start_bound(&self) -> Bound<&usize> {
        Bound::Unbounded
    }
    fn end_bound(&self) -> Bound<&usize> {
        let which = self.which.get();
        if which + 1 < self.end_bounds.len() {
            self.which.set(which + 1);
        }
        Bound::Excluded(&self.end_bounds[which])
    }
}

fn main() {
    let range = BadBounds {
        end_bounds: [0, 10],
        which: Cell::new(0),
    };
    let x = [1, 2, 3];
    let _ = slice::range(&range, ..x.len());
    // SAFETY: This is unsound, because the bounds could change.
    let _y = unsafe {
        x.get_unchecked((
            (&range).start_bound().cloned(),
            (&range).end_bound().cloned(),
        ))
    };
}
```

**Comment by netsutetsu** [comment]
It looks that `try_range` function is almost a duplicate of `range` function but erases information about errors. I think, as initially considered, `try_range` function should return `Result` instead of `Option` and replace `range` function. Under this change, if `range(range, bounds)` is rewritten to `range(range, bounds).unwrap()` and `try_range(range, bounds)` is rewritten to `range(range, bounds).ok()`, there should be no loss of functionality.
