### ISSUE TITLE
Tracking Issue for `#[cfg(panic = "...")]`

### ISSUE THREAD

**Issue by davidhewitt** [rust-lang/rust#77443]
This is a tracking issue for the feature `cfg_panic`, introduced in PR #74754.
The feature gate for the issue is `#![feature(cfg_panic)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] ~~Implement the feature~~ (done in #74754).
- [x] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [x] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

None as yet.

### Implementation history

Introduced in #74754

**Comment by cchiw** [comment]
PRs opened to stabilize the feature

_Documentation PRs_
   - Reference [PR](https://github.com/rust-lang/reference/pull/1157)
   - Examples [PR](https://github.com/rust-lang/rust-by-example/pull/1500)
   - Book skipped due to feedback [issue](https://github.com/rust-lang/book/pull/3038)
 
_Stabilization PR_
   - Rust Compiler [PR](https://github.com/rust-lang/rust/pull/93658)

**Comment by jplatte** [comment]
Stabilization PR was merged, this can be closed AFAICT.

**Comment by davidhewitt** [comment]
Looks like docs PR not merged yet

**Comment by joshtriplett** [comment]
Stabilized in 1.60, closing.
