### ISSUE TITLE
Tracking Issue for Add `as_str` method to str split iterators

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#77998]
This is a tracking issue for the methods implemented in #75265, which allow viewing the remainder of the underlying string in str-split iterators. E.g.:

```rust
let mut split = "Mary had a little lamb".split(' '); 
assert_eq!(split.as_str(), "Mary had a little lamb");
split.next();
assert_eq!(split.as_str(), "had a little lamb");
split.by_ref().for_each(drop);
assert_eq!(split.as_str(), "");
```

The feature gates for the issue are `#![feature(str_split_as_str)]` (for most split iterators) and `#![feature(str_split_inclusive_as_str)]` (for `SplitInclusive`).

### Steps

- [x] Implement the feature (done in #75265)
- [x] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- Should empty strings point to the end of the haystack, or they can be arbitrary constants? (see https://github.com/rust-lang/rust/pull/75265#discussion_r487358752)

### Implementation history

- #75265 — implemented `as_str` methods on `core::str::{Split,RSplit,SplitN,RSplitN,SplitTerminator,RSplitTerminator,SplitInclusive}`

**Comment by SkiFire13** [comment]
Looking at its name it isn't immediately clear what it returns. Wouldn't `remainder` or something along that line be a more self-explanatory name?

**Comment by WaffleLapkin** [comment]
The name `as_str` was chosen to be in line with [`Chars::as_str`](https://doc.rust-lang.org/std/str/struct.Chars.html#method.as_str)

**Comment by TyPR124** [comment]
Can this be added to `SplitWhitespace` and `SplitAsciiWhitespace`?

**Comment by WaffleLapkin** [comment]
@TyPR124 as [noted](https://github.com/rust-lang/rust/pull/75265#issuecomment-715048698) in the implementation PR discussion it is possible, but not trivial.

Both `Split*Whitespace` are using [iterators internally](https://github.com/rust-lang/rust/blob/da5f7f10936198bad22c370118bad1ac332d2f46/library/core/src/str/iter.rs#L1136-L1161) which doesn't allow to access it's inner parts ([^1](https://github.com/rust-lang/rust/blob/da5f7f10936198bad22c370118bad1ac332d2f46/library/core/src/iter/adapters/map.rs#L60), [^2](https://github.com/rust-lang/rust/blob/master/library/core/src/iter/adapters/filter.rs#L16)). It's possible to 'solve' this problem either by making the fields `pub(crate::str::iter)` (tbh it's a hack) or providing methods on iterator adaptors that allow accessing inner iterators (downside: there are **lots** of adaptors to change).

I didn't want to complicate the original PR with this, so didn't include anything like this. I can now make a new PR that'll add the same methods to `Split*Whitespace`, thanks for reminding about it!

**Comment by WaffleLapkin** [comment]
Update: #82570 was merged, so now `SplitWhitespace` and `SplitAsciiWhitespace` has `as_str` method too!

**Comment by soerenmeier** [comment]
I just had a case we're i needed to split a str: `"tag:value"` into a `tag: &str` and a `value: Option<&str>`.
I know i can just use `Some(iter.as_str()).filter(str::is_empty)` to get the `Option`, but maybe there could be another method named `as_opt_str` or `remainder`. That method would return `None` if calling next would also return `None`.
What do you think?

**Comment by SkiFire13** [comment]
Note that split iterators could yield an empty str as their final item, so `as_opt_str` could return `Some("")` while your code with always filter that case.

**Comment by soerenmeier** [comment]
That's true, to be correct the above code should look like this:
```
let s = iter.as_str();
iter.next().map(|_| s)
```
Would be nice to have `as_opt_str`.

**Comment by m-ou-se** [comment]
> I just had a case we're i needed to split a str: `"tag:value"` into a `tag: &str` and a `value: Option<&str>`.

That sounds like a use case for the recently stabilized [`split_once`](https://doc.rust-lang.org/stable/std/primitive.str.html#method.split_once).

**Comment by m-ou-se** [comment]
I do think that returning an `Option<&str>` here might make more sense though. Right now there's no way to know if the `Split` is finished, or has just consumed a separator and will produce another `Some` (possibly a `Some("")`). Calling `.next()` for that is not great, because that will try to match against the splitter pattern again.

Maybe `.as_str() -> Option<&s>` or `.remaining() -> Option<&s>` or something would be better.

**Comment by WaffleLapkin** [comment]
> Maybe `.as_str() -> Option<&s>` or `.remaining() -> Option<&s>` or something would be better.

I could add this, seems reasonable. The only question is: do we want both `-> &str` and `-> Option<&str>`, or do we only want the latter one?

**Comment by m-ou-se** [comment]
I personally think we should only have the Option version. I'm worried the `-> &str` version leads to subtle bugs.

For example, I recently saw someone write this as an alternative for `split_once('=')`:

```rust
let mut split = "hello=world".split('=');
let (key, val) = (split.next()?, split.as_str());
```

However, the behaviour is subtly different: `"hello="` and `"hello"` both produce same `("hello", "")` output, whereas `split_once('=')` only accepts `"hello="` and returns `None` if the `=` is missing. With `Option<&str>` we force the user to handle that case.

**Comment by tbu-** [comment]
I find the `as_str` name unintuitive, choosing it for the sole reason of symmetry with `Chars::as_str` sounds bad to me.

**Comment by Piturnah** [comment]
What's the status wrt stabilisation?

**Comment by smarnach** [comment]
I noticed that `SplitWhitespace` has some counter-intuitive behaviour if tokens are separated by multiple whitespace characters. The `remainder()` method includes all but the first whitespace character in the returned string:

    let s = "foo \tbar";
    let mut it = s.split_whitespace();
    it.next().unwrap();
    assert_eq!(it.remainder(), Some("\tbar"));

This behaviour, if intended, should at least be documented.

**Comment by kornelski** [comment]
I needed a functionality of "split the string once on X or Y, whichever is first", and I need to know whether X or Y was first.

I hoped I could use `str.split(|c: char| c == X || c == Y)` and then inspect the `iter.remainder()` to see whether X or Y was there, but I was disappointed to learn that the `remainder` is *after* the next split, rather than immediately after the previously returned substring.

**Comment by lubomirkurcak** [comment]
Could this work with `peekable`?

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=73dea5523564c607bef9c4b3a93a2169

**Comment by camsteffen** [comment]
I think `as_str` would be a fine name - I personally just expected it to exist since I am familiar with `as_str` and `as_slice` on other iterators.

I feel like the Option may be overcomplicating it. I expected it to just return an empty string as in `&string[string.len()..] == ""`. I think the reasoning for Option doesn't apply for `split_inclusive()` at least, IIUC. Not having an Option would allow for simpler code if an empty string is not a special case.

**Comment by lo48576** [comment]
> I feel like the Option may be overcomplicating it. I expected it to just return an empty string as in `&string[string.len()..] == ""`. I think the reasoning for Option doesn't apply for `split_inclusive()` at least. Not having an Option would allow for simpler code when an empty string is not a special case.

I think returning None is more convenient. Assume you got the remainder as `iter.as_str()`.

* None to empty string: `iter.as_str().unwrap_or_default()`
* empty string to None: `Some(iter.as_str()).filter(|s| !s.is_empty())`
* (identity conversion: `iter.as_str()`)

I don't remember if there is simpler or shorter way of doing `Some(val).filter(pred)` without binding to a variable, but from this comparison I think returning `Option<&str>` from the method is more generic and straightforward to use in any situation.

**Comment by sumitpsm** [comment]
Here, is another use case of `remainder` function:
I am trying to implement a `Scanner`
```rs
pub struct Scanner<R> {
    reader: R,
    buffer: Vec<u8>,
    iter: std::str::SplitAsciiWhitespace<'static>,
}

impl<R: std::io::BufRead> Scanner<R> {
    pub fn new(reader: R) -> Self {
        Self {
            reader,
            buffer: vec![],
            iter: "".split_ascii_whitespace(),
        }
    }

    pub fn next<T: std::str::FromStr>(&mut self) -> T {
        loop {
            if let Some(token) = self.iter.next() {
                return unsafe { token.parse().unwrap_unchecked() };
            }
            self.buffer.clear();
            self.reader.read_until(b'\n', &mut self.buffer).unwrap();
            self.iter = unsafe {
                let slice = std::str::from_utf8_unchecked(&self.buffer);
                std::mem::transmute(slice.split_ascii_whitespace())
            }
        }
    }

    pub fn next_line<T: std::str::FromStr>(&mut self) -> T {
        if self.iter.nth(0).is_none() {
            self.buffer.clear();
            self.reader.read_until(b'\n', &mut self.buffer).unwrap();
        }
        self.iter = "".split_ascii_whitespace();
        let result = std::mem::take(&mut self.buffer);
        unsafe {
            let s = std::str::from_utf8_unchecked(&result);
            s.trim().parse().unwrap_unchecked()
        }
    }
}
```
here `remainder` function will boil down the code for the `next_line` function in few lines

**Comment by cramertj** [comment]
I have a use case for this where I want to split a file into a header and a footer, where the end of the header is determined by seeing a line that matches some predicate. I don't particularly care whether the remainder is empty or not, so in this case the `Option` would be mapped to a an empty string.

**Comment by sffc** [comment]
I've landed on this issue multiple times after looking for a function like `split_once_inclusive`.
