### ISSUE TITLE
Tracking Issue for VecDeque binary search functions

### ISSUE THREAD

**Issue by vojtechkral** [rust-lang/rust#78021]
Feature gate: `#![feature(vecdeque_binary_search)]`

This is a tracking issue for  `VecDeque::binary_search{,_by,_by_key}()`, formerly RFC rust-lang/rfcs#2997

### Public API

```rust
// alloc::collections::vec_deque

impl<T> VecDeque<T> {
    pub fn binary_search(&self, x: &T) -> Result<usize, usize>
    where
        T: Ord;

    pub fn binary_search_by<'a, F>(&'a self, f: F) -> Result<usize, usize>
    where
        F: FnMut(&'a T) -> Ordering;

    pub fn binary_search_by_key<'a, B, F>(&'a self, b: &B, f: F) -> Result<usize, usize>
    where
        F: FnMut(&'a T) -> B,
        B: Ord;

    pub fn partition_point<P>(&self, mut pred: P) -> usize
    where
        P: FnMut(&T) -> bool;
}
```

### Steps / History

- [x] Implementation: #77751
- [x] Final commenting period (FCP)
- [x] Stabilization PR: #83362

### Unresolved Questions

- [x] Stop at `Equal` like we do for `[]`? https://github.com/rust-lang/rust/issues/78021#issuecomment-805118750
- [x] Add `partition_point` too, just like `[]` has?

**Comment by m-ou-se** [comment]
We recently changed `slice::binary_search_by` to stop directly at `Ordering::Equal`, and added `slice::partition_point` for a binary search that only considers less and greater than. Maybe we should do the same for `VecDeque`.

**Comment by vojtechkral** [comment]
@m-ou-se Okay, I can do that...

**Comment by vojtechkral** [comment]
@m-ou-se Added the quick return for `Ordering::Equal`, but I'm not sure about `partition_point()`. Do you think that's useful for a `VecDeque` too? I'm not sure...

**Comment by m-ou-se** [comment]
>  I added the quick return for Ordering::Equal (locally in my branch so far)

Feel free to send that as a PR and assign me with `r? @m-ou-se`.

> I'm not sure about `partition_point()`. Do you think that's useful for a `VecDeque` too?

I don't have a very strong opinion on that. I think it might be useful, but I'd be fine with starting the FCP for just the three `VecDeque::binary_search*` functions.

**Comment by vojtechkral** [comment]
Sorry about the radio silence, I've added `partition_point()` as well, will create the PR tomorrow...

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by JohnTitor** [comment]
It has been stabilized (#83362), closing.
