### ISSUE TITLE
Tracking Issue for `panic_any`

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#78500]
Feature gate: `#![feature(panic_any)]`

This is a tracking issue for `std::panic::panic_any`, a function to allow panicking with any value.

### Context

Right now, it is possible to panic (that is, `std::panic!`) on any value: `panic!(123)`. This will be disallowed in Rust 2021, when `panic!(..)` will always take a format string just like `println!(..)`. At that point, this function will be the only way to panic without a (format) string. (See https://github.com/rust-lang/rust/issues/80162 and https://github.com/rust-lang/rfcs/pull/3007.)

### Public API

```rust
mod std::panic {

    /// Panic the current thread with the given message as the panic payload.
    ///
    /// The message can be of any (`Any + Send`) type, not just strings.
    ///
    /// The message is wrapped in a `Box<'static + Any + Send>`, which can be
    /// accessed later using [`PanicInfo::payload`].
    ///
    /// See the [`panic!`] macro for more information about panicking.
    pub fn panic_any<M: Any + Send>(msg: M) -> !;

}
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/74622
- [x] Final commenting period (FCP)
- [x] Stabilization PR: https://github.com/rust-lang/rust/pull/81194

### Unresolved Questions

- None yet.

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by sfackler** [comment]
It seems like the function signature is missing a `'static` bound?

**Comment by m-ou-se** [comment]
> It seems like the function signature is missing a `'static` bound?

`Any: 'static` already requires that. I can add it in the stabilization PR to make it explicit.

**Comment by sfackler** [comment]
Oh right, I think I asked this same question when this function was added! Yeah, might be best to add the duplicate bound in.

**Comment by KodrAus** [comment]
Now that this is stable I'll go ahead and close this tracking issue. Please feel free to re-open if we'd like to keep it around until `1.51.0` actually ships!
