### ISSUE TITLE
Tracking Issue for #![feature(async_stream)]

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#79024]
This is a tracking issue for the RFC "2996" (rust-lang/rfcs#2996).
The feature gate for the issue is `#![feature(async_stream)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC (cc @rust-lang/XXX -- can anyone write up mentoring
      instructions?)
- [x] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions
None currently

### Implementation history
- [PR instroducing `core::stream::{Stream, Next}`](https://github.com/rust-lang/rust/pull/79023)

**Comment by kaimast** [comment]
Is there a plan to include a `core::stream::StreamExt` (similar to the one in the futures crate) as well?

**Comment by yoshuawuyts** [comment]
> 
> 
> Is there a plan to include a `core::stream::StreamExt` (similar to the one in the futures crate) as well?

The plan is to add methods directly onto `Stream` much like methods exist on `Iterator`, but we want to do so in a way that won't cause ambiguities with ecosystem-defined methods in order to not accidentally break existing codebases when upgrading to newer Rust versions.

**Comment by joshtriplett** [comment]
Some [discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async-foundations/topic/renaming.20stream.20to.20async.20iterator) raised the question of naming. With full acknowledgement to the fact that the name `Stream` has a long history in the async ecosystem, multiple people observed that something like `AsyncIterator` or similar might be much more evocative for new users. Such a name would allow people to map their existing understanding of iterators. "I understand `Iterator`, and I understand async, and this is an async version of `Iterator`".

**Comment by brainstorm** [comment]
As a new, inexperienced user, I find `AsyncIterator` way more foreign than `Stream`, to be honest... perhaps I'm not too involved in compiler discussions and I don't see how the jargon clicks together though :-S

**Comment by yoshuawuyts** [comment]
Prior art on "iterator" and "async iterator" naming schemes in other languages:

- JavaScript: [`Symbol.Iterator`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator), [`Symbol.AsyncIterator`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/asyncIterator)
- C#: [`IEnumerable`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ienumerable-1?view=net-5.0), [`IAsyncEnumerable`](https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8)
- Python: [`__iter__`](https://wiki.python.org/moin/Iterator), [`__aiter__`](https://www.python.org/dev/peps/pep-0525/)
- Swift: [`Sequence`](https://developer.apple.com/documentation/swift/sequence), [`AsyncSequence`](https://github.com/apple/swift-evolution/blob/main/proposals/0298-asyncsequence.md)

**Comment by ibraheemdev** [comment]
> Restore `Stream::next`. This was removed from the RFC because it prevents dynamic dispatch, and subsequently removed from the implementation. This should be resolved before stabilizing.

Does `where Self: Sized` as in the iterator methods not resolve this issue?

**Comment by bbros-dev** [comment]
Context: We're prototyping some simple CLI app functionality.  We're following the mini-redis example code where we can.

We've bumped out head on streams, and the need for the crates async-streams, and parallel-streams.

In our experience some `*Iterator` terminology would have helped clarify what streams are.

Given the need for the crates we cited, especially the async-streams RFC, we wonder if there isn't a need for:

* `Iterator`
* `ConcurrentIterator`
* `ParallelIterator`

Or is the intention that async-stream and parallel-stream crate efforts all able to converge into a `stream` that covers the concurrent and parallel use cases?

**Comment by benkay86** [comment]
[Rayon](https://docs.rs/rayon) provides a whole ecosystem of parallel iterators on top of a work-stealing threadpool, and is currently the _de facto_ Rust standard for parallel iteration.  But I don't foresee a parallel iterator trait getting into the Rust standard library anytime soon.

Streams are supposed to cover the use case of concurrent iterators only (per my understanding).  Hopefully once streams are stabilized into the Rust standard library we can have some syntax to use them in concurrent for loops just like we currently use synchronous iterators in for loops.  However, there are still some issues to work out like what to do if a a stream panics or is dropped.  Settling on a name (Stream vs AsyncIterator vs ConcurrentIterator) will be the easy part! :stuck_out_tongue_winking_eye:

Unfortunately, it's difficult to combine parallel and concurrent iteration at the moment.  This would require Rayon to support a way to move tasks from worker threads to an async executor thread, or for an async executor like Tokio to support parallel thread pools in a more sophisticated way than `tokio::task::spawn_blocking()`.  Until that happens, most programmers try to get all their data into memory first on a concurrent executor-driven threadpool and then offload the synchronous computation to a parallel threadpool (e.g. managed by Rayon).

**Comment by yoshuawuyts** [comment]
> multiple people observed that something like `AsyncIterator` or similar might be much more evocative for new users. Such a name would allow people to map their existing understanding of iterators. "I understand `Iterator`, and I understand async, and this is an async version of `Iterator`".

I've filed a PR to the RFCs repo, updating the "streams" terminology to "async iterator" instead: https://github.com/rust-lang/rfcs/pull/3208.

**Comment by noelzubin** [comment]
why did `.next` make it. where can i get more info on this ?

**Comment by clarfonthey** [comment]
One potential concern re: methods on `AsyncIterator`, which is less of a concern and more of a justification for requiring them, is methods that use internal versus external iteration.

For example, it can be very efficient to perform a `fold` on an iterator which is composed of several `chain`s, but it can be much less efficient to directly call `next` on said iterators.

My concern is that without parity between the methods on `Iterator` and `AsyncIterator`, much of these optimisations that already exist for `Iterator` will be lost in the conversion to `AsyncIterator`. Since, as it stands, there's not really a way to run a `for_each` or `fold` on a regular iterator if the loop contains async operations.

I know for a fact that the current async ecosystem with `futures::stream::Stream` does *not* have parity with `Iterator`, with some notable surprises including the fact that `try_fold` requires the iterator item to also be composed of results, rather than just the return type of the function.

It would be extremely detrimental to the idea that "this is just the async version of an iterator" if there weren't parity there IMHO, since users might notice slowdowns in code that simply calls `std::async_iter::from_iter` without adding any extra async code at all.

**Comment by yoshuawuyts** [comment]
@clarfonthey yes, definitely. The concerns you raise are valid, and the working group is currently actively investigating how we can ensure parity between sync and async Rust APIs. We don't yet (but should) have guidelines on how methods on async traits should be translated from sync to async, but that likely needs us to land async closures / async traits first.

**Comment by joshtriplett** [comment]
Given the current trend of the async working group, I wouldn't be surprised if this can become `async fn next` rather than `fn poll_next`.

**Comment by withoutboats** [comment]
(NOT A CONTRIBUTION)

> Given the current trend of the async working group, I wouldn't be surprised if this can become async fn next rather than fn poll_next.

> ah yes, that's definitely something we've been discussing within the working group, and we're currently working towards enabling that.

I think this is not the right direction for this feature. AsyncIterator::poll_next enables library authors to write explicit, low-level async iteration primitives for unsafe optimizations. Relying on the compiler generated futures of an async function will make the layout of these types much less predictable or controllable and will take this away from users.

For ease of use where this fine-grained laying control is not desirable, generators are the play (async or otherwise), rather than having to write next methods (async or otherwise) at all.

You need to have the low level APIs (poll, next and poll_next) for hand-rolled optimized code that the compiler can't be relied on to generate. You need to have the high level syntax (async functions, generators, and async generators) for when people just want to get things done and don't care about these kinds of optimizations. You need both. Async methods, next and an async next method would be doing each side of it only halfway, and would basically trapping Rust in a local maxima that looks appealing from where we are now but would not be the best final state.

**Comment by the8472** [comment]
@withoutboats for your [latest blog post](https://without.boats/blog/poll-progress/), can you give an approximate loop desugaring like in https://github.com/rust-lang/rust/pull/118847#issue-2036784747
I'm not sure if I'm parsing the ascii charts properly.

Anyway, I'm reraising a concern here that I already [mentioned in the PR](https://github.com/rust-lang/rust/pull/118847#issuecomment-1851720014) and that's similar to [clarfonthey's](https://github.com/rust-lang/rust/issues/79024#issuecomment-1049559009):

I think the current proposed interface is terrible for performance when iterating on small types (e.g. `u8`s) because the `poll_next` interface returns a `Poll<Option<Item>>` that conveys two states at the same time, readiness and end-of-iteration.
If the loop body contains no await points, just munching some bytes for example, then that loop body would ideally optimize to a single [induction variable](https://en.wikipedia.org/wiki/Induction_variable) based on `next`'s internals. I.e. just a branch of "do we still have more data to process".
Only when reaching the end of available data it should poll. This also requires a separation of progress information and getting the next item(s), but it goes in a different direction than boat's proposal.

One option is to make `poll_next` not-async (basically just `next`) but only return items when the iterator has made progress, which would be polled by a separate method. `poll_progress` would then return a `Poll<bool>` I guess to indicate more items / end of iteration.

Another approach is returning an `I where I: IntoIterator<IntoIter=IN>, IN: ExactSizeIterator` from `poll_next`. `Option` fulfills these bounds *but* an async iter that has an internal buffer can instead choose to return some iterable with more than one item, which allows the loop body to process them on a single induction variable of that iterable without polling.

**Comment by jmjoy** [comment]
> Given the current trend of the async working group, I wouldn't be surprised if this can become `async fn next` rather than `fn poll_next`.

After rust 1.75 released, trait async func is stable, `async fn next` is more user friendly.

**Comment by tesaguri** [comment]
> > Given the current trend of the async working group, I wouldn't be surprised if this can become `async fn next` rather than `fn poll_next`.
> 
> 
> 
> After rust 1.75 released, trait async func is stable, `async fn next` is more user friendly.

In the rest of the thread, withoutboats has argued that we need async generators for ergonomics, rather than `async fn next()`, which is less fine-grained than `fn poll_next()` and less ergonomic than async generators in their opinion. Then, what is your rationale for promoting `async fn next()` over async generators?

**Comment by RalfJung** [comment]
Looking at this through the lens of algebraic effects, I would say that
- `Future` corresponds to a (suspended ongoing invocation of a) function that can trigger the "pending" effect. The effect has argument and return type `()` (and eventually the function returns `Future::Output`).
- `Iterator` corresponds to a (suspended ongoing invocation of a) function that can trigger the "yield" effect. The effect has argument type `Iterator::Item` and return type `()` (and eventually the function returns `()`).

This analogy is not quite perfect: futures can be polled again after returning "ready" (and similar for iterators); futures have this "context" argument; iterators are not pinned. But I would argue all of those are concessions to how we model these kinds of computations in Rust -- the abstract concept we want to model doesn't have them, but the imperfect realization of that concept in Rust does have them.

An `AsyncIterator` would then be a (suspended ongoing invocation of a) function that can trigger *both* the "pending" and the "yield" effect, with the same types as above (and eventually the function returns `()`).

We don't have algebraic effects in Rust, but futures have shown how we can model one particular algebraic effect. If we follow that same paradigm, then the `fn poll_next`-based encoding seems to be the most direct way to represent an `AyncIterator`.

In contrast, the `async fn next`-based encoding seems to model something different: it represents a function that can trigger a "yield" effect, where the argument type of this effect (i.e., the data being passed from the function to the handler) is a function that can trigger a "pending" effect. If we view an async iterator as triggering a sequence of yield and pending, then this does seem equal in abstract expressivity to `fn poll_next` (split up the sequence after each yield, to obtain a sequence of subsequences; then each of these subsequences corresponds to one of the functions that is being yielded). However, it is a much less direct encoding of what actually happens, involving a seemingly unnecessary "thunk" (the functions being yielded). Sure, in trivial cases this can be optimized away, but I wouldn't bet much on the claim that such optimizations will always work. It certainly does not seem to fit the usual Rust philosophy of avoiding unnecessary overhead in the most basic abstractions.

So I guess what I am saying is, I tend to agree with boats. Mind you, I'm not an expert in async, I am taking a 10,000 foot view of this problem.

**Comment by bionicles** [comment]
speaking of https://doc.rust-lang.org/nightly/std/async_iter/index.html#laziness --- can the basic async iterator has a usage example? right now these docs show how to define the counter and implement the async iterator trait, but not how to actually invoke it or use it as an end user. 

is this because to run this async iterator we need externals like tokio? if so, how do we ensure std has what it needs to run async iterators without needing an external runtime 

here's the part i mean, the code isn't really showing what to do with the counter, so it's hard to look at this page of rustdoc and know fully how to get rolling with a minimalist async iterator, which tbh is likely to be much more rewarding for all of us than futures, just a hunch, async iterators are the move, because they promote categorical thinking

![image](https://github.com/rust-lang/rust/assets/24532336/c90e4302-12d0-4f8f-ad48-f3d4dddddd50)

**Comment by traviscross** [comment]
@rustbot labels -I-libs-api-nominated +T-lang +WG-async

This was discussed briefly in the libs-api call today.  This work is going to be driven from the lang side on the basis of work done in WG-async, as we had discussed in the meeting on 2024-05-14.  On that basis, the decision was to unnominate.

**Comment by RalfJung** [comment]
> meeting on 2024-05-14

Where can I find the minutes of that meeting? In the t-lang/meetings Zulip channel, I can only find the meeting on meeting on 2024-05-15, but that was about a different topic (match ergonomics).

**Comment by YuhanLiin** [comment]
One thing from Yosh's blog post that hasn't been mentioned here is that `poll_next()` and `async fn next()` have slightly different semantics, in that `poll_next()` requires the iterator to be pinned while `async fn next()` doesn't. Can't say for sure which one is better. I've never actually had to move an iterator after calling `next()` on it, but maybe that's a legitimate use case.

Another thing is that there's a lot of comparisons being made about the performance of `poll_next()` versus `async fn next()`. The easiest way to resolve this would be to implement an async iterator using both APIs, iterate over them using whatever `for` loop desugaring we're planning to ship, and compare the compiled assembly/LLVM IR. We should do this for non-trivial iterators and also mix in some combinators. Specifically, we can compare the compiled output of:
```rust
fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<T>> {
    // Do something
    // Return Poll<Option<T>>
}
```
with the output of:
```rust
async fn next(&mut self) -> Option<T> {
    future::poll_fn(|cx| /* -> Poll<Option<T>> */ {
        // Do something
        // Return Poll<Option<T>>
    }).await
}
```
Since `future::poll_fn` allows async functions to "drop down" to lower level polling operations, we can put (mostly) the same code in the bodies of both implementations so that they perform the same operations, leading to a fair comparison. As a bonus, this experiment can also discover perf issues with the loop desugaring and combinator implementations.

**Comment by conradludgate** [comment]
> poll_next() requires the iterator to be pinned while async fn next() doesn't

This makes poll_next more powerful. A Stream like <https://docs.rs/tokio-util/latest/tokio_util/codec/struct.FramedRead.html> currently works with any `! Unpin` AsyncRead type. If we moved to `async fn next()`, the AsyncRead would need to be Unpin.

Similar story is for <https://docs.rs/futures-concurrency/latest/futures_concurrency/stream/trait.Merge.html> which would now need to cache the futures of each `async fn next()`. Since they are all `!Unpin`, Merge is now forced to box these next futures

**Comment by YuhanLiin** [comment]
> Similar story is for https://docs.rs/futures-concurrency/latest/futures_concurrency/stream/trait.Merge.html which would now need to cache the futures of each async fn next(). Since they are all !Unpin, Merge is now forced to box these next futures

The main issue here is that with `poll_next()`, the iterator itself must contain the async state machine. Whereas with `async fn next()`, the async state machine is transiently created by the iterator. Self-contained state machines are much easier to cache and poll in an arbitrary order, which is what `Merge` does. Managing transient state machines created by async functions is a pain point of async traits in general.

Now that I think about it, the current version of `AsyncIterator`/`Stream` is just a future that you can keep polling after returning `Poll::Ready`. If we ship the current iteration, we should definitely also have async generators that make them easier to implement, similar to async functions.

**Comment by yoshuawuyts** [comment]
> Similar story is for https://docs.rs/futures-concurrency/latest/futures_concurrency/stream/trait.Merge.html which would now need to cache the futures of each `async fn next()`. Since they are all `!Unpin`, Merge is now forced to box these next futures

I would be hesitant to take this as an inherent constraint. I'm fairly certain that with unsafe binders we can formulate an implementation of `Merge` based on `async fn next` which does not require any allocations. We'll need to play around a little with the traits and bounds, but I believe it should be possible.

Unsafe binders are going to be a great help for async traits regardless of their shape. They are the same feature required to e.g. make `fn poll_next` work with async closures, which is something we need for example for `AsyncIterator::filter`.

**Comment by YuhanLiin** [comment]
If we use `async fn next`, `Merge` will have to store the futures generated by each call to `next`. That means `Merge` will need to be pinned. I don't see how unsafe lifetime binders can get rid of the pinning requirement. The example of unsafe binders from the design doc also uses `Pin<&mut Self>`.

**Comment by yoshuawuyts** [comment]
I didn't say anything about not needing to pin, I said it shouldn't be necessary to allocate.

**Comment by conradludgate** [comment]
Right. I suggested box-pinning because at present the `async fn next(&mut self)` does not present a pinning interface. That is unless we expect to implement
```rust
impl AsyncIterator for Pin<&mut Merge<...>> { ... }
```

otherwise we'd need to instead offer

```rust
trait AsyncIterator {
    async fn next(self: Pin<&mut Self>) -> Option<Self::Item>;
}
```

**Comment by 21aslade** [comment]
I've been thinking about this problem a bit lately, and I think I have an objection to `async fn next` that I haven't seen raised before. There are some very basic uses of `async gen fn` that I don't think `async fn next` can accommodate:
```rs
async gen fn shared_state() yield i32 {
    let reused = foo().await;
    yield bar(reused).await;
    yield baz(reused).await;
}
```
I can't imagine how that could possibly compile with `async fn next`: `reused` must be part of the *iterator*'s state machine to be used on later iterations, but the iterator's state machine *can't contain anything that requires await*. It can't be part of the transient future's state machine, cause there's no way for the future's state machine to communicate back to the iterator's state machine. I can't see a way around that.

This is a direct consequence of Ralph Jung's observation that `poll_next` is the correct effect-based equivalent to `async gen`. An `async gen fn` is a function that can yield items **and also** await futures, not one who yields items that can then be awaited. Or, put another way, we shouldn't think of `AsyncIterator` as adding the `async` effect to `Iterator`, we should think of it as adding the `async` and `gen` effects to `FnMut` (except that it's pinned, so `FnPin`).

I'm not an async Rust expert, so I could be wrong. But it seems like from both a theoretical and practical view, `poll_next` is the correct signature. It's less ergonomic in the short term than `async fn next`, but WAY more expressive, and essentially necessary for `async gen` to be useful.

**Comment by traviscross** [comment]
Tracking issues aren't meant for discussion of this kind.  From above:

> A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.

If you want to discuss this generally, probably the right thing to do would be to open a thread in Zulip under `#wg-async`.

**Comment by Kek5chen** [comment]
Just to get an idea on the scale of this and to see if I understood correctly:

Is this going to be the foundation for any async implementations of the current iterators on - for example - containers?

As I see, completion of this, should uncover a next step in the roadmap to implement things like `Vec<T: Send + 'static>::iter_async()::map(A).await` where map takes an async closure.

Is this also planned?

Unrelated to this trait specifically but this would throw up a question on if an async version of `Option::map` also has rights to exist as it's fundamentally the same idea of asynchronously mapping.

**Comment by ghost** [comment]
Could we add asynchronous [`DoubleEndedIterator`](https://doc.rust-lang.org/std/iter/trait.DoubleEndedIterator.html) too?

**Comment by oconnor663** [comment]
After the [_Futurelock_](https://rfd.shared.oxide.computer/rfd/0609) post came out in January, I went down kind of a rabbit hole collecting related deadlocks. The end result was another post: https://jacko.io/snooze.html. Several of the examples in there are related to streams. I came out wondering whether the `Stream`/`AsyncIterator` trait might need to change in a couple of ways to protect callers from these issues. Here's a condensed summary of the two categories of problems I'm worried about.

The first problem is "buffered" streams, that is `FuturesOrdered`/`FuturesUnordered` and the helper methods that wrap them. These are deadlock-prone if the futures they're buffering hold any locks across await points. For example ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=19e5bc9c2992d4445f2aaef31827ba84)):

```rust
async fn foo() {
    static LOCK: Mutex<()> = Mutex::const_new(());
    let _guard = LOCK.lock().await;
    sleep(Duration::from_millis(10)).await;
}

#[tokio::main]
async fn main() {
    futures::stream::iter([foo(), foo()])
        .buffered(2)
        .for_each(async |_| {
            foo().await; // Deadlock!
        })
        .await;
}
```

To make this work reliably in the presence of async locking, I think the stream returned by `.buffered(_)` needs to expose something like @withoutboats' [`poll_progress`](https://without.boats/blog/poll-progress/) method, and the `for_each` future (and in general any stream combinator) needs to be honor-bound to call it. This would be an expansion of the basic "contract" for streams, in addition to the trait API.

The second problem is related to the `.next()` method on any stream, not just buffered ones. Consider this example, using the same `foo` function from above ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=53f5bc1bb31742cc39671965bcfa0c01)):

```rust
#[tokio::main]
async fn main() {
    let mut stream = pin!(stream::once(foo()));
    _ = timeout(Duration::from_millis(5), stream.next()).await;
    foo().await; // Deadlock!
}
```

The problem there is that if `.next()` is cancelled, it can suspend a stream (and any futures it might contain) at potentially any `.await` point, not necessarily a well-behaved "yield point" where suspension is expected. Unless `.next()` is paired with some sort of "uncancellable futures" feature, I worry this makes it too error-prone to recommend for general use. I realize that's a radical thing to suggest, but maybe most existing callers of `.next()` could be replaced with `for await`, or in general any helper that takes _ownership_ of the stream. (`for await` would also presumably participate in any sort of `poll_progress` solution to the first problem.)

If these problems are worth a discussion, maybe I should open a separate issue thread, but I wanted to at least mention them here at the top level.

Edit: Examples with `Mutex` and `sleep` can feel too contrived, so here's [a more "natural" example with `OnceCell` and `reqwest`][reqwest] and here's [one with a bounded channel and no cancellation][channel].

Edit again: I opened [a thread on the wg-async Zulip][zulip], which is a better place for discussion than this tracking issue.

Edit August: I'm working on [a draft RFC for this](https://github.com/oconnor663/rfcs/blob/poll_progress/text/0000-poll-progress.md).

[reqwest]: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&code=use+futures%3A%3A%7BStreamExt%2C+stream%7D%3B%0Ause+std%3A%3Apin%3A%3Apin%3B%0Ause+tokio%3A%3Async%3A%3AOnceCell%3B%0Ause+tokio%3A%3Atime%3A%3A%7BDuration%2C+timeout%7D%3B%0A%0A%2F%2F%2F+Fetch+some+Zen+wisdom+from+the+GitHub+API.+This+makes+a+network%0A%2F%2F%2F+request+the+first+time+and+caches+the+result.%0Aasync+fn+zen_wisdom%28%29+-%3E+%26%27static+str+%7B%0A++++static+ZEN%3A+OnceCell%3CString%3E+%3D+OnceCell%3A%3Aconst_new%28%29%3B%0A++++ZEN.get_or_init%28async+%7C%7C+%7B%0A++++++++let+url+%3D+%22https%3A%2F%2Fapi.github.com%2Fzen%22%3B%0A++++++++reqwest%3A%3Aget%28url%29.await.unwrap%28%29.text%28%29.await.unwrap%28%29%0A++++%7D%29%0A++++.await%0A%7D%0A%0A%23%5Btokio%3A%3Amain%5D%0Aasync+fn+main%28%29+%7B%0A++++%2F%2F+Put+some+Zen+wisdom+in+a+stream.%0A++++let+mut+zen_stream+%3D+pin%21%28stream%3A%3Aonce%28zen_wisdom%28%29%29%29%3B%0A++++%2F%2F+Start+reading+it%2C+but+cancel+the+read+with+a+tight+timeout.%0A++++_+%3D+timeout%28Duration%3A%3Afrom_millis%281%29%2C+zen_stream.next%28%29%29.await%3B%0A++++%2F%2F+Now+the+stream+is+%22snoozed%22%2C+but+it%27s+still+holding+the+%60ZEN%60%0A++++%2F%2F+lock.+Calling+%60zen_wisdom%60+again+is+a+deadlock.%0A++++println%21%28%22We+make+it+here...%22%29%3B%0A++++zen_wisdom%28%29.await%3B%0A++++println%21%28%22...but+not+here.%22%29%3B%0A%7D>

[channel]: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&code=use+futures%3A%3A%7BStreamExt%2C+stream%7D%3B%0Ause+std%3A%3Async%3A%3ALazyLock%3B%0Ause+tokio%3A%3Async%3A%3Ampsc%3A%3A%7BSender%2C+channel%7D%3B%0A%0A%2F%2F+The+sleeps+in+this+example+make+it+deadlock+immediately+and+in+a+predictable%0A%2F%2F+way.+You+can+comment+out+the+sleeps+and+still+get+deadlocks%2C+but+you+might%0A%2F%2F+need+to+run+it+5-10+times%2C+and+the+behavior+is+more+complicated.%0Ause+tokio%3A%3Atime%3A%3A%7BDuration%2C+sleep%7D%3B%0A%0Astatic+LOG_BUFFER_SIZE%3A+usize+%3D+10%3B%0Astatic+STREAM_BUFFER_SIZE%3A+usize+%3D+20%3B%0A%0Aasync+fn+log%28i%3A+usize%29+%7B%0A++++%2F%2F+The+first+time+log%28%29+is+called%2C+is+opens+a+bounded+channel+for+sending%0A++++%2F%2F+logs+%28here+just+ints%29+and+spawns+a+background+task+to+print+them.%0A++++static+LOG_SENDER%3A+LazyLock%3CSender%3Cusize%3E%3E+%3D+LazyLock%3A%3Anew%28%7C%7C+%7B%0A++++++++let+%28sender%2C+mut+receiver%29+%3D+channel%28LOG_BUFFER_SIZE%29%3B%0A++++++++tokio%3A%3Aspawn%28async+move+%7B%0A++++++++++++%2F%2F+Briefly+delay+starting+the+background+reader%2C+as+a+hack+to+let%0A++++++++++++%2F%2F+the+channel+buffer+fill+up.%0A++++++++++++sleep%28Duration%3A%3Afrom_millis%2810%29%29.await%3B%0A++++++++++++while+let+Some%28i%29+%3D+receiver.recv%28%29.await+%7B%0A++++++++++++++++println%21%28%22log%3A+%7Bi%7D%22%29%3B%0A++++++++++++%7D%0A++++++++%7D%29%3B%0A++++++++sender%0A++++%7D%29%3B%0A++++LOG_SENDER.send%28i%29.await.unwrap%28%29%3B%0A++++%2F%2F+Briefly+sleep+after+each+channel+write%2C+as+a+hack+to+get+all+the+buffered%0A++++%2F%2F+futures+below+in-flight+at+the+same+time.%0A++++sleep%28Duration%3A%3Afrom_millis%281%29%29.await%3B%0A%7D%0A%0A%23%5Btokio%3A%3Amain%5D%0Aasync+fn+main%28%29+%7B%0A++++stream%3A%3Aiter%280..STREAM_BUFFER_SIZE%29%0A++++++++.map%28log%29%0A++++++++.buffered%28STREAM_BUFFER_SIZE%29%0A++++++++.for_each%28async+%7C_%7C+%7B%0A++++++++++++println%21%28%22We+make+it+here...%22%29%3B%0A++++++++++++%2F%2F+Deadlock%21+By+the+time+we+get+here%2C+there+are+10+writes+in+the%0A++++++++++++%2F%2F+channel+buffer+and+also+10+log%28%29+futures+in+the+stream+buffer%0A++++++++++++%2F%2F+waiting+to+write.+The+following+log%28%29+%22gets+in+line%22+behind+those%0A++++++++++++%2F%2F+10+futures%2C+but+then+we+never+poll+them+again%2C+even+after+the%0A++++++++++++%2F%2F+reader+task+wakes+up+and+starts+clearing+the+channel+buffer.%0A++++++++++++log%2842%29.await%3B%0A++++++++++++println%21%28%22...but+not+here.%22%29%3B%0A++++++++%7D%29%0A++++++++.await%3B%0A%7D>

[zulip]: https://rust-lang.zulipchat.com/#narrow/channel/187312-wg-async/topic/.60AsyncIterator.60.20deadlocks.20that.20suggest.20design.20changes/near/597365155

**Comment by jonhoo** [comment]
The things we're running into here also bear some resemblance to [`DirectService` in `tower`](https://github.com/tower-rs/tower/pull/118) from way back in the day. The discussion around its introduction and [its eventual abandonment](https://github.com/tower-rs/tower/issues/136) may also be of use here, even if it's not _quite_ the same.
