### ISSUE TITLE
Tracking Issue for bufwriter_raw_buffer

### ISSUE THREAD

**Issue by tgnottingham** [rust-lang/rust#79916]
This feature adds methods to `BufWriter` that enable raw access and manipulation of the underlying buffer. In particular, it adds methods analogous to the following raw buffer methods available on `Vec`: `as_ptr`, `as_mut_ptr`, `len`, and `set_len`. The names of these methods on `BufWriter` may differ.

The feature gate for the issue is `#![feature(bufwriter_raw_buffer)]`.

See #79921 for implementation and discussion.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the feature (in progress at #79921)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

**Comment by tgnottingham** [comment]
@rfcbot label T-libs F-bufwriter_raw_buffer

**Comment by tgnottingham** [comment]
I've worked around my need for this API by essentially implementing my own `BufWriter` (see #80463). Closing this, as I don't have a strong enough desire to push for it, and I'm not certain it's worth the trade-off of adding to the API surface.
