### ISSUE TITLE
Tracking Issue for maybe_uninit_write_slice

### ISSUE THREAD

**Issue by beepster4096** [rust-lang/rust#79995]
Feature gate: `#![feature(maybe_uninit_write_slice)]`

This is a tracking issue for `MaybeUninit::copy_from_slice` and `MaybeUninit::clone_from_slice`.

These methods are the equivalents of `[T]::copy_from_slice` and `[T]::clone_from_slice` for uninitialized slices.

### Public API

```rust
impl<T> [MaybeUninit<T>] {
    pub fn write_copy_of_slice(&mut self, src: &[T]) -> &mut [T]
    where
        T: Copy;

    pub fn write_clone_of_slice(&mut self, src: &[T]) -> &mut [T]
    where
        T: Clone;
}
```

### Steps / History

- [x] Implementation: #79607
- [x] Make slice methods inherent: https://github.com/rust-lang/rust/pull/129259
- [ ] Stabilization PR

### Unresolved Questions

- [ ] Should the name be changed back to `copy/clone_from_slice`?
  - [Reasoning for the original name](https://github.com/rust-lang/rust/pull/79607#pullrequestreview-542275599) and rust-lang/libs-team#122
  - Changed to `copy_from_slice` and `clone_from_slice` in #116385
  - Changed again to `write_copy_of_slice` and `write_clone_of_slice` in https://github.com/rust-lang/rust/pull/129259
- [ ] https://github.com/rust-lang/rust/issues/80376

**Comment by DrMeepster** [comment]
will this work or will someone else need to do it for me :thinking:

@rustbot modify labels: C-tracking-issue, T-libs, A-raw-pointers

**Comment by Thomasdezeeuw** [comment]
These functions are great additions to the `MaybeUninit` API.

But if may open the bikeshed, should be renamed to `copy_slice` and `clone_slice` to more closely match what the functions are actually doing? The current names are a little confusing/misleading. For example let's look at a similarly named function: `MaybeUninit::write`, it takes ownership of the value it writes and moves the value into the `MaybeUninit`. However `write_slice` and `write_slice_cloned` don't do this as they copy/clone, so I think the "write" terminology can be a bit misleading.

**Comment by SimonSapin** [comment]
> These methods are the equivalents of `[T]::copy_from_slice` and `[T]::clone_from_slice` for uninitialized slices.

This seems like a great reason to name these methods `MaybeUninit::copy_from_slice` and `MaybeUninit::clone_from_slice`

**Comment by veber-alex** [comment]
is it possible to add this as methods on `impl [MaybeUninit<T>]` ?

**Comment by s1ck** [comment]
@DrMeepster what are the plans on getting this stabilized?

**Comment by Noah-Kennedy** [comment]
I'm pretty interested in seeing this stabilized as well.

**Comment by Kixunil** [comment]
I think it just needs an ACP and approval.

**Comment by SUPERCILEX** [comment]
Regarding the naming, I also think they should be called `{copy,clone}_from_slice` for consistency and ease of finding. The [original reasoning](https://github.com/rust-lang/rust/pull/79607#pullrequestreview-542275599) for their current name is to indicate that the cloned values will NOT be dropped. However, I'd argue most people don't even realize that value replacement causes the old values to be dropped (I know I didn't until I thought about it). If you think about it for a bit it's obvious, but I don't think people associate "clone_from_slice" with "old stuff dropped". Instead, I think the docs can be a bit louder about the fact that old data won't be dropped.

**Comment by bend-n** [comment]
> These methods are the equivalents of [T]::copy_from_slice and [T]::clone_from_slice for uninitialized slices.

Then why is the api so different?

**Comment by clarfonthey** [comment]
As of #129259 these are now:

```rust
impl<T> [MaybeUninit<T>] {
    pub fn write_copy_of_slice(&mut self, value: &[T]) -> &mut [T] where T: Copy;
    pub fn write_clone_of_slice(&mut self, value: &[T]) -> &mut [T] where T: Clone;
}
```

Worth updating the description for this.

**Comment by thaliaarchi** [comment]
Now that these methods are inherent, it seems like the design has settled and would be ready to stabilize. I believe this design also satisfies the unresolved question on naming, because `write_{copy,clone}_of_slice` avoids the name conflict with `<[T]>::{copy,clone}_from_slice` and parallels the similar `MaybeUninit::write` API.

Could we start an FCP?

**Comment by the8472** [comment]
@rust-rfcbot merge

@rfcbot merge

**Comment by rust-rfcbot** [comment]
:bell: **This is now entering its final comment period**, as per the [review above](https://github.com/rust-lang/rust/issues/79995#issuecomment-3427267604). :bell:

**Comment by thaliaarchi** [comment]
I've opened stabilization PR https://github.com/rust-lang/rust/pull/148048, so people can look at it while the FCP is going.

Note that I also chose to const-stabilize `<[MaybeUninit<_>]>::write_copy_of_slice`. That method depends on `<[_]>::copy_from_slice`, which is already const-stable, and the unstable `<[MaybeUninit<_>]>::assume_init_mut`, which is just casts.

**Comment by bend-n** [comment]
does anyone use `write_clone_of_slice`? i feel `write_copy_of_slice` is usually what makes sense. anyhow, couldn't one could simply not return `&mut [T]`? i dont know how useful the return is. and im not sure what you mean by taking `self`, as self is `[MU<T>]`?

**Comment by bend-n** [comment]
what, but then the function would have to be implemented on arrays?

**Comment by hkBst** [comment]
> Why is it relevant to return a pair `([T], [MaybeUninit<T>])`? It writes via copy/clone to the entire slice, so the uninit remainder will always be empty.

I hadn't noticed that these panic when given different length slices. I do wonder at this choice, since the length of the slices can always be easily adjusted to be equal. It **does not give any guarantees that the whole underlying uninit slice was initialized** though, **just the uninit subslice that was passed to these methods**.

And would a const generic solution (like `array_assume_init`) not be able to lift this panic to compile time?

> Re leaking: `MaybeUninit` is like `ManuallyDrop`, so people should just be aware of this when using it. I don't think this blocks anything. [`MaybeUninit::write`](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#method.write) documents:

I think there is a big difference in having an uninit array with an inited subslice (not necessarily including the start of the array), which is what these functions give you, and a single uninit value that has been inited but still needs to be `assume_init`ed.
