### ISSUE TITLE
Tracking Issue for RFC 3007: Making core and std's panic identical in Rust 2021

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#80162]
This is a tracking issue for RFC 3007 "Plan to make core and std's panic identical": https://github.com/rust-lang/rfcs/pull/3007

### Steps

- [x] Add a lint for format strings incompatible with the edition change: https://github.com/rust-lang/rust/pull/78088
- [x] Add `std::panic::panic_any`: https://github.com/rust-lang/rust/pull/74622
- [x] Stabilize `std::panic::panic_any`: Tracking issue #78500, PR #81194
- [x] Add a lint for panicking on non-string-literals (and suggest `panic_any`): #81645
- [x] Update `panic!()` documentation about non-string-literals: Part of #81645
- [x] Throw a `&str` instead of a `String` in `std` when using `core::panic!`: https://github.com/rust-lang/rust/pull/78119
- [x] Fix hygiene in `todo!()`, `assert_eq!()`, etc. to always use `core::panic!()`: https://github.com/rust-lang/rust/pull/78343
- [x] Fix `assert!(expr, message)` to call `core`'s panic mechanism directly: Part of https://github.com/rust-lang/rust/pull/78088
- [x] Fix `assert!(expr)` to call `core`'s panic mechanism directly in edition 2021: #80855
- [x] Make `{std, core}::panic!(..)` always use `format_args!(..)` in edition 2021: #80851
  - [x] This needs #80850.
- [x] Make `std::panic!(..)` an alias for `core::panic!(..)` in edition 2021: ~~#80879~~ Included in #80851.
  - [x] ~~This requires #80846 to be fixed first~~
- [x] Update `panic_fmt` lint to mention edition 2021: Part of #81645
- [x] Fix 2021's `assert!(123, "{}")` expanding to the wrong edition of `panic!()`: #81647

**Comment by rodrimati1992** [comment]
I'm a little confused about what's supported.

Do the changes here allow you to panic in `#![no_std]` crates with a non-literal `&'static str` constant at compile-time?

I made the `const_format` crate to allow me to do formatting at compile-time before the standard library can do it, and need to be able to panic with a non-literal `&'static str` to have my own static assertion macros.

**Comment by m-ou-se** [comment]
@rodrimati1992 Panicking at compile is unstable, both before and after these changes. The current unstable implementation of `const_panic` will not work right away with the new 2021 version of `panic!()`, as `panic!(SOME_CONST)` is no longer accepted. The 2021 version of the `panic!()` macro will accept the exact same arguments as the `println!()` macro. That is, the first argument must be a format string as string literal.

Options for panicking at compile time with a non-literal string message in Rust 2021:
- Use [`core::panicking::panic`](https://doc.rust-lang.org/stable/core/panicking/fn.panic.html) instead of the `panic!()` macro (which is unstable, but so is `const_panic`) or
- Extend `const_panic` to understand at least `panic!("{}", SOME_CONSTANT)`, or
- Implement https://github.com/rust-lang/rust/issues/78356.

**Comment by m-ou-se** [comment]
@rodrimati1992 By the way, note that `core::panic!(SOME_CONST)` in `const_panic` in the current editions [was fixed](https://github.com/rust-lang/rust/pull/78069) and works now. Also, if your crate uses edition 2018 and has a macro that expands to `panic!(..)`, it would always be the 2018 version of `panic!()`, even if the crate that uses your macro is a 2021 crate.

**Comment by m-ou-se** [comment]
Done!

# :tada:

**Comment by djugei** [comment]
bit of a late commer, seeing that this rfc has already been accepted, but:
defining shared error messages now results in a warning, i.e.:

    const ERR_ALPHA: &'static str = "alpha error";
    panic!(ERR_ALPHA);

this can be easily resolved in user code by writing

    panic!("{}", ERR_ALPHA};

but no actual formatting is needed, i just want to push a string literal to stderr. this especially means that i would like to avoid pulling in the format machinery if at all possible, because it has a noticeable impact on binary size.

**Comment by m-ou-se** [comment]
@djugei https://github.com/rust-lang/rust/issues/78356 would help with that. Ideally, `format_args!("{}", ERR_ALPHA)` results in the same trivial `fmt::Arguments` as `format_args!("alpha error")` with a `.as_str()` returning `Some("alpha error")` to avoid any formatting.

Depending on how far away we think that is, we could consider stabilizing [`panic_str`](https://doc.rust-lang.org/stable/core/panicking/fn.panic_str.html) in the meantime.

**Comment by djugei** [comment]
Ah, thanks i had not found panic_str (hidden under 2 layers of nightly), im ok with using nightly for now. Some const evaluation of format args could be cool though.
