### ISSUE TITLE
Tracking Issue for `const_refs_to_cell`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#80384]
This is a tracking issue for taking references to values of types that (may) contain `UnsafeCell` within const contexts.
The feature gate for the issue is `#![feature(const_refs_to_cell)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps
- [x] Implement the RFC (#80418)
- [ ] Adjust documentation: https://github.com/rust-lang/reference/pull/1590
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/129195

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved questions

* The feature gate permits `const BAR: AtomicUsize = ..; static FOO: &AtomicUsize = &BAR;` and only prevents `const FOO: &AtomicUsize = &BAR;`. This decision was made because the implementation is simpler this way and we would already allow the `static FOO` case if `BAR` were a static itself.
    * This could be problematic, because LLVM ends up deduplicating some unnamed allocations like the one in `static FOO`
* ~~The soundness of this feature depends on the fact that if a `StorageDead` exists for a local, then for every assignment to the local, on each pass from that assignment to any `return`, there will be a `StorageDead` for this local.~~
* Once we get heap allocations in constants, it would be possible for users to write a `const fn foo() -> &'static Cell<i32>`, which could then be used to initialize a `const FOO: &'static Cell<i32>` which is unsound (and only caught by dynamic checks). The tracking issue for const heap is #79597 

### Implementation history

* #80418

**Comment by kupiakos** [comment]
Does this need to apply to raw references/`ptr::addr_of!`? Given only a `*const UnsafeCell<T>`, there in not yet a stable way to mutate the referent:

```rust
#![feature(const_refs_to_cell)]

use core::cell::UnsafeCell;
use core::ptr;

fn main() {
    const _: i32 = {
        let x = UnsafeCell::new(5i32);
        let p: *const UnsafeCell<i32> = ptr::addr_of!(x);

        unsafe {
            // No stable way to mutate `p`

            // Requires const_mut_refs
            // *(p as *mut i32) = 10

            // Requires const_ptr_write
            // (p as *mut i32).write(10)

            // Requires const_intrinsic_copy, which just left FCP
            // ptr::copy(&10, p as *mut i32, 1);

            *(p as *const i32)
        }
    };
}
```

**Comment by RalfJung** [comment]
I would be rather nervous about relying on roundabout arguments like this -- that's the kind of reasoning which quickly leads to accidental stabilization.

For some motivation why we care about this feature, see https://github.com/Gilnaa/memoffset/issues/4#issuecomment-1069658383.

**Comment by kupiakos** [comment]
Do you suspect `const_mut_ref` would stabilize before this?

This limitation would be much less frustrating if it didn't trigger when taking the address of _any_ generic `T`, even where I have full certainty that the input cannot contains `UnsafeCell`. If I could bound on `Freeze` to communicate this impossibility this would solve the problem (and plenty of other soundness bounds I run into). Is there any way to do so?

I'm trying to read a generic integer's bytes without mutation and am prevented from doing so on the impossible possibility that an interior mutable type is used. Fortunately it can be gotten around for now by passing in a reference to the `const fn`, but a `&u8` arg is a [questionable API surface](https://twitter.com/david_koloski/status/1501690905002229764/photo/1). For context, I'm attempting to create a stable, generic, [`const`-compatible checked integer cast](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ed05d627cad8b4d1983e909d60e3ed46), but this is the last blocker for an ergonomic API.

**Comment by RalfJung** [comment]
Status update: const_mut_refs will hopefully to be stabilized [soon](https://github.com/rust-lang/rust/pull/129195). However, I think I'd prefer to wait a bit whether there are any issues showing up there before we also allow references to interior mutable types. In particular, the "safety net" described in https://github.com/rust-lang/rust/pull/129195 doesn't work as well for shared references due to https://github.com/rust-lang/rust/issues/121610 and https://github.com/rust-lang/unsafe-code-guidelines/issues/493. Therefore, I'd like to increase our confidence in the static checks before stabilizing something without a solid safety net.

See [here](https://rust-lang.zulipchat.com/#narrow/stream/189540-t-compiler.2Fwg-mir-opt/topic/Determining.20whether.20a.20local.20has.20a.20StorageDead.20before.20the.20end) for a Zulip discussion about what it would take to make sure that when we are allowing references to interior mutable data, that data is indeed "transient" and does not escape the initializer expression.
