### ISSUE TITLE
Tracking Issue for const_intrinsic_copy

### ISSUE THREAD

**Issue by usbalbin** [rust-lang/rust#80697]
Feature gate: `#![feature(const_intrinsic_copy)]`

This is a tracking issue for making the functions `ptr::copy` and `ptr::copy_nonoverlapping` as well as some related functions `const fn`.

### Public API

```rust
mod ptr {
    pub const unsafe fn copy_nonoverlapping<T>(src: *const T, dst: *mut T, count: usize);
    pub const unsafe fn copy<T>(src: *const T, dst: *mut T, count: usize);
}

impl *const T {
    pub const unsafe fn copy_to(self, dest: *mut T, count: usize);
    pub const unsafe fn copy_to_nonoverlapping(self, dest: *mut T, count: usize);
}

impl *mut T {
    pub const unsafe fn copy_to(self, dest: *mut T, count: usize);
    pub const unsafe fn copy_to_nonoverlapping(self, dest: *mut T, count: usize);

    pub const unsafe fn copy_from(self, src: *const T, count: usize);
    pub const unsafe fn copy_from_nonoverlapping(self, src: *const T, count: usize);
}
```

### Steps / History

- [x] Implementation of `ptr::copy` and `ptr::copy_nonoverlapping` as `const fn`: #79684 
  - [x] Link to this issue in feature gate: #80699
- [x] Also constify `copy_to`, `copy_from` and friends : #83091 
- [x] Final commenting period (FCP)
- [x] Stabilization PR: #97276
- [x] De-stabilization PR: https://github.com/rust-lang/rust/pull/117905
- [ ] TODO: new stabilization PR, once https://github.com/rust-lang/rust/issues/57349 is stable

**Comment by usbalbin** [comment]
@RalfJung with #81238 merged, is the concern about "bringing back debug assertions" resolved as - we won't bring them back?

**Comment by RalfJung** [comment]
Yeah I guess for now we won't bring them back.

**Comment by RalfJung** [comment]
This got partially reverted again by #86003, but hopefully we can re-land it soon.

**Comment by RalfJung** [comment]
Sorry, I misread, this feature gate is not affected (but some others are).

**Comment by joshtriplett** [comment]
Seems reasonable, assuming that @rust-lang/wg-const-eval is fine with it.

@rfcbot merge
@rfcbot concern confirm-with-wg-const-eval

**Comment by RalfJung** [comment]
Fine from my side -- these are all conceptually simple functions and their implementation has been battle-tested *a lot* in Miri.

**Comment by joshtriplett** [comment]
@rfcbot resolve confirm-with-wg-const-eval

**Comment by Dylan-DPC** [comment]
Opening since stablisation was reverted in https://github.com/rust-lang/rust/pull/117905

**Comment by RalfJung** [comment]
@rust-lang/libs-api with https://github.com/rust-lang/rust/pull/129195 being in FCP, I think we can move towards re-stabilizing these methods. Copying between raw pointers seems like basic functionality once mutable raw pointers are allowed, so would be nice to ship this all in the same release. Also, since these methods used to be stable, let's make them stable again as soon as we can. :)

Given that you have already approved this above, will this require another FCP or can we just go ahead and make a PR once https://github.com/rust-lang/rust/pull/129195 lands?

**Comment by dtolnay** [comment]
Like you said, this is already approved from our end. Feel free to make a re-stabilization PR after #129195. We can ping the team again on the PR but that should be enough notice.

**Comment by RalfJung** [comment]
Stabilization PR is up: https://github.com/rust-lang/rust/pull/130762

**Comment by tgross35** [comment]
For posterity: the `const`ness of some `NonNull`  methods were moved to this gate in https://github.com/rust-lang/rust/pull/124498, but the tracking issue didn't get updated. They got const stabilized as part of https://github.com/rust-lang/rust/pull/130762 (with libs-api signoff). Included:

```rust
impl <T> NonNull<T> {
    pub const unsafe fn copy_to(self, dest: NonNull<T>, count: usize);
    pub const unsafe fn copy_to_nonoverlapping(self, dest: NonNull<T>, count: usize);
    pub const unsafe fn copy_from(self, src: NonNull<T>, count: usize);
    pub const unsafe fn copy_from_nonoverlapping(self, src: NonNull<T>, count: usize);
}
```
