### ISSUE TITLE
Tracking Issue for maybe_uninit_array_assume_init

### ISSUE THREAD

**Issue by joboet** [rust-lang/rust#80908]
Feature gate: `#![feature(maybe_uninit_array_assume_init)]`

This is a tracking issue for `MaybeUninit::array_assume_init`.

### Public API

```rust
// core::mem::maybe_uninit

impl<T> MaybeUninit<T> {
    pub unsafe fn array_assume_init<const N: usize>(array: [Self; N]) -> [T; N];
}
```

### Steps / History

- [x] Implementation: #80600
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- [ ] Should this be a const function?
- [ ] Should this be a method of array?
- [ ] Should this method be replaced by a conversion method from `[MaybeUninit<T>; N]` to `MaybeUninit<[T; N]>` (see [comment](https://github.com/rust-lang/rust/issues/80908#issuecomment-953258213)).

**Comment by hellow554** [comment]
I think the question is, should this ever be stabilized? As you (?) wrote [in the docs](https://doc.rust-lang.org/nightly/core/mem/union.MaybeUninit.html#method.uninit_array):

> Note: in a future Rust version this method may become unnecessary when array literal syntax allows repeating const expressions. The example below could then use let mut buf = [MaybeUninit::<u8>::uninit(); 32];.

Maybe therefore this should stay an unstable option until (and later removed) until #49147 is stabilized?

**Comment by CoffeeBlend** [comment]
This is the wrong issue, it does not cover `MaybeUninit::uninit_array`, you're looking for #65580, which seems not to have a tracking issue. 

I do intend for this (`MaybeUninit::array_assume_init`) to become stable, even when mem::transmute supports const generics it is a handy abstraction.

**Comment by hellow554** [comment]
> This is the wrong issue, it does not cover MaybeUninit::uninit_array, you're looking for #65580, which seems not to have a tracking issue.

I don't know why I picked that function and assumed this tracking issue was the correct one. Sorry for that!

**Comment by bstrie** [comment]
The documentation for this item suggests that it should be used with another unstable API, `MaybeUninit::uninit_array`. However that API is not contained under this feature flag, and furthermore I can't find a tracking issue for it. Should we use this issue to track that one as well?

**Comment by cole-miller** [comment]
Fwiw, this function is now used by hashbrown (`nightly` crate feature only, introduced in rust-lang/hashbrown#239). I'd love to see it stabilized soon! (Along with `maybe_uninit_uninit_array`.)

**Comment by joboet** [comment]
> A possible alternative is to have a conversion method from `[MaybeUninit<T>; N]` to `MaybeUninit<[T; N]>` and then `assume_init()` the latter. Then a separate `array_assume_init()` function isn't needed.

That's a good idea! `MaybeUninit::from(_).assume_init()` is about the same length as `MaybeUninit::array_assume_init(_)` and allows for better integration with the other methods.

**Comment by Kixunil** [comment]
Converting in the other direction could be useful too as well as between `MaybeUninit<[MaybeUninit<T>; N]>` and the rest.

**Comment by clarfonthey** [comment]
Would very much like some version of `uninit_array` and `array_assume_init` to be stable; right now there's not really a stable equivalent.

IMHO, we should at least collect the array-based issues into a single issue (likely this one) like what's already done with the slice methods in #63569.

**Comment by Raekye** [comment]
> * Should this be a const function?

[`MaybeUninit::assume_init`](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#method.assume_init) is const as of 1.59, and I'd like to see this be const as well

One issue with the conversion traits (`From` and `Into`) is that they can't be used in const contexts, so I'd like this function to exist as well

**Comment by joboet** [comment]
Thank you! I'll close this issue then. For future readers: please go to #96097 for further discussion of this feature.
