### ISSUE TITLE
Tracking Issue for cfg-target-abi

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/rust#80970]
This is a tracking issue for the RFC "Add `target_abi` configuration" (rust-lang/rfcs#2992).
The feature gate for the issue is `#![feature(cfg_target_abi)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC (cc @rust-lang/lang -- can anyone write up mentoring
      instructions?)
- [x] Fix up tier 3 targets that have target ABIs embedded in their target env (#78791)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

**Comment by nvzqz** [comment]
I came across `x86_64_fortanix_unknown_sgx` and I'm wondering if `sgx` should be changed from being `env` to `abi`? I assume not, but I figured I'd ask.

**Comment by joshtriplett** [comment]
`rustc --print cfg` should print `target_abi`. Right now, `rustc --target arm-unknown-linux-gnueabi --print cfg` and `rustc --target arm-unknown-linux-gnueabihf --print cfg` have the same output.

**Comment by joshtriplett** [comment]
@nvzqz For `x86_64-fortanix-sgx`, I think "sgx" should remain the "os" and "fortanix" should be moved from "vendor" to either "abi" or "env".

**Comment by joshtriplett** [comment]
Implementation in progress at https://github.com/rust-lang/rust/pull/86922

**Comment by oli-obk** [comment]
How does this interact with custom target json files? Something like https://github.com/embed-rs/stm32f7-discovery/blob/e4c00f8536d7c6b167c9cf5574d0fe8e1e0cfcff/stm32f7.json

**Comment by nvzqz** [comment]
@oli-obk custom targets like that would specify `"abi": "eabihf"` to match the underlying LLVM target's ABI. Otherwise `#[cfg(target_abi = "eabihf")]` should not match the custom target.

With #86922 merged, I think this is ready to stabilize.

**Comment by joshtriplett** [comment]
For anyone wanting to act on the ready-to-stabilize label: also note the `FIXME` comments in the target files, added in #86922, and make the corresponding adjustments when stabilizing. That PR will also need the `relnotes` label.

**Comment by jrose-signal** [comment]
Ended up here precisely because I wanted to distinguish iOS device and simulator targets in `cfg`. I'm not sure what the high-level difference is between `target_env` and `target_abi`, but by putting the iOS variants in `target_abi`, I can't get at them on stable.

**Comment by ChrisDenton** [comment]
## Request for Stabilization

This is [ready for stabilization](https://github.com/rust-lang/rust/issues/80970#issuecomment-1072695121). It's essential for disambiguating targets that have the same `target_env` and otherwise only differ in their `abi`. Such targets seem to be growing in number as rust grows.

### Summary

This stabilizes the `cfg` option called `target_abi`:

```rust
#[cfg(target_abi = "eabihf")]
```

And `target_abi` is also shown when using `--print=cfg` (snipped for length):

```
> rustc --print=cfg --target armv7-unknown-freebsd

debug_assertions
overflow_checks
panic="unwind"
relocation_model="pic"
target_abi="eabihf"
target_arch="arm"
target_endian="little"
target_env="gnu"
target_family="unix"
[...]
target_os="freebsd"
target_pointer_width="32"
target_vendor="unknown"
unix
```

### Tests

tests/ui/cfg/cfg-target-abi.rs
tests/ui/check-cfg/well-known-values.rs

## Documentation

https://github.com/rust-lang/reference/pull/1446

**Comment by traviscross** [comment]
@rustbot labels +I-lang-nominated

Nominating on behalf of @ChrisDenton on the basis of the stabilization report above.

**Comment by workingjubilee** [comment]
Pardon, @traviscross @rust-lang/lang but this issue came up in discussion and we were wondering if this requires lang FCP to move forward? The RFC was FCPed but the stabilization report needs to have another one for final consensus check on shipping this implementation, right?

**Comment by workingjubilee** [comment]
The [rustc dev guide](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#fcp) does document FCP itself being a requirement of stabilization though interestingly the tracking issue template doesn't have FCP as a separate checkbox. I guess because for a while stabilization PRs were basically considered synonymous with FCP. At some point we moved towards putting stabilization reports more often on the issue itself, although there's no formal rule requiring that.

Perhaps the template should have a separate checkbox for FCP? So we don't lose track of that. A lot of tracking issues aren't updated with their final task boxes checked and their links updated, anyways, but that would at least make it easier.

**Comment by workingjubilee** [comment]
Ah I see! Thank you for clarifying.

**Comment by joshtriplett** [comment]
Based on the stabilization report, this does indeed look ready for stabilization.

@rfcbot merge

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this in the lang triage meeting today, and the consensus was that we want to do this.  It's now in FCP.  Thanks to @KodrAus and to @ChrisDenton for pushing forward on this.

**Comment by madsmtm** [comment]
> The `target_abi` defaults to "" (the empty string) and most targets don't set it.

[`target_os`](https://doc.rust-lang.org/reference/conditional-compilation.html#target_os) uses `"none"` instead of the empty string, maybe that's actually the saner value?

The empty string _feels_ to me more like "no-one thought about what to put here so `rustc` just defaulted to something, but you can't actually rely on `#[cfg(target_abi = "")]` working".

**Comment by joshtriplett** [comment]
@madsmtm I think `""` is consistent with how the ABI appears in target triples. `target_os` uses `"none"` because of target names like `x86_64-unknown-none`. `target_abi` uses `""` rather than `"none"` because we don't, for instance, write `x86_64-unknown-linux-muslnone` the way we write `arm64-unknown-linux-musleabihf`.

I think it's valid to say "there isn't a special ABI", rather than (for instance) having to enumerate ABIs.
