### ISSUE TITLE
[rustdoc-json] Output is currently under-tested

### ISSUE THREAD

**Issue by CraftSpider** [rust-lang/rust#81359]
Currently, the output of rustdoc's JSON backend has very few tests, which only assure some of the most simple functionality. It would be nice to at least have tests for basic forms of each item, as well as any known issues. A quick list of things not really tested (non-exhaustive):

- [ ] Impls
- [ ] Associated Items
- [ ] Consts/Statics
- [ ] Extern items (all forms)
- [ ] Macros
- [ ] Types

It also would be nice to know the desired layout of the tests. Currently, the directory holds the form
```
root
| structs
- | plain
  | tuple
  | generic
| traits
- | has_body
| unions
- | plain
| ...
```
This is slightly different from how normal rustdoc ui tests are structured, but on the other hand HTML output is very different and serves a somewhat different goal. If we want to establish guidelines on the test directory layout, now is a good time to discuss it, before the directories fill up.

**Comment by aDotInTheVoid** [comment]
Another thing we don't have tests for: `ItemEnum::TraitAlias`

**Comment by aDotInTheVoid** [comment]
- [ ] Tests with `--document-private-items` and `--document-hidden-items`

**Comment by aDotInTheVoid** [comment]
- [ ] We have no tests for [`provided_trait_methods`](https://docs.rs/rustdoc-types/latest/rustdoc_types/struct.Impl.html#structfield.provided_trait_methods)
