### ISSUE TITLE
Tracking Issue for `option_result_unwrap_unchecked`

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rust#81383]
Feature gate: `#![feature(option_result_unwrap_unchecked)]`

This is a tracking issue for the unchecked variants of `unwrap()` and `unwrap_err()` of `Option` and `Result`.

These are unsafe functions intended to be used in hot paths of performance sensitive applications where the variant an `Option`/`Result` holds is known, allowing to skip the branch that the safe version introduces. They complement other `*_unchecked()` methods already available, such as `get_unchecked()` in slices.

### Public API

```rust
impl<T> Option<T> {
    pub unsafe fn unwrap_unchecked(self) -> T;
}

impl<T, E> Result<T, E> {
    pub unsafe fn unwrap_unchecked(self) -> T;
    pub unsafe fn unwrap_err_unchecked(self) -> E;
}
```

### Steps / History

- [x] Implementation: #80876
- [x] Stabilization report: https://github.com/rust-lang/rust/issues/81383#issuecomment-944498212
- [ ] Final commenting period (FCP): https://github.com/rust-lang/rust/issues/81383#issuecomment-945379226
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/89951

### Unresolved Questions

- [x] Should we add `expect_unchecked`, and if yes, do it within another feature flag, to unblock `unwrap_unchecked`? https://github.com/rust-lang/rust/issues/81383#issuecomment-801492960
  + It seems best to have it under another feature flag to avoid blocking this one.

- [x] Should we panic on failure in debug (i.e. for those projects that build `core` themselves)? If yes, that would mean there is no way to actually remove the check for those projects, which could be potentially needed by someone. If we do, should it be documented? https://github.com/rust-lang/rust/issues/81383#issuecomment-824654722
  + The current implementation uses `debug_assert!`, which may be useful for projects that build `core` with debug assertions enabled (e.g. the bors test suite or some embedded projects), but this is *not* documented, and indeed most users will not see such behavior, since `core` is shipped in release mode.
  + Furthermore, since it is UB anyway, we have room for changing the implementation, e.g. if we end up distributing the standard library with debug assertions enabled for some use cases.

- [x] Should we name them `unchecked_unwrap` instead? https://github.com/rust-lang/rust/issues/81383#issuecomment-942533948.
  + The current name (`unwrap_unchecked`) follows the convention of other stable methods in the standard library such as `get_unchecked`, `map_unchecked`, `new_unchecked`, `unreachable_unchecked`... (see as well https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter).
  + On the other hand, the `unchecked_{add,...}` methods seem to follow the opposite convention, but those are unstable and they likely do it because the stable `{checked,...}_{add,...}` exist.

**Comment by camelid** [comment]
Also: start dogfooding this in `std`.

**Comment by ojeda** [comment]
@camelid Indeed! The first two PRs for this are submitted.

**Comment by ojeda** [comment]
There are a couple more that can be replaced in `library/core/src/iter/adapters/fuse.rs` (not counting the macro ones, which are quite a few, but those would require several equivalent functions), but it may make codegen worse due to missed optimizations in LLVM. I filed https://bugs.llvm.org/show_bug.cgi?id=48975 to see what can be done on their side. This may also help other `*_unchecked()` functions too, e.g. https://github.com/rust-lang/rust/pull/81354.

**Comment by bhgomes** [comment]
Is there a way to express that this is a "safe" operation when we know that the error type is `Infallible`?

**Comment by ojeda** [comment]
That's an interesting idea, although I am not sure what the policy is on having differing function qualifiers for the same method name, @m-ou-se?

I guess that could ideally be achieved with the future specialization feature (if it supports inherent impls). We can also (ab)use the priority of inherent methods over traits, but it feels a bit dirty:

```rust
use std::convert::Infallible;

pub enum MyResult<T, E> {
    Ok(T),
    Err(E),
}

trait UnsafeUnwrapUnchecked<T> {
    unsafe fn unwrap_unchecked(self) -> T;
}

impl<T, E> UnsafeUnwrapUnchecked<T> for MyResult<T, E> {
    unsafe fn unwrap_unchecked(self) -> T {
        match self {
            MyResult::Ok(t) => t,
            MyResult::Err(_) => core::hint::unreachable_unchecked(),
        }
    }
}

impl<T> MyResult<T, Infallible> {
    fn unwrap_unchecked(self) -> T {
        match self {
            MyResult::Ok(t) => t,
            MyResult::Err(_) => unsafe { core::hint::unreachable_unchecked() },
        }
    }
}
    
pub fn f() {
    let _ = MyResult::<i32, Infallible>::Ok(42).unwrap_unchecked();
    let _ = unsafe { MyResult::<i32, i32>::Ok(42).unwrap_unchecked() };
}
```

**Comment by CryZe** [comment]
There already is into_ok() and into_err() that do this, there is no need to overload unwrap_unchecked.

**Comment by m-ou-se** [comment]
@ojeda Even if we could make `unsafe` depend on the generic type, I wouldn't want to call the safe version `unchecked`, since there's no check that's being skipped in that case. And as @CryZe mentioned, we already have [`into_ok()`](https://doc.rust-lang.org/stable/std/result/enum.Result.html#method.into_ok) for that.

**Comment by ojeda** [comment]
Yeah, that is what I imagined, thanks!

**Comment by alecmocatta** [comment]
Personally I try to "label" unwraps by instead using `expect`. I for one would appreciate the presence of `unsafe fn expect_unchecked("...") -> T` if it were to be added as well?

**Comment by ojeda** [comment]
That could be a bit misleading since the message will not be used. On the other hand, we could use it in debug builds for asserting.

**Comment by alecmocatta** [comment]
Yes, in almost all cases the message would never be printed. Note that I believe it requires `-Zbuild-std` or similar to compile `core` with debug assertions enabled.

Personally I would still find this useful. My flow is to start with `unwrap`/`expect`s, and cautiously relax them to `unwrap_unchecked`/`expect_unchecked` when necessitated by a perf bottleneck, using a trait like [`unchecked_unwrap::UncheckedUnwrap`](https://docs.rs/unchecked_unwrap/3/unchecked_unwrap/trait.UncheckedUnwrap.html).

**Comment by ojeda** [comment]
Yeah. Some projects do build `core` on their own (in particular the ones where debugging can be harder, e.g. embedded, kernels, etc.), plus rustc development can benefit from it too, so it can still be helpful (which is why we have `debug_assert!` in the `unwrap_unchecked`).

**Comment by camelid** [comment]
If `expect_unchecked` is added, I think it might be better to have a separate feature flag for it so it can be considered separately. Some people may feel that `unwrap_unchecked` makes sense but `expect_unchecked` does not, so one should not block the other.

**Comment by TrolledWoods** [comment]
I feel that `expect_unchecked` makes sense if it still panics with the message in debug mode. Since `unwrap_unchecked` also panics in debug mode, should this be noted in the documentation?

**Comment by dbeckwith** [comment]
I agree that the panic in debug mode should be documented, that seems very useful to know.

**Comment by camelid** [comment]
> Note that there are stable methods called `get_unchecked`, `map_unchecked`, `new_unchecked`, `unreachable_unchecked`...

That's a good point; I didn't think of those functions. In that case, the current names are probably fine. I'll leave it as an unresolved question for now just so it is brought to T-libs's attention when FCP happens.

> So I would say the `unchecked_add` etc. are the ones that should be changed to follow the normal convention before stabilizing them.

Ah, I thought they were already stable. However, even though they are unstable, it probably wouldn't be good to rename them since `checked_add`, `saturating_add`, etc. are stable.

**Comment by PureWhiteWu** [comment]
According to this chapter of the Rust API Guidelines(https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter), I guess `unwrap_unchecked` maybe makes more sense?

**Comment by ojeda** [comment]
# Request for Stabilization
## Summary
Unsafe versions of `unwrap` and `unwrap_err` of `Option` and `Result` which allow to skip the branch:
```rust
let x = Some("air");
assert_eq!(unsafe { x.unwrap_unchecked() }, "air");
```

## Tests
- `Option::unwrap_unchecked`
  https://github.com/rust-lang/rust/blob/af9b508e1d6c83a8f0e6f5c0b2b75598aa37ed27/library/core/tests/option.rs#L163-L168

- `Result::unwrap_unchecked`
  https://github.com/rust-lang/rust/blob/af9b508e1d6c83a8f0e6f5c0b2b75598aa37ed27/library/core/tests/result.rs#L131-L135

- `Result::unwrap_err_unchecked`
  https://github.com/rust-lang/rust/blob/af9b508e1d6c83a8f0e6f5c0b2b75598aa37ed27/library/core/tests/result.rs#L137-L141

## Existing users
There seem to be a fair amount of users in the wild: https://github.com/search?l=Rust&q=option_result_unwrap_unchecked&type=code, plus we also have a few users in the standard library, e.g. in `Option` itself:

https://github.com/rust-lang/rust/blob/af9b508e1d6c83a8f0e6f5c0b2b75598aa37ed27/library/core/src/option.rs#L1209-L1214

## Resolutions of unresolved questions

- *Should we add `expect_unchecked`, and if yes, do it within another feature flag, to unblock `unwrap_unchecked`?*
  + It seems best to have it under another feature flag to avoid blocking this one.

- *Should we panic on failure in debug (i.e. for those projects that build `core` themselves)? If yes, that would mean there is no way to actually remove the check for those projects, which could be potentially needed by someone. If we do, should it be documented?*
  + The current implementation uses `debug_assert!`, which may be useful for projects that build `core` with debug assertions enabled (e.g. the bors test suite or some embedded projects), but this is *not* documented, and indeed most users will not see such behavior, since `core` is shipped in release mode.
  + Furthermore, since it is UB anyway, we have room for changing the implementation, e.g. if we end up distributing the standard library with debug assertions enabled for some use cases.

- *Should we name them `unchecked_unwrap` instead?*
  + The current name (`unwrap_unchecked`) follows the convention of other stable methods in the standard library such as `get_unchecked`, `map_unchecked`, `new_unchecked`, `unreachable_unchecked`... (see as well https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter).
  + On the other hand, the `unchecked_{add,...}` methods seem to follow the opposite convention, but those are unstable and they likely do it because the stable `{checked,...}_{add,...}` exist.
