### ISSUE TITLE
Tracking Issue for linking modifiers for native libraries 

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#81490]
This is a tracking issue for the RFC "Linking modifiers for native libraries" (https://github.com/rust-lang/rfcs/pull/2951) accepted through MCP https://github.com/rust-lang/compiler-team/issues/356.
The feature gate for the issue is `#![feature(native_link_modifiers)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC - #83507
- [x] Adjust documentation - https://github.com/rust-lang/reference/pull/1170
- [x] Stabilization PR - https://github.com/rust-lang/rust/pull/93901

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

**Comment by 12101111** [comment]
```
warning: the feature `native_link_modifiers` is incomplete and may not be safe to use and/or cause compiler crashes
 --> library/unwind/src/lib.rs:8:12
  |
8 | #![feature(native_link_modifiers)]
  |            ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #81490 <https://github.com/rust-lang/rust/issues/81490> for more information
```

There are 4 feature gate: `native_link_modifiers_{as_needed,bundle,verbatim,whole_archive}`, are they both incomplete or just some of them are incomplete?

**Comment by petrochenkov** [comment]
I don't think the incomplete warning is correct, the modifiers are not yet stable, but they are complete enough.

**Comment by luqmana** [comment]
@petrochenkov Is there anything left before at least stabilizing the modifiers syntax (the `native_link_modifiers` feature)? If not I can help move that forward. It's definitely something we need to do before we stabilize any of the specific formats.

**Comment by petrochenkov** [comment]
No, as far as I know (I wanted to audit the implementation once more though).
It probably makes sense to stabilize the syntax together with one of the specific modifiers, otherwise the stabilization is all the responsibility and none of the profits.

**Comment by krasimirgg** [comment]
@petrochenkov I'm interested in helping out getting this stabilized if that's OK.
I'm hoping this RFC will help us improve [Bazel Rust support](https://github.com/bazelbuild/rules_rust).
I'm a novice with respect to rustc development.
What's left and what's the best way to get involved?

Maybe: the [Relative order of -l and -Clink-arg(s) options](https://rust-lang.github.io/rfcs/2951-native-link-modifiers.html#relative-order-of--l-and--clink-args-options) part of the RFC is not yet implemented: https://github.com/rust-lang/rust/pull/83507#issuecomment-1033933049. Is anyone working on it, otherwise does it sound reasonable for me to pick this up?

**Comment by petrochenkov** [comment]
@krasimirgg 
I actually just started auditing the implementation for stabilization today (the general modifier syntax, and the `whole-archive` modifier specifically). If no other task interrupts me, then I'll likely make a PR tomorrow.

The "relative order" part is entirely orthogonal though, so you can certainly work on that.
I remember starting implementing that and discovering that it is a more invasive change than I expected, so I abandoned it due to a lack of time, IIRC.

The code parsing these options (`-l`, `-C link-arg` and `-C link-args`) lives in `compiler\rustc_session\src\options.rs` and in `compiler\rustc_session\src\config.rs`.
It currently builds two separate option vectors - `Options::libs` and `CodegenOptions::link_args`, instead it needs to build a single vector for the both kinds of options that will then be used throughout the compiler.

**Comment by petrochenkov** [comment]
@hlopko 
1. Yes.
2. Yes.
3. No, probably not, I see it as a bugfix.

**Comment by petrochenkov** [comment]
>I remember starting implementing that and discovering that it is a more invasive change than I expected, so I abandoned it due to a lack of time, IIRC.

I now remember why I abandoned it.

The linker command line is constructed in `fn linker_with_args`.
Currently the options are passed roughly like this:
- libraries (`add_local_native_libraries` in particular)
- options added by the compiler (`add_order_independent_options`)
- options added by the user (`add_user_defined_link_args`)

So user options passed with `-Clink-arg(s)` can be used to override options added by the compiler by default.
This behavior must be kept.

So I guess the user options will have to be split into two groups now - "before the last `-l`" and "after the last `-l`", with the "[Relative order of -l and -Clink-arg(s)](https://rust-lang.github.io/rfcs/2951-native-link-modifiers.html#relative-order-of--l-and--clink-args-options)" change affecting only the first group.
This is all pretty annoying, I need to think about it more, maybe a new option will be required instead.

**Comment by petrochenkov** [comment]
@krasimirgg 
Could you say which specific options did you plan to order relatively to `-l`s in https://github.com/rust-lang/rust/pull/83507#issuecomment-1033876170?

**Comment by petrochenkov** [comment]
Stabilization PR for the general modifier syntax and the `whole-archive` modifier - https://github.com/rust-lang/rust/pull/93901.

**Comment by krasimirgg** [comment]
WDYT about expanding the guarantee to preserve the relative order between linker flags derived from `-l` [under the `-l link-arg` suggestion] and `--extern` rustc flags? I noticed [in Bazel rules](https://osscs.corp.google.com/bazel/rules_rust/+/main:rust/private/rustc.bzl;l=488;drc=c435cf4478fc6e097edc5dba0e71de6608ab77d8) we have a knob to pass some rlibs via `--extern`.

**Comment by hlopko** [comment]
I think `-llink-arg` is going to solve all our use cases, which are:

* control over `--whole-archive` (in combination with following items)
* ability to pass libraries by their full path (`-L`/`-l` pairs have a problem when there are 2 different libraries, in 2 different directories, with the same basename)
* ability to pass object files directly without creating a static archive for them (wrapped inside `--start-lib`/`--end-lib`)

@krasimirgg, AFAIK we don't necessarily need to keep relative order between `-l` and `--extern`, it's enough that linker flags from `--extern` appear to the left from `-l` flags. We would only need to keep their relative order if C++ library depended on Rust library, and we used `--extern` to link the Rust library. However in this situation we use `-l` for the Rust library.

**Comment by petrochenkov** [comment]
>WDYT about expanding the guarantee to preserve the relative order between linker flags derived from `-l` [under the `-l link-arg` suggestion] and `--extern` rustc flags?

This is harder because crates are not just names for rustc, unlike native libraries, they have dependencies between each other, they are sorted by topological sort to avoid breaking those dependencies, dependency crates may also bring their own native libraries.
So the resulting linker command line may be very different from what was originally passed to rustc with `--extern` options.

**Comment by hlopko** [comment]
@petrochenkov I'll double check with @krasimirgg and come back if I'm wrong, but for the time being please assume we don't need to preserve relative order between `--extern` and `-l`.

**Comment by krasimirgg** [comment]
We don't need to preserve relative order between `--extern` and `-l`/`-C` link args. Tangentially, I noticed that `CodegenOptions::pre_link_args` also exists, [AFAIK not available as a rustc flag]. That seems like another little reason to use `-l link-arg=something`.

@petrochenkov does the following sound good:
1. We still reference the same RFC, updating the link order section accordingly.
2. We put the new -llink-arg behavior under a new experimental feature flag.

**Comment by petrochenkov** [comment]
@krasimirgg 
Sounds ok to me.

**Comment by petrochenkov** [comment]
Stabilization PR for the `bundle` modifier - https://github.com/rust-lang/rust/pull/95818.
It's currently blocked, but it documents the step-by-step path to merging it.

**Comment by petrochenkov** [comment]
@krasimirgg 
The change is intentional, before https://github.com/rust-lang/rust/pull/93901 rustc added `--whole-archive` to static libraries in some (semi-random) cases.
After https://github.com/rust-lang/rust/pull/93901 we are no longer doing that, and the documentation was updated to mention that, and the release notes will mention it too.

The fix is (usually) to reorder the native libraries to respect dependencies between them, or (more rarely) to add a `+whole-archive` modifier. E.g. see https://github.com/rust-lang/rust/issues/96328#issuecomment-1107393042 in another reported issue about this.

**Comment by krasimirgg** [comment]
@petrochenkov I agree. This example is a bit different: there is just 1 native library and a reference from an rlib to it. The problem is with the relative order between an rlib and its native lib dependency. The general instance of this problem is something like: anytime something uses a picky linker with an rlib -> native dependency, they risk backward reference errors and will have to fall back to using `+whole-archive`.

In Bazel rules_rust, we currently have a knob to use `+whole-archive` as a workaround for this issue, but it's not ideal, as we ideally want to only use whole-archive for libraries that really need it (alwayslink) and use standard linker options for standard libraries, enabling more linker optimisations.

We could update rules_rust to use an additional `-Clink-arg=-lfoo` for each native dep of a transitive rlib dependency, but I thought that this problem is general enough to try and address within rustc itself, if possible.

**Comment by petrochenkov** [comment]
>This example is a bit different: there is just 1 native library and a reference from an rlib to it.

Nothing in https://github.com/krasimirgg/native-libs-order-example indicates that libbar.rlib depends on libfoo.a though.
Rustc does preserve dependencies when they are specified, typically bar.rs would have a `#[link(name = foo)]` in its source code or `println!("cargo:rustc-link-lib=foo");` (*) in its build script.
But if dependencies are not specified, then rustc is free to put libraries in any random order.

(*) This will result in `rustc ... -l bar ...` when building libbar.rlib, which won't *link* anything because no linker is involved when producing rlibs, but will register the dependency.

**Comment by petrochenkov** [comment]
>To address this, would it make sense to update `rustc` to mention `-lstatic=foo` libs one more time on the linker command line, after all the non-standard rlibs (or after all rlibs)?

Rustc is not the right abstraction level for that, IMO, since it's not aware of dependencies between libraries unless they are specified externally.
As I understand Bazel/rules_rust is a replacement of cargo, so it should be aware of all the dependencies, and can either pass `-l` options when building rlibs to register dependencies, or to order the final command line while preserving dependencies.

**Comment by krasimirgg** [comment]
Thank you very much! What I was missing was this way to instruct rustc to say an rlib depends on a native library at the time of building the rlib (with the -bundle modifier): 
>This will result in rustc ... -l bar ... when building libbar.rlib, which won't link anything because no linker is involved when producing rlibs, but will register the dependency. 

I think Bazel/rules_rust wasn't doing this properly in all cases, and because previously rustc was always using `--whole-archive` for native deps we didn't notice these problems until now. I'll look into adapting rules_rust.

**Comment by krasimirgg** [comment]
@petrochenkov I'm curious what's the mechanism via which rustc registers the dependency in this case:
>(*) This will result in rustc ... -l bar ... when building libbar.rlib, which won't link anything because no linker is involved when producing rlibs, but will register the dependency.

Does it do it by recording some metadata in the rmeta rlib archive member?

**Comment by petrochenkov** [comment]
@krasimirgg 
>Does it do it by recording some metadata in the rmeta rlib archive member?

Yes.

**Comment by krasimirgg** [comment]
@petrochenkov : Consider a case where an rlib depends on multiple native libraries, which themselves depend on each other, say rlib `r` depends on `libnative1.a` which itself depends on `libnative2.a`. My understanding is that while building `r`, we'll supply its native dependencies in the expected relative linker order, e.g., `rustc -o r.rlib ... -lstatic:-bundle=native1 -lstatic:-bundle=native2 ...`.

Later, when `r` is used to build a rust binary `b`, I'd expect that in the linker invocation constructed to build `b`, the relative order of `native1` and `native2` will be preserved. Does rustc guarantee that?

**Comment by petrochenkov** [comment]
@krasimirgg 
>I'd expect that in the linker invocation constructed to build `b`, the relative order of `native1` and `native2` will be preserved. Does rustc guarantee that?

Yes, in practice.
See https://github.com/rust-lang/rust/issues/96328 for some discussion about documenting it.

**Comment by petrochenkov** [comment]
Closing this umbrella issue in favor of more specific issues for the remaining unstable and unimplemented pieces:
- https://github.com/rust-lang/rust/issues/99424
- https://github.com/rust-lang/rust/issues/99425
- https://github.com/rust-lang/rust/issues/99427
- https://github.com/rust-lang/rust/issues/99429

**Comment by dcsommer** [comment]
For "Unresolved Questions" I think there is still the matter of the default of the `bundle` link modifier and it's purpose and interaction with respect to `whole-archive`. The full cross-product of intended behaviors for (+/-whole-archive, +/-bundle, crate-type) is a little unclear to me and would ideally get documentation.

**Comment by petrochenkov** [comment]
@dcsommer 
This is already documented in nightly docs - https://doc.rust-lang.org/beta/rustc/command-line-arguments.html
Except that the compatibility case for `whole-archive` is intentionally vague, and the restriction on `+bundle,+whole-archive` in rlibs in not documented because it's sort of an implementation deficiency that we are planning to fix (https://github.com/rust-lang/rust/issues/99429).
