### ISSUE TITLE
Tracking Issue for `-Z normalize-docs`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#82692]
This is a tracking issue for the feature `-Z normalize-docs`. This normalizes projections like `<Vec<T> as IntoIterator>::IntoIter` to `std::vec::IntoIter<T>`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the features (https://github.com/rust-lang/rust/pull/77467)
- [ ] Fix the bugs blocking stabilization (https://github.com/rust-lang/rust/issues/81091)
  - [ ] Cycles in trait bounds should be recoverable (https://github.com/rust-lang/rust/issues/79459)
  - [ ] Recursion limit errors in trait bounds should be recoverable (https://github.com/rust-lang/rust/issues/79506)
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

No unresolved questions known, this is "just hard".

### Implementation history

- initial impl: https://github.com/rust-lang/rust/pull/77467
- reverted due to breakage: https://github.com/rust-lang/rust/pull/77467
- re-added as unstable: https://github.com/rust-lang/rust/pull/79525

**Comment by jyn514** [comment]
@workingjubilee hmm, I'm not sure why you marked this as A-cli? The intention is to remove the flag completely when the blocking issues are fixed, and have this always on.

**Comment by workingjubilee** [comment]
:shrug:

**Comment by fmease** [comment]
Apart from marking the impl as https://github.com/rust-lang/rust/labels/S-tracking-impl-incomplete / “incomplete” (buggy), I'm marking it as https://github.com/rust-lang/rust/labels/S-tracking-design-concerns because there have been lots of discussions around the question whether we want to normalize/evaluate *constant expressions* in rustdoc (“intent” vs. “representation”) and by extension the same concern applies to types. See #102456, #99630, [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/new.20const.20display/near/364308963).
