### ISSUE TITLE
Tracking Issue for NOOP_METHOD_CALL lint

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#83099]
This is a tracking issue for the `NOOP_METHOD_CALL` lint (https://github.com/rust-lang/lang-team/issues/67)

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the initial version of the lint (https://github.com/rust-lang/rust/pull/80723)
- [ ] Extend this to more complicated cases, like `ToOwned`
- [ ] Make the lint warn-by-default

### Unresolved Questions

* Should we lint when a method is called via UFCS? This could be interpreted as the user explicitly choosing to call a no-op method.
* Should we allow external crates to mark their own methods as being 'noop-ops', so that this lint can fire on third-party methods?

### Implementation history

* Initial version implemented in https://github.com/rust-lang/rust/pull/80723

**Comment by safinaskar** [comment]
Also, it seems NOOP_METHOD_CALL is now warn-by-default
