### ISSUE TITLE
Tracking Issue for RFC 3052: make the authors field optional

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#83227]
This is a tracking issue for the RFC "Make the authors field optional" (rust-lang/rfcs#3052).

### About tracking issues

Tracking issues are used to record the overall progress of implementation. They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions. A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature. Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC
  - [x] cargo: stop including authorship information in `cargo new`/`cargo init` and in templates
  - [x] crates.io: start accepting crates without authorship information
  - [ ] crates.io: stop displaying and serving authorship information
  - [x] docs.rs: stop displaying and serving authorship information

### Implementation history

* rust-lang/crates.io#3429 - start accepting crates without authorship information
* rust-lang/crates.io#3132 - Remove "Authors" section from crate details page
* rust-lang/cargo#9282 - Stop including authors field in manifests made by cargo new
* rust-lang/docs.rs#1322 - stop displaying and serving authorship information
* rust-lang/docs.rs#1323 -  stop collecting author data and delete the old data

**Comment by hi-rustin** [comment]
Do you need help with this issue? I am interested in implementing it.

**Comment by lf-** [comment]
I'm also interested in looking into the cargo side.

**Comment by hi-rustin** [comment]
I will finish the rest of the task.

@rustbot claim

**Comment by pietroalbini** [comment]
Thanks for the interest in implementing this :heart: 

@hi-rustin to avoid duplicating work, note that there is a PR to stop displaying the field in the crates.io UI open already (https://github.com/rust-lang/crates.io/pull/3132) since before this tracking issue was open. Added that PR and lf-'s one to the issue text.

**Comment by hi-rustin** [comment]
> Thanks for the interest in implementing this ❤️
> 
> @hi-rustin to avoid duplicating work, note that there is a PR to stop displaying the field in the crates.io UI open already ([rust-lang/crates.io#3132](https://github.com/rust-lang/crates.io/pull/3132)) since before this tracking issue was open. Added that PR and lf-'s one to the issue text.

Got it. Thanks!

**Comment by hi-rustin** [comment]
>     * crates.io: stop displaying and serving authorship information

@pietroalbini  I think this already done. See also: https://github.com/rust-lang/crates.io/pull/3132#issuecomment-803542651

**Comment by hi-rustin** [comment]
>  Adjust documentation

What other documents need to be updated?

**Comment by hi-rustin** [comment]
@pietroalbini Could you please take a look?

**Comment by pksunkara** [comment]
I just came across this. How does this change the `CARGO_PKG_AUTHORS`? I would need to update [`clap`](https://github.com/clap-rs/clap/blob/master/src/macros.rs#L112-L124) for this.

**Comment by lf-** [comment]
> I just came across this. How does this change the `CARGO_PKG_AUTHORS`? I would need to update [`clap`](https://github.com/clap-rs/clap/blob/master/src/macros.rs#L112-L124) for this.

Hi! This does not change CARGO_PKG_AUTHORS. All the current changes do is hide the authors field in various websites' UI and make it much harder to accidentally include it in a package as cargo-new does not introduce it. If you handle CARGO_PKG_AUTHORS being empty already (it was allowed to be before these changes, you just couldn't upload such crates to crates.io), you don't have to change anything.

**Comment by pietroalbini** [comment]
Sorry for taking a while to respond!

> I think this already done. See also: rust-lang/crates.io#3132 (comment)

The two other actions needed on the crates.io side are:

* Stop [returning authorship information from the API](https://crates.io/api/v1/crates/rustwide/0.1.0/authors), changing the endpoint to always return an empty list.
* Stop collecting authorship information during publish and drop the existing data from the database.

> What other documents need to be updated?

Removed that point, it was a leftover from the tracking issue template.

**Comment by hi-rustin** [comment]
> * Stop [returning authorship information from the API](https://crates.io/api/v1/crates/rustwide/0.1.0/authors), changing the endpoint to always return an empty list.
> 
> * Stop collecting authorship information during publish and drop the existing data from the database.

Got it. I will working on these.

**Comment by hi-rustin** [comment]
![image](https://user-images.githubusercontent.com/29879298/115403633-2eee7f00-a21f-11eb-9f49-3c2a0eeccb68.png)
@pietroalbini It seems that the action state in the Issue body is lost?

**Comment by pietroalbini** [comment]
Whelp, not sure how that happened, fixed it!

**Comment by hi-rustin** [comment]
cc: https://github.com/rust-lang/docs.rs/issues/1323
