### ISSUE TITLE
Tracking Issue for `-C export-executable-symbols`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#84161]
This is a tracking issue for the RFC "2841" (rust-lang/rfcs#2841).
The feature gate for the issue is `#![feature(export_executable_symbols)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC (cc @rust-lang/compiler  -- can anyone write up mentoring
      instructions?)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- Is this a good name for it?
- Should it be more general and export when limit_rdylib_exports or crate_type == ProcMacro?

**Comment by nagisa** [comment]
This should not have been closed.

**Comment by bjorn3** [comment]
The `reachable_set` analysis currently doesn't take the export-executable-symbols flag into account.

**Comment by GoldsteinE** [comment]
What’s stopping this from moving forward? Can I do something to help?

**Comment by Enselic** [comment]
Triage: Incidentally I just created a new label for this feature before I saw your comment on this issue.

A good first step would be to go through the issues in this query and triage them appropriately: https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+Zexport-executable-symbols

Maybe https://github.com/rust-lang/rust/issues/34131 can be closed as "covered by the tracking issue", for example.

**Comment by GoldsteinE** [comment]
Thanks! I think I’ll look into #101610 first, because it affects the promised semantics of the flag.

**Comment by g-mero** [comment]
What's the current progress on this feature? It's been 3 years.

**Comment by bjorn3** [comment]
It's still buggy afaik and I don't think anyone has volunteered to work on fixing the bugs it has.

**Comment by GoldsteinE** [comment]
@g-mero It’s somewhere on my backlog, but I can’t promise getting to it soon. I think the problem in #101610 is either with version script or with linker arguments, so if you’d like to help, you can try to check whether symbols get to the version script. If they do, I think we should either use `--dynamic-list` or just `--export-dynamic`. Debugging this requires spending more time reading ld manuals than I currently have bandwidth for.
