### ISSUE TITLE
Tracking Issue for RFC 3101: Reserved Prefixes

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#84978]
This is a tracking issue for the RFC "Reserved Prefixes" (rust-lang/rfcs#3101).
The feature gate for the issue is `#![feature(reserved_prefixes)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC (implementation details are tracked in https://github.com/rust-lang/rust/issues/84599)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [x] Stabilization FCP ([see instructions on rustc-dev-guide][stabilization-guide]) -- https://github.com/rust-lang/rust/issues/88140

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

* How to manage the API `proc_macro::TokenStream::from_str`, which does not take any edition information? ([raised here](https://github.com/rust-lang/rfcs/pull/3101#issuecomment-832686934)) --> Discussed in https://github.com/rust-lang/rust/issues/84979

**Comment by nikomatsakis** [comment]
@lrh2000 great! I'm going to spin off an implementation issue, I think to track this discussion. (I should've done this from the start, perhaps.)

**Comment by steffahn** [comment]
Some relevant examples regarding string (and similarly char) literals – the first two copied from the [linked zulip](https://rust-lang.zulipchat.com/#narrow/stream/268952-edition-2021/topic/reserved.20prefixes/near/238979476) discussion ([archive](https://zulip-archive.rust-lang.org/268952edition2021/41671reservedprefixes.html#238979476)) – include
```rust
match"foo" { _ => () }

if"foo".eq("foo") {}

while"foo".ne("foo") {}

if let"foo" = "foo" {}

loop {
    break"foo"
};

for _ in"foo".chars() {}

return"foo"
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=17dc20e3ce2af25f846ddf180ca431dc))

which raises the question whether we want to exclude all keywords or maybe certain keywords from the disallowed prefixes.

**Comment by petrochenkov** [comment]
>whether we want to exclude all keywords or maybe certain keywords from the disallowed prefixes

Note that lexer isn't currently aware of the keyword list (*), and making it aware is a step in the wrong direction, IMO.
I generally support the @matklad's idea of working with literal prefixes using jointness (https://github.com/rust-lang/rust/issues/84979#issuecomment-843929357), this is the direction in which multi-character punctuation and "compound" float literals are supposed to move  in accordance with https://github.com/rust-lang/rust/pull/71322#issuecomment-629835568.

(*) After all, every left-hand side of a macro is able to introduce its own syntax entirely independent from Rust syntax, with its own keyword list, and lexer works with macro inputs too.

**Comment by nikomatsakis** [comment]
@petrochenkov I was wondering about "jointness". The idea here would be that we produce the same tokens, but in the Rust parser we check for (e.g.) `k#foo` and interpret it differently than `k# foo`?

**Comment by petrochenkov** [comment]
Yeah, it should be applicable to `prefix#ident` too in some form (with less urgency), but I was talking about `prefixLITERAL` specifically (as an answer to https://github.com/rust-lang/rust/issues/84978#issuecomment-844147408) because it has larger compatibility issues.

**Comment by lrh2000** [comment]
@petrochenkov So do you mean that we should emit errors for reserved prefixes in the parser instead of the lexer?

I think it does not *solve* the problem about `TokenStream::from_str`. Instead, it only *defers* the problem. We may not alter the lexing rules now, but in the future we have to change the lexing rules if we want to introduce another prefix that is also used to denote raw strings (or something like them). Am I missing anything?

But I think it sounds good because it can easily solve almost all problems pointed out by @steffahn . For example, we can distinguish lifetimes from string literals and we can also distinguish keywords from identifiers. And I can have better diagnostics messages like
```
error: unknown prefix on string literal: bar
 --> file.rs:x:y
  |
1 | foo!(bar"qux");
  |      ^^^ help: try using whitespace here: `bar "qux"`
  |
  = note: prefixed string literals are reserved for future use
``` 

But I've found currently parsing the macro arguments and expanding macros is done in `rustc_expand`, so it means that we will emit errors for reserved prefixes both from `rustc_parse` and `rustc_expand`, does it sound good?

**Comment by petrochenkov** [comment]
@lrh2000 
>So do you mean that we should emit errors for reserved prefixes in the parser instead of the lexer?

Yes, at least for breakage-prone things like `match"foo"`.
For anything involving raw strings with `#`s the errors can reported in the lexer just to save time and defer the final decision, I'm pretty sure that code like `match#"foo"#` is not used in practice.

>I think it does not solve the problem about TokenStream::from_str

Could you remind what is the problem with `TokenStream::from_str` exactly?

>but in the future we have to change the lexing rules if we want to introduce another prefix that is also used to denote raw strings (or something like them). Am I missing anything?

String escaping is done during parsing (proc macros can do custom escaping in particular), so lexer doesn't need to discern between raw and non-raw strings unless `#`s are involved, but `#`s should be covered by the first item.

>But I've found currently parsing the macro arguments and expanding macros is done in rustc_expand, so it means that we will emit errors for reserved prefixes both from rustc_parse and rustc_expand, does it sound good?

`rustc_expand` should always delegate to `rustc_parse` for parsing (maybe unless compatibility shims for `tt` matchers are involved?).
Sorry for the brief answers, I can't spend much time on this right now.

**Comment by steffahn** [comment]
> lexer doesn't need to discern between raw and non-raw strings unless `#`s are involved

It does need to discern. Both `"\""` and `r"\"` are valid (raw) string literals, whereas `"\"` is an un terminated string literal and `r"\""` is just `r"\"` followed by an unterminated string literal.

**Comment by nikomatsakis** [comment]
We can certainly just accept that any future form of raw string will have to use `#`.

**Comment by lrh2000** [comment]
@petrochenkov Thanks for your reply first.

> Could you remind what is the problem with TokenStream::from_str exactly?

I think we may get different results (`TokenStream`) for the same string (`from_str`) in different versions of Rust, but the version information of the string is not known during the evaluation of `TokenStream::from_str`.

I'm not sure why you ask this. Maybe I misunderstand the problem?

> String escaping is done during parsing (proc macros can do custom escaping in particular), so lexer doesn't need to discern between raw and non-raw strings unless #s are involved, but #s should be covered by the first item.

Now the lexer reports the start position and the end position for every token, so it has to do some (although simplified) escaping, see https://github.com/rust-lang/rust/blob/bf24e6ba00e8a74103fc69a8de25ff955f910ba3/compiler/rustc_lexer/src/lib.rs#L653-L671

> rustc_expand should always delegate to rustc_parse for parsing (maybe unless compatibility shims for tt matchers are involved?).

If we check reserved prefixes in parser, I think the best place is in `parse_ident`. But when parsing macro arguments, things are different. I don't believe it will go through the `parse_ident` path, especially when it just expects a token. I think it reflects that checking reserved prefixed in parser is less elegant than checking in lexer (at least in some certain aspects), although it also brings many benefits.

I will conduct more experiments on this, but now I'm curious about your opinions (if any).

**Comment by m-ou-se** [comment]
Note that the 'jointness' solution won't really work. That's exactly what we wanted to avoid by reserving prefixes in the *lexer*, to make sure we don't have to decide right now on the lexing rules for every possible prefix. As I wrote in https://github.com/rust-lang/rust/issues/84979#issuecomment-851432665:

> We specifically wanted to make these things a *lexer* error, so we don't have to decide on the lexing rules for that literal yet. E.g. is `fb"\xFF"` valid or not? How about `fb"❉"`? Or `fr"\"`? Or `f"hello {123 + "hey".len()}"`?

---

Also, this doens't seem to be true:

> String escaping is done during parsing (proc macros can do custom escaping in particular)

Proc macros cannot accept string literals with escape sequences or characters that don't match the prefix. These errors are given without parsing:

```rust
#[proc_macro]
pub fn hey(_: TokenStream) -> TokenStream {
    TokenStream::new()
}
```
```rust
hey!("\xFF");
hey!(b"å");
```
```
error: out of range hex escape
 --> examples/hey.rs:3:7
  |
3 | hey!("\xFF");
  |       ^^^^ must be a character in the range [\x00-\x7f]

error: non-ASCII character in byte constant
 --> examples/hey.rs:4:8
  |
4 | hey!(b"å");
  |        ^
  |        |
  |        byte constant must be ASCII
  |        help: use a \xHH escape for a non-ASCII byte: `\xE5`
```

**Comment by m-ou-se** [comment]
As for `match"hey"` etc., I think it's perfectly fine if that gives an error and a suggestion for `match "hey"` with a space.

**Comment by m-ou-se** [comment]
This seems to have already been completed. Apart from edition 2021 not being stable yet, this is stable.

**Comment by nikomatsakis** [comment]
Re-opening as we have not made a stabilization decision here. Has there been a Rust reference PR? I drafted a stabilization report in [this hackmd](https://hackmd.io/uTiMV0g4Te6EOMDrn1KfzQ).

**Comment by nikomatsakis** [comment]
@triagebot release-assignment

I don't believe @lrh2000 is still pushing this forward.

**Comment by nikomatsakis** [comment]
Stabilization proposed in 8

**Comment by compiler-errors** [comment]
For the record, T-lang decided to retroactively reserve `'prefix#lifetime` lifetimes as an extension to this work, which is implemented in https://github.com/rust-lang/rust/pull/126452. That PR also implements raw lifetimes, like `'r#async`.
