### ISSUE TITLE
Tracking Issue for `async {}` blocks in const expressions

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#85368]
This is a tracking issue for use of `async {}` expressions in const contexts.
The feature gate for the issue is `#![feature(const_async_blocks)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the feature (https://github.com/rust-lang/rust/pull/85353)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

**Comment by CryZe** [comment]
Technically this already existed, but I'll close mine in favor of this one: https://github.com/rust-lang/rust/issues/69431

**Comment by jonas-schievink** [comment]
Ah okay, normally we don't have tracking issues for things that aren't implemented

**Comment by Swatinem** [comment]
Hi! 👋🏻 
I discovered while working on https://github.com/rust-lang/rust/pull/104321 that async blocks can trivially be const as soon as the https://github.com/rust-lang/rust/issues/104826 workaround is fixed.

Depending on whats happening with https://github.com/rust-lang/rust/issues/104826, what would be the next steps in moving forward with the feature flag/stabilization?

**Comment by CryZe** [comment]
Is there anything preventing this from getting stabilized? I'd like to do the remaining work to push this to stabilization.
