### ISSUE TITLE
prepare  PR that will "dry run" the crater migration

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#85895]
As part of the 2021 Edition release, we want to do a "dry run" crater run that attempts to do migrations and then builds and runs tests. This will help us check the lints.

We cannot actually run this setup until the following issues are closed, but we can still do the work to prepare the PR now:

* [x] Create group containing all Rust 2021 edition lints #85894 
* [x] Force-warn for edition lints #85512 
* [x] Tracking Issue for RFC 3101: Reserved Prefixes #84978 

and other items in the "Feature Complete Blockers" column from the [Rust 2021 Project Board](https://github.com/orgs/rust-lang/projects/7).

**Comment by nikomatsakis** [comment]
Some notes here on Zulip:

https://zulip-archive.rust-lang.org/268952edition2021/01650Rust2021dryruncraterrun.html

**Comment by nikomatsakis** [comment]
### Mentoring notes

I'm no expert on the crater code, but here are some notes extracted from the thread above (thanks @pietroalbini).

#### The goal

We want to modify crater so that, for each 2018 crate, it runs `cargo fix --edition` to see if it builds.

* Run `cargo fix --edition`
* Run `cargo check` afterwards, to see that it still builds (maybe? I think that cargo fix may do this itself...)

#### Modifying crater

To start, you would add a mode like `EditionMigration` to this enum:

https://github.com/rust-lang/crater/blob/aa40b144e61f7f1c6ba6a3bfc5e85b52b9e4a177/src/experiments.rs#L29-L36

When you do, the compiler will take you on a little tour of the crater code. The critical bit is here, where we create different kinds of tasks depending on the mode:

https://github.com/rust-lang/crater/blob/ba03080696d339981948fff0b3da3611e45fdbb9/src/runner/graph.rs#L291-L324

We'll have to add a new kind of TaskStep for "cargo fix --edition" and propagate things around:

https://github.com/rust-lang/crater/blob/29fcb562fd88f43c0560320fd262f58add55a1a3/src/runner/tasks.rs#L51-L61

At some point that will require writing a function like this that actually invokes `cargo fix`:

https://github.com/rust-lang/crater/blob/29fcb562fd88f43c0560320fd262f58add55a1a3/src/runner/test.rs#L321-L343

**Comment by nikomatsakis** [comment]
@ehuss [pointed out on Zulip](https://zulip-archive.rust-lang.org/268952edition2021/64759craterrun.html) that another, perhaps better, approach would be to do a crater run with a modified cargo. This would make it easier to get a "stable" comparison.

The idea would be to modify cargo so that e.g. `cargo build` or `cargo test` runs `cargo fix --edition`.

**Comment by pietroalbini** [comment]
Actually, now that I think about it the best way to implement this in Crater would be to add a new "toolchain flag" that runs `cargo fix --edition`, allowing you to define a toolchain like `try#1234567890abcdef+edition-fix`. That way you'd run the experiment between `try#1234567890abcdef` and `try#1234567890abcdef+edition-fix`, and you could use all the existing modes on top of that (`check-only`, `build-and-test`...).

You'd need to add a boolean flag [here](https://github.com/rust-lang/crater/blob/aa40b144e61f7f1c6ba6a3bfc5e85b52b9e4a177/src/toolchain.rs#L27-L32) and implement [display](https://github.com/rust-lang/crater/blob/aa40b144e61f7f1c6ba6a3bfc5e85b52b9e4a177/src/toolchain.rs#L71) and [parse](https://github.com/rust-lang/crater/blob/aa40b144e61f7f1c6ba6a3bfc5e85b52b9e4a177/src/toolchain.rs#L118-L134) for `+edition-fix`. Once that's done [before starting a test](https://github.com/rust-lang/crater/blob/aa40b144e61f7f1c6ba6a3bfc5e85b52b9e4a177/src/runner/test.rs#L222) you need to add code to check whether the flag is set on the toolchain, and in that case run `cargo fix --edition`.

**Comment by ehuss** [comment]
I have prepared a hacked cargo that should work: https://github.com/ehuss/cargo/commit/e32d9d54c8dfbe0c890cb88c327e22d05399313c

Another snag I ran into was that crater runs with a read-only filesystem.  The source needs to be writeable to apply any fixes. The hack copies the source to `/tmp` to work around that.  I'm uncertain if that will cause problems, but I think it should work (at least it seemed fine in my testing).

Getting crater to support this use case would be nice, but I think will require quite a few changes (such as making the `toolchain_start` run different commands than `toolchain_end`).  And it's not really clear how to integrate the things like modifying `Cargo.toml`.  I think the hack should suffice for now, and maybe for the next edition we can plan for something better. 😉
