### ISSUE TITLE
Tracking Issue for `BuildHasher::hash_one`

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#86161]
Feature gate: `#![feature(build_hasher_simple_hash_one)]`

This is a tracking issue for the `hash_one` method on the `BuildHasher` trait.  This is a convenience method to make it easier to get the hash of a value, such as when implementing a hash table or when writing unit tests.

### Public API

```rust
pub trait BuildHasher { // existing trait
    fn hash_one<T: Hash>(&self, x: T) -> u64
    where
        Self: Sized; // new method, with provided implementation
}
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/86151
- [x] Add missing `Self: Sized`: https://github.com/rust-lang/rust/pull/88031
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by dtolnay** [comment]
Added `where Self: Sized` in #88031 in order to preserve object safety of BuildHasher.

**Comment by thomcc** [comment]
This API is unexpected useful for performance.

There are certain hash algorithms which can provide a (substantially) more efficient implementation if they know they aren't being used in a streaming scenario, and that they just need to hash a single input (such as a range of bytes).

xxHash is one of these — the streaming API is very much set up for the "hash a big file" use case, and has a large flat overhead to initialize the state for computing the streaming hash. That is, in a direct port, `BuildHasher::build_hasher` is very slow — much slower than the actual hashing for small keys.

However, it has a separate API for hashing a chunk of memory (with an optional seed), which you're supposed to use for hashtable keys and such. This API produces the same results as streaming (it wouldn't be much of a hash if this weren't the case), but is *quite* fast... far faster if this is all you need and you have small strings and such, as are common for hash-table keys.

I had some plans on how to subvert the issues here... But I don't need to if this API exists (and is used in HashMap), so long as I provide a bunch of specializations on `T` (a pain, but worth it here).

I dunno if this was completely unintentional, or just not mentioned, but I had considered this basically unsolvable the way Rust's hashing APIs were designed<sup>\[1\]</sup>, so it's nice to be wrong.

I'll try to get benchmark numbers for this soonish.

---

\[1\]: I figured that we had traded perf for flexibility here, and that it was... a bit unfortunate, but probably worth it given that Rust's hashing APIs are far more convenient (and far less error-prone) than the ones in other langs which are hashcode-based.

**Comment by tkaitchuck** [comment]
Yes, this could have performance gains, but they could be even better with a slight modification: remove the `&self` parameter. 

Modifying the example in the docs using it would look like:
```
#![feature(build_hasher_simple_hash_one)]

use std::cmp::{max, min};
use std::hash::{BuildHasher, Hash, Hasher};
struct OrderAmbivalentPair<T: Ord>(T, T);
impl<T: Ord + Hash> Hash for OrderAmbivalentPair<T> {
    fn hash<H: Hasher>(&self, hasher: &mut H) {
        min(&self.0, &self.1).hash(hasher);
        max(&self.0, &self.1).hash(hasher);
    }
}

use std::collections::hash_map::RandomState;
// Then later, in a `#[test]` for the type...

assert_eq!(
    RandomState::hash_one(OrderAmbivalentPair(1, 2)),
    RandomState::hash_one(OrderAmbivalentPair(2, 1))
);
assert_eq!(
    RandomState::hash_one(OrderAmbivalentPair(10, 2)),
    RandomState::hash_one(&OrderAmbivalentPair(2, 10))
);

```

The advantage of this is that the hashing algorithm knows up front that all the data that will ever be provided is being passed in a single call. This solves the problem that motivated the attempt to improve performance here: https://github.com/rust-lang/hashbrown/pull/207 and here: https://github.com/rust-lang/hashbrown/pull/232 but was has not yet been implemented due to technical difficulties. 

The only reason I can see to keep the `&self` parameter is if for some reason it is desirable to support doing this:
```
let rs = RandomState::new();
x.hash(&mut rs);
let result = rs.hash_one(y);
```
I can't think of a use case that would require this pattern. And speaking as an implementer of a hasher, I very much don't want to implement support for doing that.

**Comment by tkaitchuck** [comment]
Yes. This could give a significant performance gain particularly if the implementation was not held to the requirement that the resulting output be identical to what would have resulted by passing the value into the hasher and then calling `finish()`. This means that hashers can take advantage of knowing that all the data is present and more is not coming to reduce the amount of work done.

**Comment by thomcc** [comment]
I think it needs to return the same value, otherwise things like `Borrow` won't work. Users currently can implement Hash for their own types in terms of hashing a nested type, and have their `Borrow` implementation be correct. I suspect there's other things like this too.

I also think it would be very surprising if it returned different values, and suspect that it still can be done as efficiently in most cases, just more work to derive an efficient "closed-form" version of the computation.

**Comment by Amanieu** [comment]
I think this is a generally useful helper function that makes it easier for code to work with hashers. In particular, it replaces this rather cumbersome code for hashing a value:

```rust
fn compute_hash<K: Hash + ?Sized, S: BuildHasher>(hash_builder: &S, key: &K) -> u64 {
    let mut state = hash_builder.build_hasher();
    key.hash(&mut state);
    state.finish()
}
```

@rfcbot fcp merge

**Comment by JohnTitor** [comment]
Triage: Closing as it was stabilized already.

**Comment by oulaoba** [comment]
@lucas7788

# Error reason

The latest release of [ahash](https://github.com/tkaitchuck/ahash) uses [build_hasher_simple_hash_one](https://github.com/rust-lang/rust/issues/86161) which was stabilized in 1.71 but the latest rustc version from the Solana tools is 1.68.0.

You can fix it by :
``` toml
[dependencies]
ahash = "=0.8.4"
```

**Comment by mikemaccana** [comment]
This still seems to be failing in solana-cli 1.17.17, anchor-cli 0.29.0. 

```
% anchor --version
anchor-cli 0.29.0

% solana --version
solana-cli 1.17.17 (src:27a43800; feat:1337574167, client:SolanaLabs)

% anchor init anchor-test --template=multiple

% cd anchor-test

% anchor build
<...snip...>
   Compiling solana-frozen-abi v1.17.14
   Compiling num-traits v0.2.17
   Compiling memoffset v0.9.0
   Compiling cpufeatures v0.2.12
error[E0658]: use of unstable library feature 'build_hasher_simple_hash_one'
   --> src/random_state.rs:463:5
    |
463 | /     fn hash_one<T: Hash>(&self, x: T) -> u64 {
464 | |         RandomState::hash_one(self, x)
465 | |     }
    | |_____^
    |
    = note: see issue #86161 <https://github.com/rust-lang/rust/issues/86161> for more information
    = help: add `#![feature(build_hasher_simple_hash_one)]` to the crate attributes to enable

   Compiling jobserver v0.1.27
For more information about this error, try `rustc --explain E0658`.
error: could not compile `ahash` due to previous error
```
