### ISSUE TITLE
Tracking Issue for const_ptr_write

### ISSUE THREAD

**Issue by usbalbin** [rust-lang/rust#86302]
Feature gate: `#![feature(const_ptr_write)]`

This is a tracking issue for making the functions `ptr::write` and `ptr::write_unaligned`, and the same methods on `*mut T`, `const fn`.

### Public API

```rust
mod ptr {
    pub const unsafe fn write<T>(dst: *mut T, src: T);
    pub const unsafe fn write_unaligned<T>(dst: *mut T, src: T);
    pub const unsafe fn write_bytes<T>(dst: *mut T, val: u8, count: usize);
}

impl<T> *mut T {
    pub const unsafe fn write(self, val: T);
    pub const unsafe fn write_unaligned(self, val: T);
    pub const unsafe fn write_bytes(self, val: u8, count: usize);
}

impl <T> NonNull<T> {
    pub const unsafe fn write(self, val: T);
    pub const unsafe fn write_unaligned(self, val: T);
    pub const unsafe fn write_bytes(self, val: u8, count: usize);
}
```

### Steps / History

- [x] Implementation: #81167
- [x] Reverted: #86003
- [x] Re-constified: #86295
- [x] `core::intrinsics::write_bytes` aka `ptr::write_bytes` - #90081 
- [x] `(*mut T)::write_bytes` - #91824
- [x] blocked on https://github.com/rust-lang/rust/issues/57349
- [x] `NonNull` methods stabilized, `const`ness moved to this gate https://github.com/rust-lang/rust/pull/124498
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

#### Related
* const_ptr_read #80377

### Unresolved Questions

- None yet.

**Comment by woppopo** [comment]
`core::intrinsics::write_bytes` and `(*mut T)::write_bytes` have been constified: #90081 #91824

**Comment by SUPERCILEX** [comment]
How does one initiate the FCP? Or are there any blockers?

**Comment by c410-f3r** [comment]
AFAICT, there are no blockers so this feature can probably be stabilized.

**Comment by RalfJung** [comment]
How does stabilizing this help? You can't create mutable pointers on stable anyway...

**Comment by RalfJung** [comment]
IOW, this is blocked on https://github.com/rust-lang/rust/issues/57349 getting stabilized first.

**Comment by wyfo** [comment]
> How does stabilizing this help? You can't create mutable pointers in const on stable anyway...

It seems you can with [`UnsafeCell::raw_get`](https://doc.rust-lang.org/std/cell/struct.UnsafeCell.html#method.raw_get).

**Comment by RalfJung** [comment]
Oh fun, another accidental stabilization...

Well, https://github.com/rust-lang/rust/issues/57349 should be stable soon, so it's not worth de-stabilizing like we did with https://github.com/rust-lang/rust/issues/80697.

**Comment by RalfJung** [comment]
@rust-lang/libs-api with https://github.com/rust-lang/rust/pull/129195 in FCP, I'd like to get the ball rolling for stabilizing this feature as well, so that it can be released together with const_mut_refs. After all, what good is a mutable raw pointer if you cannot `.write()` it? Okay, you can use `*ptr = ...;`, and in const context we don't allow `Drop` types, so this can't cause destructor problems... but still, these functions seem like basic functionality to go with "you can have mutable pointers and references now", so would be nice to ship them all in one package.

So, can we get a t-libs-api FCP started for this? :)

**Comment by dtolnay** [comment]
@rfcbot fcp merge

`const` for these 6 already-stable functions, in the same order as shown at the top of this issue:

- https://doc.rust-lang.org/nightly/std/ptr/fn.write.html
- https://doc.rust-lang.org/nightly/std/ptr/fn.write_unaligned.html
- https://doc.rust-lang.org/nightly/std/ptr/fn.write_bytes.html
- https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.write
- https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.write_unaligned
- https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.write_bytes

**Comment by RalfJung** [comment]
@Amanieu @BurntSushi @joshtriplett @m-ou-se this proposes to stabilize some very basic `*mut T` operations that would be nice to ship together with the const_mut_refs stabilization. Given that these have been stable outside `const` since forever, it should be entirely uncontroversial. :)

**Comment by RalfJung** [comment]
FYI, turns out there are three more functions under this feature gate -- `NonNull` has the exact same set of functions as `*mut`.
```rust
impl <T> NonNull<T> {
    pub const unsafe fn write(self, val: T);
    pub const unsafe fn write_unaligned(self, val: T);
    pub const unsafe fn write_bytes(self, val: u8, count: usize);
}
```
