### ISSUE TITLE
Tracking Issue for RFC 2528: type-changing struct update syntax

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#86555]
This is a tracking issue for RFC 2528 (rust-lang/rfcs#2528), type-changing struct update syntax.
The feature gate for the issue will be `#![feature(type_changing_struct_update)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC, including tests (cc @rust-lang/compiler -- can anyone write up mentoring instructions?)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- [ ] Type inference: when implementing this, we need to confirm that it won't adversely affect type inference.

"Further generalization" in the RFC would be the subject of future RFCs, not something we need to track in this tracking issue.

### Implementation history

(No PRs yet.)

**Comment by Rua** [comment]
#90035 seems to have implemented this, so that box can be crossed off.

**Comment by joshtriplett** [comment]
It looks like this has been implemented; are there any further known issues or blockers with it?

**Comment by Rua** [comment]
I'm eagerly awaiting stabilisation of this feature! Is there anything that still needs to be done?

**Comment by crlf0710** [comment]
> It looks like this has been implemented; are there any further known issues or blockers with it?
Yes, i created #101970 to track it

**Comment by luojia65** [comment]
This feature would be useful in bootloader development when different stages of bootloading would handover structures with small modifications. For example, bootstrap module would provide main function like:

```rust
fn main(param: Parameters) -> Handover {
    // ....
}
```

where `Handover` share most of fields with `Parameters`, but only small subset of fields are changed in declaration. This will be ideal to express the way Rust ownership works in embedded: one peripheral is wrapped in a structure to show it cannot be initialized or dropped twice. Thus, the wrapper struct should be provided as-is in `Handover`. We can do like this:

```rust
fn main(param: Parameters) -> Handover {
    let serial = Serial::new(param.uart0, /* ... */);
    // ....
    Handover { serial, ..param }
    // instead of: Handover { serial, periph_1: param.periph_1, periph_2: param.periph_2, periph_3: param.periph_3, /* ... */ }
}
```

We can now avoid repeat passing peripheral fields in bootload stage handovering, where there would typically be dozens of peripherals whose ownerships are going to be transfered.

I'll express my idea in playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3e55ac9e8f6cf1c69870390d75cf77d5

In this way, type changing struct update syntax will have an obvious code size reduction, which will help a lot in embedded development.

**Comment by rodrimati1992** [comment]
@luojia65 This feature is only for changing the generic arguments of the struct, i.e: going from `Foo<Bar>` to `Foo<Baz>`.

What you want sound like what's [in the Rationales and Alternatives section of the RFC for this feature](https://github.com/rust-lang/rfcs/blob/master/text/2528-type-changing-struct-update-syntax.md#further-generalization), except that it doesn't talk about going between structs with sub/supersets of fields.

**Comment by rcywongaa** [comment]
Does this work with closures as well?
If so, it would work nicely with the arg struct pattern to make it much easier to provide default arguments for functions that take closures
i.e.
```
struct Args<A: FnMut(), B: FnMut()> {
    pub a: A,
    pub b: B,
}

static NO_OP: fn() = ||{};
static DEFAULT_ARGS: Args<fn(), fn()> = Args { a: NO_OP, b: NO_OP };

// -- snip --

let arg = Arg {
  a: || println!("My non-default closure"),
  ..DEFAULT_ARGS
}
func_with_closure_args(arg);
```
([SO question for more context](https://stackoverflow.com/q/78143011/3177701))
