### ISSUE TITLE
Tracking Issue for "Overconstraining and omitting unsafe in impls of unsafe trait methods" (RFC 2316)

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#87919]
This is a tracking issue for the RFC "Overconstraining and omitting unsafe in impls of unsafe trait methods" (rust-lang/rfcs#2316).
The feature gate for the issue is `#![feature(⚠ not yet chosen ⚠)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC (can anyone write up mentoring
      instructions?)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

None known at this time

**Comment by tmandry** [comment]
This RFC was revised and generalized by rust-lang/rfcs#3245, which is now tracked in #100706.

**Comment by clarfonthey** [comment]
Should this be closed if it's superceded by a more general RFC? Or will this just track implementing it for unsafety specifically?

**Comment by Dylan-DPC** [comment]
Closing this as #100706 tracks this.
