### ISSUE TITLE
Tracking Issue for `Saturating` type

### ISSUE THREAD

**Issue by kellerkindt** [rust-lang/rust#87920]
This is a tracking issue for the RFC "928" (rust-lang/rfcs#928).
The feature gate for the issue is `#![feature(saturating_int_impl)]`.

### About tracking issues

Tracks progress for `Saturating` type analogue to #32463

### Unresolved Questions

 - [ ] What is the MVP for stabilization?
 - [ ] What is the correct impl of `Shl` and `ShalAssign` for `Saturating<signed>`
       https://github.com/rust-lang/rust/pull/87921#discussion_r695870065
     Possible solution: https://github.com/rust-lang/rust/issues/87920#issuecomment-913015985
     @avitex https://github.com/avitex/rfcs/blob/master/text/0000-saturating-bit-shifts.md

### Steps

- [x] implement (#87921)
- [x] Stabilize `saturating_div` (#89381)
- [ ] Split of saturating bit shifts (#103441)
- [ ] Stabilize `saturating_int_impl`

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

 - Implementation #87921
   - Adds `struct Saturating` and `feature(saturating_int_impl)`
 - Stabilization (TODO)

**Comment by joshtriplett** [comment]
FCP for stabilizing `saturating_div`:
@rfcbot merge

**Comment by Amanieu** [comment]
What about the remaining unresolved question regarding the correct behavior of `Shl`?

**Comment by kellerkindt** [comment]
@kennytm outlined possible implementations for that (https://github.com/rust-lang/rust/pull/87921#discussion_r695870065), but I am not sure what seems to be the correct implementation and I would be happy for any input in that regards.

**Comment by Amanieu** [comment]
I would like to see the situation with saturating shift clarified first before we stabilize this. There is an [unsubmited RFC](https://github.com/avitex/rfcs/blob/master/text/0000-saturating-bit-shifts.md) about this (cc @avitex) which has been discussed a bit in Zulip ([1](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Pre-RFC.3A.20saturating_shl.2Fshr.20on.20integer.20types) [2](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Adding.20saturated.20shift.20operations.20to.20libcore.3F)) but without coming to a conclusion.

@rfcbot concern saturating shifts

**Comment by kellerkindt** [comment]
Hmm, it might be a bit confusing, but I initially intended to only stabilize `saturating_div` for now and not the whole `Saturating` type (yet).

@joshtriplett also mentioned it that way [here](https://github.com/rust-lang/rust/issues/87920#issuecomment-912943834)?

**Comment by Amanieu** [comment]
Oh right, I missed that message. TBF it's a bit confusing to have two very different features sharing the same tracking issue.

@rfcbot resove saturating shift

**Comment by kellerkindt** [comment]
> Oh right, I missed that message. TBF it's a bit confusing to have two very different features sharing the same tracking issue.

Yes, you are right about that, sorry 😅🙈

@avitex I would appreciate your implementation for shl and shr in the number types for the `Saturating` type 🙂👍

**Comment by Amanieu** [comment]
@rfcbot resolve saturating shift

**Comment by Amanieu** [comment]
@rfcbot resolve saturating shifts

**Comment by yaahc** [comment]
> Oh right, I missed that message. TBF it's a bit confusing to have two very different features sharing the same tracking issue.
> 
> @rfcbot resove saturating shift

Should we go ahead and split this tracking issue?

**Comment by kellerkindt** [comment]
That's fine with me, I had the wrong impression that the rfcbot would be run on #88624. What effect does it have on the running poll?

**Comment by yaahc** [comment]
> That's fine with me, I had the wrong impression that the rfcbot would be run on #88624. What effect does it have on the running poll?

We would close the poll on this tracking issue and re-open it on the new one and check off the boxes for those who've already approved it here, so effectively none.

**Comment by kellerkindt** [comment]
Okay, I have just created it: #89381

**Comment by yaahc** [comment]
@rfcbot cancel

**Comment by Rudxain** [comment]
I have a question. Why was the name `saturating` chosen? I had no idea what it was until I read the docs and realized it's just `clamped` arithmetic. Since it's still a nightly feature, can it be renamed to `clamping`?

**Comment by kellerkindt** [comment]
> I have a question. Why was the name `saturating` chosen? I had no idea what it was until I read the docs and realized it's just `clamp`ed arithmetic. Since it's still a nightly feature, can it be renamed to `clamping`?

Because all the underlying calls on the Integer are also already prefixed with `saturating_*` :)

https://doc.rust-lang.org/stable/std/intrinsics/fn.saturating_add.html

**Comment by tarcieri** [comment]
@Rudxain saturation describes *how* the resulting value is clamped: if the result of an operation is greater than the maximum, it is clamped to the maximum, and conversely, if it is below the minimum, it is clamped to the minimum.

https://en.wikipedia.org/wiki/Saturation_arithmetic

**Comment by Rudxain** [comment]
> Because all/most the underlying calls on the Integer are also already prefixed with `saturating_*` :)

Yeah, I realized that renaming would take too much work+time now

> saturation describes _how_ the resulting value is clamped.
> https://en.wikipedia.org/wiki/Saturation_arithmetic

I like how Rust takes inspiration/influence from math, it ensures stuff is well-defined

**Comment by kellerkindt** [comment]
So, as the discussion about the correct shift impl [re-ignites](https://github.com/rust-lang/libs-team/issues/230), I was reminded (thx!) that complete feature parity with the `Wrapping` type is not required for stabilization.

@T-libs-api So, I propose to stabilize the `Saturating` type as is, but **without** any `Shl`, `ShlAssign`, `Shr` and `ShrAssign` impl, because we are missing a real world use case [for](https://github.com/rust-lang/libs-team/issues/230#issuecomment-1648760568) [the](https://github.com/rust-lang/libs-team/issues/230#issuecomment-1650662059) [correct](https://github.com/rust-lang/libs-team/issues/230#issuecomment-1652070808) [shift](https://github.com/rust-lang/libs-team/issues/230#issuecomment-1652133233) [impls](https://github.com/rust-lang/libs-team/issues/230#issuecomment-1652184375) [!!!!](https://github.com/rust-lang/rust/pull/103441#issuecomment-1288175327) ([and also](https://github.com/avitex/rfcs/blob/master/text/0000-saturating-bit-shifts.md)).

The current impl of the `Saturating` type is in nightly for **almost two years** and nobody complained about it (tbf, with the `Wrapping` type as blueprint, the `Saturating` type is nothing world shattering new).

As a very short summary, the `Saturating` type is an Integer wrapper that uses `saturating_*` fn calls for all of its arithmetic operations. It boils down to this* [(playground link)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=85f7b99bfb7feb050d61af8b230159ae):

```rust
    let mut s = Saturating(1_u8) + Saturating(1_u8); // 1 + 1
    s += Saturating(3); // 2 + 3
    s -= Saturating(1); // 5 - 1
    s -= 1;             // 4 - 1
    
    assert_eq!(3, s.0);
    
    s /= 3;              //  3 / 3
    s /= Saturating(1);  //  1 / 1
    s *= Saturating(10); //  1 * 10
    s *= 10;             // 10 * 10

    // nothing fancy so far
    
    assert_eq!(100, s.0);
    
    s *= 200; // 100 * 200     SATURATES with 255
    
    assert_eq!(255, s.0);
    
    s -= 200; // 255 - 200
    s -= 200; //  55 - 200     SATURATES with 0
    
    assert_eq!(0, s.0);
```

*As well as a few more impls like `Rem`, `RemAssign`, `Not`, `BitXor`, `BitXorAssign`, `BitOr`, `BitOrAssign`, `BitAnd`, `BitAndAssign` and a few constants.

**Comment by kellerkindt** [comment]
r? libs

**Comment by Amanieu** [comment]
The only contentious part of `Saturating` was the shifts, which are explicitly excluded. The most likely future plan for those is to expose them as methods with informative names.

@rfcbot fcp merge
