### ISSUE TITLE
Stabilize Rust 2021

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#87959]
- [x] FCP on closure capture changes: https://github.com/rust-lang/rust/issues/88126
- [x] FCP on reserved prefixes: https://github.com/rust-lang/rust/issues/88140
- [x] FCP on force-warn: https://github.com/rust-lang/rust/issues/86516#issuecomment-900382193
- [x] Decide that Rust 1.56 will ship Rust 2021 as stable: [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/268952-edition-2021/topic/Release.20Decision/near/251224903)
- [x] Make `--edition=2021` stable in rustc: https://github.com/rust-lang/rust/pull/88100
- [x] Remove/stabilize experimental 2021 cargo feature: https://github.com/rust-lang/cargo/pull/9800
    - [x] Update `cargo` submodule: https://github.com/rust-lang/rust/pull/88563
- [x] Update edition guide and other documentation to reflect stability.
    - [x] Edition guide: https://github.com/rust-lang/edition-guide/pull/266
        - [x] Update edition-guide submodule: https://github.com/rust-lang/rust/pull/88563
    - [x] Check if there's any other documentation that needs updating

**Comment by crlf0710** [comment]
cc #85811

**Comment by HTG-YT** [comment]
May I help with the third item when it is needed to be implemented?

**Comment by m-ou-se** [comment]
@HTG-YT Can you open that as a (draft) PR? Then we can review it so it's ready to be merged when we get to that point. Thanks!

**Comment by HTG-YT** [comment]
Alright!

**Comment by m-ou-se** [comment]
![](https://github.githubassets.com/images/icons/emoji/unicode/1f389.png)
