### ISSUE TITLE
New destructor semantics

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#8861]
Tracking issue for [RFC #769](https://github.com/rust-lang/rfcs/pull/769), Sound Generic Drop.

Original description follows:
----

We agreed in a meeting to replace the unsafe destructor code with the rule that a value with a destructor must only contain values of lifetime *strictly greater* than the value to be destructed. The idea is to prevent values from referencing one another. Permitting borrowed values in destructors enables a number of RAII causes and helps to eliminate the need for once fns. This also relies on the change to prevent `&` pointers from being placed within managed boxes (which I think has already been made).

I have to figure out precisely how to formalize this rule still. =)

Nominating for backwards compat.

----

Update from @pnkfelix : Much of this is implemented, and so pnkfelix is listing out specific subtasks, issues, and/or PRs, to try to track what is done and what is left to do:

 * [x] Track finer-grained scopes (i.e. block suffixes): See PR https://github.com/rust-lang/rust/pull/21657 
 * [x] Land the drop-checker ("dropck").  See PR #21972
 * [x] Keep `Drop` from adding new bounds on a type param; Issue #8142 
 * [x] Revise for-loops so that temporaries from the `<iterator-expr>` only live for the for-loop itself.  (i.e. turn for-loops into a terminating scope).  Addresses the bulk Issue https://github.com/rust-lang/rust/issues/21114.  Resolved by #21984
 * [x] Remove `#[unsafe_destructor]` attribute entirely; Issue #22196

Far future / No longer deemed necessary
 * [ ] Make `Vec<T>`, `Box<T>`, `Rc<T>`, etc, covariant with respect to `T`.  Discussed on issue #21198 (may not be a strict requirement for landing new destructor semantics).
 * [ ] Track even finer grained scopes, e.g. destruction order of temporary rvalues in an expression.  Issue #22323

(See also #22321)

**Comment by pythonesque** [comment]
Does this rule mean code like this would be invalid?

```rust
extern crate arena;

fn main() {
    struct Foo<'a> { foo: ::std::cell::Cell<Option<&'a Foo<'a>>> }
    let foo = arena::TypedArena::new();
    let bar = foo.alloc(Foo { foo: ::std::cell::Cell::new(None) });
    bar.foo.set(Some(&*bar));
}
```

If so, I'm not really on board with it, as this is a very useful pattern (and is perfectly safe in this case), as this change seems to force the use of `*const` or `*mut` instead of lifetimes if you ever want cycles.  This makes these cases *less* safe because the borrow checker will no longer verify that the stored collection doesn't move and isn't dropped until you're done with it.

**Comment by pythonesque** [comment]
As an addendum: this only seems to be a memory safety issue when two things occur together:

* A struct field has lifetime equal to that of the struct itself.
* The struct has an *explicit* destructor.

If the struct does not have an explicit destructor, then for each field, either the field is a reference (in which case there is no drop glue, so it can't cause memory unsafety), the field is a non-reference and has a lifetime equal to itself (in which case we can recursively perform the same check), or the field is a non-reference with a lifetime strictly greater than itself (in which case it's fine and we can move on to the next field).

I realize this still eliminates `TypedArena` from consideration (`TypedArena` would still need an unsafe drop implementation, and probably some method of running the check described above on its type parameter) but it allows for many other safe patterns.

**Comment by aturon** [comment]
Nominating for -beta milestone.

**Comment by pnkfelix** [comment]
Moving ahead to the 1.0-beta milestone.

**Comment by pnkfelix** [comment]
for people who come to this issue url due to its many references on github, the code base, and IRC: I suspect the most relevant thing for you to look at right now is the Sound Generic Drop RFC PR: rust-lang/rfcs#769

**Comment by pnkfelix** [comment]
The description for #21972 accidentally closed this ticket, but there is still work to be done; reopening.

Also, assigning to myself since I pretty much own this topic at this point.

**Comment by pnkfelix** [comment]
reclassifying P-high, not 1.0 since everything for 1.0 is pretty much done (hopefully `unsafe_destructor will indeed be gone).

**Comment by pnkfelix** [comment]
closing; the remaining (hypothetical or far-future) work items are tracked on #22321
