### ISSUE TITLE
Tracking Issue for RFC 3123: Scrape code examples from `examples/` directory for Rustdoc

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#88791]
This is a tracking issue for the RFC "Scrape code examples from `examples/` directory for Rustdoc" (rust-lang/rfcs#3123).

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC (#85833 and rust-lang/cargo#9525)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

1. Is showing 1 example by default the best idea? Or should scraped examples be hidden by default? 
2. Is the ability to see the full file context worth the increase in page size?
3. How should the examples be ordered? Is there a way to determine the "best" examples to show first?

**Comment by vicky5124** [comment]
Some crates make `rustdoc` panic with this feature being used, a couple of these are:

[serenity](https://github.com/serenity-rs/serenity), which leads to these logs: https://pastebin.com/smwdrWbD
Using a relatively standard `cargo doc` command:
`RUST_BACKTRACE=full RUSTDOCFLAGS="--cfg docsrs -D rustdoc::broken_intra_doc_links" cargo +nightly doc -Z unstable-options -Z rustdoc-scrape-examples=all --open --no-deps --all-features`

A similar issue happens with  [lavalink-rs](https://gitlab.com/vicky5124/lavalink-rs), where the serenity example panics `rustdoc` with these logs: https://pastebin.com/sHJ0YZh6
But if it's removed from the workspaces on `Cargo.toml`, it compiles with the twilight example, but with an issue: none of the methods used in the example show up in the docs.

To show that this is not an issue strictly with serenity, [poise](https://github.com/kangalioo/poise), a library which depends on serenity, uses it on its examples, and re-exports it, does not have this issue, as show by it having its [docs](https://kangalioo.github.io/poise/develop/poise/enum.Context.html#method.say) built this way.

Note: `rustdoc-scrape-examples=all` is used instead of `rustdoc-scrape-examples=examples` because both of the libraries with issues use subcrates as examples; I thought this was the reason as to why the panic happens, but a minimal crate with the same kind of examples worked just fine. I also tried to see if proc-macros were causing the panic, but that's not the case either.

**Comment by willcrichton** [comment]
@vicky5124 thanks for the bug reports. I have fixed these issues (macro-related) in #90583 which should hopefully land by the time today's nightly (2021-11-05) is released.

**Comment by programatik29** [comment]
I did a quick test.

Scraping examples with this `Cargo.toml` does not work:
```toml
[package]
name = "scrape-me"
version = "0.1.0"
edition = "2021"

[dependencies]
```

This works:
```toml
[package]
name = "scrape_me" # '_' instead of '-'
version = "0.1.0"
edition = "2021"

[dependencies]
```

**Comment by willcrichton** [comment]
@programatik29 thanks for the report. This is issue rust-lang/cargo#10035 which has been fixed in rust-lang/cargo#10037. We just have to wait for the cargo submodule in rustc to get updated (cc @ehuss).

**Comment by programatik29** [comment]
Nice. This feature is amazing. Can't wait to use it in my docs.

**Comment by PicoJr** [comment]
## Building doc locally works fine

```
cargo +nightly doc -Z unstable-options -Z rustdoc-scrape-examples=examples
```
does pick up the right code snippet from my `examples/` folder for my crate [htp](https://docs.rs/crate/htp/0.4.1).

It looks great btw.

## Online rustdoc (does not seem to work with my crate)

I have not managed to have my crate's doc benefit from this new feature, here is my Cargo.toml:

https://github.com/PicoJr/htp/blob/6faea37ad8f1c63a9992d16391389fda5d79011d/Cargo.toml#L21-L23

I use the section described [here](https://twitter.com/wcrichton/status/1456112698165321728?s=20).

**Comment by PicoJr** [comment]
> @PicoJr yes, it is your `include` section. docs.rs will download the published version of your crate, and if the examples aren't included, then they can't be scraped.
> 
> Note to everyone reading this: if you see the following warning in your `cargo doc` logs, then your examples are either misconfigured or not published:
> 
> ```
> Warning: Target filter `examples` specified, but no targets matched. This is a no-op
> ```

@willcrichton thanks for your reply [it does work now](https://docs.rs/htp/0.4.2/htp/fn.parse.html).

**Comment by joseluis** [comment]
Hi, I just found this RFC and funnily enough I recently devised a way to achieve this in current stable. So I wanted to share my solution. The following minimal project shows how to include documentation and tests from the examples directory:

**project files:**

```toml
# Cargo.toml
[package]
name = "mycrate"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
```

```rust
//! /src/lib.rs

/// Hello from lib.
#[derive(Debug)]
pub struct Hello;

#[path = "../examples"]
#[cfg(any(doc, test))]
pub mod examples {
    #![allow(dead_code)]

    pub mod world;
}
```

```rust
//! /examples/world.rs

// external dependencies:
#[cfg(not(doc))]
use rand::random;

// internal dependencies:
#[cfg(any(test, doc))]
use crate::Hello;
#[cfg(not(any(test, doc)))]
use mycrate::Hello;

/// World example.
#[derive(Debug)]
pub struct World;

fn main() {
    let (h, w) = (Hello, World);
    println!("{:?} {:?} {}", h, w, random::<u8>());
}

#[cfg(test)]
mod test {
    #[test]
    fn testing_world() {
        assert![true];
    }
}
```

**testing it out:**

```sh
$ cargo doc --open # shows the example documentation ok

$ cargo run --quiet --example world # runs the example ok
Hello World 159

$ cargo test testing_world # runs the example test ok

running 1 test
test examples::world::test::testing_world ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by camelid** [comment]
@joseluis That's different from this feature. This feature is about showing snippets of examples in the documentation for functions that are called from the examples.

**Comment by willcrichton** [comment]
The feature has now been on nightly for about two months. I've been able to fix all the bug reports raised thus far, and I have not received any further suggestions on the UI design. Are there any objections to moving forward with stabilization? 

Note that we still need to separately stabilize the Cargo changes (rust-lang/cargo#9910).

cc @jyn514 @camelid @GuillaumeGomez

**Comment by camelid** [comment]
I have not actually seen it in use yet. Do you know of some crates that enable it on docs.rs?

**Comment by PicoJr** [comment]
> I have not actually seen it in use yet. I'd like to see it in practice a bit before stabilizing. Do you know of some crates that enable it on docs.rs?

I enabled it for my crate `htp`, here is [how it looks on doc.rs](https://docs.rs/htp/latest/htp/fn.parse.html).

Is there a tool for searching crates that depend on this feature?

**Comment by jyn514** [comment]
You could download the source for all crates.io crates and search for `rustdoc-scrape-examples`. There's instructions on https://www.pietroalbini.org/blog/downloading-crates-io/, I think https://github.com/the-lean-crate/criner/tree/main/criner automates it.

**Comment by GuillaumeGomez** [comment]
@willcrichton I wanted to try to improve the JS side to reduce its size but it's not blocking for a stabilization I think.

**Comment by jyn514** [comment]
@Mark-Simulacrum a while ago suggested using `--emit example-metadata` or something like that (or maybe you were just suggesting that this would be part of normal `.rlib`s? I'm not sure how that works with the whole reverse-dependency thing though ...). We probably should iron that out before stabilizing.

https://zulip-archive.rust-lang.org/stream/266220-rustdoc/topic/--scrape-examples.20feedback.20.2388791.html

**Comment by willcrichton** [comment]
I followed @jyn514's advice and used criner to find crates with scrape-examples. Here are a few crates using this feature:
* [save](https://docs.rs/save/0.6.0-dev.1/save/cli/fn.init.html)
* [panda-re](https://docs.rs/panda-re/0.26.0/panda/struct.Callback.html#method.new)
* [with_lock](https://docs.rs/with_lock/0.4.2/with_lock/struct.MutexCell.html)
* [scrape_me](https://docs.rs/scrape-me/latest/scrape_me/fn.test_function.html) (probably just to test this feature?)

**Comment by programatik29** [comment]
@willcrichton I first tested this feature in `scrape_me` crate. There was a problem with `-` character that is now fixed.

I am currently using it in [`axum-server`](https://docs.rs/axum-server/latest/axum_server/) crate.

**Comment by willcrichton** [comment]
Some thoughts as I'm looking through the crates above.

## Highlighting large regions

Some examples, especially higher-order functions, correspond to large regions of code. For instance:

![Screen Shot 2022-01-21 at 4 57 55 PM](https://user-images.githubusercontent.com/663326/150618117-b06d38fa-5f58-459e-b69d-409b022a7269.png)

This is kind of ugly, and also hard to read. One possibility might be to just highlight the function identifier, and then emphasize the function arguments in a different way?

## Minimizing examples

Given that scraped examples take up a lot of screen real-estate, there should probably be a way of disabling them. Right now you can hit the global [-] button. But perhaps there should be another option to just minimize examples?

## Optional warning for functions with no examples

It might be interesting to library authors to identify which functions have no scraped examples. That can serve as a signal that they might want to add examples involving a particular function.

**Comment by jsha** [comment]
> Given that scraped examples take up a lot of screen real-estate, there should probably be a way of disabling them. Right now you can hit the global [-] button. But perhaps there should be another option to just minimize examples?

I'd like to avoid adding a new setting for minimizing examples separately from their containing item. I think the global `[-]` button does the job well enough.

Here's how I think of it: rustdoc is ultimately a tool of the documentation author to write the best, most useful, most readable documentation they can. It makes that job a lot easier, including organizing by type, extracting doccomments, and scraping examples. If a documentation author finds that their scraped examples take up too much room in their docs, they can arrange for those examples not to get scraped.

**Comment by camelid** [comment]
> This is kind of ugly, and also hard to read. One possibility might be to just highlight the function identifier, and then emphasize the function arguments in a different way?

One possible solution is to elide the interior lines if there're more than e.g. 10. Also, highlighting the arguments in a different way sounds promising.

> It might be interesting to library authors to identify which functions have no scraped examples. That can serve as a signal that they might want to add examples involving a particular function.

Yeah, we could consider a lint for that, but it'd probably be best to save it for later, especially because we'd probably need to make example scraping the default first.

**Comment by GuillaumeGomez** [comment]
> One possible solution is to elide the interior lines if there're more than e.g. 10.

I agree. We can add `...` after it and that should solve most problems with it.

> Yeah, we could consider a lint for that, but it'd probably be best to save it for later, especially because we'd probably need to make example scraping the default first.

For later: agreed. I'm curious though: should we put it in rustdoc or in clippy?

**Comment by willcrichton** [comment]
One simple solution is to strip leading whitespace from the highlighted regions. There's still a lot of yellow, but it's better. 

<img width="991" alt="Screen Shot 2022-01-22 at 3 10 59 PM" src="https://user-images.githubusercontent.com/663326/150658377-8f66d871-5938-448e-a777-edac5553c91d.png">

**Comment by camelid** [comment]
> One simple solution is to strip leading whitespace from the highlighted regions. There's still a lot of yellow, but it's better.

Hmm, but what about multiline strings?

> I played around with different ways to highlight arguments distinct (or not at all) from the function call identifier. But nothing really felt both appealing and consistent across the different scenarios (1-line vs multi-line). Also there's already two different highlight colors when there are multiple call-sites in a single item, so introducing a third color felt too much.

What about just highlighting the function name (and _maybe_ the `(` and `)`) and showing the arguments without highlighting?

**Comment by willcrichton** [comment]
True, this doesn't handle multiline strings.

And I tried not highlighting arguments, but for single-line call sites, it looked weird. If I saw `foo.bar("baz")` it seemed more natural for `("baz")` to be highlighted, since it is part of the example function call. And it would be strange to have different highlighting behavior for single-line and multi-line call sites.

**Comment by jsha** [comment]
I like the idea of just highlighting the item name. I'd actually like the scraped examples to use the same visual language as the non-scraped examples. Consistency helps people learn.

Proposal: In all documentation examples, we should emphasize the name of the item being documented. Perhaps by bolding it?

Also, if we want to apply highlighting to the line numbers, we should avoid yellow - which is used to indicate the linked-to line numbers in source view. Maybe bold the line numbers as well, to match the bolded item name?

**Comment by runiq** [comment]
> What about just highlighting the function name (and _maybe_ the `(` and `)`) and showing the arguments without highlighting?

I think I'd prefer this. Some additional options that could maybe help:

- Highlight the arguments with a very low opacity setting.
- Highlight the line numbers additionally.

**Comment by camelid** [comment]
> Proposal: In all documentation examples, we should emphasize the name of the item being documented. Perhaps by bolding it?

Hmm, it's an interesting idea, although I'm not sure the extra implementation complexity is worth it. Scraped examples are handled by a totally different code path from non-scraped examples.

I also don't think we should use bold (or italics, for that matter) in code blocks. Bolded code doesn't look good IMO.

**Comment by willcrichton** [comment]
Here's what it would look like to just highlight the function name.

![Screen Shot 2022-01-23 at 5 04 19 PM](https://user-images.githubusercontent.com/663326/150706444-70ab80d6-c1f3-4d60-b560-4406b531544a.png)

![Screen Shot 2022-01-23 at 5 04 42 PM](https://user-images.githubusercontent.com/663326/150706439-72f19371-7af7-448a-84dd-aec2e92faaa6.png)

(I could include the parentheses, although I'm not 100% sure how to figure extract their spans from the HIR node.)

Do y'all prefer this to highlighting the arguments?

**Comment by jsha** [comment]
I like that variant a lot!

> Hmm, it's an interesting idea, although I'm not sure the extra implementation complexity is worth it. Scraped examples are handled by a totally different code path from non-scraped examples.

I feel its worth it. It shouldn't block implementation here, but it's worth doing eventually. As a reader, I look at the "Example" and "Examples found in repository" and wonder why the name is highlighted in one place and not the other.

> I also don't think we should use bold (or italics, for that matter) in code blocks. Bolded code doesn't look good IMO.

I suspect that has a lot to do with the particular font-face and whether it has a dedicated bold weight or [it is using fake bold](https://alistapart.com/article/say-no-to-faux-bold/). Source Code Pro has a nice variety of weights: https://fonts.google.com/specimen/Source+Code+Pro?query=source+code+pro. I'll try putting together an experiment at some point. The other option available to us is picking a specific syntax highlighting color that is always used for the item being documented.

**Comment by camelid** [comment]
> I feel its worth it. It shouldn't block implementation here, but it's worth doing eventually. As a reader, I look at the "Example" and "Examples found in repository" and wonder why the name is highlighted in one place and not the other.

That's actually another UI concern of mine. I think we should try to make the scraped-examples section look different from user-written docs. The "Examples found in repository" appended as a regular Markdown heading has always bothered me a bit.

**Comment by willcrichton** [comment]
@camelid here's a few concepts, like any of them?

## Option 1: Left border

![Screen Shot 2022-01-23 at 6 07 32 PM](https://user-images.githubusercontent.com/663326/150710920-d797d8f2-2d76-4459-a911-6e6961e63d7d.png)

## Option 2: Top border

![Screen Shot 2022-01-23 at 6 07 56 PM](https://user-images.githubusercontent.com/663326/150710859-36c505c3-07c1-4838-a949-4c566fcfdfb8.png)

## Option 3: Box w/ inset shadow

![Screen Shot 2022-01-23 at 6 06 33 PM](https://user-images.githubusercontent.com/663326/150710863-00cb16ac-026c-4060-8be6-50c8c5f48caa.png)

**Comment by tshepang** [comment]
I likes me some option 3

**Comment by jsha** [comment]
With https://github.com/rust-lang/rust/issues/59829, https://github.com/rust-lang/rust/issues/59851#issuecomment-488976397,  we're trying to reduce the use of horizontal lines spanning the page, because they draw attention more strongly than regular headings do, and can make it look like, e.g. "Examples found in repository" is a more important heading than `pub fn arch`. So of these 3, I prefer Option 1. Another possibility, if we need to strongly distinguish scraped examples, would be to show them with no background, [as the mockup I linked above proposes](https://github.com/rust-lang/rust/issues/59851#issuecomment-488976397). But I still don't understand the need to strongly distinguish scraped examples.

> I think we should try to make the scraped-examples section look different from user-written docs. The "Examples found in repository" appended as a regular Markdown heading has always bothered me a bit.

@camelid can you explain why it's so important to distinguish the scraped examples strongly? From a reader perspective, the main thing is to understand that there is additional context and the example is not standalone. But I think that's adequately conveyed by the file name (and line number).

@willcrichton I appreciate your working through this! I know doing UI design via GitHub issue can be... time consuming. We can also start a Zulip thread tomorrow. That might make it a little faster to work out where we're each coming from. :-)

**Comment by camelid** [comment]
> @camelid can you explain why it's so important to distinguish the scraped examples strongly? From a reader perspective, the main thing is to understand that there is additional context and the example is not standalone. But I think that's adequately conveyed by the file name (and line number).

I think just think it could be a little confusing or misleading for documentation readers and writers. For example, if someone sees an example that shouldn't show up (for whatever) reason, they may go look to edit the source, but get confused by not seeing the example there.

I'd also just rather keep a clear separation between user- and machine-generated content for consistency and clarity.

**Comment by willcrichton** [comment]
After a lot of discussion on Zulip and some implementation work, most of the remaining issues are being addressed in these PRs:

* #93217 
* #93497 
* rust-lang/cargo#10343

**Comment by Emilgardis** [comment]
On a note related to https://github.com/rust-lang/rust/issues/88791#issuecomment-963080815

it seems it's impossible to use `rustdoc-scrape-examples=all` and workspace members for examples on docs.rs, i.e the `.crate` tarball doesn't include the workspace members since they are not part of the published crate, and thus there is nothing to scrape. Adding the members in `include` doesn't solve it either.

My use-case is a crate with its examples being workspace members to include different dependencies without "polluting" `dev-dependencies`

**Comment by rcoh** [comment]
It seems like this scrapes function usages but not macro usages. Is that something that's possible to support?

**Comment by willcrichton** [comment]
> It seems like this scrapes function usages but not macro usages. Is that something that's possible to support?

It would certainly be possible to support. There's a catch-all in `scrape_examples.rs` that could be filled in with more kinds of expressions:

https://github.com/rust-lang/rust/blob/e87ccb8676be9ab641849a2539b215d0c9027237/src/librustdoc/scrape_examples.rs#L174-L176

There is a broader discussion about what kinds of items and what kinds of examples we want in Rustdoc. I focused on function calls for functions items, but there's nothing preventing us from scraping uses of constants, modules, and so on. @GuillaumeGomez @camelid do y'all have any thoughts about this?

**Comment by GuillaumeGomez** [comment]
I think it'd make sense to also look for macros and scrape examples for them as well.

**Comment by OliverKillane** [comment]
> I think it'd make sense to also look for macros and scrape examples for them as well.

+1 for this. Would be very suave for documenting proc-macros, we currently have:
![image](https://github.com/rust-lang/rust/assets/44177991/3ad52955-16ad-4631-900c-08b27a4875cf)

**Comment by nikomatsakis** [comment]
For the record, I love this.
