### ISSUE TITLE
rustdoc: Tracking issue for generating links to definitions on source code pages

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#89095]
This is a tracking issue for generating links to definitions on source code pages.
The feature can be enabled by passing `--generate-link-to-definition -Zunstable-options` to a nightly `rustdoc`.

> [!NOTE]
>
> Tracking issues are used to record the overall progress of implementation.
> They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
>
> A tracking issue is however *not* meant for large scale discussion, questions, or bug reports.
> Instead, open a dedicated issue for the specific matter or post in the [#t-rustdoc](https://rust-lang.zulipchat.com/#narrow/channel/266220-t-rustdoc) Zulip channel.
>
> Discussion comments will get marked as off-topic or deleted.
> Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Outstanding work

 * [ ] Improve "jump links" UI: for now it's highlighted background but it was suggested we could try an "underline dotted": https://github.com/rust-lang/rust/issues/88120
 * [ ] Add support to go to both source definition and documentation page (if available!). We could do it by adding a popup when hovering the item. (#89157)
 * [ ] Make all links go to source location, not documentation (currently, external types link to documentation)

### Steps

To go through stabilization, we will gradually enable it in different places:

 * [x] Enable it by default on the compiler docs (https://github.com/rust-lang/rust/pull/88292 and #89217)
 * [ ] Enable it by default on the std docs
 * [ ] Enable the feature by default (on nightly only) and remove the flag.
 * [ ] Send the stabilization PR.

### Implementation history

FIXME: Likely missing some PRs.

* #84176
* #88033 
* #91264
* #134216
* #135771

**Comment by jyn514** [comment]
> Enable the feature by default (on nightly only) and reverse the flag (so that it disables instead of enabling).

I think we should *not* do this, this is exactly how we got in trouble with intra-doc links (see https://github.com/rust-lang/rust/issues/63305). Instead we should just enable it by default at the same time we remove the flag and stabilize the feature.

**Comment by GuillaumeGomez** [comment]
This is a very good point. I had in mind that maybe people would want to disable it but I guess we can always add it later on if the needs appear.
