### ISSUE TITLE
Tracking Issue for RFC: Supertrait Item Shadowing

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#89151]
This is a tracking issue for:

- https://github.com/rust-lang/rfcs/pull/2845
- https://github.com/rust-lang/rfcs/pull/3624

The feature gate for the issue is `#![feature(supertrait_item_shadowing)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Accept an RFC.
  - https://github.com/rust-lang/rfcs/pull/2845
  - https://github.com/rust-lang/rfcs/pull/3624
- [x] Implement in nightly.
  - https://github.com/rust-lang/rust/pull/125782
- [ ] Add documentation to the [dev guide][].
  - See the [instructions][doc-guide].
- [ ] Add documentation to the [reference][].
  - See the [instructions][reference-instructions].
- [x] Add formatting for new syntax to the [style guide][].
  - See the [nightly style procedure][].
- [ ] Stabilize.
  - See the [instructions][stabilization-instructions].

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[stabilization-instructions]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

*    Level for lint that fires on the definition of a subtrait that has a shadow method?
*    Level for lint that fires on a method call that resolves to the subtrait because of shadowing?

### Related

- https://github.com/rust-lang/rfcs/pull/2845
- https://github.com/rust-lang/rfcs/pull/3624
- https://github.com/rust-lang/rust/pull/125782

**Comment by petrochenkov** [comment]
I remember looking at the method resolution logic (excluding auto(de)ref) in the compiler a couple of years ago, and not liking what I've seen.

Treating methods from generic parameter bounds as inherent (bad idea, IMO), treating `Trait` methods on `dyn Trait` as inherent (bad idea, IMO), not considering `Trait` methods on `impl Trait` at all (bad idea, IMO, #41221), filtering of private methods (needs to have some priority relative to supertrait item shadowing), filtering of unstable methods (needs to have some priority relative to supertrait item shadowing).

I wish that area got some principled common vision (and corresponding bugfixing) before new features are added.

**Comment by tgross35** [comment]
@petrochenkov did any of that resolution restructuring happen? I think there has gotten some interest recently

**Comment by Amanieu** [comment]
I re-read the RFC with the `Itertools` situation in mind and it doesn't seem to be the right thing that we need. Here is a summary of the current situation:

```rust
// core
trait Iterator {
    #[unstable]
    fn intersperse(self, element: Self::Item) -> Intersperse<Self>;
}

// itertools
trait Itertools: Iterator {
    fn intersperse(self, element: Self::Item) -> Intersperse<Self>;
}
```

Today, `Iterator::intersperse` is unstable and therefore de-prioritized in method resolution. However we are blocked from stabilizing it because it will cause ambiguity errors in any crates currently using the `itertools` version of the method. This is pretty widely used, with 59 root regressions in crater (#88967) which makes it impractical to individually update each crate.

Most uses of this method look like this:

```rust
// Implicit prelude import
use core::iter::Iterator;

// Explicit trait import
use itertools::Itertools;

// Actual use which causes an ambiguity error.
let text = lines.intersperse("\n").collect();
```

This would not work with the RFC as proposed since no generic bounds are in use. Instead we would need one of the proposed alternatives, specifically "Always resolving in favor of the subtrait". Essentially, if there is ambiguity between a supertrait and subtrait method, we should always resolve the ambiguity by selecting the subtrait method.

@rust-lang/types What are your thoughts on this? @rust-lang/libs-api would like to know if this is likely to move forward since this affects future development of the `Iterator` trait in the standard library.

**Comment by lcnr** [comment]
My personal preference would be to always resolve in favor of the sub trait linting when defining a sub trait if the trait has an item with the same name as the super trait. I believe always shadowing super traits is fairly straightforward to implement and linting the definition of the sub trait is as well.

I consider this behavior to be part of the area where the responsibilities of t-types and t-lang overlap. T-lang is responsible for the *vibe* while T-types has to sign off that it works well with the general design of the type system and its implementation in rustc. Nominating this for t-lang to decide whether "always prefering methods from subtraits" is acceptable to them and to decide whether this needs any additional FCP/RFC to be implemented.

**Comment by nikomatsakis** [comment]
We discussed this in the @rust-lang/lang triage meeting and we felt we didn't have sufficient context to evaluate precisely what is being proposed, so we'd love to see a short RFC about this. What I think would be really useful is to highlight the examples of where this "does the right thing" but also any edge cases.

Basically what are the arguments *against* this? Off the top of my head...

* Adding a use of the subtrait can now change what method gets invoked, instead of introducing ambiguity. I think this is true already.

**Comment by Amanieu** [comment]
I wrote an RFC: https://github.com/rust-lang/rfcs/pull/3624

**Comment by the8472** [comment]
Something that came up in a libs-api meeting today: If the shadowed methods have different signatures and the user is calling something with the wrong arguments, will there be a note on the error informing them there's another method which might better match what they're trying to do?

(also edited the top comment to add the unresolved questions)

**Comment by Amanieu** [comment]
This came up again in the @rust-lang/libs-api meeting in the context of lifting more iterator methods from itertools to the standard library. Stabilizing these is blocked on @rust-lang/lang stabilizing this feature.
