### ISSUE TITLE
Warn if feature settings may break compilation

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rust#89586]
Currently, if a user instructs the compiler to adjust the features for compilation, or uses `#[target_feature]` to set unusual feature settings for a function, or introduces a custom target, this can trigger miscompilations if the settings are improperly "aligned" with each other (to do correct parameter passing and so on). This mostly impacts x86, due to its particular architectural extensions, but it could affect other platforms.

Some examples we definitely want to warn on:
- [ ] Enabling soft floats and not disabling SSE/SSE2 and the x87 FPU. This came up with https://github.com/rust-lang/rust/issues/61721
- [ ] `"-sse"` but not `"-sse2"`. I don't know how this even makes sense, honestly, but it also came up with https://github.com/rust-lang/rust/issues/61721
- [ ] Enabling SSE or SSE2 for single functions on x86 without SSE2 platforms and calling into it. See https://github.com/rust-lang/rust/issues/64609 for more.

Some of these issues are currently caught by LLVM, but Rust programmers often find underlying LLVM errors surfacing to be mysterious and cryptic, and in this case we can definitely detect them and warn about them ourselves.

In addition, due to the desire for binary floating point conformance per https://github.com/rust-lang/rust/issues/10087, we **probably** want to emit a warning for any build configuration such that, despite having an FPU we consider to be conformant and desirable, disables the ability to use such a floating point unit, such that it could introduce non-conformant floating point code. However, that can be extended into a future issue when all the known-100%-bad bases are covered.

**Comment by workingjubilee** [comment]
This requires digging deep into the `target_feature` code and likely refactoring it. Much of it lives in https://github.com/rust-lang/rust/tree/master/compiler/rustc_codegen_llvm and it should probably be, as part of this, hoisted into https://github.com/rust-lang/rust/tree/master/compiler/rustc_codegen_ssa

**Comment by Wardenfar** [comment]
Hello @workingjubilee,

I'm trying to understand the issue and i have some questions.
 - For the first sub-task : i need to detect imcompatible global features or at function level ? 
   and i have not found a way to detect ` x87 FPU`. 
 - To report an error : should i use `sess.err(...)` ?
 
 Thanks

**Comment by bstrie** [comment]
@Wardenfar You may want to try asking on the #t-compiler Zulip thread: https://rust-lang.zulipchat.com/#streams/131828/t-compiler

**Comment by workingjubilee** [comment]
My apologies for taking so long to answer. Yes, I am more reachable on Zulip.

1. - Q: Should we detect incompatible features at the global feature level?
   - A: Yes, definitely.
0. - Q: Should we detect incompatible features at the function feature level?
   - A: Ideally also yes.
0. - Q. How is the x87 FPU denoted?
   - A. The x87 FPU feature uses the string `"+x87"` to enable and `"-x87"` to disable
0. - Q. How to report an error?
   - A. Yes, `sess.err` or any of the other typical error emitters should be fine, including builders like `struct_span_err`.

**Comment by workingjubilee** [comment]
this is turning out to be way more complex than I thought it would possibly be, see:
- https://github.com/rust-lang/rust/issues/131799

**Comment by RalfJung** [comment]
Oh damnit, I don't know what happened with the labels... I just added ABI and target-feature, and then github removed all the others. Not sure why.
