### ISSUE TITLE
Tracking Issue for LLVM Control Flow Integrity (CFI) Support for Rust

### ISSUE THREAD

**Issue by rcvalle** [rust-lang/rust#89653]
This is a tracking issue for the LLVM Control Flow Integrity (CFI) Support for Rust project (see the [design document](https://rcvalle.com/docs/rust-cfi-design-doc.pdf)).

### Steps

LLVM CFI support for Rust work will be implemented in the following steps:

 - [ ] Add option to the Rust compiler driver and frontend. (#89652)
 - [ ] Add support for emitting type metadata and checks to the Rust compiler code generation. (#89652)
 - [ ] Implement Rust-compiled code only LLVM CFI support by using Rust-specific type metadata identifiers. (#89652)
 - [ ] Define type metadata identifiers for cross-language LLVM CFI support.
 - [ ] Change initial implementation to use the defined type metadata identifiers for cross-language LLVM CFI support.
 - [ ] Create documentation and tests.

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

LLVM uses type metadata to allow IR modules to aggregate pointers by their types.[1] This type metadata is used by LLVM Control Flow Integrity to test whether a given pointer is associated with a type identifier (i.e., test type membership).

Clang uses the Itanium C++ ABI's[2] virtual tables and RTTI typeinfo structure name[3] as type metadata identifiers for function pointers. The typeinfo name encoding is a two-character code (i.e., “TS”) prefixed to the type encoding for the function.

For cross-language LLVM CFI support, a compatible encoding must be used by either

1. Using a superset of types that encompasses types used by Clang (i.e., Itanium C++ ABI's type encodings[4]), or at least types used at the FFI boundary.
2. Reducing the types to the least common denominator between types used by Clang (or at least types used at the FFI boundary) and Rust compilers (if even possible).
3. Creating a new ABI for cross-language CFI and using it for Clang and Rust compilers (and possibly other compilers).

Option (2) may weaken the protection for Rust-compiled only code, so it should be provided as an alternative to a Rust-specific encoding for when mixing Rust and C and C++ -compiled code. Option (3) would require changes to Clang to use the new ABI.

[1] https://llvm.org/docs/TypeMetadata.html
[2] https://itanium-cxx-abi.github.io/cxx-abi/abi.html
[3] https://itanium-cxx-abi.github.io/cxx-abi/abi.html#mangling-special-vtables
[4] https://itanium-cxx-abi.github.io/cxx-abi/abi.html#mangling-type

### Implementation history

 1. #89652

**Comment by RalfJung** [comment]
All of the "steps" listed in the issue have been checked. What is still being tracked here, what is still missing?

**Comment by rcvalle** [comment]
> All of the "steps" listed in the issue have been checked. What is still being tracked here, what is still missing?

I was planning to close it when I finish fixing all the known issues--I've two PRs open that should fix most of them: #113593 and #113708--but I'm also okay with closing it now. What do you think?

**Comment by RalfJung** [comment]
Either work for me, I was just wondering about the current status. :)

Is there an issue tracking the availability on stable?

**Comment by rcvalle** [comment]
> Either work for me, I was just wondering about the current status. :) Is there an issue tracking the availability on stable?

Not yet, but I'll create one right after. (FWIW, here is our roadmap for the rest of 2023 and beyond: https://hackmd.io/@rcvalle/H1epy5Xqn.)

**Comment by Nilstrieb** [comment]
Is there a reason why unnormalized integers are supported in rustc at all? It is clearly not something that is supported by Rusts model and is something that is very C specific. I doubt there's a significant security benefit from not normalizing them, though I do not know details. Should that just be removed with only normalized integers being supported?
I also have some concerns about the [cfi-types](https://crates.io/crates/cfi-types) crate. If someone is supposed to use this crate (or roll their own aliases) to use the CFI feature, I think that would have a huge negative impact on the feature. Either it would just be unusable in practice because dependencies doing FFI don't use it or these dependencies would all receive patches to use this crate, which seems quite bad too. With integer normalization, I don't see why this crate would be needed, as rustc can just pick the correct CFI encoding for its primitive integers, making the crate redundant and making CFI just work for everyone.

**Comment by RalfJung** [comment]
@Nilstrieb what are unnormalized integers, which issue are you referring to?

I read through the readme at https://crates.io/crates/cfi-types, and that part seems to be about the idiosyncrasies of C integer types. Is it really required to import those idiosyncrasies into every language that wants to have CFI interop with C?

**Comment by workingjubilee** [comment]
@RalfJung These "idiosyncrasies", as you call them, are "unnormalized integers".

**Comment by RalfJung** [comment]
Ah okay. I guess I am agreeing with Nilstrieb then, only normalized integers really make sense for Rust.

**Comment by rcvalle** [comment]
Sorry for the late replies. I'm out traveling for speaking on a conference and then on vacation.

Enabling the integer normalization option by default in rustc wouldn't help on cross-language CFI because most Rust integers have the same encoding as when normalized already (i.e., encoded as u<length><type-name> as vendor extended type), and most of the integer normalization work is actually done by the foreign language compiler (i.e., Clang). It'd just degrade the protection of a program written in Rust only (i.e., when a foreign language isn't used), and we want programs written in Rust only to have the best protection by default.

The cfi_types crate helps in other scenarios, such as when a precompiled library needs to be linked to a program written in Rust, but wasn't compiled either with integer normalization or CFI enabled, and recompiling it isn't an option (and avoid adding e.g. https://github.com/rcvalle/rust/blob/55e3dc487fdf8025fb99301883e24af15323912a/library/std/src/sys/unix/thread_local_dtor.rs#L23 thoroughout the code).

**Comment by RalfJung** [comment]
> It'd just degrade the protection of a program written in Rust only

How that?

We explicitly [document](https://doc.rust-lang.org/nightly/std/primitive.fn.html#abi-compatibility) `u64` and `usize` to be ABI-compatible on 64bit platforms. So if the function takes `usize` and the caller uses type `u64`, that is completely legal and should not be stopped by CFI.

**Comment by rcvalle** [comment]
> > It'd just degrade the protection of a program written in Rust only
> 
> How that?
> 
> We explicitly [document](https://doc.rust-lang.org/nightly/std/primitive.fn.html#abi-compatibility) `u64` and `usize` to be ABI-compatible on 64bit platforms. So if the function takes `usize` and the caller uses type `u64`, that is completely legal and should not be stopped by CFI.

Are `usize` and `u64` interchangeable in the Rust language as types or are they different types?

**Comment by RalfJung** [comment]
They are different types but ABI-compatible.

**Comment by rcvalle** [comment]
> They are different types but ABI-compatible.

Which means that for CFI they're different types, but can be used in place of one another if the proper conversion is done at the call site, and CFI will allow that.

**Comment by RalfJung** [comment]
> It'd just degrade the protection of a program written in Rust only

Could you give an example of that?
I'm not very familiar with how CFI works.
Here's an [example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7fdd16a4a5734648d372c809b4a84a09) of a program that should be accepted, even though call-site-type and callee-type are not the same.

Based on what @Nilstrieb says, we should at least clearly document than cross-language CFI is only expected to work with normalized integers.

**Comment by rcvalle** [comment]
> > It'd just degrade the protection of a program written in Rust only
> 
> Could you give an example of that?
> I'm not very familiar with how CFI works.
> Here's an [example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7fdd16a4a5734648d372c809b4a84a09) of a program that should be accepted, even though call-site-type and callee-type are not the same.

Your example demonstrates exactly what an attempt to redirect the control flow of a program by an attacker exploiting a (likely a memory corruption) vulnerability would look like, and what CFI protects against, and why the integer normalization would degrage the security of programs written in Rust only (because it would allow it).

An example that would work would be to have the correct function declaration/type for the function pointer and convert the type instead.

> 
> Based on what @Nilstrieb says, we should at least clearly document than cross-language CFI is only expected to work with normalized integers.

Yes, it's documented at https://doc.rust-lang.org/beta/unstable-book/compiler-flags/sanitizer.html#controlflowintegrity.

**Comment by RalfJung** [comment]
Rust explicitly allows certain ABI mismatches. Those are not a sign of an attack. There's no chance of data misinterpretation or so here, behavior is entirely well-defined. If CFI rejects those programs then it rejects valid Rust programs. That's bad.

Here's [another example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ab6565185671009e0d49395b8f70c20c) of a valid program.

**Comment by rcvalle** [comment]
> Rust explicitly allows certain ABI mismatches. Those are not a sign of an attack. There's no chance of data misinterpretation or so here, behavior is entirely well-defined. If CFI rejects those programs then it rejects valid Rust programs. That's bad.
> 
> Here's [another example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ab6565185671009e0d49395b8f70c20c) of a valid program.
> 

What I'm saying is that these examples demonstrate it, not that these are cases that can and would be exploited. These demonstrate/have the same effect of an attacker redirecting the control flow of a program by exploiting a memory corruption vulnerability and overwriting a function pointer to perform a code reuse attack, redirecting the control flow to existing code they can benefit from.

This is how type-based control flow protection works. It works at the language's type system level, and not the ABI level, and introduces such constraints (and in Rust case, these are unsafe operations/transmutes only, other languages are not), but provides ways to allow these with additional options, such as with the integer normalization and pointer generalization options.

**Comment by Nilstrieb** [comment]
I think it's problematic to support "extra protection" by rejecting valid Rust programs. If CFI sees adoption in the ecosystem, people will start opening issues for crates that write correct code to get them to "fix their code" and support CFI. It can also be confusing to users, who start using CFI and then get crashes for their correct code. Documenting this as "If you want to use CFI on Rust, remember to pass this 'make it work' option" is also not ideal. Instead of having a 'make it work' option, it should just always work :).
All of this is assuming that there is not a significant loss of security with normalized integers. It's obvious that there's gonna be _some_ loss, but I do not know how much, I assume not a lot. If you can show that the security benefit is significant (and not just 1% or similar which I remember reading somewhere? Not sure though.) then it may make sense to add unnormalized integers as an opt-in. But without significant benefit, I think it's a pretty bad idea to support it.

**Comment by rcvalle** [comment]
> I think it's problematic to support "extra protection" by rejecting valid Rust programs. If CFI sees adoption in the ecosystem, people will start opening issues for crates that write correct code to get them to "fix their code" and support CFI. It can also be confusing to users, who start using CFI and then get crashes for their correct code. Documenting this as "If you want to use CFI on Rust, remember to pass this 'make it work' option" is also not ideal. Instead of having a 'make it work' option, it should just always work :).
> All of this is assuming that there is not a significant loss of security with normalized integers. It's obvious that there's gonna be _some_ loss, but I do not know how much, I assume not a lot. If you can show that the security benefit is significant (and not just 1% or similar which I remember reading somewhere? Not sure though.) then it may make sense to add unnormalized integers as an opt-in. But without significant benefit, I think it's a pretty bad idea to support it.

As I mentioned in another thread already, I wish fine-grained type-based CFI was an enable and forget mitigation as many others because I want as many users to use it as possible, but unfortunately it does require some code care and maintenance for use.

And It's actually common for large code bases to have those CFI violations when CFI support is initially implemented. For example, the Linux kernel had many that had to be fixed to have it initially supported and enabled.

**Comment by RalfJung** [comment]
It is also fairly common for large C codebases to have UB. That does not apply to Rust though. In Rust we have a very clear baseline for what a program and a library is expected to ensure: no UB. Period.

Having a "protection" mechanism apply higher standards than that is highly problematic and would need to be widely discussed in the project. I certainly think it's a bad idea. Protection mechanisms should detect UB. They shouldn't raise false positives in non-UB programs.

Rust is not C, so not all things that make sense in C also make sense in Rust.

**Comment by Nilstrieb** [comment]
Are you saying that codebases require some care to get working because they're filled with bugs that CFI exposes? If that's the case then that's great and we want that! I just see a significant difference between "it doesn't work because there's UB" and "it doesn't work because the sanitizer doesn't understand Rust semantics". The former is awesome and a feature, the latter is a bug that I'd like to see eliminated with integer normalization.

**Comment by rcvalle** [comment]
Happy to continue this discussion in a new Zulip thread under project-exploit-mitigations. Let's move it there if you all agree.
