### ISSUE TITLE
Tracking Issue for additional `array::IntoIter` constructors (feature `array_into_iter_constructors`)

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#91583]
Feature gate: `#![feature(array_into_iter_constructors)]`

This is a tracking issue for the `from_raw_parts` and `empty` constructors on `core::array::IntoIter`.

This allows creating such an iterator with something other than a fully-initialized array.

### Public API

```rust
// core::array

impl<T, const N: usize> IntoIter<T, N> {
    pub const fn empty() -> Self;
    pub const unsafe fn from_raw_parts(buffer: [MaybeUninit<T>; N], initialized: Range<usize>) -> Self;
}
```

### Steps / History

- [ ] Implementation: https://github.com/rust-lang/rust/pull/91341
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- [ ] Should this be named `from_raw_parts` or something else?
- [ ] Should this have to go through an `ArrayVec`-like type (like how `Vec` has `from_raw_parts` instead of `vec::IntoIter` having it), instead of making the `IntoIter` directly?

**Comment by clarfonthey** [comment]
I would definitely like to see an implementation of `Default` for `IntoIter` that uses `empty()`, although that would be insta-stable and require an FCP.
