### ISSUE TITLE
Proposal: Implement `core::ops::*<T>` on `Saturating<T>` / `Wrapping<T>` type

### ISSUE THREAD

**Issue by kellerkindt** [rust-lang/rust#91586]
Relevant RFC "928" (rust-lang/rfcs#928).
 - #87920
 - #32463

### Public API
The [`Wrapping`](https://doc.rust-lang.org/core/num/struct.Wrapping.html) and [`Saturating`](https://doc.rust-lang.org/core/num/struct.Saturating.html) types enforce that a certain behaviour for all operations on the underlying integer is performed - `.wrapping_*` or `.saturating_*`. When doing the "simplified" operations, `.add` *always* becomes `.wrapping_add` or `.saturating_add`, `.sub` *always* becomes `.wrapping_sub` / `.saturating_sub` and so on.

The fundamental ideas seem to be:
 1. Never perform the an integer operation with the wrong behaviour by forgetting to write `.wrapping_*` or `.saturating_*`
 2. Reduce boiler-plate code / text by being able to omit writing `.wrapping_*` or `.saturating_*`

But number 2 seems to fall short in reality. The traits in `core::ops::` are only implemented for `Wrapping` and `Saturating` where the other type is `Wrapping` or `Saturating` as well (`impl core::ops::*<Wrapping<T>> for Wrapping<T>`¹). So, instead of writing a integer addition like this:
```rust
    let mut value = 17u8;
    // ...
    value += 8;
    value *= 7;
    // ...
    let other: u8 = value / 3;
```
for `Wrapping` and `Saturating` types, it looks likes this:
```rust
    let mut value = Wrapping(17u8);
    // ...
    value += Wrapping(8);
    value *= Wrapping(7);
    // ...
    let other: Wrapping<u8> = value / Wrapping(3);
```

This introduces the need for additional mentions of `Wrapping` /  `Saturating` in every code location where an integer operation is performed - and in my opinion, adds unnecessary noise to the code. In my opinion, having the integer being wrapped in either `Wrapping` or  `Saturating` in the declaration / initialization should be all that is needed.

I propose that - in addition to `impl core::ops::*<Wrapping<T>> for Wrapping<T>`¹ - the integer operations are also implemented using the raw integer type itself (`impl core::ops::*<T> for Wrapping<T>`¹), and therefore the following is being made possible:

```rust
    let mut value = Wrapping(17u8);
    // ...
    value += 8;
    value *= 7;
    // ...
    let other: Wrapping<u8> = value / 3;
```

¹ as well as for `Saturating`
### Steps / History

- [x] Decide on wrapping integer (rust-lang/rfcs#928)
- [x] Implement basic `Wrapping` type  #32463
  - [x] Stabilize it
- [x] Implement basic `Saturating` type #87920
  - [ ] Stabilize it (WIP)
- [ ] Add raw integer operations (TODO)
  - [ ] on `Wrapping`
  - [ ] on `Saturating`
- [ ] Stabilize raw integer operations
  - [ ] on `Wrapping`
  - [ ] on `Saturating`

### Unresolved Questions

- RFC vs PR?.
  Following ["The overarching philosophy is: do whatever is easiest"](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md), I created this PR because the underlying types already exist, and it **"only"** proposes additional trait impls. Or does this change need a proper RFC?
