### ISSUE TITLE
Tracking Issue for try_reserve method on more containers

### ISSUE THREAD

**Issue by TennyZhuang** [rust-lang/rust#91789]
This is another tracking issue for the try_reserve part of the RFC "fallible collection allocation" (rust-lang/rfcs#2116).
The feature gate for the issue is `#![feature(try_reserve_2)]`.

The feature is a follow-up to #48043. Since `try_reserve` was stabilized in 1.57.0, we may need a new feature gate for further `try_reserve` implementation on more containers.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement `try_reserve` and `try_reserve_exact` on `BinaryHeap` #91529 
- [x] Implement `try_reserve` and `try_reserve_exact` on `PathBuf` #92513
- [x] Implement `try_reserve` and `try_reserve_exact` on `OsString` #92338 
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

If any containers were missing, please comment in the issue, and I will add it to the list.

### Implementation history

#91529 
#92338 
#92513

**Comment by Xuanwo** [comment]
After a diff between https://doc.rust-lang.org/std/?search=reserve and https://doc.rust-lang.org/std/?search=try_reserve, I think the current list is complete.

**Comment by Xuanwo** [comment]
I'm interested in implement try_reserve and try_reserve_exact on PathBuf.

**Comment by Xuanwo** [comment]
@TennyZhuang Please help update the issue link into description: https://github.com/rust-lang/rust/pull/92338

**Comment by Xuanwo** [comment]
And the support of `PathBuf` will be based on work #92338, I will continue it after this PR get merged.

**Comment by Xuanwo** [comment]
@TennyZhuang https://github.com/rust-lang/rust/pull/92513 has been submitted for review. Let's go forward the stabilization!

**Comment by Xuanwo** [comment]
Let's stabilize this feature! Steps are listed here:

From https://rustc-dev-guide.rust-lang.org/stability.html#stabilizing-a-library-feature

- [ ] Ask a T-libs-api member to start an FCP on the tracking issue and wait for the FCP to complete
- [ ] Change `#[unstable(...)]` to `#[stable(since = "version")]`
- [ ] Remove `#![feature(...)]` from any test or doc-test for this API
- [ ] Open a PR against `rust-lang/rust`
  - Add the appropriate labels: `@rustbot modify labels: +T-libs-api`.
  - Link to the tracking issue and say "Closes #XXXXX".

**Comment by Xuanwo** [comment]
@yaahc Hi, can you start an FCP for feature `try_reserve_2`?

**Comment by yaahc** [comment]
Absolutely!

@rfcbot merge

**Comment by dtolnay** [comment]
It's worth being aware that the `OsString` version of these methods is extremely weird, and probably not adequately documented about how weird it is. In particular the following "obvious" code is not correct, but it seems likely that almost every caller would fall into this trap unless there is very clear guidance on how to use the method correctly.

```rust
fn os_string_push_str(buf: &mut OsString, data: &str) -> Result<(), TryReserveError> {
    buf.try_reserve(data.len())?;
    buf.push(data);
}
```

The units in which string length is measured, and the units in which OsString capacity is measured, are in general totally different units.

Quoting from elsewhere in the OsString docs:

> As discussed in the `OsString` introduction, `OsString` and `OsStr` store strings in a **form best suited for cheap inter-conversion between native-platform and Rust string forms, which may differ significantly from both of them, including in storage size and encoding**.

This is saying that the **"storage size"** of an OS string (which is the size that `len` returns, and the same units as the `additional` arg of `try_reserve`) **"may differ significantly"** from the storage size of the **"Rust string form"** of the same data, i.e. that `os_str.len()` and `os_str.to_str().unwrap().len()` may differ significantly.

@rfcbot concern do we need better docs about what the argument value means (not bytes)

**Comment by TennyZhuang** [comment]
> It's worth being aware that the `OsString` version of these methods is extremely weird, and probably not adequately documented about how weird it is. In particular the following "obvious" code is not correct, but it seems likely that almost every caller would fall into this trap unless there is very clear guidance on how to use the method correctly.

I definitely agree that `OsString::try_reserve` is very easy to be used incorrectly, but I think the problem already exists due to the `with_capacity` API. Users may also got wrong results while they use with_capacity from another type’s len().

**Comment by dtolnay** [comment]
I agree that `with_capacity` also needs to be better explained. That function is from 2016 when our standards were lower. :wink:

**Comment by Xuanwo** [comment]
I will start PRs to address the concern that @dtolnay proposed.

- [ ] Add better docs for `OsString::try_reserve` about what the argument value means
- [ ] (Maybe) Polish the docs for `OsString::with_capacity` too ?

**Comment by m-ou-se** [comment]
> This is saying that the "storage size" of an OS string "may differ significantly" from the storage size of the "Rust string form" of the same data.

We should probably just update that documentation. We already guarantee any `&str` can be turned into a `&OsStr` through `AsRef`, so there's not much room for doing anything other than representing `str` data exactly as is in an `OsStr`, with the same length. The only space left for 'surprises' is how many units/bytes unmatched UTF-16 surrogate pair halves take on Windows.

**Comment by Xuanwo** [comment]
Sorry for stalling this work for so long; I'll take care of all the concerns next week.

**Comment by dtolnay** [comment]
https://github.com/rust-lang/rust/issues/91789#issuecomment-1029914247 sounds good to me. I would be prepared to accept (with libs-api FCP) a PR that updates all the places talking about OS string capacity to indicate that this means UTF-8 byte size for OS strings which were created from valid unicode, and not otherwise specified for other contents.

**Comment by Xuanwo** [comment]
Great, please take a look at https://github.com/rust-lang/rust/pull/95392

**Comment by joshtriplett** [comment]
https://github.com/rust-lang/rust/pull/97202

**Comment by dtolnay** [comment]
@rfcbot resolve do we need better docs about what the argument value means (not bytes)

**Comment by Xuanwo** [comment]
> look like [`BTreeSet::try_reserve`](https://doc.rust-lang.org/std/collections/struct.BTreeSet.html) have been forgotten too.
> 
> Don't know what would be the plan for [`LinkedList`](https://doc.rust-lang.org/std/collections/struct.LinkedList.html)

IMHO, we need a proposal to discuss adding `reserve` for `BTressSet` and `LinkedList` first.

**Comment by TennyZhuang** [comment]
BTreeSet and LinkedList are pointer-based data structure, which means that they can't benefit from batch allocation. The reserve method on them is exactly same as just allocate one by one, but will make the code much more complicated (we have to introduce placeholder nodes for that).

**Comment by Stargateur** [comment]
ah I get fouled by https://doc.rust-lang.org/src/core/iter/traits/collect.rs.html#379

these two collections probably need something like `try_push()` instead.
