### ISSUE TITLE
Stop using `in_band_lifetimes` in compiler crates

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#91867]
With more than 50% of the sign-offs needed in https://github.com/rust-lang/rust/issues/44524#issuecomment-988260475 to remove the feature entirely (EDIT: And now in FCP), I think it's now fine to start updating the compiler code to stop using the nightly feature.

Here are the crates currently using it:
- [x] compiler\rustc_borrowck\src\lib.rs https://github.com/rust-lang/rust/pull/91879
- [x] compiler\rustc_codegen_llvm\src\lib.rs #91931
- [x] compiler\rustc_codegen_ssa\src\lib.rs https://github.com/rust-lang/rust/pull/91885
- [x] compiler\rustc_const_eval\src\lib.rs https://github.com/rust-lang/rust/pull/91887
- [x] compiler\rustc_data_structures\src\lib.rs #91580
- [x] compiler\rustc_hir\src\lib.rs https://github.com/rust-lang/rust/pull/91893
- [x] compiler\rustc_incremental\src\lib.rs https://github.com/rust-lang/rust/pull/91894
- [x] compiler\rustc_infer\src\lib.rs #91878
- [x] compiler\rustc_metadata\src\lib.rs #91926 
- [x] compiler\rustc_middle\src\lib.rs #91984
- [x] compiler\rustc_mir_dataflow\src\lib.rs #91922
- [x] compiler\rustc_mir_transform\src\lib.rs #91638
- [x] compiler\rustc_monomorphize\src\lib.rs https://github.com/rust-lang/rust/pull/91895
- [x] compiler\rustc_passes\src\lib.rs https://github.com/rust-lang/rust/pull/91896
- [x] compiler\rustc_privacy\src\lib.rs #91925
- [x] compiler\rustc_query_impl\src\lib.rs #91923
- [x] compiler\rustc_symbol_mangling\src\lib.rs #91901
- [x] compiler\rustc_trait_selection\src\lib.rs #91904
- [x] compiler\rustc_traits\src\lib.rs #91929
- [x] compiler\rustc_typeck\src\lib.rs https://github.com/rust-lang/rust/pull/91882
- [x] library\proc_macro\src\lib.rs #91906

I've marked this `E-easy` as it's very mechanical work.  If you're interested in helping out:

- Get your dev environment set up so that you can successfully build the compiler, see https://rustc-dev-guide.rust-lang.org/
- Post the crate you'll tackle, to avoid duplicate work.  (I suggest picking ~randomly, not going in order.)
- Delete the `#![feature(in_band_lifetimes)]` line from the `lib.rs` file
- Look at the compiler errors, and either
  - See that the undeclared lifetime is single-use, and thus replace it with `'_`, or
  - If it's used multiple times, declare it at the appropriate scope.
- Once it compiles again, review the git diff to ensure it has *only* lifetime annotation changes.
- EDIT: Remember to run `x.py fmt` and `x.py test tidy`!
- Send a PR cc'ing this issue, and edit your previous post to include the PR number.

If you'd like to see how these PRs end up looking, here's two that I made earlier:

- #91580
- #91638

(They're also listed in the checklist above.)

**Comment by LegionMammal978** [comment]
Something tricky I've found: Suppose a trait is implemented with `impl Trait<'tcx> for Type<'tcx> { ... }`. Then, when `in_band_lifetimes` is disabled, the compiler assumes that it only implements `Trait<'static>`, and generates an error whenever you use a method or subtrait of `Trait<'tcx>` that depends on `'tcx`. The general error always contains `note: expected Trait<'_>`, `found Trait<'static>`, so you should find the type being used, find where it implements `Trait`, and change that to use `impl<'tcx> Trait<'tcx> for Type<'tcx> { ... }`, which should make the errors go away.

**Comment by bugadani** [comment]
I can give `rustc_borrowck` a try

**Comment by Patrick-Poitras** [comment]
I'll try with `rust_typeck`

**Comment by pitaj** [comment]
I'll take `rustc_hir` and `rustc_incremental`

**Comment by SylvanB** [comment]
I'll take `rustc_symbol_mangling` .

**Comment by anuvratsingh** [comment]
will try `library\proc_macro\src\lib.rs`

**Comment by Patrick-Poitras** [comment]
I'll give rust-middle a try.

**Comment by Patrick-Poitras** [comment]
I'm going to be yielding `rust-middle` to the queue again. Anyone can take it, but I'm the second person to return this to the queue due to some difficult structures. I'd recommend someone that has worked with `rustc_middle` before, or at least a more experienced contributor than myself.

It has a lot of the small detail work that we would find with the other removals, but there's a few pieces that are entirely out of my grasp, and may require the work of someone with a certain level of expertise. There's a proc macro derived in many of the structs used that uses an inband-lifetime, and several other macros that use a lifetime for some of the structs but not others. Sorting through this requires more-than-surface-understanding of the module.

**Comment by Aaron1011** [comment]
I'll take `rustc_middle`

**Comment by scottmcm** [comment]
Thanks everyone for jumping on this so quickly!  It looks like all the crates have been picked up, so I've removed the E- tags for now so it stops showing up in queries for people looking for things.

**Comment by scottmcm** [comment]
Looks like these have all landed, so I'll close this.

Thanks for the help, everyone!
