### ISSUE TITLE
Tracking issue for thread local Cell methods

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#92122]
Feature gate: `#![feature(local_key_cell_methods)]`

This is a tracking issue for thread local Cell methods: [RFC 3184](https://github.com/rust-lang/rfcs/pull/3184).

### Public API

```rust
impl<T: 'static> LocalKey<Cell<T>> {
    pub fn set(&'static self, value: T);
    pub fn get(&'static self) -> T where T: Copy;
    pub fn take(&'static self) -> T where T: Default;
    pub fn replace(&'static self, value: T) -> T;
}

impl<T: 'static> LocalKey<RefCell<T>> {
    pub fn with_borrow<F, R>(&'static self, f: F) -> R where F: FnOnce(&T) -> R;
    pub fn with_borrow_mut<F, R>(&'static self, f: F) -> R where F: FnOnce(&mut T) -> R;
    pub fn set(&'static self, value: T);
    pub fn take(&'static self) -> T where T: Default;
    pub fn replace(&'static self, value: T) -> T;
}
```

### Steps / History

- [x] RFC: https://github.com/rust-lang/rfcs/pull/3184
- [x] Implementation: #92123
- [x] Final comment period (FCP): https://github.com/rust-lang/rust/issues/92122#issuecomment-1660551128
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/114689

### Unresolved Questions

- ~~Is the behavior of `set()` (to skip the default initialization) the right behavior?~~ Yes.
- Are there any other types commonly used as thread locals for which we should do something similar?
  - Do we also want anything for `UnsafeCell`? Maybe `LocalKey<UnsafeCell<T>>::get()` to get the `*mut T`, just like `UnsafeCell<T>::get()`. 
  - Not a blocker for stabilizing this feature. Methods for other types can be a separate feature.

**Comment by dymayday** [comment]
Hello,
Can it be stabilized ?

**Comment by m-ou-se** [comment]
Nominated this for discussion in the next libs-api meeting.

I believe the only remaining point of discussion is the behaviour of `.set()`:

The `.set()` method bypasses the lazy initialization that `.with(|v| v.set())` would perform, making this pattern possible:

```
thread_local! {
    static ID: Cell<i32> = panic!("ID not set on this thread!");
}

fn main() {
    ID.set(123); // OK, no panic.
    println!("{}", ID.get()); // OK, no panic now that it has been set.
}
```

**Comment by dymayday** [comment]
Awesome ! And thank you for your answer.

**Comment by tgross35** [comment]
> Nominated this for discussion in the next libs-api meeting.
> 
> I believe the only remaining point of discussion is the behaviour of `.set()`:

Was there any specific resolution on this? (I have no qualms, just wondering for completeness)

**Comment by m-ou-se** [comment]
Initially, not everyone was convinced this was a good idea. Some thought that making `.set()` not do the same as `.with(|x| x.set())` can result in subtle bugs. But after some discussion, we couldn't think of common situations where that'd easily result in bugs. We discussed some valuable use cases that are enabled by the proposed behaviour of `.set()`. Eventually we concluded that the proposed behaviour is acceptable and sometimes very useful, on the condition that the behaviour is well documented (which it already is).
