### ISSUE TITLE
Tracking Issue for `saturating_int_assign_impl`

### ISSUE THREAD

**Issue by kellerkindt** [rust-lang/rust#92354]
Feature gate: `#![feature(saturating_int_assign_impl)]`

This is a tracking issue for adding basic integer operations to the `Saturating` Wrapping type:
```rust
let mut value = Saturating(2u8);
value += 3u8;
value -= 1u8;
value *= 2u8;
value /= 2u8;
value %= 2u8;
value ^= 255u8;
value |= 123u8;
value &= 2u8;
```

<details>
  <summary>
    <s>As well as</s>
  </summary>

  See https://github.com/rust-lang/rust/pull/93208#issuecomment-1022564429. **No longer** within the scope of this feature:

  ```rust
  let mut value = Saturating(2u8);
  let _: Saturating<u8> = value + 3u8;
  let _: Saturating<u8> = value - 1u8;
  let _: Saturating<u8> = value * 2u8;
  let _: Saturating<u8> = value / 2u8;
  let _: Saturating<u8> = value % 2u8;
  let _: Saturating<u8> = value ^ 255u8;
  let _: Saturating<u8> = value | 123u8;
  let _: Saturating<u8> = value & 2u8;
  ```
</details>

### Steps / History

 - [x] Implement basic `Saturating` type #87920
 - [x] Proposal for this implementation:  #91586
 - [x] Implementation of `saturating_int_assign_impl` #92356
   - [x]  Reduce `saturating_int_assign_impl` #93353 
 - [ ] Final comment period (FCP)
 - [ ] Stabilization PR

### Unresolved Questions

- Is this reasonable?

An implementation for the `Wrapping` type is planned as follow up.
