### ISSUE TITLE
Tracking Issue for Associated Const Equality

### ISSUE THREAD

**Issue by JulianKnodt** [rust-lang/rust#92827]
This is a tracking issue for the feature Associated Const Equality brought up in #70256.
The feature gate for the issue is `#![feature(associated_const_equality)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Fully implement the feature
  - [ ] Teach Chalk about terms (enum Ty or Const relating an associated type or const respectively)
  - [ ] Remove all FIXME(associated_const_equality)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

XXX --- list all the "unresolved questions" found in the RFC to ensure they are
not forgotten

### Implementation history

- Initial Effort which includes parsing and use of `term` throughout the codebase in #87648, but still lacking a complete implementation.

**Comment by pushkine** [comment]
Hello!
Is there a corresponding RFC, or any context whatsoever concerning those changes ? 
This is the first occurrence of language syntax change that is not backed by RFC and community feedback
@Centril @oli-obk

**Comment by oli-obk** [comment]
Well, we have https://github.com/rust-lang/rust/issues/70256 which indeed has basically no discussion of the feature. It just seemed like an oversight to have associated types + associated type bounds, but only associated consts without any bounds for them.

**Comment by JulianKnodt** [comment]
I probably should've tagged the original issue in this at the start (it was in the original PR if I remember correctly) but I'm bad at leaving a thorough paper trail. I'll add a reference to the original issue in the issue itself, and if there's more work that needs to be done please let know

**Comment by oli-obk** [comment]
You did everything correctly. I found the issue because you did link it in the first sentence in this issue 😄

We should probably do a lang team MCP for it along with some medium sized doc explaining what is going on and why. I'll open a hackmd and then we can collab on it

**Comment by joshtriplett** [comment]
What's the current state of this? How much is implemented, and how functional is it?

**Comment by JulianKnodt** [comment]
@joshtriplett I've started work on it, and the syntax/parsing is in place, but the implementation currently does not work. I started working on Chalk, but that has stalled since I wasn't really able to know whether it was necessary for implementing it in rustc. I've also gotten a bit sidetracked working on other things.

**Comment by urben1680** [comment]
Is it plannet to recognize Associated Constant Equality as disjoint cases?
```rs
trait Foo{ /*stuff*/ }
trait Bar{
    const DECIDER: bool;
}
impl<T: Bar<DECIDER = true>> Foo for T{ /*stuff*/ }
impl<T: Bar<DECIDER = false>> Foo for T{ /*stuff*/ }
```

**Comment by JulianKnodt** [comment]
@urben1680 I believe this would be the main point of this, but I have not got around to actually implementing it

**Comment by djdisodo** [comment]
```rust
pub struct ConstNum<const N: usize>;

pub trait Is<const N: usize> {}

impl<const N: usize> Is<N> for ConstNum<N> {}


struct Bar<const N: usize>([u8; N]);

fn foo<const N: usize>(_input: Bar<N>) where ConstNum<N>: Is<2> {
    
}

fn main() {
    let bar = Bar([0u8; 2]);
    foo(bar);
}
```

**Comment by ifsheldon** [comment]
Another use case would be checking tensor shapes. I hit this issue when compiling my code that constrains the shapes of input tensors to have the same dimensionality and/or rank. 

For example, dumb code like the below
```rust
pub trait TensorShape1D {
    const SHAPE: usize;  // i.e. length
}

pub fn add<const L: usize, LEFT_TENSOR: TensorShape1D<SHAPE=L>, RIGHT_TENSOR: TensorShape1D<SHAPE=L>>(left: LEFT_TENSOR, right: RIGHT_TENSOR) {
    todo!()
}
```
Any two structs that implement `TensorShape1D` and have the same `SHAPE` can be the input of this function.

Right now, I have to use `typenum` crate and associated type to do the same checking, but it would be great to not have to type-dance like `typenum`. I think when this is implemented, `typenum` can be greatly simplified.

**Comment by oli-obk** [comment]
I am locking this, as it is a tracking issue. Please open a thread on zulip for discussions or open issues for any issues you encounter.

**Comment by fmease** [comment]
PSA: The feature (`associated_const_equality`) has now been integrated into the incomplete unstable feature `min_generic_const_args` (tracking issue: #132980). Please subscribe to said tracking issue if you'd like to continue watching this now subfeature! The plan is to include ACE in the upcoming mGCA RFC.

This tracking issue will be closed soon once I've reorganized some things.
