### ISSUE TITLE
Tracking Issue for Option::is_some_and and Result::is_{ok,err}_and

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#93050]
Feature gate: `#![feature(is_some_and)]`

This is a tracking issue for `Option::is_some_and`, `Result::is_ok_and` and `Result::is_err_and`.

### Public API

```rust
impl<T> Option<T> {
    pub fn is_some_and(self, f: impl FnOnce(T) -> bool) -> bool;
}

impl<T, E> Result<T, E> {
    pub fn is_ok_and(self, f: impl FnOnce(T) -> bool) -> bool;
    pub fn is_err_and(self, f: impl FnOnce(E) -> bool) -> bool;
}
```

### Steps / History

- [x] Lots of discussion and bikeshedding starting here: https://github.com/rust-lang/rust/issues/62358#issuecomment-970280621
- [x] Implementation: #93051
- [x] Rename: https://github.com/rust-lang/rust/pull/94765
- [x] Take `self` by value: https://github.com/rust-lang/rust/pull/98354
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- [x] Naming. Alternatives:
   - `is_some_with` / `is_ok_with` / `is_err_with`
   - :arrow_right: `is_some_and` / `is_ok_and` / `is_err_and`
     - See https://github.com/rust-lang/rust/issues/93050#issuecomment-1016407980 and https://github.com/rust-lang/rust/issues/93050#issuecomment-1019312470
   - `contains` / `contains_err`
   - `and_is` / `and_err_is`
   - `is`
   - `has`
- [x] Take `self` or `&self`?

**Comment by the8472** [comment]
What are the use-cases? And won't that largely be covered by if-let chains?

```rust
if let Some(foo) = opt && foo > bar {
   
}
```

**Comment by m-ou-se** [comment]
Lots of functions on `Option` and `Result` are already 'covered' by `match` or `if let`, but it's still very useful to have methods for the most common cases. It makes things more readable and less verbose, and also easier to write (especially with auto completion).

```rust
let deadline_passed = optional_deadline.is_some_with(|d| d < now);

let deadline_passed = matches!(optional_deadline, Some(d) if d < now);

let deadline_passed = if let Some(d) = optional_deadline && d < now { true } else { false };
```

**Comment by camsteffen** [comment]
`is` or any name ending in "is" will not flow well with function names that follow: `opt.and_is(char::is_lowercase)`, `dog.and_is(Dog::has_a_bone)`, etc.

`is_some_and` flows better. I would consider the shorter `some_and` as well.

**Comment by m-ou-se** [comment]
> I assume `deadline_passed`would then flow into another `if` in which case one could do an if-let-chain (once that's stable) directly rather than having a separate variable for that.

This example about a `deadline: Option<Instant>` comes directly from code I worked on recently. Checking some condition on a `Some` is a pattern that occurs reguarly there. In some cases it's just used in an `if` directly, but in many cases the value is stored in some struct first, or used by multiple `if`s, or passed to a function, serialized and sent over a socket, etc. In some cases it's only used in a single `if`, but part of a much more complicated condition. Various parts of that condition are first assigned to named `bool`s to keep things clear. (Just like why people use `matches!()` rather than a `match` or `if let` in some situations. Or `x.is_some()` rather than `if let Some(_) = x`. And so on.)

> Or maybe just `is`?

I've added `is` and `has` to the alternatives.

**Comment by m-ou-se** [comment]
There are 117 cases of `.map_or(false, ` in the `compiler/` directory in the rust repository. Most of them are probably good examples of use cases for these methods.

**Comment by jakoschiko** [comment]
The name `is_some_and` would allow us to add its counterpart `is_none_or` in the future.

**Comment by m-ou-se** [comment]
> is_some_and

After thinking about it a bit more, I like this name. It very clearly states that it first checks `is_some`, `and` then also checks a condition afterwards.

**Comment by camsteffen** [comment]
FWIW this was attempted in #75298.

**Comment by kekeimiku** [comment]
Want this feature, for example the following use case feels very convenient
`.filter(|v:&Result<Vec<usize>>| v.is_ok_and(|x| !x.is_empty()))`

**Comment by jam1garner** [comment]
As someone who finds map_or both overly verbose for this (I need this version far more than the general case of map_or) and generally unpleasant (due to argument order not matching the name, although I 100% understand that decision even if I don't love it) I would be thrilled for this.

I think the worry about overlap with if/let is valid but for filtering and other combinators this composes really well (having played with it some now)

Also +1 to `is_some_and` for the name, very much a fan

**Comment by filip-hejsek** [comment]
I often define similar functions in my code as an extension trait, and `is_some_or` is exactly the name i used (before it was added to nightly rust). I think it's a very intuitive name.

I would like to also see the `is_none_or` counterpart added to Rust. Note that `is_none_or` cannot be easily expressed using if-let chains.

**Comment by AmitPr** [comment]
Would love to see this stabilized. My usecase is checking if a submitted value matches the last value, if there was a last value:
```rs
//Earlier, for example:
let last : Option<u64>;
let next : u64;
//In logic
if last.is_some_and(|v| v == next) {
    return Err(());
}
```

**Comment by m-ou-se** [comment]
@AmitPr `if last == Some(next)` should also work, right?

**Comment by SrTobi** [comment]
@m-ou-se: not if `next` is expensive.

**Comment by m-ou-se** [comment]
It seems like everybody is happy with the current names for these methods. I think it's time to consider stabilization.

@rfcbot merge

**Comment by m-ou-se** [comment]
`is_none_or` is a separate method that has been suggested but isn't part of this tracking issue.

**Comment by SrTobi** [comment]
Thx, does this mean we have to create a new issue for that method or is it somehow possible to attach it to this issue? I can also do the impl, just not sure how the process is.

**Comment by m-ou-se** [comment]
I think functions named `is_` shouldn't consume `self`. If you want to consume it, I feel like a `map_or` would be more appropriate. Making many use cases of `is_some_and` more verbose by forcing them to use `.as_ref()` doesn't seem great.

**Comment by m-ou-se** [comment]
> Thx, does this mean we have to create a new issue for that method or is it somehow possible to attach it to this issue? I can also do the impl, just not sure how the process is.

You can propose it here: https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29

**Comment by camsteffen** [comment]
> I think functions named `is_` shouldn't consume `self`.

I see where you're coming from and I can get behind that. My only reservation is that I think this method will most often be used on a temporary value, like `some_function().is_some_and(...)` and in that case it feels weird to be given a reference when `is_some_and` is the sole user of the `Option` before it gets dropped. On the other hand I can see how, in other cases, `is_some_and` causing a "moved here" error could be surprising.

I just opened a PR using the method in rustc. I needed to destructure the reference (as in `is_some_and(|&foo| ..)`) a *lot* to get around type errors. Not really a big deal, the "extra reference" scenario is pretty common in Rust. There were only [two](https://github.com/rust-lang/rust/blob/10f4ce324baf7cfb7ce2b2096662b82b79204944/compiler/rustc_trait_selection/src/traits/select/mod.rs#L1482) [instances](https://github.com/rust-lang/rust/blob/10f4ce324baf7cfb7ce2b2096662b82b79204944/compiler/rustc_query_system/src/dep_graph/graph.rs#L802) where I had to stick with `map_or` because the value was not Copy. But I think rustc deals with a disproportionate amount of Copy values and other code repos will hit that scenario (must use `map_or`) more often.

**Comment by RalfJung** [comment]
I like `is_some_and` as replacement for `map_or(false, ...)`. But then the obvious question is, do we also want a similar function for `map_or(true, ...)`? The natural name would probably be something like `is_none_or`.

`rg 'map_or\(true' compiler/ | wc -l` says there are at least 37 uses of `map_or(true, ...)` in the compiler sources.

**Comment by RalfJung** [comment]
> I think functions named `is_` shouldn't consume `self`. If you want to consume it, I feel like a `map_or` would be more appropriate. Making many use cases of `is_some_and` more verbose by forcing them to use `.as_ref()` doesn't seem great.

I find `map_or(true/false` rather error-prone; each time I see them I have to stop and think carefully about what happens. `is_some_and`/`is_none_or` make such code a lot more readable. Hence I think we should have a by-value function with those semantics.

If the leading `is` is the problem, we could use `some_and`/`none_or`, i.e., drop the leading `is_`?

**Comment by m-ou-se** [comment]
> I think this method will most often be used on a temporary value, like some_function().is_some_and(...)

> I needed to destructure the reference (as in is_some_and(|&foo| ..)) a lot [..]

Oh, interesting. Every single time I wanted this function, it was on something that I did not want to consume. I didn't realize consuming would be such a common use case.

Aborting the FCP, because we clearly need to figure this out before it's ready for stabilization. :)

@rfcbot abort

**Comment by m-ou-se** [comment]
@rfcbot cancel

**Comment by joshtriplett** [comment]
It does seem like most combinators for option and result types use values. Having to call `as_ref` doesn't seem too onerous, and doing so won't be necessary for copy types.

**Comment by camelid** [comment]
Having `is_some_and` consume the option would conflict with Rust's (and `Option`'s) existing "policy" of having `is_` functions take `&self`, so IMO a different name would be needed in that case.

**Comment by Xiretza** [comment]
The same could be said about a "policy" of `is_` methods not taking any arguments, I'm not sure either is a useful metric to apply here.

**Comment by MatrixDev** [comment]
Is there any reason to actually consume `Option` here?

IMHO in my use cases most of the time I only need to check value inside `Option` and consuming it will be to a detriment. Basically for consuming we already can use `and_then`.

PS: same arguments go for `Result`.

**Comment by RalfJung** [comment]
I almost always want to consume the value, since it is a temporary that will anyway not be used afterwards. Having to use `map_or` or `and_then` makes the code a lot harder to read.

If you don't want to consume it, you can use `as_ref`, like with any other `Option` function. Basically all of them consume their argument, if there is any reason for them to. `is_some`/`is_none` are exceptions because it would be entirely pointless for the to consume their argument.

**Comment by MatrixDev** [comment]
> `is_some`/`is_none` are exceptions

@RalfJung, I don't know about you, but for me `is_some_and` is very familiar to `is_some`, it just takes function to customise the result. It becomes very confusing with such names, as most other places (maybe there are exceptions) don't change received type when adding suffix for the method name.

This just doesn't seem intuitive in a slightest, at least for me.

**Comment by RalfJung** [comment]
As I stated above, for me `is_some_and(f)` is syntactic sugar for `map_or(false, f)`. This improves readability by a *lot*; I find the `map_or` invocation so hard to read that I often rather write a `match` despite its verbosity. (One part of this is probably the occurrence of "or" in the name, even though this is logically an "and" as indicated by `is_some_and`.)

**Comment by MatrixDev** [comment]
@RalfJung, I'm only agains the naming, not your idea in general. If `is_some` takes reference, `is_some_xxx` should take a reference as well. I'd prefer a different naming for consumption that doesn't have such conflicts.

You're talking about confusing naming, but nevertheless have no problems with adding even more "types" of consumption prefixes for Option methods that behave differently from what we already have.

Also your approach will forbid me from calling `is_some_and` for option arguments that are already a reference and cannot be consumed, which I think is much worse than not liking `map_or` syntax.

**Comment by RalfJung** [comment]
> Also your approach will forbid me from calling is_some_and for option arguments that are already a reference and cannot be consumed, which I think is much worse than not liking map_or syntax.

This has been discussed above; you can just use `x.as_ref().is_some_and`. That still has the clear readability of `is_some_and`.

Making it consume ownership is strictly more general/powerful than making it take a reference.

I am not tied to the name either, and also stated that above already. :)

> If the leading is is the problem, we could use some_and/none_or, i.e., drop the leading is_?

**Comment by SabrinaJewson** [comment]
Since the non-consuming version leaves the option unusable afterward, maybe it should be called `was_some_and` (half-joking here, but if it had any precedent it wouldn't even be a bad name IMO).

**Comment by camsteffen** [comment]
I doubt the mismatch in the signature with `is_some` would actually cause much or any confusion in practice. When using `is_some`, I don't give a thought to what the signature is. I agree there's value in consistency, but I think that's a small loss when weighed against the benefit of being a total replacement for `map_or(false, `. Also consider `&self` is useless for a `Option<&mut T>`.

Sure we could resolve the tension by using a different name, but I feel that `is_some_and` is a _very excellent_ name that is unrivaled for readability. It's extremely clear and even has smooth grammatical flow in real usages.

In my mind, `and_if` is the one other viable name option. That name seems to have been forgotten since the other thread. It's more analogous to `and_then`, which takes `self`.

**Comment by BurntSushi** [comment]
It's not clear to me that something like `is_some_and` is better than `map_or(false`. That is, given the choice, I'm pretty sure I'd take the latter option almost every time. I think that the former _could_ be justified if it became a core part of someone's vocabulary, but I don't think it will get used enough for that. `map_or` on the other hand is virtually self-describing, and makes the fallback value (when the `Some` isn't present) very clear. But `is_some_and` kind of requires thinking about it a little bit and realizing that `and` implies that `false` is returned if it's a `None` value.

Here's my main point: if I stumbled across these routines in a code review without previous knowledge of them, I'd probably have to look it up. If I stumbled across `map_or` without previously knowing about them, I probably wouldn't have to look it up. Obviously, this isn't a universal litmus test (I might have to look up `and_then` too, for example), but it's what stands out to me the most for this case.

To be clear, I don't think I feel super strongly about this. But as it stands, I'm not totally convinced these are worth adding.

**Comment by jplatte** [comment]
As a small data point, I grepped through the projects I'm mostly working on ([Ruma](https://github.com/ruma/ruma) and [matrix-rust-sdk](https://github.com/matrix-org/matrix-rust-sdk)) and found two or three cases of `.as_ref().map_or(false, ...)`, but I'm pretty sure none of the (overall many more) `.map_or(false, ...)` invocations needed to consume the `Option`.

This matches my intuition / preference towards the current signature; I think the readability of `is_some_and` isn't the only advantage over `map_or(false, ...)`, not having to call `.as_ref()` first to avoid consuming the `Option` is also an advantage IMHO.

**Comment by joshtriplett** [comment]
> In my mind, `and_if` is the one other viable name option.

I think that's substantially less readable. `is_some_and` felt intuitively obvious the moment I saw it. `and_if` reads nicely in an `if` (`if x.and_if(|val| cond(val)) { ... }`), but it doesn't read as nicely in any other context.

**Comment by SrTobi** [comment]
`opt.is_some_and(f)` is also equivalent to `opt.into_iter().any(f)` or `opt.iter().any(f)`. So a possible name would also be just `any` (and `all` for `is_none_or`).
`Iterator::any` also already takes a value, so no new precedence and it would be consistent naming.

Scala does this with its [`Option.exists`](https://www.scala-lang.org/api/2.13.3/scala/Option.html#exists(p:A=%3EBoolean):Boolean)

**Comment by scottmcm** [comment]
I really like the argument that `is_` implies `&self`, whereas some of the other names (`and_if`, etc) imply `self`.

So I think the two questions are tied together.

**Comment by joshtriplett** [comment]
Meanwhile, let's gauge consensus on adding this method orthogonally to whether it takes `self` or `&self`.

I'm going to FCP this and immediately raise a blocking concern. I intend to leave the concern until we see how the by-value version works out in practice (ideally via a draft of the aforementioned PR).

If you would approve this either way, or if you would approve whichever version makes for simpler code in practice, go ahead and check your box. If you would only approve one version but not the other, and that doesn't depend on the practical consideration of which one produces simpler code, you may want to raise a separate concern for that.

@rfcbot merge
@rfcbot concern ref

**Comment by jakoschiko** [comment]
This reminds me of the let-expression RFC #3159. It would allow to write this:
```rust
assert!((let Some(x) = a) && (let Some(y) = b(x)) && x == y);
```

**Comment by philpax** [comment]
Hi - not sure what the best way to show support for this is, but weighing in to say that I'd very much appreciate this (or some variant of it, like the language extension proposed above.)

I am working with an ECS that lets me retrieve components through an `Option`; I find myself needing to evaluate predicates against those components reasonably often (e.g. `get(tags).map_or(false, |t| t.contains(a_tag)))`). 

Unfortunately, the ways of currently doing this aren't easy to parse for a reader - `map_or(false, predicate)` or `map(predicate).unwrap_or_default()` both obscure the primary objective of the operation to me (it's not really clear what either of those are doing unless you've seen them before)

I would much rather be able to do `get(tags).is_some_and(|t| t.contains(a_tag))` (or some variant thereof), which I find to be _vastly_ more readable / semantically obvious. (In a sense, this is me responding directly to [BurntSushi's comment](https://github.com/rust-lang/rust/issues/93050#issuecomment-1166327427) from above; I think the proposed alternative is much clearer than what currently exists!)

That being said, if it is possible to replace the majority of the `Option`/`Result` combinators with something more general-purpose within the language itself, I would also love that. I'm really just throwing my weight behind the general principle 🙏

**Comment by camsteffen** [comment]
> @camsteffen Apologies for the extra work, but would you be willing to make a draft PR that 1) modifies the signature of `is_some_and` (I saw that you had a PR for that previously), and then 2) includes an updated version of #98427 that shows what that would look like with a by-value signature?

Here you go! #99087

**Comment by joshtriplett** [comment]
Looks to me like by-value improved the vast majority of cases.

**Comment by kekeimiku** [comment]
Suddenly it feels like having map_or is enough, it seems unnecessary to make Option Result more bloated if it's just for readability without any other advantages.
   (please feel free to ignore my statement

**Comment by arniu** [comment]
Why not add `map_or_default` / `map_err_or_default`?

**Comment by Amanieu** [comment]
> Looks to me like by-value improved the vast majority of cases.

If we do decide to go with that then the docs should have an example using `.as_ref()`.

**Comment by czipperz** [comment]
I'd like `is_none_or`.  I have a code block like this:

```
list.iter().filter(|x| {
            if let Some(symbols) = &symbols {
                symbols.contains(&x)
            } else {
                true
            }
})
```

it could instead be:
```
list.iter().filter(|x| {
            symbols.is_none_or(|symbols| symbols.contains(&x))
})
```

**Comment by joshtriplett** [comment]
@rfcbot resolved ref
@rfcbot concern should-take-self-by-value

**Comment by jdahlstrom** [comment]
(This is slightly tangential but also a potential argument against adding a new method when there's an existing, almost as concise alternative:)

Huh. To me the obvious way to write "is_some_and()" has always been `filter().is_some()` rather than `map_or`:

```rust
optional_deadline.is_some_and(|d| d < now);
```
vs
```rust
optional_deadline.filter(|d| d < now).is_some();
```

but I haven't seen it mentioned in this (or the previous) thread. Maybe it's less idiomatic than I thought? I noticed that `Option::filter` has only been stable since 1.27 so there's maybe that?

**Comment by RalfJung** [comment]
I didn't even know `filter` existed, I would have thought you would have to `into_iter` first. Nice!

**Comment by arniu** [comment]
[RFC: map_or_default in Option and Result](https://github.com/rust-lang/rfcs/pull/3148)

We should add a single `map_or_default` rather than `is_some_and` / `is_ok_and`.

**Comment by Amanieu** [comment]
I don't think `map_or_default` is the right solution here: if anything, it's less readable than a plain `map_or`.

**Comment by jam1garner** [comment]
> I don't think `map_or_default` is the right solution here: if anything, it's less readable than a plain `map_or`.

Agreed, just to be another data point: I virtually never use the `*_or_default` methods for primitives. Using `unwrap_or*` as an example, not only is `.unwrap_or(false)` *shorter* than `.unwrap_or_default()`, but it is one less layer of cognitive indirection (in terms of what an  internal monologue might looks like: "unwrap or default. what is the default? false". potentially worse if it takes a second to think about what type).

**Comment by arniu** [comment]
Maybe `map_or_default` is not the right solution here, but it's better than `is_some_and` / `is_ok_and` / `is_err_and`.

**Comment by OliveIsAWord** [comment]
Adding my own data point in support of `is_none_or`. My current use case is parsing a language with significant whitespace.
```rust
let foo = tokens.last().map(Token::kind);
let n = Token::Newline;
// `bar` should be true iff the latest token wasn't a newline or if this is the beginning of the source code.
let bar = match foo {
    Some(x) if x == n => false,
    _ => true,
};
let bar = foo.map_or(true, |x| x != n);
let bar = foo.is_none() || foo.unwrap() != n;
let bar = foo.is_none() || foo.is_some_and(|x| x != n);
let bar = foo.filter(|y| y == n).is_none();
let bar = foo.is_none_or(|x| x != n);
```
I hope you agree that using `is_none_or` provides the shortest and most readable solution.

**Comment by m-ou-se** [comment]
I'd be happy to approve a PR that adds `is_none_or` as an unstable function. :)

**Comment by urben1680** [comment]
I would have a use case for this too. 
I have a `VecDeque` and at some point I want to find out if I need to pop the front.
I would do this if:
1. There is a second element
2. The second element has a certain value

```rs
if self.entries.get(1).is_some_and(|second| second == value) { //...
```

**Comment by flukejones** [comment]
Hexerator is currently using this https://github.com/crumblingstatue/hexerator/commit/8d643c5153dbe366b55b607972031cabaa7705c2

**Comment by SUPERCILEX** [comment]
Since it is unclear to me that the past few examples are aware of `matches` (I certain wasn't!), here's some rehashing:
- @flukejones: https://github.com/crumblingstatue/hexerator/pull/41
- @urben1680: `matches!(self.entries.get(1), Some(second) if second.value == value)`
- @philpax: `matches!(get(tags), Some(t) if t.contains(a_tag))`

**Comment by dogunbound** [comment]
I have a use case for it too:

```rust
fn is_draw_full_cell_enabled(color_cell: Option<Rc<RefCell<ColorCell>>>) -> bool {
    if let Some(color_cell) = color_cell {
        color_cell.borrow().draw_full_cell
    } else {
        false
    }
}
match event {
    Event::MouseButtonPressed { button, x, y }
        if is_draw_full_cell_enabled(
            color_grid.mouse_position_to_cell_mut(Vector2::new(x, y)),
        ) => {}
    _ => {}
}```

Could just be:
```rust
match event {
    Event::MouseButtonPressed { button, x, y }
        if color_grid
            .mouse_position_to_cell_mut(Vector2::new(x, y))
            .is_some_and(|cell| cell.borrow().draw_full_cell) => {}
    _ => {}
}```


My code would be far simply if I could just do that.

**Comment by m-ou-se** [comment]
Looks like this got stuck at some point. I believe the main thing left to do was to change it to take `self` by value, which already happened in #98354.

Let's start a new FCP.

@rfcbot cancel

@rfcbot merge

**Comment by SUPERCILEX** [comment]
Was there a resolution to the concern that the same behavior could be achieved with `matches`?

**Comment by joshtriplett** [comment]
@SUPERCILEX `is_some_and` looks clearer and chains more easily. `matches!` requires going back to the beginning of the expression to open a `matches!(`, and looks more complex when embedding an `if` in it.

**Comment by SUPERCILEX** [comment]
@joshtriplett Fair enough, thanks!

**Comment by jplatte** [comment]
Is this just waiting for somebody to create a stabilization PR? I can probably do that if so.

**Comment by Amanieu** [comment]
> Is this just waiting for somebody to create a stabilization PR? I can probably do that if so.

Yes. Feel free to go ahead.

**Comment by asquared31415** [comment]
The description of this API in this tracking issue and in #110019 say that the closure takes `&T` but the implementation has the closure taking `T`.

**Comment by Amanieu** [comment]
We had a second FCP to change the closure to take `T`, but it seems that we forgot to update the issue description. I've just updated it.

**Comment by jplatte** [comment]
I totally forgot about all that.. Well I guess I will live with it. The draft PR to show that it made `is_some_and` calls "nicer" unfortunately didn't show any places where taking ownership of of the inner value was *necessary*, but maybe there are a few and it would probably be pretty annoying for some people for the combinator to not be applicable therethr same way I find the extra `as_ref` annoying where it is needed..

**Comment by wrenger** [comment]
Well, I don't know if these functions are really that essential. These checks can be made in several different ways.

```rust
let data = Some("foo");

if data == Some("foo") {
    //...
}
if data.is_some_and(|inner| inner == "foo") {
    //...
}
if let Some(inner) = data && inner == "foo" {
    //...
}
if matches!(data, Some(inner) if inner == "foo") {
    //...
}
```

The first might only be desirable in some cases, but the third one with `let-chains` https://github.com/rust-lang/rust/issues/53667 is a little bit more legible, in my opinion.

**Comment by tnblumer** [comment]
In which version should we expect this feature? I thought it was going to be in 1.70.0, but apparently not.

**Comment by RalfJung** [comment]
It is in 1.70.0 (see https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html)
