### ISSUE TITLE
Tracking Issue for `wrapping_int_assign_impl`

### ISSUE THREAD

**Issue by kellerkindt** [rust-lang/rust#93204]
Feature gate: `#![feature(wrapping_int_assign_impl)]`

This is a tracking issue for adding basic integer operations to the `Wrapping` type:
```rust
let mut value = Wrapping(2u8);
value += 3u8;
value -= 1u8;
value *= 2u8;
value /= 2u8;
value %= 2u8;
value ^= 255u8;
value |= 123u8;
value &= 2u8;
```
As well as
```rust
let mut value = Wrapping(2u8);
let _: Wrapping<u8> = value + 3u8;
let _: Wrapping<u8> = value - 1u8;
let _: Wrapping<u8> = value * 2u8;
let _: Wrapping<u8> = value / 2u8;
let _: Wrapping<u8> = value % 2u8;
let _: Wrapping<u8> = value ^ 255u8;
let _: Wrapping<u8> = value | 123u8;
let _: Wrapping<u8> = value & 2u8;
```

### Steps / History

 - [x] Proposal for this implementation:  #91586
 - [ ] Implementation of `wrapping_int_assign_impl` #93208
 - [ ] Final comment period (FCP)
 - [ ] Stabilization PR

### Unresolved Questions

- Is this reasonable?

This is analog to the implementation for the `Saturating` type here #92354

**Comment by m-ou-se** [comment]
Trait implementations like these for a stable type cannot be added as unstable, so there's nothing to be tracked. So, I'm closing this issue.

In general, please only create tracking issues after a reviewer from the libs-api team has approved of the new (unstable) feature and asked you to do so. (See also [the tracking issue template](https://github.com/rust-lang/rust/blob/ecf72996eda4f8af19b0ca7235c6f62e0245a313/.github/ISSUE_TEMPLATE/library_tracking_issue.md?plain=1#L14-L17).) You can use `issue = "none"` as a placeholder when opening a PR for a new unstable feature that doesn't have an RFC.
