### ISSUE TITLE
Tracking Issue for asm_experimental_arch

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/rust#93335]
The feature gate for the issue is `#![feature(asm_experimental_arch)]`.

### Summary

This feature tracks `asm!` and `global_asm!` support for the following architectures:
- NVPTX
- PowerPC
- Hexagon
- MIPS32r2 and MIPS64r2
- wasm32
- BPF
- SPIR-V
- AVR
- MSP430

### Status

Each architecture needs to be reviewed before stabilization:
- It must have `clobber_abi`.
- It must be possible to clobber every register that is normally clobbered by a function call.
- Generally review that the exposed register classes make sense.

**Comment by AtomicGamer9523** [comment]
Is there any news about AVR ? If not, where and how can I contribute to this?

**Comment by tgross35** [comment]
The top post mentions the following:

> Each architecture needs to be reviewed before stabilization:
>     * It must have `clobber_abi`.
>     * It must be possible to clobber every register that is normally clobbered by a function call.
>     * Generally review that the exposed register classes make sense.

Anyone can post a stabilization (or status) report answering the above, probably with examples/tests. Having that is probably a good place for any platform to start.

The bar for enabling AVR should be pretty low since it is tier 3. I'm not sure what exactly would be needed for wasm as requested by @solomatov, but we should make sure we have an idea of how complete or buggy LLVM support is (@alexcrichton maybe you have an idea about this, or know who would?)

**Comment by tgross35** [comment]
Cc @ecnelises with the above in case you are interested in moving ppc assembly forward, based on linked issues it seems like there may be some ecosystem use cases.

**Comment by alexcrichton** [comment]
Ah I don't know very much about inline assembly for the wasm target. I believe it works enough to do "some things" but that's the extent of my knowledge, and I wouldn't be prepared to assist with or myself propose stabilization. I also don't know who might know more about the wasm side of things other than "generally LLVM folks doing wasm things may know more", which I realize is unfortunately not very specific or actionable...

**Comment by tgross35** [comment]
@AtomicGamer9523 https://github.com/rust-lang/rust/pull/131258 is an example of stabilizing assembly for a target that is behind this feature. You could probably put up a similar PR for AVR.

**Comment by taiki-e** [comment]
In my understanding, here is the status on each architecture other than s390x (which already has stabilization PR):
(Disclaimer: I'm not an expert of any of these. In particular, I know almost nothing about asm for WASM, GPU and BPF.)

- Arm64EC (perhaps ready for stabilization)
  - [x] clobber_abi
  - [x] preserves_flags
- Nvptx64
  - [ ] clobber_abi
  - [ ] preserves_flags?
- Hexagon
  - [ ] `p*` register (clobber-only) should be supported (needed for writing code with branching)
  - [ ] clobber_abi
    - Refs: "7 Register usage across calls" in [Qualcomm Hexagon™ Application Binary Interface User Guide](https://lists.llvm.org/pipermail/llvm-dev/attachments/20190916/21516a52/attachment-0001.pdf)
  - [ ] preserves_flags?
- Mips, Mips64
  - [ ] clobber_abi
  - [ ] preserves_flags?
- PowerPC, PowerPC64
  - [ ] `v*` register (at least as clobber-only) should be supported (needed for clobber_abi on PowerPC64)
  - [ ] clobber_abi
    - Refs(32-bit SysV): "Function Calling Sequence" in [SYSTEM V APPLICATION BINARY INTERFACE PowerPC Processor Supplement](https://refspecs.linuxfoundation.org/elf/elfspec_ppc.pdf)
    - Refs(64-bit ELFv2): "2.2 Function Calling Sequence" in [OpenPOWER ABI for Linux Supplement Power Architecture 64-Bit ELF V2 ABI](https://ftp.rtems.org/pub/rtems/people/sebh/ABI64BitOpenPOWERv1.1_16July2015_pub.pdf)
    - Refs(64-bit ELFv1): "3.2. Function Calling Sequence" in [64-bit PowerPC ELF Application Binary Interface Supplement](https://refspecs.linuxfoundation.org/ELF/ppc64/PPC-elf64abi.html#FUNC-CALL)
    - Refs(AIX): https://www.ibm.com/docs/en/aix/7.3?topic=convention-linkage-overview
    - Previous attempts/open PRs: https://github.com/rust-lang/rust/pull/111335, https://github.com/rust-lang/rust/pull/124279
  - [x] preserves_flags is no-op, but (IIUC) `xer` and `cr*` supported as clobber-only registers correspond to this.
- SpirV: unsupported by LLVM
- Wasm32, Wasm64
  - [ ] clobber_abi
  - [ ] preserves_flags?
- Bpf
  - [ ] clobber_abi
  - [ ] preserves_flags?
- AVR
  - [ ] clobber_abi
    - Refs: https://gcc.gnu.org/wiki/avr-gcc#Call-Used_Registers
  - [x] preserves_flags
    - Docs simply says "The status register SREG", but (IIUC) I (Global Interrupt Enable) bit of it should not actually be considered as a target of this option. (the same as MSP430 case)
- MSP430
  - [ ] clobber_abi
    - Refs: "3.2 Register Conventions" in [MSP430 Embedded Application Binary Interface](https://www.ti.com/lit/an/slaa534a/slaa534a.pdf)
  - [x] preserves_flags
    - Docs simply says "The status register r2", but (IIUC) only C, Z, N, and V bits of it are should actually be considered as targets of this option. ([previous discussion](https://github.com/taiki-e/portable-atomic/pull/40#issuecomment-1281504378))
- M68k
  - [ ] clobber_abi
    - Refs: https://m680x0.github.io/doc/abi.html
  - [x] preserves_flags
- CSKY
  - [ ] clobber_abi
    - Refs(v2): "2.2.1 Register Assignments" in [C-SKY V2 CPU Applications Binary Interface Standards Manual](https://github.com/c-sky/csky-doc/blob/9f7121f7d40970ba5cc0f15716da033db2bb9d07/C-SKY_V2_CPU_Applications_Binary_Interface_Standards_Manual.pdf)
  - [ ] preserves_flags?
- Xtensa: unsupported in rust-lang/rust (supported in esp fork)


FYI:
- clobber_abi related code is [here](https://github.com/rust-lang/rust/blob/2b21f90d5efb8b76f9016dd88cf6f3c04216c33b/compiler/rustc_target/src/asm/mod.rs#L884-L1130).
- preserves_flags related code (LLVM) is [here](https://github.com/rust-lang/rust/blob/e561499e90d354b651ea23c93d2441ba971f6522/compiler/rustc_codegen_llvm/src/asm.rs#L229-L282).
- See [getReservedRegs in LLVM repo](https://github.com/search?q=repo%3Allvm%2Fllvm-project+%2F%3A%3AgetReservedRegs%2F&type=code) for registers reserved by LLVM.
