### ISSUE TITLE
Tracking Issue for unix_socket_creation

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/rust#93423]
Feature gate: `#![feature(unix_socket_creation)]`

This is a tracking issue for `os::unix::net::SocketAddr::from_path`.

### Public API

```rust
use os::unix::net::SocketAddr;

impl SocketAddr {
    pub fn from_path<P>(path: P) -> io::Result<SocketAddr>
    where
        P: AsRef<Path>;
}
```

### Steps / History

- [x] Implementation: [#93239](https://github.com/rust-lang/rust/pull/93239)
- [ ] Final comment period (FCP): https://github.com/rust-lang/rust/pull/94356#issuecomment-1050802322
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/94356

### Unresolved Questions

- [ ] Name it `from_pathname` to match `as_pathname`?
  - https://github.com/rust-lang/rust/pull/94356 renames the method to `from_pathname`.

**Comment by Thomasdezeeuw** [comment]
Starting to discuss stabilisation: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Stabilization.20of.20unix_socket_creation/near/273212183.
