### ISSUE TITLE
Tracking Issue for control-flow enforcement technology (CET)

### ISSUE THREAD

**Issue by abrown** [rust-lang/rust#93754]
This is a tracking issue for standardizing the control-flow enforcement technology (CET) flag, `cf-protection`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the unstable flag for `cf-protection`
- [ ] Standardize the `cf-protection` flag as a `-C` codegen flag

### Unresolved Questions

- [ ] Decide whether it is necessary/advisable to merge similar compilation flags (e.g. `cf-guard`, `cf-protection`, `branch-protection`) under a common flag interface
- [ ] Decide whether to build the standard libraries with `cf-protection` by default

### Implementation history

See #93439.

**Comment by xnox** [comment]
In distributions that already elect to build everything with CET enabled by default, we would want to turn it on by default in the rustc compiler and use it for the standard library, and everything by default.

The question is simply as to when. And what can be done to get there. I wonder if we could attempt rebuilding all packages with CET in the distribution to see how far the coverage goes.

**Comment by cuviper** [comment]
> In distributions that already elect to build everything with CET enabled by default, we would want to turn it on by default in the rustc compiler and use it for the standard library, and everything by default.

I don't see any way we could conditionally-default CET for rustup toolchains, but I think the way to go is to make it a rustbuild option, for such distributions to use when building their own Rust toolchain.

**Comment by haraldh** [comment]
one issue:
https://github.com/rust-lang/rust/issues/98768

**Comment by workingjubilee** [comment]
>  Decide whether it is necessary/advisable to merge similar compilation flags (e.g. cf-guard, cf-protection, branch-protection) under a common flag interface

If these are going to be independent compiler flags and not, say, target features, then yes, it may be a good idea to coalesce these. At least, certainly when the feature is functionally identical (e.g. `branch-protection=bti` vs. `cf-protection=branch`).

**Comment by tgross35** [comment]
Could we get a better summary of the status is here? There is this issue (cc @abrown), a tracking issue with no content for `cf-protection` https://github.com/stratis-storage/project/issues/418 (cc @mulkieran) and a tracking issue specifically for `cf-branch-protection`'s _stabilization_ (?) https://github.com/rust-lang/rust/issues/113369 (cc @jacobbramley). Then there's the CFI issue https://github.com/rust-lang/rust/issues/89653 and RFC https://github.com/rust-lang/rfcs/pull/3296 (cc @rcvalle), which aren't the same thing but cover similar areas.

My feeling is that since `cf-protection` is just a LLVM flag that has been in the compiler for two years, we can probably stabilize something here if someone makes a proposal about what flags to use, which will go through FCP. But the tracking issues are kind of chaotic, need to figure out what is going on there first

**Comment by jacobbramley** [comment]
@tgross35 I just updated #113369 with a link to a [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.60-Zbranch-protection.60.20stability) regarding merging with `cf-protection` (or not). I'd welcome further input!

**Comment by tgross35** [comment]
Thanks for the update Jacob, I think following up on Zulip is a good direction to go toward getting this done 👍
