### ISSUE TITLE
Tracking Issue for `used_with_arg`

### ISSUE THREAD

**Issue by nikic** [rust-lang/rust#93798]
The feature gate for the issue is `#![feature(used_with_arg)]`.

This extends the existing `#[used]` attribute with two variants `#[used(compiler)]` and `#[used(linker)]`:

* The `#[used(compiler)]` attribute indicates that the symbol should be considered used at the compiler level. It should not be eliminated by the compiler even if it appears unreferenced. This attribute guarantees that the symbol will make it to the linker.
* The `#[used(linker)]` attribute indicates that the symbol should additionally be considered used at the linker level. The linker should not eliminate the symbol even if it appears unreferenced.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Initial implementation: https://github.com/rust-lang/rust/pull/91504
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- [ ] What should `#[used]` default to? It is currently specified to only guarantee `#[used(compiler)]` but has historically acted like `#[used(linker)]` on non-ELF platforms. See https://github.com/rust-lang/rust/issues/47384 for extended discussion on the topic.
- [ ] `#[used(linker)]` currently uses SHF_RETAIN on ELF platforms, which is a relatively new flag. This means that the symbol may not actually be retained if an old linker is used.

**Comment by joshtriplett** [comment]
An addition to the unresolved questions: should we add both of these, or only add one of them? It may make sense to only have `#[used]` and `#[retain]`, for instance.

**Comment by jsgf** [comment]
Does `#[used(linker)]` imply `#[used(compiler)]` or does it mean the symbol is only considered used if it actually makes it past the compiler?

**Comment by kaspar030** [comment]
How can I help bringing this forward?

**Comment by steveklabnik** [comment]
Just an experience report: we use `used_with_arg` in Hubris, one of the last few nightly flags we use: https://github.com/oxidecomputer/hubris/blob/bef2484a71aaf5eff7e46fbbc6c90d0d4b562447/build/xtask/src/config.rs#L703-L708

Because this is an OS, we don't use the standard Rust test runner, but implement our own. The macro used to generate test cases uses `used(linker)`: https://github.com/oxidecomputer/hubris/blob/bef2484a71aaf5eff7e46fbbc6c90d0d4b562447/test/test-suite/src/main.rs#L50-L65
