### ISSUE TITLE
Tracking Issue for cfg_target_has_atomic_load_store

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#94039]
The feature gate for the issue is `#![feature(cfg_target_has_atomic_load_store)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

* [ ] Do we need a separate cfg for load/store operations, in combination with the existing `cfg(target_has_atomic = ...)`?

**Comment by josephlr** [comment]
I think the name of this feature is wrong, using it gives:
```
error[E0635]: unknown feature `cfg_target_has_atomic_load_store`
 --> src/lib.rs:5:12
  |
5 | #![feature(cfg_target_has_atomic_load_store)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It seems like the `#[cfg(target_has_atomic_load_store = ...)]` functionality is still gated on `#![feature(cfg_target_has_atomic)]`

**Comment by RalfJung** [comment]
Is there anything else guarded under `cfg_target_has_atomic`, besides `cfg(target_has_atomic_load_store)`?

**Comment by FeldrinH** [comment]
This feature would be really useful when trying to polyfill atomic CAS for targets that may or may not have atomic load/store. It seems that the implementation for `cfg(target_has_atomic_load_store)` is complete, and it has been used by the std implementation of atomics for a while, so presumably it is also relatively well tested.

Are there any blockers to stablization? Is there anything that I can do to help push this to stabilization?
