### ISSUE TITLE
rustdoc-json: replace jsondocck with jsondocckng

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#94140]
We want to use <https://github.com/aDotInTheVoid/jsondocckng> which allows writing the tests in a seperate rust files, instread of the current `jsondocck` and `check_missing_items.py`

## Reasons to do this

- Easier for new contributors: They don't need to learn how to use `JsonPath`  and `@set`... commands
- Easier for exising contributors: Common idioms (`"$.index[*][?(@.name=='...')]`) can be converted to rust code to avoid duplication. [Paths referenced repeatedly](https://github.com/rust-lang/rust/blob/b17226fcc11587fed612631be372a5b4cb89988a/src/test/rustdoc-json/type/generic_default.rs#L13-L24) can be replaced with a let
- We can avoid the problems with quoting of the shlex/serde_json frankensteined value system that leads to things like `'"\"vectorcall\""'`

## Drawbacks

- We dont test the raw json, but instead the Rust Repr
- Unclear how to integrate into rustbuild in current from
- Existing tests need to be rewritten

## Todo

- [ ] Improve features of jsondocckng
    - [ ] Allow multifile crates
    - [ ] Allow passing args to rustdoc
    - [ ] Allow multiple json outputs
    - [ ] When failure occours, diff with nightly and prity print
- [ ] Integrate with rustbuild
- [ ] Port existing tests
- [ ] Document 

@rustbot modify labels:  +A-contributor-roadblock +A-testsuite +T-rustdoc +A-rustdoc-json +A-rustbuild

**Comment by aDotInTheVoid** [comment]
2 Possible approaches for this:

### 1 Crate per test

Each test is its own crate (in addition to the crate being documented). Rustbuild documents the `<name>.rs` file, compiles `<name>_test.rs` to a binary, and then calls generated binary with a path the the json. Their is a library crate that each test depends on that provides common test utilitys, and a main method that reads the json file, and then calls the test crates test function.

More concretely

foo.rs
```rust
pub fn foo() {}
```

foo_test.rs
```rust
use jsondocck::{TCrate, main_test}

fn main() {main_test(test);}

fn test(t: TCrate) {
   let foo = t.get_root::<Function>("foo");
   assert_eq!(foo.decl.output, None);
}
```

### One crate for all tests

All tests live in the same (binary) crate. rustbuild the test document and builds the one test crate, and then calls the test crate binary with the name of the test to run and the path to json. The test crate has the all the test functions within it, and calls the appropried one based on the name of the test passed on the command line

This feels simpler to impement, but may lead to a slower feedback loop, as the whole test crate needs to be recompilled whenever the contents of a single test is changed.

**Comment by CraftSpider** [comment]
Personally, 1 sounds better. I like the idea of one crate per test, with a helper they all rely on. On the other hand I agree it may be a little more complex.

**Comment by aDotInTheVoid** [comment]
After some [zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/rustbuild.2Fcompiletest.20question.3A.20Many.20or.20One.20test.20crate) with @_Mark-Simulacrum, it looks like one-crate-per-test is infeasable, because compiletest can't build crates that have crates.io dependencys (needed for serde_json).

Additionaly this looks alot like https://github.com/rust-lang/rust/issues/40713

**Comment by aDotInTheVoid** [comment]
Started work at https://github.com/aDotInTheVoid/rust/tree/jsondocck-ng

**Comment by aDotInTheVoid** [comment]
It might be worth just rewriting [src/etc/check_missing_items.py](https://github.com/rust-lang/rust/blob/96b9bb4620f4d48aa25c381c7ea77e0cab48ac5b/src/etc/check_missing_items.py) to start with, as that should fit nicely into rustbuild, and it's out of sync whenever the format changes (and even when it doesn't due to undertesting). Eg

```rust
pub type RefFn<'a> = &'a dyn for<'b> Fn(&'a i32) -> i32;
```
fails it.

Theirs a very barebones implementation [here](https://github.com/aDotInTheVoid/jsondocckng/blob/trunk/src/validate.rs).

**Comment by aDotInTheVoid** [comment]
I don't think this is gonna happen, or is a good idea. Closing to not confuse people into thinking this is likely, in favour of #142327, a much more practical approach.

**Comment by aDotInTheVoid** [comment]
>  it looks like one-crate-per-test is infeasable, because compiletest can't build crates that have crates.io dependencys (needed for serde_json).

For posterity, I don't think this is true anymore, due to run-make tests. If we ever go down this road before, this could probably be implemented as a submodule of `run_make_support`, and reuse their infra for integrating with compiletest and 3rd party crates.
