### ISSUE TITLE
Tracking Issue for `cargo run` as the main bootstrap entry point

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#94829]
This is a tracking issue for removing the requirement on python for bootstrapping the compiler.
Note that bootstrap.py is never going to be removed altogether, since distros still need to get a bootstrap compiler from anywhere; this issue is about contributors who already have a rust toolchain installed.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement `cargo run -p bootstrap`
- [ ] Add `rust-toolchain` to the workspace root so that people don't use the wrong toolchain by accident
  - [ ] Add support in rustup for a `rustfmt` that comes from a different toolchain than the rest of the components
- [ ] Move `download-llvm` to rustbuild
- [ ] Move `download-rustc` to rustbuild
- [ ] Change `src/tools/x` to use `cargo run` instead of python
- [ ] Update documentation in the dev-guide to suggest `cargo run` instead of `./x.py`.

### Unresolved Questions

- Should submodules be managed in rustbuild instead of bootstrap.py? This would require moving rustbuild out of the workspace.
- How does this interact with the build lock in bootstrap.py? Should rustbuild depend on sqlite too, or should we come up with a file locking library?
- Should we move the "Build completed successfully" output to rustbuild? If we keep it only in bootstrap.py, the new entry point will have less info; if we move it to bootstrap the info will be incomplete even for python users because it won't include the time to build rustbuild.

### Implementation history

- [x] Implement `cargo run -p bootstrap`: https://github.com/rust-lang/rust/pull/92260
- [x] Align rustbuild's submodule behavior with x.py's: https://github.com/rust-lang/rust/pull/93722
- [x] https://github.com/rust-lang/rust/pull/94796
- [ ] https://github.com/rust-lang/rust/pull/94828
- [ ] https://github.com/rust-lang/rust/pull/94806

@rustbot label: +A-rustbuild

**Comment by cuviper** [comment]
> Note that bootstrap.py is never going to be removed altogether, since distros still need to get a bootstrap compiler from somewhere;

Distros generally need **offline** builds, so I'm not sure what role you see for bootstrap.py there. For most builds I'm just pointing to the `/usr` toolchain, or if that's broken or non-existent I'll use a manually-unpacked upstream toolchain.

**Comment by jyn514** [comment]
> Distros generally need offline builds, so I'm not sure what role you see for bootstrap.py there. For most builds I'm just pointing to the /usr toolchain, or if that's broken or non-existent I'll use a manually-unpacked upstream toolchain.

Ah, interesting. I'm a little confused why we *ever* had a python entry point then - @Mark-Simulacrum do you remember the original goal? Was it intended for individual users trying to build from source? I'm ok with regressing that a little bit as long as people can still install rustup from source and then build bootstrap ...

**Comment by bjorn3** [comment]
bootstrap.py was introduced when rewriting the build system from make to rust in https://github.com/rust-lang/rust/commit/046e6874c47ec55e23b7a566bca51d2920562485. Back then rustup (it was still called multirust at that point I believe) wasn't really common I believe.

**Comment by Mark-Simulacrum** [comment]
The python wrapper supports us in a number of ways (or did): submodule initialization (needed before first Cargo invocation due to workspace resolution), downloading and checking hashes on a specific beta/stable (sort of replaceable with rustup, but historically our needs are a little more complex such as with rustfmt being a separate toolchain), figuring out what the platform target triple is...

It also does more "mundane" things like permitting a single interface to rustbuild without cargo run -- ... prefixing every command, which to me feels at least not obviously better than x.py. (And configuring that initial Cargo invocation with our linting requirements etc)

**Comment by bjorn3** [comment]
Cargo allows adding aliases in `.cargo/config.toml`, so you can have eg `cargo rustcbuild`, `cargo rustctest`, ...

**Comment by jyn514** [comment]
> It also does more "mundane" things like permitting a single interface to rustbuild without cargo run 

We could have that unified interface with `src/tools/x`, which is also shorter than either `x.py` or `cargo run`. That seems nicer than having the interface tied to the language.

The other things are mostly done by rustup - I guess the concern is for tooling in CI, which doesn't have rustup installed?

**Comment by jyn514** [comment]
I have divided this up into some smaller tasks that can be done in parallel; see https://rust-lang.zulipchat.com/#narrow/stream/122652-new-members/topic/Help.20with.20RRIR.20bootstrap.20entrypoint for more info.

@rustbot label: +E-mentor +E-help-wanted

**Comment by jyn514** [comment]
If you're following along on this issue, I would very much appreciate your feedback on what the entrypoint should be (`cargo run` has a few issues mentioned in https://github.com/rust-lang/rust/issues/95858#issuecomment-1133812693): https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/bootstrap.20user.20survey
Please respond on Zulip and not here so we can keep using this as the tracking issue.

**Comment by jyn514** [comment]
Status update: this is getting pretty close to done. Once https://github.com/rust-lang/rust/pull/97513 merges, the only major work still done by python will be building rustbuild and holding the build lock.

I plan to work on downloading rustbuild from CI in the next month or so. I could still use help on a rust file locking library - it doesn't have to be bullet proof, just good enough that it usually catches rust-analyzer running concurrently with another build.

> * Should we move the "Build completed successfully" output to rustbuild? If we keep it only in bootstrap.py, the new entry point will have less info; if we move it to bootstrap the info will be incomplete even for python users because it won't include the time to build rustbuild.

I think we can duplicate this in all the entrypoints; it's only one or two lines.

**Comment by albertlarsan68** [comment]
The checkbox for "Change `src/tools/x` to use the new entrypoints" can be checked
