### ISSUE TITLE
Tracking issues for unstable language features used by `std`

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#94971]
`std` uses a lot of unstable library features. While `core` will most likely always have to use *language* features, we can strive for `std` to eventually be free of both unstable language and unstable library features.

Some of these we'll need to stabilize, but some others we might be able to simply remove with some small changes to the code.

(See also https://github.com/rust-lang/rust/issues/94970 for the language features.)

These are the library features we currently use in `std`:

- Not yet stable core features:
  - [ ] exact_size_is_empty
  - [ ] extend_one
  - [ ] maybe_uninit_slice
  - [ ] maybe_uninit_write_slice
  - [ ] mixed_integer_ops
  - [ ] nonnull_slice_from_raw_parts
  - [ ] portable_simd
  - [ ] ptr_as_uninit
  - [ ] raw_os_nonzero
  - [ ] slice_ptr_get
- Not yet stable alloc features:
  - [ ] alloc_layout_extra
  - [ ] allocator_api
  - [ ] new_uninit
  - [ ] toowned_clone_into
  - [ ] try_reserve_kind
  - [ ] vec_into_raw_parts
- core::panic:
  - [ ] panic_info_message
  - [ ] panic_internals
  - [ ] panic_can_unwind
- Core's internals: (Should we make some of these public/stable?)
  - [ ] char_internals
  - [ ] core_intrinsics
  - [ ] hashmap_internals
  - [ ] std_internals
  - [ ] str_internals
- The unwind crate:
  - [ ] panic_unwind
- These become unnecessary if we move `trait Error` to core:
  - [ ] array_error_internals
  - [ ] char_error_internals
  - [ ] duration_checked_float
  - [ ] int_error_internals
  - [ ] map_try_insert

**Comment by compiler-errors** [comment]
Should this be titled "Tracking issues for unstable library features used by `std`"?
