### ISSUE TITLE
Tracking Issue for more complex const parameter types: `feature(adt_const_params)`

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#95174]
This is a tracking issue for allowing more const parameter types.
The feature gate for this issue is `#![feature(adt_const_params)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

Most of the work here will be coordinated in the `#project-const-generics` stream on [zulip](https://rust-lang.zulipchat.com/#narrow/stream/260443-project-const-generics).

- [x] Implement `valtrees`
- [x] deal with structural equality
- [x] Figure out which types should be allowed as const parameter types and how
- [ ] Investigate ICEs around not-wf const arguments (e.g. #131052 #129095 #128232)
- [ ] Ensure no forwards compatibility issues with `min_generic_const_args`
- [ ] Finalize symbol mangling decision for values of arbitrary types (#61486 rust-lang/rfcs#3161)
- [ ] Document feature
- [ ] Stabilization report with lang FCP explaining all the differences between rfc and current impl

### Unresolved Questions

- Is the v0 mangling setup for `adt_const_params` forwards compatible with `unsized_const_params` (#128028)

cc @rust-lang/project-const-generics

**Comment by griffi-gh** [comment]
I think at least simple enums without assigned values should be allowed for now

**Comment by tarcieri** [comment]
@griffi-gh I agree. However, in the meantime if you have an e.g. `repr(u64)` C-style enum, you can cast it with `as u64` (or whatever integer type) to sort of fake being const generic around an enum, and that works fine even in const contexts, while also hopefully being trivially upgradable to `adt_const_params` in the future.

**Comment by jhpratt** [comment]
For what it's worth, I am currently hacking around this in `time` by encoding a struct into a u128, passing as a const generic, and decoding it back to the original struct. All at compile time, as the values are then associated constants. This approach is tedious, but it works for everything up to 16 bytes in size.

**Comment by mqudsi** [comment]
I use this with `&'static str` const generics to optimize a parser via compile-time generic constants passing in `&'static str` values to mark values that should be consumed in a user-friendly way.

**Comment by eminence** [comment]
Once place where `adt_const_params` really shines is in diagnostics.  Consider the following stable code, which casts a `repr(u8)` enum, to be used in a const generic:

```rust
#[repr(u8)]
pub enum Facing {
    Up,
    Down,
}

pub struct Card<const FACING: u8> {
    // would normally have a "suit" and "number" field
}

pub fn foo(card: Card<{Facing::Up as u8}>) {
    let _: Card<{Facing::Down as u8}> = card;
}
```

```
   |
12 |     let _: Card<{Facing::Down as u8}> = card;
   |            --------------------------   ^^^^ expected `1`, found `0`
   |            |
   |            expected due to this
   |
   = note: expected struct `Card<1>`
              found struct `Card<0>`
```

But with a real enum and `adt_const_params`, the error message is much clearer:

```
   |
14 |     let _: Card<{Facing::Down}> = card;
   |            --------------------   ^^^^ expected `Facing::Down`, found `Facing::Up`
   |            |
   |            expected due to this
   |
   = note: expected struct `Card<Facing::Down>`
              found struct `Card<Facing::Up>`
```

**Comment by safinaskar** [comment]
> to optimize a parser via compile-time generic constants

@mqudsi , cool! Please, show the code (if it public)

**Comment by smmoosavi** [comment]
>> to optimize a parser via compile-time generic constants
>
> @mqudsi , cool! Please, show the code (if it is public)

## goal

define reusable structs to match deep structs (e.g. syn)

```rust
pub trait MatchNestedMeta: Sized {
    fn match_nested_meta(meta: &syn::NestedMeta) -> Option<darling::Result<Self>>;
}

pub trait MatchString: Sized {
    fn match_string(str: &str) -> Option<darling::Result<Self>>;
}

impl MatchString for String {
    fn match_string(string: &str) -> Option<darling::Result<Self>> {
        Some(Ok(string.to_string()))
    }
}

pub struct MatchLitStr<S: MatchString = String>(pub S, pub proc_macro2::Span);

impl<S: MatchString> MatchNestedMeta for MatchLitStr<S> {
    fn match_nested_meta(meta: &syn::NestedMeta) -> Option<darling::Result<Self>> {
        match meta {
            syn::NestedMeta::Lit(syn::Lit::Str(string)) => {
                S::match_string(string.value().as_str()).map(|s| Ok(MatchLitStr(s?, string.span())))
            }
            _ => None,
        }
    }
}

```
Now we want to define a struct that can accept only some strings, before this proposal we have to define a new struct for each string. (you can imagine more structs. e.g. `MatchStartsWithFoo(String)`, `MatchEndsWithFoo(String)`

```rust
struct MatchFooString;

impl MatchString for MatchFooString {
    fn match_string(string: &str) -> Option<darling::Result<Self>> {
        if string == "foo" {
            Some(Ok(MatchFooString))
        } else {
            None
        }
    }
}

```

after this proposal, we can define more generic structs. you can imagine more structs like `MatchStringStartsWith<"foo">(String)` or `MatchStringStartsWith<"bar">(String)`

```rust

struct ExactMatchString<const S: &'a str>;

impl<const S: &'a str> MatchString for ExactMatchString<S> {
    fn match_string(string: &str) -> Option<darling::Result<Self>> {
        if string == S {
            Some(Ok(ExactMatchString))
        } else {
            None
        }
    }
}
```

## Usage
```rust

type MatchFooLitStr = MatchLitStr<ExactMatchString<"foo">>;

fn read_foo(meta: &syn::NestedMeta) {
    if let Some(Ok(MatchFooLitStr(_))) = MatchFooLitStr::match_nested_meta(meta) {
        // ...
    }
}

```

Please see this [directory] for more codes.

[directory]: https://github.com/smmoosavi/dynamic-graphql/tree/main/derive/src/utils/meta_match

**Comment by eugene2k** [comment]
My particular use case uses an array of static strings to access shader variables by name in opengl code and make sure their values are set according to the meta information in the struct. 
So, for example code like this: `shader.uniform::<"my_var">(0.0f32)` would result in an error if `my_var` isn't defined as a float or doesn't exist in the set of allowed variables, but otherwise it will set the corresponding uniform to 0.0f32 without calling glGetUniformLocation everytime (all locations are retrieved at initialization).

For anyone interested, the current code looks like this: https://gist.github.com/00237dfe4f3832fdfe1f1137908d7741

Although it would be even better if rust didn't have a problem looking up the length of zero-sized array slices at comptime:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=00237dfe4f3832fdfe1f1137908d7741 - this produces an error

**Comment by Pzixel** [comment]
Hi I found this today:

```rust
#![feature(adt_const_params)]

#[derive(Debug, PartialEq, Eq)]
struct Foo(u32);

const fn bar() {
    const ONE: Foo = Foo(1);
    match Foo(0) {
        ONE => unreachable!(),
        _ => {},
    }
}

const fn baz<const ONE: Foo>() {
    match Foo(0) {
        ONE => unreachable!(),
        _ => {},
    }
}
```

I think that `bar` and `baz` functions should have the same meaning but they currently don't

**Comment by fbstj** [comment]
@Pzixel the `ONE` in `baz` could be called with `baz<Foo(0)>()` or any other `Foo`, making the ONE branch not unreachable;

**Comment by Pzixel** [comment]
That should lead to a regular panic in compile time then, it's not different from

```rust

const fn bar() {
    const ONE: Foo = Foo(0);
    match Foo(0) {
        ONE => unreachable!(),
        _ => {},
    }
}
```

Right? I would expect them both to fail with "the evaluated program panicked at 'internal error: entered unreachable code'," in both cases.

FWIW I would expect `<const ONE: Foo>` to always behave absolutely the same as `const ONE: Foo = ...` in all contexts.

**Comment by sethp** [comment]
I'm playing with another possible `&'static str` parser-adjacent use case: riscv compilation targets. There's a shared mini-language that comes after a prefix (i.e. `32ima` -> 32-bit integers, with multiplication/division, and atomics), but gcc & friends know that ISA as `rv32ima` and cargo (presumably by way of llvm) knows it as `riscv32ima`. It also feels like somewhat of an open set: other tools might pick yet other prefixes.

It seems like it would be convenient to model this as something like:

```rust
pub struct Isa<const PREFIX: &'static str> {}

pub type Cargo = Isa<{ "riscv " }>;
pub type Gcc = Isa<{ "rv" }>;
```

which in turn would allow the common case to look something like

```rust
let target: Cargo = "riscv32ima".parse()?;
```

without preventing someone outside of the declaring crate from using `type Rvas = Riscv::Isa<{ "" }>` to interact with a hypothetical `rvas` that doesn't bother with a prefix at all.

**Comment by oli-obk** [comment]
I am locking the discussion. If you find issues with the feature, please open individual issues referencing this one. If you want to discuss the feature, consider opening a thread in zulip.

**Comment by clarfonthey** [comment]
It seems that the main blocker to stabilising this is:

> Author an RFC explaining the current state of the feature since it has significantly diverged from original RFC

Although I'm not exactly sure what exactly these differences are, and whether it's needed based after rust-lang/rfcs#3535 has clarified the details on constant patterns. Would someone be willing to update the description to clarify the details on this, and which RFC it's referring to for the original details?

(I know that there are other open issues for this feature, although it feels like the semantic clarification is the most difficult to resolve.)
