### ISSUE TITLE
Tracking Issue for `sub_ptr` (feature `ptr_sub_ptr`)

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#95892]
Feature gate: `#![feature(ptr_sub_ptr)]` & `#![feature(const_ptr_sub_ptr)]` 

This is a tracking issue for the `<*const _>::sub_ptr` & `<*mut _>::sub_ptr` methods.

This is the produces-`usize` version of `offset_from`, the same way that `add` and `sub` are the takes-`usize` versions of `offset`.

It turns out that people almost always actually know which pointer is greater than which when doing this operation, and would rather a `usize` instead of an `isize`  -- every use of `offset_from` in the library was followed with `as usize` in practice.  So like how `.add(d)` greatly improved code compared to needing `.offset(d as isize)`, being able to use `ptr.sub_ptr(origin)` instead of `ptr.offset_from(origin) as usize` is also a major improvement.  And Miri can check the unsafety better, too, since if you get the order wrong it'll [detect that](https://github.com/rust-lang/rust/pull/95837/files#diff-10506a8d62761f810db4f83a4b6b90f29c7a35c97ebd922bfd1183f418fa70f9R83-R88), unlike happens with the `as usize` approach.

This also tracks the `const`ness of operations, though with #92980 stabilizing `offset_from` being `const` , this being `const` is likely uncontroversial.

### Public API

```rust
impl<T> *const T {
    pub const unsafe fn sub_ptr(self, origin: *const T) -> usize;
    pub const unsafe fn byte_sub_ptr<U>(self, origin: *const U) -> usize;
}

impl<T> *mut T {
    pub const unsafe fn sub_ptr(self, origin: *const T) -> usize;
    pub const unsafe fn byte_sub_ptr<U>(self, origin: *const U) -> usize;
}

impl <T> NonNull<T> {
    pub const unsafe fn sub_ptr(self, subtracted: NonNull<T>) -> usize;
    pub const unsafe fn byte_sub_ptr<U>(self, origin: NonNull<U>) -> usize;
}
```

### Steps / History

- [x] Implementation: #95837
- [x] Move the `NonNull` method to this gate https://github.com/rust-lang/rust/pull/124498
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- [ ] This uses the terminology of subtraction to match the existing `add` and `sub` methods, but there might be another name that would be more evocative for people https://github.com/rust-lang/rust/pull/95837#issuecomment-1094134054

**Comment by Stargateur** [comment]
I also wonder if we could just say this doesn't panic but just return the absolute since we assert the greater than equal why not just make it return absolute ? this would cost anything else and would remove the burning for dev to think about order, and we could just call this `distance()`.

**Comment by scottmcm** [comment]
I would be strongly against this returning the absolute difference between the pointers.  Part of the value of this API is that it's more efficient than `offset_from` -- that's why slice iterators were open-coding this before the function existed -- and if it needed to do tests for ordering it would no longer be that.

Adding a *separate* absolute difference API for pointers might make sense, [like the integers have](https://doc.rust-lang.org/std/primitive.i32.html#method.abs_diff), but it wouldn't be a [serviceable](https://rust.godbolt.org/z/a3n8E99rW) replacement for the current `sub_ptr`.  (#106393 wouldn't use an absolute difference version, for example.)

**Comment by Stargateur** [comment]
I proposed this cause you write in the PR:

>         // SAFETY: The comparison has no side-effects, and the intrinsic
>        // does this check internally in the CTFE implementation.

so I expect it to be "free", I all in favor of remove all assert since the method is unsafe anyway, this kind of operation should be as fast as possible. I just see this line and wonder, well if it's free why not ?

> (Oh, and as prior art, [std::distance in C++](https://en.cppreference.com/w/cpp/iterator/distance) isn't an absolute distance either, so calling it distance might mislead people.)

I don't think C++ std using distance name wrongly is a good point, have you ever see "this object is `-1cm`" ? a distance is always possible, that why we return usize. Distance is also mention many time in https://github.com/rust-lang/rust/pull/95837#issuecomment-1094134054.

**Comment by scottmcm** [comment]
> cause you write in the PR:

`assert_unsafe_precondition!` is a magic compiler thing that only does something in CTFE.  At codegen time, `sub_ptr` doesn't do any checks, just an "I promise not to overflow" subtraction and a "I promise it's an exact multiple" division: <https://rust.godbolt.org/z/fE79dv6WT>.

**Comment by deltragon** [comment]
Since `offset_from` has a parallel `byte_offset_from` method (tracked in https://github.com/rust-lang/rust/issues/96283), should this method have an equivalent `byte_sub_ptr` method?
I am aware that this was added specifically for slice iterators, and there it doesn't seem like there has been a usecase for a bytewise method so far - but looking at the docs it seemed somewhat surprising that this is missing.

**Comment by RalfJung** [comment]
Yeah, if this stabilizes after the other `byte` methods we probably want `byte_sub_ptr` as well.

**Comment by LoganDark** [comment]
I've read some of the bikeshedding in #95837, and I'd like to second @Gankra's suggestion of "offset_to" - it's not perfect, but when I was looking for this method, I couldn't find it in the autocomplete and had to search for the `-> usize` return type instead. Having `offset` in the name would have made it easier to locate, as that's one of the first things I looked for.

Are there any blockers for stabilization besides the name? I'm not familiar with the stabilization process, but I'd be willing to open a stabilization PR for this if that would help.

**Comment by RalfJung** [comment]
So `offset_from` returns `isize` but `offset_to` returns `usize`? That makes little sense to me.

Once this is stable we can put a note in the `offset_from` docs pointing to `sub_ptr`.

**Comment by LoganDark** [comment]
> So `offset_from` returns `isize` but `offset_to` returns `usize`? That makes little sense to me.

In isolation, it doesn't make much sense to me either - given the chance to go back in time, I would have made `offset_from` return `usize` instead, as the earlier discussion mentioned, but it's too late for that now.

Another possibility may be `count_from` - it still retains a word from `offset_from`, so it shouldn't take more than a couple tries to discover through autocomplete, but it still communicates its unsignedness - an element count will/should always be unsigned, as opposed to an offset which can go in either direction.

**Comment by RalfJung** [comment]
@rust-lang/libs-api what are your current thoughts on this function? Is this generally something we'd want to have, in terms of its semantics? Any opinions on the name?

`sub_ptr` seems like an okay name to me. None of the proposed alternatives (`offset_to`, `count_from`) obviously beat it.

This doesn't currently have a "byte" variant but I assume we'll want that, too.

**Comment by Amanieu** [comment]
I'm somewhat partial to `offset_from_unsigned` which clearly indicates that this produces a `usize` and that the offset must be positive. Although this is actually longer than `offset_from() as usize`, it does involve additional safety conditions and may be easier for people to type with IDE auto-completion.

**Comment by Amanieu** [comment]
I do agree it's not great compared to `offset_from`, but the question here is whether `offset_from_unsigned` is better than sticking with the currently proposed `sub_ptr`.

**Comment by joshtriplett** [comment]
Another proposal: `p1.offset_after(p2)`. That would make it clear that `p1` must be *after* `p2`, and since it must be after, the use of unsigned naturally follows from that.

**Comment by RalfJung** [comment]
FWIW I quite like `offset_after`.

**Comment by m-ou-se** [comment]
Some other suggestions that came up in that meeting were: `positive_offset_from`, `offset_within` ("within" an allocation), and `offset_to`, but there was no consensus for any of these.

For `offset_to` the arguments would be reversed: `first_ptr.offset_to(second_ptr)` rather than `second_ptr.sub_ptr(first_ptr)`. (Which I personally like, because then you write the two pointers in the same order they appear in memory.)

I noted in the meeting that if I was new to a language that had both "offset_from" and "sub[_ptr]", I would expect `offset_from` to be unsigned, and `sub` to be signed, which is the opposite of what we have now. (But unfortunately, offset_from is already stable.)

**Comment by m-ou-se** [comment]
I dislike `offset_after`, because then we'll end up having both `offset_from` and `offset_after`, which kind of sound like opposites, even though they aren't. I can already see them getting mixing them up all the time.

I personally like `offset_to` or `distance_to` best, because it separates it a bit from `offset_from` and puts the two arguments in a (to me) more natural order, since this new method is all about (unsafely) assuming the order of the pointers.

(Similar to how we do `collection.find(element)` instead of `element.find_in(collection)`, I feel like it should be `slice_ptr.offset_to(element_ptr)` rather than `element_ptr.offset_from(slice_ptr)` when finding the index.)

**Comment by RalfJung** [comment]
It seems quite confusing that `offset_to` would be unsigned if `offset_from` is signed.

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting. Team members were of differing opinions, but in the end we reached a consensus on `offset_from_unsigned`. It is slightly better than the status quo of casting to `usize` because of IDE auto-completion, and the name clearly indicates that the result is unsigned and must be positive.

@rfcbot merge

**Comment by RalfJung** [comment]
Stabilizing this in const will also require @rust-lang/lang  approval since a new intrinsic is involved: `ptr_offset_from_unsigned`. It is implemented together with the already-stable `ptr_offset_from` so this should be easy. Can we just do this in one go?

**Comment by RalfJung** [comment]
@scottmcm so could you restart FCP for both teams? (and recheck the existing boxes)

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by traviscross** [comment]
@rfcbot reviewed

**Comment by tmandry** [comment]
@rfcbot reviewed

**Comment by joshtriplett** [comment]
I really don't like how long this name is. I do want to see this stabilized so people can use it. Perhaps we can get an alias at some point. But in the meantime, I'm not going to object to this.

**Comment by tgross35** [comment]
@pnkfelix recently changed to alumni status, should that box be checked?

Otherwise with Josh abstaining this comes down to @BurntSushi :)

**Comment by BurntSushi** [comment]
I also find the name pretty meh, but I don't have any better ideas. And I'd rather see this stable than not. And I like that it reduces `as` usage.

**Comment by hanna-kruppe** [comment]
The [FCP was for the name `offset_from_unsigned`](https://github.com/rust-lang/rust/issues/95892#issuecomment-2501374947) but the stabilization PR #137121 didn't do the renaming. Did I miss anything or should the renaming still be done?

**Comment by Noratrieb** [comment]
You did not miss anything, but @bend-n and I did, because the issue description still listed the old names. Quick rename PRs welcome.

**Comment by bend-n** [comment]
quick question, what happened to `byte_sub_ptr`? is that `byte_offset_from_unsigned`?

**Comment by Amanieu** [comment]
> quick question, what happened to `byte_sub_ptr`? is that `byte_offset_from_unsigned`?
> 

Yes, they all have the same name with the `byte_` prefix added.
