### ISSUE TITLE
Tracking issue for the implementation of RFC 2011: Generic assert

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust#96949]
Edit(fmease): The overarching tracking issue: #44838 (feature `generic_assert`).

Just a better-than-a-TODO internal issue to track the remaining things of https://github.com/rust-lang/rust/pull/96496.

* [ ] Constant environments.
* [ ] Cap size to avoid large copies (https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=85575be37ce9ebaa2286ba1a7ed4930a).
* [ ] ~~Capture `matches!` arguments.~~ (Postponed, see #110382)
* [x] Prevent copies when methods don't require ownership. For example, `PartialEq`.
* [ ] ~~Capture block statements~~
* [ ] ~~Pretty printing synchronization~~

@rustbot claim
