### ISSUE TITLE
Tracking issue for enabling `-Zdrop-tracking` by default

### ISSUE THREAD

**Issue by eholk** [rust-lang/rust#97331]
We tried to do this a while ago (#91032) but discovered a number of regressions soon afterwards so it was disabled (#93165). This issue tracks known regressions and their fixes. Note that many regressions have been fixed but are not listed here since they were done before I filed this bug.

- [x] https://github.com/rust-lang/rust/issues/97332
- [x] https://github.com/rust-lang/rust/issues/97333
- [x] https://github.com/rust-lang/rust/issues/98476
- [x] https://github.com/rust-lang/rust/issues/98477
- [x] https://github.com/rust-lang/rust/pull/101217
- [x] https://github.com/rust-lang/rust/issues/102383
- [ ] https://github.com/rust-lang/rust/pull/97334

**Comment by jyn514** [comment]
The last two issues have both been fixed :) and the first has been mitigated (it doesn't have the same error as it used to, but the new error is much more readable).
Let me know if there's any way I can help with the must_not_suspend lint.

**Comment by davidbarsky** [comment]
> For must_not_suspend, if we're lucky this may just need someone to try it out, since it seems like https://github.com/rust-lang/rust/pull/98754 might have fixed that as well.

Would it be helpful if `tracing` added `#[must_not_suspend]` behind an `RUSTFLAGS`? I can then try enabling it at work's monorepo and see what breaks.

**Comment by jyn514** [comment]
I think all of these have been fixed :) @eholk what are the next steps? Another Crater run?

**Comment by eholk** [comment]
@jyn514 - Yup! Let me rebase #97334 and then we should be able to run just the failed ones from last time.

**Comment by eholk** [comment]
Bummer, looks like there's another test that broke in the meantime: https://github.com/rust-lang/rust/pull/97334#issuecomment-1219902302

**Comment by StyMaar** [comment]
Shouldn't this issue be closed now that everything in it is done?

**Comment by eholk** [comment]
Yes!

**Comment by vladfaust** [comment]
I realize it may not be that useful, but I've stumbled upon https://users.rust-lang.org/t/future-is-not-send-as-this-value-is-used-across-an-await/92580/3, and in my case the `future is not 'Send' as this value is used across an await` problem is indeed fixed by wrapping the offending code in a block instead of explicitly `drop`-ping a `tokio::sync::Mutex` lock.

It seems like `drop` is still "ignored" by the compiler. Unfortunately I can not share my code, as it's kinda complex, but I can say that I have `rustc 1.86.0-nightly (4a4309466 2025-02-02)` on MacOS 15. The issue may therefore be still relevant.
