### ISSUE TITLE
Tracking Issue for `extern "rust-cold"` ABI (feature `rust_cold_cc`)

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#97544]
This is a tracking issue for the experimental `extern "rust-cold"` ABI.
The feature gate for the issue is `#![feature(rust_cold_cc)]`.

This allows emitting functions with [`coldcc` in LLVM](https://llvm.org/docs/LangRef.html#calling-conventions) and [`CallConv::Cold` in cranelift](https://docs.rs/cranelift-codegen/latest/cranelift_codegen/isa/enum.CallConv.html#variant.Cold).  These are more aggressive than the stable `#[cold]`, as they can use a different calling convention (and thus have incompatible `fn`s), not just affect branch weights -- for example, they might require more/slower code in the callee in exchange for smaller call sites.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC (cc @rust-lang/XXX -- can anyone write up mentoring
      instructions?)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

XXX --- list all the "unresolved questions" found in the RFC to ensure they are
not forgotten

### Implementation history

- [ ] #97512

**Comment by reinerp** [comment]
I'm very excited about this, thank you for your work on this!

Couple comments:
* this seems to be broken for 16-byte returns on x86-64. Example: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e484bf958a2e5b421de9e5a52f736723. Looking at the code for `foo` in this example, it seems to be trying to return the result in `rax` and `rdx`, but then it calls `pop rdx` which clobbers the return value.
* `coldcc` is suitable for "never runs" things like panics. For "runs rarely (amortized)" things, LLVM's `preserve_mostcc` seems like it is often a better fit. (A primary difference is that `coldcc` saves all XMM registers, whereas `preserve_mostcc` does not.) It has the added advantage of being exposed to C++ in Clang, and seems to be used in some popular codebases (V8, Folly), so it might be better exercised/tested than the `coldcc` convention. Would it be possible to have a "rust-cool" variant too, which uses `preserve_mostcc`?
