### ISSUE TITLE
Tracking Issue for `feature(file_set_times)`: `FileTimes` and `File::set_times`

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#98245]
Feature gate: `#![feature(file_set_times)]`

This is a tracking issue for setting file accesses/modification timestamps via the `File::set_times` function and associated `FileTimes` structure.

### Public API

```rust
// std::fs

#[derive(Copy, Clone, Debug, Default)]
pub struct FileTimes { /* ... */ };

impl FileTimes {
    pub fn new() -> Self;
    pub fn set_accessed(self, t: SystemTime) -> Self;
    pub fn set_modified(self, t: SystemTime) -> Self;
}

impl File {
    pub fn set_times(&self, times: FileTimes) -> std::io::Result<()>;
    pub fn set_modified(&self, t: SystemTime) -> std::io::Result<()>;
}
```

```rust
// std::os::ios::fs
// std::os::macos::fs
// std::os::watchos::fs
// std::os::windows::fs

pub trait FileTimesExt: Sealed {
    fn set_created(self, t: SystemTime) -> Self;
}

impl FileTimesExt for std::fs::FileTimes;
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/98246
- [x] https://github.com/rust-lang/rust/pull/109773
- [x] Final comment period (FCP)
- [x] Stabilization PR

**Comment by m-ou-se** [comment]
I wonder if it would be good to have a `file.set_last_modified(time)` short-hand for `file.set_times(FileTimes::new().set_modified(time))`. `FileTimes` nicely allows platforms to have a `FileTimesExt` trait to add more times, but it's a bit verbose for simple use cases.

**Comment by joshtriplett** [comment]
@m-ou-se No fundamental objection, though I don't think we should provide an alias for `accessed` (less common to set in isolation, and if we had both people might be tempted to call both rather than making one call to `set_times`).

Also, I'd probably call it `set_modified` for symmetry with the various uses of `modified`.

**Comment by joshtriplett** [comment]
@m-ou-se Done.

**Comment by sunfishcode** [comment]
On Unix-family platforms, there's a mechanism for setting a timestamp to the current time (`UTIME_NOW`), which doesn't appear to be covered in this API. One can get the same effect by using a timestamp of `SystemTime::now()`; is that fast enough? I expect it is on Linux with the vDSO, but I don't know about other platforms.

**Comment by sargun** [comment]
One thing I noticed is that there's no way to set the AT_SYMLINK_NOFOLLOW flag for this call. We might want to expose that.

**Comment by silence-coding** [comment]
Is there a planned stabilization time for this feature?

**Comment by Zerowalker** [comment]
is it possible to at `created` times here as well?
I know it exists in Windows, not sure about Unix but i would expect it's a thing there as well.

**Comment by rbtcollins** [comment]
`statx` is needed for birth time support, and its getting more and more support, but it still pretty new as these things go. https://www.phoronix.com/news/FAT-File-Creation-Birth-5.19 for instance adding support for FAT32 support.

@sargun This seems to be operating on the FD - does NOFOLLOW make any sense when not operating with paths?

**Comment by joshtriplett** [comment]
@sunfishcode Might make sense to have an extension for passing `UTIME_NOW` on platforms that support it.

**Comment by joshtriplett** [comment]
This has been around for quite a while now, and seems to work as advertised. Shall we stabilize it?

@rfcbot merge

**Comment by ChrisDenton** [comment]
FCP is completed! Anyone feel like making a [stabilization PR](https://std-dev-guide.rust-lang.org/development/stabilization.html#stabilization-pr-for-library-features)?

**Comment by chenyukang** [comment]
Closing this issue since stabilization PR is finished,
