### ISSUE TITLE
Tracking issue for `--extern priv`

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#98399]
This is a tracking issue for the `priv` CLI option for `--extern`.

* Docs: https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/extern-options.html
* RFC: https://rust-lang.github.io/rfcs/1977-public-private-dependencies.html

This option marks the given crate as "private" which is used by the [`exported_private_dependencies`](https://doc.rust-lang.org/nightly/rustc/lints/listing/warn-by-default.html#exported-private-dependencies) lint.

The syntax is `[opts ':'] name ['=' path]` where `opts` is a comma separated list of options:

```
--extern priv:foo=/path/to/libfoo.rlib
```

See also #xxx and #xxx which share this syntax extension.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [X] Implementation: #67074
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

* [ ] The syntax for adding options to `--extern` flags was added without much bikeshedding or discussion. It may need adjusting to be more flexible for more complex options.

### Implementation history

- #67074

**Comment by petrochenkov** [comment]
Stabilization blocked on ["Tracking Issue `--extern` crate modifiers"](https://github.com/rust-lang/rust/issues/98405).
