### ISSUE TITLE
Tracking Issue for `io_error_downcast`

### ISSUE THREAD

**Issue by NobodyXu** [rust-lang/rust#99262]
Feature gate: `#![feature(io_error_downcast)]`

This is a tracking issue for new API `std::io::Error::downcast`.

Existing APIs requires two separate calls to obtain the raw os error or the inner error and they both return `Option`.

Thus, users would have to first call `Error::get_ref` to check that we indeed has an inner error and checked that it [`is`](https://doc.rust-lang.org/std/error/trait.Error.html#method.is-2) the type we expected.

Users cannot use `std::io::Error::into_inner` becuase takes the error by value and returns `Option<Box<dyn Error + Send + Sync>>` instead of `Result<Box<dyn Error + Send + Sync>, Self>`.

They also cannot workaround this issue by calling `Error::raw_os_error`, since the `io::Error` can also be constructed using [`impl From<ErrorKind> for Error`](https://doc.rust-lang.org/std/io/struct.Error.html#impl-From%3CErrorKind%3E) or using other internal methods only accessible by the std library.

This new feature `io_error_downcast` solved this issue by providing new API `std::io::Error::downcast` to downcast the inner error easily without `unwrap` or `expect`.

### Public API

```rust
// std::io::Error

impl Error {
    fn downcast<E: std::error::Error + Send + Sync + 'static>(self) -> Result<E, Self>;
}
```

### Steps / History

- [x] API Change Proposal: https://github.com/rust-lang/libs-team/issues/57
- [x] Implementation: #98387 
- [x] Update `std::io::Error::downcast` return type and doc: #120117
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR #124076

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by NobodyXu** [comment]
@rust-lang/libs-api I'd like to push for stabilisation of this feature.

The only thing I'm not sure about is the return value`Result<Box<E>, Self>`
Returning a `Box` here might expose too much of an internal detail, in case the internals of `io::Error` change in future to use something like a thin box.

**Comment by NobodyXu** [comment]
Emmm it seems I can't at libs-api team...

**Comment by NobodyXu** [comment]
@yaahc I'd want to stablise the feature and I'd like your feedback.

**Comment by NobodyXu** [comment]
@yaahc Pinging

**Comment by NobodyXu** [comment]
# Stablisation Report

## Implementation History
 - `std::io::Error::downcast` implemented in #98387

## API Summary

A summary of the API is included [in the description of this issue](https://github.com/rust-lang/rust/issues/99262#issue-1305526238).

## Experience Report

n/a

**Comment by NobodyXu** [comment]
@yaahc seems to be on away from github
@joshtriplett Can we have a fcp poll for this?

**Comment by NobodyXu** [comment]
r? libs-api

**Comment by NobodyXu** [comment]
Hmmm, sorry for the @ mentions, I didn't know how to proper request for stablisation.

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

https://doc.rust-lang.org/nightly/std/io/struct.Error.html#method.downcast

```rust
impl std::io::Error {
    pub fn downcast<E>(self) -> Result<Box<E>, Self>
    where
        E: Error + Send + Sync + 'static
}
```

Signature resembles these existing stable ones:

```rust
impl Box<dyn Any> {
    pub fn downcast<T>(self) -> Result<Box<T>, Self>
    where
        T: Any
}

impl dyn Error {
    pub fn downcast<T>(self: Box<Self>) -> Result<Box<T>, Box<Self>>
    where
        T: Error + 'static
}
```

**Comment by BurntSushi** [comment]
@rfcbot concern box

@NobodyXu mentioned a question above about returning a `Box<E>` here potentially limiting our choices down the line. Is this true? It looks like there are other APIs on `io::Error` that return a `Box`, so I wonder if that ship has already sailed.

Also, AIUI, an `std::error::Error` can be `?Sized`, but the API being proposed here asks for a sized `E`. Am I understanding that correctly? If so, and if the implicit `Sized` constraint is intentional, then presumably we don't need to return a `Box<E>` at all and could just return an `E`. But I imagine we probably want to support `E: ?Sized`?

**Comment by Amanieu** [comment]
@NobodyXu We discussed this in the libs-api meeting. We think that we can move forward with the FCP once the changes proposed by @BurntSushi are addressed:
- `downcast` should return plain `Result<E, Self>` instead of boxing the error. While it's true that the error is boxed internally, this may not always be true in the future, and if you're downcasting to a specific type then you usually don't need the box.
- Regarding the docs, I think your response addresses the concerns, so this should be resolved.

**Comment by NobodyXu** [comment]
# Stablisation Report

## Implementation History
 - `std::io::Error::downcast` implemented in #98387
 - Update `std::io::Error::downcast` return type and doc according to concern from @BurntSushi in #120117

## API Summary

https://doc.rust-lang.org/nightly/std/io/struct.Error.html#method.downcast

```rust
impl std::io::Error {
    pub fn downcast<E>(self) -> Result<E, Self>
    where
        E: Error + Send + Sync + 'static,
}
```

signature resembles existing stable ones:

```rust
impl Box<dyn Any> {
    pub fn downcast<T>(self) -> Result<Box<T>, Self>
    where
        T: Any
}

impl dyn Error {
    pub fn downcast<T>(self: Box<Self>) -> Result<Box<T>, Box<Self>>
    where
        T: Error + 'static
}
```

## Experience Report

n/a

**Comment by Amanieu** [comment]
@BurntSushi I believe your concerns have now been addressed

**Comment by BurntSushi** [comment]
Now that #123851 is merged, @rfcbot resolve docs.

**Comment by BurntSushi** [comment]
@rfcbot resolve docs
