### ISSUE TITLE
Tracking Issue for Transmutability Trait: `#[transmutability]`

### ISSUE THREAD

**Issue by jswrenn** [rust-lang/rust#99571]
Feature gate: `#![feature(transmutability)]`

This is a tracking issue for [MCP411: *Lang Item for Transmutability*](https://github.com/rust-lang/compiler-team/issues/411). The MCP defines an experimental, compiler-implemented trait that can be used to audit whether a particular transmutation (or other form of bit-reinterpretation cast) is safe. 

At this time, this feature is **NOT** on track to stabilization. It has been specified in an MCP, not an RFC, and will likely require an RFC to be tracked for stabilization.

### Public API
The public API of this feature, as defined by MCP411, is roughly as follows:
```rust
#[lang = "transmute_trait"]
pub unsafe trait BikeshedIntrinsicFrom<Src, Context, const ASSUME: Assume>
where
    Src: ?Sized
{}

#[lang = "transmutability_opts"]
#[derive(PartialEq, Eq, Clone, Copy)]
#[non_exhaustive]
pub struct Assume {
    pub alignment   : bool,
    pub lifetimes   : bool,
    pub validity    : bool,
    pub visibility  : bool,
}

impl Assume {
    pub const NOTHING: Self = Self {
        alignment   : false,
        lifetimes   : false,
        validity    : false,
        visibility  : false,
    };

    pub const ALIGNMENT:  Self = Self {alignment:  true, ..Self::NOTHING};
    pub const LIFETIMES:  Self = Self {lifetimes:  true, ..Self::NOTHING};
    pub const VALIDITY:   Self = Self {validity:   true, ..Self::NOTHING};
    pub const VISIBILITY: Self = Self {visibility: true, ..Self::NOTHING};
}

impl const core::ops::Add for Assume {
    type Output = Self;

    fn add(self, rhs: Self) -> Self {
        Self {
            alignment   : self.alignment  || rhs.alignment,
            lifetimes   : self.lifetimes  || rhs.lifetimes,
            validity    : self.validity   || rhs.validity,
            visibility  : self.visibility || rhs.visibility,
        }
    }
}

impl const core::ops::Sub for Assume {
    type Output = Self;

    fn sub(self, rhs: Self) -> Self {
        Self {
            alignment   : self.alignment  && !rhs.alignment,
            lifetimes   : self.lifetimes  && !rhs.lifetimes,
            validity    : self.validity   && !rhs.validity,
            visibility  : self.visibility && !rhs.visibility,
        }
    }
}
```

### Steps / History

- [x] MCP: https://github.com/rust-lang/compiler-team/issues/411
- [ ] Implementation:
  - [ ] https://github.com/rust-lang/rust/pull/92268
- [ ] RFC: #...
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions
Virtually all aspects of this experimental feature are unresolved. 

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html
