### ISSUE TITLE
Tracking Issue for `impl Trait` as output type of `Fn` traits in function return position

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#99697]
This is a tracking issue for `impl Trait` as output type in `Fn` traits in return position of functions, for example `fn f() -> impl Fn() -> impl Sized { ... }`.
The feature gate for the issue is `#![feature(impl_trait_in_fn_trait_return)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the feature (https://github.com/rust-lang/rust/pull/93582)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

Questions to be answered in stabilization report (after gaining experience).

### Should we allow `impl Fn() -> impl Trait` in argument position of functions?

```rust
fn f(into_iter_fn: impl Fn() -> impl Iterator) {}
```

...and what does that desugar to? [See discussion here](https://github.com/rust-lang/rust/pull/93082#issuecomment-1021511579).

### Behavior of `'_`

What is the behavior of `'_` in impl trait in general and in this specific case? In this particular case, `'_` should be consistent with its use in other function signatures.

### Parsing rules

Let's document the parsing behavior and assure ourselves we are happy with it. [Some notes here.](https://github.com/rust-lang/rust/pull/93082#issuecomment-1027270291)

### Implementation history

- https://github.com/rust-lang/rust/pull/93582
